### DISCUSSION TITLE
How to create replication between two minio?

### DISCUSSION THREAD

**Discussion by zynpsnltrkk** [minio/minio#11861] [Q&A] [answered]
Hey, I have two minion setups running on the docker-compose. both of them have the same configuration. I am simply trying to replicate between two separate docker-compose and minio s running on separate VMS on AWS.
``` 
  minio:
    image: "RELEASE.2021-03-17T02-33-02Z"
    container_name: minio
    environment:
      MINIO_ACCESS_KEY: "minio"
      MINIO_SECRET_KEY: "minio123"
    ports:
      - "18050:18050"
    deploy:
      replicas: 1
    network_mode: "host"
    restart: always
    volumes:
      - "/opt/test/minio/disk0:/data/disk0"
        #    command: "gateway nas /data/disk0 --address :18050"
    command: "server /data/disk0 --address :18050"
```
I am following this documentation: https://github.com/minio/minio/blob/master/docs/bucket/replication/setup_replication.sh

when I create to version enabled bucket in that two minio s, I am getting that error
```
root@ip-x-x-x-x:/etc/test#  mc mb minio/velero --l --debug
mc: <DEBUG> PUT /velero/ HTTP/1.1
Host: 127.0.0.1:18050
User-Agent: MinIO (linux; amd64) minio-go/v7.0.11 mc/RELEASE.2021-03-23T05-46-11Z
Content-Length: 0
Authorization: AWS4-HMAC-SHA256 Credential=minio/20210323/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-bucket-object-lock-enabled;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Bucket-Object-Lock-Enabled: true
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20210323T124220Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 501 Not Implemented
Content-Length: 319
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Tue, 23 Mar 2021 12:42:20 GMT
Server: MinIO
Vary: Origin
X-Amz-Request-Id: 166EF9393EB7711B
X-Xss-Protection: 1; mode=block

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NotImplemented</Code><Message>A header you provided implies functionality that is not implemented</Message><BucketName>velero</BucketName><Resource>/velero/</Resource><RequestId>166EF9393EB7711B</RequestId><HostId>400cba47-5974-488f-8225-cbf07a11a294</HostId></Error>mc: <DEBUG> Response Time:  4.114582ms

mc: <ERROR> Unable to make bucket `minio/velero`. A header you provided implies functionality that is not implemented
 (1) mb-main.go:151 cmd.mainMakeBucket(..) Tags: [minio/velero]
 (0) client-s3.go:1247 cmd.(*S3Client).MakeBucket(..)
 Release-Tag:RELEASE.2021-03-23T05-46-11Z | Commit:c3cae160b35d | Host:ip-10-0-0-193 | OS:linux | Arch:amd64 | Lang:go1.16.2 | Mem:4.7 MB/75 MB | Heap:4.7 MB/67 MB
```
due to that error, I created non-versioned bucket and try to replicate it, I am getting that error
```
root@ip-x-x-x-x:/etc/test# mc admin bucket remote add minio/velero http://minio:minio123@ip:18050/velero --service replication --region minio --debug
mc: <DEBUG> PUT /minio/admin/v3/set-remote-target?bucket=velero HTTP/1.1
Host: 127.0.0.1:18050
User-Agent: MinIO (linux; amd64) madmin-go/0.0.1 mc/RELEASE.2021-03-23T05-46-11Z
Content-Length: 383
Authorization: AWS4-HMAC-SHA256 Credential=minio/20210323//s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e62889d9f8580f88886a19a89c5dada53150d3e177b070275691977f0973bf8b
X-Amz-Date: 20210323T124315Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 426 Upgrade Required
Content-Length: 224
Accept-Ranges: bytes
Content-Type: application/json
Date: Tue, 23 Mar 2021 12:43:15 GMT
Server: MinIO
Vary: Origin

{"Code":"XMinioAdminVersionMismatch","Message":"This 'admin' API is not supported by server in 'mode-server-fs'","Resource":"/minio/admin/v3/set-remote-target","RequestId":"","HostId":"400cba47-5974-488f-8225-cbf07a11a294"}
mc: <DEBUG> Response Time:  1.840053ms

mc: <ERROR> Unable to configure remote target. This 'admin' API is not supported by server in 'mode-server-fs'
 (1) admin-bucket-remote-add.go:264 cmd.mainAdminBucketRemoteAdd(..) Tags: [minio/velero, http://minio:lZPKemovi-E=0kjr7=bb22UF@54.93.48.36:18050/velero]
 (0) admin-bucket-remote-add.go:264 cmd.mainAdminBucketRemoteAdd(..)
 Release-Tag:RELEASE.2021-03-23T05-46-11Z | Commit:c3cae160b35d | Host:ip-10-0-0-193 | OS:linux | Arch:amd64 | Lang:go1.16.2 | Mem:69 MB/144 MB | Heap:69 MB/134 MB.
```
I also tried nas gateway but the same error came.

Is there any way to provide this replication?
