### DISCUSSION TITLE
Server not initialized error for minio cluster on distributed erasure mode

### DISCUSSION THREAD

**Discussion by zynpsnltrkk** [minio/minio#11927] [Q&A] [answered]
I have 3 minio working on separate VMS. I want these to work in a cluster. Below is the docker-compose configuration that I use for all 3 machines.
```
  minio:
    image: "minio/minio:RELEASE.2021-03-17T02-33-02Z"
    container_name: minio
    environment:
      MINIO_ACCESS_KEY: "minio"
      MINIO_SECRET_KEY: "minio123"
    deploy:
      replicas: 1
    network_mode: "host"
    restart: always
    volumes:
      - "/opt/test/minio:/data"
    **command: "server http://10.0.0.x/data/disk{0...5} http://10.0.0.y/data/disk{0...5} http://10.0.0.z/data/disk{0...5} --address :18050 "**
```
x, y, and z are not consecutive strings. That's why I couldn't use it http://10.0.0.{x...z}/data/disk{0...5} way.

I am getting the following error with this configuration
from one of the VMS
```
API: SYSTEM()
Time: 11:33:29 UTC 03/30/2021
Error: http://10.0.0.x:18050/data/disk0 as has incorrect configuration: Expected endpoint http://10.0.0.x/data/disk0, seen http://10.0.0.x:18050/data/disk0 (*fmt.wrapError)
       1: cmd/server-main.go:491:cmd.serverMain()
```

from the other two vms
```
Waiting for the first server to format the disks.
```

from UI
```
Server not initialized, please try again
```

What am I doing wrong with this configuration?

**Comment by klauspost** [comment, marked as answer]
You shouldn't mix ellipsis and non-ellipsis like this. You are creating 3 server pools and not a single pool.

Use dns names and make them consecutive so you can use a single parameter for each.

**Comment by zynpsnltrkk** [comment]
yep, thanks @klauspost 

I solved the problem with these configurations by adding dns

```
  minio:
    image: "minio/minio:RELEASE.2021-03-17T02-33-02Z"
    container_name: minio
    environment:
      MINIO_ACCESS_KEY: "minio"
      MINIO_SECRET_KEY: "minio123"
    deploy:
      replicas: 1
    network_mode: "host"
    restart: always
    volumes:
      - "/opt/rcplatform/minio:/data"
    command: "server http://primary-0{1...3}.test.io/data/disk{0...5} --address :18050 "
```
then the cluster is ready.
