### DISCUSSION TITLE
[resolved] Content hash does not match (drive issue)

### DISCUSSION THREAD

**Discussion by champds** [minio/minio#11988] [Q&A] [answered]
We're getting errors like such:
```bash
minio3_1  | API: SYSTEM()
minio3_1  | Time: 20:39:26 UTC 04/05/2021
minio3_1  | DeploymentID: 0ba4e256-4535-4c9a-a2d7-da9ef5ab2ff6
minio3_1  | Error: Disk: /data1  -> .minio.sys/buckets/vod-aub/.usage-cache.bin/c3f6a55c-b702-4861-af09-2dc9af419eb4/part.1 - content hash does not match - expected c44df0d48de2cd4e35de4daa7f79b6b5dea7869e9187a910e56bc7faee6d85e5, got 3c632569aa882fea6467645dd5beef850da2c5f0db961d78b9a0117e74365bcc (*errors.errorString)
minio3_1  |        2: /go/minio/cmd/bitrot-streaming.go:162:cmd.(*streamingBitrotReader).ReadAt()
minio3_1  |        1: /go/minio/cmd/erasure-decode.go:164:cmd.(*parallelReader).Read.func1()
minio3_1  | 
minio3_1  | API: SYSTEM()
minio3_1  | Time: 20:39:26 UTC 04/05/2021
minio3_1  | DeploymentID: 0ba4e256-4535-4c9a-a2d7-da9ef5ab2ff6
minio3_1  | Error: Disk: /data2  -> .minio.sys/buckets/vod-aub/.usage-cache.bin/c3f6a55c-b702-4861-af09-2dc9af419eb4/part.1 - content hash does not match - expected 64536590ebd850db669e801140adaaf0bdc7f49efa0e7ffe98cdb8499d721128, got 780e2ccfdb42cc784631583af9692e97bd44b6ceabf8c4f6a24e52c0b0fec259 (*errors.errorString)
minio3_1  |        2: /go/minio/cmd/bitrot-streaming.go:162:cmd.(*streamingBitrotReader).ReadAt()
minio3_1  |        1: /go/minio/cmd/erasure-decode.go:164:cmd.(*parallelReader).Read.func1()
minio3_1  | 
minio3_1  | API: SYSTEM()
minio3_1  | Time: 20:39:26 UTC 04/05/2021
minio3_1  | DeploymentID: 0ba4e256-4535-4c9a-a2d7-da9ef5ab2ff6
minio3_1  | Error: Disk: http://minio1:9009/data2  -> .minio.sys/buckets/vod-aub/.usage-cache.bin/c3f6a55c-b702-4861-af09-2dc9af419eb4/part.1 - content hash does not match - expected db59a23831f85f5c592f9b01c9017ec42e358230af86ca509d520cccf281cddc, got 5aba8c0e26244c9f74a9306eff9175530de0d1a7c358b483daa93e53f04331af (*errors.errorString)
minio3_1  |        2: /go/minio/cmd/bitrot-streaming.go:162:cmd.(*streamingBitrotReader).ReadAt()
minio3_1  |        1: /go/minio/cmd/erasure-decode.go:164:cmd.(*parallelReader).Read.func1()
```

We have three minio instances on three separate physical devices.  Each has /data1 and /data2.  When we restart the entire cluster, this error pops up on various different hosts (but it seems always on the same host per stop/start).  That is, it's always one host complaining about itself and one other host.  

The question is how to determine the issue here and/or recover from it.  We noted this after some time with a test deployment, and wiped all drives and started fresh.  After some time, these same errors keep popping up.  It does not seem to affect performance, etc, but we'd like to know more, if anyone knows.

## Expected Behavior
Not sure what expected behavior should be here.  Nor how to debug / recover from this.

## Steps to Reproduce (for bugs)
Three separate "latest" minio docker images, 2 drives each.

**Comment by harshavardhana** [comment]
You can simply remove the usage-cache.bin path on all drives. This should never happen unless you have some drive issue or the drives are going to go bad that they are bit-rotted

**Comment by champds** [comment]
Thanks @harshavardhana - we have some more detail that may help - here's the excerpt from the compose file:

This works just fine w/ no issues:
```yml
...
command: server --address :9009 http://minio{1...3}:9009/data{1...2}
...
```

However, when we add drives to a new pool (new drives /data3 and /data4 on existing machines):
```yml
...
command: server --address :9009 http://minio{1...3}:9009/data{1...2} http://minio{1...3}:9009/data{3...4}
...
```
...this is when the errors start creeping up (but on /data1 and /data2, curiously)

Is this the correct way to expand or should we have been adding drives via
```yml
...
command: server --address :9009 http://minio{1...3}:9009/data{1...4}
...
```
Thanks so much for the help here.

**Comment by harshavardhana** [comment]
This is correct way to expand, I will try to reproduce this.

**Comment by harshavardhana** [comment]
@champds so I used latest master `minio/minio:edge` - and do not see any error - would you mind trying minio/minio:edge - NOTE: once upgraded you cannot downgrade from master anymore.  So if you have data then please be mindful of such updates.

Here are my compose.yml files - tried all combinations starting with all disks

```
command: server --address :9009 http://minio{1...3}:9009/data{1...2}
```

and 

```
command: server --address :9009 http://minio{1...3}:9009/data{1...2} http://minio{1...3}:9009/data{3...4}
```

```yaml
version: '3.7'        
                                               
# starts 4 docker containers running minio server instances.
# using nginx reverse proxy, load balancing, you can access
# it through port 9000.
services:     
  minio1:       
    image: y4m4/minio:dev   
    volumes:                       
      - data1-1:/data1                                                                         
      - data1-2:/data2
      - data1-3:/data3                                                                         
      - data1-4:/data4
    expose:       
      - "9000"  
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server http://minio{1...3}/data{1...2} http://minio{1...3}/data{3...4}
    healthcheck:                             
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
                                               
  minio2:     
    image: y4m4/minio:dev
    volumes:                                                                                   
      - data2-1:/data1                                                                         
      - data2-2:/data2
      - data2-3:/data3
      - data2-4:/data4
    expose:
      - "9000"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server http://minio{1...3}/data{1...2} http://minio{1...3}/data{3...4}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
                                                                                                                                                                                              
  minio3:                       
    image: y4m4/minio:dev
    volumes:
      - data3-1:/data1
      - data3-2:/data2
      - data3-3:/data3
      - data3-4:/data4
    expose:
      - "9000"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server http://minio{1...3}/data{1...2} http://minio{1...3}/data{3...4}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  nginx:
    image: nginx:1.19.2-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
    depends_on:
      - minio1
      - minio2
      - minio3

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  data1-1:
  data1-2:
  data2-1:
  data2-2:
  data3-1:
  data3-2:
  data1-3:
  data1-4:
  data2-3:
  data2-4:
  data3-3:
  data3-4:

```
