### DISCUSSION TITLE
Error enabling prometheus servicemonitor with minio-operator

### DISCUSSION THREAD

**Discussion by mymasse** [minio/minio#12408] [Q&A]
Hello, I'm deploying MinIO using the minio-operator in K8S with the helm chart version 4.1.0, 

I'm trying to enable the prometheus service monitor and keep running into issues. In the Operator Console it always reports `Provisioning Prometheus service monitor for Prometheus metrics feature`. Checking the operator logs I get `error syncing 'minio/tenant': servicemonitors.monitoring.coreos.com "tenant-prometheus" already exists` and yes the service monitor does indeed exist but I'm not getting any metrics in prometheus itself.

Here is the Tenant I'm deploying

```yaml
---
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: tenant
  namespace: minio
  annotations:
    prometheus.io/path: /minio/prometheus/metrics
    prometheus.io/port: "9000"
    prometheus.io/scrape: "true"
spec:
  credsSecret:
    name: minio-secret
  requestAutoCert: false
  podManagementPolicy: Parallel
  pools:
    - servers: 4
      volumesPerServer: 1
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          storageClassName: default
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
  console:
    replicas: 1
    consoleSecret:
      name: minio-console-secret
  exposeServices:
    minio: false
    console: false
  prometheusOperator: {}
```
