### DISCUSSION TITLE
STS setup with Auth0

### DISCUSSION THREAD

**Discussion by VinceAdamo** [minio/minio#12555] [Q&A] [answered]
I am trying to setup minio sts with auth0 and client grants but when I try to retrieve temporary credentials from the minio server I receive the following error: 
```
?xml version="1.0" encoding="UTF-8"?>
<ErrorResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/">
    <Error>
        <Type></Type>
        <Code>STSNotInitialized</Code>
        <Message>Server not initialized, please try again</Message>
    </Error>
    <RequestId>168B0B8032FF6C48</RequestId>
</ErrorResponse>
``` 

I was just wondering why this is happening? Thanks

**Comment by harshavardhana** [comment, marked as answer]
Because you haven't setup MinIO with CLIENT_ID and IDP configuration

**Reply by VinceAdamo** [reply]
I have set MINIO_IDENTITY_OPENID_CONFIG_URL= `https://my-auth0-domain/.well-known/openid-configuration`, and I have set MINIO_IDENTITY_OPENID_CLIENT_ID to the ID of an application on Auth0, is this not enough?

**Reply by harshavardhana** [reply]
> I have set MINIO_IDENTITY_OPENID_CONFIG_URL= https:///.well-known/openid-configuration, and I have set MINIO_IDENTITY_OPENID_CLIENT_ID to the ID of an application on Auth0, is this not enough?

The URL looks wrong here.

**Reply by VinceAdamo** [reply]
Sorry typo, the URL I used is `https://my-auth0-domain/.well-known/openid-configuration`

**Reply by harshavardhana** [reply]
are you using gateway? @VinceAdamo

**Reply by VinceAdamo** [reply]
No, I’m not. I’m running minio server locally with docker.

**Reply by harshavardhana** [reply]
> No, I’m not. I’m running minio server locally with docker.

can you show me your command line and how are you passing the ENVs?

**Reply by VinceAdamo** [reply]
I'm using nginx reverse proxy with 4 minio server instances. Starting it up with docker-compose file and passing a .env file to set the variables. My docker compose file looks like this: 
```
version: '3.7'

# starts 4 docker containers running minio server instances.
# using nginx reverse proxy, load balancing, you can access
# it through port 9000.
services:
  minio1:
    image: minio/minio
    volumes:
      - data1-1:/data1
      - data1-2:/data2
    expose:
      - "9000"
    env_file: ../.env.minio
    command: server http://minio{1...4}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio2:
    image: minio/minio
    volumes:
      - data2-1:/data1
      - data2-2:/data2
    expose:
      - "9000"
    env_file: ../.env.minio
    command: server http://minio{1...4}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio3:
    image: minio/minio
    volumes:
      - data3-1:/data1
      - data3-2:/data2
    expose:
      - "9000"
    env_file: ../.env.minio
    command: server http://minio{1...4}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio4:
    image: minio/minio
    volumes:
      - data4-1:/data1
      - data4-2:/data2
    expose:
      - "9000"
    env_file: ../.env.minio
    command: server http://minio{1...4}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  nginx:
    image: nginx
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  data1-1:
  data1-2:
  data2-1:
  data2-2:
  data3-1:
  data3-2:
  data4-1:
  data4-2:
```

My .env file looks like this:
```
MINIO_ROOT_USER=minio
MINIO_ROOT_PASSWORD=minio123
MINIO_IDENTITY_OPENID_CONFIG_URL=https://my-auth0-domain/.well-known/openid-configuration
MINIO_IDENTITY_OPENID_CLIENT_ID=my-client-id
MINIO_IDENTITY_OPENID_CLAIM_NAME=https://my-auth0-domain/minio/policy
```
