### DISCUSSION TITLE
The default accessKey and secretKey counter with "unauthorized" error

### DISCUSSION THREAD

**Discussion by sunsdy2018** [minio/minio#12674] [Q&A] [answered]
My OS is Windows 10.

The version of minio.exe is：
![image](https://user-images.githubusercontent.com/38706610/125055722-184b1c00-e0da-11eb-920e-4368dc1dc3bc.png)

Use the following command to start minio.exe:
![image](https://user-images.githubusercontent.com/38706610/125055829-331d9080-e0da-11eb-9347-1955c9b5344c.png)

Open the browser and access the url using the default accessKey and secretKey as follows:
![image](https://user-images.githubusercontent.com/38706610/125056015-66601f80-e0da-11eb-9a4b-8b1c7aabce9d.png)

**Comment by klauspost** [comment, marked as answer]
I cannot reproduce on Win 10 + minio version `RELEASE.2021-07-08T19-43-25Z`:

![image](https://user-images.githubusercontent.com/5663952/125060339-8f69bb80-e0ac-11eb-9753-d94833ce7e20.png)

![image](https://user-images.githubusercontent.com/5663952/125060647-de175580-e0ac-11eb-9d59-6e1ef024c41e.png)

**Comment by harshavardhana** [comment]
Seems to be working as intended as well across platforms @sunsdy2018 - would be able to provide more information?

**Comment by MickL** [comment]
I do have the same problem using the latest version and Docker Compose, i tried:

```
version: "3"
services:
  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - 'minio_data:/data'
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_REGION_NAME: 'eu-central-1'
    command: minio server --console-address ":9001" /data

volumes:
  minio_data:
    driver: local
```

But I cant login into console. It even says:

> WARNING: Detected default credentials 'minioadmin:minioadmin', we recommend that you change these values with 'MINIO_ROOT_USER' and 'MINIO_ROOT_PASSWORD' environment variables

But then still:

> minio_1  | API: AssumeRole()
> minio_1  | Time: 18:24:27 UTC 07/15/2021
> minio_1  | DeploymentID: 7c3a26e2-1825-48b3-b009-56d2bb34f35d
> minio_1  | RequestID: 16920A0D3D763E1C
> minio_1  | RemoteHost: 172.22.0.2
> minio_1  | Host: 172.22.0.2:9000
> minio_1  | UserAgent: Go-http-client/1.1
> minio_1  | Error: specified policy consoleAdmin, not found Specified canned policy does not exist (*fmt.wrapError)
> minio_1  |        3: cmd/sts-errors.go:58:cmd.writeSTSErrorResponse()
> minio_1  |        2: cmd/sts-handlers.go:250:cmd.(*stsAPIHandlers).AssumeRole()
> minio_1  |        1: net/http/server.go:2069:http.HandlerFunc.ServeHTTP()
> minio_1  | original error -> (user_login.go:50: invalid Login)
> minio_1  | debugging error: 400 Bad Request

I do have some errors when starting up, tho:

> minio_1  | Error: Unable to initialize sub-systems: Unable to migrate all config at .minio.sys/config/: Decrypting config failed sio: data is not authentic, possibly credentials are incorrect (*fmt.wrapError)
> minio_1  |        1: cmd/server-main.go:558:cmd.serverMain()
> minio_1  | Server startup failed with 'Unable to initialize sub-systems: Unable to migrate all config at .minio.sys/config/: Decrypting config failed sio: data is not authentic, possibly credentials are incorrect'
> minio_1  | Not all features may be available on this server
> minio_1  | Please use 'mc admin' commands to further investigate this issue
> minio_1  | API: http://172.22.0.2:9000  http://127.0.0.1:9000 
>

**Reply by harshavardhana** [reply]
> minio_1 | API: AssumeRole()
> minio_1 | Time: 18:24:27 UTC 07/15/2021
> minio_1 | DeploymentID: 7c3a26e2-1825-48b3-b009-56d2bb34f35d
> minio_1 | RequestID: 16920A0D3D763E1C
> minio_1 | RemoteHost: 172.22.0.2
> minio_1 | Host: 172.22.0.2:9000
> minio_1 | UserAgent: Go-http-client/1.1
> minio_1 | Error: specified policy consoleAdmin, not found Specified canned policy does not exist (*fmt.wrapError)

not sure why would you know have this policy because this is default and should always be present,  can you share more logs from the container from the beginning?

**Reply by MickL** [reply]
I just added an error that occurs on startup

**Reply by harshavardhana** [reply]
I just ran locally it works fine @MickL 

```
version: "3"
services:
  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - 'minio_data:/data'
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_REGION_NAME: 'eu-central-1'
    command: minio server --console-address ":9001" /data

volumes:
  minio_data:
    driver: local
```
![browser](https://user-images.githubusercontent.com/622699/125839046-56c4df14-1475-4c60-bd60-781299fd413a.png)

```
docker-compose -f /tmp/t.yaml up
WARNING: The Docker Engine you're using is running in swarm mode.

Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.

To deploy your application across the swarm, use `docker stack deploy`.

Starting tmp_minio_1_de21c55c0249 ... done
Attaching to tmp_minio_1_de21c55c0249
minio_1_de21c55c0249 | WARNING: MINIO_ACCESS_KEY and MINIO_SECRET_KEY are deprecated.
minio_1_de21c55c0249 |          Please use MINIO_ROOT_USER and MINIO_ROOT_PASSWORD
minio_1_de21c55c0249 | API: http://172.27.0.2:9000  http://127.0.0.1:9000 
minio_1_de21c55c0249 | 
minio_1_de21c55c0249 | Console: http://172.27.0.2:9001 http://127.0.0.1:9001 
minio_1_de21c55c0249 | 
minio_1_de21c55c0249 | Documentation: https://docs.min.io
minio_1_de21c55c0249 | WARNING: Detected default credentials 'minioadmin:minioadmin', we recommend that you change these values with 'MINIO_ROOT_USER' and 'MINIO_ROOT_PASSWORD' environment variables
```
