### DISCUSSION TITLE
problem when using the latest version with AWS sdk or cli (return a 503)

### DISCUSSION THREAD

**Discussion by cstmgl** [minio/minio#12712] [Q&A]
Updating my post since I understood a bit better the problem.

hi All,
I'm updating my version from release 2021-04-06T23-11-00Z to 2021-07-12T02-44-53Z
I noticed there are some differences in the console and also how the ports are used between console and API and I'm trying to understand how this works.

Anyway I'm running MinIO in kubernetes (openshift actually) and I'm accessing MinIO over a route and this always fails when using the AWS SDK.
Using the minio cli it works fine even over the route. Using the AWS SDK and accessing the server directly also works, just somehow the route does not work with the AWS cli.

I thought the original problem was about the redirect from the API port to the console port but that is just something that happens on the browser.

I was wondering if something changed in how this is managed and if there is any example of how I can define my routes so that I can access the API and do my calls with the sdk (I'm using the amazon sdk btw)

thanks for any tips of what the problem might be.

**Comment by cstmgl** [comment]
it might be related to https://github.com/minio/minio/discussions/12684 and the https://github.com/minio/minio#test-minio-connectivity even though I must say I do not know what value I should define in my default redirect.
Or actually can I somehow disable the default redirect to the console? I would like to do that implicitly in the route

**Reply by harshavardhana** [reply]
S3 API should not redirect

**Reply by cstmgl** [reply]
this is my statefulset:
```
      containers:
        - name: minio
          image: minio/minio:RELEASE.2021-07-08T19-43-25Z
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh"]
          args:
            - -c
            - /opt/script/init-script.sh
          volumeMounts:
            - name: export
              mountPath: /export
            - name: script
              mountPath: /opt/script
          ports:
            - name: api
              containerPort: 9000
            - name: console
              containerPort: 9001

```

my init-script is something like this: 
```
/usr/bin/docker-entrypoint.sh minio -S /etc/minio/certs/ server /export --address ":9000" --console-address ":9001" ;
```

my service:
```
apiVersion: v1
kind: Service
metadata:
  name: minio-server-svc
  labels:
    app.kubernetes.io/component: business-service
spec:
  type: ClusterIP
  ports:
    - name: api
      port: 9000
      protocol: TCP
      targetPort: 9000
    - name: console
      port: 9001
      protocol: TCP
      targetPort: 9001

# Workaround needed to trick MinIO during the node discovery process
apiVersion: v1
kind: Service
metadata:
  name: minio-headless-svc
  labels:
    app.kubernetes.io/component: business-service
spec:
  # If all the nodes have the same IP, MinIO fails
  clusterIP: None
  ports:
    - name: api
      port: 9000
      protocol: TCP
      targetPort: 9000
    - name: console
      port: 9001
      protocol: TCP
      targetPort: 9001
```

and my routes:
```
apiVersion: v1
kind: Route
metadata:
  name: minio-console
  labels:
    app.kubernetes.io/component: business-service
spec:
  port:
    targetPort: console
  tls:
    termination: edge
  to:
    kind: Service
    name: minio-server-svc
    weight: 100
  wildcardPolicy: None  
---
apiVersion: v1
kind: Route
metadata:
  name: minio-api
  labels:
    app.kubernetes.io/component: business-service
spec:
  port:
    targetPort: api
  tls:
    termination: edge
  to:
    kind: Service
    name: minio-server-svc
    weight: 100
  wildcardPolicy: None
```

just for reference I'm using minio to simulate the aws s3 in my developments but I think with this new version where we have the 2 services somehow I can't make it work and every access to the api port goes redirected to the console port

any idea something that might be completely wrong? I really don't get it, I can access the console without any problems and navigate the buckets and things just the API service I can't find a way to use it
