### DISCUSSION TITLE
When do hostnames cached by the distributed server process expire?

### DISCUSSION THREAD

**Discussion by funkypenguin** [minio/minio#12745] [Q&A] [answered]
Hey guys!

I'm using the latest bitnami image/chart, to run Minio in distributed mode as a statefulset in Kubernetes. The statefulset runs the minio server with the `MINIO_DISTRIBUTED_NODES` env var correctly set to reference the 4 members of my statefulset:

```
MINIO_DISTRIBUTED_NODES:         minio-{0...3}.minio-headless.preview-minio-pr-110.svc.cluster.local/data
```

Our environment is heavily locked down, such that I have a NetworkPolicy which permits connection between the minio pods on port 9000, based on their label (`app.kubernetes.io/name=minio`)

I've noticed blocked attempts by the minio pods to connect to IPs which _in the past_ used to be the IPs of the minio pods. I.e., I update the statefulset, and the rollout restarts pods, one-at-a-time.

What seems to happen though, is that it can take ~30s for coredns to remove the old DNS entry for one of the pods from its cache - if another pod starts up and receives "bad" data from coredns re the IPs of its distributed nodes, it **continuously** attempts to connect to that node. I.e., there's no expiry and re-lookup of the hostname from DNS. 

For illustration's sake, these pods were restarted _hours_ ago, but are still attempting to connect to the old (and by now, well-expired) IPs of their neighbors in the statefulset:

![image](https://user-images.githubusercontent.com/1524686/126108400-1dafd7c7-80f9-4dd4-8e2a-fd2c1a636dea.png)

## Expected Behavior

Minio should re-lookup the IPs of distributed nodes at a (configurable?) interval, to avoid stale DNS causing problems between the distributed nodes.

## Current Behavior

Minio appears to never re-refresh the IPs of the addresses in the `MINIO_DISTRIBUTED_NODES` env var

## Possible Solution

As above, especially when unable to connect to a distributed node peer, force a refresh of the peer's IP from DNS

## Steps to Reproduce (for bugs)

1. Deploy a distributed install using a statefulset
2. Apply networkpolicy to permit minio-to-minio communication only (sample below, subset of full manifests, also includes policy to permit DNS resolution)

```
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: minio
    ports:
    - port: 9000
      protocol: TCP
  podSelector:
    matchLabels:
      app.kubernetes.io/name: minio
  policyTypes:
  - Ingress
---
spec:
  egress:
  - ports:
    - port: 9000
      protocol: TCP
    to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: minio
  podSelector:
    matchLabels:
      app.kubernetes.io/name: minio
  policyTypes:
  - Egress
---
spec:
  egress:
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
    to:
    - namespaceSelector:
        matchLabels:
          name: kube-system
  podSelector: {}
  policyTypes:
  - Egress
```

3. Apply process to report on policy-dropped packets (I used Hubble with Cilium for quick visibility)

## Context

Our CI platform deploys fresh namespaces with Minio distributed clusters routinely. When a cluster deploy fails for some reason (for example, an error which causes the pods to crashloop), subsequent (correct) deploys can also fail, since the "old" IPs of the minio pods are served by DNS (within 30s) to the freshly-deployed pods.

## Regression

No

## Your Environment

* Version used (`minio --version`): `minio version DEVELOPMENT.2021-06-18T09-39-33Z`
* Server setup and configuration: Kubernetes 1.20.6, installed on bare-metal with kubeadm
* Operating System and version (`uname -a`): Ubunte 20.04 as a Kubernetes node base OS
