### DISCUSSION TITLE
Console Login Failed for GCS Gateway

### DISCUSSION THREAD

**Discussion by fairyhunter13** [minio/minio#13085] [Q&A] [answered]
I tried to set up a Minio gateway for connecting to GCS but my attempts were failed.

# Configuration

**docker-compose.yml**: 
```yaml
version: '3'
services:
  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: rootpass
      MINIO_REGION_NAME: asia-southeast2
      GOOGLE_APPLICATION_CREDENTIALS: "/credentials.json"
    command: gateway gcs central-diode-286607 --console-address ":9001"
    # command: server /data/minio --console-address ":9001"
    volumes:
      - "./credentials.json:/credentials.json"
    ports:
      - "9000:9000"
      - "9001:9001"
```

# Output Result
- Docker Machine IP
![image](https://user-images.githubusercontent.com/12372147/131071226-c906c157-d110-49d9-87a2-b3c8cb8b7a5d.png)

- Running with `docker-compose`:
![image](https://user-images.githubusercontent.com/12372147/131070913-c60b0c70-f837-401f-a9c5-dd0aa04f92ab.png)

- Failed Login Attempt
![image](https://user-images.githubusercontent.com/12372147/131071006-498d045b-f0ac-4449-8b4b-cc866f2b017f.png)

- Request and Response
![image](https://user-images.githubusercontent.com/12372147/131071062-87059876-c2fd-42ac-b311-bfb06dfd6f87.png)
![image](https://user-images.githubusercontent.com/12372147/131071085-29228b59-0b57-475f-b409-3e594a99f766.png)

Could someone please help me?

**Comment by harshavardhana** [comment]
> I tried to set up a Minio gateway for connecting to GCS but my attempts were failed.
> 
> # Configuration
> **docker-compose.yml**:
> 
> ```yaml
> version: '3'
> services:
>   minio:
>     image: minio/minio
>     environment:
>       MINIO_ROOT_USER: root
>       MINIO_ROOT_PASSWORD: rootpass
>       MINIO_REGION_NAME: asia-southeast2
>       GOOGLE_APPLICATION_CREDENTIALS: "/credentials.json"
>     command: gateway gcs central-diode-286607 --console-address ":9001"
>     # command: server /data/minio --console-address ":9001"
>     volumes:
>       - "./credentials.json:/credentials.json"
>     ports:
>       - "9000:9000"
>       - "9001:9001"
> ```
> 
> # Output Result
> * Docker Machine IP
>   ![image](https://user-images.githubusercontent.com/12372147/131071226-c906c157-d110-49d9-87a2-b3c8cb8b7a5d.png)
> * Running with `docker-compose`:
>   ![image](https://user-images.githubusercontent.com/12372147/131070913-c60b0c70-f837-401f-a9c5-dd0aa04f92ab.png)
> * Failed Login Attempt
>   ![image](https://user-images.githubusercontent.com/12372147/131071006-498d045b-f0ac-4449-8b4b-cc866f2b017f.png)
> * Request and Response
>   ![image](https://user-images.githubusercontent.com/12372147/131071062-87059876-c2fd-42ac-b311-bfb06dfd6f87.png)
>   ![image](https://user-images.githubusercontent.com/12372147/131071085-29228b59-0b57-475f-b409-3e594a99f766.png)
> 
> Could someone please help me?

Please pull `docker pull minio/minio`

**Reply by fairyhunter13** [reply]
@harshavardhana Wait, let me try it again.

**Reply by fairyhunter13** [reply]
@harshavardhana The problem still persists.

# Output Result:
![image](https://user-images.githubusercontent.com/12372147/131086924-7f3a4bfb-edb0-482e-bd36-b901a024ff19.png)
![image](https://user-images.githubusercontent.com/12372147/131087031-e2f26345-8fd4-413c-8ca6-f6170688f7de.png)
![image](https://user-images.githubusercontent.com/12372147/131087094-09256217-9288-409a-951b-425306df7837.png)

**Reply by fairyhunter13** [reply]
@harshavardhana Is my configuration really wrong? Do you have any working examples for the GCS gateway? Since when I tried to serve the actual directory, it's really working.

# For Example

This is an example of serving the actual directory.

## Configuration

**docker-compose.yml**:
```yaml
version: '3'
services:
  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: rootpass
      MINIO_REGION_NAME: asia-southeast2
      GOOGLE_APPLICATION_CREDENTIALS: "/credentials.json"
    # command: gateway gcs central-diode-286607 --console-address ":9001"
    command: server /data/minio --console-address ":9001"
    volumes:
      - "./credentials.json:/credentials.json"
    ports:
      - "9000:9000"
      - "9001:9001"
```

## Output Result

- Running with `docker-compose`:
![image](https://user-images.githubusercontent.com/12372147/131087705-ede97fc9-1411-4b32-ad95-c319c5eb4793.png)

- Request and Response:
![image](https://user-images.githubusercontent.com/12372147/131087843-3ff74bc5-fb33-47a2-8f7b-96b48f7d79f0.png)
![image](https://user-images.githubusercontent.com/12372147/131087902-0c747383-3d9e-4e67-9a80-32f54ec76f8d.png)

- Browser:
![image](https://user-images.githubusercontent.com/12372147/131088007-f1da022f-5faa-426c-a251-ae5561e5494a.png)
