### DISCUSSION TITLE
Unable to read 'format.json' Server expects 'storage' API version 'v39', instead found 'v39'

### DISCUSSION THREAD

**Discussion by northway** [minio/minio#13287] [Q&A] [answered]
Hi! I’m about to setup a 4 node distributed setup over the local network with the following command:

```bash
server http://192.168.53.10{1...4}/data{1...2} --console-address ":9002" --address ":9001"
```

After staring the containers, I get this looping error message:

```
Unable to read 'format.json' from http://192.168.53.101:9001/data1: Server expects 'storage' API version 'v39', instead found 'v39' - *rolling upgrade is not allowed* - please make sure all servers are running the same MinIO version (RELEASE.2021-09-18T18-09-59Z)

Unable to read 'format.json' from http://192.168.53.102:9001/data1: Server expects 'storage' API version 'v39', instead found 'v39' - *rolling upgrade is not allowed* - please make sure all servers are running the same MinIO version (RELEASE.2021-09-18T18-09-59Z)

Unable to read 'format.json' from http://192.168.53.103:9001/data1: Server expects 'storage' API version 'v39', instead found 'v39' - *rolling upgrade is not allowed* - please make sure all servers are running the same MinIO version (RELEASE.2021-09-18T18-09-59Z)

Unable to read 'format.json' from http://192.168.53.104:9001/data1: Server expects 'storage' API version 'v39', instead found 'v39' - *rolling upgrade is not allowed* - please make sure all servers are running the same MinIO version (RELEASE.2021-09-18T18-09-59Z)

Unable to read 'format.json' from http://192.168.53.101:9001/data2: Server expects 'storage' API version 'v39', instead found 'v39' - *rolling upgrade is not allowed* - please make sure all servers are running the same MinIO version (RELEASE.2021-09-18T18-09-59Z)

Unable to read 'format.json' from http://192.168.53.102:9001/data2: Server expects 'storage' API version 'v39', instead found 'v39' - *rolling upgrade is not allowed* - please make sure all servers are running the same MinIO version (RELEASE.2021-09-18T18-09-59Z)

Unable to read 'format.json' from http://192.168.53.103:9001/data2: Server expects 'storage' API version 'v39', instead found 'v39' - *rolling upgrade is not allowed* - please make sure all servers are running the same MinIO version (RELEASE.2021-09-18T18-09-59Z)

Unable to read 'format.json' from http://192.168.53.104:9001/data2: Server expects 'storage' API version 'v39', instead found 'v39' - *rolling upgrade is not allowed* - please make sure all servers are running the same MinIO version (RELEASE.2021-09-18T18-09-59Z)
```

* No TLS
* The disks are writeble (checked)
* The network has no firewall (checked)
* The containers can see each other (checked)

What am I missing?

This is my full ansible task:

```yaml
- name: Start the minio container
  community.general.docker_container:
    name: "{{ minio_standard.name }}"
    image: "{{ minio_standard.image_tag }}"
    container_default_behavior: compatibility
    state: started
    recreate: yes
    restart_policy: always
    network_mode: default
    networks:
      - name: "{{ minio_standard.network }}"
        ipv4_address: 172.18.0.2
    networks_cli_compatible: yes
    ports:
      - "9001:9001/tcp"
      - "9002:9002/tcp"
    env:
      TZ: "Europe/Budapest"
      MINIO_ROOT_USER: "{{ minio_standard.root_user }}"
      MINIO_ROOT_PASSWORD: "{{ minio_standard.root_password }}"
      MINIO_REGION_NAME: "{{ minio_standard.region_name }}"
    volumes:
      - "/srv/minio/einfra/standard/data1:/data1:rw"
      - "/srv/minio/einfra/standard/data2:/data2:rw"
    command: 
      - |
          server http://192.168.53.10{1...4}:9001/data{1...2} --console-address ":9002" --address ":9001"
    command_handling: compatibility
    healthcheck:
      test: ["CMD", "curl", "--fail", "-k", "http://{{ minio_standard.name }}:9001/minio/health/live"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 120s
    log_driver: json-file
    log_options:
      max-file: "2"
      max-size: "1m"
```

**Comment by harshavardhana** [comment, marked as answer]
> ```shell
> ```shell
> server http://192.168.53.10{1...4}/data{1...2} --console-address ":9002" --address ":9001"
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> ```

Make sure this IP belongs to all the container that is running - you cannot use any random IPs that do not belong to the container POD.  MinIO needs to know which node is owner of the drives to expose them over the network.

**Comment by northway** [comment]
Well, I'm a little bit confused.

> Make sure this IP belongs to all the container that is running - you cannot use any random IPs that do not belong to the container POD. MinIO needs to know which node is owner of the drives to expose them over the network.

Not using random address. I have a very similar working setup. The main difference is the server addresses, FQDN vs. IP address. In both cases, the VM's are running a stateless docker (no swarm, no k8s).

Based on your answer, I tought the problem is that I'm not using FQDN's. So I added local IP address to DNS records and used it as a server command:

```bash
http://node-{1...4}.test.s3.domain.com:9001/data{1...2}
```

The `node-{1...4}.test.s3.domain.com` records are resolving to their own IP address `http://192.168.53.10{1...4}`, but I'm getting the same error message

```
Unable to read 'format.json' from http://node-1.test.s3.domain.com:9001/data1: Server expects 'storage' API version 'v39', instead found 'v39' - *rolling upgrade is not allowed* - please make sure all servers are running the same MinIO version (RELEASE.2021-09-18T18-09-59Z)

Unable to read 'format.json' from http://node-2.test.s3.domain.com:9001/data1: Server expects 'storage' API version 'v39', instead found 'v39' - *rolling upgrade is not allowed* - please make sure all servers are running the same MinIO version (RELEASE.2021-09-18T18-09-59Z)

Unable to read 'format.json' from http://node-3.test.s3.domain.com:9001/data1: Server expects 'storage' API version 'v39', instead found 'v39' - *rolling upgrade is not allowed* - please make sure all servers are running the same MinIO version (RELEASE.2021-09-18T18-09-59Z)

Unable to read 'format.json' from http://node-4.test.s3.domain.com:9001/data1: Server expects 'storage' API version 'v39', instead found 'v39' - *rolling upgrade is not allowed* - please make sure all servers are running the same MinIO version (RELEASE.2021-09-18T18-09-59Z)

Unable to read 'format.json' from http://node-1.test.s3.domain.com:9001/data2: Server expects 'storage' API version 'v39', instead found 'v39' - *rolling upgrade is not allowed* - please make sure all servers are running the same MinIO version (RELEASE.2021-09-18T18-09-59Z)

Unable to read 'format.json' from http://node-2.test.s3.domain.com:9001/data2: Server expects 'storage' API version 'v39', instead found 'v39' - *rolling upgrade is not allowed* - please make sure all servers are running the same MinIO version (RELEASE.2021-09-18T18-09-59Z)

Unable to read 'format.json' from http://node-3.test.s3.domain.com:9001/data2: Server expects 'storage' API version 'v39', instead found 'v39' - *rolling upgrade is not allowed* - please make sure all servers are running the same MinIO version (RELEASE.2021-09-18T18-09-59Z)

Unable to read 'format.json' from http://node-4.test.s3.domain.com:9001/data2: Server expects 'storage' API version 'v39', instead found 'v39' - *rolling upgrade is not allowed* - please make sure all servers are running the same MinIO version (RELEASE.2021-09-18T18-09-59Z)
```

This is my other **working** deployment. Here the domains are resolving to a public IP address instead of a private IP address.

```yaml
- name: Start the minio container
  community.general.docker_container:
    name: "{{ minio_standard.name }}"
    image: "{{ minio_standard.image_tag }}"
    container_default_behavior: compatibility
    state: started
    recreate: yes
    restart_policy: always
    network_mode: default
    hostname: "{{ inventory_hostname }}"
    networks:
      - name: "{{ minio_standard.network }}"
        ipv4_address: 172.18.0.2
    networks_cli_compatible: yes
    ports:
      - "9001:9001/tcp"
      - "9002:9002/tcp"
    env:
      TZ: "Europe/Budapest"
      MINIO_ROOT_USER: "{{ minio_standard.root_user }}"
      MINIO_ROOT_PASSWORD: "{{ minio_standard.root_password }}"
      MINIO_REGION_NAME: "{{ minio_standard.region_name }}"
      HOST_HOSTNAME: "{{ inventory_hostname }}"
      MINIO_SERVER_URL: "{{ minio_standard.server_url }}"
      MINIO_BROWSER_REDIRECT_URL: "{{ minio_standard.browser_redirect_url }}"
      MINIO_STORAGE_CLASS_STANDARD: "8"
    volumes:
      - "/srv/minio/einfra/standard/data1:/data1:rw"
      - "/srv/minio/einfra/standard/data2:/data2:rw"
      - "{{ minio_standard.server_cert }}:/root/.minio/certs"
    command: 
      - |
          server https://node-{1...8}.dev.s3.domain.com:9001/data{1...2} --console-address ":9002" --address ":9001"
    command_handling: compatibility
    healthcheck:
      test: ["CMD", "curl", "--fail", "-k", "https://{{ minio_standard.name }}:9001/minio/health/live"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 120s
    log_driver: json-file
    log_options:
      max-file: "2"
      max-size: "1m"
```

Can you please explain why MinIO gets confused when I'm using private IP addresses?
