### DISCUSSION TITLE
MinIO S3 gateway server/console behind Nginx Kubernetes ingress returns 401 (console /api/v1/session)

### DISCUSSION THREAD

**Discussion by danilopeixoto** [minio/minio#13283] [Q&A]
I'm using Bitnami Minio Helm Chart to deploy MinIO S3 gateway but I can't login to the console.
MinIO server and console are behind Nginx Kubernetes ingress. The reverse proxies enable TLS certificate (`*.domain.com`) and HTTP/2.

* `:9000` -> `storage.domain.com` (server ingress)
* `:9001` -> `s3.domain.com` (console ingress)

I set up the following environment variables:

* MINIO_SERVER_URL: https://storage.domain.dell.com
* MINIO_BROWSER_REDIRECT_URL: https://s3.domain.com

## Expected Behavior
Login to the console behind proxy.

## Current Behavior

Login page fails and redirects back to itself.
Request: `https://s3.domain.com/api/v1/session`
Status code: `401`

## Possible Solution

I can login to the console by forwarding the 9001 service port (`kubectl port-forward`)
I can list buckets from http://storage.domain.dell.com using MinIO client (HTTPS returns `x509: certificate signed by unknown authority`)

## Steps to Reproduce (for bugs)
Expose MinIO server and console behind NGINX Kubernetes ingress with TLS certificates and HTTP/2.

**Ingresses**

Console:

```yaml
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: minio-release
  namespace: minio-release
  labels:
    app.kubernetes.io/instance: minio-release
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: minio
    helm.sh/chart: minio-8.1.3
  annotations:
    kubernetes.io/ingress.class: nginx
    meta.helm.sh/release-name: minio-release
    meta.helm.sh/release-namespace: minio-release
    nginx.ingress.kubernetes.io/proxy-body-size: 2000m
spec:
  rules:
    - host: s3.domain.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: minio-release
                port:
                  name: minio-console
```

Server:

```yaml
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: minio-release-api
  namespace: minio-release
  labels:
    app.kubernetes.io/instance: minio-release
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: minio
    helm.sh/chart: minio-8.1.3
  annotations:
    kubernetes.io/ingress.class: nginx
    meta.helm.sh/release-name: minio-release
    meta.helm.sh/release-namespace: minio-release
    nginx.ingress.kubernetes.io/proxy-body-size: 2000m
spec:
  rules:
    - host: storage.domain.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: minio-release
                port:
                  name: minio-api
```

Nginx Kubernetes Ingress Controller configuration:

```
nginx-ingress-controller
    --publish-service=ingress-nginx/ingress-nginx-controller
    --election-id=ingress-controller-leader
    --ingress-class=nginx
    --configmap=ingress-nginx/ingress-nginx-controller
    --validating-webhook=:8443
    --default-ssl-certificate=ingress-nginx/tls-certs
    --enable-ssl-chain-completion=false
```

**Additional `tls-certs` information**

Public key header:
```
Bag Attributes
    localKeyID: <ommited>
    friendlyName: *.domain.com
subject=C = US, ST = <ommited>, L = <ommited>, O = <ommited>, CN = *.domain.com

issuer=C = US, O = "Entrust, Inc."... <ommited>
```

Other deployments are already using this controller successfully.

## Context
We need https://storage.domain.com and https://s3.domain.com available for everyone.

## Regression
I tested images from Bitnami and MinIO repositories (2020 and 2021 versions).

## Your Environment

* Version used (`minio --version`): DEVELOPMENT.2021-09-18T18-09-59Z
* Server setup and configuration: Bitnami Minio Helm Chart 8.1.3, Nginx Kubernetes Ingress Controller v1.0.0

**Comment by harshavardhana** [comment]
> I can login to the console by forwarding the 9001 service port (`kubectl port-forward`)
> I can list buckets from http://storage.domain.dell.com using MinIO client (HTTPS returns `x509: certificate signed by unknown authority`)

if you have a self signed cert you need to make sure to trust this cert on the server at `~/.minio/certs/CAs` without this trust console cannot talk to MinIO

**Comment by danilopeixoto** [comment]
> > I can login to the console by forwarding the 9001 service port (`kubectl port-forward`)
> > I can list buckets from http://storage.domain.dell.com using MinIO client (HTTPS returns `x509: certificate signed by unknown authority`)
> 
> if you have a self signed cert you need to make sure to trust this cert on the server at `~/.minio/certs/CAs` without this trust console cannot talk to MinIO

Hi @harshavardhana,

Thanks for the support.
We have `public.crt` and `private.key` issued by Entrust, Inc.

**Comment by harshavardhana** [comment]
> Thanks for the support.
> We have `public.crt` and `private.key` issued by Entrust, Inc.

Entrust, Inc. is not part of ca-certificates @danilopeixoto you need to make sure this public.crt is present and added to `~/.minio/certs/CAs` for it to be trusted.

**Comment by harshavardhana** [comment]
This is just a configuration issue converting this into a discussion.

**Reply by harshavardhana** [reply]
Since you are using bitnami containers they do not ship our containers AFAIK - they try to build their own Debain based images. 

We cannot support Bitnami containers

```
image:
  registry: docker.io
  repository: bitnami/minio
  tag: 2021.9.18-debian-10-r0
```

Please use our officially published containers that are based on RHEL UBI8

**Reply by danilopeixoto** [reply]
Hi @harshavardhana,

I switched to MinIO official images:

```yaml
image:
  registry: docker.io
  repository: minio/minio
  tag: latest
clientImage:
  registry: docker.io
  repository: minio/mc
  tag: latest
```

Browsers can detect our certificates in Nginx ingress/proxy:
![image](https://user-images.githubusercontent.com/10113621/134550588-6d757006-8819-47b8-8b99-3222ca0277fd.png)
But MinIO client fails for HTTPS:
![image](https://user-images.githubusercontent.com/10113621/134551402-2eadbafc-7c83-4bfd-a14d-348274455b1f.png)

MinIO client works fine for HTTP.

Credentials and domain name were ommited.
