### DISCUSSION TITLE
Docker distributed mode if main host fails, all other hosts fail

### DISCUSSION THREAD

**Discussion by tom0010** [minio/minio#13339] [Q&A] [answered]
I have setup distributed mode inside docker containers going to 3 different sites with one node each with the exception of 1 of the sites having two nodes. I have a docker-compose file below, which seems to work just fine, if I destroy one of the containers, it seems to still operate. However if i destroy the main docker container (site1-001) the other 3 containers cannot operate. Is that expected? 
My assumption was that because it is distributed, it would continue to operate no matter which container died. But right now it seems that the whole setup is dependant on the first container (master if you will) being up, so I am unable to use for an HA setup because of that dependency of the first node.
docker-compose.yml (same for all 4 nodes):
```
version: '3.2'
services:
  minio:
    image: minio/minio:RELEASE.2021-09-24T00-24-24Z
    container_name: minio
    volumes:
      - data1:/data1
      - data2:/data2
      - data3:/data3
      - data4:/data4
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_PROMETHEUS_AUTH_TYPE: public
      MINIO_ROOT_USER: test1234
      MINIO_ROOT_PASSWORD: test1234
    command: server --console-address ":9001" http://node1-001.mydomain.com:9000/data{1...4} http://node1-002.mydomain.com:9000/data{1...4} http://node2-001.mydomain.com:9000/data{1...4} http://node3-001.mydomain.com:9000/data{1...4}
    dns:
      - x.x.x.x
      - x.x.x.x
    dns_search:
      - mydomain.com
    network_mode: host
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
volumes:
  data1:
    driver: local
  data2:
    driver: local
  data3:
    driver: local
  data4:
    driver: local
```
