### DISCUSSION TITLE
Error: LDAP server error: Unable to find user DN: User DN for minio not found

### DISCUSSION THREAD

**Discussion by Bhagi33** [minio/minio#13347] [Q&A]
Hi Team,

I have configured the LDAP with environment variables(Tenant pod). But facing issue.
can you please suggest on the configuration

 kubectl logs minio-pool-0-0 -n test-minio                                                         Waiting for all MinIO sub-systems to be initialized.. lock acquired
Verifying if 1 bucket is consistent across drives...
Automatically configured API requests per node based on available memory on the system: 424
All MinIO sub-systems initialized successfully
Waiting for all MinIO IAM sub-system to be initialized.. lock acquired
Status:         16 Online, 0 Offline.
API: https://minio.test-minio.svc.cluster.local

Console: https://192.168.67.104:9443 https://127.0.0.1:9443

Documentation: https://docs.min.io

API: AssumeRoleWithLDAPIdentity()
Time: 11:37:47 UTC 10/01/2021
DeploymentID: 247a975d-85d3-4071-b72d-93becebd462c
RequestID: 16A9E52079A9D00D
RemoteHost: x.x.x.x
Host: minio-pool-0-0.minio-hl.test-minio.svc.cluster.local:9000
UserAgent: Go-http-client/1.1
Error: LDAP server error: Unable to find user DN: User DN for minio not found (*fmt.wrapError)
       3: cmd/sts-errors.go:58:cmd.writeSTSErrorResponse()
       2: cmd/sts-handlers.go:594:cmd.(*stsAPIHandlers).AssumeRoleWithLDAPIdentity()
       1: net/http/server.go:2046:http.HandlerFunc.ServeHTTP()

-bash-4.2$ kubectl get tenant -n test-minio -o yaml

**Comment by harshavardhana** [comment]
> API: AssumeRoleWithLDAPIdentity() Time: 11:37:47 UTC 10/01/2021 DeploymentID: 247a975d-85d3-4071-b72d-93becebd462c RequestID: 16A9E52079A9D00D RemoteHost: x.x.x.x Host: minio-pool-0-0.minio-hl.test-minio.svc.cluster.local:9000 UserAgent: Go-http-client/1.1 Error: LDAP server error: Unable to find user DN: User DN for minio not found (*fmt.wrapError) 3: cmd/sts-errors.go:58:cmd.writeSTSErrorResponse() 2: cmd/sts-handlers.go:594:cmd.(*stsAPIHandlers).AssumeRoleWithLDAPIdentity() 1: net/http/server.go:2046:http.HandlerFunc.ServeHTTP()

Trying to login as `minio`  do you have `minio` user?

**Reply by Bhagi33** [reply]
i have basic user minio, but after LDAP configuration its not able to login.
Can you please help me how to give user access on Tenant cluster with out Password as i want to Authenticate User with LDAP.

Note: i have deployed Tenant from backend i.e through helm chart.

**Reply by vadmeste** [reply]
> i have basic user 'minio'

Is this the same user that you set in MINIO_ROOT_USER ?

**Reply by Bhagi33** [reply]
I have created the secret with
 access key=minio
Secret key=minio123
I tried to login with minio user ..
I am not sure whether this user will be root user or not

**Reply by Bhagi33** [reply]
Hi Team,

I ran this command to get STS credentials. but i am getting this 
I ran POST command outside minio cluster & with LB IP and port(exposed Minio cluster service to LB)

POST https://x.x.x.x:30003?Action=AssumeRoleWithLDAPIdentity&LDAPUsername=euserh&LDAPPassword=Pwd@123&Version=2011-06-15&Policy={}

[2] 25068
[3] 25069
[4] 25070
[5] 25071
[3]   Done                    LDAPUsername=euserh
-bash-4.2$ Please enter content (application/x-www-form-urlencoded) to be POSTed:


![image](https://user-images.githubusercontent.com/68953135/135973291-bcdfd30e-91dc-4093-8664-b015b9b7ac47.png)

**Reply by Bhagi33** [reply]
Hi Team,
Can you please suggest on this

**Comment by PayBas** [comment]
I'm running into the same problem when logging into the console using the `MINIO_ROOT_USER`/`MINIO_ROOT_PASSWORD` credentials.

```
minio    | WARNING: Detected default credentials 'minioadmin:minioadmin', we recommend that you change these values with 'MINIO_ROOT_USER' and 'MINIO_ROOT_PASSWORD' environment variables
minio    | 
minio    | API: AssumeRoleWithLDAPIdentity()
minio    | Time: 17:08:41 UTC 10/30/2021
minio    | DeploymentID: f4fbca93-7f3a-434f-8f8c-c55d1b12d0b6
minio    | RequestID: 16B2DE013663BA0B
minio    | RemoteHost: 172.21.0.2
minio    | Host: 172.21.0.2:9000
minio    | UserAgent: Go-http-client/1.1
minio    | Error: LDAP server error: Unable to find user DN: User DN for minioadmin not found (*fmt.wrapError)
minio    |        3: cmd/sts-errors.go:58:cmd.writeSTSErrorResponse()
minio    |        2: cmd/sts-handlers.go:599:cmd.(*stsAPIHandlers).AssumeRoleWithLDAPIdentity()
minio    |        1: net/http/server.go:2046:http.HandlerFunc.ServeHTTP()
```
Why would the local root user traverse through the `AssumeRoleWithLDAPIdentity` API?
I read all the documentation 3 times and still can't make heads or tails of this. It says in numerous places things like:
> The external IDP must have at least one configured user identity with the required policy claims. If no such user exists, the MinIO server is effectively inaccessible outside of using the root user.

But in reality the root user becomes inaccessible as well.

My `docker-compose.yml`
```
version: '3.7'
services:
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_IDENTITY_LDAP_SERVER_ADDR: ...
      MINIO_IDENTITY_LDAP_LOOKUP_BIND_DN: '...'
      MINIO_IDENTITY_LDAP_LOOKUP_BIND_PASSWORD: '...'
      MINIO_IDENTITY_LDAP_USER_DN_SEARCH_BASE_DN: '...'
      MINIO_IDENTITY_LDAP_USER_DN_SEARCH_FILTER: '...'
      MINIO_IDENTITY_LDAP_GROUP_SEARCH_BASE_DN: '...
      MINIO_IDENTITY_LDAP_GROUP_SEARCH_FILTER: '...'
    volumes:
      - type: volume
        source: minio-data
        target: /data
    networks:
      - minio
    ports:
      - 9000:9000
      - 9001:9001
    command:
      - server
      - /data
      - '--console-address=:9001'

volumes:
  minio-data:
networks:
  minio:
    name: minio
```
