### DISCUSSION TITLE
Minio Audit logging

### DISCUSSION THREAD

**Discussion by Vineeth-varma** [minio/minio#13476] [Q&A] [answered]
Can someone help me to set up or enable audit logging for Minio Operator.

mc admin config set myminio/ audit_webhook --env --insecure
KEY:
audit_webhook[:name]  send audit logs to webhook endpoints

ARGS:
MINIO_AUDIT_WEBHOOK_ENABLE*      (on|off)    enable audit_webhook target, default is 'off'
MINIO_AUDIT_WEBHOOK_ENDPOINT*    (url)       HTTP(s) endpoint e.g. "http://localhost:8080/minio/logs/audit"
MINIO_AUDIT_WEBHOOK_AUTH_TOKEN   (string)    opaque string or JWT authorization token
MINIO_AUDIT_WEBHOOK_CLIENT_CERT  (string)    mTLS certificate for Audit Webhook authentication
MINIO_AUDIT_WEBHOOK_CLIENT_KEY   (string)    mTLS certificate key for Audit Webhook authentication
MINIO_AUDIT_WEBHOOK_COMMENT      (sentence)  optionally add a comment to this setting

I got struck in understanding few args from the above screenshot

Thanks

**Comment by harshavardhana** [comment, marked as answer]
> mc admin config set myminio/ audit_webhook --env --insecure KEY: audit_webhook[:name] send audit logs to webhook endpoints
> 
> ARGS: MINIO_AUDIT_WEBHOOK_ENABLE* (on|off) enable audit_webhook target, default is 'off' MINIO_AUDIT_WEBHOOK_ENDPOINT* (url) HTTP(s) endpoint e.g. "http://localhost:8080/minio/logs/audit" MINIO_AUDIT_WEBHOOK_AUTH_TOKEN (string) opaque string or JWT authorization token MINIO_AUDIT_WEBHOOK_CLIENT_CERT (string) mTLS certificate for Audit Webhook authentication MINIO_AUDIT_WEBHOOK_CLIENT_KEY (string) mTLS certificate key for Audit Webhook authentication MINIO_AUDIT_WEBHOOK_COMMENT (sentence) optionally add a comment to this setting
> 
> I got struck in understanding few args from the above screenshot

You need to create `minio-config` as secret, which will be automatically loaded.  // cc @Alevsk 

Something like this

```
spec:
  ## Add environment variables to be set in MinIO container (https://github.com/minio/minio/tree/master/docs/config)
  env:
    - name: MINIO_IDENTITY_OPENID_CONFIG_URL
      value: "https://your-extenal-idp.com/.well-known/openid-configuration" # Your external identity provide configuration
    - name: MINIO_IDENTITY_OPENID_CLIENT_ID
      value: "OPENID CLIENT ID"
    - name: MINIO_IDENTITY_OPENID_CLIENT_SECRET
      value: "OPENID CLIENT SECRET"
    - name: MINIO_IDENTITY_OPENID_SCOPES
      value: "openid,profile,email"
    - name: MINIO_IDENTITY_OPENID_CLAIM_NAME
      value: "https://min.io/policy"
```
