### DISCUSSION TITLE
MinIO and LDAP integration

### DISCUSSION THREAD

**Discussion by eclipsetalk** [minio/minio#13703] [Q&A] [answered]
Hello,
Has anyone be successful using minio and LDAP?  I've configured the env variables as below, I can see them set in the pod but LDAP is not being used. Any config you can share would be greatly appreciated. Thanks!

```
extraEnvVars:
  - name: MINNIO_LOG_LEVEL
    value: DEBUG
  - name: MINIO_IDENTITY_LDAP_SERVER_ADDR
    value: "ldaps://xxxx.corp:636"
  - name: MINIO_IDENTITY_LDAP_GROUP_SEARCH_FILTER
    value: "(&(objectCategory=user)(sAMAccountName=%s))"
  - name: MINIO_IDENTITY_LDAP_USER_DN_SEARCH_BASE_DN
    value: "DC=xxx,DC=CORP"
  - name: MINIO_IDENTITY_LDAP_LOOKUP_BIND_PASSWORD
    value: 'xxxx'
  - name: MINIO_IDENTITY_LDAP_LOOKUP_BIND_DN
    value: "CN=xxxxx,OU=Svcaccts,DC=xxx,DC=CORP"
  - name: MINIO_IDENTITY_LDAP_GROUP_SEARCH_FILTER
    value: "(&(objectClass=group)(member=%d))"
```
