### DISCUSSION TITLE
Console port in kubernetes yaml

### DISCUSSION THREAD

**Discussion by zkryakgul** [minio/minio#13806] [Q&A] [answered]
Hi guys, i want to add the` --console-port ` parameter to my minio in kubernetes statefulset. Here is my containers section in sts yaml:
```
containers:
        - name: minio
          image: minio/minio:RELEASE.2021-11-24T23-19-33Z
          args:
            - server
            - http://minio-0.minio:9000/data/minio{0...15}
            - http://minio-1.minio:9000/data/minio{0...15}
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
            - name: console
              containerPort: 9001
              protocol: TCP
```
I try to add
`- '--console-port ":90001"'`
in my **args** section but minio keep crashing
Any suggestions?
