### DISCUSSION TITLE
mlflow-minio yaml deployment

### DISCUSSION THREAD

**Discussion by shounakgit** [minio/minio#13847] [Q&A]
Hi, I am trying to use Minio to integrate with Mlflow. There are few links on the web and I had been primarily following this one (https://towardsdatascience.com/mlflow-part-2-deploying-a-tracking-server-to-minikube-a2d6671e6455). After the pod comes up in the minikube and I don't know how to connect with Minio. Here are my few questions. Really appreciate if I can get some answers.

1) Should I use MINIO_ACCESS_KEY or MINIO_ROOT_USER?
2) Do I need to add a secret in Minikube to work with minio? 
3) Can you suggest what is perhaps going wrong with yaml file below that I am unable to reach Minio in the pod?

` http://192.168.49.2:30211/minio/login` refuses connection. 
 
```
me4@ubuntu:~/Workspace1/mlflow1/minio$ minikube service mlflow-minio-service 
|-----------|----------------------|-------------|---------------------------|
| NAMESPACE |         NAME         | TARGET PORT |            URL            |
|-----------|----------------------|-------------|---------------------------|
| default   | mlflow-minio-service |        9000 | http://192.168.49.2:30211 |
|-----------|----------------------|-------------|---------------------------|
```
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-minio-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: standard 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-minio-deployment
spec:
  selector:
    matchLabels:
      app: mlflow-minio
  template:
    metadata:
      labels:
        app: mlflow-minio
    spec:
      volumes:
      - name: mlflow-minio-storage
        persistentVolumeClaim:
          claimName: mlflow-minio-pvc
      containers:
      - name: mlflow-minio
        image: minio/minio:RELEASE.2020-10-18T21-54-12Z
        args:
        - server
        - /data
        volumeMounts:
        - name: mlflow-minio-storage
          mountPath: '/data'
        env:
        - name: MINIO_ACCESS_KEY
          value: "minioadmin"
        - name: MINIO_SECRET_ACCESS_KEY
          value: "minioadmin"
        ports:
        - containerPort: 9000
          hostPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-minio-service
spec:
  type: NodePort
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
  selector:
    app: mlflow-minio
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mlflow-minio-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.il/add-base-url: "true"
    nginx.ingress.kubernetes.il/ssl-redirect: "false"
spec:
  rules:
  - host: mlflow-minio.local
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: mlflow-minio-service
            port:
              number: 9000
```
