### DISCUSSION TITLE
The bucket you are attempting to access must be addressed using the specified endpoint

### DISCUSSION THREAD

**Discussion by fpytloun** [minio/minio#14210] [Q&A] [answered]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

I have configured S3 gateway to Wasabi with cache and since version `RELEASE.2021-12-27T07-23-18Z` I am getting this error:

```
API: ListObjectsV2(bucket=thanos-domecek)
Time: 11:13:59 UTC 01/30/2022
DeploymentID: 179608a7-2174-48a1-adc5-9ffa60ef64ee
RequestID: 16CF080C960A694F
RemoteHost: 10.244.0.164
Host: thanos-minio.monitoring.svc.cluster.local:9000
UserAgent: MinIO (linux; amd64) minio-go/v7.0.10 thanos-compact/0.23.1 (go1.16.8)
Error: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint. (minio.ErrorResponse)
       4: cmd/api-errors.go:2103:cmd.toAPIErrorCode()
       3: cmd/api-errors.go:2128:cmd.toAPIError()
       2: cmd/bucket-listobjects-handlers.go:252:cmd.objectAPIHandlers.ListObjectsV2Handler()
       1: net/http/server.go:2047:http.HandlerFunc.ServeHTTP()
```

Last working version is `RELEASE.2021-12-20T22-07-16Z`

## Expected Behavior

Requests working as in previous versions

## Current Behavior

Requests failing

## Steps to Reproduce (for bugs)

1. Setup MiniO S3 proxy to Wasabi with `gateway s3 "https://s3.wasabisys.com:443"`
2. Try to make request (I am using Thanos with S3 config as client)

## Context

Kubernetes manifest:
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: thanos-minio
  namespace: monitoring
  labels:
    app: thanos
    component: minio
spec:
  podManagementPolicy: "Parallel"
  serviceName: minio
  replicas: 1
  selector:
    matchLabels:
      app: thanos
      component: minio
  template:
    metadata:
      name: thanos-minio
      labels:
        app: thanos
        component: minio
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - thanos
                - key: component
                  operator: In
                  values:
                  - minio
              namespaces:
              - monitoring
              topologyKey: kubernetes.io/hostname
            weight: 100
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - finwe
      containers:
        - name: minio
          # TODO: doesn't work
          #image: minio/minio:RELEASE.2022-01-28T02-28-16Z
          #image: minio/minio:RELEASE.2021-12-27T07-23-18Z
          # Last working:
          image: minio/minio:RELEASE.2021-12-20T22-07-16Z
          args:
          - "gateway"
          - "s3"
          - "https://s3.wasabisys.com:443"
          volumeMounts:
            - name: minio-data
              mountPath: /data
          ports:
            - name: http
              containerPort: 9000
          env:
          - name: MINIO_PROMETHEUS_AUTH_TYPE
            value: "public"
          - name: MINIO_ROOT_USER
            value: "dummy"
          - name: MINIO_ROOT_PASSWORD
            value: "dummy"
          - name: MINIO_CACHE
            value: "on"
          - name: MINIO_CACHE_DRIVES
            value: "/data"
          - name: MINIO_CACHE_EXPIRY
            value: "90"
          - name: MINIO_CACHE_AFTER
            value: "1"
      volumes:
        - name: minio-data
          hostPath:
            path: /srv/prometheus/minio
```

Thanos config:
```
    type: S3
    config:
      endpoint: "thanos-minio.monitoring.svc.cluster.local:9000"
      insecure: true
      bucket: "thanos-domecek"
      access_key: "dummy"
      secret_key: "dummy"
      signature_version2: true
```

## Regression

Yes, broken in `RELEASE.2021-12-27T07-23-18Z`

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):
