### DISCUSSION TITLE
Kubernetes S3 gateway

### DISCUSSION THREAD

**Discussion by varuna-sd** [minio/minio#14218] [Q&A]
Hi, How can I configure S3 gateway in kubernetes?

Current sepc
```
spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: minio-pvc
      containers:
        - name: minio
          image: >-
            gcr.io/ml-pipeline/minio:RELEASE.2019-08-14T20-37-41Z-license-compliance
          args:
            - server
            - /data
          ports:
            - containerPort: 9000
              protocol: TCP
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: mlpipeline-minio-artifact
                  key: accesskey
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: mlpipeline-minio-artifact
                  key: secretkey
          resources: {}
          volumeMounts:
            - name: data
              mountPath: /data
              subPath: minio
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
```
