### DISCUSSION TITLE
How to set different log levels for minio?

### DISCUSSION THREAD

**Discussion by patsevanton** [minio/minio#14213] [Q&A] [answered]
Hello!
I use minio in docker-compose.
How to set different log levels for minio?

```
  minio:
    image: minio/minio:RELEASE.2020-10-27T04-03-55Z
    ports:
      - '9000:9000'
    volumes:

      - ./data/storage:/data 
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: always
```

I see 
```
set MINIO_LOGGER_WEBHOOK_ENABLE_<IDENTIFIER>="on"
set MINIO_LOGGER_WEBHOOK_ENDPOINT_<IDENTIFIER>="https://webhook-1.example.net"
set MINIO_LOGGER_WEBHOOK_AUTH_TOKEN_<IDENTIFIER>="TOKEN"
```

But my question:
How add/set env variable LOG_LEVEL=DEBUG and get more log in docker container minio ?
