### DISCUSSION TITLE
Localize tenant docker images

### DISCUSSION THREAD

**Discussion by asoleimanibo** [minio/minio#14300] [Q&A]
I have deployed tenant via Helm-charts In the Kubernetes cluster. After activating logging, "minio1-log" and "minio1-log-search-api" resources are created in "minio-tenant" namespace. I want to pull images from a private registry. How can I set image registry for all of the images that minio-tenant will be used such as "minio/operator", "library/postgres" and "prometheus"?

**Comment by harshavardhana** [comment]
- helm - https://github.com/minio/operator/blob/master/helm/tenant/values.yaml#L14
- plugin - https://docs.min.io/minio/k8s/reference/minio-kubectl-plugin.html#kubectl-minio-init-image-pull-secret

**Reply by asoleimanibo** [reply]
@harshavardhana I have set `imagePullSecret` for both operator and tenant:
```
tenants:
  - name: minio1
    image:
      repository: registry.local:9059/quay.io/minio/minio
      tag: RELEASE.2021-08-31T05-46-54Z
      pullPolicy: IfNotPresent
    namespace: minio-tenant
    imagePullSecret: {'minio-pull'}
```
```
operator:
  image:
    repository: registry.local:9059/minio/operator
    tag: v4.4.7
    pullPolicy: IfNotPresent
  imagePullSecrets:
    - name: minio-pull
```
But still, images are not pulled from private registry:
```
minio1-log 	
library/postgres:13 + 1 image
1 Pod / Created 21 minutes ago / Pod Restarts: 0
ReplicaSet "minio1-log-search-api-697b777986" has timed out progressing.
minio/operator:v4.4.7
1 Pod / Created 21 minutes ago / Pod Restarts: 0
```
Which field exactly declares the private repo URL for images such as `library/postgres:13`?
