### DISCUSSION TITLE
Migrating to TLS failure: Unable to initialize backend

### DISCUSSION THREAD

**Discussion by pepitogrillominio** [minio/minio#14792] [Q&A] [answered]
Hi everybody and thank you first of all,
We have 2 working pools of 3 server (I do understand is not a production grade setup) on docker with docker-compose:
```
services:
  minio:
    image: registry.local:5000//minio:20220226 
    user: 10015:10015   #minio-user:minio
    hostname: minio4    
    networks:
      docker-encrypted-network:
        ipv4_address: 10.10.10.21
    command: server --console-address ":9001" https://minio{4...6}:9000/data{1...4}   
    ports:
    - target: 9000
      published: 9000
      protocol: tcp
    - target: 9001
      published: 9001
      protocol: tcp
    logging:
      driver: syslog
      options:
        syslog-address: "udp://172.17.0.1:514"
        tag: "minio"
        syslog-facility: local7

    environment:
       - MINIO_ROOT_USER=minio123
       - MINIO_ROOT_PASSWORD=minio123
    extra_hosts:
        - "minio1:10.10.10.11"    
        - "minio2:10.10.10.12"    
        - "minio3:10.10.10.13"    
        - "minio4:10.10.10.21"    
        - "minio5:10.10.10.22"    
        - "minio6:10.10.10.23"    
    volumes:
      - /data/Project/minio/data1:/data1:Z
      - /data/Project/minio/data2:/data2:Z
      - /data/Project/minio/data3:/data3:Z
      - /data/Project/minio/data4:/data4:Z
      - /home/minio-user/.minio:/.minio:Z
    cap_add:
      - IPC_LOCK

networks:
  docker-encrypted-network:
    external: true
```
It's been working without a problem, but now when trying to migrate to a TLS setup changing from http:// to https://  in the command and adding self signed certificates we get the error: 

Unable to initialize backend: pool(1st) = http://minio/{4...6}:9000/data{1...4} is not specified, please specify on server command line"

Minio waits for other nodes to be alive and exits as soon as there is another node available.
What would I would be missing?
Thank's a million
Daniel
