### DISCUSSION TITLE
aws javascript sdk v3 - Cannot read properties of undefined (reading 'data') Error

### DISCUSSION THREAD

**Discussion by vtrofin** [minio/minio#14951] [Q&A] [answered]
Hi there Team,

I'm having an issue using the [getObjectAttributes](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-s3/classes/s3.html#getobjectattributes) method with Minio. As i've already seen question #14709 and the regression described there, i'm wondering whether the error i'm getting below is because of misconfiguration or maybe some other regression.

I'm running minio in a local docker container with the following configuration in the docker compose file:
```
services:
  minio:
    image: minio/minio:latest
    ports:
      - 80:9000
      - 46453:46453
    command: server /data -console-address :46453
    environment:
      MINIO_ACCESS_KEY: <access key>
      MINIO_SECRET_KEY: <secret key>
      MINIO_COMPRESS: "true"
      MINIO_COMPRESS_EXTENSIONS: ".png,.jpg,.jpeg,.pdf"
      MINIO_COMPRESS_MIME_TYPES: "image/png,image/jpeg,application/pdf"

    volumes:
      - minio_data:/data
```

I'm using the following  s3 client version:
```
  "@aws-sdk/client-s3": "3.94.0",
  "@aws-sdk/s3-request-presigner": "3.94.0",
```

The implementation of the `getObjectAttributes` method looks like this :

```
import { GetObjectAttributesCommandOutput, S3 } from "@aws-sdk/client-s3";

export class StorageService {
  private client: S3;

  constructor() {
    const minioConfig = {
      endpoint: {
        protocol: "http",
        hostname: "localhost",
        path: "",
      },
      credentials: {
        accessKeyId: "<access key>",
        secretAccessKey: "<secret key>",
      },
      region: "ap-northeast-1",
      forcePathStyle: true,
    };

    this.client = new S3(minioConfig);
  }

  async statObject({
    bucketName,
    objectName,
  }: {
    bucketName: string;
    objectName: string;
  }): Promise<GetObjectAttributesCommandOutput> {
    return this.client.getObjectAttributes({
      Bucket: bucketName,
      Key: objectName,
      ObjectAttributes: [
        "Checksum",
        "ETag",
        "ObjectParts",
        "ObjectSize",
        "StorageClass",
      ],
    });
  }
}

```

Calling the `statObject` function above with the bucket name and the object name results in the undefined error below
```
 const storageService = StorageService()
 const objectAttributes = await storageService.statObject({
    bucketName: <bucket name>,
    objectName: <object Key>,
  })

```

```
TypeError: Cannot read properties of undefined (reading 'data')
    at Object.getTraversalObj (/Users/victor_trofin/github/ats-api/node_modules/fast-xml-parser/src/xmlstr2xmlnode.js:252:29)
    at exports.parse (/Users/victor_trofin/github/ats-api/node_modules/fast-xml-parser/src/parser.js:19:39)
    at /Users/victor_trofin/github/ats-api/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:12792:55
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async deserializeAws_restXmlGetObjectAttributesCommand (/Users/victor_trofin/github/ats-api/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:6295:87)
    at async /Users/victor_trofin/github/ats-api/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at async /Users/victor_trofin/github/ats-api/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:11:20
    at async StandardRetryStrategy.retry (/Users/victor_trofin/github/ats-api/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)
    at async /Users/victor_trofin/github/ats-api/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22
    at async Object.handler (/Users/victor_trofin/github/ats-api/tests/services/StorageService.test.ts:160:34) {
  '$metadata': { attempts: 1, totalRetryDelay: 0 }
}
```

I didn't find anything to help explain the potential issue on a google search or through the github issues. Is there a way to figure out at least why this error happens? I'm not sure what the `data` thing even is.
 
Thank you very much for any potential information that might help in figuring out the issue.
