### DISCUSSION TITLE
How to proxy minio with ingress-nginx

### DISCUSSION THREAD

**Discussion by SeibertronSS** [minio/minio#15147] [Q&A] [answered]
I deployed a standalone minio on my kubernetes cluster via helm. But I can't proxy minio through ingress-nginx. This is the ingress yaml I use
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: minio-bucket-1edb2ca4
  namespace: minio
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/upstream-vhost: minio:9000
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers        "HOST $host";
      more_set_headers        "X-Real-IP $remote_addr";
      more_set_headers        "X-Forwarded-For $proxy_add_x_forwarded_for";
      more_set_headers        "X-Forwarded-Proto $scheme";

spec:
  rules:
  - host: 1edb2ca4.com
  - http:
      paths:
      - path: /1edb2ca4
        backend:
          serviceName: minio
          servicePort: 9000
```
I want to proxy bucket '1edb2ca4' in minio through the ingress. When I access the connection shared by the minio through this ingress I get the following error
```
<Error>
<Code>SignatureDoesNotMatch</Code>
<Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>
<Key>2022-6/69b47458e66311eca9e6ee49a8ed890b/20220110161903.png</Key>
<BucketName>1edb2ca4</BucketName>
<Resource>/1edb2ca4/2022-6/69b47458e66311eca9e6ee49a8ed890b/20220110161903.png</Resource>
<RequestId>16FAE81E626255BD</RequestId>
<HostId>6ad3e992-9b54-4926-8ee8-4ef22ecbf27f</HostId>
</Error>
```
It is worth mentioning that the request received by ingress was forwarded by another nginx, and the upstream nginx added extra headers to the request. Is this the cause of the error?

**Comment by vadmeste** [comment]
@SeibertronSS certains things in the request created by the S3 client should not be modified, such as the request 'path' and the 'Host' header. It seems you are overriding Host header in this case.

**Comment by SeibertronSS** [comment, marked as answer]
I found a way to proxy Minio with ingress-nginx.
The yaml is
```
apiVersion: extensions/v1beta1 # networking.k8s.io/v1beta1 #extensions/v1beta1
kind: Ingress
metadata:
  name: minio-bucket-1edb2ca4
  namespace: easytai
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/upstream-vhost: xx.xx.xx.xxx:9000
spec:
  rules:
  - host: 1edb2ca4.com
  - http:
      paths:
      - path: /1edb2ca4
        backend:
          serviceName: minio
          servicePort: 9000
```
The xx.xx.xx.xxx:9000 is the clusterIP of the svc of the minio pod.
