### DISCUSSION TITLE
How to configure on Vanilla Helm Chart Erasure Coding?

### DISCUSSION THREAD

**Discussion by jas02** [minio/minio#15333] [Q&A]
Hi, I would like to reduce data redundancy to minimum (EC: 2). How to do that using this vanilla helm chart?

Currently I am using distributed mode.

```
drivesPerNode: 1
gateway:
      replicas: 4
      type: nas
mode: distributed
pools: 1
replicas: 4
``` 

Second question. Is it possible to increase number of servers/disks by 2 and not 4? I tried to scale up servers/disks (replicas) from four to six, and it didn't worked. I had to increase the pool number, which created four new servers/drives.
