### DISCUSSION TITLE
minio helm chart vanilla: HowTo define multiple customCommands ?

### DISCUSSION THREAD

**Discussion by r0b1ndot** [minio/minio#15472] [Q&A] [answered]
## Expected Behavior

i want to execute multiple commands via the customCommands option.
how can i define this in the values.yaml using the Vanilla Chart without the operator?

```
  customCommands:
    - command1: rb myminio/foo1
    - command2: mb --with-lock myminio/foo1
    - command2: mc retention set --default GOVERNANCE "5d" myminio/foo1
```
## Current Behavior
Chart is not rendered due to config issue.

## Steps to Reproduce (for bugs)

there are no further docs available only a hint in the values file for one command but not for multiple.
