### DISCUSSION TITLE
Metrics not work well inside the minio web console

### DISCUSSION THREAD

**Discussion by gigi206** [minio/minio#15526] [Q&A]
Metrics not working inside the web console.

I installed with the Kubernetes [minio charts 4.0.11](https://artifacthub.io/packages/helm/minio-official/minio/4.0.11) and I enabled metrics with the following parameters:
```yaml
        - name: metrics.serviceMonitor.enabled
          value: 'true'
        - name: metrics.serviceMonitor.additionalLabels.release
          value: prometheus-stack
        - name: environment.MINIO_PROMETHEUS_URL
          value: 'http://prometheus-operated.prometheus-stack.svc.cluster.local:9090'
```

Metrics work well, I show the targets in Prometheus and the Grafana dashboard works but metrics seem not working in the minio web console.

![console](https://i.ibb.co/VBM8Q0X/Capture-d-cran-du-2022-08-12-01-30-34.png)
