### DISCUSSION TITLE
How to set up etcd authentication?

### DISCUSSION THREAD

**Discussion by jgillich** [minio/minio#15715] [Q&A]
Hi,

I'm using minio S3 gateway mode and I need to connect minio to etcd for IAM storage. I have deployed etcd using the [chart from bitnami](https://artifacthub.io/packages/helm/bitnami/etcd) and generate the client cert using cert-manager.

```yaml
# cert
apiVersion: cert-manager.io/v1
kind: Certificate
spec:
  commonName: minio-gateway-etcd-cert
  secretName: minio-gateway-etcd-cert
  privateKey:
    algorithm: ECDSA
    size: 256
---
# etcd chart values
    auth:
      rbac:
        create: false
      client:
        secureTransport: true
        existingSecret: minio-gateway-etcd-cert
        certFilename: "tls.crt"
        certKeyFilename: "tls.key"
---
# minio chart values
    extraEnvVars:
      - name: MINIO_ETCD_CLIENT_CERT
        value: "/etc/credentials/tls.crt"
      - name: MINIO_ETCD_CLIENT_CERT_KEY
        value: "/etc/credentials/tls.key"
    extraVolumes:
      - name: etcd-client-certs
        secret:
          secretName: minio-gateway-etcd-cert
          defaultMode: 256
    extraVolumeMounts:
      - name: etcd-client-certs
        mountPath: /etc/credentials
        readOnly: true
```
With this, I see `remote error: tls: bad certificat` errors in the etcd logs, so this probably isn't right. But I couldn't find any examples of how to set this up correctly.

Does anyone have a sample setup for etcd+minio on Kubernetes (or even without K8s)?
