### DISCUSSION TITLE
Receiving 403 Forbidden from Minio when using Istio routing via Virtual Service

### DISCUSSION THREAD

**Discussion by asianman35** [minio/minio#15784] [Q&A] [answered]
Hi All, I'm hoping someone out there who has gotten Minio to work with Istio in a kubernetes environment can help me out. I have my application (Go Lang) pointing to minio using the local cluster address (http://core-minio.core-minio.svc.cluster.local:9000) and everything works fine, I have TLS disabled, externalAccess disabled. I have then created an Istio Virtual Service pointing to my minio service, and set my minio url to (https://external-host.com/api/minio) in my app, but now minio returns a 403 forbidden (verified using mc admin trace). This is using the same username/pass I was using before, just changed the url to minio so that it goes outside the cluster and back in through the Istio Ingress and Virtual Service. I know that the call is getting to minio, I can see the call when doing a trace in Minio, but it does not give me any more data as to why. My Istio ingress terminates the TLS connection and forwards the request at http. Comparing both traces of both calls, both have the Authorization header with the same username. The only difference is that the local call has an X-Forwarded-Client-Cert header that looks something like 'By=spiffe://cluster.local/ns/core-minio/sa/core-minio:Hash={somehash};Subject="";URI=spiffe://cluster.local/ns/{callerns}/sa/default' Here is my Virtual Service, i basically have it listening on /api/minio but then it rewrites the path to just / to get rid of that. 
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: minio-vservice
  namespace: core-minio
spec:
  gateways: 
  - core/local-gateway
  hosts: 
  - external-host.com
  http:
  - corsPolicy:
       allowCredentials: true
       allowHeaders:
       - Authorization
       - Content-Type
       - X-Forwarded-Client-Cert
       allowMethods:
       - GET
       - POST
       - PUT
       - PATCH
       - DELETE
       - OPTIONS
       allowOrigins:
       - regex: .*
       maxAge: 24h
     match: 
     - uri: 
          prefix: /api/minio
       name: minio-api-service
       rewrite: 
          uri: /
        route:
        - destination:
             host: core-minio.core-minio.svc.cluster.local
             port: 9000
  ```

**Comment by harshavardhana** [comment, marked as answer]
you cannot custom rewrite rules with S3 API 

```
    match: 
     - uri: 
          prefix: /api/minio
       name: minio-api-service
       rewrite: 
```

Also don't use istio it is pretty bad for performance with distributed setup.
