### DISCUSSION TITLE
minio admin web with nginx proxy manager , download image not working 403

### DISCUSSION THREAD

**Discussion by MilesWuCode** [minio/minio#15878] [Q&A]
## Expected Behavior
i use docker and nginx proxy manager on one site server
```sh
docker run -d \
--name minio \
-v ${PWD}/data:/data \
-p 3105:9000 \
-p 3106:9001 \
-e MINIO_ROOT_USER=admin \
-e MINIO_ROOT_PASSWORD=password \
-e MINIO_SERVER_URL="https://minio.miles-home.cc" \
-e MINIO_BROWSER_REDIRECT_URL="https://minio-console.miles-home.cc" \
--restart unless-stopped \
minio/minio:latest \
server /data \
--address ":9000" \
--console-address ":9001"
```

## Current Behavior
minio admin :
create public buckets and  upload a.json b.jpg
only json file can be download
b.jpg can not preview and download

## Possible Solution
disabled
```sh
-e MINIO_SERVER_URL="https://minio.miles-home.cc" \ 
```
## Steps to Reproduce (for bugs)
![Screenshot 2022-10-17 2 06 31 PM](https://user-images.githubusercontent.com/1192835/196101372-176c1b78-ad16-459b-a7b7-1203a0679040.png)

![Screenshot 2022-10-17 2 07 14 PM](https://user-images.githubusercontent.com/1192835/196101396-b432a2ef-c2fc-4ef1-a3c0-afa2a65a05ab.png)

Metadata is empty
![Screenshot 2022-10-17 2 06 56 PM](https://user-images.githubusercontent.com/1192835/196101451-e03a53e1-295c-4b0e-b273-abc428bd4154.png)

## Your Environment

* Version used (`minio --version`):  minio/minio:RELEASE.2022-10-15T19-57-03Z
* Operating System and version (`uname -a`): Linux miles 5.15.0-50-generic Ubuntu SMP Tue Sep 20 13:23:26 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
Please share your nginx config..

**Reply by MilesWuCode** [reply]
Nginx Proxy Manager with Let's Encrypt

```yml
version: "3"
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '3100:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP

    # Uncomment the next line if you uncomment anything in the section
    # environment:
      # Uncomment this if you want to change the location of 
      # the SQLite DB file within the container
      # DB_SQLITE_FILE: "/data/database.sqlite"

      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'

    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
 ```
![Screenshot 2022-10-17 2 30 27 PM](https://user-images.githubusercontent.com/1192835/196104744-bb3148f5-461e-4e38-af36-bd8426ea889b.png)

![Screenshot 2022-10-17 2 30 02 PM](https://user-images.githubusercontent.com/1192835/196104771-3f0a5b08-6952-4849-9607-ca0df2560c3c.png)

![Screenshot 2022-10-17 2 31 48 PM](https://user-images.githubusercontent.com/1192835/196104876-58665410-a5af-4cb6-a6e9-538a7cb22ff2.png)
