### DISCUSSION TITLE
TLS problem between minio and minio kes in docker

### DISCUSSION THREAD

**Discussion by amirAlamian** [minio/minio#15948] [Q&A] [answered]
Hi I'm trying to use minio SSE with hashicorp vault and minio kes. they are all in docker and vault is not using TLS for connections. But minio kes using it and when I want to connect minio to minio kes I'm getting this error in minio:
```
ERROR Unable to initialize a connection to KES as specified by the shell environment: Post "https://minio-kes:7373/v1/key/create/minio-backend-default-key": x509: certificate signed by unknown authority
```

and minio kes is logging this:
```
 {"message":"2022/10/26 08:53:45 http: TLS handshake error from 192.176.0.11:34898: remote error: tls: bad certificate"}
```

this is my docker compose:

```
  app-minio:
    image: minio/minio
    restart: always
    container_name: app-minio
    depends_on:
      - minio-kes
    volumes:
      - /mnt/minio:/data
      - ./public:/images
      - ./orchestration/Minio/env/minio:/etc/default/minio/minio
      - ./orchestration/Minio/KES/certs:/etc/default/minio/certs
    environment:
      - 'MINIO_ROOT_USER=${MINIO_USERNAME}'
      - 'MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}'
      - MINIO_CONFIG_ENV_FILE=/etc/default/minio/minio
    ports:
      - '9001:9001'
      - '9000:9000'
    command: server --console-address ":9001" /data
    networks:
      my-network:
        ipv4_address: 192.176.0.12
    valut:
    image: vault
    restart: always
    container_name: vault
    cap_add:
      - IPC_LOCK
    environment:
      - 'VAULT_LOCAL_CONFIG={"backend": {"file": {"path": "/vault/file"}}, "default_lease_ttl": "168h", "max_lease_ttl": "720h"}'
      -  VAULT_ADDR=http://127.0.0.1:8200
    ports:
      - '8200:8200'
    volumes:
      - /vault:/vault
      - ./orchestration/Vault/main.hcl:/etc/vault/main.hcl
    command: server -config /etc/vault/main.hcl
    networks:
      my-network:
        ipv4_address: 192.176.0.13
  minio-kes:
    image: minio/kes
    container_name: minio-kes
    restart: always
    volumes:
      - ./orchestration/Minio/KES:/root/.kes
    environment:
    - KES_SERVER=https://0.0.0.0:7373
    - KES_CLIENT_CERT=/root/.kes/certs/minio-kes.crt
    - KES_CLIENT_KEY=/root/.kes/certs/minio-kes.key
    ports:
      - 7373:7373
    cap_add:
      - CAP_IPC_LOCK
    command: server --config=/root/.kes/config/config.yaml --auth=off 
    networks:
      my-network:
        ipv4_address: 192.176.0.14

```

and this is my minio kes config file :

```
address: 0.0.0.0:7373 # Listen on all network interfaces on port 7373

admin:
  identity: disabled

tls:
  key: /root/.kes/certs/kes-server.key
  cert: /root/.kes/certs/kes-server.crt

policy:
  admin:
    allow:
      - /v1/key/create/*
      - /v1/key/generate/*
      - /v1/key/decrypt/*
      - /v1/key/delete/*
      - /v1/key/list/*
      - /v1/identity/list/*
    identities:
      - myIdentityString


keystore:
  vault:
    endpoint: http://vault:8200
    version:  v2 # The K/V engine version - either "v1" or "v2".
    approle:
      id:     vault-appRole-id # Your AppRole ID
      secret: vault-appRole-secret # Your AppRole Secret
      retry:  15s
    status:
      ping: 10s


log:
  error: on
  audit: on

```

and minio env file:

```

MINIO_KMS_KES_ENDPOINT=https://minio-kes:7373

MINIO_KMS_KES_CERT_FILE=/etc/default/minio/certs/minio-kes.crt
MINIO_KMS_KES_KEY_FILE=/etc/default/minio/certs/minio-kes.key

MINIO_KMS_KES_CA_PATH=/etc/default/minio/certs/kes-server.crt
MINIO_KMS_KES_KEY_NAME=minio-backend-default-key

```

any help?
