### DISCUSSION TITLE
API returns a 400 bad request all the time, nginx reverse proxy

### DISCUSSION THREAD

**Discussion by Traction6131** [minio/minio#15989] [Q&A]
Hey! So I basically just set up minio and wanted to intergrate it in my reverse proxy. However, while I followed the [tutorial](https://min.io/docs/minio/linux/integrations/setup-nginx-proxy-with-minio.html), it returns a 400 Bad Request.
Docker compose file looks like this:
``` 
version: '2'

services:
  minio:
    container_name: Minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=yeah
      - MINIO_ROOT_PASSWORD=aint gonna show that
      - MINIO_SERVER_URL=(url I want the api on)
    image: quay.io/minio/minio:latest
    volumes:
      - ./minio:/data
    restart: unless-stopped

networks:
  default:
    name: nginx
    external: true
```

and the nginx config like that:
```
server {
  set $forward_scheme http;
  set $server         "minio";
  set $port           9000;

  listen 80;
listen [::]:80;

listen 443 ssl http2;
listen [::]:443 ssl http2;


  server_name (the domain of the api);


  # Let's Encrypt SSL
  include conf.d/include/letsencrypt-acme-challenge.conf;
  include conf.d/include/ssl-ciphers.conf;
  ssl_certificate /etc/letsencrypt/live/npm-18/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/npm-18/privkey.pem;






  # Block Exploits
  include conf.d/include/block-exploits.conf;



  # HSTS (ngx_http_headers_module is required) (63072000 seconds = 2 years)
  add_header Strict-Transport-Security "max-age=63072000;includeSubDomains; preload" always;
  add_header Referrer-Policy strict-origin-when-cross-origin;
  add_header X-Content-Type-Options nosniff;
  add_header X-XSS-Protection "1; mode=block";
  add_header X-Frame-Options SAMEORIGIN;
  add_header Content-Security-Policy upgrade-insecure-requests;
  add_header Permissions-Policy interest-cohort=();
  add_header Expect-CT 'enforce; max-age=604800';
  add_header Host  $host;
  add_header X-Real-IP $remote_addr;
  add_header X-Forwarded-For $proxy_add_x_forwarded_for;






    # Force SSL
    include conf.d/include/force-ssl.conf;





  access_log /data/logs/proxy-host-40_access.log proxy;
  error_log /data/logs/proxy-host-40_error.log warn;



  location / {
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Scheme $scheme;
    proxy_set_header X-Forwarded-Proto  $scheme;
    proxy_set_header X-Forwarded-For    $remote_addr;
    proxy_set_header X-Real-IP          $remote_addr;
    proxy_pass       http://minio:9000;





  # Block Exploits
  include conf.d/include/block-exploits.conf;



    # Force SSL
    include conf.d/include/force-ssl.conf;




  # HSTS (ngx_http_headers_module is required) (63072000 seconds = 2 years)
  add_header Strict-Transport-Security "max-age=63072000;includeSubDomains; preload" always;
  add_header Referrer-Policy strict-origin-when-cross-origin;
  add_header X-Content-Type-Options nosniff;
  add_header X-XSS-Protection "1; mode=block";
  add_header X-Frame-Options SAMEORIGIN;
  add_header Content-Security-Policy upgrade-insecure-requests;
  add_header Permissions-Policy interest-cohort=();
  add_header Expect-CT 'enforce; max-age=604800';
  add_header Host  $host;
  add_header X-Real-IP $remote_addr;
  add_header X-Forwarded-For $proxy_add_x_forwarded_for;
  more_clear_headers 'X-Powered-By';








    proxy_set_header Host $http_host;
  }





  # Custom
  include /data/nginx/custom/server_proxy[.]conf;
}
```

Thank you!
