### DISCUSSION TITLE
Multi-Node Single-Drive

### DISCUSSION THREAD

**Discussion by leandroleal** [minio/minio#16047] [Q&A] [answered]
I have 2 new servers (`olympos` and `ocean` - we try to use meaningful names :grinning:) running in **RAID 6** (by hardware) with **237 TB** each, and I would like to have **474 TB** in my _MinIO setup_, without losing any storage space and enabling further horizontal expansion. Considering that the `fs backend` was [ripped out](https://github.com/minio/minio/discussions/15967), I tried a multi-node setup using `xl-single backend`.

```yaml
version: '3.7'

services:
  s3:
    container_name: minio_s3
    hostname: ${HOSTNAME}
    image: minio/minio:RELEASE.2022-10-20T00-55-09Z
    command: server --console-address ":9001" http://olympos/data http://ocean/data
    restart: ${RESTART_POLICY}
    ports:
      - "9000:9000"
      - "9001:9001"
    extra_hosts:
      - "ocean:192.168.1.64"
      - "olympos:192.168.1.65"
    environment:
      - TZ
      - MINIO_ROOT_USER=${ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${SECRET_KEY}
    volumes:
      - /mnt/${HOSTNAME}/.minio/data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 60s
      timeout: 60s
      retries: 3
```

And it's working fine.
```bash
$ mc admin info ocean
●  ocean:9000
   Uptime: 3 days 
   Version: 2022-10-20T00:55:09Z
   Network: 2/2 OK 
   Drives: 1/1 OK 
   Pool: 1

●  olympos:9000
   Uptime: 3 days 
   Version: 2022-10-20T00:55:09Z
   Network: 2/2 OK 
   Drives: 1/1 OK 
   Pool: 1

Pools:
   1st, Erasure sets: 1, Drives per erasure set: 2

17 TiB Used, 10 Buckets, 74,929 Objects
2 drives online, 0 drives offline
```

However after moving some data and check the usage space
```bash
$ df -h /mnt/ocean/ /mnt/olympos/
Filesystem                Size  Used Avail Use% Mounted on
//192.168.1.64/Ocean_w    237T   19T  218T   8% /mnt/ocean
//192.168.1.65/Olympos_w  237T   19T  218T   8% /mnt/olympos
```

... I'm not sure if the data is replicated or split on both servers. 

In a nutshell, I'm looking for a **Multi-Node Single-Drive** setup able to combine the storage space of `n` server without lose any storage space. I couldn't find it in the documentation / GitHub so I'm asking for help, thanks in advance.
