### DISCUSSION TITLE
Cannot get monitoring to work

### DISCUSSION THREAD

**Discussion by mindrunner** [minio/minio#16085] [Q&A] [answered]
I am using the Vanilla helm chart and latest minio in standalone mode.

```
environment:
  MINIO_PROMETHEUS_URL: http://prometheus-stack-kube-prom-prometheus.monitoring:9090
  MINIO_PROMETHEUS_AUTH_TYPE: "public"

metrics:
  serviceMonitor:
    enabled: true
    includeNode: true
    public: true
    relabelConfigs: {}
    relabelConfigsCluster: {}

```

The Grafana Dashboard seems to show some metrics, but buy far not all of them:
![image](https://user-images.githubusercontent.com/1413542/202484147-4095cad7-1a2e-44cd-b30b-7266de118d90.png)

Minio Console shows nothing:
![image](https://user-images.githubusercontent.com/1413542/202484375-9a9c158a-9e43-4f48-bc44-1c0546498a91.png)

Prometheus is scraping:
![image](https://user-images.githubusercontent.com/1413542/202484490-fe4b32a5-e98d-4a68-8480-3ab94c9adff4.png)

What am I missing here?

**Comment by eco-minio** [comment]
It isn't really possible for it to get some metrics and not others. The two things to check first off are what happens when you curl the prometheus endpoint of the MinIO ppds directly (you should see quite a few results come back). Assuming that is working, query prometheus itself for MinIO specific metrics. If you are using the UI just start typing minio and it will autocomplete for you if anything has been persisted. From within the minio pods curl should be there as well so make sure they can communicate to prometheus and vice versa. Last thing I would check is that your scrape job is named properly. If you are using something custom then you also need to set the job ID as well per the docs - https://min.io/docs/minio/linux/reference/minio-server/minio-server.html#envvar.MINIO_PROMETHEUS_JOB_ID

Is this the official MinIO grafana dashboard or something custom?

**Reply by mindrunner** [reply]
Thanks for the answer!

> It isn't really possible for it to get some metrics and not others. 

Yeah, that's what really confuses me as well.


> what happens when you curl the prometheus endpoint of the MinIO ppds directly

https://pastebin.com/ap9WHzbY


> If you are using the UI just start typing minio and it will autocomplete for you if anything has been persisted

Actually, this is kinda weird. I see the autocompletion, but data is empty :/
![image](https://user-images.githubusercontent.com/1413542/202708757-c05e7408-1d09-4518-8d9f-b60eaa47fb98.png)


> From within the minio pods curl should be there as well so make sure they can communicate to prometheus and vice versa

```
bash-4.4$ curl prometheus-stack-kube-prom-prometheus.monitoring:9090
<a href="/graph">Found</a>.
```


> Last thing I would check is that your scrape job is named properly. If you are using something custom then you also need to set the job ID as well per the docs

Ok, that's something I was not sure about. The helm chart deploys a ServiceMonitor CRD with more or less default settings:
```
metrics:
  serviceMonitor:
    enabled: true
    includeNode: true
    public: true
    relabelConfigs: {}
    relabelConfigsCluster: {}
```

Prometheus is configured in a way to scrape whatever it finds clusterwide and does not need any additional application specific configuration. The concept of setting job-id's is new to me and I might not fully understand it. The documentation is not really clear about where I am supposed to set them. I was assuming it's using the defaults if I don't override it anywhere.


>Is this the official MinIO grafana dashboard or something custom?

https://grafana.com/grafana/dashboards/13502-minio-dashboard/
