### DISCUSSION TITLE
Can the `edge-cicd` docker tag be updated

### DISCUSSION THREAD

**Discussion by williamdes** [minio/minio#16099] [Q&A]
It was added by https://github.com/minio/minio/pull/10933

This is really needed by GitHub actions users: https://github.com/orgs/community/discussions/26688#discussioncomment-4097866
My example: https://github.com/orgs/community/discussions/26688#discussioncomment-4183701

See: https://stackoverflow.com/a/64188150/5155484

Actual usage:

```yaml
        services:
            s3:
                # See: https://stackoverflow.com/a/64188150/5155484
                image: minio/minio:edge-cicd
                options: --health-cmd "curl -s http://localhost:9000/minio/health/live"
                env:
                    MINIO_ROOT_USER: dev
                    MINIO_ROOT_PASSWORD: admindev
        steps:
            - name: Fetch mc client
              run: curl -o ./mc -# https://dl.min.io/client/mc/release/linux-amd64/mc && chmod +x ./mc
            - name: Create the dev bucket
              run: ./mc alias set minio http://s3:9000 dev admindev && ./mc mb minio/dev-bucket
            - name: Remove mc client
              run: rm -v ./mc
           # this also could work: docker run --rm --entrypoint /bin/sh minio/mc -exu -c 'mc alias set minio http://s3:9000 dev admindev;mc mb minio/dev-bucket;'
           # - [...] checkout and stuff
```
