### DISCUSSION TITLE
S3 API Requests must be made to API port

### DISCUSSION THREAD

**Discussion by Podolyan98** [minio/minio#16252] [Q&A] [answered]
I deployed Minio via Docker:

```bash
mkdir -p ~/minio/data

sudo docker run \
   -p 9000:9000 \
   -p 9090:9090 \
   --name minio \
   -v ~/minio/data:/data \
   -e "MINIO_ROOT_USER=user" \
   -e "MINIO_ROOT_PASSWORD=12345" \
   quay.io/minio/minio server /data --console-address ":9090"

sudo docker update --restart unless-stopped e7f4e8530e6fbeac80ce16906effd14acfd0f7c863fdd4c4d6d7c5f6b9ea4ca2
```

Nginx config:

```bash
server {
   if ($host = docs.mydomain.com) {
      return 301 https://$host$request_uri;
   } # managed by Certbot

    listen 80;
    server_name docs.mydomain.com;
}
server {
    listen 443 ssl;
    server_name docs.mydomain.com;

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass       http://10.50.0.18:9090;
    }

    ssl_certificate /etc/letsencrypt/live/docs.mydomain.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/docs.mydomain.com/privkey.pem; # managed by Certbot
}
```

The site works at docs.mydomain.com, but the API does not work. How can I fix this?

**Comment by klauspost** [comment, marked as answer]
Port 9090 is the web console port
Port 9000 is the S3 API port.

**Reply by Podolyan98** [reply]
@klauspost Can you please tell me how to fix the Nginx configuration so I can access port 9000?

Need to add a new server { ... } block?

**Reply by harshavardhana** [reply]
https://github.com/minio/minio/blob/master/docs/orchestration/docker-compose/nginx.conf

**Comment by tan-yong-sheng** [comment]
I encountered a similar issue when running the following script, which requires S3 API requests to be made to the API port.

Here's the situation: I have deployed a MinIO instance on the cloud with an HTTPS domain name. While programming within that cloud, I attempted to connect to the MinIO instance using the localhost endpoint.

```
# Failed script
# Set up MinIO client
s3 = boto3.client('s3',
                  endpoint_url="https://<minio domain>", 
                  aws_access_key_id=minio_access_key,
                  aws_secret_access_key=minio_secret_key)

# List objects in the bucket
response = s3.list_buckets()['Buckets']
print(response)
```

Meanwhile, when I run the script via localhost to connect with my self hosted minio server, it works:
```
# Working script
# Set up MinIO client
s3 = boto3.client('s3',
                  endpoint_url='http://minio:9000',
                  aws_access_key_id=minio_access_key,
                  aws_secret_access_key=minio_secret_key)

# List objects in the bucket
response = s3.list_buckets()['Buckets']
print(response)
```

Here is my minio's deployment via docker compose.yml

```
version: '3.7'
services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_SERVER_URL=https://minio.${DOMAINNAME}
    volumes:
      - ./minio_data:/data
    command: server --console-address ":9001" /data
    depends_on:
      - minio-webhook
    labels:
      - traefik.enable=true
      - traefik.http.routers.minio.rule=Host(`minio.${DOMAINNAME}`)
      - traefik.http.routers.minio.entrypoints=websecure
      - traefik.http.routers.minio.tls=true
      - traefik.http.routers.minio.tls.certresolver=letsencrypt
      - traefik.docker.network=proxy
      - traefik.http.routers.minio.service=minio
      - traefik.http.services.minio.loadbalancer.server.port=9001
```

Hope for help, thanks.

**Reply by tan-yong-sheng** [reply]
I found the reason aldy, it's my Docker setup problem... I should set port 9000 to be the API endpoint via traefik loadbalancer


Now i could access my minio's public endpoint aldy, not localhost!
```
version: "3.7"

services:
  # guide to set up AWS lambda-like service for minio to receive webhook from minio
  # reference: https://blog.min.io/minio-webhook-event-notifications/
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_BROWSER_REDIRECT_URL=https://minioadmin.${DOMAINNAME}
    volumes:
      - ./minio_data:/data
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        minio server /data --console-address ":9001"
    labels:
      - traefik.enable=true
      - traefik.http.routers.minio.entrypoints=websecure
      - traefik.http.routers.minio.rule=Host(`minio.${DOMAINNAME}`)
      - traefik.http.routers.minio.service=minio
      - traefik.http.services.minio.loadbalancer.server.port=9000

      - traefik.http.routers.minioadmin.entrypoints=websecure
      - traefik.http.routers.minioadmin.rule=Host(`minioadmin.${DOMAINNAME}`)
      - traefik.http.routers.minioadmin.service=minioadmin
      - traefik.http.services.minioadmin.loadbalancer.server.port=9001 
      - traefik.docker.network=proxy

    networks:
      - proxy
      - internal

```
