### DISCUSSION TITLE
How run minio on docker-compose + nginx reverse proxy?

### DISCUSSION THREAD

**Discussion by robokonk** [minio/minio#16288] [Q&A]
Hey

I have problem with minio, not started on selected domain - 502 error.
- my docker-compose.yml for nginx proxy reverse + le
```
services:
    nginx:
        container_name: nginx
        image: nginxproxy/nginx-proxy
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - /var/docker/nginx/html:/usr/share/nginx/html
            - /var/docker/nginx/certs:/etc/nginx/certs
            - /var/docker/nginx/vhost:/etc/nginx/vhost.d
        logging:
            options:
                max-size: "10m"
                max-file: "3"

    letsencrypt-companion:
        container_name: nginx-le
        image: jrcs/letsencrypt-nginx-proxy-companion
        restart: unless-stopped
        volumes_from:
            - nginx
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/docker/nginx/acme:/etc/acme.sh
        environment:
            DEFAULT_EMAIL: mail@mail.com
```
- docker-compose.yml for minio
```
version: '2'

services:
  minio:
    container_name: minio.domain.com
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=supersecret
      - MINIO_BROWSER_REDIRECT_URL=https://minio.domain.com
      - MINIO_DOMAIN=minio.domain.com
    image: quay.io/minio/minio:latest
    volumes:
      - minio:/data
    restart: unless-stopped
    expose:
      - "9000"
      - "9001"
    environment:
      VIRTUAL_HOST: minio.domain.com
      LETSENCRYPT_HOST:  minio.domain.com
    networks:
      - proxy

networks:
  proxy:
    external:
      name: nginx_default

volumes:
 minio:
```
- logs from docker logs for minio container
```
Warning: Default parity set to 0. This can lead to data loss.
WARNING: Detected default credentials 'minioadmin:minioadmin', we recommend that you change these values with 'MINIO_ROOT_USER' and 'MINIO_ROOT_PASSWORD' environment variables
MinIO Object Storage Server
Copyright: 2015-2022 MinIO, Inc.
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Version: RELEASE.2022-12-12T19-27-27Z (go1.19.4 linux/amd64)

Status:         1 Online, 0 Offline.
API: http://192.168.0.7:9000  http://127.0.0.1:9000
Console: http://192.168.0.7:9001 http://127.0.0.1:9001

Documentation: https://min.io/docs/minio/linux/index.html
```

When I put in docker-compose for minio:
```
   ports:
      - '9000:9000'
      - '9001:9001'
```

Minio working, but for all domain on my server.
How I can fix that minio show only on minio.domain.com ?

**Comment by harshavardhana** [comment]
See here how to do this https://github.com/minio/minio/tree/master/docs/orchestration/docker-compose

**Reply by robokonk** [reply]
@harshavardhana 
Hey, thanks, I running according with your link, at the moment my configuration:
```
services:
  minio:
    container_name: sub.dom.com
    command: server /data --console-address ":80" 
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=supersecret
      - MINIO_BROWSER_REDIRECT_URL=https://sub.dom.com
      - MINIO_DOMAIN=sub.dom.com
      - VIRTUAL_HOST=sub.dom.com
      - LETSENCRYPT_HOST=sub.dom.com
    image: quay.io/minio/minio:latest
    volumes:
      - minio:/data
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - proxy

networks:
  proxy:
    external:
      name: nginx_default

volumes:
 minio:
 ```
 
 I running it on port 80, but api not working, what I should correct?
