### DISCUSSION TITLE
Minio console doesn't load objects in bucket

### DISCUSSION THREAD

**Discussion by hanslissi** [minio/minio#16722] [Q&A] [answered]
Hi! I have successfully installed a minio server on my own digital ocean server. The environment variables and the systemd config file are in place. I'm using nginx as a reverse proxy so, it my minio console can be accessed with my custom domain. That all works great! 

So, I have created a bucket and access keys using the minio console (web interface) and used the access keys for an application I'm building. From the application I've uploaded several pictures to the bucket. These pictures can be seen using the `mc ls` command:

```
$ mc ls -r medusa_minio
[2023-02-27 16:19:47 UTC] 2.7MiB STANDARD medusa/DSC_0005-1677514786882.JPG
[2023-02-27 16:17:17 UTC] 616KiB STANDARD medusa/Screenshot 2023-01-07 at 13.16.14-1677514637000.png
[2023-02-27 16:17:44 UTC] 408KiB STANDARD medusa/Screenshot 2023-02-05 at 16.02.22-1677514664714.png
[2023-02-27 16:17:58 UTC] 548KiB STANDARD medusa/Screenshot 2023-02-08 at 20.46.39-1677514678885.png
```

But when trying to view them in the minio console (web interface) it's loading forever and when inspecting it can be seen that the request to `/ws/objectManager` returns with the error `400 Bad Request`. Also the application that uses the access keys can't display the images. 

Does anyone know how I can solve this problem?

Here is my nginx config for my custom domain:
```
# Proxy Config from: https://min.io/docs/minio/linux/integrations/setup-nginx-proxy-with-minio.html
server {
    server_name my.custom.domain;
    listen [::]:443 ssl; # managed by Certbot
    listen 443 ssl; # managed by Certbot

    location / {
        proxy_pass http://IP.IP.IP.IP:MINIO_CONSOLE_PORT;
        include proxy_params;

        proxy_connect_timeout 300;
        # Default is HTTP/1, keepalive is only enabled in HTTP/1.1
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        chunked_transfer_encoding off;
    }

    # To allow special characters in headers
    ignore_invalid_headers off;
    # Allow any size file to be uploaded.
    # Set to a value such as 1000m; to restrict file size to a specific value
    client_max_body_size 0;
    # To disable buffering
    proxy_buffering off;

    ssl_certificate /etc/letsencrypt/live/my.custom.domain/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/my.custom.domain/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}

server {
    if ($host = my.custom.domain) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    listen [::]:80;

    server_name my.custom.domain;
    return 404; # managed by Certbot


}
```

**Comment by ravindk89** [comment, marked as answer]
https://github.com/minio/docs/pull/743

We're in the process of updating some of our nginx reverse proxy docs - at a glance it looks like there are several proxy-specific options missing in your config that maybe are preventing MinIO from working correctly from behind the proxy. 

If you can take a look at that PR - there is a staged view for simplicity - and try to pull some of those settings over, that might help.

**Comment by hanslissi** [comment]
Ok! Thanks, works now! I guess it was the missing websocket support :)
I added
```
proxy_request_buffering off;
```
and

```
real_ip_header X-Real-IP;
proxy_connect_timeout 300;

# To support websockets in MinIO versions released after January 2023
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
```
to my nginx config

Now my whole config looks like this (rearranged the lines a bit too):
```
server {
    listen [::]:443 ssl; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    server_name my.custom.domain;

    # To allow special characters in headers
    ignore_invalid_headers off;
    # Allow any size file to be uploaded.
    # Set to a value such as 1000m; to restrict file size to a specific value
    client_max_body_size 0;
    # To disable buffering
    proxy_buffering off;
    **proxy_request_buffering off;**

    location / {
        include proxy_params;

        **real_ip_header X-Real-IP;**

        proxy_connect_timeout 300;
        # To support websockets in MinIO versions released after January 2023
        proxy_http_version 1.1;
        **proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";**

        proxy_pass http://IP.IP.IP.IP:MINIO_CONSOLE_PORT/;
    }

    ssl_certificate /etc/letsencrypt/live/my.custom.domain/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/my.custom.domain/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}

server {
    if ($host = my.custom.domain) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    listen [::]:80;

    server_name my.custom.domain;
    return 404; # managed by Certbot
}
```

**Comment by Vishnu-yes-i-am** [comment]
can you please write the solution for apache too  for the same problem

**Comment by jerryoung** [comment]
i add the ws config for nginx, it is not work for me.
version:20230707
continue: kill ng, then   `/usr/sbin/nginx -c /etc/nginx/nginx.conf` , it is work.
if you run `nginx -sreload -t`, then it is not work, you can try my method.

**Comment by James-Oakley** [comment]
Yes, as @Vishnu-yes-i-am mentioned above, if someone could please share the solution for apache2 that would be a great help.

In another closed issue on here from a few years back, someone is linked to the documentation page for setting up minio behind an apache reverse proxy. That documentation page no longer exists (but wayback machine retrieved it and that helped me fix one thing I had done wrong). But the page vanished before minio introduced websockets, so it never got updated.

I've enabled the proxy_wstunnel module, and added these lines to my virtual host configuration:

```
RewriteEngine on
RewriteCond %{HTTP:UPGRADE} ^WebSocket$ [NC]
RewriteCond %{HTTP:CONNECTION} ^Upgrade$ [NC]
RewriteRule .* ws://127.0.0.1:9000%{REQUEST_URI} [P,L]
```
I've tried the RewriteRule with both port 9000 (S3 API port) and 9001 (console port), but neither fixes the problem: object don't load in the console's object browser, and the apache logs show status 400 against `GET /ws/objectManager`.

**Comment by Nils98Ar** [comment]
This works for me (console vHost):

```
[...]

RewriteEngine on
RewriteCond %{HTTP:UPGRADE} ^WebSocket$ [NC]
RewriteCond %{HTTP:CONNECTION} ^Upgrade$ [NC]
RewriteRule .* ws://127.0.0.1:9001%{REQUEST_URI} [P,L]

ProxyPass               /ws         ws://127.0.0.1:9001/

ProxyPass               /           http://127.0.0.1:9001/
ProxyPassReverse        /           http://127.0.0.1:9001/

[...]
```

**Comment by lukedupin** [comment]
I finally got mine working on apache2. 

First, make sure you've enabled rewrite_module and proxy_wstunnel

Here is my complete config:

```
# S3 console for editing
<VirtualHost *:443>
    ServerName s3-console.xxxxxx.com

  RewriteEngine on
  ProxyPreserveHost On
  RewriteCond %{HTTP:Upgrade} =websocket [NC]
  RewriteRule /(.*)           ws://localhost:4567/$1 [P,L]
  RewriteCond %{HTTP:Upgrade} !=websocket [NC]
  RewriteRule /(.*)           http://localhost:4567/$1 [P,L]

  ProxyPass / http://localhost:4567/
  ProxyPassReverse / http://localhost:4567/
  ProxyPass /ws ws://localhost:4567/ws
  ProxyPassReverse /ws ws://localhost:4567/ws
  ProxyRequests off


    Include /etc/letsencrypt/options-ssl-apache.conf
    SSLCertificateFile /etc/letsencrypt/live/xxxxxxxx/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/xxxxxxxxxx/privkey.pem
</VirtualHost>
```

Notice, my server console runs on port 4567, you'll need to change that to whatever yours runs on, maybe 9001.

**Comment by thp44** [comment]
I had the same issue, I solved it in nginx proxy manager, simple by checking this:
![image](https://github.com/user-attachments/assets/5afa4956-4388-44a7-920d-a1c28ac721f6)

**Reply by smkdev-platform** [reply]
Really helps a lot. Mine works now :raised_hands:

**Comment by n2nn2n** [comment]
I finally came around to upgrading my MinIO install from almost 2 years ago and discovered more features and more requirements. 
Came across the object not loading issue but I thought I had configured my WebSocket correctly. I finally realized that I was using https: not http: so I needed wss instead of ws

As a note; if I used the console url with the port - ie. https://minio.mydomain.com:5002, using ws was okay

Here's my complete setup if it helps anyone

**Setup:**
Internet -> Apache proxy/reverse (ip 192.168.11.111) -> MinIO server (ip 192.168.11.222)

**Ports:**
API port: 5001
Console port: 5002

**Browser Access:**
http -> https://minio.mydomain.com -> Console: https://console.minio.mydomain.com

API: https://minio.mydomain.com:5001
Console: https://console.minio.mydomain.com

**Environment Variables:**
```
MINIO_ROOT_USER="username"
MINIO_ROOT_PASSWORD="my_password"
MINIO_VOLUMES="/home/minio/miniodata/"
MINIO_OPTS="-C /etc/minio --address :5001 --console-address :5002  --certs-dir /etc/minio/certs/"
MINIO_DOMAIN="minio.mydomain.com"
MINIO_SERVER_URL="https://minio.mydomain.com:5001"
MINIO_BROWSER_REDIRECT_URL="https://console.minio.mydomain.com"
```

**Apache vHost:**
```
# Redirect HTTP to HTTPS
<VirtualHost 192.168.11.111:80>
    ServerName minio.mydomain.com

    RewriteEngine On
    RewriteCond %{HTTPS} off
    RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
</VirtualHost>

# HTTPS configuration for minio.mydomain.com (redirect to console)
<VirtualHost 192.168.11.111:443>
    ServerName minio.mydomain.com

    SSLEngine on
    SSLCertificateFile /my_path/ssl.cert
    SSLCertificateKeyFile /my_path/ssl.key

    # Redirect to the console
    RewriteEngine On
    RewriteRule ^(.*)$ https://console.minio.mydomain.com/ [R=301,L]
</VirtualHost>

# HTTPS configuration for console.minio.mydomain.com
<VirtualHost 192.168.11.111:443>
    ServerName console.minio.mydomain.com

    DocumentRoot /home/domains/minio.mydomain.com
    ErrorLog /var/log/console.minio.mydomain.com_error_log
    CustomLog /var/log/console.minio.mydomain.com_access_log combined

    SSLEngine on
    SSLProxyEngine On
    SSLCertificateFile /my_path/ssl.cert
    SSLCertificateKeyFile /my_path/ssl.key

    ProxyRequests Off
    ProxyPreserveHost On

    <Proxy *>
        Require all granted
    </Proxy>

    # Proxy all console traffic
    ProxyPass / https://192.168.11.222:50002/
    ProxyPassReverse / https://192.168.11.222:50002/

    # WebSocket Support
    RewriteEngine On
    RewriteCond %{HTTP:UPGRADE} ^WebSocket$ [NC]
    RewriteCond %{HTTP:CONNECTION} Upgrade$ [NC]
    RewriteRule .* wss://192.168.11.222:50002%{REQUEST_URI} [P]

    # Necessary Headers for MinIO
    RequestHeader set X-Forwarded-Proto https
    RequestHeader set Host %{HTTP_HOST}s

    # CORS Headers
    Header always set Access-Control-Allow-Origin "*"
    Header always set Access-Control-Allow-Methods "GET, PUT, POST, DELETE, OPTIONS"
    Header always set Access-Control-Allow-Headers "Authorization, Content-Type, X-Amz-Date, X-Amz-Security-Token, X-Requested-With"
</VirtualHost>
```

**Comment by santurini** [comment]
I am having the same error with a different stack.
I have MinIO deployed via Helm Chart on a kubernetes cluster and exposed via TLS on minio-console.mydomain.com, I can see the bucket that correctly shows the number of objects and the total size of the bucket, but if I try to navigate the bucket it just loads forever.
This is the `values.yaml` I used:
```
tenant:
  name: minio
  image:
    repository: quay.io/minio/minio
    tag: RELEASE.2024-11-07T00-52-20Z
    pullPolicy: IfNotPresent
  configuration:
    name: minio-env-configuration
  configSecret:
    name: minio-env-configuration
    accessKey: minio
    secretKey: minio123
  pools:
    - servers: 4
      name: tenant-pool
      volumesPerServer: 4
      size: 20Gi
      nodeSelector: { }
      affinity: { }
      resources: { }
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
        runAsNonRoot: true
      containerSecurityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        seccompProfile:
          type: RuntimeDefault
      topologySpreadConstraints: [ ]
  mountPath: /export
  subPath: /data
  metrics:
    enabled: false
    port: 9000
    protocol: http
  certificate:
    externalCaCertSecret: [ ]
    externalCertSecret: [ ]
    requestAutoCert: false
    certConfig: { }
  features:
    bucketDNS: false
    domains: { }
    enableSFTP: false
  buckets:
    - name: raw
      objectLock: false
      region: eu-central-1
  users: [ ]
  podManagementPolicy: Parallel
  prometheusOperator: false
  env: [ ]

ingress:
  api:
    enabled: true
    ingressClassName: "contour"
    labels: { }
    annotations: { }
    tls:
      - hosts:
        - minio.mydomain.com
        secretName: mydomain.com
    host: minio.mydomain.com
    path: /
  console:
    enabled: true
    ingressClassName: "contour"
    labels: { }
    annotations: { }
    tls:
      - hosts:
        - minio-console.mydomain.com
        secretName: mydomain.com
    host: minio-console.mydomain.com
    path: /
```

**Reply by santurini** [reply]
Just adding [this annotation](https://projectcontour.io/docs/v1.5.0/annotations/) solved the problem, full ingress definition:
```
ingress:
  console:
    enabled: true
    ingressClassName: "contour"
    labels: { }
    annotations:
      projectcontour.io/websocket-routes: "/"
    tls:
      - hosts:
        - minio-console.mydomain.com
        secretName: mydomain.com
    host: minio-console.mydomain.com
    path: /
```
