### DISCUSSION TITLE
How use old SSE-C key after RELEASE.2021-04-22T15-44-28Z

### DISCUSSION THREAD

**Discussion by F1asher** [minio/minio#16936] [Q&A] [answered]
Hello, I'm new to minio. I'm using a very old version of minio (RELEASE.2020-07-22T00-26-33Z) still with fs-backend. I wanted to update it, but I only managed to update to RELEASE.2021-04-22T15-44-28Z. In later versions, the MINIO_SSE_MASTER_KEY environment variable has been removed.

How can I use my old key to encrypt new files and decrypt old files in later versions?
MINIO_SSE_MASTER_KEY: "minio-key:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
I tried converting the HEX key value to base64 and passing it to the MINIO_KMS_SECRET_KEY environment variable, but failed:
(ERROR Unable to parse the KMS secret key inherited from the shell environment: kms: invalid master key format).
I also tried updating to a newer version than RELEASE.2021-04-22T15-44-28Z and accessing encrypted files using the mc utility:
$ mc cp my-minio/my-bucket/ENC-FILE ./test/ENC-FILE --encrypt-key "my-minio/my-bucket/=bWluaW8ta2V5OmFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhY"
mc: <ERROR> Unable to parse encryption keys. Encryption key should be 32 bytes plain text key or 44 bytes base64 encoded key.

I would like to upgrade at least to the version in which the FS-backend was removed. Or to the newest, but keep the data and use my encryption key.

Any help is welcome. Thank you in advance.

**Comment by F1asher** [comment]
minio-deploy.yaml

```
services:
  old_minio:
    image: minio/minio:RELEASE.2022-08-05T23-27-09Z
    volumes:
        - ./storage/old/vol/:/data/
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_SSE_AUTO_ENCRYPTION: on
      MINIO_SSE_MASTER_KEY: "minio-key:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
      MINIO_HTTP_TRACE: /dev/stderr
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
```
