### DISCUSSION TITLE
How to Shere File? why the generated link does not work

### DISCUSSION THREAD

**Discussion by POMXARK** [minio/minio#16975] [Q&A]
![image](https://user-images.githubusercontent.com/18720947/230031221-1af344a8-e46a-4885-9c61-7d8ee837da5e.png)

Similarly here
https://play.min.io:9443/

Does this functionality work?
How to use in a docker
How to configure this? What are the requirements?
```
version: '3.9'

services:
  minio:
    image: minio/minio:latest
    command: server --address ":9000" --console-address ":9001" /data/
    expose:
      - "9000"
      - "9001"
    ports:
      - ${MINIO_API_PORT:-0}:9000
      - ${MINIO_WEB_PORT:-0}:9001
    environment:
      MINIO_ROOT_USER: ${MINIO_USER:-0}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD:-0}
    volumes:
      - minio-storage:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  minio-storage:
  ```
