### DISCUSSION TITLE
Failed to load resource: the server responded with a status of 403 ()

### DISCUSSION THREAD

**Discussion by peveloper** [minio/minio#17118] [Q&A] [answered]
```
version: '3.6' 
services:
  postgres:
    image: postgres:11
    volumes:
      - videocharlietools_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?err}
    networks:
    - videocharlietools_default
    ports:
    - "5432:5432"
  graphql-engine:
    image: hasura/graphql-engine:latest
    ports:
    - "8080"
    depends_on:
    - "postgres"
    restart: always
    networks:
    - videocharlietools_default
    volumes:
    - type: bind
      source: ./certificates/_sauber-motorsport_com.crt
      target: /etc/ssl/certs/selfsigned.crt
      read_only: true
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://${POSTGRES_USER:?err}:${POSTGRES_PASSWORD:?err}@postgres:5432/postgres
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      PG_DATABASE_URL: postgres://${POSTGRES_USER:?err}:${POSTGRES_PASSWORD:?err}@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    networks:
    - videocharlietools_default
    volumes:
      - /mnt/swd-docker:/data
    environment:
      MINIO_ROOT_USER: ${VITE_MINIO_USER:?err}
      MINIO_ROOT_PASSWORD: ${VITE_MINIO_PASSWORD:?err}
    ports:
    - "9000"
    - "9001"
  caddy:
    image: caddy/caddy
    depends_on:
    - "graphql-engine"
    - "minio"
    restart: always
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./Caddyfile:/etc/caddy/Caddyfile
    - ./certificates:/data
    networks:
      - videocharlietools_default
networks:
  videocharlietools_default:
    external: true
volumes:
  videocharlietools_db_data:
    external: true
```

The above is my docker-compose. the /mnt/swd-docker is a SMB Azure file storage mounted on my host machine (Ubuntu 20.04). I can see that the owner is the same as the one used by docker. 

```
mc stat swd-docker
Name      : swd-docker/
Date      : 2022-12-09 14:58:42 UTC 
Type      : folder 
Metadata  :
  X-Amz-Meta-Mc-Attrs: atime:1670597922#351130800/gid:998/gname:docker/mode:16895/mtime:1670597922#351130800/uid:1000/uname:charly_tool 
  Content-Type       : application/octet-stream 
```

This is my Caddyfile

```

devvideo.sauber-motorsport.com {
  tls /data/_sauber-motorsport_com.cer /data/sauber-motorsport.key
  reverse_proxy video:3000
  header {
    Cross-Origin-Embedder-Policy "require-corp"
    Cross-Origin-Opener-Policy "same-origin"
  }
}

devhasura.sauber-motorsport.com {
  tls /data/_sauber-motorsport_com.cer /data/sauber-motorsport.key
  reverse_proxy graphql-engine:8080
}

devminio.sauber-motorsport.com {
  tls /data/_sauber-motorsport_com.cer /data/sauber-motorsport.key
  reverse_proxy minio:9000
  reverse_proxy /videos/* minio:9000 {
    flush_interval -1
  }
}

devupload.sauber-motorsport.com {
  tls /data/_sauber-motorsport_com.cer /data/sauber-motorsport.key
  reverse_proxy minio:9001
}

devcharlie.sauber-motorsport.com {
  tls /data/_sauber-motorsport_com.cer /data/sauber-motorsport.key
  reverse_proxy charlie:3001
}

http://devvideo.sauber-motorsport.com, http://devhasura.sauber-motorsport.com, http://devcharlie.sauber-motorsport.com, http://devminio.sauber-motorsport.com {
  redir https://{host}{uri}
}
```

I am able to listObjects, access the console and upload and download files via the console. My problem is when trying to bind a src property to the url of the object
`
<video bind:this={video} src={url} controls preload="auto"  crossorigin="anonymous" >`

url looks like this

`"https://devminio.sauber-motorsport.com/videos/" + data?.path;`

What could the issue be?
