### DISCUSSION TITLE
Minio bucket replication with SSE-S3 encryption problem

### DISCUSSION THREAD

**Discussion by amirAlamian** [minio/minio#17595] [Q&A]
Hi I have two minio stances with SSE-S3 encryption enabled using minio/kes and hashicorp vault. when I setup replication between my minio instances for a bukcket that its name is public, first it works for about a minute but after that, I get this error in replication target minio and replication stops:
```
DeploymentID: 89be6e21-8a84-4e91-9689-87c9b5fa083a
not authorized: insufficient permissions (kes.Error)
```

and this error in kes server

```
{"time":"2023-07-07T11:14:48.583146888Z","request":{"ip":"192.177.0.2","path":"/v1/status"},"response":{"code":403,"time":16000}}
```

and my docker config is:

```
version: '3.8'

networks:
  storage-network:
    ipam:
      driver: default
      config:
        - subnet: 192.177.0.0/25
          gateway: 192.177.0.1

services:
  app-minio1:
    image: minio/minio
    restart: always
    container_name: app-minio
    depends_on:
      - minio-kes1
    volumes:
      - /mnt/minio:/data
      - ./Minio/env/minio:/etc/default/minio/minio
      - ./Minio/KES/certs:/etc/default/minio/certs
    environment:
      - 'MINIO_ROOT_USER=${MINIO_USERNAME}'
      - 'MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}'
      - MINIO_CONFIG_ENV_FILE=/etc/default/minio/minio
    ports:
      - 9001:9001
      - 9000:9000
    command: server --console-address ":9001" /data
    networks:
      storage-network:
        ipv4_address: 192.177.0.2
  valut1:
    image: vault:1.13.3
    restart: always
    container_name: vault
    cap_add:
      - IPC_LOCK
    environment:
      - 'VAULT_LOCAL_CONFIG={"backend": {"file": {"path": "/vault/file"}}, "default_lease_ttl": "168h", "max_lease_ttl": "720h"}'
      -  VAULT_ADDR=http://127.0.0.1:8200
    ports:
      - '8200:8200'
    volumes:
      - /vault:/vault
      - ./Vault:/etc/vault
    command: server -config /etc/vault/main.hcl
    networks:
      storage-network:
        ipv4_address: 192.177.0.3
  minio-kes1:
    image: minio/kes
    container_name: minio-kes
    restart: always
    volumes:
      - ./Minio/KES:/root/.kes
    environment:
    - KES_SERVER=https://0.0.0.0:7373
    - KES_CLIENT_CERT=/root/.kes/certs/minio-kes.cert
    - KES_CLIENT_KEY=/root/.kes/certs/minio-kes.key
    ports:
      - 7373:7373
    cap_add:
      - IPC_LOCK
    command: server --config=/root/.kes/config/config.yaml --auth=off 
    networks:
      storage-network:
        ipv4_address: 192.177.0.4
  app-minio3:
    image: minio/minio
    restart: always
    container_name: app-minio3
    depends_on:
      - minio-kes3
    volumes:
      - /mnt/minio3:/data
      - ./Minio3/env/minio:/etc/default/minio/minio
      - ./Minio3/KES/certs:/etc/default/minio/certs
    environment:
      - 'MINIO_ROOT_USER=${MINIO_USERNAME}'
      - 'MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}'
      - MINIO_CONFIG_ENV_FILE=/etc/default/minio/minio
    ports:
      - 9005:9001
      - 9004:9000
    command: server --console-address ":9001" /data
    networks:
      storage-network:
        ipv4_address: 192.177.0.8
  valut3:
    image: vault:1.13.3
    restart: always
    container_name: vault3
    cap_add:
      - IPC_LOCK
    environment:
      - 'VAULT_LOCAL_CONFIG={"backend": {"file": {"path": "/vault/file"}}, "default_lease_ttl": "168h", "max_lease_ttl": "720h"}'
      -  VAULT_ADDR=http://127.0.0.1:8200
    ports:
      - '8203:8200'
    volumes:
      - /vault3:/vault
      - ./Vault:/etc/vault
    command: server -config /etc/vault/main.hcl
    networks:
      storage-network:
        ipv4_address: 192.177.0.9
  minio-kes3:
    image: minio/kes
    container_name: minio-kes3
    restart: always
    volumes:
      - ./Minio3/KES:/root/.kes
    environment:
    - KES_SERVER=https://0.0.0.0:7373
    - KES_CLIENT_CERT=/root/.kes/certs/minio-kes.cert
    - KES_CLIENT_KEY=/root/.kes/certs/minio-kes.key
    ports:
      - 7375:7373
    cap_add:
      - IPC_LOCK
    command: server --config=/root/.kes/config/config.yaml --auth=off 
    networks:
      storage-network:
        ipv4_address: 192.177.0.10


```

and this is replication config in my other minio instance:

![image](https://github.com/minio/minio/assets/65771812/f542dd9b-cd32-4693-976e-f461c6f956a8)

when I am not using SSE-S3, replication works perfectly but when I connect minio to kes it does not work.

can you help me. please tell me if you need more information
