### DISCUSSION TITLE
Creating a cluster via docker compose on the 1 host.

### DISCUSSION THREAD

**Discussion by rubl91** [minio/minio#17653] [Q&A] [answered]
I want to create a cluster of two Minio servers on the host, I have a software raid 5 array of three disks. I created 4 directories for data for each containser, named it s1 s2 s3 s4, but i've got an error **Error: Marking minio1:9000 offline temporarilly caused by Post "http://minio:9000/minio/storage/data2/v49/readall?disk-id&file-path=format.json&volume=.minio.sys"**

docker-compose.yaml
```
version: '3.7'

x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2023-07-11T21-29-34Z
  command: server --console-address ":9000" http://minio{1...4}/data/s{1...4}
  ports:
    - "9000"
    - "9000"

  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3


services:
  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - /data2/compose:/data2
      - /etc/default/minio:/etc/config.env

  minio2:
    <<: *minio-common
    hostname: minio2
   volumes:
      - /data2/compose:/data2
      - /etc/default/minio:/etc/config.env
    
  minio3:
    <<: *minio-common
    hostname: minio3
   volumes:
      - /data2/compose:/data2
      - /etc/default/minio:/etc/config.env
     
  minio4:
    <<: *minio-common
    hostname: minio2
   volumes:
      - /data2/compose:/data2
      - /etc/default/minio:/etc/config.env


     nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4

```

**Comment by rubl91** [comment]
I'll tried to create 2 containers, like this. But it says: "Unable to initialize backend: /data2/s1 drive is already being used in another erasure deployment. (Number of drives specidied: 4 but the number of drives found on the 2nd drive's format.json: 12"

```
version: '3.7'

x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2023-07-11T21-29-34Z
  command: server --console-address ":9000" http://minio{1...4}/data/s{1...2}
  ports:
    - "9000"
    - "9000"

  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3


services:
  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - /data2/compose:/s1
      - /etc/default/minio:/etc/s2

  minio2:
    <<: *minio-common
    hostname: minio2
   volumes:
      - /data2/compose:/s1
      - /etc/default/minio:/s2
  

     nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio1
      - minio2
    
```
