### DISCUSSION TITLE
Batch replicate not working

### DISCUSSION THREAD

**Discussion by CGsama** [minio/minio#17679] [Q&A] [answered]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior

adding batchfile

## Current Behavior

{"Code":"NoSuchSourceBucket","Message":"The specified bucket [remote-bucket-name] does not exist","Resource":"/minio/admin/v3/start-job",

## Steps to Reproduce (for bugs)

![image](https://github.com/minio/minio/assets/15722562/70d7e21b-2af2-483d-8560-3ec9fb7c9b2d)

run with mc batch start --debug myalias ./filenamel.yaml

## Context

try to replicate to cloud as backup, intent using cheap provider like idrivee2, but got error, then try to use aws still instant throw the same error

## Your Environment

minio version RELEASE.2023-06-09T07-32-12Z (commit-id=6b7c98bd0fde630c6aee78d702b9d37b0200f52c)
Linux minio 5.15.0-73-generic #80-Ubuntu SMP Mon May 15 15:18:26 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

running the executable alone in tmux

**Comment by CGsama** [comment]
![image](https://github.com/minio/minio/assets/15722562/611c0129-1301-4c5d-b454-61e098e75ac6)
dont think it even talk to the remote server

**Comment by harshavardhana** [comment]
It says that your remote bucket doesn't exist

**Reply by CGsama** [reply]
im running fine with plain mc mirror, and the error code is source bucket not exist

**Reply by CGsama** [reply]
https://minio.slack.com/archives/C3NDUB8UA/p1689709943919419

**Reply by ravindk89** [reply]
@CGsama one thing I thought of - can you provide your full YAML here instead of the generic one? You can omit passwords/hostnames, but seeing the full thing would help.

To summarize the conversation in slack, the remote bucket setup works fine w/ `mc mirror`, but not `batch replicate` - which w/ S3 remote or source *should* have `mc mirror`-like semantics

**Reply by CGsama** [reply]
the full yaml is
```
replicate:
  apiVersion: v1
  source:
    type: "minio"
    bucket: "local-bucket"
    endpoint: "local"
    credentials:
      accessKey: "xxxx"
      secretKey: "xxxx"
  target:
    type: "s3"
    bucket: "remote-bucket"
    endpoint: "s3.us-east-1.amazonaws.com"
    credentials:
      accessKey: "xxxx"
      secretKey: "xxxx"
  retry:
    attempts: 10
    delay: "5000ms"
```

**Comment by CGsama** [comment]
Its really wired the remote bucket name show up in the "NoSuchSourceBucket" error, more like should be at "NoSuchTargetBucket"
https://github.com/minio/minio/blob/0120ff93bc4b9cfaf2865e55850e9b20e5ef703d/cmd/batch-handlers.go#L1356C22-L1356C40
might be the yaml parser got something wong

**Comment by CGsama** [comment]
the issue is https://github.com/minio/minio/blob/0120ff93bc4b9cfaf2865e55850e9b20e5ef703d/cmd/batch-handlers.go#L1246 here check the endpoint if its empty, but empty wont be valid input, doc says it must be "local", then cause it localBkt will always be the target one

**Reply by CGsama** [reply]
https://github.com/minio/minio/blob/0120ff93bc4b9cfaf2865e55850e9b20e5ef703d/cmd/batch-handlers.go#L1278

**Reply by ravindk89** [reply]
@poornas can you review ? Maybe our docs also need some refinement here based on where `local` is supposed to go, if it's not `endpoint`.

**Comment by poornas** [comment]
@CGsama , the batch yaml is incorrect - the endpoint and credentials should be specified only for the remote, not the local minio cluster from which you are running the batch job. The only time creds and endpoint will be specified is if your source happens to be a remote cluster

change your source: section like below
```
source:
    type: "minio"
    bucket: "local-bucket"
```

**Reply by ravindk89** [reply]
I'll update our docs to make this clearer as well - thanks!

**Reply by CGsama** [reply]
if i dont provide endpoint, it will throw inv arg
![image](https://github.com/minio/minio/assets/15722562/10f67706-855c-46c7-bc3b-f216637df5b4)

**Reply by poornas** [reply]
you need to remove these lines from source: section in your yaml, or comment it out. 

```
    endpoint: "local"
    credentials:
      accessKey: "xxxx"
      secretKey: "xxxx"
   ```

**Reply by CGsama** [reply]
i did it

**Comment by harshavardhana** [comment]
The correct yaml - writing it here to avoid more bike-shedding on this topic. 

```yaml
replicate:
  apiVersion: v1
  source:
    type: "minio"
    bucket: "local-bucket"

  target:
    type: "s3"
    bucket: "remote-bucket"
    endpoint: "https://s3.us-east-1.amazonaws.com"
    credentials:
      accessKey: "xxxx"
      secretKey: "xxxx"
  retry:
    attempts: 10
    delay: "5000ms"
```
