### DISCUSSION TITLE
KES CLI error: certificate signed by unknown authority

### DISCUSSION THREAD

**Discussion by kukulam-form3** [minio/minio#17739] [Q&A] [answered]
# Context
I am enabling encryption at rest by following this documentation: [Server-Side Object Encryption with Hashicorp Vault Root KMS](https://min.io/docs/minio/linux/operations/server-side-encryption/configure-minio-kes-hashicorp.html). I setup everything and it's working fine. Minio is able to connect to KES and create a key, but when I want to create key manually with KES CLI then I got a problem:
```bash
bash-4.4$ /kes key create minio-key
Error: failed to create key "minio-key": Post "https://minio-kes.minio.svc.cluster.local:7373/v1/key/create/minio-key": tls: failed to verify certificate: x509: certificate signed by unknown authority
```

### Docker images
```
minio/kes:2023-05-02T22-48-10Z
```
### Kes config
```yaml
address: 0.0.0.0:7373

admin:
  identity: disabled

tls:
  key:  /etc/kes/certs/tls.key
  cert: /etc/kes/certs/tls.crt
  ca: /etc/kes/certs/ca.crt

policy:
  minio:
    allow:
      - /v1/key/create/minio-*
      - /v1/key/generate/minio-*
      - /v1/key/decrypt/minio-*
      - /v1/key/bulk/decrypt
      - /v1/key/list
      - /v1/status
      - /v1/metrics
      - /v1/log/audit
      - /v1/log/error
    identities:
      - HASH

keystore:
  vault:
    endpoint: http://vault.vault.svc.cluster.local:8200
    engine: "secret"
    version: "v2"
    approle:
      id: ID
      secret: SECRET
      retry: 15s
    status:
      ping: 10s
    tls:
      ca: /etc/kes/certs/ca.crt
```

### Pod's envs where I run `kes` CLI:
```
KES_SERVER=https://minio-kes.minio.svc.cluster.local:7373
KES_CLIENT_KEY=/etc/kes/certs/client/tls.key
KES_CLIENT_CERT=/etc/kes/certs/client/tls.crt
```

## Skipping TLS certificate validation
I know that I can add flag `-k` to skip tls verification (and then it's working), but I would like to use CLI without skipping this check.

I am using self signed certificates created by cert-manager on k8s. I believe that there should be an option to set `CAPATH` for KES CLI, but I couldn't find it. I also found very [similar discussion](https://github.com/minio/minio/discussions/14630), but here is no information how to setup `CA` for KES CLI. 

# Question
Is it possible to use KES CLI without skipping TLS certificate validation with self signed certificates ?
