### DISCUSSION TITLE
KES Vault with kubernetes service account

### DISCUSSION THREAD

**Discussion by kukulam-form3** [minio/minio#17785] [Q&A] [answered]
# Context
I am enabling encryption at rest by following this documentation: [Server-Side Object Encryption with Hashicorp Vault Root KMS](https://min.io/docs/minio/linux/operations/server-side-encryption/configure-minio-kes-hashicorp.html). I see that there is an example how to setup integration KES with Vault by setting up appRole, but we would like to integrate KES with Vault using kubernetes service account. I checked KES [configuration](https://github.com/minio/kes/blob/a3d7ee1b6d86e6303d16c4b282039100ddfb6a0f/server-config.yaml#L268) and there is a section `kubernetes` in part of vault configuration, also there is a [test](https://github.com/minio/kes/blob/a3d7ee1b6d86e6303d16c4b282039100ddfb6a0f/edge/config_test.go#L189) checking that config ([test config](https://github.com/minio/kes/blob/master/edge/testdata/vault-k8s-with-service-account-file.yml#L19C19-L19C19)).

I managed to use KES with kubernetes service account, but I got error when server starts (`Error: open JWT: file name too long`):

- using [JWT from test](https://github.com/minio/kes/blob/master/edge/testdata/vault-k8s-service-account)
```bash
Error: open eyJhbGciOiJSUzI1NiIsImtpZCI6IkJQbGNNeTdBeXdLQmZMaGw2N1dFZkJvUmtsdnVvdkxXWGsteTc5TmJPeGMifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJteS1uYW1lc3BhY2UiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoibXktc2VydmljZS1hY2NvdW50LXRva2VuLXA5NWRyIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6Im15LXNlcnZpY2UtYWNjb3VudCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjdiYmViZGE2LTViMDUtNGFlNC05Yjg2LTBkODE0NWMwNzdhNSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpteS1uYW1lc3BhY2U6bXktc2VydmljZS1hY2NvdW50In0.dnvJE3LU7L8XxsIOwea3lUZAULdwAjV9_crHFLKBGNxEu70lk3MQmUbGTEFvawryArmxMa1bWF9wbK1GHEsNipDgWAmc0rmBYByP_ahlf9bI2EEzpaGU5s194csB_eG7kvfi1AHED_nkVTfvCjIJM-9oGICCjDJcoNOP1NAXICFmqvWfXl6SY3UoZvtzUOcH9-0hbARY3p6V5pPecW4Dm-yGub9PKZLJNzv7GxChM-uvBvHAt6o0UBIL4iSy6Bx2l91ojB-RSkm_oy0W9gKi9ZFQPgyvcvQnEfjoGdvNGlOEdFEdXvl-dP6iLBPnZ5xwhAk8lK0oOONWvQg6VDNd9w: file name too long
```
- using my JWT generated by kubernetes service account
```bash
Error: open eyJhbGciOiJSUzI1NiIsImtpZCI6ImhPTVlvVjhzWGVhTXhvUEZSUXd4SnhmZVlFd3VTZ2V4X0FndjN4eTRVRGsifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJtaW5pbyIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJtaW5pby1rZXMtc2EtdG9rZW4iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibWluaW8ta2VzIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiY2M1ZTVkNzUtZDdhZC00ODNhLTljZDMtMDlmMjIyMjlkM2JhIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Om1pbmlvOm1pbmlvLWtlcyJ9.M-k00acuSalbhrzUErcFokxlO0fqHGZn7j_zeZ6orawyGyBiK1-S94Wh4gurbOCDTX1RyQxU03Irk02e7ctWCwfzdQRaE4oZ9pWfqjpPoU_3JMbhHwGkyGkJ_Ek-R-qOYNDWl5r9RNL64Q6Ikdv4HTcHjXyM11c1WBzQIMeisPFf-f0fFx730GQyHGU9qpH2osZnDLBdpmGVBtZA7juiAIhyy2YQvyxCKjQJzvtijclA6i0adG4KC6b7bKiQr930mnU9epyg5Dx4TwVubFqs-4vh9aidn6OnNdZoMUHWybcLMIrh0Mf2Bpg_6-CVjVsfjrRpOZgB_DjDU8xR-j0HQg: file name too long
```

### Docker images
```
minio/kes:2023-05-02T22-48-10Z
vault:1.12.2
```
### Kes config
```yaml
    address: 0.0.0.0:7373

    admin:
      identity: ADMIN_IDENTITY_HASH

    tls:
      key:  /etc/kes/certs/tls.key
      cert: /etc/kes/certs/tls.crt
      ca: /etc/kes/certs/ca.crt

    # api docs: "https://github.com/minio/kes/wiki/Server-API"
    policy:
      minio:
        allow:
          - /v1/key/create/minio-*
          - /v1/key/generate/minio-*
          - /v1/key/encrypt/minio-*
          - /v1/key/decrypt/minio-*
          - /v1/key/info/minio-*
          - /v1/enclave/describe/minio-*
          - /v1/key/bulk/decrypt/minio-*
          - /v1/key/list/*
          - /v1/policy/describe/*
          - /v1/policy/read/*
          - /v1/policy/list/*
          - /v1/identity/describe/*
          - /v1/identity/list/*
          - /v1/identity/self/describe
          - /version
          - /v1/api
          - /v1/metrics
          - /v1/status
          - /v1/log/audit
          - /v1/log/error
        identities:
          - MINIO_IDENTITY_HASH

    keystore:
      vault:
        endpoint: http://vault.vault.svc.cluster.local:8200
        engine: secret
        prefix: minio
        version: v2
        kubernetes:
          engine: kubernetes
          role: minio-kes
          jwt: eyJhbGciOiJSUzI1NiIsImtpZCI6IkJQbGNNeTdBeXdLQmZMaGw2N1dFZkJvUmtsdnVvdkxXWGsteTc5TmJPeGMifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJteS1uYW1lc3BhY2UiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoibXktc2VydmljZS1hY2NvdW50LXRva2VuLXA5NWRyIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6Im15LXNlcnZpY2UtYWNjb3VudCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjdiYmViZGE2LTViMDUtNGFlNC05Yjg2LTBkODE0NWMwNzdhNSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpteS1uYW1lc3BhY2U6bXktc2VydmljZS1hY2NvdW50In0.dnvJE3LU7L8XxsIOwea3lUZAULdwAjV9_crHFLKBGNxEu70lk3MQmUbGTEFvawryArmxMa1bWF9wbK1GHEsNipDgWAmc0rmBYByP_ahlf9bI2EEzpaGU5s194csB_eG7kvfi1AHED_nkVTfvCjIJM-9oGICCjDJcoNOP1NAXICFmqvWfXl6SY3UoZvtzUOcH9-0hbARY3p6V5pPecW4Dm-yGub9PKZLJNzv7GxChM-uvBvHAt6o0UBIL4iSy6Bx2l91ojB-RSkm_oy0W9gKi9ZFQPgyvcvQnEfjoGdvNGlOEdFEdXvl-dP6iLBPnZ5xwhAk8lK0oOONWvQg6VDNd9w
        status:
          ping: 10s
        tls:
          ca: /etc/kes/certs/ca.crt
```

### My JWT generated by kubernetes service account
```
eyJhbGciOiJSUzI1NiIsImtpZCI6ImhPTVlvVjhzWGVhTXhvUEZSUXd4SnhmZVlFd3VTZ2V4X0FndjN4eTRVRGsifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJtaW5pbyIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJtaW5pby1rZXMtc2EtdG9rZW4iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibWluaW8ta2VzIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiY2M1ZTVkNzUtZDdhZC00ODNhLTljZDMtMDlmMjIyMjlkM2JhIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Om1pbmlvOm1pbmlvLWtlcyJ9.M-k00acuSalbhrzUErcFokxlO0fqHGZn7j_zeZ6orawyGyBiK1-S94Wh4gurbOCDTX1RyQxU03Irk02e7ctWCwfzdQRaE4oZ9pWfqjpPoU_3JMbhHwGkyGkJ_Ek-R-qOYNDWl5r9RNL64Q6Ikdv4HTcHjXyM11c1WBzQIMeisPFf-f0fFx730GQyHGU9qpH2osZnDLBdpmGVBtZA7juiAIhyy2YQvyxCKjQJzvtijclA6i0adG4KC6b7bKiQr930mnU9epyg5Dx4TwVubFqs-4vh9aidn6OnNdZoMUHWybcLMIrh0Mf2Bpg_6-CVjVsfjrRpOZgB_DjDU8xR-j0HQg
```

### JWT from KES test ([test config](https://github.com/minio/kes/blob/master/edge/testdata/vault-k8s-service-account))
```
eyJhbGciOiJSUzI1NiIsImtpZCI6IkJQbGNNeTdBeXdLQmZMaGw2N1dFZkJvUmtsdnVvdkxXWGsteTc5TmJPeGMifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJteS1uYW1lc3BhY2UiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoibXktc2VydmljZS1hY2NvdW50LXRva2VuLXA5NWRyIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6Im15LXNlcnZpY2UtYWNjb3VudCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjdiYmViZGE2LTViMDUtNGFlNC05Yjg2LTBkODE0NWMwNzdhNSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpteS1uYW1lc3BhY2U6bXktc2VydmljZS1hY2NvdW50In0.dnvJE3LU7L8XxsIOwea3lUZAULdwAjV9_crHFLKBGNxEu70lk3MQmUbGTEFvawryArmxMa1bWF9wbK1GHEsNipDgWAmc0rmBYByP_ahlf9bI2EEzpaGU5s194csB_eG7kvfi1AHED_nkVTfvCjIJM-9oGICCjDJcoNOP1NAXICFmqvWfXl6SY3UoZvtzUOcH9-0hbARY3p6V5pPecW4Dm-yGub9PKZLJNzv7GxChM-uvBvHAt6o0UBIL4iSy6Bx2l91ojB-RSkm_oy0W9gKi9ZFQPgyvcvQnEfjoGdvNGlOEdFEdXvl-dP6iLBPnZ5xwhAk8lK0oOONWvQg6VDNd9w
```

### Filepath
Instead of putting whole JWT in config file I also tested scenario with setting path to JWT token, but I got the same error.
```yaml
jwt: /etc/secrets/token
```

# Question
Is it bug or I am doing something wrong ? Do you have maybe some documentation how to setup KES with Vault using k8s service account ?
