### DISCUSSION TITLE
docker compose cluster replicate error

### DISCUSSION THREAD

**Discussion by sunsjgit** [minio/minio#17786] [Q&A]
I'm going to take a look at this website [https://github.com/minio/minio/tree/5317a0b755b0788d543d88974d3db73b9ee988c9/docs/orchestration/docker-compose](https://github.com/minio/minio/tree/5317a0b755b0788d543d88974d3db73b9ee988c9/docs/orchestration/docker-compose)

mc 
```
[work@hn minio]$ ./mc -version
mc version RELEASE.2023-07-21T20-44-27Z (commit-id=1c17ff4c995d772c97eed8c5a269f2074a9425fe)
Runtime: go1.19.11 linux/amd64
Copyright (c) 2015-2023 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
```

add replicate
```
 ./mc alias set minio1 http://192.168.102.92:9000 minioadmin minioadmin
 ./mc alias set minio2 http://192.168.102.95:9000 minioadmin minioadmin
./mc admin replicate add minio1 minio2
```
after error
```
# ERROR 192.168.102.92
minio-minio1-1  | API: SYSTEM()
minio-minio1-1  | Time: 14:48:44 UTC 08/02/2023
minio-minio1-1  | DeploymentID: 606d5e80-7ff7-414b-bcd4-6759a9908ab4
minio-minio1-1  | Error: minio1: ConfigureReplication: Site replication error(s):
minio-minio1-1  | 'ConfigureReplication' on site minio2 (bf0a61e1-b786-4ef8-a18d-33287a5bf3d9): failed(bucket replication config validation error: cmd.APIError{Code:"XMinioAdminRemoteIdenticalToSource", Description:"The remote target cannot be identical to source (remote target endpoint http://192.168.102.95:9000 is self referential)", HTTPStatusCode:400}) (*fmt.wrapError)
minio-minio1-1  |        4: internal/logger/logger.go:258:logger.LogIf()
minio-minio1-1  |        3: cmd/site-replication.go:4451:cmd.(*SiteReplicationSys).healBucketReplicationConfig()
minio-minio1-1  |        2: cmd/site-replication.go:3774:cmd.(*SiteReplicationSys).healBuckets()
minio-minio1-1  |        1: cmd/site-replication.go:3661:cmd.(*SiteReplicationSys).startHealRoutine()
# ERROR 192.168.102.95
minio-minio1-1  | API: SYSTEM()
minio-minio1-1  | Time: 14:51:10 UTC 08/02/2023
minio-minio1-1  | DeploymentID: bf0a61e1-b786-4ef8-a18d-33287a5bf3d9
minio-minio1-1  | Error: minio2: ConfigureReplication: Site replication error(s):
minio-minio1-1  | 'ConfigureReplication' on site minio1 (606d5e80-7ff7-414b-bcd4-6759a9908ab4): failed(bucket replication config validation error: cmd.APIError{Code:"XMinioAdminRemoteIdenticalToSource", Description:"The remote target cannot be identical to source (remote target endpoint http://192.168.102.92:9000 is self referential)", HTTPStatusCode:400}) (*fmt.wrapError)
minio-minio1-1  |        4: internal/logger/logger.go:258:logger.LogIf()
minio-minio1-1  |        3: cmd/site-replication.go:4451:cmd.(*SiteReplicationSys).healBucketReplicationConfig()
minio-minio1-1  |        2: cmd/site-replication.go:3774:cmd.(*SiteReplicationSys).healBuckets()
minio-minio1-1  |        1: cmd/site-replication.go:3661:cmd.(*SiteReplicationSys).startHealRoutine()
```

**Comment by harshavardhana** [comment]
Let's discuss this here this is a configuration issue.

**Reply by sunsjgit** [reply]
192.168.102.95 / 192.168.102.92 

The layout is the same.

```
x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2023-06-23T20-26-00Z
  command: server --console-address ":9001" http://minio1/data{1...4}
  expose:
    - "9000"
    - "9001"
  environment:
    MINIO_ROOT_USER: minioadmin
    MINIO_ROOT_PASSWORD: minioadmin
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3

services:
  minio1:
    <<: *minio-common
    hostname: minio1
    restart: always
    volumes:
      - $PWD/minio/data1:/data1
      - $PWD/minio/data2:/data2
      - $PWD/minio/data3:/data3
      - $PWD/minio/data4:/data4
      - $PWD/minio/log1:/log
      - /etc/localtime:/etc/localtime
  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    restart: always
    volumes:
      - $PWD/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio1
```
nginx
```
user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections  4096;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;
    sendfile        on;
    keepalive_timeout  65;

    # include /etc/nginx/conf.d/*.conf;

    upstream minio {
        server minio1:9000;
    }

    upstream console {
        ip_hash;
        server minio1:9001;
    }

    server {

                # endpoint
        listen       9000;
        listen  [::]:9000;
        server_name  localhost;

        # To allow special characters in headers
        ignore_invalid_headers off;
        # Allow any size file to be uploaded.
        # Set to a value such as 1000m; to restrict file size to a specific value
        client_max_body_size 30M;
        # To disable buffering
        proxy_buffering off;
        proxy_request_buffering off;

        location / {
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_connect_timeout 300;
            # Default is HTTP/1, keepalive is only enabled in HTTP/1.1
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            chunked_transfer_encoding off;

            proxy_pass http://minio;
        }
    }

    server {
                # console address 控制台
        listen       9001;
        listen  [::]:9001;
        server_name  localhost;

        # To allow special characters in headers
        ignore_invalid_headers off;
        # Allow any size file to be uploaded.
        # Set to a value such as 1000m; to restrict file size to a specific value
        client_max_body_size 30M;
        # To disable buffering
        proxy_buffering off;
        proxy_request_buffering off;

        location / {
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-NginX-Proxy true;

            # This is necessary to pass the correct IP to be hashed
            real_ip_header X-Real-IP;

            proxy_connect_timeout 300;

            # To support websocket
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";

            chunked_transfer_encoding off;

            proxy_pass http://console;
        }
    }
}
```
