### DISCUSSION TITLE
MinIO Distributed Mode silently fails to pickup additional nodes

### DISCUSSION THREAD

**Discussion by prologic** [minio/minio#17969] [Q&A]
Hi Team,

As the title suggests, I'm trying to create a 3 node MinIO distributed cluster, and I've followed every piece of documentation I can find. There are no errors on startup, everything looks great 👌

But the Health page and startup logs indicate only a single node is online.

The following is my setup (using Docker):

```yaml
---

version: "3.9"

x-default: &service
  image: minio/minio
  command: server http://minio{1...3}/export
  environment:
    - MINIO_ROOT_USER=minio
    - MINIO_ROOT_PASSWORD=xxx
    - MINIO_ADDRESS=:9000
    - MINIO_CONSOLE_ADDRESS=:9090
    - MINIO_VOLUMES=/export
    - MINIO_DOMAIN=minio.mydomain.tld
    - MINIO_SERVER_URL=https://minio.mydomain.tld
    - MINIO_BROWSER_REDIRECT_URL=https://minio.mydomain.tld/ui/
    - MINIO_DISTRIBUTED_MODE_ENABLED=yes
    - MINIO_DISTRIBUTED_NODES=minio{1...3}
    - MINIO_SKIP_CLIENT=yes
  networks:
    - minio
    - traefik
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3

x-default: &deploy
  replicas: 1
  restart_policy:
    condition: any

services:
  minio1:
    <<: *service
    volumes:
      - minio1:/export
    deploy:
      <<: *deploy
      placement:
        constraints:
          - "node.hostname == node1.mydomain.tld
      labels:
        - "xyz.megpoid.swarm-updater.enable=true"
        - "traefik.enable=true"
        - "traefik.docker.network=traefik"
        - "traefik.http.services.minio_api.loadbalancer.server.port=9000"
        # use regex matching to route primary and subdomains here
        - "traefik.http.routers.minio_api.rule=HostRegexp(`minio.mydomain.tld`, `{bucket:.+}.minio.mydomain.tld`)"
        - "traefik.http.routers.minio_api.service=minio_api"
        - "traefik.http.routers.minio_api.priority=2"
        # tell Traefik to generate a wildcard certificate for this domain
        - "traefik.http.routers.minio_api.tls.certresolver=acme"
        - "traefik.http.routers.minio_api.tls.domains[0].main=minio.mydomain.tld
        - "traefik.http.routers.minio_api.tls.domains[0].sans=*.minio.mydomain.tld"
        - "traefik.http.services.minio_ui.loadbalancer.server.port=9090"
        - "traefik.http.routers.minio_ui.rule=Host(`minio.mydomain.tld`) && PathPrefix(`/ui`)"
        - "traefik.http.routers.minio_ui.middlewares=minio_ui_stripprefix"
        - "traefik.http.routers.minio_ui.service=minio_ui"
        - "traefik.http.routers.minio_ui.priority=3"
        - "traefik.http.middlewares.minio_ui_stripprefix.stripprefix.prefixes=/ui"

  minio2:
    <<: *service
    volumes:
      - minio2:/export
    deploy:
      <<: *deploy
      placement:
        constraints:
          - "node.hostname == node2.mydomain.tld"

  minio3:
    <<: *service
    volumes:
      - minio3:/export
    deploy:
      <<: *deploy
      placement:
        constraints:
          - "node.hostname == node3.mydomain.tld"

volumes:
  minio1:
    driver: local
  minio2:
    driver: local
  minio3:
    driver: local

networks:
  minio:
    driver: overlay
  traefik:
    external: true

```

And the startup logs of one of the nodes (_the other two are basically identical_)

```
| Formatting 1st pool, 1 set(s), 1 drives per set.
| WARNING: Host local has more than 0 drives of set. A host failure will result in data becoming unavailable.
| MinIO Object Storage Server
| Copyright: 2015-2023 MinIO, Inc.
 | License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
| Version: RELEASE.2023-08-31T15-31-16Z (go1.19.12 linux/amd64)
 |
| Status:         1 Online, 0 Offline.
| S3-API: https://minio.mydomain.tld
| Console: https://minio.mydomain.tld/ui/
|
| Documentation: https://min.io/docs/minio/linux/index.html
 Warning: The standard parity is set to 0. This can lead to data loss.
```

What am I missing here? I understand that:

- MinIO has no debug logging and only logs when things fail or are critical
- MinIO clusters can be expanded once created (_so I've been deleting the cluster, volumes each debug attempt_)

I've also confirmed:

- All nodes are reachable
- Every node can reach very other node
- Hostname resolution `minio1`, etc work.

What am I missing?! 😱

<img width="1392" alt="Screenshot 2023-09-03 at 13 36 22" src="https://github.com/minio/minio/assets/1290234/1a91bf51-14ac-4b95-82d4-f1b186e1cb33">

**Comment by prologic** [comment]
**Update:** I've tried to build a local cluster on my Desktop (using Docker for Mac) with a single-node Cluster just to be sure of the config. I used both `docker-compose` and `docker stack deploy` variants (_basically the same config_):

`minio.yml` or `docker-compose.ym`:

```yaml
version: '3.7'

# configuration source https://github.com/minio/minio/blob/master/docs/orchestration/docker-compose/docker-compose.yaml

# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: minio/minio
  command: server --console-address ":9001" http://minio{1...4}/data{1...2}
  networks:
    - minio
  environment:
    MINIO_ROOT_USER: 'minio'
    MINIO_ROOT_PASSWORD: 'xxx'
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3

# starts 4 docker containers running minio server instances.
# using nginx reverse proxy, load balancing, you can access
# it through port 9000.
services:
  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - data1-1:/data1
      - data1-2:/data2

  minio2:
    <<: *minio-common
    hostname: minio2
    volumes:
      - data2-1:/data1
      - data2-2:/data2

  minio3:
    <<: *minio-common
    hostname: minio3
    volumes:
      - data3-1:/data1
      - data3-2:/data2

  minio4:
    <<: *minio-common
    hostname: minio4
    volumes:
      - data4-1:/data1
      - data4-2:/data2

  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    networks:
      - minio
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000/tcp"
      - "9001:9001/tcp"
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4

networks:
  minio:
    driver: overlay

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  data1-1:
  data1-2:
  data2-1:
  data2-2:
  data3-1:
  data3-2:
  data4-1:
  data4-2:
```

Which works. I can see all 4 nodes in the UI by hitting http://localhost:9001/support/diagnostics

I'm really quite perplexed at this point as to what the differences are here? Asie from Nginx vs. Treafik as the ingress load balancer I really can't see why my original setup isn't working? 🤔
