### DISCUSSION TITLE
Using ingress-nginx and rewrite-targets

### DISCUSSION THREAD

**Discussion by markandersontrocme** [minio/minio#18054] [Q&A] [answered]
I would like to serve minio as a subpath in my k8s cluster. When adding a rewrite-target, that adds `/minio` it no longer works:

Working:
```
operator:
  env:
  - name: MINIO_SERVER_URL
    value: http://localhost
  - name: MINIO_BROWSER_REDIRECT_URL
    value: "http://localhost/minio/"
console:
  ingress:
    enabled: {{ .Values.minio.ingress.enable }}
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$1
    ingressClassName: nginx
    path: /minio/(.*)
    host: ""
```

Not Working, but I want this to work...:
```
operator:
  env:
  - name: MINIO_SERVER_URL
    value: http://localhost
  - name: MINIO_BROWSER_REDIRECT_URL
    value: "http://localhost/minio/"
console:
  ingress:
    enabled: {{ .Values.minio.ingress.enable }}
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /minio/$1
    ingressClassName: nginx
    path: /minio/(.*)
    host: ""
```

I would like all of minio stuff to be under `/minio`, any help?

**Comment by vadmeste** [comment, marked as answer]
@markandersontrocme in the S3 specification, you are not allowed to change the resource path in the incoming request; otherwise the request will be considered tampered and it will be rejected. It is not possible to do what you want to do. The only solution is to create a new subdomain for MinIO.

**Comment by MdShimulMahmud** [comment]
@markandersontrocme  @vadmeste 

Here’s a clean and organized configuration to deploy MinIO as a StatefulSet and expose its console under /minio or /minio1 subpaths using Nginx Ingress:

**1. MinIO StatefulSet Configuration**

Configure MinIO to recognize it’s being served under a subpath using environment variables:

path := "http://minio-svc.testing.svc.cluster.local/minio/" and "http://minio1-svc.testing.svc.cluster.local/minio1/"

```yaml
# minio-statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: testing
spec:
  serviceName: minio-svc  # Matches the Service name
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: quay.io/minio/minio:latest
        args:
        - server
        - /data
        - --console-address ":9090"
        env:
        - name: MINIO_BROWSER_REDIRECT_URL  # Critical for subpath support
          value: path
        ports:
        - containerPort: 9000  # S3 API Port
        - containerPort: 9090  # Console Port
        readinessProbe:
          httpGet:
            path: /minio/health/ready  # Subpath-aware health check
            port: 9090
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: 9090
```

**2. Service Configuration**

Expose both the S3 API (9000) and Console (9090):
```yaml
# minio-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: minio-svc
  namespace: testing
spec:
  selector:
    app: minio
  ports:
  - name: s3
    port: 9000
    targetPort: 9000
  - name: console
    port: 9090
    targetPort: 9090
```

**3. Ingress Configuration**

Route traffic to the /minio subpath and rewrite URLs correctly:

```yaml
# minio-ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: testing-ns-ingress-service
  namespace: testing-ns
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 8m
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx-testing-ns
  rules:
    - http:
        paths:
          - path: /minio1/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: minio1-svc
                port:
                  number: 9090
          - path: /minio/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: minio-svc
                port:
                  number: 9090

```

1. ```MINIO_BROWSER_REDIRECT_URL```

    Purpose: Tells MinIO to generate URLs with the ```/minio``` subpath (e.g., ```/minio/login ``` instead of ```/login```).

    Format: ```http://<service-name>.<namespace>.svc.cluster.local/<subpath>/```

    Example:
```yaml
value: "http://minio-svc.testing.svc.cluster.local/minio/"
```

2. ```Ingress rewrite-target```

    Behavior: Strips the ```/minio/``` prefix from requests before forwarding to MinIO.
    Example:
    ```http://<external-ip>/minio/``` → MinIO receives ```/login```.
