### DISCUSSION TITLE
requests_max parameter in case of Minio Operator based deployment

### DISCUSSION THREAD

**Discussion by dharapvj** [minio/minio#18328] [Q&A] [answered]
Hi,

As mentioned in [minio throttling document](https://github.com/minio/minio/blob/master/docs/throttle/README.md#configuring-connection-limit) I have tried to set the environment variable at tenant level in kubernetes operator scenario..

```yaml
minio-tenant:
  tenant:
    name: minio-sinapse
    pools:
      - name: ss-0
    env:
    - name: MINIO_API_REQUESTS_MAX
      value: "2000"
```

Once I set this.. the default log message that was appearing in each pod of the tenant has stopped appearing. So I take it as signal that my setting has worked.

But, the minio console for the tenant still does not show this value. 
![image](https://github.com/minio/minio/assets/1920926/58cbb319-d833-40b6-8f87-a19960356172)

mc output also shows something weird.. It shows `requests_max` as `0` but it also outputs may exported enviroment variable.

```
bash-4.4# mc admin config get minio api
# MINIO_API_REQUESTS_MAX=2000
api requests_max=0 requests_deadline=10s cluster_deadline=10s cors_allow_origin=* remote_transport_deadline=2h list_quorum=strict replication_priority=auto transition_workers=100 stale_uploads_cleanup_interval=6h stale_uploads_expiry=24h delete_cleanup_interval=5m disable_odirect=off gzip_objects=off root_access=on
```

So I am not sure if the setting is working fine or not. Is the console still showing `0` a bug in console?
