### DISCUSSION TITLE
How to use SSE-KMS based Hashicorp KeyVault on helm installation?

### DISCUSSION THREAD

**Discussion by david-nano** [minio/minio#18351] [Q&A]
My Minio instance runs on a K8s cluster using `helm`.
What will be the best practice to use server-side-encryption to my buckets, and keep the keys in my Hashicorp Vault (which also installed on the same cluster)?

In the [guide](https://min.io/docs/minio/linux/operations/server-side-encryption/configure-minio-kes-hashicorp.html#minio-sse-vault) I've found - the KES is installed via Binary file, which is not the right solution in my case.
So what do I miss? What needed to provide KES and add this integration so I can encrypt buckets?

My current `values.yaml`

```yaml
minio:
  image:
    repository: minio/minio
  mcImage:
    repository: minio/mc
  replicas: 2
  existingSecret: "minio-login"
  persistence:
    existingClaim: "minio-static-pvc"
    storageClass: "minio-storage"
    size: 10Ti
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - minio.domain.com
    tls:
  consoleIngress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - minio-console.domain.com
    tls:
```
