### DISCUSSION TITLE
deploying the minio service from docker-compose

### DISCUSSION THREAD

**Discussion by Leonid2377** [minio/minio#18517] [Q&A] [answered]
Hello everyone!
i have a problem with deploying service minio s3 on Ubuntu server 20.04 from docker-compose

when I deploy - I don't see any problems in the console, everything works and the web interface starts, but I can't login to the console

![image](https://github.com/minio/minio/assets/93476930/7a2964b3-cd59-469d-bea9-85dfdd955367)

i have error:
`tls: failed to verify certificate: x509: certificate relies on legacy Common Name field, use SANs instead`

that's my docker-file:

```
version: '3.7'

services:
  minio:
    image: minio/minio
    command: server --address ":9000" --console-address ":9001" /data --certs-dir /certs

    ports:
      - "9000:9000"
#      - "443:443"
      - "9001:9001"
#        - "127.0.0.1:9000:9000"
#        - "127.0.0.1:9001:9001"

    environment:
      CONSOLE_MINIO_SERVER: https://s3-dfa.oe:9001
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      #MINIO_SCHEME: https
      MINIO_SERVER_URL: "https://s3-dfa.oe"
#      MINIO_SERVER_URL="https://s3-dfa.oe:9000" # that's not working
    volumes:
      - ./certs:/certs
      - ./data:/data
```
