### DISCUSSION TITLE
how not to enter the port number in the browser?

### DISCUSSION THREAD

**Discussion by Leonid2377** [minio/minio#18520] [Q&A]
hello, I'm sorry for this question

how do I make it so that when entering into the browser, I do not enter the port?
now I have to enter, https://s3-dfa.oe:9000

```
version: '3.7'

services:
  minio:
    image: minio/minio
    command: server --address ":9000" --console-address ":9001" /data --certs-dir /certs

    ports:
      - "9000:9000"
#      - "443:443"
      - "9001:9001"
#        - "127.0.0.1:9000:9000"
#        - "127.0.0.1:9001:9001"



    environment:
#      CONSOLE_MINIO_SERVER: "https://s3-dfa.oe"
#      MINIO_BROWSER_REDIRECT_URL: "https://s3-dfa.oe"
      MINIO_SERVER_URL: "https://s3-dfa.oe:9000"
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
#      MINIO_SCHEME: https
#      MINIO_SERVER_URL: "https://s3-dfa.oe:9000"
#      MINIO_SERVER_URL="https://s3-dfa.oe:9000" # that's not working
    volumes:
      - ./certs:/certs
      - ./data:/data

```
