### DISCUSSION TITLE
Minio Audit logging with webhook

### DISCUSSION THREAD

**Discussion by vini-intenseye** [minio/minio#18758] [Q&A]
I am trying to install MinIO with the latest helm chart and I am unabel to enable the Audit logging on the tenant that i m creating. 
I have tried using elasticsearch as the webhook server (I was not able to get the CA verified by the tenant) In my past installation the audit logging was enabled with postgres (via the GUI). This option currently do not exist. 
How do i use postgres with the new set up? I have a postgres running on the cluster. I have manually created the audit_log_events table.

My configuration for the audit logging

```
   env:
    - name: MINIO_AUDIT_WEBHOOK_ENABLE_postgres
      value: 'on'
    - name: MINIO_AUDIT_WEBHOOK_ENDPOINT_postgres
      value: http://minio-postgres-postgresql-hl:8080/minio
```

I have tried various combinations and none of them worked.  Using postgres connection string doenst work either. It says the protocol isnt supported. 

What am i missing here?
