### DISCUSSION TITLE
MinIO docker setup

### DISCUSSION THREAD

**Discussion by ghost** [minio/minio#19459] [Q&A]
Hello,

I'm trying to introduce MinIO to our current tech stack.
I have noticed some periodic increases in the file upload duration (the file is pretty small, about 10kb).
We are uploading the file every ~300ms and usually it's pretty fast (about 10 ms) but approximately once per minute it takes more (150+ ms).

The setup I have is 4 nodes (running on 4 different servers) with 2 drives per node, having an HAProxy in front.
Here is the docker-compose config:
```
version: '3.7'

services:
  minio:
      image: {{ nexus_host }}/{{ minio.image }}
      container_name: minio
      hostname: {{ minio.instance_hostname }}
      command: server --console-address ":9001" http://minio{1...4}/data{1...2}
      ports:
        - '9000:9000'
        - '9001:9001'
      environment:
        - MINIO_ROOT_USER={{ minio.root_username }}
        - MINIO_ROOT_PASSWORD={{ minio.root_password }}
        - MINIO_DISTRIBUTED_MODE_ENABLED=yes
        - MINIO_DISTRIBUTED_NODES=minio1,minio2,minio3,minio4
        - MINIO_SKIP_CLIENT=yes
        - MINIO_PROMETHEUS_AUTH_TYPE=public
        - MINIO_PROMETHEUS_JOB_ID=minio-job
#        - MINIO_PROMETHEUS_URL=http://localhost:9090
      extra_hosts:
        - "minio1:{{ minio.host1 }}"  # 1st node
        - "minio2:{{ minio.host2 }}"  # 2nd node
        - "minio3:{{ minio.host3 }}"  # 3rd node
        - "minio4:{{ minio.host4 }}"  # 4th node
      volumes:
        - {{ base_dir }}/minio/data/1:/data1
        - {{ base_dir }}/minio/data/2:/data2
      healthcheck:
        test: ["CMD", "mc", "ready", "local"]
        interval: 5s
        timeout: 5s
        retries: 5
```

From the functional perspective, I didn't notice any issues.
Versions used: RELEASE.2024-02-17T01-15-57Z for image, 8.5.8 for Java SDK.

Since the docker approach is officially recommended only for testing purposes, do you think a setup like this where we have a multi-node env could be used for prod or would it be better to use a Linux native solution?
Also, do you have any idea what could be the cause for the periodic increase in write duration?

Thanks
