### DISCUSSION TITLE
[Multipart upload] Minio multipart upload API did not merge parts in file system when completed with completeMultipartUpload

### DISCUSSION THREAD

**Discussion by quangduytr2403** [minio/minio#19490] [Q&A] [answered]
Hi every one, I start Minio from docker compose
```
version: '3.7'

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - ./test:/data 
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data

```    
And In BE code, I use Minio Java SDK ver 8.0.3 https://mvnrepository.com/artifact/io.minio/minio/8.0.3
I implement APIs for multipart upload and try to upload a mp4 file. Now, after call completeMultipartUpload I receive status 200, I can see that file on Minio dashboard, download and watch it successfully. But in file system, I see this file in save as part like this.
![image](https://github.com/minio/minio/assets/89594236/b0330c36-a748-42a7-afee-4b8bf489bf02)

I need to automatically concatenate all part into mp4 file, so I can use it for future purpose, like transcode... But currently I can see any way to do this, does Minio support this feature? Please help me
