### DISCUSSION TITLE
How to automatically create a bucket via docker-compose and make it public?

### DISCUSSION THREAD

**Discussion by ouroboros-official** [minio/minio#20124] [Q&A] [answered]
Hi, how can I automatically create a bucket in minio via docker-compose and make it public? Unfortunately, trying all the solutions I could find on the internet didn't give any results, so I'm asking here.

The current configuration looks like this:

```
minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin
    command: server --console-address :9001 /data
```
