### DISCUSSION TITLE
SignatureDoesNotMatch on basic putObject

### DISCUSSION THREAD

**Discussion by FatalCatharsis** [minio/minio#20273] [Q&A]
I'm attempting to call normal putObject and I receive this error

> ErrorResponse(code = SignatureDoesNotMatch, message = The request signature we calculated does not match the signature you provided.

This is just a basic test using the minio java client and a local bitnami minio instance in docker. 

I setup docker with this compose file:

```
version: "3.7"
services:
  minio:
    image: bitnami/minio:2024.7.31
    environment:
      MINIO_ROOT_USER: admin123
      MINIO_ROOT_PASSWORD : password
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - test_minio:/bitnami/minio/data

volumes:
  test_minio: {}
```

And then I perform the following actions in spring (kotlin)
```
// variables come from spring application config
// url = http://localhost:9000
// accessKey = admin123
// accessSecret = password
val client = MinioClient.builder()
    .endpoint(url)
    .credentials(accessKey, accessSecret)
    .build()

val bucketExistingRequest = BucketExistsArgs.builder()
    .bucket(bucket)
    .build()
if (!client.bucketExists(bucketExistingRequest)) {
    val makeBucketRequest = MakeBucketArgs.builder()
        .bucket(bucket)
        .build()
    client.makeBucket(makeBucketRequest)
}

// I created an object before this called request that has an open input stream to an image and content type is "image/jpeg; UTF-8"
val newId = UUID.randomUUID()
val minioRequest = PutObjectArgs.builder()
    .bucket(bucket)
    .`object`("$newId")
    .stream(request.inputStream,-1, 1485760000)
    .contentType(request.contentType)
    .build()
// error occurs here
client .putObject(minioRequest)
```

The other questions and posts indicate that this should be one of 2 things, either the password is incorrect or there is a proxy config that is stripping host from the header. The password must be correct because it successfully created the bucket. There is no proxy config because this is just on my local machine. Is there something special about it being in a docker container? I've tried reading about presigned URL's, but apparently that's an explicit action, presignedPutObject which I am not calling?

Is there some documentation I've missed?

Note: client is io.minio:minio:8.5.10
