### DISCUSSION TITLE
Error: Invalid endpoint: localhost:9000

### DISCUSSION THREAD

**Discussion by Alwoch** [minio/minio#20288] [Q&A] [answered]
Hi there, I'm trying to read a minio object (Excel file) straight into pandas and I keep getting the error `Invalid endpoint: localhost:9000`. Im doing this in python with fast api. 

**references:**
- [Reading and writing remote files into pandas](https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html#reading-writing-remote-files)
- [How to load a file from minio into pandas](https://stackoverflow.com/questions/67093837/how-to-load-file-from-custom-hosted-minio-s3-bucket-into-pandas-using-s3-url-fo)

Here's a snippet of my `fileprocessor.py`code :
```
from fastapi import Depends, UploadFile, APIRouter, HTTPException, BackgroundTasks
from fastapi.responses import JSONResponse

from minioconf import minio_client
import pandas as pd
from dotenv import load_dotenv
import s3fs

from db import get_db

from io import BytesIO
import json
from datetime import datetime
import os

load_dotenv()


MINIO_END_POINT = os.environ.get("MINIO_ENDPOINT")
MINIO_ACCESS_KEY = os.environ.get("MINIO_ACCESS_KEY")
MINIO_SECRET_KEY = os.environ.get("MINIO_SECRET_KEY")


async def process_file(saved_object):
    #s3 path
    s3_path = f"s3://excels/{saved_object}"

    try:
        df = pd.read_excel(
            s3_path,
            storage_options={
                "key": MINIO_ACCESS_KEY,
                "secret": MINIO_SECRET_KEY,
                "client_kwargs": {"endpoint_url":MINIO_END_POINT}
            }
        )

        print(df.head())
        

    except Exception as e:
        print(f"Failed to process file: {e}")


@router.post("/uploadfile")
async def upload_file(file: UploadFile, background_tasks: BackgroundTasks):
    # check for valid excel files

    valid_mime_types = [
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "application/vnd.ms-excel"
    ]

    if file.content_type not in valid_mime_types:
        raise HTTPException(
            status_code=415, detail="upload a valid excel file")

    # Read file content
    file_content = await file.read()

    try:
        result = minio_client.put_object(
            "excels",  # bucket name
            file.filename,  # object name
            BytesIO(file_content),  # data to be uploaded
            len(file_content),  # size of the data
            content_type=file.content_type  # content type
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail="failed to upload file")

    file_obj = result.object_name
    print(file_obj)

    # create background tasks to process the file

    background_tasks.add_task(process_file, file_obj)

    return {"message": "file uploaded successfully"}
```
Here's my docker-compose.yml:
```
services:
  minio:
    image: minio/minio:${VERSION}
    container_name: minio
    ports:
      - ${PORT}:9000
      - ${ANOTHER_PORT}:9090
    restart: always
    environment:
      TZ: ${TIMEZONE}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    volumes:
      - ./tmp/data/minio:/data
    command: server /data --console-address ":9090"
    
volumes:
  minio_data:
```
Here's an example of my env file:
```
PORT=9000
ANOTHER_PORT=9090

MINIO_ACCESS_KEY=miniouser
MINIO_SECRET_KEY=miniopassword
MINIO_ENDPOINT=localhost:9000
```
my minioconf.py:
```
from minio import Minio
from dotenv import load_dotenv

import os

# load environment variables
load_dotenv()

END_POINT = os.environ.get("MINIO_ENDPOINT")
ACCESS_KEY = os.environ.get("MINIO_ACCESS_KEY")
SECRET_KEY = os.environ.get("MINIO_SECRET_KEY")

# minio client
minio_client = Minio(
    endpoint=END_POINT,
    access_key=ACCESS_KEY,
    secret_key=SECRET_KEY,
    secure=False
)
```
