### DISCUSSION TITLE
Can't access images from Public bucket directly (Minio in Docker on VPS)

### DISCUSSION THREAD

**Discussion by SkrylnikMikhail** [minio/minio#20360] [Q&A] [answered]
Hello guys, hope you will be able to help me.
I've setup MINIO on VPS using docker compose:

```
version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"   # MinIO API
      - "9001:9001"   # MinIO Console
    volumes:
      - ./minio-data:/mnt/data
      - ./minio-config:/etc/config.env
    restart: always    
    environment:
      MINIO_VOLUMES: "/mnt/data"
      MINIO_OPTS: "--console-address :9001"
    command: server /mnt/data --console-address ":9001"
    networks:
      - shared_network

networks:
  shared_network:
    external: true
```

It runs just fine, i am able to load files from my express server  using put object, i can download and preview files, but for some reason i cannot get file from direct link like: https://minio-server/bucket-name/filename.jpg
I get this icon 
![image](https://github.com/user-attachments/assets/34737654-c830-4d24-9ac0-840103b03129)

My bucket is indeed public:
![image](https://github.com/user-attachments/assets/e13103a1-9c00-41e0-be08-f24d78cd6642)

Anonymous access:
![image](https://github.com/user-attachments/assets/7986622b-2934-4bae-bcd0-debedb3ce9d9)

Cors is *
![image](https://github.com/user-attachments/assets/641a2066-e587-422a-bef4-a72365782509)

Would you be able to help, please?
