### DISCUSSION TITLE
Best way for service discovery and Prometheus metrics endpoints

### DISCUSSION THREAD

**Discussion by schewara** [minio/minio#20562] [Q&A]
With the Metrics being split up into hundreds of sub endpoints, I have not yet found a working solution to scrape all the metrics through through automated service discovery methods.

What I am trying to achieve here is the following

- one or multiple minio container instances are started
- prometheus automatically pics up the container through service discovery
  which in our case [docker_sd](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#docker_sd_config)
- prometheus then automatically scrapes the available metrics by leveraging the relevant config parts through container labels

This usually works splendid with any other service as they have a single scrape endpoint where all metrics are exposed.

Any service discovery mechanism usually only pics up a single scrape target and as a scrape job only allows a single metrics_path I was wondering how I could actually make this work without having to hack together lot's of workarounds

For me it would make much more sense to have a single metrics endpoint and maybe some config parameters which allow you to enable or disable certain metrics based on the individual needs (like [cadvisor](https://github.com/google/cadvisor/blob/master/docs/runtime_options.md)), or alternatively switch to OpenTelemetry for the Metrics, Logs and Traces and eliminate the whole scrape endpoint mess.

**Comment by marktheunissen** [comment]
Hi @schewara what are you talking about when you mention "hundreds of sub endpoints"?

Have you followed the guide here?

https://github.com/minio/minio/blob/master/docs/metrics/prometheus/README.md

**Reply by schewara** [reply]
Hey

I am talking about [Metrics Version 3](https://min.io/docs/minio/linux/operations/monitoring/metrics-and-alerts.html) which now has **21** endpoints to be scraped if you want to get all the metrics :exploding_head: 

And in reference to the guide, which is not yet updated, I have of course seen, read and tried it out, but because it is a static setup which does not work with service discovery in a dynamic environment I have not followed it.

Maybe here a bit more detail on how the service discovery commonly works.
I am sticking here with the docker_sd example, but it would be more or less the same for the k8s prometheus operator and other service discovery methods.

Here a simple universal scrape config to start with

```yaml
      scrape_configs:
      - docker_sd_configs:
        - filters:
          - name: label
            values:
            - prometheus.scrape=true
          host: unix:///var/run/docker.sock
        job_name: docker-containers
        relabel_configs:
        - action: replace
          source_labels:
          - __meta_docker_container_label_prometheus_path
          target_label: __metrics_path__
        - action: replace
          regex: /(.*)
          source_labels:
          - __meta_docker_container_name
          target_label: container_name
        - action: replace
          separator: ':'
          source_labels:
          - container_name
          - __meta_docker_container_label_prometheus_port
          target_label: __address__
```

What's happening in the background is

1. Prometheus calls the Docker to get a list of al containers which have the label `prometheus.scrape` set to true
2. In a second step Prometheus checks for additional labels, `prometheus.port` and `prometheus.path` and starts an internal relabeling process to construct the scrape target.
   As there can be only a single path, this method is unfortunately not working for MinIO.

When I now have to scale out some services from runnning more then one container, this gets automatically picked up without having to adjust anything, as the Docker API now returns more then just one running container.

Coming back to MinIO, in it's current state, I now would have the following options to get all metrics.

1. manually and statically configure 21 scrape configs for a single container which adds more then 100 lines of config for each container and does not support scaling or any other dynamic scenario for CI/CD or temp. review environments as everything is hardcoded.

2. run a sidecar container, that plays proxy for all the metrics [Prometheus Agent](https://prometheus.io/docs/prometheus/latest/feature_flags/#prometheus-agent) mode or other ones.

3. deploy a custom [multi-target exporter](https://prometheus.io/docs/guides/multi-target-exporter/) 

4. other hacks, like [file_sd_config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#file_sd_config) or something else in between Prometheus and MinIO, that handles generating new scrape targets and their configuration dynamically outside of the common available methods

None of these solutions are satisfying, as it makes things more complicated, uses up more resources for a service which has Prometheus metrics already out of the box and a SINGLE metrics endpoint (why not provide it as a feature flag?) would solve the whole nightmare.

Personally I would really love to get a better and deeper understanding of the individual decisions which resulted in the current state of the metrics endpoint.

How do the MinIO Developers monitor and test their instances to make sure all the metrics are there correct and working as they should?
