### DISCUSSION TITLE
Seed minio container with initial data

### DISCUSSION THREAD

**Discussion by kd-labs** [minio/minio#20583] [Q&A] [answered]
Hello 

**Context**: I am using minio as S3 alternative in my local as a docker container. I have a golang service which uses minio to get objects.

**Problem Statement** - I want to add an initial seed data by mounting the path to seed data in my local filesystem to a path in container and running `mc cp` from inside the container so that seed data can be uploaded to the bucket.

**System** - mac silicon

The below is the minio configuration in docker compose file
```
  minio:
    image: "minio/minio:latest"
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: "root"
      MINIO_ROOT_PASSWORD: "root"
    volumes:
      - "minio:/data/minio"
      - ./seed_data/minio:/tmp
    command: minio server /data/minio  --console-address ":9090" --address "0.0.0.0:9000"
    networks:
      - infrastructure
```
1. I was successfully able to create a bucket using `mc mb /data/minio/test-bucket` and was showing up in UI.
<img width="1469" alt="image" src="https://github.com/user-attachments/assets/2bd00d1d-2881-4cdc-b6ca-bb7ea5e1aa9d">

2. But when I'm trying to run `mc cp --recursive /tmp/ /data/minio/test-bucket`, it's not working.
![image](https://github.com/user-attachments/assets/3460a9c8-4711-4ceb-8593-2ac610fb6a1d)

As you can see I have some files inside the folders as well which are not getting added to the bucket.
![image](https://github.com/user-attachments/assets/6a456bab-0c76-4a28-aaca-308526ab1437)

I'm have tried the same with `mc put` as well but to no avail.
Could you please guide me on how to go about it.
