### DISCUSSION TITLE
Can not upload a file > 600mb with k3s and traefik

### DISCUSSION THREAD

**Discussion by peterparker2005** [minio/minio#20747] [Q&A] [answered]
### **Problem Description**

When I attempt to upload a 600 MB file through the MinIO console, the upload consistently fails at 13% with the error message: `something went wrong`.

### **Cluster Configuration**

```sh
root@abstracted-story:~# kubectl get nodes
NAME                            STATUS   ROLES                  AGE   VERSION
abstracted-story.aeza.network   Ready    control-plane,master   42m   v1.30.6+k3s1
daffy-nation.aeza.network       Ready    worker                 40m   v1.30.6+k3s1
```

- **MinIO Deployment:** MinIO is hosted on the **worker node** (`daffy-nation.aeza.network`).
- **Ingress Controller:** I'm using the built-in Traefik that comes with k3s.
- **TLS:** Configured via Traefik and Cert-Manager to serve HTTPS for the console and CDN endpoints.
- **Ingress Traffic Flow:** Requests are being routed through the **master node** (`abstracted-story.aeza.network`) to the worker node where MinIO is running.

### **Observations**

1. **With ClusterIP + Traefik:**  
   - Uploading the 600 MB file fails consistently at 13% with the error `something went wrong`.
   - This occurs when accessing MinIO via the Ingress endpoint with HTTPS.

2. **With NodePort:**  
   - When exposing MinIO directly via NodePort (bypassing Traefik), the upload works perfectly and completes quickly.

#### **Ingress Configuration**

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-ingress
  namespace: minio
  annotations:
    traefik.ingress.kubernetes.io/buffering: |
      maxRequestBodyBytes: 0
      memRequestBodyBytes: 0
      maxResponseBodyBytes: 0
      memResponseBodyBytes: 0
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/clientTimeout: "3600"
    traefik.ingress.kubernetes.io/readTimeout: "3600"
    traefik.ingress.kubernetes.io/writeTimeout: "3600"
spec:
  rules:
    - host: cdn.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio
                port:
                  number: 9000
    - host: console.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio
                port:
                  number: 9001
  tls:
    - hosts:
        - cdn.example.com
        - console.example.com
      secretName: minio-tls
```

#### **Service Configuration**

```yaml
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: minio
spec:
  selector:
    app: minio
  ports:
    - name: http
      port: 9000
      targetPort: 9000
    - name: console
      port: 9001
      targetPort: 9001
  type: ClusterIP
```

### **Deployment configuration**

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: {{ .Values.minio.namespace }}
  labels:
    app: minio
spec:
  replicas: {{ .Values.minio.replicas }}
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      nodeSelector: {{ .Values.minio.nodeSelector | toJson }}
      tolerations: {{ .Values.minio.tolerations | toJson }}
      containers:
        - name: minio
          image: minio/minio:latest
          args:
            - server
            - --address=:9000
            - --console-address=:9001
            - /data
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: MINIO_ROOT_USER
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: MINIO_ROOT_PASSWORD
            - name: MINIO_BUCKETS
              value: {{ .Values.minio.bucket }}
          ports:
            - name: api
              containerPort: 9000
            - name: console
              containerPort: 9001
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          hostPath:
              path: /mnt/data/minio
              type: DirectoryOrCreate
```
