### DISCUSSION TITLE
How do I make a webhook(fastapi) with mc events to notify of creation of new buckets?

### DISCUSSION THREAD

**Discussion by automataIA** [minio/minio#20890] [Q&A] [answered]
How can I develop a webhook using FastAPI and integrate it with MC events to receive notifications when a new bucket is created?
how to write bash script, docker compose, script py.
I've tried writing every way I can, but it either doesn't work or doesn't send notifications.

now i was trying a docker minio-init that starts a bash script that runs mc events commands.

**Comment by marktheunissen** [comment]
Hi @automataIA, consult the documentation on this topic: https://min.io/docs/minio/linux/administration/monitoring/bucket-notifications.html

If you cannot get it to work by following those docs, copy-paste all your work into this discussion showing the outputs and errors. Don't just say "it doesn't work" because we cannot help without information.

**Reply by automataIA** [reply]
Then I will write everything in full. 
## Objectives
- receive webhook notifications from mc events for:
	- creation and removal buckets(so you don't know the name in advance)
	- creation and removal of files from buckets
- in any case must be able to talk to fastapi
## Remarks
- is it possible to use a dockerfile with minio base image to which I apply mc commands instead of minio-init? how?
- Are there easier ways than what I did?
- is it possible to enable mc events via minio python sdk?

## Problem
in this case I am not getting notifications of the events written above.


## Files used

**`configure-minio.sh`**

```YAML
version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_NOTIFY_WEBHOOK_ENABLE: "on"
      MINIO_NOTIFY_WEBHOOK_ENDPOINT: "http://webhook:8000/minio-events"
      MINIO_NOTIFY_WEBHOOK_AUTH_TOKEN: ""
      MINIO_NOTIFY_WEBHOOK_COMMENT: "webhook notification setup"
      MINIO_NOTIFY_WEBHOOK_ENABLE_PRIMARY: "on"
      MINIO_NOTIFY_WEBHOOK_ENDPOINT_PRIMARY: "http://webhook:8000/minio-events"
      MINIO_NOTIFY_WEBHOOK_QUEUE_DIR_PRIMARY: "/data/.notify-events"
      MINIO_NOTIFY_WEBHOOK_QUEUE_LIMIT_PRIMARY: "10000"
      MINIO_API_SELECT_ALL: "on"
      MINIO_BROWSER: "on"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - minio-net

  webhook:
    build: .
    container_name: webhook
    ports:
      - "8000:8000"
    environment:
      - LOGURU_LEVEL=DEBUG
      - PYTHONUNBUFFERED=1
    depends_on:
      - minio
    networks:
      - minio-net

  minio-init:
    image: minio/mc
    container_name: minio-init
    tty: true
    depends_on:
      minio:
        condition: service_healthy
      webhook:
        condition: service_started
    volumes:
      - ./init-scripts:/init-scripts
    entrypoint: ["/init-scripts/configure-minio.sh"]
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    networks:
      - minio-net

networks:
  minio-net:
    driver: bridge

volumes:
  minio_data:
```

**`configure-minio.sh`**

```bash
#!/bin/sh
set -e

echo "Configurazione MinIO in corso..."

# Configura l'alias per MinIO
mc alias set myminio http://minio:9000 "${MINIO_ROOT_USER}" "${MINIO_ROOT_PASSWORD}" --api S3v4

# Configura il webhook per tutti i bucket
mc admin config set myminio notify_webhook enable=on endpoint=http://webhook:8000/minio-events queue_dir=/data/.notify-events queue_limit=10000

# Riavvia MinIO per applicare le modifiche
mc admin service restart myminio || true

# Attendi che il server si riavvii
sleep 2

# Crea un bucket di test
mc mb myminio/test --ignore-existing || true

# Configura gli eventi per tutti i bucket
mc admin config set myminio notify_webhook queue_limit=100000
mc admin config set myminio notify_webhook queue_dir="/data/events"
mc admin config set myminio notify_webhook enable="on"

# Riavvia di nuovo per applicare tutte le modifiche
mc admin service restart myminio || true

# Attendi che il server si riavvii
sleep 2

# Test: crea un file di prova
echo "test" > /tmp/test.txt
mc cp /tmp/test.txt myminio/test/

# Test: rimuovi il file di prova
mc rm myminio/test/test.txt

echo "Configurazione MinIO completata!"


```

**`configure-minio.sh`**
```python
import os
from typing import Dict, Any

from fastapi import FastAPI
from fastapi.responses import ORJSONResponse
from loguru import logger
from pydantic import BaseModel

app = FastAPI(default_response_class=ORJSONResponse)


class S3EventRecord(BaseModel):
    eventVersion: str
    eventSource: str
    awsRegion: str
    eventTime: str
    eventName: str
    userIdentity: Dict[str, Any]
    requestParameters: Dict[str, Any]
    responseElements: Dict[str, Any]
    s3: Dict[str, Any]

    class Config:
        extra = "allow"

class MinioEvent(BaseModel):
    EventName: str | None = None
    Key: str | None = None
    Records: list[S3EventRecord] | None = None

    class Config:
        extra = "allow"


from fastapi import Request

@app.post("/minio-events")
async def minio_webhook(request: Request):
    # Log dei dati raw
    body = await request.body()
    logger.info(f"RAW REQUEST BODY: {body.decode()}")
    
    # Log degli headers
    logger.info(f"REQUEST HEADERS: {request.headers}")
    
    # Converti il body in JSON
    try:
        data = await request.json()
        logger.info(f"PARSED JSON: {data}")
        event = MinioEvent(**data)
    except Exception as e:
        logger.error(f"Errore nel parsing della richiesta: {e}")
        return {"status": "error", "message": f"Errore nel parsing: {str(e)}"}
    logger.debug("Headers della richiesta ricevuta")
    logger.info("Ricevuto evento MinIO")
    logger.info(f"Evento completo: {event.dict()}")

    if not event.Records:
        logger.warning("Nessun record nell'evento")
        return {"status": "success", "message": "Nessun record da processare"}

    for record in event.Records:
        logger.info(f"Processando record: {record.eventName}")
        
        # Estrai informazioni dal record S3
        bucket_name = record.s3.get('bucket', {}).get('name', '')
        object_key = record.s3.get('object', {}).get('key', '')
        
        # Gestione eventi bucket
        if "s3:BucketCreated" in record.eventName:
            logger.info(f"Nuovo bucket creato: {bucket_name}")
            return {"status": "success", "message": f"Bucket {bucket_name} creato e configurato"}

        # Gestione eventi file
        elif "s3:ObjectCreated" in record.eventName:
            logger.info(f"Nuovo file creato: {object_key} nel bucket {bucket_name}")
            return {"status": "success", "message": f"File {object_key} caricato nel bucket {bucket_name}"}

        logger.info(f"Evento {record.eventName} processato per bucket: {bucket_name}, oggetto: {object_key}")

    return {"status": "success", "message": "Eventi processati"}


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(
        "main:app",
        host="0.0.0.0",
        port=8000,
        reload=True,
        loop="uvloop",
        http="httptools",
    )
```
