### DISCUSSION TITLE
CPU spike occurs when uploading data via SFTP or Web UI (upload local file or through camera)

### DISCUSSION THREAD

**Discussion by bolero2** [minio/minio#20920] [Q&A]
## Expected Behavior
1. I expect very low CPU usage when uploading data via SFTP or Web UI.

## Current Behavior
1. CPU spike occurs when uploading data via SFTP or Web UI.

## Steps to Reproduce (for bugs)

1. I am uploading multiple image data over SFTP/Web using python asyncssh package. (Data Lake)
    - ref 1: https://min.io/docs/minio/linux/developers/file-transfer-protocol.html (minio ftp)
    - ref 2: https://asyncssh.readthedocs.io/en/latest/api.html#asyncssh.SFTPClient (asyncssh) 
3. Both sftp.mput and sftp.put functions in the asyncssh package cause CPU spikes.
4. Even if an upload delay is given, a CPU spike occurs at the moment of upload.

5. code sample:
```python
async def upload_from_local(self):
    is_file = True
    if not self.conn:
        self.conn = await self._create_client()

        if not self.conn:
            logging.error("Failed to create SSH connection. Aborting upload.")
            return

    try:
        async with self.conn.start_sftp_client() as sftp:
            logging.info(f"SFTP session opened: {sftp} .")

            if not os.path.isfile(self.upload): # is not file
                if os.path.isdir(self.upload):  # is directory
                    object_list = glob(os.path.join(self.upload, f"*"), recursive=True)
                    self.upload = [x for x in object_list if os.path.isfile(x)]
                else:   # is not file and not directory
                    raise NotImplementedError
            else:       # is file
                func = sftp.put

            logging.info(f"Uploading '{self.upload}' to '{self.path}'...")

            if isinstance(self.upload, list):
                for targetf in self.upload:
                    if targetf is None:
                        continue
                    else:
                        await sftp.put(targetf, self.path)
                        # await asyncio.sleep(self.interval)
            elif os.path.isfile(self.upload):
                await sftp.put(self.upload, self.path)

            # await func(self.upload, self.path, block_size=4096)
            result = {"code": 200, "message": "success", "data": {"src": self.upload, "dst": self.path}}
            logging.info(json.dumps(result))

    except (OSError, asyncssh.Error, AttributeError) as failed_exc:
        logging.error(f"SSH/SFTP connection failed: {failed_exc}")
        traceback.print_exc()
    except asyncssh.sftp.SFTPNoSuchFile as notarget_exc:
        logging.error(f"SSH/SFTP cannot found file/path to upload: {notarget_exc}")
        traceback.print_exc()
    except asyncio.CancelledError as cancelled_exc:
        logging.error(f"Upload task cancelled: {cancelled_exc}")
        traceback.print_exc()
    except TimeoutError as timeout_exc:
        logging.error(f"Timeout: {timeout_exc}")
        traceback.print_exc()
    except Exception as e:
        logging.error(f"An unexpected error occurred: {e}")
        traceback.print_exc()

    finally:
        if self.conn:
            self.conn.close()
            await self.conn.wait_closed()
            self.conn = None
```
- `mc admin trace`
<img width="1710" alt="Image" src="https://github.com/user-attachments/assets/1854028a-53ab-469d-bd6a-6224e4766101" />

- `mc admin trace --verbose`
<img width="1708" alt="Image" src="https://github.com/user-attachments/assets/a545fbe0-4bc8-4379-aa81-32e752d4390e" />

## Context

1. When uploading image data from an external device, CPU load occurs.
2. However, I need to connect multiple devices and receive image data from multiple places via SFTP.

## Regression
 

No

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2024-10-13T13-34-11Z (commit-id=d10bb7e1b667c2df72c394ef1fa52ab4a6802d0f)
* Server setup and configuration: 
```yaml
  minio:
    image: minio/minio:latest
    container_name: myminio_dev
    restart: always
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USERNAME}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_PORT: ${MINIO_PORT}
      MINIO_CONSOLE_PORT: ${MINIO_CONSOLE_PORT}
      MINIO_SFTP_PORT: ${MINIO_SFTP_PORT}
    command: server /data --console-address ":${MINIO_CONSOLE_PORT}" --sftp "address=:${MINIO_SFTP_PORT}" --sftp "ssh-private-key=${MINIO_SSH_PRIVATE_KEY}" --sftp "trusted-user-ca-key=${MINIO_TRUSTED_USER_CA_KEY}"
    ports:
      - "${MINIO_PORT}:${MINIO_PORT}"  # S3 API access port
      - "${MINIO_CONSOLE_PORT}:${MINIO_CONSOLE_PORT}"  # MinIO console access port
      - "${MINIO_FTP_PORT}:${MINIO_FTP_PORT}"  # MinIO FTP connection port
      - "${MINIO_FTP_PASV_PORT}:${MINIO_FTP_PASV_PORT}"   # MinIO FTP Data ports
      - "${MINIO_SFTP_PORT}:${MINIO_SFTP_PORT}"  # MinIO SFTP connection port
    volumes:
      - /mnt/minio:/data
      - ${MINIO_CERT_PATH}:${MINIO_CERT_PATH}:ro
```
* Operating System and version (`uname -a`): Linux -aws #23-Ubuntu SMP Mon Dec  9 23:59:34 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux (EC2 `m7i-xlarge`)
* use EC2 EBS storage.
