### DISCUSSION TITLE
No such IDP configuration exists

### DISCUSSION THREAD

**Discussion by ceuser1** [minio/minio#21013] [Q&A] [answered]
I am trying to use OpenID Connect with Keycloak, as described in [Configure MinIO for Authentication using Keycloak](https://min.io/docs/minio/container/operations/external-iam/configure-keycloak-identity-management.html)

OS: Windows 11
Docker Client: 27.3.1
Docker Server: Desktop 4.36.0 (175267)

docker-compose.yml:
```yml
services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    restart: always
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=keycloakadmin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=keycloakadmin123
      - KC_LOG_LEVEL=DEBUG
    ports:
      - 19080:8080
    command: start-dev
    volumes:
      - ./keycloak-data:/opt/keycloak/data

  minio:
    image: minio/minio
    container_name: minio
    restart: always
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - 19008:9000
      - 19009:9001
    command: server /data --console-address ":9001"
    volumes:
      - ./minio-data:/data

volumes:
  minio-data:
  keycloak-data:
```

Docker compose:
```shell
docker compose -f 'docker-compose.yml' up -d --build
```

Two containers are created:
![image](https://github.com/user-attachments/assets/9cb2e2af-9c46-4dd1-88cb-07eb454f0b8f)

MinIO is running on [http://localhost:19009](http://localhost:19009), version RELEASE.2025-02-28T09-55-16Z (go1.23.6 linux/amd64)
Keycloak is running on [http://localhost:19080](http://localhost:19080), version 26.1.3

Now I configure keycloak according to [Configure MinIO for Authentication using Keycloak](https://min.io/docs/minio/container/operations/external-iam/configure-keycloak-identity-management.html) documentation - create new ```minio-realm```, ```minio-client```, set scope, mapper, user, group etc... 
The realm configuration is available at [http://localhost:19080/realms/minio-realm/.well-known/openid-configuration](http://localhost:19080/realms/minio-realm/.well-known/openid-configuration)

Next step is to configure MinIO to use the keycloak OpenID provider, but I just can't figure out why my keycloak IDP isn't found... the error is ```No such IDP configuration exists```. I tried many different options for ```Config URL``` because I'm not an expert with docker networking (localhost:19080, localhost:8080, keycloak:19080, keycloak:8080, host.docker.internal:19080, host.docker.internal:8080, ...) but the error remains.
![image](https://github.com/user-attachments/assets/58b28181-edd7-4842-bd3d-b637d789f089)

Any idea?
