### DISCUSSION TITLE
Restoring Original Files from XL Format After Docker Container Crash

### DISCUSSION THREAD

**Discussion by franzfilip** [minio/minio#21040] [Q&A]
Hello MinIO Team,

I have been running MinIO as an S3 service within a Docker container. Unfortunately, my server crashed, and I managed to secure the mounted storage from the container on my PC. I then attempted to start the MinIO Docker container on my PC using the same mount. However, I noticed that objects originally uploaded as .wav files are not stored as single files. Instead, they appear with a folder structure similar to this:

article.wav/
├── xl.meta
└── 5390a4b2-ddb8-4310-8717-7c85e61d5faa/
    └── part.1

I understand that MinIO uses this internal structure (with the xl.meta file and one or more parts) to store objects in XL mode. My questions are:

Is there an official tool or documented procedure to reconstruct the original file (e.g., the complete .wav file) from this internal structure?
Alternatively, are there recommended steps or scripts to manually merge the parts stored in the XL format back into a single, usable file?
Any guidance or suggestions would be greatly appreciated.

Or spoken in general:
How can i fix the broken state, because some files are getting detected correctly (just a few) and others are not even displayed:
Working:
![image](https://github.com/user-attachments/assets/42210576-24c4-42bd-b21e-b060d97fbf6b)

Not Working:
![image](https://github.com/user-attachments/assets/5f7cfacc-ae08-49e2-a182-0655924299db)
![image](https://github.com/user-attachments/assets/6fa2a8bb-2171-4f17-a581-a41117d7a327)
![image](https://github.com/user-attachments/assets/e910cfa6-0fe7-4dc9-a433-f9a56125e35d)
![image](https://github.com/user-attachments/assets/27a22ca0-734b-4a63-8d73-5e3fc074c061)

Docker Compose
```
  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - preview
```
