### DISCUSSION TITLE
Service account to access bucket

### DISCUSSION THREAD

**Discussion by badsector3** [minio/minio#21207] [Q&A]
Hi Team,

I'm trying to configure MinIO Operator STS to allow a pod using a Service Account (default/example-sa) to access specific buckets (jars, savepoints) on our MinIO Tenant (minio-rke2/minio - name confirmed).

Setup:

    Kubernetes: [v1.31.6+rke2r1]
    MinIO Operator: [6.0.4]
    MinIO Tenant: Healthy, TLS enabled using a custom CA (issued via cert-manager using CA issuer type after issues with selfSigned).
    MinIO Operator Health: Operator pods running, logs show STS API started. Operator is configured via Helm values to trust the custom CA (volumes/volumeMounts added), and Tenant health checks (Get "https://minio-hl.minio-rke2...) are now succeeding in Operator logs (no more TLS errors).

Configuration:

Service Account (default/example-sa):
``` YAML

apiVersion: v1
kind: ServiceAccount
metadata:
  name: example-sa
  namespace: default
```
MinIO Policy (example-minio-policy on Tenant):
```JSON

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "PolicyForexample-minio-policy",
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::jars",
                "arn:aws:s3:::jars/*",
                "arn:aws:s3:::savepoints",
                "arn:aws:s3:::savepoints/*"
            ]
        }
    ]
}
```
(Confirmed policy exists on Tenant using mc admin policy info)

PolicyBinding (minio-rke2/example-minio-access):

```YAML
apiVersion: sts.min.io/v1alpha1
kind: PolicyBinding
metadata:
  name: example-minio-access
  namespace: minio-rke2 # Tenant Namespace
spec:
  application:
    namespace: default    # App Namespace
    serviceaccount: example-sa # App SA
  policies:
    - example-minio-policy # Policy from Step 2
```
(Confirmed exists in Tenant namespace)

CA Trust Secret (default/ca-trust):
```YAML

# Secret containing the public ca.crt for the custom CA used by the Tenant
# Created via: kubectl create secret generic ca-trust --from-file=ca.crt=... -n default
```
(Confirmed exists)

Test Pod (default/minio-test):
```YAML
    apiVersion: v1
    kind: Pod
    metadata:
      name: minio-test
      namespace: default
    spec:
      serviceAccountName: example-sa
      restartPolicy: Never
      containers:
        - name: awscli
          image: amazon/aws-cli:latest # Using latest aws-cli
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Listing contents of s3://jars..."
              # Using correct bucket name from policy & --debug flag
              aws s3 ls s3://jars/ --endpoint-url=https://minio-hl.minio-rke2.svc.cluster.local:9000 --debug
              echo "Test complete."
          env:
            - name: AWS_WEB_IDENTITY_TOKEN_FILE
              value: /var/run/secrets/kubernetes.io/serviceaccount/token
            # Using standard syntactically valid dummy ARN
            - name: AWS_ROLE_ARN
              value: arn:aws:iam::123456789012:role/DummyRoleForMinIOOperatorSTS
            - name: AWS_REGION
              value: us-east-1
            - name: AWS_ENDPOINT_URL
              # Verified this matches the Tenant Service endpoint
              value: https://minio-hl.minio-rke2.svc.cluster.local:9000
            - name: AWS_CA_BUNDLE
              # Path matches volumeMount below
              value: /etc/minio-test-certs/ca.crt
          volumeMounts:
            - name: ca-bundle
              mountPath: /etc/minio-test-certs
              readOnly: true
      volumes:
        - name: ca-bundle
          secret:
            secretName: ca-trust # Secret from Step 4 above
```
Problem:

Despite ensuring the Operator is healthy, CA trust is configured correctly for both the Operator and the test pod, and using the standard recommended dummy AWS_ROLE_ARN format, the minio-test pod still fails immediately with the exact same error as initially encountered.
```
An error occurred (InvalidParameterValue) when calling the AssumeRoleWithWebIdentity operation: Error processing RoleArn parameter: RoleARN parse err: invalid ARN - bad partition field
```
The MinIO Operator logs do not show any log entries related to receiving or processing the AssumeRoleWithWebIdentity request when the test pod runs (no mention of STS, TokenReview, example-sa, etc., only regular Tenant reconciliation logs). The client pod logs (with --debug) show it attempts the call to the correct endpoint but fails with the above parameter error before getting a meaningful response from the server side.

Question:

What else could cause the AWS SDK within the pod to fail parsing the AWS_ROLE_ARN with this specific error (bad partition field), even when a standard dummy value is provided and other components (Operator health, CA trust, PolicyBinding) seem correctly configured? Is there any known issue or other configuration for Operator STS (perhaps related to Calico CNI?) that might interfere with how the SDK parses parameters or how the request is handled/intercepted?

Thanks for any insights!
