### DISCUSSION TITLE
[HELP] MinIO tenant deploy full of errors everywhere

### DISCUSSION THREAD

**Discussion by santurini** [minio/minio#21206] [Q&A]
Hello I deployed MinIO on kubernetes via Helm charts using this values for the tenant:
```
tenant:
  name: minio
  image:
    tag: RELEASE.2025-01-20T14-49-07Z
  configuration:
    name: minio-credentials
  configSecret:
    existingSecret: true
  certificate:
    requestAutoCert: false
  buckets:
    - name: warehouse
      objectLock: false
      region: eu-central-1
```

Everything seems to look perfectly fine at a first glance, but if I check the tenant pods logs everyone gives different errors:
```
INFO: Unable to use the drive http://minio-tenant-pool-3.minio-hl.minio-tenant.svc.cluster.local:9000/export3/data: drive not found, will be retried

...

Error: Unable to initialize backend: Storage resources are insufficient for the read operation .minio.sys/pool.bin, retrying in 4.115915682s (*fmt.wrapError)

       7: internal/logger/logger.go:268:logger.LogIf()

       6: cmd/logging.go:156:cmd.storageLogIf()

       5: cmd/erasure-server-pool.go:214:cmd.newErasureServerPools()

       4: cmd/server-main.go:1174:cmd.newObjectLayer()

       3: cmd/server-main.go:918:cmd.serverMain.func11()

       2: cmd/server-main.go:561:cmd.bootstrapTrace()

       1: cmd/server-main.go:916:cmd.serverMain()

...

Error: Drive: http://minio-tenant-pool-1.minio-hl.minio-tenant.svc.cluster.local:9000/export3/data returned drive not found (*fmt.wrapError)

       endpoint="http://minio-tenant-pool-1.minio-hl.minio-tenant.svc.cluster.local:9000/export3/data"

       4: internal/logger/logger.go:258:logger.LogAlwaysIf()

       3: cmd/logging.go:65:cmd.peersLogAlwaysIf()

       2: cmd/prepare-storage.go:51:cmd.init.func22.1()

       1: cmd/erasure-sets.go:230:cmd.(*erasureSets).connectDisks.func2()

...

Error: http://minio-tenant-pool-1.minio-hl.minio-tenant.svc.cluster.local:9000->http://minio-tenant-pool-0.minio-hl.minio-tenant.svc.cluster.local:9000 has incorrect configuration: Expected MinIO binary checksum: 810080f8c1eaa8975a072663002efbde, seen: 6e8e84ab423ffe7240c88be251c7a19e (*fmt.wrapError)

       4: internal/logger/logonce.go:118:logger.(*logOnceType).logOnceIf()

       3: internal/logger/logonce.go:149:logger.LogOnceIf()

       2: cmd/logging.go:104:cmd.bootLogOnceIf()

       1: cmd/bootstrap-peer-server.go:233:cmd.verifyServerSystemConfig.func1()

INFO: Waiting for quorum READ healthcheck to succeed retrying in 496.552654ms.. possible cause unhealthy sets

...

Error: grid: http://minio-tenant-pool-1.minio-hl.minio-tenant.svc.cluster.local:9000 re-connecting to http://minio-tenant-pool-0.minio-hl.minio-tenant.svc.cluster.local:9000: dial tcp 10.42.0.17:9000: connect: connection refused (*net.OpError) Sleeping 1.83s (3) (*fmt.wrapError)

       6: internal/logger/logonce.go:118:logger.(*logOnceType).logOnceIf()

       5: internal/logger/logonce.go:149:logger.LogOnceIf()

       4: internal/grid/connection.go:59:grid.gridLogOnceIf()

       3: internal/grid/connection.go:672:grid.(*Connection).connect.func1()

       2: internal/grid/connection.go:678:grid.(*Connection).connect()

       1: internal/grid/connection.go:275:grid.newConnection.func3()

...

Error: maximum retry reached to load the data usage cache `golden/.usage-cache.bin` (*errors.errorString)

       5: internal/logger/logonce.go:118:logger.(*logOnceType).logOnceIf()

       4: internal/logger/logonce.go:149:logger.LogOnceIf()

       3: cmd/logging.go:140:cmd.scannerLogOnceIf()

       2: cmd/data-usage-cache.go:941:cmd.(*dataUsageCache).load()

       1: cmd/erasure.go:501:cmd.erasureObjects.nsScanner.func2()

...

Error: failed to fetch last day tier stats: Server not initialized, please try again (*fmt.wrapError)

       6: internal/logger/logonce.go:118:logger.(*logOnceType).logOnceIf()

       5: internal/logger/logonce.go:149:logger.LogOnceIf()

       4: cmd/logging.go:71:cmd.peersLogOnceIf()

       3: cmd/notification.go:1564:cmd.(*NotificationSys).GetLastDayTierStats()

       2: cmd/tier-handlers.go:255:cmd.adminAPIHandlers.TierStatsHandler()

       1: net/http/server.go:2220:http.HandlerFunc.ServeHTTP()

...

Error: Server not initialized, please try again (grid.RemoteErr)

       peerAddress="minio-tenant-pool-0.minio-hl.minio-tenant.svc.cluster.local:9000"

       4: internal/logger/logonce.go:118:logger.(*logOnceType).logOnceIf()

       3: internal/logger/logonce.go:149:logger.LogOnceIf()

       2: cmd/logging.go:71:cmd.peersLogOnceIf()

       1: cmd/notification.go:140:cmd.(*NotificationGroup).Go.func1()

...

Error: remote disconnected (grid.RemoteErr)

       5: internal/logger/logger.go:268:logger.LogIf()

       4: cmd/logging.go:46:cmd.adminLogIf()

       3: cmd/admin-handlers.go:1479:cmd.getAggregatedBackgroundHealState()

       2: cmd/admin-handlers.go:708:cmd.adminAPIHandlers.StorageInfoHandler()

       1: net/http/server.go:2220:http.HandlerFunc.ServeHTTP()
```

I am unable to delete a bucket, both from CLI and console:
```
ubuntu@node1:~$ mc rb --force --dangerous mycloud/warehouse/translated
Removed `mycloud/warehouse/translated` successfully.
ubuntu@node1:~$ mc ls mycloud/warehouse
[2025-04-18 08:57:41 UTC]     0B translated/
ubuntu@node1:~$ mc rm mycloud/warehouse/translated/
Removed `mycloud/warehouse/translated`.
ubuntu@node1:~$ mc ls mycloud/warehouse
[2025-04-18 08:58:14 UTC]     0B translated/
ubuntu@node1:~$ mc rm --recursive --force mycloud/warehouse/translated
ubuntu@node1:~$ mc ls mycloud/warehouse
[2025-04-18 09:03:55 UTC]     0B translated/
```

Last but not least I have kafka connect iceberg connectors writing to MinIO and all failed after a few days with this error:
```
Resource requested is unreadable, please reduce your request rate (Service: S3, Status Code: 503, Request ID: 18372B091B4D8448, Extended Request ID: adeb5426ef3f96a74e55ef62eb0012e5b86d5ce0de74d3bff25dcd1162bd12d7)
```

The same day two files disappeared from a bucket. How do I even start debugging this, I need serious help please

**Comment by harshavardhana** [comment]
> Error: http://minio-tenant-pool-1.minio-hl.minio-tenant.svc.cluster.local:9000->http://minio-tenant-pool-0.minio-hl.minio-tenant.svc.cluster.local:9000 has incorrect configuration: Expected MinIO binary checksum: 810080f8c1eaa8975a072663002efbde, seen: 6e8e84ab423ffe7240c88be251c7a19e (*fmt.wrapError)

You have to different binaries running in the setup.

**Comment by santurini** [comment]
@harshavardhana but i get that error only on a single tenant (a single tenant pod), I should have it on all 4. Would a helm upgrade solve the error or I have to do a fresh install?

**Comment by santurini** [comment]
@harshavardhana I tried upgrading to the latest release but I still have the same error

**Reply by klauspost** [reply]
Then you haven't updated correctly or something isn't right in your setup.

Figure out why it is installing different binaries on different machines.

**Reply by santurini** [reply]
I will try to do a fresh installation as soon as I finish backuping

**Comment by santurini** [comment]
@klauspost Now I have this log on all tenants:
```
INFO: Waiting for the first server to format the drives (elapsed 0s)

INFO: 

 You are running an older version of MinIO released 3 weeks before the latest release 

 Update: Run `mc admin update ALIAS` 

INFO: Waiting for all MinIO sub-systems to be initialize...

INFO: Configured max API requests per node based on available memory: 39661

INFO: All MinIO sub-systems initialized successfully in 14.440856ms

INFO: IAM load(startup) finished. (duration: 1.815539ms)

---------------------------

MinIO Object Storage Server

Copyright: 2015-2025 MinIO, Inc.

License: GNU AGPLv3 - https://www.gnu.org/licenses/agpl-3.0.html

Version: RELEASE.2025-03-12T18-04-18Z (go1.24.1 linux/amd64)

API: http://minio.minio-tenant.svc.cluster.local 

WebUI: http://10.42.0.69:9090 http://127.0.0.1:9090   

Docs: https://docs.min.io

---------------------------
```

Do you suggest to update to the latest version or for production also this one is good?

**Reply by klauspost** [reply]
Logs look fine. For commercial support and guidance reach out on sales@min.io

**Comment by BigBoyForLive** [comment]
I'm actually facing the same issue , i wonder if you found a solution @santurini

**Reply by santurini** [reply]
I can share with you the ansible playbook I used to correctly install it:
```yaml
- name: MinIO Kubernetes Setup
  hosts: all
  gather_facts: false
  vars:
    NAMESPACE: minio-tenant
  vars_files:
    - ../secrets.yaml

  tasks:
    - name: Add MinIO operator repository
      kubernetes.core.helm_repository:
        name: minio-operator
        url: https://operator.min.io

    - name: Install MinIO operator
      kubernetes.core.helm:
        name: minio-operator
        chart_ref: minio-operator/operator
        namespace: minio-operator
        create_namespace: true

    - name: Create Kubernetes secret minio-credentials
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template', '../../../_templates/trino/minio_credentials.yaml') }}"

    - name: Install MinIO tenant
      kubernetes.core.helm:
        name: minio-tenant
        chart_ref: minio-operator/tenant
        namespace: "{{ NAMESPACE }}"
        create_namespace: true
        values: "{{ lookup('template', 'values.yaml') | from_yaml }}"

```

**minio-credentials.yaml**
```yaml
apiVersion: v1
stringData:
  config.env: |-
    export MINIO_ROOT_USER={{ MINIO_USER }}
    export MINIO_ROOT_PASSWORD={{ MINIO_PASSWORD }}
kind: Secret
metadata:
  name: minio-credentials
  namespace: {{ NAMESPACE }}
```

**values.yaml**
```yaml
tenant:
  name: minio
  configSecret:
    name: minio-credentials
    existingSecret: true
  certificate:
    requestAutoCert: false
  buckets:
    - name: warehouse
      objectLock: false
      region: eu-central-1
  pools:
    - servers: 1
      name: tenant-pool
      volumesPerServer: 1
      size: 750Gi # total size will be volumesPerServer x size so be sure you have that space available in the cluster
      storageClassName: longhorn # use default if you do not have longhorn

ingress:
  api:
    enabled: true
    ingressClassName: "contour"
    annotations: 
      projectcontour.io/websocket-routes: "/" # ignore if you do not use contour
      projectcontour.io/response-timeout: "infinity" # ignore if you do not use contour
    tls:
      - hosts:
        - minio.yourdomain.com
        secretName: yourdomain.com
    host: minio.yourdomain.com
    path: /
  console:
    enabled: true
    ingressClassName: "contour" # ignore if you do not use contour
    annotations:
      projectcontour.io/websocket-routes: "/" # ignore if you do not use contour
      projectcontour.io/response-timeout: "infinity" # ignore if you do not use contour
    tls:
      - hosts:
        - minio-console.yourdomain.com
        secretName: yourdomain.com
    host: minio-console.yourdomain.com
    path: /
```

To run the playbook you will need a **secrets.yaml** file with these entries:
```yaml
MINIO_USER: youruser
MINIO_PASSWORD: yourpassword
```

Of course remember to change the paths according to your ansible repo structure and to correctly setup the machines following the MinIO documentation prerequisites.

Hope this helps!
