### DISCUSSION TITLE
minio event notify to kafka  not getting connected

### DISCUSSION THREAD

**Discussion by s009desh** [minio/minio#21204] [Q&A]
We are connecting to Kafka using kcat, and the deployment is set up with the Strimzi operator in Kraft mode. It works fine both internally and externally, and we can list topics using kcat. Kafka is configured without TLS and with SCRAM-SHA-512 authentication. When authentication is enabled, kcat works fine and connects without issues. However, when we try to connect MinIO with authentication enabled, it fails. Below are the Kafka configuration details and the error MinIO encounters when attempting to connect.             

```
 apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 3.9.0
    metadataVersion: 3.9-IV0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        authentication:
          type: scram-sha-512
      - name: sasl 
        port: 9093
        type: loadbalancer 
        tls: false
        authentication:
          type: scram-sha-512
    rack:
      topologyKey: rack
    authorization:
      type: simple
      superUsers:
        - fastpix  
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      log.retention.hours: 96  
    storage:
      type: jbod
      volumes:
        - id: 0
          type: persistent-claim
          size: 100Gi
          deleteClaim: false
          class: openebs-hostpath 
  entityOperator:
    topicOperator: {}
    userOperator: {}
```
command-  

`mc admin config set fastpix notify_kafka:kafka_cluster="topic=fastpix-storage-object-created brokers=<>:9093 sasl_username=minio-new sasl_password=************* sasl=sasl-plaintext sasl_mechanism=SCRAM-SHA-512 tls=off"
`
Error

`  error mc: <ERROR> Unable to set 'notify_kafka:kafka_cluster=topic=fastpix-storage-object-created brokers=<DNS>:9093 sasl_username=minio-new sasl_password=**************** sasl=sasl-plaintext sasl_mechanism=SCRAM-SHA-512 tls=off' to server: error (kafka_cluster=topic=fastpix-storage-object-created:kafka): kafka: client has run out of available brokers to talk to: EOF.`
