### DISCUSSION TITLE
minio admin features gone

### DISCUSSION THREAD

**Discussion by harridu** [minio/minio#21316] [Q&A]
Since the upgrade from 20250422221226.0.0 to 20250524170830.0.0 all the admin features seem to be missing, even though I logged in as minioadmin. I found #21278, but it doesn't really enlighten the situation. Is this a bug or a feature/restriction? The release notes (https://github.com/minio/minio/releases/tag/RELEASE.2025-05-24T17-08-30Z) say its a bug fix release, but is it?

**Comment by MichelVanAutreve** [comment]
I'm having the same issues, I'm really wondering what's going on here.

**Comment by dani** [comment]
Looks like the open source edition won't have any admin option in the console from now on. Only a basic object browser is provided. Everything must be configured through mc. It's weird as there's not a single warning about this in the changelog

**Comment by harridu** [comment]
Such a user-unfriendly move. I've lost faith in this project.

**Comment by julienlau** [comment]
It's not an issue they did it on purpose.
https://github.com/minio/object-browser/pull/3509

They changed the license of the browser and removed all features except basic browsing.

I guess they did to try to kill their open source offerings in order to try to boost the sell of their new non open source S3 "AIstor"

**Comment by danielrosehill** [comment]
WTH!? Assumed this was a bug. That's .... disheartening. Anyone have a good alternative? I store 90% of stuff on public S3s but ... thought it was a nice idea to have my own little endpoint for the odd requirement.

**Reply by foster-hangdaan** [reply]
There is [Garage](https://garagehq.deuxfleurs.fr/) and [OpenMaxIO](https://github.com/OpenMaxIO/openmaxio-object-browser).

**Reply by ilhamsj** [reply]
try this bro 
```yaml
networks:
  seaweedfs-net:
  universe:

services:
  master:
    image: chrislusf/seaweedfs
    container_name: seaweedfs-master
    command: "master -ip=master"
    ports:
      - 9333:9333
    networks:
      - seaweedfs-net
      - universe

  volume:
    image: chrislusf/seaweedfs
    container_name: seaweedfs-volume
    command: "volume -mserver=master:9333 -port=8080"
    ports:
      - 8080:8080
    depends_on:
      - master
    networks:
      - seaweedfs-net
      - universe
    volumes:
      - ./data/seaweedfs-data:/data

  filer:
    image: chrislusf/seaweedfs
    container_name: seaweedfs-filer
    command: "filer -master=master:9333"
    ports:
      - 8888:8888
    depends_on:
      - master
    networks:
      - seaweedfs-net
      - universe
    volumes:
      - ./data/seaweedfs-filer-data:/data

```
