### ISSUE TITLE
Getting error on Bucket#clear! since release from 12-7-2020

### ISSUE THREAD

**Issue by ghost** [minio/minio#10035]
I use minio for local testing my aws S3 stuff with the aws ruby sdk. With the latest version of minio I'm getting the error

```
Failure/Error: bucket.clear!
            Aws::S3::Errors::NotImplemented:
            A header you provided implies functionality that is not implemented
```

## Expected Behavior
The service should implement the AWS S3 interface

## Current Behavior
When calling the Bucket#clear! method I'm getting this error

```
Failure/Error: bucket.clear!

            Aws::S3::Errors::NotImplemented:
              A header you provided implies functionality that is not implemented
            # /usr/local/bundle/ruby/2.7.0/gems/aws-sdk-core-3.103.0/lib/seahorse/client/plugins/raise_response_errors.rb:17:in `call'
            # /usr/local/bundle/ruby/2.7.0/gems/aws-sdk-s3-1.73.0/lib/aws-sdk-s3/plugins/sse_cpk.rb:24:in `call'
            # /usr/local/bundle/ruby/2.7.0/gems/aws-sdk-s3-1.73.0/lib/aws-sdk-s3/plugins/dualstack.rb:28:in `call'
            # /usr/local/bundle/ruby/2.7.0/gems/aws-sdk-s3-1.73.0/lib/aws-sdk-s3/plugins/accelerate.rb:37:in `call'
            # /usr/local/bundle/ruby/2.7.0/gems/aws-sdk-core-3.103.0/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:22:in `call'
            # /usr/local/bundle/ruby/2.7.0/gems/aws-sdk-core-3.103.0/lib/aws-sdk-core/plugins/idempotency_token.rb:19:in `call'
            # /usr/local/bundle/ruby/2.7.0/gems/aws-sdk-core-3.103.0/lib/aws-sdk-core/plugins/param_converter.rb:26:in `call'
            # /usr/local/bundle/ruby/2.7.0/gems/aws-sdk-core-3.103.0/lib/aws-sdk-core/plugins/response_paging.rb:12:in `call'
            # /usr/local/bundle/ruby/2.7.0/gems/aws-sdk-core-3.103.0/lib/seahorse/client/plugins/response_target.rb:24:in `call'
            # /usr/local/bundle/ruby/2.7.0/gems/aws-sdk-core-3.103.0/lib/seahorse/client/request.rb:72:in `send_request'
            # /usr/local/bundle/ruby/2.7.0/gems/aws-sdk-s3-1.73.0/lib/aws-sdk-s3/client.rb:6350:in `list_object_versions'
            # /usr/local/bundle/ruby/2.7.0/gems/aws-sdk-s3-1.73.0/lib/aws-sdk-s3/bucket.rb:704:in `block in object_versions'
            # /usr/local/bundle/ruby/2.7.0/gems/aws-sdk-core-3.103.0/lib/aws-sdk-core/resources/collection.rb:101:in `each'
            # /usr/local/bundle/ruby/2.7.0/gems/aws-sdk-core-3.103.0/lib/aws-sdk-core/resources/collection.rb:101:in `each'
            # /usr/local/bundle/ruby/2.7.0/gems/aws-sdk-core-3.103.0/lib/aws-sdk-core/resources/collection.rb:101:in `block in non_empty_batches'
            # /usr/local/bundle/ruby/2.7.0/gems/aws-sdk-s3-1.73.0/lib/aws-sdk-s3/object_version.rb:530:in `each'
            # /usr/local/bundle/ruby/2.7.0/gems/aws-sdk-s3-1.73.0/lib/aws-sdk-s3/object_version.rb:530:in `each'
            # /usr/local/bundle/ruby/2.7.0/gems/aws-sdk-s3-1.73.0/lib/aws-sdk-s3/object_version.rb:530:in `batch_delete!'
            # /usr/local/bundle/ruby/2.7.0/gems/aws-sdk-s3-1.73.0/lib/aws-sdk-s3/customizations/bucket.rb:33:in `clear!'
```

## Regression
Maybe, with image RELEASE.2020-07-02T00-15-09Z it works well.

## Your Environment
* Version used latest image digest: ab0b45845f33
* Server setup and configuration: default
* Operating System and version: linux debian 10

**Comment by vadmeste** [comment]
@ALandscheidt could you paste a sample code which reproduces this ? or you can use `mc admin trace` and paste the failing request (make sure that you don't paste anything sensitive)

**Comment by harshavardhana** [comment]
@ALandscheidt use the https://github.com/minio/minio/releases/tag/RELEASE.2020-07-13T18-09-56Z latest release with multiple directories - It looks like you are using single disk mode `minio server /data` instead just provide `minio server /data{1..4}` and it should work for you.

**Comment by ghost** [comment]
@harshavardhana not sure if I did it right but it seems not to work for me. 

I'm using Minio with docker-compose and the tests running on jenkins:

This is the last configuration I tried
```
  minio:
    image: minio/minio:RELEASE.2020-07-13T18-09-56Z
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - ./miniodata:/data
    command: server /data1
```

This was the previous one

```
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - ./miniodata:/data
    command: server /data
```

For now we will set a fixed working release.
