### ISSUE TITLE
[resolved] four node cluster, 'delete pod minio-0' causes outage without recovery

### ISSUE THREAD

**Issue by skandragon** [minio/minio#10080]
When I start a fresh statefulset deployment in Kubernetes, and kill a pod, the system does not appear to recover.

# Expected Behavior

When the pod is recreated, I expect it to self-heal.

## Current Behavior

1.  'mc' sometimes works, sometimes times out.
2.  The web interface reports 'server is not initialized'

## Steps to Reproduce (for bugs)

1.  Build a 4 node cluster using yaml:

```
apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    app: minio
spec:
  clusterIP: None
  ports:
    - port: 9000
      name: minio
  selector:
    app: minio
  publishNotReadyAddresses: true
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
spec:
  serviceName: minio
  replicas: 4
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      containers:
      - name: minio
        env:
        - name: MINIO_ACCESS_KEY
          value: "keyGoesHere"
        - name: MINIO_SECRET_KEY
          value: "secretGoesHere"
        image: minio/minio:RELEASE.2020-07-14T19-14-30Z-arm64
        args:
        - server
        - http://minio-{0...3}.minio.minio.svc.cluster.local/data
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 200Gi
      # Uncomment and add storageClass specific to your requirements below. Read more https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1
      #storageClassName:
---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  type: LoadBalancer
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: minio
```

2. let things boot and store a few files.
3. delete a pod.
4. Watch things never recover.

It also seems that if two or more pods go down, the system constantly bounces, and 'mc admin info' reports nodes going up and down randomly, and times out often.

I was able to recover by deleting all pods again, and somehow this caused things to return to normal.

## Context

Testing failure conditions.

## Regression

Unknown

## Your Environment
* Version used:  minio/minio:RELEASE.2020-07-14T19-14-30Z-arm64
* Server setup and configuration: 

```
NAME                     STATUS   ROLES    AGE   VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE           KERNEL-VERSION     CONTAINER-RUNTIME
kubepi01.rpi.flame.org   Ready    master   26d   v1.18.5   10.45.100.1   <none>        Ubuntu 20.04 LTS   5.4.0-1013-raspi   docker://19.3.12
kubepi02.rpi.flame.org   Ready    worker   26d   v1.18.5   10.45.100.2   <none>        Ubuntu 20.04 LTS   5.4.0-1013-raspi   docker://19.3.12
kubepi03.rpi.flame.org   Ready    worker   26d   v1.18.5   10.45.100.3   <none>        Ubuntu 20.04 LTS   5.4.0-1013-raspi   docker://19.3.12
kubepi04.rpi.flame.org   Ready    worker   26d   v1.18.5   10.45.100.4   <none>        Ubuntu 20.04 LTS   5.4.0-1013-raspi   docker://19.3.12
```

* Operating System and version (`uname -a`):

**Comment by skandragon** [comment]
Running 'mc admin info' in a loop shows that my commend about recovery was premature.  Nodes are reported as up and down randomly and the UI sometimes works, sometimes reports 'not initialized'.

Logs:

```
kubectl -n minio logs minio-0

 You are running an older version of MinIO released 1 week ago
 Update: https://docs.min.io/docs/deploy-minio-on-kubernetes


Waiting for all MinIO sub-systems to be initialized.. lock acquired
All MinIO sub-systems initialized successfully
Waiting for all MinIO IAM sub-system to be initialized.. lock acquired
Use `mc admin info` to look for latest server/disk info
 Status:         3 Online, 1 Offline.
Endpoint:  http://10.1.108.63:9000  http://127.0.0.1:9000

Browser Access:
   http://10.1.108.63:9000  http://127.0.0.1:9000

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
```

```
$ kubectl -n minio logs minio-1

 You are running an older version of MinIO released 1 week ago
 Update: https://docs.min.io/docs/deploy-minio-on-kubernetes



API: SYSTEM()
Time: 06:29:55 UTC 07/18/2020
DeploymentID: 85b5d8ad-1c14-464f-9cd9-ca09b2c44465
Error: disk not found
       endpoint=http://minio-3.minio.minio.svc.cluster.local:9000/data
       2: github.com/minio/minio@/cmd/prepare-storage.go:51:cmd.glob..func5.1()
       1: github.com/minio/minio@/cmd/xl-sets.go:205:cmd.(*xlSets).connectDisks.func1()

API: SYSTEM()
Time: 06:29:55 UTC 07/18/2020
DeploymentID: 85b5d8ad-1c14-464f-9cd9-ca09b2c44465
Error: disk not found
       endpoint=http://minio-2.minio.minio.svc.cluster.local:9000/data
       2: github.com/minio/minio@/cmd/prepare-storage.go:51:cmd.glob..func5.1()
       1: github.com/minio/minio@/cmd/xl-sets.go:205:cmd.(*xlSets).connectDisks.func1()
```

```
$ kubectl -n minio logs minio-2

 You are running an older version of MinIO released 1 week ago
 Update: https://docs.min.io/docs/deploy-minio-on-kubernetes



API: SYSTEM()
Time: 06:29:59 UTC 07/18/2020
DeploymentID: 85b5d8ad-1c14-464f-9cd9-ca09b2c44465
Error: disk not found
       endpoint=http://minio-3.minio.minio.svc.cluster.local:9000/data
       2: github.com/minio/minio@/cmd/prepare-storage.go:51:cmd.glob..func5.1()
       1: github.com/minio/minio@/cmd/xl-sets.go:205:cmd.(*xlSets).connectDisks.func1()

API: SYSTEM()
Time: 06:29:59 UTC 07/18/2020
DeploymentID: 85b5d8ad-1c14-464f-9cd9-ca09b2c44465
Error: disk not found
       endpoint=http://minio-1.minio.minio.svc.cluster.local:9000/data
       2: github.com/minio/minio@/cmd/prepare-storage.go:51:cmd.glob..func5.1()
       1: github.com/minio/minio@/cmd/xl-sets.go:205:cmd.(*xlSets).connectDisks.func1()
```

```
$ kubectl -n minio logs minio-3

 You are running an older version of MinIO released 1 week ago
 Update: https://docs.min.io/docs/deploy-minio-on-kubernetes



API: SYSTEM()
Time: 06:30:03 UTC 07/18/2020
DeploymentID: 85b5d8ad-1c14-464f-9cd9-ca09b2c44465
Error: disk not found
       endpoint=http://minio-1.minio.minio.svc.cluster.local:9000/data
       2: github.com/minio/minio@/cmd/prepare-storage.go:51:cmd.glob..func5.1()
       1: github.com/minio/minio@/cmd/xl-sets.go:205:cmd.(*xlSets).connectDisks.func1()

API: SYSTEM()
Time: 06:30:03 UTC 07/18/2020
DeploymentID: 85b5d8ad-1c14-464f-9cd9-ca09b2c44465
Error: disk not found
       endpoint=http://minio-2.minio.minio.svc.cluster.local:9000/data
       2: github.com/minio/minio@/cmd/prepare-storage.go:51:cmd.glob..func5.1()
       1: github.com/minio/minio@/cmd/xl-sets.go:205:cmd.(*xlSets).connectDisks.func1()
```

The pods themselves do not restart according to Kubernetes.

**Comment by harshavardhana** [comment]
> 3\. Watch things never recover.

Your pod specification is wrong, here is a working example on how to use it. I delete pods and they all recover fine. 

```
## Create service of minio dist xl StatefulSet.
apiVersion: v1
kind: Service
metadata:
  name: minio-edge
spec:
  type: NodePort
  ports:
  - port: 9000
  selector:
    app: minio-app-edge
---
## Create headless service to StatefulSet to work.
apiVersion: v1
kind: Service
metadata:
  name: minio-headless-edge
  labels:
    app: minio-headless-edge
spec:
  ports:
  - port: 9000
  clusterIP: None
  selector:
    app: minio-app-edge
---
## Run minio dist xl StatefulSet.
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio-edge
spec:
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: "Parallel"
  serviceName: "minio-headless-edge"
  replicas: 4
  selector:
    matchLabels:
      app: minio-app-edge
  template:
    metadata:
      labels:
        app: minio-app-edge
    spec:
      containers:
      - name: minio-edge
        env:
        - name: MINIO_ACCESS_KEY
          value: "minio"
        - name: MINIO_SECRET_KEY
          value: "minio123"
        image: minio/minio:edge
        imagePullPolicy: Always
        args:
        - server
        - http://minio-edge-{0...3}.minio-headless-edge.default.svc.cluster.local/data
        ports:
        - containerPort: 9000
```
