### ISSUE TITLE
Environment variables for NSQ are parsed as the wrong format

### ISSUE THREAD

**Issue by ghost** [minio/minio#10100]
## Expected Behavior

When following the steps of the [documentation](https://docs.minio.io/docs/minio-bucket-notification-guide.html#NSQ), I expect that the environment variables for the NSQ config to get them parsed correctly.

## Current Behavior

It seems that the current parameters are parsed as boolean, although they have the `address` or `string` type.

## Steps to Reproduce (for bugs)

By using the following docker-compose, this issue can be reproduced.

```yaml
version: "3"

services:
  minio:
    image: minio/minio
    command: server /data
    ports:
      - "9100:9000"
    environment:
      - "MINIO_NOTIFY_NSQ_ENABLE=on"
      - "MINIO_NOTIFY_NSQ_NSQD_ADDRESS=nsqd:4150"
      - "MINIO_NOTIFY_NSQ_TOPIC=storage"

  nsqd:
    image: nsqio/nsq
    command: /nsqd
    ports:
      - "4150"
      - "4151"
```

When opening the logs `docker logs <container_id>` afterwards, I get the following output:

```
API: SYSTEM()
Time: 21:48:41 UTC 07/20/2020
DeploymentID: 9255a182-d0bf-4b62-8006-e299b63ff2f6
Error: Unable to initialize notification target(s): invalid argument
       7: github.com/minio/minio@/cmd/config-current.go:487:cmd.lookupConfigs()
       6: github.com/minio/minio@/cmd/config-current.go:604:cmd.loadConfig()
       5: github.com/minio/minio@/cmd/config.go:233:cmd.initConfig()
       4: github.com/minio/minio@/cmd/config.go:193:cmd.(*ConfigSys).Init()
       3: github.com/minio/minio@/cmd/server-main.go:322:cmd.initAllSubsystems()
       2: github.com/minio/minio@/cmd/server-main.go:247:cmd.initSafeMode()
       1: github.com/minio/minio@/cmd/server-main.go:517:cmd.serverMain()

API: SYSTEM()
Time: 21:48:41 UTC 07/20/2020
DeploymentID: 9255a182-d0bf-4b62-8006-e299b63ff2f6
Error: Unable to initialize notification target(s): ParseBool: parsing 'nsqd:4150': invalid syntax
       7: github.com/minio/minio@/cmd/config-current.go:492:cmd.lookupConfigs()
       6: github.com/minio/minio@/cmd/config-current.go:604:cmd.loadConfig()
       5: github.com/minio/minio@/cmd/config.go:233:cmd.initConfig()
       4: github.com/minio/minio@/cmd/config.go:193:cmd.(*ConfigSys).Init()
       3: github.com/minio/minio@/cmd/server-main.go:322:cmd.initAllSubsystems()
       2: github.com/minio/minio@/cmd/server-main.go:247:cmd.initSafeMode()
       1: github.com/minio/minio@/cmd/server-main.go:517:cmd.serverMain()
Endpoint:  http://172.21.0.3:9000  http://127.0.0.1:9000

Browser Access:
   http://172.21.0.3:9000  http://127.0.0.1:9000

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
Detected default credentials 'minioadmin:minioadmin', please change the credentials immediately using 'MINIO_ACCESS_KEY' and 'MINIO_SECRET_KEY'
```
