### ISSUE TITLE
[not our bug] Deploy on 3 nodes failed "Expected endpoint"

### ISSUE THREAD

**Issue by Fyne5** [minio/minio#10123]
Dear friends,

Today I deploy docker-compose config on 3 nodes and got the error:
```
k1_1_8bc74a13671c | API: SYSTEM()
k1_1_8bc74a13671c | Time: 22:02:12 UTC 07/22/2020
k1_1_8bc74a13671c | Error: http://192.168.56.102:9000/data1 as has incorrect configuration: Expected endpoint http://k1/data1, seen http://k2/data1
k1_1_8bc74a13671c |        1: github.com/minio/minio@/cmd/server-main.go:486:cmd.serverMain()
```

Second node
```
k2_1_c151e5a8b97f | API: SYSTEM()
k2_1_c151e5a8b97f | Time: 22:07:56 UTC 07/22/2020
k2_1_c151e5a8b97f | Error: http://192.168.56.101:9000/data1 as has incorrect configuration: Expected endpoint http://k2/data1, seen http://k1/data1
k2_1_c151e5a8b97f |        1: github.com/minio/minio@/cmd/server-main.go:486:cmd.serverMain()
```

Here docker-compose from node 1:
```
version: '3.7'

# starts 2 docker containers running minio server instances. Each
# minio server's web interface will be accessible on the host at port
# 9001 through 9004.
services:
  k1:
    image: minio/minio:RELEASE.2020-07-22T00-26-33Z
    volumes:
      - ./data1-1:/data1
      - ./data1-2:/data2
      - ./data1-3:/data3
      - ./data1-4:/data4
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: 12312311
    command: server http://k1/data{1...4} http://192.168.56.10{2...3}/data{1...4}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3.
    extra_hosts:
      - "k2:192.168.56.102"
      - "k3:192.168.56.103"

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  data1-1:
  data1-2:
  data1-3:
  data1-4:
```

And the same for 2 last nodes. I searched around but not found solution, could you please let me know what I'm wrong and how can i solve it. Thanks!
