### ISSUE TITLE
[faq] Can MinIO be hosted at a sub-path

### ISSUE THREAD

**Issue by Hokwang** [minio/minio#10162]
Hello.

I am trying to install minio on the kubernetes cluster which is in on-prem servers.
In my company, here's http proxy and user can't make sub domain easily.
so I need ingress sub path like company.net/minio, company.net/minio-stage, ...

my values.yaml is
```
mode: distributed

persistence:
  storageClass: "sas-ssd1-stage"

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  path: /minio-stage
  hosts:
    - company.net
  tls:
    - secretName: ingress-tls
      hosts:
        - company.net
```

When I access https://company.net/minio-stage
but it redirect to https://company.net/minio/minio-stage

when I change path in vaules.yaml
```
path: /minio
```

I can access https://company.net/minio successfully.
but left bottom of the screen, address show company.net not company.net/minio

and when I upload some file, click share icon,
shareable link is
https://company.net/<bucketname>/<filename>?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-<snip>
this is wrong.
https://company.net/minio/<bucketname>/<filename>/... is right.

Can I use minio with sub path?
If so, is there a default config for path (eg. minio) ?

Thanks,
