### ISSUE TITLE
[resolved] lifecycle configuration does not work

### ISSUE THREAD

**Issue by jianwang-beijing** [minio/minio#10255]
lifecycle does not works
## Expected Behavior
Files in bucket should be deleted after expiry days

## Current Behavior
Files remain

## Possible Solution
No
#### 1 check current lifecycle
```
mc list minio/
mc ilm list minio/ng-temp
```
#### 2 create a test rule file(lifecycle.json)
```
{
  "Rules": [
    {
      "Expiration": {
        "Days": 1
      },
      "ID": "TestRule",
      "Status": "Enabled",
      "NoncurrentVersionExpiration": {
        "NoncurrentDays": 1
      },
      "AbortIncompleteMultipartUpload": {
        "DaysAfterInitiation": 1
      }
    }
  ]
}

```
#### 3 apply the new test rule
```
mc ilm import minio/ng-temp < lifecycle.json
```

#### 4 cp some test file in temp bucket
```
mc cp lifecycle.json minio/ng-temp/debug/lifecycle1.json
mc cp lifecycle.json minio/ng-temp/debug/lifecycle2.json
```

#### 5 check the test file after one day
I hope the `ng-temp` bucket is empty

## Regression
No
## Your Environment

* Version used (`minio --version`): RELEASE.2020-05-16T01-44-37Z
* Server setup and configuration:
* Operating System and version (`uname -a`): Linux ip-10-0-170-187.cn-northwest-1.compute.internal 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
> * Version used (`minio --version`): RELEASE.2020-05-16T01-44-37Z

@jianwang-beijing please upgrade to latest release - we rewrote the entire lifecycle implementation.

**Comment by jianwang-beijing** [comment]
> > * Version used (`minio --version`): RELEASE.2020-05-16T01-44-37Z
> 
> @jianwang-beijing please upgrade to latest release - we rewrote the entire lifecycle implementation.

Sorry, I also want make sure  if my lifecycle.json is right. I want to apply the expiration rule for whole bucket. So should I need to config the `Filter`, if necessary, how to config?(I can find out at docs/bucket/lifecycle/README.md)

**Comment by harshavardhana** [comment]
> Sorry, I also want make sure if my lifecycle.json is right. I want to apply the expiration rule for whole bucket. So should I need to config the `Filter`, if necessary, how to config?(I can find out at docs/bucket/lifecycle/README.md)

Its right here https://docs.minio.io/docs/minio-bucket-lifecycle-guide.html

**Comment by jianwang-beijing** [comment]
> > Sorry, I also want make sure if my lifecycle.json is right. I want to apply the expiration rule for whole bucket. So should I need to config the `Filter`, if necessary, how to config?(I can find out at docs/bucket/lifecycle/README.md)
> 
> Its right here https://docs.minio.io/docs/minio-bucket-lifecycle-guide.html

I also do my test following the document in office website. The reason I want to ask the question is the https://github.com/minio/minio/issues/8109. Ok, both the lifecycle/README.md and minio-bucket-lifecycle-guide.html can not tell how to configuration if I want to apply a rule for whole bucket. If my bucket name is `ng-temp`, In the below two way, which is rights?
`A:`
```
{
      "Expiration": {
        "Days": 1
      },
      "ID": "TestRule",
      "Status": "Enabled",
      "NoncurrentVersionExpiration": {
        "NoncurrentDays": 1
      },
      "AbortIncompleteMultipartUpload": {
        "DaysAfterInitiation": 1
      }
    },
```
`B:`
```
{
      "Expiration": {
        "Days": 1
      },
      "Filter": {
        "Prefix": "ng-temp/"
      },
      "ID": "BucketFilter",
      "Status": "Enabled",
      "NoncurrentVersionExpiration": {
        "NoncurrentDays": 1
      },
      "AbortIncompleteMultipartUpload": {
        "DaysAfterInitiation": 1
      }
    }
```
`A` or `B`?

**Comment by jianwang-beijing** [comment]
I have setup the latest version minio with docker-compose. The yaml looks like:
```
version: '3.7'

# starts 4 docker containers running minio server instances. Each
# minio server's web interface will be accessible on the host at port
# 9001 through 9004. 
services:
  minio1:
    image: minio/minio:RELEASE.2020-08-13T02-39-50Z
    volumes:
      - data1-1:/data1
      - data1-2:/data2
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio{1...4}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio2:
    image: minio/minio:RELEASE.2020-08-13T02-39-50Z
    volumes:
      - data2-1:/data1
      - data2-2:/data2
    ports:
      - "9002:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio{1...4}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio3:
    image: minio/minio:RELEASE.2020-08-13T02-39-50Z
    volumes:
      - data3-1:/data1
      - data3-2:/data2
    ports:
      - "9003:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio{1...4}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio4:
    image: minio/minio:RELEASE.2020-08-13T02-39-50Z
    volumes:
      - data4-1:/data1
      - data4-2:/data2
    ports:
      - "9004:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio{1...4}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  data1-1:
  data1-2:
  data2-1:
  data2-2:
  data3-1:
  data3-2:
  data4-1:
  data4-2:
```
I use the below command to create the lifecycle:
```
mc ilm import local/ng-temp < lifecycle.json
```
the lifecycle.json look like:
```
{
  "Rules": [
    {
      "Expiration": {
        "Days": 1
      },
      "ID": "TestRule",
      "Status": "Enabled",
      "NoncurrentVersionExpiration": {
        "NoncurrentDays": 1
      },
      "AbortIncompleteMultipartUpload": {
        "DaysAfterInitiation": 1
      }
    },
    {
      "Expiration": {
        "Days": 1
      },
      "Filter": {
        "Prefix": "ng-temp/"
      },
      "ID": "BucketFilter",
      "Status": "Enabled",
      "NoncurrentVersionExpiration": {
        "NoncurrentDays": 1
      },
      "AbortIncompleteMultipartUpload": {
        "DaysAfterInitiation": 1
      }
    }
  ]
}
```
As same with my first test case, I copy some files in local/ng-temp bucket after I create the lifecycle rule. The files are remain after my expected expiration days.
![image](https://user-images.githubusercontent.com/54609180/90337274-053be300-e014-11ea-8b57-b4601a89da67.png)
So what's wrong about the lifecycle?
