### ISSUE TITLE
Bug: minio pod is not start with operator 3.0.12

### ISSUE THREAD

**Issue by rerime** [minio/minio#10266]
minio-operator: `3.0.12`
Checked few latest minio versions
**ERROR Invalid command line arguments: Invalid arguments specified**
```
apiVersion: v1
kind: Secret
metadata:
  name: minio-creds-secret
type: Opaque
data:
  accesskey: bWluaW8= # base 64 encoded "minio" (echo -n 'minio' | base64)
  secretkey: bWluaW8xMjM= # based 64 encoded "minio123" (echo -n 'minio123' | base64)
---
apiVersion: minio.min.io/v1
kind: Tenant
metadata:
  name: minio
## If specified, Tenant pods will be dispatched by specified scheduler.
## If not specified, the pod will be dispatched by default scheduler.
# scheduler:
#  name: my-custom-scheduler
spec:
  ## Add metadata to the all pods created by the StatefulSet
  metadata:
    ## Optionally pass labels to be applied to the statefulset pods
    labels:
      app: minio
    annotations:
      prometheus.io/path: /minio/prometheus/metrics
      prometheus.io/port: "9000"
      prometheus.io/scrape: "true"

  ## Registry location and Tag to download MinIO Server image
  image: minio/minio
  zones:
    - servers: 4
      volumesPerServer: 1
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
        # if you have direct-csi installed https://github.com/minio/direct-csi
        # storageClassName: direct.csi.min.io
  ## Mount path where PV will be mounted inside container(s). Defaults to "/export".
  mountPath: /export
  ## Sub path inside Mount path where MinIO starts. Defaults to "".
  # subPath: /data
  ## This VolumeClaimTemplate is used across all the volumes provisioned for MinIO cluster.
  ## Please do not change the volumeClaimTemplate field while expanding the cluster, this may
  ## lead to unbound PVCs and missing data
  ## Secret with credentials to be used by MinIO instance.
  credsSecret:
    name: minio-creds-secret

  ## PodManagement policy for pods created by StatefulSet. Can be "OrderedReady" or "Parallel"
  ## Refer https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/#pod-management-policy
  ## for details. Defaults to "Parallel"
  podManagementPolicy: Parallel
  ## Secret with certificates to configure TLS for MinIO certs. Create secrets as explained
  ## here: https://github.com/minio/minio/tree/master/docs/tls/kubernetes#2-create-kubernetes-secret
  # externalCertSecret:
  # name: tls-ssl-minio
  ## Enable Kubernetes based certificate generation and signing as explained in
  ## https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster
  requestAutoCert: false

  ## Used when "requestAutoCert" is set to true. Set CommonName for the auto-generated certificate.
  ## Internal DNS name for the pod will be used if CommonName is not provided.
  ## DNS name format is minio-{0...3}.minio.default.svc.cluster.local
  certConfig:
    commonName: ""
    organizationName: []
    dnsNames: []

  ## Used to specify a toleration for a pod
  # tolerations:
    #  - effect: NoSchedule
    #    key: dedicated
    #    operator: Equal
    #    value: storage

  ## Add environment variables to be set in MinIO container (https://github.com/minio/minio/tree/master/docs/config)
  # env:
    # - name: MINIO_BROWSER
    #   value: "off" # to turn-off browser
    # - name: MINIO_STORAGE_CLASS_STANDARD
    #   value: "EC:2"

  ## Configure resource requests and limits for MinIO containers
  # resources:
  #   requests:
  #     cpu: 250m
  #     memory: 16Gi
  #   limits:
  #     cpu: 500m
  #      memory: 16Gi

  ## Liveness probe detects situations where MinIO server instance
  ## is not working properly and needs restart. Kubernetes automatically
  ## restarts the pods if liveness checks fail.
  liveness:
    initialDelaySeconds: 10
    periodSeconds: 1
    timeoutSeconds: 1

  ## nodeSelector parameters for MinIO Pods. It specifies a map of key-value pairs. For the pod to be
  ## eligible to run on a node, the node must have each of the
  ## indicated key-value pairs as labels.
  ## Read more here: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
  # nodeSelector:
  #   disktype: ssd
  #
  ## Affinity settings for MinIO pods. Read more about affinity
  ## here: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity.
  # affinity:

  ## PriorityClassName indicates the Pod priority and hence importance of a Pod relative to other Pods.
  ## This is applied to MinIO pods only.
  ## Refer Kubernetes documentation for details https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/#priorityclass/
  # priorityClassName: high-priority
```
