### ISSUE TITLE
[working as intended] O_DIRECT error when using minio on OSX with docker (erasure coding)

### ISSUE THREAD

**Issue by 3pns** [minio/minio#10277]
This bug is related to #9554

I am getting the following error when trying to use minio with OSX using docker-compose and using the tags :
- edge
- RELEASE.2020-08-16T18-39-38Z  

```
2020-08-17T10:13:16.782153134Z ERROR Unable to initialize backend: Unable to write to the backend
2020-08-17T10:13:16.782204468Z       > Please ensure your disk supports O_DIRECT
2020-08-17T10:13:16.782211280Z       HINT:
2020-08-17T10:13:16.782214450Z         '/data1' does not support O_DIRECT flags, refusing to use
```
I am getting the following permissions errors using the tag 
- RELEASE.2020-05-06T23-23-25Z

```
2020-08-17T10:42:28.445873679Z ERROR Unable to initialize posix backend: open /data1/.writable-check-9efe938f0de7065a.tmp: invalid argument
2020-08-17T10:42:28.445882319Z       > Please ensure MinIO binary has write permissions for the backend
2020-08-17T10:42:28.445884828Z       HINT:
2020-08-17T10:42:28.445886848Z         Run the following command to add the convenient permissions: `sudo chown root /data1 && sudo chmod u+rxw /data1`
```

However the same docker-compose.yml file will work using minio with the tag
- RELEASE.2020-04-28T23-56-56Z

**Comment by harshavardhana** [comment]
> This bug is related to #9554
> 
> I am getting the following error when trying to use minio with OSX using docker-compose and using the tags :
> 
> * edge
> * RELEASE.2020-08-16T18-39-38Z
> 
> ```
> 2020-08-17T10:13:16.782153134Z ERROR Unable to initialize backend: Unable to write to the backend
> 2020-08-17T10:13:16.782204468Z       > Please ensure your disk supports O_DIRECT
> 2020-08-17T10:13:16.782211280Z       HINT:
> 2020-08-17T10:13:16.782214450Z         '/data1' does not support O_DIRECT flags, refusing to use
> ```
> 
> I am getting the following permissions errors using the tag
> 
> * RELEASE.2020-05-06T23-23-25Z
> 
> ```
> 2020-08-17T10:42:28.445873679Z ERROR Unable to initialize posix backend: open /data1/.writable-check-9efe938f0de7065a.tmp: invalid argument
> 2020-08-17T10:42:28.445882319Z       > Please ensure MinIO binary has write permissions for the backend
> 2020-08-17T10:42:28.445884828Z       HINT:
> 2020-08-17T10:42:28.445886848Z         Run the following command to add the convenient permissions: `sudo chown root /data1 && sudo chmod u+rxw /data1`
> ```
> 
> However the same docker-compose.yml file will work using minio with the tag
> 
> * RELEASE.2020-04-28T23-56-56Z

We do not support backend drives which do not support O_DIRECT 

There is no way for us to fix this situation for you.

It is not a regression, in FS mode we do not require O_DIRECT you seem to be trying to use erasure coding.

**Comment by 3pns** [comment]
> We do not support backend drives which do not support O_DIRECT
> 
> There is no way for us to fix this situation for you.
> 
> It is not a regression, in FS mode we do not require O_DIRECT you seem to be trying to use erasure coding.

Thanks for the reply, I was able to make it work with your hint, somehow I got misleaded by the documentation as I was looking for a ready to use docker-compose.yml to run minio on my computer. (in the past I only used minio with helm/kubernetes)

https://docs.min.io/docs/deploy-minio-on-docker-compose
https://github.com/minio/minio/blob/master/docs/orchestration/docker-compose/docker-compose.yaml?raw=true

The docker-compose file is configured with 4 services, as per your instruction I simplified it to 1 service and it works now :

```
version: '3.7'

services:
  minio1:
    image: minio/minio:RELEASE.2020-08-16T18-39-38Z 
    volumes:
      - ./data:/data
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
```
