### ISSUE TITLE
Trying to fetch vm images from minio for kubevirt; "Error opening file: Server does not support 'range' (byte ranges)."

### ISSUE THREAD

**Issue by larsks** [minio/minio#10272]
## Expected Behavior

I was hoping that the CDI importer (for importing remote URLs into `datavolumes` on kubevirt) would be able to import images from minio.

## Current Behavior

I'm running CNV (aka Kubevirt) on OpenShift 4.5.5. I was hoping to use Minio to provide a local cache for vm images. Uploading images to minio works just fine, but trying to use them as the source for a `datavolume`, like this:

```
[...]
    dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1alpha1
      kind: DataVolume
      metadata:
        name: ${NAME}-disk0
      spec:
        pvc:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
          storageClassName: hostpath-provisioner
          volumeMode: Filesystem
        source:
          http:
            url: https://minio-minio.apps.cnv.example.com/images/centos-8-x86_64
```

Fails with the following error when CDI attempts to import the image:

> E0815 03:56:36.515299       1 importer.go:159] qemu-img: Could not open 'json: {"file.driver": "https", "file.url": "https://minio-minio.apps.cnv.example.com/images/centos-8-x86_64", "file.timeout": 3600}': CURL: Error opening file: Server does not support 'range' (byte ranges).

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2020-08-08T04-50-06Z
* Server setup and configuration: openshift 4.5.5, installed from minio helm charts (modified e.g. to remove `runAsUser`)
* Operating System and version (`uname -a`): RHCOS 45.82.202008010929-0 (openshift 4.5.5)
