### ISSUE TITLE
Expected 'storage' API version 'v20', instead found 'v20', please upgrade the servers

### ISSUE THREAD

**Issue by hetianyi** [minio/minio#10329]
## Current Behavior

```shell
Unable to read 'format.json' from http://minio-0:9000/data: Expected 'storage' API version 'v20', instead found 'v20', please upgrade the servers
```
## Steps to Reproduce (for bugs)

I'm using helm to deploy a minio cluster, here is my helm chart:

**values.yaml:**
```yaml
namespace: minio
tz: "Asia/Shanghai"
minio:
  version: RELEASE.2020-08-18T19-41-00Z
  accessKey: bWluaW86YWRtaW46MTIzCg== # minio:admin:123
  secretKey: bWluaW86YWRtaW46MXEydzNlNHIK # minio:admin:1q2w3e4r
  containerDataDir: /data
  eraseData: true
  cluster:
    - port: 9000
      bindHostName: manager
      hostDataDir: /var/minio/m1
    - port: 9000
      bindHostName: manager
      hostDataDir: /var/minio/m2
    - port: 9000
      bindHostName: manager
      hostDataDir: /var/minio/m3
    - port: 9000
      bindHostName: manager
      hostDataDir: /var/minio/m4
    - port: 9000
      bindHostName: worker1
      hostDataDir: /var/minio/m1
    - port: 9000
      bindHostName: worker1
      hostDataDir: /var/minio/m2
    - port: 9000
      bindHostName: worker1
      hostDataDir: /var/minio/m3
    - port: 9000
      bindHostName: worker1
      hostDataDir: /var/minio/m4
```

**deployment.yaml:**
```yaml
{{- range $i,$c := .Values.minio.cluster }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio-{{ $i }}
  namespace: {{ $.Values.namespace }}
  labels:
    app: minio-{{ $i }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio-{{ $i }}
  serviceName: minio-{{ $i }}
  template:
    metadata:
      labels:
        app: minio-{{ $i }}
    spec:
      volumes:
        - name: minio-data-dir
          persistentVolumeClaim:
            claimName: minio-{{ $i }}
        - name: init
          configMap:
            name: init
      containers:
        - name: minio-server
          image: minio/minio:{{ $.Values.minio.version }}
          imagePullPolicy: IfNotPresent
          args:
            - server
            - --address
            - ":{{ $c.port }}"
            - http://minio-{0...7}/data
            #{{- range $n,$x := $.Values.minio.cluster }}
            #- {{ printf "http://minio-%d:%d%s " $n ($x.port | int) $.Values.minio.containerDataDir }}
            #{{- end }}
          ports:
            - containerPort: {{ $c.port }}
          env:
            - name: TZ
              value: {{ $.Values.tz }}
            - name: MINIO_ACCESS_KEY
              value: {{ $.Values.minio.accessKey | quote }}
            - name: MINIO_SECRET_KEY
              value: {{ $.Values.minio.secretKey | quote }}
          volumeMounts:
            - name: minio-data-dir
              mountPath: {{ $.Values.minio.containerDataDir }}
      initContainers:
      - image: hehety/alpine:dev
        name: init
        command:
          - /bin/sh
          - "/app/init.sh"
        env:
          - name: EraseData
            value: {{ $.Values.minio.eraseData | quote }}
          - name: ContainerDataDir
            value: {{ $.Values.minio.containerDataDir }}
        volumeMounts:
          - name: minio-data-dir
            mountPath: {{ $.Values.minio.containerDataDir }}
          - name: init
            mountPath: /app

---
{{- end }}
```

**service.yaml:**
```yaml
{{- range $i,$c := .Values.minio.cluster -}}
apiVersion: v1
kind: Service
metadata:
  name: minio-{{ $i }}
  namespace: {{ $.Values.namespace }}
  labels:
    app: minio-{{ $i }}
spec:
  type: ClusterIP
  selector:
    app: minio-{{ $i }}
  ports:
    - name: http
      port: {{ $c.port }}
      targetPort: {{ $c.port }}
      protocol: TCP
---
{{ end }}

```
## Your Environment

* Version used (`minio --version`): ```RELEASE.2020-08-18T19-41-00Z```
* Server setup and configuration:
* Operating System and version (`uname -a`): Linux 3.10.0-1127.10.1.el7.x86_64 #1 SMP Wed Jun 3 14:28:03 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

full helm chart is available here

[minio-helm.tar.gz](https://github.com/minio/minio/files/5113363/minio-helm.tar.gz)
