### ISSUE TITLE
[resolved] Running minio on Windows kubernetes workers with caching options

### ISSUE THREAD

**Issue by Win32Sector** [minio/minio#10331]
Running minio on Windows kubernetes workers with caching options crashes with error 

ERROR Unable to initialize disk caching: Atime support required for disk caching

## Expected Behavior
Pod started and cache works.

## Current Behavior
Pod in CrashLoopBackOf status

## Steps to Reproduce (for bugs)

1. I build Image docker pull win32sector/minio-nanoserver:1809 for running minio on windows nodes. 

2. I tried to run minio in standalone mode with command minio.exe server c:/export(for test) and adding cache options. 

I see this issue https://github.com/minio/minio/issues/8125 and I know Disk caching requires atime to be enabled on the cache drive(s) for cache eviction
But it's about linux, and my issue about running on windows and I don't know, what is windows analog for atime option.
May be parameters in article by thise link I need to use? https://www.opentechguides.com/how-to/article/windows-10/129/enable-last-access-time.html

Is cache working on windows as well?

## Your Environment

* Version used (`minio --version`): minio.RELEASE.2020-04-28T23-56-56Z
* Server setup and configuration: Virtual machine on Azure 
* Operating System and version (`uname -a`): Windows version 10.0.17763

**Comment by Win32Sector** [comment]
I tried to execute 

fsutil behavior set disablelastaccess 0 

on windows node and in dockerfile, but I receive error anyway.

**Comment by harshavardhana** [comment]
Without atime support we cannot support caching on disks, you should use windows disks directly without containers which already support atime or just use Linux.

There is nothing we can do to fix it for you.

**Comment by Win32Sector** [comment]
You know, it doesn't work without containers on windows.
Maybe because in your code

https://github.com/minio/minio/blob/36d36fab0bfeb0e91099e852408d0e1ac2e06440/cmd/disk-cache-check-support_windows.go

Here:

```
lowSetting := setting & 0xFFFF
	if lowSetting != uint64(0x0000) && lowSetting != uint64(0x0002) {
		return errors.New("Atime not supported")
	}
```

You want to see 0x0000 or 0x0002, but realy, values are  0x80000000 if DisableLastAccess = 0  (User Managed, Disabled) 
and 0x80000002 if DisableLastAccess = 2  (System Managed, Disabled) 


```
PS C:\Windows\system32> fsutil behavior query disablelastaccess
DisableLastAccess = 0  (User Managed, Disabled)

PS C:\Windows\system32> reg query HKLM\SYSTEM\CurrentControlSet\Control\FileSystem /v NtfsDisableLastAccessUpdate

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem
    NtfsDisableLastAccessUpdate    REG_DWORD    0x80000000
```
```

PS C:\Windows\system32> fsutil behavior set disablelastaccess 2
DisableLastAccess = 2  (System Managed, Disabled)
PS C:\Windows\system32> reg query HKLM\SYSTEM\CurrentControlSet\Control\FileSystem /v NtfsDisableLastAccessUpdate

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem
    NtfsDisableLastAccessUpdate    REG_DWORD    0x80000002

```

**Comment by harshavardhana** [comment]
> lowSetting := setting & 0xFFFF

You are missing the logical operation - here which is meant to extract the last remaining bits here @Win32Sector  

https://play.golang.org/p/bR2oydZW3gq

The check is correct.

**Comment by Win32Sector** [comment]
But why I can't run minio with caching on windows if I have correct value of NtfsDisableLastAccessUpdate?
This behavior on my notebook with windows, on vm with windows 10 and windows server 2019, on my windows kubernetes nodes in Azure. 

It reproduced in containers and when I run minio directly, for example minio.exe gateway s3 http://addres:port with caching or minio.exe server /data with cache on fast disk.

**Comment by harshavardhana** [comment]
> But why I can't run minio with caching on windows if I have correct value of NtfsDisableLastAccessUpdate?
> This behavior on my notebook with windows, on vm with windows 10 and windows server 2019, on my windows kubernetes nodes in Azure.

I don't know - I never use windows so can't really tell you why. 

how did you set caching? can you show me the error that you see? and also the environment variable used?

**Comment by Win32Sector** [comment]
I tried two scenaries: run locally and run in docker:
1. 

```
C:\Users\user1\repos\minio-windows\cache>set MINIO_ACCESS_KEY=minio

C:\Users\user1\repos\minio-windows\cache>set MINIO_SECRET_KEY=minio123

C:\Users\user1\repos\minio-windows\cache>set MINIO_CACHE="on"

C:\Users\user1\repos\minio-windows\cache>set MINIO_CACHE_DRIVES=C:\cache

C:\Users\user1\repos\minio-windows\cache>set MINIO_CACHE_QUOTA=80

C:\Users\user1\repos\minio-windows\cache>set MINIO_CACHE_AFTER=0

C:\Users\user1\repos\minio-windows\cache>set MINIO_CACHE_WATERMARK_LOW=70

C:\Users\user1\repos\minio-windows\cache>set MINIO_CACHE_WATERMARK_HIGH=90

C:\Users\user1\repos\minio-windows\cache>minio server C:\data

+-----------------------------------------------------------------+
| You are running an older version of MinIO released 3 months ago |
| Update: Run mc admin update                                   |
+-----------------------------------------------------------------+

Attempting encryption of all config, IAM users and policies on MinIO backend
ERROR Unable to initialize disk caching: Atime support required for disk caching
```

2. And in docker:

It is a Dockerfile 
```

FROM mcr.microsoft.com/windows/nanoserver:1809
USER ContainerAdministrator
SHELL [ "md", "C:\\app", "C:\\export", "C:\\cache"]
WORKDIR C:\\app
ADD minio.exe C:\\app
EXPOSE 9000
ENTRYPOINT  ["minio.exe"]

```

And docker-compose.yml

```
version: '3.7'

services:
  minio:
    image: win32sector/minio-nanoserver:1809
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data

  minio-cache:
    image: win32sector/minio-nanoserver:1809
    restart: on-failure
    container_name: minio-cache
    volumes:
      - "C:\\data:C:\\data"
    ports:
      - 9002:9000
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_CACHE: "on"
      MINIO_CACHE_DRIVES: C:\cache
      MINIO_CACHE_QUOTA: 80
      MINIO_CACHE_AFTER: 0
      MINIO_CACHE_WATERMARK_LOW: 70
      MINIO_CACHE_WATERMARK_HIGH: 90
    command: gateway s3 http://minio:9000
    depends_on: 
      - minio
```

When I execute docker-compose up -d I see two containers - one - minio  in status Running, and minio-cache in restarting 

```
C:\Users\user1\repos\minio-windows>docker ps
CONTAINER ID        IMAGE                               COMMAND                  CREATED             STATUS                        PORTS                    NAMES
f9daade0ba28        win32sector/minio-nanoserver:1809   "minio.exe gateway s…"   18 seconds ago      Restarting (1) 1 second ago                            minio-cache
351d543d951e        win32sector/minio-nanoserver:1809   "minio.exe server /d…"   20 seconds ago      Up 17 seconds                 0.0.0.0:9001->9000/tcp   minio-windows_minio_1

C:\Users\user1\repos\minio-windows>docker logs f9da
ERROR Unable to initialize disk caching: Atime support required for disk caching
ERROR Unable to initialize disk caching: Atime support required for disk caching
```

What can I try to do?
