### ISSUE TITLE
[working as intended] SetBucketQuota does not work in single drive mode

### ISSUE THREAD

**Issue by steffens-a** [minio/minio#10371]
* `mc admin bucket quota  minio/sccache --fifo 10GB`
* `mc admin bucket quota minio/sccache`
return unexpected
```
mc: <ERROR> Unable to set bucket quota. This 'admin' API is not supported by server in 'mode-server-fs'.
````

configuration: docker-compose.yml
````
version: "3.3"

services:
    
  minio-server:
    restart: always
    image: minio/minio:RELEASE.2020-08-18T19-41-00Z 
    container_name: minio-server
    hostname : minio-server
    command:  [ "server", "/data" ]
    environment:
      MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
      MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      MINIO_COMPRESS: "on"
    volumes:
      - /var/opt/minio/data:/data
    ports:
      - "9000:9000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
````
