### ISSUE TITLE
[not our bug] Unable to read 'format.json' from http://ip:9000/data-mi/data1: Expected 'storage' API version 'v20', instead found 'a1', please upgrade the servers

### ISSUE THREAD

**Issue by thewholeworld** [minio/minio#10529]
## Expected Behavior
![image](https://user-images.githubusercontent.com/41433762/93774394-d1c42800-fc53-11ea-9f99-82c019b02ab8.png)

## Current Behavior
I use four me

## Possible Solution

I have used four machines to deploy Minio, but after the command is started, I will be prompted that there is a problem in the picture. Why is there a version problem? How can I solve this exception?
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`):
![image](https://user-images.githubusercontent.com/41433762/93774834-41d2ae00-fc54-11ea-9572-0296c4d32620.png)

* Server setup and configuration:
* Operating System and version (`uname -a`):
![image](https://user-images.githubusercontent.com/41433762/93774846-45fecb80-fc54-11ea-9a3d-decbcea4b8a6.png)

**Comment by harshavardhana** [comment]
> ##
> I have used four machines to deploy Minio, but after the command is started, I will be prompted that there is a problem in the picture. Why is there a version problem? How can I solve this exception?

Most probably you have a 

- proxy in between
- they can't talk to each other

**Comment by zieg8301** [comment]
I am experiencing the same issue. Steps to reproduce: 
Environment: 4 cleanly imaged servers running centos7

1. docker run -d -p 9000:9000 -v /tmp/data:/data -e MINIO_ACCESS_KEY=minio1234 -e MINIO_SECRET_KEY=minio1234 minio/minio:latest server http://10.59.32.38:9000/data http://10.59.32.49:9000/data http://10.59.32.88:9000/data http://10.59.32.82:9000/data

Error: 
```
Unable to read 'format.json' from http://10.59.32.38:9000/data: Expected 'storage' API version 'v20', instead found 'v20', please upgrade the servers
Unable to read 'format.json' from http://10.59.32.49:9000/data: Expected 'storage' API version 'v20', instead found 'v20', please upgrade the servers
Unable to read 'format.json' from http://10.59.32.88:9000/data: Expected 'storage' API version 'v20', instead found 'v20', please upgrade the servers
Unable to read 'format.json' from http://10.59.32.82:9000/data: Expected 'storage' API version 'v20', instead found 'v20', please upgrade the servers
Waiting for a minimum of 2 disks to come online (elapsed 11s)
Unable to read 'format.json' from http://10.59.32.38:9000/data: Expected 'storage' API version 'v20', instead found 'v20', please upgrade the servers
Unable to read 'format.json' from http://10.59.32.49:9000/data: Expected 'storage' API version 'v20', instead found 'v20', please upgrade the servers
Unable to read 'format.json' from http://10.59.32.88:9000/data: Expected 'storage' API version 'v20', instead found 'v20', please upgrade the servers
Unable to read 'format.json' from http://10.59.32.82:9000/data: Expected 'storage' API version 'v20', instead found 'v20', please upgrade the servers
Waiting for a minimum of 2 disks to come online (elapsed 12s)
```

No firewall, all servers can ping each other and are in the same subnet and while docker containers are running, all can curl each other on <IP address>:9000 and return:
```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>XMinioServerNotInitialized</Code><Message>Server not initialized, please try again.</Message><Resource>/</Resource><RequestId>1636E2E878A18F0B</RequestId><HostId></HostId></Error>
```
/tmp/data is 0777 on all participants

**Comment by harshavardhana** [comment]
> I am experiencing the same issue. Steps to reproduce:
> Environment: 4 cleanly imaged servers running centos7
> 
> 1. docker run -d -p 9000:9000 -v /tmp/data:/data -e MINIO_ACCESS_KEY=minio1234 -e MINIO_SECRET_KEY=minio1234 minio/minio:latest server http://10.59.32.38:9000/data http://10.59.32.49:9000/data http://10.59.32.88:9000/data http://10.59.32.82:9000/data

@zieg8301 here the IPs are from the host node? how can they communicate without you providing `--net=host` ?

**Comment by zieg8301** [comment]
The IPs are the public IPs of the centos servers themselves. The -p switch is exposing the docker container port on the docker host on each server: 

```
[root@benlx0002 ~]# netstat -lnt
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 10.59.32.49:17472       0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:17473         0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN     
tcp6       0      0 :::9000                 :::*                    LISTEN     
tcp6       0      0 :::22                   :::*                    LISTEN     
tcp6       0      0 ::1:25                  :::*                    LISTEN     
```

**Comment by harshavardhana** [comment]
> The IPs are the public IPs of the centos servers themselves. The -p switch is exposing the docker container port on the docker host on each server:

That is not enough for MinIO @zieg8301 we need to know if the disk belongs to the host so you need to expose the IP i.e `--net=host`

**Comment by 2qif49lt** [comment]
i have encounter same problem @harshavardhana 
![image](https://user-images.githubusercontent.com/848930/93861441-1a7eee00-fcf3-11ea-927b-3f85a36ebd17.png)
![image](https://user-images.githubusercontent.com/848930/93861457-236fbf80-fcf3-11ea-9b01-2b2e08839028.png)

**Comment by thewholeworld** [comment]
Hi, I changed the IP in the startup command to change the public IP to the private IP. This problem has been solved, but I have encountered a new problem. Regarding the path of file storage, must the attached hard disk be an empty hard disk?

@harshavardhana

**Comment by thewholeworld** [comment]
@2qif49lt Try changing the IP in your configuration to private IP

**Comment by 2qif49lt** [comment]
> @2qif49lt Try changing the IP in your configuration to private IP

 they are private ips already.

**Comment by 2qif49lt** [comment]
i change deployment to statefulset, make sure pod's hostname is same as parameter, and works.

**Comment by harshavardhana** [comment]
> i change deployment to statefulset, make sure pod's hostname is same as parameter, and works.

Statefulset is what we support, you can't construct your own deployment yaml to make it work since k8s networking is not consistent with it's behavior in all deployment styles.

**Comment by harshavardhana** [comment]
> Hi, I changed the IP in the startup command to change the public IP to the private IP. This problem has been solved, but I have encountered a new problem. Regarding the path of file storage, must the attached hard disk be an empty hard disk?
> 
> @harshavardhana 

Yes or you can choose an empty subdirectory

**Comment by harshavardhana** [comment]
> Hi, I changed the IP in the startup command to change the public IP to the private IP. This problem has been solved, but I have encountered a new problem. Regarding the path of file storage, must the attached hard disk be an empty hard disk?
> 
> @harshavardhana 

As per your comment closing this issue.

**Comment by HattabbI4** [comment]
@harshavardhana Hi! 
I my case i'm used all recomendations from this issue but my minio instances is not working: 

```
cat docker-compose.yml
version: '3'

services:
  minio:
    image: minio/minio:RELEASE.2020-09-23T19-18-30Z
    container_name: minio
    volumes:
      - /data/minio/data1:/data1
      - /data/minio/data2:/data2
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: <...>
      MINIO_SECRET_KEY: <...>
    command: server http://10.10.10.1{0...1}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: always
```

log: 

```
Waiting for a minimum of 2 disks to come online (elapsed 51s)

Unable to read 'format.json' from http://10.10.10.10:9000/data1: Expected 'storage' API version 'v20', instead found 'a1', please upgrade the servers

Unable to read 'format.json' from http://10.10.10.11:9000/data1: Expected 'storage' API version 'v20', instead found 'a1', please upgrade the servers

Unable to read 'format.json' from http://10.10.10.10:9000/data2: Expected 'storage' API version 'v20', instead found 'a2', please upgrade the servers

Unable to read 'format.json' from http://10.10.10.11:9000/data2: Expected 'storage' API version 'v20', instead found 'a2', please upgrade the servers
```


curl from minio container return "Server not initialized, please try again."
all nodes available from container 

But when i use this configuration below all works fine

```
version: '3'

services:
  minio1:
    image: minio/minio:RELEASE.2020-09-23T19-18-30Z
    container_name: minio
    volumes:
      - /data/minio/data1:/data1
      - /data/minio/data2:/data2
    expose:
      - "9000"
    environment:
      MINIO_ACCESS_KEY: <...>
      MINIO_SECRET_KEY: <...>
    command: server http://minio{1...2}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: always
  minio2:
    image: minio/minio:RELEASE.2020-09-23T19-18-30Z
    container_name: minio2
    volumes:
      - /data/minio/data3:/data1
      - /data/minio/data4:/data2
    expose:
      - "9000"
    environment:
      MINIO_ACCESS_KEY: <...>
      MINIO_SECRET_KEY: <...>
    command: server http://minio{1...2}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: always

```
