### ISSUE TITLE
[working as intended] Minio with Minikube

### ISSUE THREAD

**Issue by secretlifeof** [minio/minio#10550]
I am trying to install Minio using this [helm chart](https://hub.helm.sh/charts/minio/minio) but I always get this warning

```
Type     Reason            Age              From               Message
  ----     ------            ----             ----               -------
  Warning  FailedScheduling  6s (x2 over 6s)  default-scheduler  0/1 nodes are available: 1 Insufficient memory.
```

The does not get pass status *pending*. Trying to `minikube config set memory 10240` does not remove the error. I have done `minikube delete` and the `minikube start` like described in other issues here.

## Expected Behavior
That Minio gets installed into the clust

## Current Behavior
Status pending

## Possible Solution
I don´t have any

## Steps to Reproduce (for bugs)

1. `minikube config set memory 10240`
2. `minikube start`
3. create PersistentVolumeClaim called **pvc** (10Gi)

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /data/pv0001/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
```

4. `helm install argo-artifacts stable/minio --set fullnameOverride=argo-artifacts  --set persistence.existingClaim=pvc`

## Question
Am I installing Minio wrongly? How much resources does Minio need (10Gb should be enough)?

## Your Environment

* Version used (`minio --version`): 7.0.1 (from Helm chart)
* Server setup and configuration: Minikube v1.13.0
* Operating System and version (`uname -a`): macOS Catalina
