### ISSUE TITLE
Bucket doesn't exist after expanding distributed cluster 

### ISSUE THREAD

**Issue by tobernguyen** [minio/minio#10599]
After expanding the capacity of the distributed cluster by adding a new zone to the cluster, I couldn't write new files to the existing bucket. Got the error
```
mc: <ERROR> Failed to copy `/tmp/tmp.AlACBa`. Bucket `bucket2` does not exist.
```
All nodes are healthy and accepting requests.

## Expected Behavior
I expect everything should work just like before adding a new zone. I should be able to upload/write new files to `bucket2`.

## Current Behavior
The server is not accepting new files, return the following error:
```
mc: <ERROR> Failed to copy `/tmp/tmp.AlACBa`. Bucket `bucket2` does not exist.
```

## Possible Solution
I found a way to fix this. After adding a new zone, I have to run the make bucket command again. Despite receiving the message `mc: <ERROR> Unable to make bucket bucket2. Your previous request to create the named bucket succeeded and you already own it`, that fixes the problem. I can write new files again.

## Steps to Reproduce (for bugs)

1. Deploy the MinIO-operator
2. Deploy a new MinIO Tenant with just one zone of 4 servers, 1 disk each server
  ```yaml
  apiVersion: minio.min.io/v1
  kind: Tenant
  ...
  spec:
    zones:
      - servers: 4
        volumesPerServer: 1
        volumeClaimTemplate:
          metadata:
            name: minio-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 100Gi
  ...
  ```
3. Create a new bucket named `bucket2`
4. Write some files to`bucket2`
5. Modify the CR to add a new zone with exactly same config
  ```yaml
  apiVersion: minio.min.io/v1
  kind: Tenant
  ...
  spec:
    zones:
      - servers: 4
        volumesPerServer: 1
        volumeClaimTemplate:
          metadata:
            name: minio-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 100Gi
      - servers: 4
        volumesPerServer: 1
        volumeClaimTemplate:
          metadata:
            name: minio-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 100Gi
  ...
  ```
6. Wait for the rolling update and all nodes healthy (I have to manually restart the newly created statefulset tho, but that is for another issue)
7. All nodes are healthy
8. Write a new files to `bucket2`, got error:
  ```
  mc: <ERROR> Failed to copy `/tmp/tmp.AlACBa`. Bucket `bucket2` does not exist.
  ```
9. Run `mc mb cluster/bucket2` again.
10. Write a new file to `bucket2` got success.

## Context
- MinIO version: `minio/minio:RELEASE.2020-09-26T03-44-56Z`

## Regression
I don't know

## Your Environment
- AWS
- K8s cluster managed via Kops
