### ISSUE TITLE
GitHub authentification via dex not working

### ISSUE THREAD

**Issue by KairaMiu** [minio/minio#10692]
I don't manage to set up minIO and dex based on any descriptions so that github authentication works successfully.

## Expected Behavior
Successful login to minIO using GitHub authentification via dex.

## Current Behavior
Error message "policy claim missing from the JWT token, credentials will not be generated" is generated and minIO view is opened where it is required to enter the Cliend ID. No login was executed.

## Possible Solution
Remove JWT claim "policy" as madatory for openID authentification (WebIdentity)
or
update documentation, that this does not work (docs/sts/dex.md, docs/sts/README.md)
or 
update the documentation on what needs to be done (docs/sts/dex.md, docs/sts/README.md).

## Steps to Reproduce (for bugs)
1. Install dex and minIO on kubernetes cluster using helm charts(see versions in section "Your Environment")
2. Customize configuration as described in https://github.com/minio/minio/blob/master/docs/sts/dex.md and https://github.com/minio/minio/blob/master/docs/sts/dex.yaml.
3. Configure minIO parameter passed at startup in helm values file:
    ```
    environment:
        MINIO_IDENTITY_OPENID_CLIENT_ID: "minio"
        MINIO_IDENTITY_OPENID_CLIENT_SECRET: abcd
        MINIO_IDENTITY_OPENID_CONFIG_URL: "http://dex.url/.well-known/openid-configuration"
        MINIO_IDENTITY_OPENID_SCOPES: "groups,openid,email,profile"
    ```

## Context
I am trying to enable authetification in minIO using GitHub. Only GitHub user, that are part of the organization shall be able to login.

On MinIO container deployed by the helm chart there is no mc installed.

GitHub authentification with dex and provided example application works (https://dexidp.io/docs/getting-started/).

GitHub authentification with keycloak and minIO works, after adding custom JWT claim "policy" with values "readwrite" in keycloak.

Dex does not provide custom claims (https://github.com/dexidp/dex/issues/1182).

## Regression
No

## Your Environment
* Version used (`minio --version`): minio version RELEASE.2020-09-26T03-44-56Z
* Operating System and version (`uname -a`): Linux minio-7b8594d44-mtljt 5.7.19-050719-generic #202008270830 SMP Thu Aug 27 08:35:40 UTC 2020 x86_64 Linux (container in kubernetes cluster)
* Dex Version used (`dex version`): 
    ```
    dex Version: v2.24.0
    Go Version: go1.13.10
    Go OS/ARCH: linux amd64
    ```
* Server setup and configuration:
    * Ubuntu 20.04 with k3s installed.
    * Deployed dex and minio via helm chart to kubernetes cluster:
        * minIO 
            * version 7.1.2
            * repository https://helm.min.io/
        * dex
            * version 2.14.0
            * repository https://kubernetes-charts.storage.googleapis.com
