### ISSUE TITLE
[fixed] Modify `Dockerfile` to be used as a service with github workflow

### ISSUE THREAD

**Issue by galaxie** [minio/minio#10745]
**Is your feature request related to a problem? Please describe.**
I want to use [Minio form Dockerhub](https://hub.docker.com/r/minio/minio) as a service in Github Workflows, but Github services don't support `command` option, so having a basic config like the following

```
jobs:
  services:
    minio:
      image: minio/minio
      env:
        MINIO_ACCESS_KEY: access_key
        MINIO_SECRET_KEY: secret_key
      ports:
        - 9000:9000
```
the container exits right after the start. It invokes `CMD ["minio"]` and then exits with `Usage` page.

**Describe the solution you'd like**
I would like the `Dockerfile` to be either fully configurable via `ENV` or have a default command which would allow me to start the server.

**Describe alternatives you've considered**
I tried to play around with Workflow having something `options: --entrypoint 'sh -c '/usr/bin/minio server /data'`, but they seem either not supported or I am doing something wrong.
The only solution that have available is a custom image on top of Minio which would have  `server /data` as a command.

**Additional context**
If there is a ready to use workaround, I would really appreciate if someone tells me.
