### ISSUE TITLE
docker swarm deployment does not work - Unable to read 'format.json' from http://miniotest_minio2:9000/export1: Not allowed (POST /minio/storage/export1/v22/readall?disk-id=&file-path=format.json&volume=.minio.sys on S3 API)

### ISSUE THREAD

**Issue by kolbma** [minio/minio#10861]
## Expected Behavior
I follow your description at https://docs.min.io/docs/deploy-minio-on-docker-swarm.html to deploy to a docker swarm.  
**minio** should start as described but it **doesn't**...

## Steps to Reproduce (for bugs)

1. I've modified the yml file from [here](https://raw.githubusercontent.com/minio/minio/master/docs/orchestration/docker-swarm/docker-compose-secrets.yaml) for my **2 nodes** and using **each 2 volumes**.  
The server commands need also an update because the docker container dns lookup is only successful with ${stackname}_${servicename}.  
I've also **removed the healthcheck**, because the **dns lookup seems to hang** until the system does a successful health check. But the healthcheck works only with a running server and the working dns lookup. So chicken&egg problem. At least with my docker version 19.03.8.  
After the healthcheck is removed, the dns lookup works.

```yml
version: '3.7'

services:
  minio1:
    image: minio/minio:RELEASE.2020-11-06T23-17-07Z
    hostname: minio1
    volumes:
      - minio1-1-data:/export1
      - minio1-2-data:/export2
    ports:
      - "9001:9000"
    networks:
      - minio_distributed
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:
        constraints:
          - node.labels.minio1==true
    command: server http://miniotest_minio{1...2}/export{1...2}
    secrets:
      - secret_key
      - access_key

  minio2:
    image: minio/minio:RELEASE.2020-11-06T23-17-07Z
    hostname: minio2
    volumes:
      - minio2-1-data:/export1
      - minio2-2-data:/export2
    ports:
      - "9002:9000"
    networks:
      - minio_distributed
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:
        constraints:
          - node.labels.minio2==true
    command: server http://miniotest_minio{1...2}/export{1...2}
    secrets:
      - secret_key
      - access_key

volumes:
  minio1-1-data:
  minio1-2-data:
  minio2-1-data:
  minio2-2-data:

networks:
  minio_distributed:
    driver: overlay

secrets:
  secret_key:
    external: true
  access_key:
    external: true
```
2. update the 2 nodes with the contraint labels
3. add the secrets (which are identical in the 2 containers)
```
# hostname ; cat /run/secrets/*
minio1
AYiud5yaiphoaDu4ooXoeXaH
vaiZiXeGhohshai4Xe2IeWaeTuareiw8

# hostname ; cat /run/secrets/*
minio2
AYiud5yaiphoaDu4ooXoeXaH
vaiZiXeGhohshai4Xe2IeWaeTuareiw8
```
3. `docker stack deploy -c docker-stack.yml miniotest`
4. Check container logs for successful startup
5. My logs are full with...
```
Waiting for a minimum of 2 disks to come online (elapsed 2s)

Unable to read 'format.json' from http://miniotest_minio1:9000/export1: Not allowed (POST /minio/storage/export1/v22/readall?disk-id=&file-path=format.json&volume=.minio.sys on S3 API)

Unable to read 'format.json' from http://miniotest_minio2:9000/export1: Not allowed (POST /minio/storage/export1/v22/readall?disk-id=&file-path=format.json&volume=.minio.sys on S3 API)

Unable to read 'format.json' from http://miniotest_minio1:9000/export2: Not allowed (POST /minio/storage/export2/v22/readall?disk-id=&file-path=format.json&volume=.minio.sys on S3 API)

Unable to read 'format.json' from http://miniotest_minio2:9000/export2: Not allowed (POST /minio/storage/export2/v22/readall?disk-id=&file-path=format.json&volume=.minio.sys on S3 API)

Waiting for a minimum of 2 disks to come online (elapsed 3s)
```

## Your Environment

* Version used (`minio --version`): Your docker image minio/minio:RELEASE.2020-11-06T23-17-07Z
* Operating System and version (`uname -a`):
```
# uname -a
Linux cloud01 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
```
