### ISSUE TITLE
SSL Protocol error using javascript api

### ISSUE THREAD

**Issue by rosariop** [minio/minio#10899]
Using Min.io docker container, logging in via web-gui and creating a bucket works just fine.
Fetching a listing of buckets via JavaScript API does not.

## Expected Behavior

I expect to return me a list of buckets created in the min.io s3

## Current Behavior

Returning me `net::ERR_SSL_PROTOCOL_ERROR` in chromium, `Cross-Origin blocked` in firefox.

## Steps to Reproduce (for bugs)

`const Minio = require('minio');

// Instantiate the minio client with the endpoint
// and access keys as shown below.
```js
const minioClient = new Minio.Client({
  endPoint: 'localhost',
  port: 9000,
  useSSL: true,
  accessKey: 'minioaccess',
  secretKey: 'miniossecret',
});


const bucket = {
  async uploadFile() {
    try {
      const bucketList = await minioClient.listBuckets();
      console.warn(bucketList);
    } catch (error) {
      console.error(error);
    }
  },
};

export default bucket;
```

## Context

Trying to interact with the JavaScript API to fetch files later.

## Your Environment

Using docker-compose to pull up minios
```yml
s3minio:
    image: minio/minio
    ports:
      - "9000:9000"
    volumes:
      - "./somefolder:/export"
    environment:
      - "MINIO_ACCESS_KEY=minioaccess"
      - "MINIO_SECRET_KEY=miniossecret"
    command: server /export
```
OS: Ubuntu 20.04
Not using SSL / Https on my local development machine.

Any Idea if this is a bug in my app and if so, how to fix?
Right know it's executing the `uploadFile()` method on a button click.
