### ISSUE TITLE
Unable to upload png exported from Photoshop

### ISSUE THREAD

**Issue by zhizzzzzz** [minio/minio#10932]
Unable to upload png exported from Photoshop
The picture is as follows:
![test](https://user-images.githubusercontent.com/20277316/99617438-54057880-2a5a-11eb-9bc7-90d0620d3690.png)

## Expected Behavior
success upload the png

## Current Behavior
Upload progress bar stopped at 100
![image](https://user-images.githubusercontent.com/20277316/99616578-7f876380-2a58-11eb-9953-a280beeda9c0.png)
![image](https://user-images.githubusercontent.com/20277316/99616687-9f1e8c00-2a58-11eb-8199-d5bdd87f06fa.png)

## Steps to Reproduce (for bugs)
1. run docker-compose.yml
```
version: '3.0'
services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "8080:9000"
    restart: always
    command: server /data
    environment:
      MINIO_ACCESS_KEY: xxx
      MINIO_SECRET_KEY: xxx
    logging:
      options:
        max-size: "50M" 
        max-file: "10"
      driver: json-file
    volumes:
      - /data/volume/minio/data:/data
```
2.execute the following commands from a bash or compatible terminal in the folder
```
 docker-compose up -d 
```
## Context

This prevents me from using the storage function normally

## Your Environment

* Version used (`minio --version`): 2020-11-13T20:10:18Z
* Operating System and version (`uname -a`):  Linux master 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
