### ISSUE TITLE
[fixed] Allow disabling list cache

### ISSUE THREAD

**Issue by josiasmontag** [minio/minio#10942]
**Is your feature request related to a problem? Please describe.**
Thanks for fixing #10873. The latest version solves the slow listing issue for me.

However, I noticed that the general load on my cluster got much higher since the list caching feature. With release `2020-11-10` my servers had an average load of ~2-4. With newer versions, my servers have a load of 10-40. The higher load is coming from increased disk access. 

I think this is happening because I do have a lot of `PutObject` requests. As far as I understand, each write operation invalidates the list cache and MinIO tries to build a new cache. In my special case this is rather contra productive because ~30% of my requests create new objects. 

I do understand that my use case might not be typical. However, such a setting would also allow easier debugging for similar issues.

**Describe the solution you'd like**
Adding a setting `MINIO_API_DISABLE_LIST_CACHE` which completely disables generating the cache.

**Additional context**
See #10873.

**Comment by harshavardhana** [comment]
> Adding a setting `MINIO_API_DISABLE_LIST_CACHE` which completely disables generating the cache.

I don't think this is feasible to do we cannot go back to the older approach and have multiple paths for similar functionality.

> However, I noticed that the general load on my cluster got much higher since the list caching feature. With release `2020-11-10` my servers had an average load of ~2-4. With newer versions, my servers have a load of 10-40. The higher load is coming from increased disk access.

This also doesn't seem right unless your application is super convoluted in design i.e it does PUT and then List and then PUT and then List. Also if the disk is capable of handling the load why should you be worried? are you saying that you are losing on IOPS on the drives? i.e you can't do the same level of PUTs as before? 

> I think this is happening because I do have a lot of `PutObject` requests. As far as I understand, each write operation invalidates the list cache and MinIO tries to build a new cache. In my special case this is rather contra productive because ~30% of my requests create new objects.

yeah but it's not as simple as this, can you provide a sample code to provide a more convincing argument on the load? - just having a higher load on the servers is fine as long as the application does its job in the expected time frame.  Unless you are losing IOPS and the application becomes slower.  I don't think there is a good argument on why list caching should be disabled.

**Comment by josiasmontag** [comment]
> I don't think this is feasible to do we cannot go back to the older approach and have multiple paths for similar functionality.

Ok, let be more specific here. My understanding is that the list cache works like this (simplified):

Listing with prefix: 
1. Dirty bloom filter: List request is sent to lister **with** prefix and just caching the current prefix.
2. Clean bloom filter: List request is sent to lister **without** prefix and doing a recursive scan to build a larger cache.

2 causes issues in my scenario. The expensive recursive list scan results in high disc IO and the cache gets invalidated a few seconds later because new files are added or others are deleted.

More technical, I just would like to have an option to disable this bloom filter check and always send the prefix to the lister: https://github.com/klauspost/minio/blob/4609d8d1ce3b089eeee792cd80b4a86e60de0b06/cmd/metacache-set.go#L292

Maybe a better name would be `MINIO_DISABLE_EAGER_LIST_CACHE`.

> This also doesn't seem right unless your application is super convoluted in design i.e it does PUT and then List and then PUT and then List.

Exactly this is happening in my scenario. I do have a distributed application which does the following:

1. Server 1 uploads one or multiple files to a prefix
2. Server 2 scans this prefix
3. Server 2 downloads the files
4. Server 2 deletes the files in this prefix


> Also if the disk is capable of handling the load why should you be worried? are you saying that you are losing on IOPS on the drives? i.e you can't do the same level of PUTs as before?

Besides the increased load we are getting regular `SlowDown` error responses. We had to roll back to `2020-10-28` which solves this. With `iostat` I can see that the disc utilization is at ~70-100% where it was ~30% before.

**Comment by klauspost** [comment]
@josiasmontag In your description the bloom filter will be dirty as soon as Server 1 uploads the files.

You can add an ending slash on the prefix to the listobjects. So if objects are uploaded as `prefix/somepath/object01.bin`, etc, you can list `prefix/something/` to get a separate listing.

That will be faster in all cases since the `prefix` folder will never need to be scanned.

Disabling the bloom filter check will make the cache mostly useless.

**Comment by josiasmontag** [comment]
> You can add an ending slash on the prefix to the listobjects.

All list operations are already with ending `/` prefix and with `/` delimiter.

> Disabling the bloom filter check will make the cache mostly useless.

So thats exactly what I want. I do understand that the cache makes sense in a lot of cases but in my specific scenario it does more harm than good. Besides that, such a setting allows better debugging of slow list requests and load issues.

**Comment by klauspost** [comment]
@josiasmontag 

> All list operations are already with ending `/` prefix and with `/` delimiter.

Then disabling the cache will not make any difference. The list cache is simply built as a sideeffect of the listing which was already going on.

> Besides that, such a setting allows better debugging of slow list requests and load issue

We don't want to add more options just for the sake of adding them. That creates more potential failure scenarios and generally is just confusing.

We can through your server setup to identify the actual bottleneck. Right now it seems to be more guessing.  See our options at https://min.io/pricing

You can experiment with the existing `MINIO_API_LIST_QUORUM` option. By default 3 disks will be asked for lists. Setting it to `reduced` will ask 2, `disk` will ask one.

**Comment by tazimmerman** [comment]
Apologies in advance if I'm hijacking this with an unrelated issue, but I believe the list caching is negatively impacting me as well (hopefully I am wrong!). I was on **RELEASE.2020-12-03T05-49-24Z**, and bisected my way to **RELEASE.2020-10-28T08-16-50Z**, with that being the most recent version that still works for me.

My data layout is pretty simple. I have tasks that write daily files historically, in a "directory structure" like this:

```
bucket/path/to/output/2007-01-01/file.parquet
bucket/path/to/output/2007-01-02/file.parquet
bucket/path/to/output/2007-01-03/file.parquet
...
bucket/path/to/output/2020-12-03/file.parquet
```

When I upgrade, I am consistently only seeing files from **2007-01-01** to **2010-03-11**. I've tried a variety of things.

1) Running standalone instances vs. a replicated cluster
2) Writing plain text files (such as JSON) instead of Parquet tables
3) Changing the date range, which results in equally strange behavior: if I generate data for **2015-01-01** to **2018-12-31**, I'll only see files through **2018-03-12**, as if I'm reaching some fixed cutoff
4) Performing my basic tests on versions from ~6 months ago through this week

I also use Apache Arrow heavily, which integrates very well with S3 and thus MinIO (until today it's been a flawless duo), but it relies on list operations for it's dataset API. The data API is such that if you have a collection of daily files, a datasets give you a logical view as of it's a single timeseries, even if it's hundreds or thousands of physical files in S3. The version that introduces the list caching results in the dataset only thinking it has ~3 years of data.

I've also observed the MinIO UI exhibits the same behavior of thinking only a subset of files are in my bucket, while `mc ls` displays all files.

I'm happy to delete this an open a separate issue if you'd prefer. I'd also like to say that, while the upgrade has obviously been a bit challenging, overall I'm extremely impressed with MinIO and its capabilities.

**Comment by harshavardhana** [comment]
@tazimmerman this doesn't look like the issue being described here and also doesn't look like something we have seen.

**Comment by tazimmerman** [comment]
@harshavardhana Thank you for the quick reply. I'll put together a reproducible example with as few moving parts as possible, and open a separate issue (assuming it persists).

**Comment by josiasmontag** [comment]
> Then disabling the cache will not make any difference.

Good to know, thanks for the explanation.

With the current version `2020-12-03` we do have the issue that list requests are constantly taking 5s.

```
19:41:38.294 [200 OK] s3.ListObjectsV1 storage/tasks?prefix=bcf05550-24fd-4cdb-8f68-6e08f5c32e62%2F  xx.xx.xx.xx     5.016528s    ↑ 121 B ↓ 962 B
19:41:38.296 [200 OK] s3.ListObjectsV1 storage/tasks?prefix=d72d1590-e41d-4492-a264-e84b05e826fd%2F  xx.xx.xx.xx     5.014304s    ↑ 155 B ↓ 926 B
19:41:38.299 [200 OK] s3.ListObjectsV1 storage/tasks?prefix=d72d1590-e41d-4492-a264-e84b05e826fd%2F  xx.xx.xx.xx     5.016388s    ↑ 121 B ↓ 962 B
19:41:38.301 [200 OK] s3.ListObjectsV1 storage/tasks?prefix=389a4429-9787-447d-a992-22f43ccc75f9%2F  xx.xx.xx.xx     5.012181s    ↑ 155 B ↓ 926 B
19:41:38.305 [200 OK] s3.ListObjectsV1 storage/tasks?prefix=f93757b5-b11b-457d-91bb-d87e62504967%2F  xx.xx.xx.xx     5.009779s    ↑ 155 B ↓ 926 B
19:41:38.298 [200 OK] s3.ListObjectsV1 storage/tasks?prefix=389a4429-9787-447d-a992-22f43ccc75f9%2F  xx.xx.xx.xx     5.01518s     ↑ 121 B ↓ 962 B
19:41:38.303 [200 OK] s3.ListObjectsV1 storage/tasks?prefix=f93757b5-b11b-457d-91bb-d87e62504967%2F  xx.xx.xx.xx     5.012284s    ↑ 121 B ↓ 962 B
19:41:38.302 [200 OK] s3.ListObjectsV1 storage/tasks?prefix=bf68dea0-85d9-4b61-b72b-8decd190c4e2%2F  xx.xx.xx.xx     5.015936s    ↑ 155 B ↓ 926 B
19:41:38.307 [200 OK] s3.ListObjectsV1 storage/tasks?prefix=fe8e3f49-092f-4da8-89c8-9b7b1a368d1e%2F  xx.xx.xx.xx     5.011574s    ↑ 155 B ↓ 926 B
19:41:38.302 [200 OK] s3.ListObjectsV1 storage/tasks?prefix=a8f71ead-6977-43f7-b7d3-98f04f9b9428%2F  xx.xx.xx.xx     5.016179s    ↑ 155 B ↓ 926 B
19:41:38.304 [200 OK] s3.ListObjectsV1 storage/tasks?prefix=2641e607-ccd7-4196-b92e-96e6f6657d31%2F  xx.xx.xx.xx     5.016528s    ↑ 155 B ↓ 926 B
19:41:38.299 [200 OK] s3.ListObjectsV1 storage/tasks?prefix=bf68dea0-85d9-4b61-b72b-8decd190c4e2%2F  xx.xx.xx.xx     5.018989s    ↑ 121 B ↓ 962 B
19:41:38.305 [200 OK] s3.ListObjectsV1 storage/tasks?prefix=fe8e3f49-092f-4da8-89c8-9b7b1a368d1e%2F  xx.xx.xx.xx     5.013002s    ↑ 121 B ↓ 962 B
19:41:38.300 [200 OK] s3.ListObjectsV1 storage/tasks?prefix=a8f71ead-6977-43f7-b7d3-98f04f9b9428%2F  xx.xx.xx.xx     5.018703s    ↑ 121 B ↓ 962 B
19:41:38.301 [200 OK] s3.ListObjectsV1 storage/tasks?prefix=2641e607-ccd7-4196-b92e-96e6f6657d31%2F  xx.xx.xx.xx     5.019238s    ↑ 121 B ↓ 962 B
19:41:39.116 [200 OK] s3.ListObjectsV1 storage/tasks?prefix=1b7deba1-458c-4159-a217-5c962ba00680%2F  xx.xx.xx.xx     5.01045s     ↑ 121 B ↓ 907 B
19:41:39.344 [200 OK] s3.ListObjectsV1 storage/tasks?prefix=ca3f6d81-65ae-45b2-97c5-02a8dff0b51b%2F  xx.xx.xx.xx    5.008961s    ↑ 155 B ↓ 902 B
19:41:39.349 [200 OK] s3.ListObjectsV1 storage/tasks?prefix=ca3f6d81-65ae-45b2-97c5-02a8dff0b51b%2F  xx.xx.xx.xx     5.010646s    ↑ 121 B ↓ 938 B
```

It seems that [this](https://github.com/minio/minio/blob/master/cmd/metacache-server-sets.go#L109) context timeout is kicking in. In the logs I see:

```
minio_stack_minio3.1.loxgu4maz7b7@storage3    | API: ListObjectsV1(bucket=tasks)
minio_stack_minio3.1.loxgu4maz7b7@storage3    | Time: 19:45:45 UTC 12/08/2020
minio_stack_minio3.1.loxgu4maz7b7@storage3    | DeploymentID: cce14fb7-4c6d-4310-8a7f-b1d088fa752b
minio_stack_minio3.1.loxgu4maz7b7@storage3    | RequestID: 164ED56394939020
minio_stack_minio3.1.loxgu4maz7b7@storage3    | RemoteHost: xx.xx.xx.xx
minio_stack_minio3.1.loxgu4maz7b7@storage3    | Host: minio3:9000
minio_stack_minio3.1.loxgu4maz7b7@storage3    | UserAgent: nodejs-pkgcloud/1.7.0 aws-sdk-nodejs/2.493.0 linux/v10.21.0 callback
minio_stack_minio3.1.loxgu4maz7b7@storage3    | Error: Marking http://minio6:9000/minio/peer/v11 temporary offline; caused by Post "http://minio6:9000/minio/peer/v11/getmetacache?": context deadline exceeded (*fmt.wrapError)
minio_stack_minio3.1.loxgu4maz7b7@storage3    |        9: cmd/rest/client.go:122:rest.(*Client).Call()
minio_stack_minio3.1.loxgu4maz7b7@storage3    |        8: cmd/peer-rest-client.go:68:cmd.(*peerRESTClient).callWithContext()
minio_stack_minio3.1.loxgu4maz7b7@storage3    |        7: cmd/peer-rest-client.go:655:cmd.(*peerRESTClient).GetMetacacheListing()
minio_stack_minio3.1.loxgu4maz7b7@storage3    |        6: cmd/metacache-server-sets.go:111:cmd.(*erasureServerPools).listPath()
minio_stack_minio3.1.loxgu4maz7b7@storage3    |        5: cmd/erasure-server-sets.go:728:cmd.(*erasureServerPools).ListObjects()
minio_stack_minio3.1.loxgu4maz7b7@storage3    |        4: cmd/bucket-listobjects-handlers.go:360:cmd.objectAPIHandlers.ListObjectsV1Handler()
minio_stack_minio3.1.loxgu4maz7b7@storage3    |        3: cmd/http-tracer.go:204:cmd.Trace()
minio_stack_minio3.1.loxgu4maz7b7@storage3    |        2: cmd/handler-utils.go:356:cmd.httpTraceAll.func1()
minio_stack_minio3.1.loxgu4maz7b7@storage3    |        1: net/http/server.go:2042:http.HandlerFunc.ServeHTTP()
minio_stack_minio3.1.loxgu4maz7b7@storage3    | 
minio_stack_minio3.1.loxgu4maz7b7@storage3    | API: ListObjectsV1(bucket=tasks)
minio_stack_minio3.1.loxgu4maz7b7@storage3    | Time: 19:45:45 UTC 12/08/2020
minio_stack_minio3.1.loxgu4maz7b7@storage3    | DeploymentID: cce14fb7-4c6d-4310-8a7f-b1d088fa752b
minio_stack_minio3.1.loxgu4maz7b7@storage3    | RequestID: 164ED56394939020
minio_stack_minio3.1.loxgu4maz7b7@storage3    | RemoteHost: xx.xx.xx.xx
minio_stack_minio3.1.loxgu4maz7b7@storage3    | Host: minio3:9000
minio_stack_minio3.1.loxgu4maz7b7@storage3    | UserAgent: nodejs-pkgcloud/1.7.0 aws-sdk-nodejs/2.493.0 linux/v10.21.0 callback
minio_stack_minio3.1.loxgu4maz7b7@storage3    | Error: Post "http://minio6:9000/minio/peer/v11/getmetacache?": context deadline exceeded (*rest.NetworkError)
minio_stack_minio3.1.loxgu4maz7b7@storage3    |        7: cmd/peer-rest-client.go:657:cmd.(*peerRESTClient).GetMetacacheListing()
minio_stack_minio3.1.loxgu4maz7b7@storage3    |        6: cmd/metacache-server-sets.go:111:cmd.(*erasureServerPools).listPath()
minio_stack_minio3.1.loxgu4maz7b7@storage3    |        5: cmd/erasure-server-sets.go:728:cmd.(*erasureServerPools).ListObjects()
minio_stack_minio3.1.loxgu4maz7b7@storage3    |        4: cmd/bucket-listobjects-handlers.go:360:cmd.objectAPIHandlers.ListObjectsV1Handler()
minio_stack_minio3.1.loxgu4maz7b7@storage3    |        3: cmd/http-tracer.go:204:cmd.Trace()
minio_stack_minio3.1.loxgu4maz7b7@storage3    |        2: cmd/handler-utils.go:356:cmd.httpTraceAll.func1()
minio_stack_minio3.1.loxgu4maz7b7@storage3    |        1: net/http/server.go:2042:http.HandlerFunc.ServeHTTP()
minio_stack_minio3.1.loxgu4maz7b7@storage3    | Client http://minio6:9000/minio/peer/v11 online
```

`minio6`  has no other issues and no errors in the logs. It is just the `/minio/peer/v11/getmetacache` calls that are timing out, other requests are working fine. 

I have also tried to:
1. Setup a fresh 8-node cluster
2. Fill cluster with 50.000 objects
3. The 5s issue starts to happen after some time

I will try to write a simple script and Docker compose file for reproduction.

**Comment by harshavardhana** [comment]
This looks like you are hitting some form of disk slowness here which affects our metadata cache reads, either that your network is perhaps not able to handle the traffic.

```
                        ctx, cancel := context.WithTimeout(ctx, 5*time.Second)
                        defer cancel()
                        c, err := rpc.GetMetacacheListing(ctx, o)
                        if err != nil {
                                if errors.Is(err, context.Canceled) {
                                        // Context is canceled, return at once.
                                        // request canceled, no entries to return
                                        return entries, io.EOF
                                }
                                if !errors.Is(err, context.DeadlineExceeded) {
                                        logger.LogIf(ctx, err)
                                }
                                o.Transient = true
                                cache = localMetacacheMgr.findCache(ctx, o)
                        } else {
                                cache = *c
                        }
```

> minio_stack_minio3.1.loxgu4maz7b7@storage3    | Error: Marking http://minio6:9000/minio/peer/v11 temporary offline; caused by Post "http://minio6:9000/minio/peer/v11/getmetacache?": context deadline exceeded (*fmt.wrapError)

This doesn't look correct in an actual sense here.

**Comment by josiasmontag** [comment]
This also happens in a local Docker environment, Reproducer:

<details>
  <summary>docker-compose.yml</summary>
  

  ```yml
version: '3.7'

services:

  minio1:
    image: minio/minio:RELEASE.2020-12-03T05-49-24Z
    hostname: minio1
    volumes:
      - export1-1:/export1
      - export1-2:/export2
      - export1-3:/export3
      - export1-4:/export4
    ports:
      - { published: 9001, target: 9000, mode: host }
    networks:
      - minio_distributed
    deploy:
      update_config:
        order: stop-first
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
    command: server http://minio{1...8}/export{1...2}
    secrets:
      - secret_key
      - access_key


  minio2:
    image: minio/minio:RELEASE.2020-12-03T05-49-24Z
    hostname: minio2
    volumes:
      - export2-1:/export1
      - export2-2:/export2
      - export2-3:/export3
      - export2-4:/export4
    ports:
      - { published: 9002, target: 9000, mode: host }
    networks:
      - minio_distributed
    deploy:
      update_config:
        order: stop-first
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
    command: server http://minio{1...8}/export{1...2}
    secrets:
      - secret_key
      - access_key



  minio3:
    image: minio/minio:RELEASE.2020-12-03T05-49-24Z
    hostname: minio3
    volumes:
      - export3-1:/export1
      - export3-2:/export2
      - export3-3:/export3
      - export3-4:/export4
    ports:
      - { published: 9003, target: 9000, mode: host }
    networks:
      - minio_distributed
    deploy:
      update_config:
        order: stop-first
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
    command: server http://minio{1...8}/export{1...2}
    secrets:
      - secret_key
      - access_key




  minio4:
    image: minio/minio:RELEASE.2020-12-03T05-49-24Z
    hostname: minio4
    volumes:
      - export4-1:/export1
      - export4-2:/export2
      - export4-3:/export3
      - export4-4:/export4
    ports:
      - { published: 9004, target: 9000, mode: host }
    networks:
      - minio_distributed
    deploy:
      update_config:
        order: stop-first
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
    command: server http://minio{1...8}/export{1...2}
    secrets:
      - secret_key
      - access_key


  minio5:
    image: minio/minio:RELEASE.2020-12-03T05-49-24Z
    hostname: minio5
    volumes:
      - export5-1:/export1
      - export5-2:/export2
      - export5-3:/export3
      - export5-4:/export4
    ports:
      - { published: 9005, target: 9000, mode: host }
    networks:
      - minio_distributed
    deploy:
      update_config:
        order: stop-first
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
    command: server http://minio{1...8}/export{1...2}
    secrets:
      - secret_key
      - access_key



  minio6:
    image: minio/minio:RELEASE.2020-12-03T05-49-24Z
    hostname: minio6
    volumes:
      - export6-1:/export1
      - export6-2:/export2
      - export6-3:/export3
      - export6-4:/export4
    ports:
      - { published: 9006, target: 9000, mode: host }
    networks:
      - minio_distributed
    deploy:
      update_config:
        order: stop-first
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
    command: server http://minio{1...8}/export{1...2}
    secrets:
      - secret_key
      - access_key




  minio7:
    image: minio/minio:RELEASE.2020-12-03T05-49-24Z
    hostname: minio7
    volumes:
      - export7-1:/export1
      - export7-2:/export2
      - export7-3:/export3
      - export7-4:/export4
    ports:
      - { published: 9007, target: 9000, mode: host }
    networks:
      - minio_distributed
    deploy:
      update_config:
        order: stop-first
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
    command: server http://minio{1...8}/export{1...2}
    secrets:
      - secret_key
      - access_key




  minio8:
    image: minio/minio:RELEASE.2020-12-03T05-49-24Z
    hostname: minio8
    volumes:
      - export8-1:/export1
      - export8-2:/export2
      - export8-3:/export3
      - export8-4:/export4
    ports:
      - { published: 9008, target: 9000, mode: host }
    networks:
      - minio_distributed
    deploy:
      update_config:
        order: stop-first
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
    command: server http://minio{1...8}/export{1...2}
    secrets:
      - secret_key
      - access_key



volumes:
  export1-1:
  export1-2:
  export1-3:
  export1-4:
  export2-1:
  export2-2:
  export2-3:
  export2-4:
  export3-1:
  export3-2:
  export3-3:
  export3-4:
  export4-1:
  export4-2:
  export4-3:
  export4-4:
  export5-1:
  export5-2:
  export5-3:
  export5-4:
  export6-1:
  export6-2:
  export6-3:
  export6-4:
  export7-1:
  export7-2:
  export7-3:
  export7-4:
  export8-1:
  export8-2:
  export8-3:
  export8-4:

networks:
  minio_distributed:
    driver: overlay

secrets:
  secret_key:
    external: true
  access_key:
    external: true


  ```
  
</details>


`docker stack deploy --compose-file=docker-compose.yml minio_stack`

`mc alias set minio http://localhost:9001` 

The script creates and lists 10.000 prefixes:

<details>
  <summary>stresstest.sh</summary>

```sh
echo "test" > test.txt
mc mb minio/stresstest

for x in {1..1000} 
do
	for i in {0..9} 
	do
		(
			echo "prefix /$x$i/"
			mc cp test.txt "minio/stresstest/$x$i/test.txt"
			mc ls "minio/stresstest/x$x$i/"
		) &
	done
	wait
done

rm test.txt
```
</details>


`./stresstest.sh` and parallel `mc admin trace minio | grep ListObject` shows the issue.

At the beginning speed is as expected. Starting from prefix ~6000 listing gets slow.
