### ISSUE TITLE
Azure gateway mode: PUT operation is not atomic

### ISSUE THREAD

**Issue by ig-sinicyn** [minio/minio#11008]
1. Docker-compose:
```
  minio-azure:
    image: minio/minio:RELEASE.2020-10-28T08-16-50Z
    container_name: minio-azure
    ports:
      - ${MINIO_AZURE_PORT}:9000
    environment:
      MINIO_ACCESS_KEY: ${MINIO_AZURE_CLIENT_ID}
      MINIO_SECRET_KEY: ${MINIO_AZURE_CLIENT_SECRET}
    command: gateway azure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_TIMEOUT}
      retries: ${HEALTHCHECK_RETRIES}
```
2 Code (c#, official minio client): [Minio.Issues.zip](https://github.com/minio/minio/files/5622776/Minio.Issues.zip)

The code checks if the reader can get content of partially updated file.

How it works: there are two threads.
First one replaces file content with one of three samples (number of sample is stored as a first byte). 
```cs
			while (!cancellation.IsCancellationRequested)
			{
				var data = _samples[rnd.Next(0, _samples.Length - 1)];
				await _client.PutObjectAsync(
					BucketName,
					_fileName,
					new MemoryStream(data),
					data.Length,
					cancellationToken: cancellation);
			}
```
Second reads file content and checks if the sample is valid
```cs
			while (!cancellation.IsCancellationRequested)
			{
				var ms = new MemoryStream();
				await _client.GetObjectAsync(
					BucketName,
					_fileName,
					s => s.CopyTo(ms),
					cancellationToken: cancellation);
				var data = ms.ToArray();

				var expectedIndex = data[0];

				var expectedSample = _samples[expectedIndex];
				var diffIndex = CompareAndGetDiffIndex(expectedSample, data);
				if (diffIndex >= 0)
				{
					Console.WriteLine($"Bad data at {diffIndex}. Expected len: {expectedSample.Length}. Actual: {data.Length}");
					readErrorCount++;
					continue;
				}
			}
```

## Expected Behavior
Sample code does not fail on both normal minio and minio in azure gateway mode

## Current Behavior
Normal minio server works fine. On azure gateway mino there's 100-200 errors per 3000 file updates

## Context
We are not able to use the minio server in production as concurrent reads and updates may result in corrupted user data.

## Your Environment
Checked on windows, docker on win, docker on lin, k8s on lin. 
* Version used (`minio --version`): RELEASE.2020-10-28T08-16-50Z
