### ISSUE TITLE
minio AssumeRole temporary credentials 

### ISSUE THREAD

**Issue by 120011676** [minio/minio#11051]
## Expected Behavior

Get minio AssumeRole temporary credentials

## Current Behavior

![image](https://user-images.githubusercontent.com/1992933/101446067-7bff4200-395d-11eb-8543-644e5c9550a6.png)

## Possible Solution

There is something wrong with my practice, but I don't know where there is a problem. The official document doesn't specify how to do it

## Steps to Reproduce (for bugs)

```yaml
version: '3'
services:
  minio-simple:
    image: minio/minio
    restart: always
    volumes:
      - ./data:/data
      - ./.minio:/root/.minio
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY==[;._PL<0okm
    command: server /data
    ports:
      - 9000:9000
    networks:
      - "dev"
networks:
  dev:
    driver: bridge
```

1.  docker-compose up -d
2. Browser open http://10.4.1.166:9000/?Action=AssumeRole&DurationSeconds=3600&Version=2011-06-15&Policy={%22Version%22:%222012-10-17%22,%22Statement%22:[{%22Sid%22:%22Stmt1%22,%22Effect%22:%22Allow%22,%22Action%22:%22s3:*%22,%22Resource%22:%22arn:aws:s3:::*%22}]}&AUTHPARAMS
3.  error
4. Way? The document didn't make it clear

## Context

no get minio AssumeRole temporary credentials，no JavaScript html page upload

## Regression

VERSION
2020-12-03T05:49:24Z
PLATFORM
Host: 8c07cf30339b | OS: linux | Arch: amd64
RUNTIME
Version: go1.15.5 | CPUs: 8

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):
centos 7
docker
