### ISSUE TITLE
Drupal 7 Minio connection failure and configuration issues

### ISSUE THREAD

**Issue by captsisko** [minio/minio#11146]
Unable to configure Drupal S3FS to successfully connect with Minio.
Drupal 7 and Minio are in seperate docker containers.
I am able to login to Minio using the access and secret keys but the S3F3 configuration form complains **The Access Key in your AWS credentials is invalid.**

I also posted an issue [here](https://drupal.stackexchange.com/questions/298936/s3fs-connection-to-use-minio-as-local-s3-service).

I examined issues such as https://github.com/minio/minio/issues/4914 but I don't understand if that issue is actually solved because a network definition is added to the docker-compose but it is not used in the settings.php code.

## Expected Behavior

I expect the Drupal 7 S3FS form to successfully connect to Minio and save my configuration data.

## Current Behavior

Drupal is unable to connect to Minio and reports **The Access Key in your AWS credentials is invalid.**

## Steps to Reproduce (for bugs)

1. Drupal 7.67
2. S3 File System 7.x-2.13
3. AWSSDK - 2.7.25 - 2015-03-26

## Context

I am unable to to re-create my AWS S3 bucket for testing locally

## Regression

It's not a regression issue

## Your Environment

* Version used (`minio --version`): minio/minio:RELEASE.2020-03-05T01-04-19Z
* Server setup and configuration: 
```
s3:
    container_name: lituk.s3
    image: minio/minio:RELEASE.2020-03-05T01-04-19Z
    restart: always
    ports:
      - 9000:9000
    volumes:
      - ./data:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data
```
* Operating System and version (`uname -a`): Drupal 7 is running on a **php:7.2-apache** container
