### ISSUE TITLE
Unexpected behavior when a node shutdown

### ISSUE THREAD

**Issue by kfirfer** [minio/minio#11140]
Hello,

Im experiencing Unexpected behavior when I shutting down one node ungracefully

Having 3 kubernetes nodes (k8s version 1.18.13), setup with helm chart version 8.0.8 (latest) ,
The NginX load balancer in front of the pods are round robin
This are the overridden helm chart values I deployed with:

```
accessKey: XXXXXXX
secretKey: XXXXXXX

mode: distributed

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - minio-test.tatzan.com
  tls:
    - hosts:
        - "*.tatzan.com"

drivesPerNode: 2
replicas: 3

persistence:
  size: 10Gi

defaultBucket:
  enabled: true
  name: kfir

resources:
  requests:
    memory: 100Mi
    cpu: 100m
  limits:
    memory: 2Gi
    cpu: 4000m

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - minio
        topologyKey: "kubernetes.io/hostname"

tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 30
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 30
```

### Test 1:
I tested with shutdown one node, and start it up again 

And the MinIO browser shows this 1/3 of the times : 

![Selection_005](https://user-images.githubusercontent.com/7741545/101996034-988dd800-3cd7-11eb-9f95-0ccd91ee7093.jpg)

Tooks around 2-4 minutes to come back normally (when the shutdown node is up again)

### Test 2:

I tested another situation when I leave one node down without start it up
Refreshing the MinIO file browser and could see 1/2 of times that files are missing:

![Selection_006](https://user-images.githubusercontent.com/7741545/101996647-db9e7a00-3cdc-11eb-9b39-deb29ce46d21.jpg)

![Selection_007](https://user-images.githubusercontent.com/7741545/101996691-de996a80-3cdc-11eb-87dc-a5d18bcd1d02.jpg)
