### ISSUE TITLE
Cannot concurrently download GCS object not being cached

### ISSUE THREAD

**Issue by hktv-tonyNg** [minio/minio#11206]
I am using minIO to serve gateway for GCS and enable disk cache following below guide
https://github.com/minio/minio/blob/master/docs/disk-caching/DESIGN.md

In our GCS, there are many large object (10GB) can be download via minIO and we use JAVA client method minioClient.getPresignedObjectUrl() to create url for client to download such large file. 

As the file is large and first client take time to complete the download and before the download complete, second client start download the same file and it is blocked that do not start download, finally resulting in stocket timeout.

## Expected Behavior
All client can start download concurrently for GCS object, even the cache not hit

## Current Behavior
Other clients are blocked to download when the not cached object is downloading from first connected client. When the first client complete download and the file is cached, other client can concurrently download without blocking.

## Possible Solution
It is suspected that due to cache creation lock and block other download, suggest to add control that still allow directly download form GCS if cache is not yet ready.

## Steps to Reproduce (for bugs)

1. start with docker using below config
```
version: '2.3'

services:
  minio:
    image: "minio/minio:RELEASE.2020-12-29T23-29-29Z"
    command: gateway gcs {your-project}
    container_name: minio
    environment:
      - MINIO_ACCESS_KEY=minioaccountname
      - MINIO_SECRET_KEY=minioaccountkey
      - MINIO_CACHE=off
      - MINIO_CACHE_AFTER=0
      - MINIO_CACHE_QUOTA=90
      - MINIO_CACHE_WATERMARK_LOW=70
      - MINIO_CACHE_WATERMARK_HIGH=90
      - MINIO_CACHE_DRIVES=/tmp
      - GOOGLE_APPLICATION_CREDENTIALS=/credentials.json
      - MINIO_PROMETHEUS_AUTH_TYPE=public
      - MINIO_CACHE_RANGE=off
    volumes:
      - "{your-gcs-services-account-json}:/credentials.json"
    ports:
      - 9000:9000
```

2. prepare large file in GCS e.g 10GB file
3. login to minIO UI and find the file, select and download 
4. after the first download start, click download same object again and the download is not fired 
5. cancel the first download and second download is fired

## Context
service quality is very low as need wait first client to complete download and others are blocked

## Your Environment
latest release of docker minIO minio/minio:RELEASE.2020-12-29T23-29-29Z
