### ISSUE TITLE
MINIO_API_CORS_ALLOW_ORIGIN environment variable not working on minio docker image

### ISSUE THREAD

**Issue by SylvainBigonneau** [minio/minio#11258]
Whatever I put in the `MINIO_API_CORS_ALLOW_ORIGIN` (as documented [here](https://docs.min.io/docs/minio-server-configuration-guide.html)), I cannot reach my minio server (ran on a docker container on my local machine) from my web app.

## Expected Behavior
Using its docker image, Minio server requests from a web browser should work if the appropriate `MINIO_API_CORS_ALLOW_ORIGIN` environment variable is set on the docker container.

## Current Behavior
Here is the `docker-compose.yml` configuration I am using or the minio image:
```
version: '3.2'

services:
  # ...
  minio:
    image: "minio/minio"
    environment:
      MINIO_ACCESS_KEY: XXXXXX
      MINIO_SECRET_KEY: XXXXXX
      MINIO_API_CORS_ALLOW_ORIGIN: '*'
    ports:
      - "9000:9000"
    command: "server /data"
    network_mode: host
    volumes:
      - "minio_data:/data"
volumes:
  minio_data:
```
Despite what I believe is a correct configuration, here are the responses from PUT requests to minio from my web app:
```
OPTIONS     localhost:9000    CORS Missing Allow Origin
PUT         localhost:9000    NS_ERROR_DOM_BAD_URI
```
I believe this happens because my "Allow Origin *" instruction has not been processed?

## Context
I am trying to recreate an AWS S3 setup on my local machine to match my web app's production infrastructure. It used to work perfectly fine with minio, but somehow now I keep getting those pesky CORS errors! :(

## Regression
Probably not

## Your Environment
* Version used (`minio --version`): RELEASE.2020-12-18T03-27-42Z
* Server setup and configuration: see "Current behavior" for docker-compose setup
* Operating System and version (`uname -a`): Linux xxxxx 5.8.0-36-generic #40-Ubuntu SMP Tue Jan 5 21:54:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
