### ISSUE TITLE
MinIO: Disk not working in docker swarm mode

### ISSUE THREAD

**Issue by prabhant** [minio/minio#11294]
Hi,
My minio standalone deployment works just fine with my setup but I'm having an issue with docker swarm mode deployment
For the manager node I get this error:
In the beginning of docker logs on the manager node, i get :
```
`Disk `/export1` is a root disk. Please ensure the disk is mounted properly, refusing to use  root disk.

```
For all the disks
```
API: SYSTEM()
Time: 06:07:56 UTC 01/18/2021
DeploymentID: 0ee2001b-a23b-44cf-ba3d-13a0c04059e0
Error: Write failed. Insufficient number of disks online (*errors.errorString)
      10: /go/minio/cmd/erasure-encode.go:100:cmd.(*Erasure).Encode()
       9: /go/minio/cmd/erasure-object.go:683:cmd.erasureObjects.putObject()
       8: /go/minio/cmd/erasure-object.go:578:cmd.erasureObjects.PutObject()
       7: /go/minio/cmd/erasure-sets.go:783:cmd.(*erasureSets).PutObject()
       6: /go/minio/cmd/erasure-server-pool.go:560:cmd.(*erasureServerPools).PutObject()
       5: /go/minio/cmd/config-common.go:67:cmd.saveConfig()
       4: /go/minio/cmd/config-encrypted.go:233:cmd.migrateConfigPrefixToEncrypted()
       3: /go/minio/cmd/config-encrypted.go:59:cmd.handleEncryptedConfigBackend()
       2: /go/minio/cmd/server-main.go:292:cmd.initServer()
       1: /go/minio/cmd/server-main.go:500:cmd.serverMain()
Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to migrate all config at .minio.sys/con>
Waiting for all MinIO sub-systems to be initialized.. lock acquired
Attempting encryption of all config, IAM users and policies on MinIO backend
```
On Worker nodes i get:
```
API: SYSTEM()
Time: 06:33:56 UTC 01/18/2021
DeploymentID: 0ee2001b-a23b-44cf-ba3d-13a0c04059e0
Error: Write failed. Insufficient number of disks online (*errors.errorString)
       6: /go/minio/cmd/erasure-encode.go:100:cmd.(*Erasure).Encode()
       5: /go/minio/cmd/erasure-object.go:683:cmd.erasureObjects.putObject()
       4: /go/minio/cmd/erasure-object.go:578:cmd.erasureObjects.PutObject()
       3: /go/minio/cmd/erasure-sets.go:783:cmd.(*erasureSets).PutObject()
       2: /go/minio/cmd/erasure-server-pool.go:560:cmd.(*erasureServerPools).PutObject()
       1: /go/minio/cmd/data-usage.go:54:cmd.storeDataUsageInBackend()
API: SYSTEM()
Time: 06:33:56 UTC 01/18/2021
DeploymentID: 0ee2001b-a23b-44cf-ba3d-13a0c04059e0
Error: Storage resources are insufficient for the write operation .minio.sys/tmp/32ce053a-f47a-4fb1-a81d-a99879d7e9e0/e7646217-f0fb-49e3-9617-6f0c324933a5/part.1 (cmd.InsufficientWriteQuorum)
       1: /go/minio/cmd/data-usage.go:56:cmd.storeDataUsageInBackend()

```
My docker file is here:
```
version: '3.8'
services:
  minio1:
    image: minio/minio:edge
    hostname: minio1
    volumes:
      - minio1-data1:/export1
      - minio1-data2:/export2
      - minio1-data3:/export3
      - minio1-data4:/export4
      - minio1-data5:/export5
      - minio1-data6:/export6
    ports:
      - "9001:9000"
    networks:
      - minio_distributed
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:
        constraints:
          - node.labels.minio1==true
    command: server --address :9000 http://minio1{1...2}/export{1...6}
    secrets:
      - secret_key
      - access_key
  minio2:
    image: minio/minio:edge
    hostname: minio2
    volumes:
      - minio2-data1:/export1
      - minio2-data2:/export2
      - minio2-data3:/export3
      - minio2-data4:/export4
      - minio2-data5:/export5
      - minio2-data6:/export6
    ports:
      - "9002:9000"
    networks:
      - minio_distributed
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:
        constraints:
          - node.labels.minio2==true
    command: server --address :9000 http://minio{1...2}/export{1...6}
    secrets:
      - secret_key
      - access_key
volumes:
  minio1-data1:
  minio1-data2:
  minio1-data3:
  minio1-data4:
  minio1-data5:
  minio1-data6:
  minio2-data1:
  minio2-data2:
  minio2-data3:
  minio2-data4:
  minio2-data5:
  minio2-data6: 
networks:
  minio_distributed:
    driver: overlay
    attachable: true
secrets:
  secret_key:
    external: true
  access_key:
    external: true
```
## Your Environment

* Version used (`minio --version`): minio/edge
* Server setup and configuration: 2 nodes 6 disks
* Operating System and version (`uname -a`): Linux openml1 5.4.0-60-generic
