### ISSUE TITLE
Distributed mode: can not be served by different port on same address

### ISSUE THREAD

**Issue by northway** [minio/minio#11418]
I'm unable to start minio server in distributed mode with 4 nodes. When I start the server I'm getting this error message:

```
ERROR Invalid command line arguments: path '/data1' can not be served by different port on same address
      > Please provide correct combination of local/remote paths
      HINT:
        For more information, please refer to https://docs.min.io/docs/minio-erasure-code-quickstart-guide
```

My goal is to setup a distributed minio across 2 kubernetes cluster.

## Deployment yaml

This is one deployment file, similar would be applied on the other zones and cluster as well.

```yaml
apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: minio-test1
  labels:
    app: minio-test1
spec:
  type: LoadBalancer
  ports:
    - name: minio-test1-lb
      port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: minio-test1

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: dev
  name: minio-test1-pvc1
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: san-ssd-delete-zone2

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: minio-test1
  labels:
    app: minio-test1
spec:
  selector:
    matchLabels:
      app: minio-test1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: minio-test1
    spec:
      nodeSelector:
        topology.cinder.csi.openstack.org/zone: "Zone2"
      restartPolicy: Always
      volumes:
      - name: minio-test1-pv1
        persistentVolumeClaim:
          claimName: minio-test1-pvc1
      - name: minio-test1-tls
        secret:
          secretName: minio-tls
          items:
          - key: private
            path: private.key
          - key: public
            path: public.crt
          - key: public
            path: CAs/public.crt
      containers:
      - name: minio-test1
        imagePullPolicy: Always
        image: minio/minio:RELEASE.2021-02-01T22-56-52Z
        args:
        - server
        - http://test1.s3.mydomain.com/data1
        - http://test2.s3.mydomain.com/data1
        - http://test3.s3.mydomain.com/data1
        - http://test4.s3.mydomain.com/data1
        # - --certs-dir
        # - /tls
        ports:
        - containerPort: 9000
        volumeMounts:
        - mountPath: "/data1"
          name: minio-test1-pv1
        - mountPath: "/tls"
          name: minio-test1-tls
        env:
        - name: TZ
          value: "Europe/Budapest"
        - name: MINIO_ROOT_USER
          value: "minio"
        - name: MINIO_ROOT_PASSWORD
          value: "minio123"
        - name: MINIO_ACCESS_KEY
          value: "minio"
        - name: MINIO_SECRET_KEY
          value: "minio123"
        # - name: MINIO_DOMAIN
        #   value: "test1.s3.mydomain.com"
        - name: MINIO_REGION_NAME
          value: "regiontwo-zone2"
        - name: MINIO_REGION_COMMENT
          value: "RegionTwo Zone2"
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
          limits:
            memory: "2Gi"
            cpu: "2"
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: 9000
          initialDelaySeconds: 5
          periodSeconds: 30
        startupProbe:
          httpGet:
            path: /minio/health/live
            port: 9000
          failureThreshold: 30
          periodSeconds: 5
```

## Environment

- Kubernetes Version: v1.18.5
- Docker Version: containerd://1.3.3
- Operating System: Ubuntu 18.04.5 LTS
