### ISSUE TITLE
Size of the existing directory

### ISSUE THREAD

**Issue by bralbral** [minio/minio#11436]
Good day!

Minio ui shows wrong size (only 600+ mb)

![image](https://user-images.githubusercontent.com/54455457/106841470-3cca4480-66b3-11eb-9fc2-80a63c6b3bdc.png)

![image](https://user-images.githubusercontent.com/54455457/106841528-58354f80-66b3-11eb-95be-66915bb45d5f.png)

My docker-compose file
```
 version: '3'
services:
  minio:
    image: minio/minio:RELEASE.2020-12-03T05-49-24Z
    restart: always
    container_name: minio
    ports:
      - "8080:9000"
    volumes:
      - /storage:/data
    environment:
      - "MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE"
      - "MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
      - "MINIO_ROOT_USER=minio"
      - "MINIO_ROOT_PASSWORD=minio123"
    command: server --address 0.0.0.0:9000 /data

```

The files were not uploaded via api, they were copied to the directory. After that, the container was restarted (`docker restart`) - to no avail, and created again (`docker-compose down && docker-compose up -d`)

Best regards!
