### ISSUE TITLE
Allow providing init scritps 

### ISSUE THREAD

**Issue by omrisk** [minio/minio#11604]
**Is your feature request related to a problem? Please describe.**
A lot of services allow to mount init scripts to bootstrap a test environment or setup needed requirements in prod.

**Describe the solution you'd like**
Ability to `COPY` or mount via docker-compose the needed `.sh` files or `mc` commands to allow running scripts automatically when the container starts up

**Describe alternatives you've considered**
Add a `docker_process_init_files` in the `entrypoint.sh` script that will be able to load and run scripts from a defined path `docker-init.d`

**Additional context**
This is supported by applications such as [MySQL](https://github.com/mysql/mysql-docker/blob/b4405db9783ca814c8ac6e068c0826b803f49c2d/8.0/docker-entrypoint.sh#L149).

**Comment by omrisk** [comment]
I'm happy to work on this once it's triaged.

**Comment by harshavardhana** [comment]
@omrisk this is quite a niche requirement for us, there are many ways to do this already using docker-compose and running `mc` as a separate service. 

I don't see why this needs to be inside docker-entrypoint.sh 

```yaml
version: '3'

services:
  minio:
    image: minio/minio:latest
    volumes:
    - data:/data
    ports:
    - "9000:9000"
    networks:
      - minio
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data

  create_buckets:
    image: minio/mc:latest
    depends_on:
      - minio
    networks:
      - minio
    entrypoint: >
      /bin/sh -c '
      sleep 5;
      /usr/bin/mc config host add s3 http://minio:9000 minio minio123 --api S3v4;
      [[ ! -z "`/usr/bin/mc ls s3 | grep challenge`" ]] || /usr/bin/mc mb s3/challenge;
      /usr/bin/mc policy download s3/challenge;
      exit 0;
      '
volumes:
  data:

networks:
  minio:
```

So no we want to keep our scripts simple and purpose-driven.

**Comment by shuckc** [comment]
We also like our kube components to put themselves in a workable state using `postStart` exec command. To do this we first bundle mc+minio together using a custom Dockerfile:
```
FROM minio/mc:RELEASE.2021-02-19T05-34-40Z as client

FROM minio/minio:RELEASE.2021-02-24T18-44-45Z

ADD VERSION .
COPY --from=client /usr/bin/mc /usr/bin/mc

# mc requires writable configuration directory
RUN mkdir /bin/.mc && chmod ugo+rw /bin/.mc
```

Then we can mount inside a custom shell script for the application-specific setup in `/opt/` like below:
```
sleep 10
mc alias set local http://localhost:9000/ $MINIO_ACCESS_KEY $MINIO_SECRET_KEY
mc mb local/bucket-public
mc mb local/bucket-private
mc policy set public local/bucket-public
mc policy set public local/bucket-private
mc admin user add local/ bucketwriter newuser123
```

The final kube yaml end up with:
```
  spec:
        containers:
        - command:
          - /usr/bin/docker-entrypoint.sh
          - minio
          - server
          - /export
          env:
          - name: MINIO_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                key: accessKey
                name: minio-secret
          - name: MINIO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                key: secretKey
                name: minio-secret
          - name: MINIO_REGION
            value: eu-west-1
          - name: MINIO_BUCKET_NAME
            value: ""
          image: quay.internal.xyz/minio:2021.02.24-f0377ec.78
          lifecycle:
            postStart:
              exec:
                command:
                - /bin/sh
                - /opt/initialise_bucket.sh
```

They key point being that kube lifecycle events like `postStart` hook can't use a seperate image.
