### ISSUE TITLE
MinIO cannot start server mode with scaleio PVCs: no such file or directory

### ISSUE THREAD

**Issue by sokui** [minio/minio#11795]
Since release RELEASE.2021-02-23T20-05-01Z, minIO cannot start the server mode (either standalone or distributed) with scaleio PVCs. The gateway mode is fine. The error message is as below:

```
sh-4.4# minio server /data{1...4}
ERROR Unable to initialize backend: Disk /data1: no such file or directory
```

## Expected Behavior
MinIO should support scaleio PVCs for server mode.

## Current Behavior
scaleio release: any release >= RELEASE.2021-02-23T20-05-01Z
pvc configuration:

```
volumeMounts:
  - mountPath: "/data1"
    name: pvc1
  - mountPath: "/data2"
    name: pvc2
  - mountPath: "/data3"
    name: pvc3
  - mountPath: "/data4"
    name: pvc4
...
volumeClaimTemplates:
  - metadata:
      name: pvc1
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: scaleio
      resources:
        requests:
          storage: 500Gi
  - metadata:
      name: pvc2
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: scaleio
      resources:
        requests:
          storage: 500Gi
  - metadata:
      name: pvc3
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: scaleio
      resources:
        requests:
          storage: 500Gi
  - metadata:
      name: pvc4
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: scaleio
      resources:
        requests:
          storage: 500Gi
```

start command and error:
```
sh-4.4# minio server /data{1...4}
ERROR Unable to initialize backend: Disk /data1: no such file or directory
```

## Steps to Reproduce (for bugs)

1. use the version  >= RELEASE.2021-02-23T20-05-01Z
2. the start command is: `minio server /data{1...4}`
3.
4.

## Your Environment

* Version used (`minio --version`): any version >= RELEASE.2021-02-23T20-05-01Z
* Server setup and configuration: running in Kube with minio image
* Operating System and version (`uname -a`): sh-4.4# uname -a
Linux zhiheng-test-minio-statefulset-0 5.4.77-7.el7pie #1 SMP Sat Nov 21 01:16:27 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
