### ISSUE TITLE
Access PresignedUrl generated in docker-compose network

### ISSUE THREAD

**Issue by marcown** [minio/minio#11826]
Hi there,

I want to use a docker-compose setup locally using multiple services and minio.  The docker-compose file looks like this

```
version: '3.7'
services:
  minio:
    image: minio/minio:RELEASE.2021-03-12T00-00-47Z
    volumes:
      - /tmp/denkweit/minio:/data
    expose:
      - 9000
    env_file: .env
    command: server /data
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://minio:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3

  nginx:
    image: nginx:1.19.2-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '9000:9000'
    depends_on:
      - minio

.... more services 'backend'
```
 the nginx conf file is the one provided by minio for running minio in docker-compose

Now the problem is the following:

We have a GraphQL Server as one of the services in the docker-compose, when a frontend wants to get the images it will get a GraphQL result with a url to the image. In the backend we generate this url using the minio go client and presigned get url.

But the frontend can't access the image: Even with changing the host file (adding "127.0.0.1 minio") I get "SignatureDoesNotMatch". I think it has sth to do with which IP / Host is doing the request (the getpresignedurl) in the first place and sth about this IP / Host is encoded in the signature. (the frontend runs on localhost and not in the docker network -> that's why 9000 is exposed)

We don't want the frontend to directly talk to minio via a mc client (for several reasons, e.g. the data does not always come from minio and the frontend does not know, also the frontend does not know in which bucket to look for which id). Is there any way to do this? I saw several questions online but none of them helped us.

regards
marc
