### ISSUE TITLE
minio or s3fs not parallel upload small file

### ISSUE THREAD

**Issue by dayiguizhen** [minio/minio#11850]
I'm deploy minio(4 node, 2 compute with 4 disk) using docker swarm.
the docker-compose file is below.

```
minio1:
    image: minio/minio:RELEASE.2021-03-12T00-00-47Z
    hostname: minio1
    volumes:
      - /mnt/minio:/export
    ports:
      - "9001:9000"
    networks:
      # On the internal you are exposed as minio1/2/3/4 by default
      internal:  {}
      minio_test_distributed:
        aliases:
          - minio-cluster
    environment:
      MINIO_ROOT_USER: AKIAIOSFODNN7EXAMPLE
      MINIO_ROOT_PASSWORD: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      HOST_HOSTNAME: minio1
      MINIO_CACHE_DRIVES: '/tmp/'
      MINIO_CACHE_EXPIRY: 1
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:
        constraints:
          - node.labels.minio1==true
    command: server http://minio{1...4}/export
```

Then, I use s3fs mount minio to local.

`s3fs -o passwd_file=/etc/.passwd-s3fs -o url=http://10.42.0.115:9001 -o allow_other -o sigv2 -o nonempty -o no_check_certificate -o use_path_request_style -o umask=000 -o parallel_count=100 -o multipart_size=100 -o max_write=131072 -o big_writes -o use_cache=/dev/shm -o enable_noobj_cache marvel /minio/`

I use `dd` do a benchmark test speed between minio/nfs and local disk.

This is my python script:

```
minio_path = '/minio/test'
nfs_path = '/data/FileServer/test'
local_path = '/data/FileServer1/tmp_test'
goofys = '/goofys/test/test'
path = minio_path
bs = 64
ts = 'M'
parallel = 100


def run_dd(i):
    cmd = f'dd if=/dev/zero of={path}_{i} bs={bs}{ts} count=1 oflag=direct'
    #print(f'{i}------------------------' + str(time.time()))
    speed = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, shell=True)
    #print(f'{i}------------------------' + str(time.time()))
    out = speed.stdout
    s = float(str(out).split(',')[-1][:-7].strip(' '))
    #os.system(f"echo index {i} : {s} >> speed.txt")
    os.system(f"echo index {i} : {out} >> speed.txt")

process_list = []
for i in range(parallel):
    process_list.append(multiprocessing.Process(target=run_dd, args=(i,)))

start = time.time()
for p in process_list:
    p.start()
p.join()
```

It was a amazing speed when I write big file to minio, how fast!

But when I try to write small file like 512K, it was seem like serial not parallel.

So if I want trans serial to parallel, what should I config? minio or s3fs?

computer info:
    CPU number: 40
    MEM: 48G
    network:10Gb/s

The write speed:

\file | 512K（10,100 parallel） | 1M | 16M | 256M | 512M
-- | -- | -- | -- | -- | --
minio | 1.6MB/S,2.MB/S | 3MB/S,3.74MB/S | 42MB/S,45MB/S | 204MB/S,211MB/S | 214MB/S,250MB/S
NFS | 87MB/S,48MB/S | 95MB/S,106MB/S | 107MB/S,111MB/S | 106MB/s,110MB/S | 104MB/S,111MB/S
nfs | 242MB/S,588MB/S | 171MB/S,1179MB/S | 2404MB/S,613MB/S | 600MB/S, 436MB/S | 492MB/S,362MB/S
