### ISSUE TITLE
Unable to initialize OpenID: Get "url_keycloak" connect: connection refused (*fmt.wrapError)

### ISSUE THREAD

**Issue by vasilievs** [minio/minio#11882]
I use minio in docker with STS (keycloak)
When using sts configuration if url keycloak is not available Minio starts without open-id and does not try to re-check the connection to it until the container is restarted.

Also if the connection to the keycloak server is disconnected at the time of operation, the ability to use the open-id will also be disabled until the restart.

workaround:
 I added url keycloak check in docker and restart minio if it is not available but it's not good idea for production
```
    healthcheck:
      test: curl -f -v -k <keycloak_sever_url>/auth/realms/master/.well-known/openid-configuration ||  echo "keycloak server disconnected" > /proc/1/fd/1 | kill 1
      interval: 60s
      timeout: 5s
```

## Possible Solution
why is there no verification at the time of the request to the web or to receive tokens? how can this be fixed?

## Steps to Reproduce (for bugs)
1. Added env varibales to docker-compose
```
      MINIO_IDENTITY_OPENID_CONFIG_URL: <keycloak_url>
      MINIO_IDENTITY_OPENID_CLIENT_ID: <clent>
      MINIO_IDENTITY_OPENID_SCOPES: openid,email,profile,policy
      MINIO_IDENTITY_OPENID_CLAIM_NAME: policy
```
2. run conteiner
3. if keycloak url connected, it works
4. if keycloak don't connected, 

##  Environment
```
docker-compose v 2.4
image: minio/minio:RELEASE.2020-12-10T01-54-29Z
```
