### ISSUE TITLE
Federated Minio in gateway mode breaks with OpenID login for cross-account bucket access

### ISSUE THREAD

**Issue by wdbasson** [minio/minio#11936]
## Expected Behavior

With a federated Minio deployment consisting of two Minio instances in gateway mode (each of which have IAM credentials for a separate AWS account), I expected that Minio Browser with OpenID login would work similar to logging in with the access key and secret key.

## Current Behavior

When logging in to `Account A` Minio Browser with access/secret keys I am able to interact with buckets owned by the IAM user of `Account B` Minio.

When logging in to `Account A` Minio Browser with OpenID I get `[403 Forbidden] s3.GetBucketLocation` when interacting with buckets owned by the IAM user of `Account B` Minio.

When using access and secret key login the `Credential` passed in the `Authorization` header as part of the `GetBucketLocation` request in `Account B` Minio's trace is the IAM access key from `Account A` Minio.

Using OIDC login, the `Credential` passed in the `Authorization` header as part of the `GetBucketLocation` request in `Account B` Minio's trace appears to be a access key from Minio STS.

Using the SDK performing operations via the `Account A` Minio endpoint the `Credential` passed in the `Authorization` header as part of the `GetBucketLocation` request in `Account B` Minio's trace also appears to be a access key from Minio STS, but an `X-Amz-Security-Token` is included and the `GetBucketLocation` request is successful.

## Possible Solution

Unsure.

## Steps to Reproduce (for bugs)

1. Deploy federated Minio in gateway mode consisting of 2 Minio instances each with IAM credentials for a separate AWS account
2. Configure OpenID login by integrating with Keycloak following standard Minio documentation
3. Login to Minio Browser in `Account A` with OpenID and try to access a bucket owned by the IAM user from Minio in `Account B`

**Trace from Account B using access and secret key login via Account A Minio Browser:**
```
172.20.16.197 [REQUEST s3.GetBucketLocation] [14:02:06.825] [Client IP: 11.68.111.122]
172.20.16.197 GET /prod-minio/?location=
172.20.16.197 Proto: HTTP/1.1
172.20.16.197 Host: 172.20.16.197:9000
172.20.16.197 X-Amz-Date: 20210331T140206Z
172.20.16.197 Authorization: AWS4-HMAC-SHA256 Credential=<redacted>/20210331/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=5e66e5be61502e05f8062f8856c11bbb08085f9d3b33a995f74dff4572172fb8
172.20.16.197 Content-Length: 0
172.20.16.197 User-Agent: MinIO (linux; amd64) minio-go/v7.0.11
172.20.16.197 X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
172.20.16.197
172.20.16.197 [RESPONSE] [14:02:06.936] [ Duration 110.916ms  ↑ 77 B  ↓ 389 B ]
172.20.16.197 200 OK
172.20.16.197 Content-Security-Policy: block-all-mixed-content
172.20.16.197 Content-Type: application/xml
172.20.16.197 X-Amz-Request-Id: 167172382E6E5C67
172.20.16.197 X-Xss-Protection: 1; mode=block
172.20.16.197 Accept-Ranges: bytes
172.20.16.197 Content-Length: 137
172.20.16.197 Server: MinIO
172.20.16.197 Vary: Origin
172.20.16.197 X-Amz-Bucket-Region: eu-west-1
172.20.16.197 <?xml version="1.0" encoding="UTF-8"?>
<LocationConstraint xmlns="http://s3.amazonaws.com/doc/2006-03-01/">eu-west-1</LocationConstraint>
```

**Trace from Account A Minio with OIDC login:**
```
minio.example.com [REQUEST web.ListObjects] [13:17:12.359] [Client IP: 11.69.20.26]
minio.example.com POST /prod-minio
minio.example.com Proto: HTTP/1.1
minio.example.com Host: minio.example.com
minio.example.com X-Amz-Date: 20210331T131711Z
minio.example.com X-Forwarded-For: 11.69.20.26
minio.example.com X-Original-Forwarded-For: 11.69.20.26
minio.example.com Accept-Encoding: gzip, deflate, br
minio.example.com Accept-Language: en-ZA,en-GB;q=0.9,en-US;q=0.8,en;q=0.7
minio.example.com Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJBS0lBNENUREpES040NFkzTUhHMiIsImV4cCI6MTYxNzI4MjY0Mywic3ViIjoiQUtJQTRDVERKREtONDRZM01IRzIifQ.Yu_1OluzhQMVUd9h7SSMU17U_4bBOYj5aJk5dT-ejoeaDtbPPnHliHp2p1qqH4WnZ6onzxKA7bxuXzizTQ5WYQ
minio.example.com Sec-Fetch-Dest: empty
minio.example.com Sec-Fetch-Site: same-origin
minio.example.com X-Forwarded-Host: minio.example.com
minio.example.com X-Forwarded-Proto: https
minio.example.com X-Real-Ip: 11.69.20.26
minio.example.com Accept: */*
minio.example.com Content-Type: application/json
minio.example.com Cookie: _ga=GA1.2.1649810565.1605078671
minio.example.com User-Agent: Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36
minio.example.com X-Request-Id: 4814ea2fa8f1a2767806f3782ae41477
minio.example.com Content-Length: 100
minio.example.com X-Forwarded-Port: 443
minio.example.com X-Scheme: https
minio.example.com Dnt: 1
minio.example.com Origin: https://minio.example.com
minio.example.com Referer: https://minio.example.com/minio/prod-minio/
minio.example.com Sec-Fetch-Mode: cors
minio.example.com X-Amzn-Trace-Id: Root=1-60647657-13b203866855074567c66e9d
minio.example.com 
minio.example.com [RESPONSE] [13:17:12.359] [ Duration 367.363ms  ↑ 100 B  ↓ 1.5 KiB ]
minio.example.com 200 OK
minio.example.com Access-Control-Allow-Origin: https://minio.example.com
minio.example.com Content-Security-Policy: block-all-mixed-content
minio.example.com X-Amz-Request-Id: 16716FC4BDD1FD64
minio.example.com X-Content-Type-Options: nosniff
minio.example.com Access-Control-Allow-Credentials: true
minio.example.com Content-Type: application/json; charset=utf-8
minio.example.com Vary: Origin
minio.example.com X-Xss-Protection: 1; mode=block
minio.example.com Access-Control-Expose-Headers: Date, Etag, Server, Connection, Accept-Ranges, Content-Range, Content-Encoding, Content-Length, Content-Type, Content-Disposition, Last-Modified, Content-Language, Cache-Control, Retry-After, X-Amz-Bucket-Region, Expires, X-Amz*, X-Amz*, *
minio.example.com <BODY>
```
**Trace from Account B Minio with OIDC login:**
```
172.20.16.197 [REQUEST s3.GetBucketLocation] [13:09:02.373] [Client IP: 11.68.111.122]
172.20.16.197 GET /prod-minio/?location=
172.20.16.197 Proto: HTTP/1.1
172.20.16.197 Host: 172.20.16.197:9000
172.20.16.197 User-Agent: MinIO (linux; amd64) minio-go/v7.0.11
172.20.16.197 X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
172.20.16.197 X-Amz-Date: 20210331T130902Z
172.20.16.197 Authorization: AWS4-HMAC-SHA256 Credential=O0B2M14KP7XSC272Y60C/20210331/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=224e4224932782773e21869c8bf467da2eede87dee31a5b1627160d137695240
172.20.16.197 Content-Length: 0
172.20.16.197 
172.20.16.197 [RESPONSE] [13:09:02.373] [ Duration 231µs  ↑ 77 B  ↓ 598 B ]
172.20.16.197 403 Forbidden
172.20.16.197 Accept-Ranges: bytes
172.20.16.197 Content-Security-Policy: block-all-mixed-content
172.20.16.197 Content-Type: application/xml
172.20.16.197 Vary: Origin
172.20.16.197 X-Amz-Bucket-Region: eu-west-1
172.20.16.197 X-Amz-Request-Id: 16716F52BE4E0D13
172.20.16.197 Content-Length: 339
172.20.16.197 Server: MinIO
172.20.16.197 X-Xss-Protection: 1; mode=block
172.20.16.197 <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidTokenId</Code><Message>The security token included in the request is invalid</Message><BucketName>prod-minio</BucketName><Resource>/prod-minio/</Resource><Region>eu-west-1</Region><RequestId>16716F52BE4E0D13</RequestId><HostId>6f325c34-b40a-4e53-bb5c-038322f23414</HostId></Error>
```
**Trace from Account B Minio when usind SDK with STS via Account A Minio endpoint:**
```
minio.example.com [REQUEST s3.GetBucketLocation] [13:53:46.578] [Client IP: 11.69.20.26]
minio.example.com GET /prod-minio?location=
minio.example.com Proto: HTTP/1.1
minio.example.com Host: minio.example.com
minio.example.com Authorization: AWS4-HMAC-SHA256 Credential=01H8D3X7KZIRET6RLLZ6/20210331/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amz-security-token, Signature=0c48b07565b5a099970b175e8f1e507f876560f856996f720c7f590ea678b10b
minio.example.com X-Original-Forwarded-For: 11.69.20.26
minio.example.com Accept-Encoding: identity
minio.example.com X-Amz-Security-Token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiIwMUg4RDNYN0taSVJFVDZSTExaNiIsImFjciI6IjEiLCJhbGxvd2VkLW9yaWdpbnMiOlsiIl0sImF1ZCI6ImFjY291bnQiLCJhenAiOiJtaW5pbyIsImVtYWlsIjoid2lsbGVtQHplbmFwdGl4LmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZXhwIjoiMTYxNzIwMDQyNyIsImZhbWlseV9uYW1lIjoiQmFzc29uIiwiZ2l2ZW5fbmFtZSI6IldpbGxlbSIsImlhdCI6MTYxNzE5NjgyNywiaXNzIjoiaHR0cHM6Ly9rZXljbG9hay5kZXYubWRwLmNsb3VkL2F1dGgvcmVhbG1zL21pbmlvIiwianRpIjoiYmY3OTE1NGMtZjExZC00MGFlLTkxMTQtOGNlYTU4ZDI5ZTE2IiwibmFtZSI6IldpbGxlbSBCYXNzb24iLCJwb2xpY3kiOiJwcmluY2lwYWwiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ3aWxsZW0uYmFzc29uIiwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6InByb2ZpbGUgZW1haWwgcG9saWN5X3JvbGVfYXR0cmlidXRlIiwic2Vzc2lvbl9zdGF0ZSI6ImFjM2IxYjkyLTZhYmItNDZkOS05YTBhLTA1OThjOGQxOWE2NSIsInN1YiI6IjA4ZDVkZTY2LWNjYzQtNDhhYy1iMGFkLWEwYjczNTY3Y2Y1NCIsInR5cCI6IkJlYXJlciJ9.i8mazrtVKYzBZLZOpy1HF1XCAxesPfaXBQgfZXEinL4qZPXeul7HNnGHcVAAzES4bHRcJhiSMNX7uB8TUQ28pg
minio.example.com X-Scheme: https
minio.example.com X-Amz-Date: 20210331T135345Z
minio.example.com X-Real-Ip: 11.69.20.26
minio.example.com X-Request-Id: 43e1473f781d8e9a1e3744f02a23fce7
minio.example.com Content-Length: 0
minio.example.com User-Agent: MinIO (Linux; x86_64) minio-py/7.0.3
minio.example.com X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
minio.example.com X-Forwarded-Host: minio.example.com
minio.example.com X-Forwarded-Port: 443
minio.example.com X-Forwarded-Proto: https
minio.example.com X-Amzn-Trace-Id: Root=1-60647eea-60346771341461836000665e
minio.example.com X-Forwarded-For: 11.69.20.26, 11.68.114.179
minio.example.com 
minio.example.com [RESPONSE] [13:53:46.694] [ Duration 116.017ms  ↑ 255 B  ↓ 389 B ]
minio.example.com 200 OK
minio.example.com Accept-Ranges: bytes
minio.example.com Content-Security-Policy: block-all-mixed-content
minio.example.com Vary: Origin
minio.example.com X-Amz-Request-Id: 167171C3B55C6AD5
minio.example.com X-Xss-Protection: 1; mode=block
minio.example.com Content-Length: 137
minio.example.com Content-Type: application/xml
minio.example.com Server: MinIO
minio.example.com X-Amz-Bucket-Region: eu-west-1
minio.example.com <?xml version="1.0" encoding="UTF-8"?>
<LocationConstraint xmlns="http://s3.amazonaws.com/doc/2006-03-01/">eu-west-1</LocationConstraint>
```

## Context

We have S3 buckets in multiple AWS accounts and would like to centralize access and policy management as well as allowing users to authenticate using OIDC.

## Regression

Unsure.

## Your Environment

* Version used: `RELEASE.2021-03-17T02-33-02Z`
* Server setup and configuration: `Kubernetes`
* Operating System and version: `EKS v1.15`

**Comment by harshavardhana** [comment]
If you don't have etcd configured there is no federation. Can you show me if you are using etcd?

**Comment by wdbasson** [comment]
> If you don't have etcd configured there is no federation. Can you show me if you are using etcd?

etcd is configured and federation works when logging in with access and secret key via Minio browser. Both Minio instances use the same root credentials in order to share etcd access (as far as I understand). `Account A` Minio uses `MINIO_ACCESS_KEY` and `MINIO_SECRET_KEY` both as the root credentials and AWS IAM credentials.

OIDC login also works when using SDK. I can interact with buckets owned by any of the Minio IAM users via both endpoints, including operations that require `GetBucketLocation`.

Below is the relevant k8s deployment template specs for `Account A` & `Account B` Minio:

**Account A Minio k8s deployment:**
```
...
    spec:
      containers:
      - args:
        - gateway
        - s3
        - $(ENDPOINT)
        env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: AccessKey
              name: minio-config
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: SecretKey
              name: minio-config
        - name: ENDPOINT
          value: https://s3.eu-west-1.amazonaws.com
        - name: MINIO_IDENTITY_OPENID_CONFIG_URL
          value: https://keycloak.dev.example.com/auth/realms/minio/.well-known/openid-configuration
        - name: MINIO_IDENTITY_OPENID_CLIENT_ID
          value: minio
        - name: MINIO_ETCD_ENDPOINTS
          value: http://etcd.dev-minio.svc.cluster.local:2379
        - name: MINIO_DOMAIN
          value: minio-fed.dev.example.com
        - name: MINIO_PUBLIC_IPS
          value: minio
        image: minio/minio:RELEASE.2021-03-17T02-33-02Z
...
```

**Account B Minio k8s deployment:**
```
...
    spec:
      containers:
      - args:
        - gateway
        - s3
        - $(ENDPOINT)
        env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: AccessKey
              name: minio-prod-config
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: SecretKey
              name: minio-prod-config
        - name: ENDPOINT
          value: 
        - name: MINIO_IDENTITY_OPENID_CONFIG_URL
          value: https://keycloak.dev.example.com/auth/realms/minio/.well-known/openid-configuration
        - name: MINIO_IDENTITY_OPENID_CLIENT_ID
          value: minio
        - name: MINIO_ETCD_ENDPOINTS
          value: http://etcd.dev-minio.svc.cluster.local:2379
        - name: MINIO_DOMAIN
          value: minio-fed.dev.mdp.cloud
        - name: MINIO_PUBLIC_IPS
          value: minio-prod
        - name: AWS_ACCESS_KEY_ID
          value: <redacted>
        - name: AWS_SECRET_ACCESS_KEY
          value: <redacted>
        image: minio/minio:RELEASE.2021-03-17T02-33-02Z
...
```

`MINIO_PUBLIC_IPS` is configured to be the k8s service of the respective pods.

Please let me know if there is any more information I can share to assist.
