### ISSUE TITLE
Enable metrics but disable service monitor

### ISSUE THREAD

**Issue by solyard** [minio/minio#12159]
**Is your feature request related to a problem? Please describe.**
I want to be able to enable metrics endpoint and creating a `bearer` for accessing it but not create ServiceMonitor for Prometheus cause I have a custom monitoring system and automation task always crashing while trying to deploy CRD (ServiceMonitor) into a cluster

**Describe the solution you'd like**
Additional option
```yaml
    metrics:
      enabled: true
      serviceMonitor:
        enabled: false
```

**Describe alternatives you've considered**
I'm actually disabled consistency check for Minio helm-chart but this is unclean feature and in production it will cause some problems
