### ISSUE TITLE
Minio not connecting to s3 compatible service due to unexpected signature v2/v4 issues

### ISSUE THREAD

**Issue by redturtlepower** [minio/minio#12245]
## Expected Behavior

The connection to backblaze s3 api does work.
My reference setup is 
- [caddy2](https://caddyserver.com/) [s3browser](https://github.com/techknowlogick/caddy-s3browser) plugin
- connect to backblaze s3 -> works

## Current Behavior

The connection to backblaze s3 api does not work.
My target setup is 
- caddy2 s3browser plugin
- s3browser connect to minio at localhost:9001 (gateway s3)
- minio connects to backblaze s3

Debugging:
Loading minio directly (not via s3browser) -> does not work with following error when loading `https://minio.mydomain.com/`
```
<Error>
<Code>InvalidRequest</Code>
<Message>
The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.
</Message>
<Resource>/</Resource>
<RequestId/>
<HostId>10e26bec-764c-46d0-a0cb-2f4935b44e36</HostId>
</Error>
```

## Possible Solution

Don't know. Maybe add documentation how to select v2 or v4 signature version?

## Steps to Reproduce (for bugs)

1. I am running minio as a docker swarm service like this:
```
---
version: "3.8"

services:
  minio:
    image: docker.nexus.mydomain.com:8084/minio:RELEASE.2021-04-22T15-44-28Z
    hostname: minio1
    volumes:
      - minio1-data:/export
    ports:
      - "9001:9000"
    networks:
      - my-network
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:
        constraints:
          - node.labels.minio1==true
      labels:
        caddy: minio.mydomain.com
        caddy.reverse_proxy: "{{upstreams 9000}}"
        caddy.basicauth.thatsme: "vcyxnmvcyxmvcxycvxyvcyxmcvxmvcxyvcyxnnvmcxy"
    command: gateway s3 https://s3.xxxxxxxxx.backblazeb2.com
    secrets:
      # Using Backblaze (b2), following terminology applies:
      # secret_key (s3)  = application key (b2)
      # accecss_key (s3) = application key id (b2)
      - secret_key
      - access_key
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  minio1-data:

networks:
  my-network:
    external: true
    name: my-network

secrets:
  secret_key:
    file: /home/thatsme/my-secrets/minio/backblaze_minio-gateway_secret-key.txt
  access_key:
    file: /home/thatsme/my-secrets/minio/backblaze_minio-gateway_access-key.txt

```

## Context

I am trying to learn minio, and use it as a cache layer. Moreover I want to push files via minio self hosted and not directly to backblaze (no tight coupling to a specific s3 supplier).
I am not aware of any settings to change v2/v4 signature behaviour. The error seems to indicate minio is not using v4 signature. Backblaze uses v4 ([source](https://help.backblaze.com/hc/en-us/articles/360047425453-Getting-Started-with-the-S3-Compatible-API))

## Regression
My first try with minio, can't tell if regression

## Your Environment

* Version used (`minio --version`):  RELEASE.2021-04-22T15-44-28Z
* Server setup and configuration: 
- Intel XEON, 2 GB RAM
- Docker version 19.03.8, build afacb8b7f0
- docker-compose version 1.26.2, build eefe0d31
* Operating System and version (`uname -a`): Linux ubuntu-2gb-fsn1-1 5.4.0-40-generic
