### ISSUE TITLE
Error message after upgrade

### ISSUE THREAD

**Issue by roiterorh** [minio/minio#12307]
## Current Behavior

getting this error message on docker container start but it seems at first view that everything works as it should though
```
API: SYSTEM()
Time: 12:07:08 UTC 05/17/2021
DeploymentID: 01d045c1-139e-4633-ac54-7fd0b3098c68
Error: Unable to migrate IAM users and policies to new format: unexpected EOF (*fmt.wrapError)
       1: cmd/iam.go:647:cmd.(*IAMSys).Init()

API: SYSTEM()
Time: 12:07:08 UTC 05/17/2021
DeploymentID: 01d045c1-139e-4633-ac54-7fd0b3098c68
Error: IAM sub-system is partially initialized, some users may not be available (*errors.errorString)
       1: cmd/iam.go:648:cmd.(*IAMSys).Init()
Exiting on signal: TERMINATED
```

# steps to reproduce

1. deploy minio version `RELEASE.2020-10-28T08-16-50Z` with this ansible task

```
- name: Create minio container
  docker_container:
    name: minio
    image: minio/minio:RELEASE.2020-10-28T08-16-50Z
    command: server {{minio_servers}}
    state: started
    recreate: true
    hostname: "{{ansible_ssh_host}}"
    restart_policy: on-failure
    published_ports:
      - 9000:9000
    volumes:
      - /var/lib/minio:/data
    env:
      MINIO_ACCESS_KEY: "{{minio_access_key}}"
      MINIO_SECRET_KEY: "{{minio_secret_key}}"
      MINIO_DOMAIN: "{{ansible_ssh_host}}:9000"
      MINIO_PROMETHEUS_AUTH_TYPE: "public"
```
2. then update tag to `RELEASE.2021-05-16T05-32-34Z` (latest version ATM) and redeploy 
3. run `docker logs minio` on any server will return the same error

We are preparing a cluster upgrade on production and therefore will have to wait on this issue to be resolved before proceeding
