### ISSUE TITLE
Minio gateway with encryption doesn't work auto-encryption enabled

### ISSUE THREAD

**Issue by annkam** [minio/minio#12335]
Good afternoon! We've set up a minio gateway with encryption in front of a basic Minio server with no encryption. We want all our data to be encrypted only at the gateway, so in case of the direct access to the backend we can not view the data unencrypted

This configuration works:

```
version: '2.4' 
  
services: 
 miniogw: 
   image: minio/minio:RELEASE.2021-04-22T15-44-28Z 
   container_name: minio-gw 
   environment: 
     MINIO_ROOT_USER: miniogw 
     MINIO_ROOT_PASSWORD: minio123 
     AWS_ACCESS_KEY_ID: minio 
     AWS_SECRET_ACCESS_KEY: minio123 
     MINIO_KMS_KES_ENDPOINT: https://play.min.io:7373 
     MINIO_KMS_KES_CERT_FILE: /minio-data/root.cert 
     MINIO_KMS_KES_KEY_FILE: /minio-data/root.key 
     MINIO_KMS_KES_KEY_NAME: my-app-key 
     MINIO_KMS_AUTO_ENCRYPTION: "on" 
     MINIO_GATEWAY_SSE: "c" 
   volumes: 
     - ./data:/minio-data 
   ports: 
     - "9001:9000" 
   command: gateway s3 http://minio:9000 
   depends_on: 
     minio: 
       condition: service_healthy 
 minio: 
   image: minio/minio:RELEASE.2021-05-18T00-53-28Z
   container_name: minio 
   environment: 
     MINIO_ROOT_USER: minio 
     MINIO_ROOT_PASSWORD: minio123 
   command: server /minio-data/data 
   volumes: 
     - ./data:/minio-data 
   ports: 
     - "9000:9000" 
   healthcheck: 
     test: "curl -sS http://localhost:9000/minio/health/live || echo 1" 
     interval: 5s 
     timeout: 10s 
     retries: 3
```

Notice that the gateway is on version `RELEASE.2021-04-22T15-44-28Z` and the server is on `RELEASE.2021-05-18T00-53-28Z`. After upgrading to `RELEASE.2021-05-18T00-53-28Z` the gateway does not work.

## Expected Behavior

I expect gateway encryption to work on latest release

## Current Behavior

Objects can't be uploaded with the following error:

```
minio-gw   | API: SYSTEM() 
minio-gw   | Time: 08:09:06 UTC 05/20/2021 
minio-gw   | DeploymentID: bfca7554-018d-4fe7-a7c1-d03788911aba 
minio-gw   | Error: Server side encryption specified but KMS is not configured (minio.ErrorResponse) 
minio-gw   |        5: cmd/api-errors.go:2031:cmd.toAPIErrorCode() 
minio-gw   |        4: cmd/api-errors.go:2056:cmd.toAPIError() 
minio-gw   |        3: cmd/web-handlers.go:2446:cmd.toWebAPIError() 
minio-gw   |        2: cmd/web-handlers.go:2455:cmd.writeWebErrorResponse() 
minio-gw   |        1: cmd/web-handlers.go:1327:cmd.(*webAPIHandlers).Upload()
```

## Steps to Reproduce
1) Deploy provided docker-compose file
2) Test uploading/downloading files
3) Change miniogw image tag to RELEASE.2021-05-18T00-53-28Z
4) Try to upload a file
