### ISSUE TITLE
Error: io: read/write on closed pipe (*errors.errorString) in healing

### ISSUE THREAD

**Issue by krakazyabra** [minio/minio#12410]
## Expected Behavior
Minio runs without such message in log

## Current Behavior
Thousands of messages like
```shell
API: SYSTEM()
Time: 12:51:27 UTC 06/01/2021
DeploymentID: 0bbd5e0d-fdb6-4bbd-b210-0c13a31d2e36
Error: io: read/write on closed pipe (*errors.errorString)
    12: cmd/data-scanner.go:869:cmd.(*scannerItem).applyHealing()
    11: cmd/data-scanner.go:972:cmd.(*scannerItem).applyActions()
    10: cmd/xl-storage.go:459:cmd.(*xlStorage).NSScanner.func1()
    9: cmd/data-scanner.go:467:cmd.(*folderScanner).scanFolder.func1()
    8: cmd/os-readdir_unix.go:176:cmd.readDirFn()
    7: cmd/data-scanner.go:402:cmd.(*folderScanner).scanFolder()
    6: cmd/data-scanner.go:519:cmd.(*folderScanner).scanFolder.func2()
    5: cmd/data-scanner.go:583:cmd.(*folderScanner).scanFolder()
    4: cmd/data-scanner.go:314:cmd.scanDataFolder()
    3: cmd/xl-storage.go:429:cmd.(*xlStorage).NSScanner()
    2: cmd/xl-storage-disk-id-check.go:171:cmd.(*xlStorageDiskIDCheck).NSScanner()
    1: cmd/erasure.go:500:cmd.erasureObjects.nsScanner.func3()
```

## Possible Solution
Show what exactly happens, more clear description of problem

## Steps to Reproduce (for bugs)

1. Update to `RELEASE.2021-05-26T00-22-46Z`
2. Run with `minio server /minio/minio{1...98}` in standalone mode
3. Use it with 1000+ buckets and 3,3M objects

## Context
There was no unusual behavior before upgrading, minio was working on `RELEASE.2021-03-26T00-00-41Z`
First time I faced with this message on `RELEASE.2021-05-22T02-34-39Z`
I suppose, that this error is not just a notice. Something bad is going inside. I'm not sure if my data in Minio is safe.

## Your Environment

* Version used (`minio --version`):
```shell
mc admin info storage11
●  storage11.s3.domain.org
   Uptime: 5 days
   Version: 2021-05-26T00:22:46Z
   Network: 1/1 OK
   Drives: 98/98 OK

18 TiB Used, 1,194 Buckets, 3,343,906 Objects
98 drives online, 0 drives offline
```

* Server setup and configuration:
Running from simple daemonset
<details><summary>minio.yaml</summary>
<p>

```yaml
---
apiVersion: v1
data:
  mount-check.sh: |
    #!/bin/sh

    for i in $(seq 1 99); do
      if grep -qs "minio$i" /proc/mounts; then
        echo "It's mounted."
      else
        echo "It's not mounted."
        mkdir -p /minio/minio$i
        mount /dev/disk/by-label/minio$i /minio/minio$i
        if [ $? -eq 0 ]; then
         echo "Mount minio$i success!"
        else
         echo "Something went wrong with the mount minio$i"
        fi
      fi; done
kind: ConfigMap
metadata:
  annotations:
    qbec.io/component: minio
  labels:
    qbec.io/application: minio
    qbec.io/environment: prod
  name: mount-check
  namespace: minio

---
apiVersion: v1
data:
  sysctl.sh: |
    #!/bin/bash

    cat > sysctl.conf <<EOF
    # maximum number of open files/file descriptors
    fs.file-max = 4194303
    # use as little swap space as possible
    vm.swappiness = 1
    # prioritize application RAM against disk/swap cache
    vm.vfs_cache_pressure = 10
    # minimum free memory
    vm.min_free_kbytes = 1000000
    # maximum receive socket buffer (bytes)
    net.core.rmem_max = 268435456
    # maximum send buffer socket buffer (bytes)
    net.core.wmem_max = 268435456
    # default receive buffer socket size (bytes)
    net.core.rmem_default = 67108864
    # default send buffer socket size (bytes)
    net.core.wmem_default = 67108864
    # maximum number of packets in one poll cycle
    net.core.netdev_budget = 1200
    # maximum ancillary buffer size per socket
    net.core.optmem_max = 134217728
    # maximum number of incoming connections
    net.core.somaxconn = 65535
    # maximum number of packets queued
    net.core.netdev_max_backlog = 250000
    # maximum read buffer space
    net.ipv4.tcp_rmem = 67108864 134217728 268435456
    # maximum write buffer space
    net.ipv4.tcp_wmem = 67108864 134217728 268435456
    # enable low latency mode
    net.ipv4.tcp_low_latency = 1
    # socket buffer portion used for TCP window
    net.ipv4.tcp_adv_win_scale = 1
    # queue length of completely established sockets waiting for accept
    net.ipv4.tcp_max_syn_backlog = 30000
    # maximum number of sockets in TIME_WAIT state
    net.ipv4.tcp_max_tw_buckets = 2000000
    # reuse sockets in TIME_WAIT state when safe
    net.ipv4.tcp_tw_reuse = 1
    # time to wait (seconds) for FIN packet
    net.ipv4.tcp_fin_timeout = 5
    # disable icmp send redirects
    net.ipv4.conf.all.send_redirects = 0
    # disable icmp accept redirect
    net.ipv4.conf.all.accept_redirects = 0
    # drop packets with LSR or SSR
    net.ipv4.conf.all.accept_source_route = 0
    # MTU discovery, only enable when ICMP blackhole detected
    net.ipv4.tcp_mtu_probing = 1
    EOF
    echo "Enabling system level tuning params"
    sysctl --quiet --load sysctl.conf && rm -f sysctl.conf
    # `Transparent Hugepage Support`*: This is a Linux kernel feature intended to improve
    # performance by making more efficient use of processor’s memory-mapping hardware.
    # But this may cause https://blogs.oracle.com/linux/performance-issues-with-transparent-huge-pages-thp
    # for non-optimized applications. As most Linux distributions set it to `enabled=always` by default,
    # we recommend changing this to `enabled=madvise`. This will allow applications optimized
    # for transparent hugepages to obtain the performance benefits, while preventing the
    # associated problems otherwise. Also, set `transparent_hugepage=madvise` on your kernel
    # command line (e.g. in /etc/default/grub) to persistently set this value.
    echo "Enabling THP madvise"
    echo madvise | sudo tee /sys/kernel/mm/transparent_hugepage/enabled
kind: ConfigMap
metadata:
  annotations:
    qbec.io/component: minio
  labels:
    qbec.io/application: minio
    qbec.io/environment: prod
  name: sysctl
  namespace: minio

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    qbec.io/component: minio
  labels:
    app: minio-storage11
    headless: minio
    qbec.io/application: minio
    qbec.io/environment: prod
  name: minio-storage11
  namespace: minio
spec:
  selector:
    matchLabels:
      app: minio-storage11
  template:
    metadata:
      labels:
        app: minio-storage11
        headless: minio
    spec:
      containers:
      - args:
        - server
        - /minio/minio{1...98}
        env:
        - name: MINIO_PROMETHEUS_AUTH_TYPE
          value: public
        - name: MINIO_STORAGE_CLASS_STANDARD
          value: EC:2
        - name: MINIO_ACCESS_KEY
          value: access_key
        - name: MINIO_SECRET_KEY
          value: secret_key
        image: minio/minio:RELEASE.2021-05-26T00-22-46Z
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: 9000
          initialDelaySeconds: 120
          periodSeconds: 20
        name: minio
        ports:
        - containerPort: 9000
          name: service
        securityContext:
          privileged: true
        terminationMessagePath: /termination-log
        volumeMounts:
        - mountPath: /minio
          mountPropagation: HostToContainer
          name: data
      initContainers:
      - command:
        - /bin/sh
        - -c
        - cp -fp /scripts/mount-check.sh /minio/mount-check.sh; chmod +x /minio/mount-check.sh; exec /minio/mount-check.sh; cp -fp /scripts/sysctl.sh /minio/sysctl.sh; chmod +x sysctl.sh; exec /minio/sysctl.sh
        image: busybox:1.31.1
        imagePullPolicy: IfNotPresent
        name: mount
        securityContext:
          privileged: true
        terminationMessagePath: /termination-log
        volumeMounts:
        - mountPath: /scripts/mount-check.sh
          name: mount-check
          subPath: mount-check.sh
        - mountPath: /scripts/sysctl.sh
          name: sysctl
          subPath: sysctl.sh
        - mountPath: /scripts
          name: scripts
        - mountPath: /minio
          mountPropagation: Bidirectional
          name: data
        - mountPath: /dev
          name: dev
      nodeSelector:
        kubernetes.io/hostname: storage11
      terminationGracePeriodSeconds: 5
      volumes:
      - emptyDir: {}
        name: scripts
      - configMap:
          defaultMode: 511
          name: mount-check
        name: mount-check
      - configMap:
          defaultMode: 511
          name: sysctl
        name: sysctl
      - hostPath:
          path: /minio
        name: data
      - hostPath:
          path: /dev
        name: dev

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    qbec.io/component: minio
  labels:
    app: minio-headless
    qbec.io/application: minio
    qbec.io/environment: prod
  name: minio-headless
  namespace: minio
spec:
  clusterIP: None
  ports:
  - name: service
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    headless: minio

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    qbec.io/component: minio
  labels:
    app: minio-svc
    qbec.io/application: minio
    qbec.io/environment: prod
  name: minio-storage11
  namespace: minio
spec:
  ports:
  - name: service
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: minio-storage11
  type: ClusterIP
```
</p>
</details>
* Operating System and version (`uname -a`):

```shell
root@storage11:/# uname -a
Linux storage11 5.4.0-73-generic #82-Ubuntu SMP Wed Apr 14 17:39:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
root@storage11:/# cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
