### ISSUE TITLE
Server not initialized, please try again

### ISSUE THREAD

**Issue by misterEggroll** [minio/minio#12473]
I am trying to deploy a minio server on Kubernetes.
The deployment has a persistent volume attached to it. Which is resulting in the pod starting but the server isn't starting.

This is the manifest I'm using:

`manifest.yaml`
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
  namespace: argo
  labels:
    name: argo-minio-pv
    app: minio
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: <server IP>
    path: <path on NFS>
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: argo-minio-pvc
  namespace: argo
  labels:
    name: argo-minio-pvc
    app: minio
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      name: argo-minio-pv
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: minio
  name: minio
spec:
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: minio
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: minio
  name: minio
spec:
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - command:
            - minio
            - server
            - /storage
          env:
            - name: MINIO_ACCESS_KEY
              value: admin
            - name: MINIO_SECRET_KEY
              value: password
          image: minio/minio:RELEASE.2021-06-07T21-40-51Z
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 10
          name: main
          ports:
            - containerPort: 9000
          securityContext:
            runAsUser: 0
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 10
          # Mount data on PVC here
          volumeMounts:
            - mountPath: /storage
              name: minio-data
      # Declare PVC as a volume accessible to the deployment
      volumes:
        - name: minio-data
          persistentVolumeClaim:
            claimName: argo-minio-pvc
```

## Expected Behavior
The minio pod should start by showing the startup log and the health check should return this result:

### Log:
```
kubectl logs -n argo minio-6b99bcf59f-r5zmh
Endpoint: http://10.0.2.212:9000  http://127.0.0.1:9000 

Browser Access:
   http://10.0.2.212:9000  http://127.0.0.1:9000

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide

```

### Health Check:
```
curl --GET http://localhost:9000/minio/health/ready -v                                                             
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 9000 (#0)
> GET /minio/health/ready HTTP/1.1
> Host: localhost:9000
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Accept-Ranges: bytes
< Content-Length: 0
< Content-Security-Policy: block-all-mixed-content
< Server: MinIO
< Vary: Origin
< X-Amz-Request-Id: 1686DB76DEEB4E9D
< X-Xss-Protection: 1; mode=block
< Date: Wed, 09 Jun 2021 08:06:59 GMT
< 
* Connection #0 to host localhost left intact
* Closing connection 0
```

## Current Behavior
I see the message "Server not initialized, please try again" when port forwarding the minio service and opening the UI on the browser.

Minio pod is starting. But the server is not accessible and not showing logs.
```
NAME                                   READY   STATUS    RESTARTS   AGE
minio-5f66cbf6db-qr2tm                 1/1     Running   0          14m
```

### Logs

```
 % kubectl logs -n argo minio-5f66cbf6db-qr2tm
 % 
```

### Health Check

```
 % curl --GET http://localhost:9000/minio/health/ready -v
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 9000 (#0)
> GET /minio/health/ready HTTP/1.1
> Host: localhost:9000
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Accept-Ranges: bytes
< Content-Length: 0
< Content-Security-Policy: block-all-mixed-content
< Server: MinIO
< Vary: Origin
< X-Amz-Request-Id: 1686D7E73EDAC6EA
< X-Minio-Server-Status: offline
< X-Xss-Protection: 1; mode=block
< Date: Wed, 09 Jun 2021 07:01:43 GMT
< 
* Connection #0 to host localhost left intact
* Closing connection 0
```

## Possible Solution

Unsure.

## Steps to Reproduce (for bugs)
1. Create PV
2. Create PVC
3. Mount folder on PVC
4. Start deployment: `kubectl apply -f manifest.yaml`

## Context
I'm trying to mount a PersistentVolumeClaim to my minio deployment.
The drive is getting mounted successfully and there are files getting created as well.

Volumes using `kubectl describe pod`:
```
Volumes:
  minio-data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  argo-minio-pvc
    ReadOnly:   false
  default-token-w8hcj:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-w8hcj
    Optional:    false
```

`ls` on the mounted drive:
```
 % kubectl exec -n argo -it minio-5f66cbf6db-qr2tm -- ls -la /storage       
total 8
drwxrwxr-x 3 root root 4096 Jun  9 07:07 .
drwxr-xr-x 1 root root   56 Jun  9 08:16 ..
drwxr-xr-x 5 root root 4096 Jun  9 07:07 .minio.sys
```

Mounted drive further details:
```
 % kubectl exec -n argo -it minio-5f66cbf6db-qr2tm -- df -h | grep -e File -e /storage
Filesystem                     Size  Used Avail Use% Mounted on
<IP>:/exports/minio/  197G   66G  131G  34% /storage
```

However, the minio server is not starting.

## Regression
Unsure.

## Environment
* Docker Release used: `minio/minio:RELEASE.2021-06-07T21-40-51Z`
* Kubernetes Version: `v1.16.15-eks-ad4801`
