### ISSUE TITLE
Docker & Traefik - "There are no buckets yet"

### ISSUE THREAD

**Issue by gino** [minio/minio#12676]
Hey everyone,

I am trying to setup MinIO through Traefik, with Docker. And I have setup two endpoints:
- `minio.mydomain.tld`, where the MinIO Console is accessible.
- `cdn.mydomain.tld`, where the actual MinIO API lives.

Both endpoints are working fine and are able to reach through the browser. However, whenever I create a bucket through the Console, my bucket does not show up in the actual overview: `There are no Buckets yet.`. I do see the created bucket in the filesystem, but it doesn't show up in the actual browser. Even though other list overviews, like listing all created users, works fine. I am not sure why this is happening, both endpoints are working, I do not see any errors in the logs either. Just `null` when it is trying to fetch all the buckets. 

I assume this bucket issue has something to do with the combination of Traefik. Since I have tried to just run a MinIO container without Traefik, and that works fine, as expected. However, I think my `docker-compose.yml` should work fine, since both endpoints are reachable and both provided with a valid SSL certificate:

```yml
services:
  minio:
    image: minio/minio:latest
    env_file: ".env"
    volumes:
      - "./data:/data"
    networks:
      - web_proxy
    command: server /data --console-address ":9001"
    labels:
      # Minio Console
      - "traefik.http.routers.minio.rule=Host(`minio.mydomain.tld`)"
      - "traefik.http.routers.minio.tls=true"
      - "traefik.http.routers.minio.tls.certresolver=resolver"
      - "traefik.http.routers.minio.service=minioService"
      - "traefik.http.services.minioService.loadbalancer.server.port=9001"
      - "traefik.http.services.minioService.loadbalancer.passhostheader=true"
      # Minio itself
      - "traefik.http.routers.cdn.rule=Host(`cdn.mydomain.tld`)"
      - "traefik.http.routers.cdn.tls=true"
      - "traefik.http.routers.cdn.tls.certresolver=resolver"
      - "traefik.http.routers.cdn.service=cdnService"
      - "traefik.http.services.cdnService.loadbalancer.server.port=9000"
      - "traefik.http.services.cdnService.loadbalancer.passhostheader=true"

networks:
  web_proxy:
    external:
      name: web_proxy
```

I hope someone is able to help me out, I have no idea why this issue is happening and it makes MinIO unable to use, unfortunately.

Thanks in advance.

**Edit:** If I try to reach my just created bucket in the URL (`https://minio.mydomain.tld/buckets/<bucket>/summary`), I receive an error in the console on the `/api/v1/buckets/test/encryption/info` call: `{ code: 404, message: "The server side encryption configuration was not found" }`. Could this error, cause the issue I am having? Even though I am not sure how to solve it..
