### ISSUE TITLE
OIDC Console Login Fails Unexpectedly

### ISSUE THREAD

**Issue by georglauterbach** [minio/minio#12722]
I'm using [Authelia](https://github.com/authelia/authelia) as an OIDC identity provider. I'm running release `RELEASE.2021-07-12T02-44-53Z` and I can click "Login with SSO", I'm redirected to Authelia where I accept the scopes. But then, I am redirected back to the login screen, not being logged in. I'm getting a HTTP 401 (sporadically) and MinIO throws an error.

## Expected Behavior

I can log in with the users defined by the OIDC identity provider

## Current Behavior

I'm redirected back to the login screen, receiving HTTP 401 Unauthorized (sporadically) and MinIO shows a "stack trace" on error.

This is the MinIO error message

```INI
API: AssumeRoleWithWebIdentity(bucket=5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5, object=5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5)
Time: 12:28:09 UTC 07/15/2021
DeploymentID: 7455ac5b-dc6d-422a-9595-f59a8fd41135
RequestID: 1691F69BE2A90C45
RemoteHost: 96469a4768fa417e42f64c08275db11f8fa4e469ca0fd54b727ac4dc9d46363c
Host: 10.0.0.63:9090
UserAgent: Go-http-client/1.1
Error: *errors.errorString
4: cmd/sts-errors.go:58:cmd.writeSTSErrorResponse()
3: cmd/sts-handlers.go:363:cmd.(*stsAPIHandlers).AssumeRoleWithSSO()
2: cmd/sts-handlers.go:459:cmd.(*stsAPIHandlers).AssumeRoleWithWebIdentity()
1: net/http/server.go:2069:http.HandlerFunc.ServeHTTP()
original error -> (user_login.go:62: invalid Login)
debugging error: 400 Bad Request
```

and this the HTTP response to the XHR POST request

``` HTTP
XHRPOSThttps://files.example.com/api/v1/login/oauth2/auth
[HTTP/2 401 Unauthorized 305ms]

POST

scheme
	https
host
	files.example.com
filename
	/api/v1/login/oauth2/auth
Address
	0.0.0.0:443
Status401
Unauthorized
VersionHTTP/2
Transferred933 B (39 B size)
Referrer Policystrict-origin-when-cross-origin

    alt-svc
    	h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400, h3=":443"; ma=86400
    cf-cache-status
    	DYNAMIC
    cf-ray
    	66f305f1af2d9ab0-FRA
    content-length
    	39
    content-type
    	application/json
    date
    	Thu, 15 Jul 2021 12:34:08 GMT
    expect-ct
    	max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
    nel
    	{"report_to":"cf-nel","max_age":604800}
    report-to
    	{"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=eMJAkxOOKEa8uDLWZb0xv%2Bhp%2BRdbSHQTZx3XCTfJUNApdzn%2FbNqLFzyD0E%2BaLfdBoLqZ1aYt9nEZ5lS5ycVgCJww5MgYy%2BrxINfP46ftczNNFh5kmeootmaGutWlRvz5WIDPf77yeBhkiMk8"}],"group":"cf-nel","max_age":604800}
    server
    	cloudflare
    strict-transport-security
    	max-age=15552000; includeSubDomains; preload
    x-content-type-options
    	nosniff
    X-Firefox-Spdy
    	h2
    x-frame-options
    	DENY
    x-xss-protection
    	1; mode=block
    	
    Accept
    	*/*
    Accept-Encoding
    	gzip, deflate, br
    Accept-Language
    	de
    Cache-Control
    	no-cache
    Connection
    	keep-alive
    Content-Length
    	209
    Content-Type
    	application/json
    Cookie
    	authelia_session=scwNUtfzIAhWsjPrFNkwTKMpjWqdvcBh
    DNT
    	1
    Host
    	files.example.com
    Origin
    	https://files.example.com
    Pragma
    	no-cache
    Referer
    	https://files.example.com/oauth_callback?code=98LZYQV6M4gyhpcP-N88j7lDN1SaCaCQS6s4upaUbyM.FzOmEjs8lLrvVGTP9NTHz3VnMeslApdJ0tNT5ffTcaE&scope=openid+groups+profile+email&state=NVBOS1MzQzNURDA0VlUzUDJJV1hLUlpMNDpnNXdIMzZud2NMVUdRRkx2b1JjZzA5Z09Lc2tKQVJTby9XWnpwMldWMkRZPQ%3D%3D
    Sec-Fetch-Dest
    	empty
    Sec-Fetch-Mode
    	cors
    Sec-Fetch-Site
    	same-origin
    TE
    	trailers
    User-Agent
    	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0

Cookie “token” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite utils.ts:68:2
```

Authelia, although on loglevel `debug`, does not show any errors. I would not cancel an issue on their side (it's still a Beta), but GitLab is working fine with Authelia.

## Possible Solution

I have no idea.

## Steps to Reproduce (for bugs)

1. Start Authelia as an OIDC provider
2. Set the following ENV variables for MinIO

``` yaml
---
kind: ConfigMap
apiVersion: v1

metadata:
  name: environment

immutable: true

data:
  MINIO_ROOT_USER: georg
  MINIO_IDENTITY_OPENID_SCOPES:       openid,groups,profile,email
  MINIO_IDENTITY_OPENID_CLIENT_ID:    minio
  MINIO_IDENTITY_OPENID_CONFIG_URL:   https://auth.example.com/.well-known/openid-configuration
  MINIO_IDENTITY_OPENID_REDIRECT_URI: https://files.example.com/oauth_callback

---
apiVersion: v1
kind: Secret

metadata:
  name: secrets

type: Opaque
immutable: true

data:
  MINIO_ROOT_PASSWORD: >-
    nope

  MINIO_IDENTITY_OPENID_CLIENT_SECRET: >-
    nopeAgain

```

3. Start the login process

![Screenshot 2021-07-15 at 15-03-54 MinIO Console](https://user-images.githubusercontent.com/44545919/125792976-c144a76a-e034-4490-a56f-3c94a57dfaeb.png)

![Screenshot 2021-07-15 at 15-04-10 Login - Authelia](https://user-images.githubusercontent.com/44545919/125792983-2ccbe2a7-46f1-44f3-9cdc-c44939aa0d27.png)

4. Click on `Login with SSO` and the `Accept`.
4. Receive the error

## Context

Trying to get OIDC SSO working. OIDC identity provider seems to be working, at least with other applications.

## Regression

Not sure.

## Your Environment

* Version used (`minio --version`): `RELEASE.2021-07-12T02-44-53Z`
* Operating System and version (`uname -a`): Ubuntu 20.04 Host, K3OS for the VM on which the K3s cluster is running
* Server setup and configuration: The complete K8s manifest

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: fileserver
---
apiVersion: v1
data:
  MINIO_IDENTITY_OPENID_CLIENT_ID: minio
  MINIO_IDENTITY_OPENID_CONFIG_URL: https://auth.example.com/.well-known/openid-configuration
  MINIO_IDENTITY_OPENID_REDIRECT_URI: https://files.example.com/oauth_callback
  MINIO_IDENTITY_OPENID_SCOPES: openid,groups,profile,email
  MINIO_ROOT_USER: georg
immutable: true
kind: ConfigMap
metadata:
  name: environment
  namespace: fileserver
---
apiVersion: v1
data:
  MINIO_IDENTITY_OPENID_CLIENT_SECRET: nopeAgain
  MINIO_ROOT_PASSWORD: nope
immutable: true
kind: Secret
metadata:
  name: secrets
  namespace: fileserver
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: minio
  name: minio
  namespace: fileserver
spec:
  clusterIP: None
  ports:
  - name: minio
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: minio
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: fileserver
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fileserver
  namespace: fileserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
        app.traefik.io/communication: "true"
    spec:
      containers:
      - args:
        - server
        - /data
        - --anonymous
        - --address
        - :9090
        - --console-address
        - :8080
        envFrom:
        - configMapRef:
            name: environment
        - secretRef:
            name: secrets
        image: docker.io/minio/minio:RELEASE.2021-07-12T02-44-53Z
        imagePullPolicy: IfNotPresent
        name: minio
        ports:
        - containerPort: 9000
          name: minio
          protocol: TCP
        resources:
          limits:
            cpu: 150m
            memory: 250Mi
          requests:
            cpu: 10m
            memory: 100Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsGroup: 65532
          runAsNonRoot: true
          runAsUser: 65532
        volumeMounts:
        - mountPath: /data
          name: data
          readOnly: false
          subPath: data
        - mountPath: /.minio
          name: data
          readOnly: false
          subPath: config
      restartPolicy: Always
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: data
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: fileserver
  namespace: fileserver
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`files.example.com`)
    services:
    - name: minio
      namespace: fileserver
      port: 8080
      scheme: http
  tls:
    options:
      name: strict
      namespace: ingress
    store:
      name: default
```

Side-question: I do not see a password login anymore when using OIDC. Is this intended? I cannot login as admin anymore, right, or am I missing something here?
