### ISSUE TITLE
Settings alias works, but then using it doesn't

### ISSUE THREAD

**Issue by georglauterbach** [minio/minio#12793]
Note: I was trying to find something about this in the docs. #7936 is the same error, but I checked that the `passHostHeader` is enabled.

I'm using MinIO `RELEASE.2021-07-22T05-23-32Z` with Authelia as my OIDC provider. When I try to set an alias with

``` BASH
$ mc alias set georg https://subdomain.example.tld --api S3v4
mc: Configuration written to `/root/.mc/config.json`. Please update your access credentials.
mc: Successfully created `/root/.mc/share`.
mc: Initialized share uploads `/root/.mc/share/uploads.json` file.
mc: Initialized share downloads `/root/.mc/share/downloads.json` file.
Enter Access Key: georg
Enter Secret Key:
Added `georg` successfully.
```

it works, but then, using it doesn't:

``` BASH
$ mc ls georg
mc: <ERROR> Unable to list folder. The request signature we calculated does not match the signature you provided. Check your key and signing method.
```

## Expected Behavior

I should see my buckets.

## Current Behavior

Authentication does not seem to work and throws errors. Weirdly enough, there is nothing in the logs... The only lines I see in the log are:

``` INI
API: http://10.0.0.226:9090 http://127.0.0.1:9090
Console:
Documentation: https://docs.min.io
original error -> (admin_info.go:798: The Access Key Id you provided does not exist in our records.)
original error -> (user_buckets.go:125: error server side encryption configuration not found)
friendly error: The server side encryption configuration was not found
```

I'm unsure as to why the line with `Console:` has no addresses, because the webUI seems to work fine.

<details>
<summary><b>When enabling `--debug`</b>, the request looks like this:</summary>
<br>

mc: \<DEBUG\> GET / HTTP/1.1
Host: subdomain.example.tld
User-Agent: MinIO (linux; amd64) minio-go/v7.0.11 mc/RELEASE.2021-06-13T17-48-22Z
Authorization: AWS4-HMAC-SHA256 Credential=georg/20210726/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20210726T133355Z
Accept-Encoding: gzip

mc: \<DEBUG\> HTTP/1.1 403 Forbidden
Content-Length: 334
Accept-Ranges: bytes
Alt-Svc: h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400, h3=":443"; ma=86400
Cf-Cache-Status: DYNAMIC
Cf-Ray: 674e00a64e704ee5-FRA
Connection: keep-alive
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Mon, 26 Jul 2021 13:33:55 GMT
Expect-Ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Nel: {"report_to":"cf-nel","max_age":604800}
Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=7Cm0nmPWMWTkllcG7UqKXJUr0%2BOa7DQdLcjRMZDsyO5UrrfyN12zufdPNKyhmI%2Bk5oh%2FKQY9mnQvAEcPvDNjYQ1pa5vkzCC2C4a4GnKILMvendMDsdxrVY7ukGFJutQIXFi7xK1liJFFGOZm"}],"group":"cf-nel","max_age":604800}
Server: cloudflare
Strict-Transport-Security: max-age=15552000; includeSubDomains; preload
Vary: Origin
Vary: Accept-Encoding
X-Amz-Request-Id: 16955A94D47C91BD
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-Xss-Protection: 1; mode=block

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><Resource>/</Resource><RequestId>16955A94D47C91BD</RequestId><HostId>d49c5385-8637-41db-be42-945861d14111</HostId></Error>mc: <DEBUG> TLS Certificate found:
mc: <DEBUG>  >> Country: US
mc: <DEBUG>  >> Organization: Cloudflare, Inc.
mc: <DEBUG>  >> Expires: 2022-06-16 23:59:59 +0000 UTC
mc: <DEBUG> TLS Certificate found:
mc: <DEBUG>  >> Country: IE
mc: <DEBUG>  >> Organization: Baltimore
mc: <DEBUG>  >> Expires: 2024-12-31 23:59:59 +0000 UTC
mc: <DEBUG> Response Time:  129.189249ms

mc: <ERROR> Unable to list folder. The request signature we calculated does not match the signature you provided. Check your key and signing method.
 (1) ls.go:239 cmd.doList(..) Tags: [https://subdomain.example.tld/]
 (0) client-s3.go:2001 cmd.(*S3Client).listInRoutine(..)
 Commit:2c52cdf27c7b | Release-Tag:RELEASE.2021-06-13T17-48-22Z | Host:975c31888398 | OS:linux | Arch:amd64 | Lang:go1.16.5 | Mem:2.2 MB/76 MB | Heap:2.2 MB/66 MB

</details>

Not using `--api S3v4` leads to:

``` BASH
$ mc alias set georg https://files.georglauterbach.com
Enter Access Key: georg
Enter Secret Key:
mc: <ERROR> Unable to initialize new alias from the provided credentials. The request signature we calculated does not match the signature you provided. Check your key and signing method.
```

which is the same error?

## Possible Solution

No idea.

## Steps to Reproduce (for bugs)

0. Set up an external identity provider
1. Set an alias with `--api S3v4`
2. Try to use it

## Context

Everything seems to work, except the `mc` client.

## Regression

Not sure.

## Your Environment

* Version used (`minio --version`): MinIO `RELEASE.2021-07-22T05-23-32Z`, `mc` version `RELEASE.2021-06-13T17-48-22Z`
* Server setup and configuration:

The deployment:

``` YAML
---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: fileserver

spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio

  template:
    metadata:
      labels:
        app: minio
        app.traefik.io/communication: 'true'

      annotations:
        container.apparmor.security.beta.kubernetes.io/minio: runtime/default

    spec:
      containers:
        - name: minio
          image: docker.io/minio/minio:RELEASE.2021-07-22T05-23-32Z
          imagePullPolicy: IfNotPresent

          args:
            - server
            - /data
            - --address
            - :9090
            - --console-address
            - 0.0.0.0:8080
            # - --anonymous

          # securityContext:
          #   allowPrivilegeEscalation: false
          #   readOnlyRootFilesystem: true
          #   runAsUser: 65532
          #   runAsGroup: 65532
          #   runAsNonRoot: true
          #   privileged: false
          #   capabilities:
          #     drop: [ALL]
          #   seccompProfile:
          #     type: RuntimeDefault

          resources:
            limits:
              memory: 250Mi
              cpu: 150m
            requests:
              memory: 100Mi
              cpu: 10m

          volumeMounts:
            - name: data
              mountPath: /data
              subPath: data
              readOnly: false
            - name: data
              mountPath: /.minio
              subPath: config
              readOnly: false

          ports:
            - name: web-interface
              containerPort: 8080
              protocol: TCP
            - name: api
              containerPort: 9090
              protocol: TCP

          envFrom:
            - configMapRef:
                name: environment
            - secretRef:
                name: secrets

      restartPolicy: Always

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
```

The environment variables

``` YAML
---
kind: ConfigMap
apiVersion: v1

metadata:
  name: environment

immutable: true

data:
  MINIO_ROOT_USER: root
  MINIO_IDENTITY_OPENID_SCOPES: openid,groups,profile,email
  MINIO_IDENTITY_OPENID_CLIENT_ID: minio
  MINIO_IDENTITY_OPENID_CLAIM_NAME: groups
  MINIO_IDENTITY_OPENID_CONFIG_URL: https://subdomain.example.tld/.well-known/openid-configuration
  MINIO_IDENTITY_OPENID_REDIRECT_URI: https://subdomain-ui.example.tld/oauth_callback

  MINIO_SERVER_URL: https://subdomain.example.tld
  MINIO_BROWSER_REDIRECT_URL: https://subdomain-ui.example.tld

  MINIO_HTTP_TRACE: /dev/stdout
  MINIO_REGION: Europe/Germany/Dresden
```

Traefik's ingress route

``` YAML
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute

metadata:
  name: fileserver-api

spec:
  entryPoints: [websecure]

  routes:
    - kind: Rule
      match: Host(`subdomain.example.tld`)

      services:
        - name: minio
          namespace: fileserver
          port: 9090
          scheme: http
          passHostHeader: true

  tls:
    store:
      name: default
    options:
      name: strict
      namespace: ingress

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute

metadata:
  name: fileserver-web-ui

spec:
  entryPoints: [websecure]

  routes:
    - kind: Rule
      match: Host(`subdomain-ui.example.tld`)

      services:
        - name: minio
          namespace: fileserver
          port: 8080
          scheme: http
          passHostHeader: true

  tls:
    store:
      name: default
    options:
      name: strict
      namespace: ingress

```

* Operating System and version (`uname -a`): Host `Ubuntu 20.04.1`
