### ISSUE TITLE
Docker image contains some duplicated files according to dive

### ISSUE THREAD

**Issue by 030** [minio/minio#12799]
We run wagoodman/dive in our pipeline and it seems that some files are duplicated in the Dockerfile.

```
$ CI=true dive docker-archive:///tmp/${CI_PROJECT_NAME}.tar
  Using default CI config
Image Source: docker-archive:///tmp/minio.tar
Fetching image... (this can take a while for large images)
Analyzing image...
  efficiency: 95.6153 %
  wastedBytes: 14392235 bytes (14 MB)
  userWastedPercent: 17.6951 %
Inefficient Files:
Count  Wasted Space  File Path
    2         10 MB  /var/lib/rpm/Packages
    2        1.6 MB  /var/lib/rpm/__db.003
    2        950 kB  /var/lib/rpm/Basenames
    2        541 kB  /var/lib/rpm/__db.001
    2        364 kB  /var/lib/rpm/Dirnames
    2        164 kB  /var/lib/rpm/__db.002
    2        131 kB  /var/lib/rpm/Providename
    2         90 kB  /var/lib/rpm/Requirename
    2         33 kB  /var/lib/rpm/Sha1header
    2         25 kB  /var/lib/rpm/Sigmd5
    2         20 kB  /etc/ld.so.cache
    2         16 kB  /var/lib/rpm/Obsoletename
    2         16 kB  /var/lib/rpm/Group
    2         16 kB  /var/lib/rpm/Name
    2         16 kB  /var/lib/rpm/Conflictname
    2         16 kB  /var/lib/rpm/Recommendname
    2         16 kB  /var/lib/rpm/Installtid
    2        4.9 kB  /etc/yum.repos.d/ubi.repo
    2         554 B  /etc/group
    2         418 B  /etc/gshadow
Results:
  FAIL: highestUserWastedPercent: too many bytes wasted, relative to the user bytes added (%-user-wasted-bytes=0.17695071825917172 > threshold=0.1)
  SKIP: highestWastedBytes: rule disabled
  PASS: lowestEfficiency
```

**Comment by harshavardhana** [comment]
MinIO docker container is based on RedHat UBI image there is nothing we can do to purge these entries.

Nothing to do with MinIO containers they are fine as is.

**Comment by 030** [comment]
Current:

```
Fetching image... (this can take a while for large images)
Analyzing image...
  efficiency: 96.1265 %
  wastedBytes: 16498952 bytes (16 MB)
  userWastedPercent: 10.5705 %

Results:
  FAIL: highestUserWastedPercent: too many bytes wasted, relative to the user bytes added (%-user-wasted-bytes=0.10570542782389454 > threshold=0.1)
  SKIP: highestWastedBytes: rule disabled
  PASS: lowestEfficiency
Result:FAIL [Total:3] [Passed:1] [Failed:1] [Warn:0] [Skipped:1]
```

Removing some duplicated files add the end of the RUN command results in:

```
Fetching image... (this can take a while for large images)
Analyzing image...
  efficiency: 96.9697 %
  wastedBytes: 9220360 bytes (9.2 MB)
  userWastedPercent: 6.1962 %

Results:
  PASS: highestUserWastedPercent
  SKIP: highestWastedBytes: rule disabled
  PASS: lowestEfficiency
Result:PASS [Total:3] [Passed:2] [Failed:0] [Warn:0] [Skipped:1]
```

Docker images should also be as lean as possible. Tools like wagoodman/dive help with this.
