### ISSUE TITLE
etcd is unreachable, please check your endpoints

### ISSUE THREAD

**Issue by DougTrajano** [minio/minio#12877]
Error: Unable to decrypt an encrypted ETCD backend for IAM users and policies: etcd is unreachable

## Expected Behavior

I expected to use **etcd** to store IAM users and policies as I'm using minIO Gateway. My goal is to setup [minIO STS (with Keycloak)](https://github.com/minio/minio/blob/master/docs/sts/keycloak.md).

## Current Behavior

I'm getting an error message that says that **etcd** is unreachable.

```
API: SYSTEM()
Time: 20:22:51 UTC 08/04/2021
DeploymentID: d28fda90-0399-453a-9fe3-fc83921ef50c
Error: Unable to decrypt an encrypted ETCD backend for IAM users and policies: etcd is unreachable, please check your endpoints [http://minio-etcd.minio:2379/] (*fmt.wrapError)
       1: cmd/iam.go:629:cmd.(*IAMSys).Init()

API: SYSTEM()
Time: 20:22:51 UTC 08/04/2021
DeploymentID: d28fda90-0399-453a-9fe3-fc83921ef50c
Error: IAM sub-system is partially initialized, some users may not be available (*errors.errorString)
       1: cmd/iam.go:630:cmd.(*IAMSys).Init()
```

If I make a curl to the **etcd** pod inside the minIO pod, I can connect with that properly.

Command: `curl http://minio-etcd.minio:2379/version`

```
{"etcdserver":"3.5.0","etcdcluster":"3.5.0"}
```

The endpoint `http://minio-etcd.minio:2379/` isn't available, I don't know if it is the error.

```
404 page not found
```

## Steps to Reproduce (for bugs)

I deployed both minIO and etcd using the bitnami helm charts.

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: minio
  labels:
    istio.io/rev: 1-10-2
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: etcd
  namespace: minio
spec:
  helmVersion: v3
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: etcd
    version: 6.2.11
  values:
    commonLabels:
      app: minio-etcd
      version: 3.5.0
    persistence:
      enabled: true
      storageClass: efs
      accessMode: ReadWriteMany
      size: 10Gi
    diagnosticMode:
      enabled: true
    podLabels:
      app: minio-etcd
      version: 3.5.0
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
    name: minio
    namespace: minio
spec:
    helmVersion: v3
    chart:
        repository: https://charts.bitnami.com/bitnami
        name: minio
        version: 7.1.6
    values:
        global:
          minio:
            existingSecret: minio-secret
        existingSecret: minio-secret
        mode: distributed
        persistence:
          enabled: false
        serviceAccount:
          name: minio-svc-account
          annotations:
            eks.amazonaws.com/role-arn: <AN-AMAZING-AWS-ARN-ROLE-HERE>
        gateway:
          sse:
            enabled: false
          enabled: true
          type: s3
          auth:
            s3:
              useIAMRole: true
        containerPort: 9000
        extraEnv:
          - name: MINIO_IDENTITY_OPENID_CONFIG_URL
            value: http://<KEYCLOAK-NAME>.<KEYCLOAK-NAMESPACE>/auth/realms/<KEYCLOAK-REALM>/.well-known/openid-configuration
          - name: MINIO_IDENTITY_OPENID_REDIRECT_URI
            value: https://<MINIO-ENDPOINT>/oauth_callback
          - name: MINIO_IDENTITY_OPENID_CLAIM_NAME
            value: minio_policies
          - name: MINIO_IDENTITY_OPENID_CLIENT_ID
            value: minio
          - name: MINIO_IDENTITY_OPENID_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: minio-auth-secret
                key: client_secret
          - name: MINIO_IDENTITY_OPENID_VENDOR
            value: keycloak
          - name: MINIO_IDENTITY_OPENID_KEYCLOAK_REALM
            value: master
          - name: MINIO_IDENTITY_OPENID_KEYCLOAK_ADMIN_URL
            value: https://<KEYCLOAK-EXTERNAL-URL>
          - name: MINIO_IDENTITY_OPENID_SCOPES
            value: openid,email,minio_policies,profile
          - name: MINIO_ETCD_ENDPOINTS
            value: http://minio-etcd.minio:2379/
```

## Your Environment

| System | Version |
| - | - |
| Istio | 1.10.2 |
| FluxCD | v1 |
| bitnami/etcd | 3.5.0-debian-10-r42 |
| bitnami/minio | 2021.6.17-debian-10-r37 |
| bitnami/minio-client | 2021.7.27-debian-10-r7
| Keycloak | 14.0.0 |

**Comment by harshavardhana** [comment]
You purge your entire etcd and re-deploy it should work fine. @DougTrajano

**Comment by DougTrajano** [comment]
> You purge your entire etcd and re-deploy it should work fine. @DougTrajano

I deleted all the resources related to my **minio-etcd** and re-deploy it again, but it stays in the same issue. :/

**Comment by harshavardhana** [comment]
> I deleted all the resources related to my **minio-etcd** and re-deploy it again, but it stays in the same issue. :/

AFAICS @DougTrajano etcd is not taking any writes we are trying to create a key on it and that's failing - you need to first check if etcd is taking writes or at least how much time it takes to write a key into etcd. 

It looks like it's beyond 30secs - since that is the deadline we have for our individual etcd API calls.

**Comment by DougTrajano** [comment]
> > I deleted all the resources related to my **minio-etcd** and re-deploy it again, but it stays in the same issue. :/
> 
> AFAICS @DougTrajano etcd is not taking any writes we are trying to create a key on it and that's failing - you need to first check if etcd is taking writes or at least how much time it takes to write a key into etcd.
> 
> It looks like it's beyond 30secs - since that is the deadline we have for our individual etcd API calls.

I'll check that

**Comment by DougTrajano** [comment]
Hey buddy, sorry for the late answer, I did some tests and changes in my deployment manifest.

<details><summary>helm charts</summary>
<p>

```yaml
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
    name: minio
    namespace: minio
spec:
    helmVersion: v3
    chart:
        repository: https://charts.bitnami.com/bitnami
        name: minio
        version: 7.1.6
    values:
        global:
          minio:
            existingSecret: minio-secret
        existingSecret: minio-secret
        mode: distributed
        persistence:
          enabled: false
        serviceAccount:
          name: minio-svc-account
          annotations:
            eks.amazonaws.com/role-arn: <AWS-ARN>
        gateway:
          sse:
            enabled: false
          enabled: true
          type: s3
          auth:
            s3:
              useIAMRole: true
        containerPort: 9000
        extraEnv:
          - name: MINIO_IDENTITY_OPENID_CONFIG_URL
            value: <KEYCLOAK-INTERNAL-URL>/realms/<KEYCLOAK-REALM>/.well-known/openid-configuration
          - name: MINIO_IDENTITY_OPENID_REDIRECT_URI
            value: <KEYCLOAK-INTERNAL-URL>/minio/oauth_callback
          - name: MINIO_IDENTITY_OPENID_CLAIM_NAME
            value: minio_policies
          - name: MINIO_IDENTITY_OPENID_CLIENT_ID
            value: minio
          - name: MINIO_IDENTITY_OPENID_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: minio-auth-secret
                key: client_secret
          - name: MINIO_IDENTITY_OPENID_VENDOR
            value: keycloak
          - name: MINIO_IDENTITY_OPENID_KEYCLOAK_REALM
            value: <KEYCLOAK-REALM>
          - name: MINIO_IDENTITY_OPENID_KEYCLOAK_ADMIN_URL
            value: <KEYCLOAK-EXTERNAL-URL>
          - name: MINIO_IDENTITY_OPENID_SCOPES
            value: openid,email,minio_policies,profile
          - name: MINIO_ETCD_ENDPOINTS
            value: http://minio-etcd.minio.svc.cluster.local:2379
          - name: MINIO_HTTP_TRACE
            value: /dev/stdout
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: etcd
  namespace: minio
spec:
  helmVersion: v3
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: etcd
    version: 6.3.3
  values:
    image:
      registry: <MY-REGISTRY>
      repository: bitnami/etcd
      tag: 3.5.0-debian-10-r42
    auth:
      rbac:
        enabled: false
        rootPassword: root
        allowNoneAuthentication: true
    commonLabels:
      app: minio-etcd
      version: 3.5.0
    persistence:
      enabled: true
      storageClass: efs
      accessMode: ReadWriteMany
      size: 20Gi
    podLabels:
      app: minio-etcd
      version: 3.5.0
```

</p>
</details>

Then, I did several troubleshooting steps that I'll describe below.

# Troubleshooting steps

## etcd configs

```yaml
...
auth:
  rbac:
    enabled: false
    rootPassword: root
    allowNoneAuthentication: true
...
```

- etcd pod: export ETCD_ROOT_USERNAME=root
- etcd pod: etcdctl put foo "bar"
   - Return: `OK` - SUCCESS
- minio pod: Install etcdctl
- minio pod: $ETCD_BIN/etcdctl put greeting "Hello, etcd" --endpoints=http://minio-etcd.minio:2379
   - Return: FAILED

```json
{
    "level": "warn",
    "ts": "2021-08-06T17:55:34.117Z",
    "logger": "etcd-client",
    "caller": "v3/retry_interceptor.go:62",
    "msg": "retrying of unary invoker failed",
    "target": "etcd-endpoints://0xc00010e380/#initially=[http://minio-etcd.minio:2379]",
    "attempt": 0,
    "error": "rpc error: code = Unavailable desc = error reading from server: EOF"
}
```

- minio pod: $ETCD_BIN/etcdctl put greeting "Hello, etcd" --endpoints=http://minio-etcd.minio:2379 --user="root:root"
   - Return: FAILED

```json
{
    "level": "warn",
    "ts": "2021-08-06T17:46:10.232Z",
    "logger": "etcd-client",
    "caller": "v3/retry_interceptor.go:62",
    "msg": "retrying of unary invoker failed",
    "target": "etcd-endpoints://0xc000620000/#initially=[http://minio-etcd.minio.svc.cluster.local:2379]",
    "attempt": 0,
    "error": "rpc error: code = Unavailable desc = error reading from server: read tcp XXX.XX.XXX.XX:XXXXX->XX.XXX.XXX.XX:2379: read: connection reset by peer"
}
```
```log
Error: rpc error: code = Unavailable desc = error reading from server: read tcp XXX.XX.XXX.XX:XXXXX->XX.XXX.XXX.XX:2379: read: connection reset by peer
```

- minio pod: $ETCD_BIN/etcdctl endpoint health
   - Return: FAILED

```json
{
    "level": "warn",
    "ts": 999999999,
    "logger": "client",
    "caller": "v3/retry_interceptor.go:62",
    "msg": "retrying of unary invoker failed",
    "target": "etcd-endpoints://0xc00031e700/#initially=[127.0.0.1:2379]",
    "attempt": 0,
    "error": "rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused\""
}
```

- etcd pod: etcdctl endpoint health
   - Return: `127.0.0.1:2379 is healthy: successfully committed proposal: took = 1.525918ms`
- minio pod: `curl -L http://minio-etcd.minio:2379/v3/kv/put -X POST -d '{"key": "Zm9v", "value": "YmFy"}'`
   - Return: SUCCESS (I can write in etcd using curl)

```json
{
    "header": {
        "cluster_id": "XX",
        "member_id": "XX",
        "revision": "4",
        "raft_term": "2"
    }
}
```

- minio pod `curl -L http://minio-etcd.minio:2379/version`
   - Return: SUCCESS

```json
{
    "etcdserver": "3.5.0",
    "etcdcluster": "3.5.0"
}
```
