### ISSUE TITLE
Error 401 in Login Console

### ISSUE THREAD

**Issue by lepuentesb** [minio/minio#12959]
## Expected Behavior
When I configure minio (docker image that also brings console) to access by https, when I want to enter with my username and password on the login page, I get the seven error message:

```
{"code": 401, "detailedMessage": "invalid Login", "message": "invalid Login"}
```

This error only happens when I enter using https and it only happens with the Console access, with http I have no problems and through minio-client I have no problems.

## Steps to Reproduce (for bugs)

1. When I configure minio (docker image that also brings console) to access by https
2. Use this configuration in the docker-compose:

```
    version: "3"

services:

  minio:
    image: minio/minio:RELEASE.2021-08-05T22-01-19Z
    volumes:
      - data1:/data
      - /etc/letsencrypt/live/domain/fullchain.pem:/root/.minio/certs/public.crt
      - /etc/letsencrypt/live/domain/privkey.pem:/root/.minio/certs/private.key
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: pass
      MINIO_SERVER_URL: https://domain:9000
    command: server --console-address ":9001" /data

volumes:
    data1:
```
## Your Environment

* Version used (`minio --version`): minio/minio:RELEASE.2021-08-05T22-01-19Z (Docker image)
* Server setup and configuration: Use Docker and docker-compose
