### ISSUE TITLE
Server expects 'storage' API version 'v39', instead found 'v39'

### ISSUE THREAD

**Issue by milanbalazs** [minio/minio#13009]
I want to use the MinIO in distributed mode with Docker Compose but I get error from MinIO. I have 2 worker nodes in my Docker Swarm to run the MinIO instances. I have 2 MinIO instances with 2 discs per node.

**Related part of my `docker-compose.yml` file:**

```
...
...
...
  object_storage_1:
    image: minio/minio:RELEASE.2021-08-17T20-53-08Z
    expose:
      - "9000"
      - "9001"
    environment:
      MINIO_ACCESS_KEY_FILE: object_storage_user
      MINIO_SECRET_KEY_FILE: object_storage_password
      MINIO_BROWSER_REDIRECT_URL: https://${SYSTEM_HOST}:9001
      MINIO_SERVER_URL: https://${SYSTEM_HOST}:9000
    command: server --console-address ":9001" http://object_storage_{1...4}/data{1...2}
    depends_on:
      - fluentd
    volumes:
      - object_storage_data_1_1:/data1
      - object_storage_data_1_2:/data2
    networks:
      - object_storage_net
    secrets:
      - object_storage_user
      - object_storage_password
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == node1
    logging:
      driver: "fluentd"
      options:
        fluentd-address: ${SYSTEM_HOST}:24224
        tag: object-storage

  object_storage_2:
    image: minio/minio:RELEASE.2021-08-17T20-53-08Z
    expose:
      - "9000"
      - "9001"
    environment:
      MINIO_ACCESS_KEY_FILE: object_storage_user
      MINIO_SECRET_KEY_FILE: object_storage_password
      MINIO_BROWSER_REDIRECT_URL: https://${SYSTEM_HOST}:9001
      MINIO_SERVER_URL: https://${SYSTEM_HOST}:9000
    command: server --console-address ":9001" http://object_storage_{1...4}/data{1...2}
    depends_on:
      - fluentd
    volumes:
      - object_storage_data_2_1:/data1
      - object_storage_data_2_2:/data2
    networks:
      - object_storage_net
    secrets:
      - object_storage_user
      - object_storage_password
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == node2
    logging:
      driver: "fluentd"
      options:
        fluentd-address: ${SYSTEM_HOST}:24224
        tag: object-storage
...
...
...
```

**The getting error:**

```
 API: SYSTEM()
 Time: 16:48:53 UTC 08/19/2021
 Error: Read failed. Insufficient number of disks online (*errors.errorString)
        5: cmd/prepare-storage.go:268:cmd.connectLoadInitFormats()
        4: cmd/prepare-storage.go:317:cmd.waitForFormatErasure()
        3: cmd/erasure-server-pool.go:90:cmd.newErasureServerPools()
        2: cmd/server-main.go:609:cmd.newObjectLayer()
        1: cmd/server-main.go:523:cmd.serverMain()
 Waiting for a minimum of 4 disks to come online (elapsed 3m31s)
 
 Unable to read 'format.json' from http://object_storage_1:9000/data1: Server expects 'storage' API version 'v39', instead found 'v39' - *rolling upgrade is not allowed* - please make sure all servers are running the same MinIO version (RELEASE.2021-08-17T20-53-08Z)
 
 Unable to read 'format.json' from http://object_storage_2:9000/data1: Server expects 'storage' API version 'v39', instead found 'v39' - *rolling upgrade is not allowed* - please make sure all servers are running the same MinIO version (RELEASE.2021-08-17T20-53-08Z)
 
 Unable to read 'format.json' from http://object_storage_3:9000/data1: Server expects 'storage' API version 'v39', instead found 'v39' - *rolling upgrade is not allowed* - please make sure all servers are running the same MinIO version (RELEASE.2021-08-17T20-53-08Z)
 
 Unable to read 'format.json' from http://object_storage_4:9000/data1: Server expects 'storage' API version 'v39', instead found 'v39' - *rolling upgrade is not allowed* - please make sure all servers are running the same MinIO version (RELEASE.2021-08-17T20-53-08Z)
 
 Unable to read 'format.json' from http://object_storage_1:9000/data2: Server expects 'storage' API version 'v39', instead found 'v39' - *rolling upgrade is not allowed* - please make sure all servers are running the same MinIO version (RELEASE.2021-08-17T20-53-08Z)
 
 Unable to read 'format.json' from http://object_storage_2:9000/data2: Server expects 'storage' API version 'v39', instead found 'v39' - *rolling upgrade is not allowed* - please make sure all servers are running the same MinIO version (RELEASE.2021-08-17T20-53-08Z)
 
 Unable to read 'format.json' from http://object_storage_3:9000/data2: Server expects 'storage' API version 'v39', instead found 'v39' - *rolling upgrade is not allowed* - please make sure all servers are running the same MinIO version (RELEASE.2021-08-17T20-53-08Z)
 
 Unable to read 'format.json' from http://object_storage_4:9000/data2: Server expects 'storage' API version 'v39', instead found 'v39' - *rolling upgrade is not allowed* - please make sure all servers are running the same MinIO version (RELEASE.2021-08-17T20-53-08Z)
```

I use the same MinIO version in my all related services and based on the error message the expected and the founded API version is the same (v39) so I don't understand what the problem can be.

Previously used MinIO image: `minio/minio:RELEASE.2020-12-10T01-54-29Z`

Could you provide a solution or hint how I can solve the above issue, please?

Thanks, 
Milan

**Comment by harshavardhana** [comment]
> I use the same MinIO version in my all related services and based on the error message the expected and the founded API version is the same (v39) so I don't understand what the problem can be.

The issue is very simple your DNS doesn't resolve properly to the hosts this happens with docker swarm where it resolves the hostnames to random IPs make sure to have 

```
object_storage_1:
    image: minio/minio:RELEASE.2021-08-17T20-53-08Z
    expose:
      - "9000"
      - "9001"
    environment:
      MINIO_ACCESS_KEY_FILE: object_storage_user
      MINIO_SECRET_KEY_FILE: object_storage_password
      MINIO_BROWSER_REDIRECT_URL: https://${SYSTEM_HOST}:9001
      MINIO_SERVER_URL: https://${SYSTEM_HOST}:9000
    command: server --console-address ":9001" http://object_storage_{1...4}/data{1...2}
    hostname: object_storage_1
    depends_on:
      - fluentd
    volumes:
      - object_storage_data_1_1:/data1
      - object_storage_data_1_2:/data2
```
