### ISSUE TITLE
Cannot set GetBucketRequestPayment in policy

### ISSUE THREAD

**Issue by Elettronik** [minio/minio#13019]
I'm using the ansible S3 client, to create a new bucket. During the process of creation, the boto client make a call that require GetBucketRequestPayment operation, and the server respond 403 AccessDenied at that request.
If I try to set that operation in a policy I receive another error about unsupported policy. 
The only workaround so far is to set the action in the policy to "s3:*" and so the server respond a dummy 202 at the client.

## Expected Behavior
 Should be possible to create a bucket  through ansible

## Current Behavior
 There is an error creating a new bucket

## Possible Solution
- GetBucketRequestPayment  is implemented in policy even if is dummy result,
- GetBucketRequestPayment return a dummy value, even if is it not specified in the permission list

## Steps to Reproduce (for bugs)

1. Create a policy with something along this lines
```
Version: "2012-10-17"
Statement:
  - Effect: "Allow"
    Action:
      - "admin:CreateServiceAccount"

  - Effect: "Allow"
    Action:
      - "s3:ListAllMyBuckets"
    Resource:
      - "arn:aws:s3:::*"

  - Effect: "Allow"
    Action:
      - "s3:CreateBucket"
      - "s3:GetBucketVersioning"
      - "s3:ListBucket"
      - "s3:HeadBucket"
    Resource:
      - "arn:aws:s3:::kaniko-*"
```
2. try to create a bucket with ansible 
```
 - name: Test functionality 1/
    amazon.aws.s3_bucket:
      s3_url: "{{ kaniko_minio_public_url }}"
      aws_access_key: "{{ kaniko_minio_access_key }}"
      aws_secret_key: "{{ kaniko_minio_secret_key }}"
      name: "{{ kaniko_minio_bucket_name }}"
      requester_pays: False
      state: present

```

* Version used (`minio --version`): latest
* Server setup and configuration: docker in k8s cluster
