### ISSUE TITLE
MinIO Helm chart - helm install stuck

### ISSUE THREAD

**Issue by alexander-bruun** [minio/minio#13048]
After adding the helm repo, I then run the helm install command with the following arguments:
![image](https://user-images.githubusercontent.com/87643857/130561541-4cc7ab6c-2eac-4104-b1d8-0b2d60aefc32.png)
It seems like it gets stuck / waiting, if you abort the command and try again, it will say a release with the name already exists, and if you try to upgrade --install it will say that the release is currently in a deploy state so you have to wait for it to finish.

After a certain amount of time it then gives the following message:
![image](https://user-images.githubusercontent.com/87643857/130561982-b1d1617f-9e72-4b0f-9ff2-899c7198d3a3.png)

And it does create the namespace:
![image](https://user-images.githubusercontent.com/87643857/130562345-be24e4aa-22e2-4935-894b-895ebb169d75.png)

And adds pods etc... to the namespace:
![image](https://user-images.githubusercontent.com/87643857/130562374-97925caf-d640-44a4-92a9-40f8a664e537.png)

So it creates the required resources, but something seems to be wrong with the helm chart. (pods are pending due to missing ram based on the helm values... is 16Gi really needed???)

## Expected Behavior

To be able to run helm install after adding the repo.

## Current Behavior

I wait for a infinite amount of time trying to install the chart.

## Possible Solution

I assume it's a helm templating issue, but am not sure.

## Steps to Reproduce (for bugs)

1. helm repo add https://charts.min.io/
2. install the chart
```
helm install minio minio/minio \
--set rootUser=rootuser \
--set rootPassword=rootpassword \
--namespace minio-ns \
--create-namespace
```
(I added --create-namespace since the command from docs will fail since namespace is not created)
3. It will then get stuck, and after a couple of minutes return "Error: failed post-install: timed out waiting for the condition"

## Context

I'm unable to use the helm chart to setup MinIO.

## Regression

Not sure since the helm chart is fairly new.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
@alexander-bruun if you want to configure less memory please do so - we are choosing production defaults. 

```
helm install minio minio/minio --set rootUser=rootuser --set rootPassword=rootpassword --set resources.requests.memory=512Mi --namespace minio-ns --create-namespace
NAME: minio
LAST DEPLOYED: Tue Aug 24 11:49:38 2021
NAMESPACE: minio-ns
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Minio can be accessed via port 9000 on the following DNS name from within your cluster:
minio.minio-ns.svc.cluster.local

To access Minio from localhost, run the below commands:

  1. export POD_NAME=$(kubectl get pods --namespace minio-ns -l "release=minio" -o jsonpath="{.items[0].metadata.name}")

  2. kubectl port-forward $POD_NAME 9000 --namespace minio-ns

Read more about port forwarding here: http://kubernetes.io/docs/user-guide/kubectl/kubectl_port-forward/

You can now access Minio server on http://localhost:9000. Follow the below steps to connect to Minio server with mc client:

  1. Download the Minio mc client - https://docs.minio.io/docs/minio-client-quickstart-guide

  2. export ACCESS_KEY=$(kubectl get secret minio -o jsonpath="{.data.rootUser}" | base64 --decode) 
  
  3. export SECRET_KEY=$(kubectl get secret minio -o jsonpath="{.data.rootPassword}" | base64 --decode)

  4. mc alias set minio-local http://localhost:9000 "$ACCESS_KEY" "$SECRET_KEY" --api s3v4

  5. mc ls minio-local

Alternately, you can use your browser or the Minio SDK to access the server - https://docs.minio.io/categories/17
```

So choose what is needed for you by modifying the `values.yaml` this is not an issue as such.

**Comment by alexander-bruun** [comment]
@harshavardhana The default ram amount was just a side-note, even when using your command with the latest minio helm chart version the install command still gets stuck and ends up giving a error, I don't see how this is working as intended...

![image](https://user-images.githubusercontent.com/87643857/130909502-e3702005-c9de-46cc-86af-13e0f2f885b3.png)

And when doing helm list:
![image](https://user-images.githubusercontent.com/87643857/130909595-b9393102-8658-4945-b922-b75d3afbfd4d.png)

**Comment by harshavardhana** [comment]
@alexander-bruun your k8s cluster seems to be broken - you need to first address that. 

On a sufficiently well-managed k8s here is the result on my end. 

```
helm install minio minio/minio --set rootUser=rootuser --set rootPassword=rootpassword --set resources.requests.memory=512Mi --namespace minio-ns --create-namespace --debug
install.go:173: [debug] Original chart version: ""
install.go:190: [debug] CHART PATH: /home/harsha/.cache/helm/repository/minio-1.0.4.tgz

client.go:128: [debug] creating 1 resource(s)
client.go:128: [debug] creating 6 resource(s)
client.go:290: [debug] Starting delete for "minio-make-user-job" Job
client.go:319: [debug] jobs.batch "minio-make-user-job" not found
client.go:128: [debug] creating 1 resource(s)
client.go:519: [debug] Watching for changes to Job minio-make-user-job with timeout of 5m0s
client.go:547: [debug] Add/Modify event for minio-make-user-job: ADDED
client.go:586: [debug] minio-make-user-job: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
client.go:547: [debug] Add/Modify event for minio-make-user-job: MODIFIED
client.go:586: [debug] minio-make-user-job: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
client.go:547: [debug] Add/Modify event for minio-make-user-job: MODIFIED
client.go:290: [debug] Starting delete for "minio-make-user-job" Job
NAME: minio
LAST DEPLOYED: Wed Aug 25 23:26:13 2021
NAMESPACE: minio-ns
STATUS: deployed
REVISION: 1
TEST SUITE: None
USER-SUPPLIED VALUES:
resources:
  requests:
    memory: 512Mi
rootPassword: rootpassword
rootUser: rootuser

COMPUTED VALUES:
DeploymentUpdate:
  maxSurge: 100%
  maxUnavailable: 0
  type: RollingUpdate
StatefulSetUpdate:
  updateStrategy: RollingUpdate
additionalAnnotations: []
additionalLabels: []
affinity: {}
bucketRoot: ""
buckets: null
certsPath: /etc/minio/certs/
clusterDomain: cluster.local
configPathmc: /etc/minio/mc/
consoleIngress:
  annotations: {}
  enabled: false
  hosts:
  - chart-example.local
  labels: {}
  path: /
  tls: []
consoleService:
  clusterIP: null
  nodePort: 32001
  port: "9001"
  type: ClusterIP
drivesPerNode: 1
environment: null
existingSecret: ""
extraArgs: []
fullnameOverride: ""
image:
  pullPolicy: IfNotPresent
  repository: minio/minio
  tag: RELEASE.2021-08-20T18-32-01Z
imagePullSecrets: []
ingress:
  annotations: {}
  enabled: false
  hosts:
  - chart-example.local
  labels: {}
  path: /
  tls: []
makeBucketJob:
  annotations: null
  podAnnotations: null
  resources:
    requests:
      memory: 128Mi
  securityContext:
    enabled: false
    fsGroup: 1000
    runAsGroup: 1000
    runAsUser: 1000
makeUserJob:
  annotations: null
  podAnnotations: null
  resources:
    requests:
      memory: 128Mi
  securityContext:
    enabled: false
    fsGroup: 1000
    runAsGroup: 1000
    runAsUser: 1000
mcImage:
  pullPolicy: IfNotPresent
  repository: minio/mc
  tag: RELEASE.2021-07-27T06-46-19Z
minioAPIPort: "9000"
minioConsolePort: "9001"
mode: distributed
mountPath: /export
nameOverride: ""
networkPolicy:
  allowExternal: true
  enabled: false
nodeSelector: {}
persistence:
  VolumeName: ""
  accessMode: ReadWriteOnce
  annotations: {}
  enabled: true
  existingClaim: ""
  size: 500Gi
  storageClass: ""
  subPath: ""
podAnnotations: {}
podDisruptionBudget:
  enabled: false
  maxUnavailable: 1
podLabels: {}
priorityClassName: ""
replicas: 4
resources:
  requests:
    memory: 512Mi
rootPassword: rootpassword
rootUser: rootuser
securityContext:
  enabled: true
  fsGroup: 1000
  runAsGroup: 1000
  runAsUser: 1000
service:
  clusterIP: null
  nodePort: 32000
  port: "9000"
  type: ClusterIP
tls:
  certSecret: ""
  enabled: false
  privateKey: private.key
  publicCrt: public.crt
tolerations: []
trustedCertsSecret: ""
users:
- accessKey: console
  policy: consoleAdmin
  secretKey: console123
zones: 1

HOOKS:
---
# Source: minio/templates/post-install-create-user-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: minio-make-user-job
  labels:
    app: minio-make-user-job
    chart: minio-1.0.4
    release: minio
    heritage: Helm
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  template:
    metadata:
      labels:
        app: minio-job
        release: minio
    spec:
      restartPolicy: OnFailure      
      volumes:
        - name: minio-configuration
          projected:
            sources:
            - configMap:
                name: minio
            - secret:
                name: minio
      containers:
      - name: minio-mc
        image: "minio/mc:RELEASE.2021-07-27T06-46-19Z"
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "/config/add-user"]
        env:
          - name: MINIO_ENDPOINT
            value: minio
          - name: MINIO_PORT
            value: "9000"
        volumeMounts:
          - name: minio-configuration
            mountPath: /config
        resources:
          requests:
            memory: 128Mi
MANIFEST:
---
# Source: minio/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: minio
  labels:
    app: minio
    chart: minio-1.0.4
    release: minio
    heritage: Helm
type: Opaque
data:
  rootUser: "cm9vdHVzZXI="
  rootPassword: "cm9vdHBhc3N3b3Jk"
---
# Source: minio/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio
  labels:
    app: minio
    chart: minio-1.0.4
    release: minio
    heritage: Helm
data:
  initialize: |-
    #!/bin/sh
    set -e ; # Have script exit in the event of a failed command.
    MC_CONFIG_DIR="/etc/minio/mc/"
    MC="/usr/bin/mc --insecure --config-dir ${MC_CONFIG_DIR}"
    
    # connectToMinio
    # Use a check-sleep-check loop to wait for Minio service to be available
    connectToMinio() {
      SCHEME=$1
      ATTEMPTS=0 ; LIMIT=29 ; # Allow 30 attempts
      set -e ; # fail if we can't read the keys.
      ACCESS=$(cat /config/rootUser) ; SECRET=$(cat /config/rootPassword) ;
      set +e ; # The connections to minio are allowed to fail.
      echo "Connecting to Minio server: $SCHEME://$MINIO_ENDPOINT:$MINIO_PORT" ;
      MC_COMMAND="${MC} config host add myminio $SCHEME://$MINIO_ENDPOINT:$MINIO_PORT $ACCESS $SECRET" ;
      $MC_COMMAND ;
      STATUS=$? ;
      until [ $STATUS = 0 ]
      do
        ATTEMPTS=`expr $ATTEMPTS + 1` ;
        echo \"Failed attempts: $ATTEMPTS\" ;
        if [ $ATTEMPTS -gt $LIMIT ]; then
          exit 1 ;
        fi ;
        sleep 2 ; # 1 second intervals between attempts
        $MC_COMMAND ;
        STATUS=$? ;
      done ;
      set -e ; # reset `e` as active
      return 0
    }
    
    # checkBucketExists ($bucket)
    # Check if the bucket exists, by using the exit code of `mc ls`
    checkBucketExists() {
      BUCKET=$1
      CMD=$(${MC} ls myminio/$BUCKET > /dev/null 2>&1)
      return $?
    }
    
    # createBucket ($bucket, $policy, $purge)
    # Ensure bucket exists, purging if asked to
    createBucket() {
      BUCKET=$1
      POLICY=$2
      PURGE=$3
      VERSIONING=$4
    
      # Purge the bucket, if set & exists
      # Since PURGE is user input, check explicitly for `true`
      if [ $PURGE = true ]; then
        if checkBucketExists $BUCKET ; then
          echo "Purging bucket '$BUCKET'."
          set +e ; # don't exit if this fails
          ${MC} rm -r --force myminio/$BUCKET
          set -e ; # reset `e` as active
        else
          echo "Bucket '$BUCKET' does not exist, skipping purge."
        fi
      fi
    
      # Create the bucket if it does not exist
      if ! checkBucketExists $BUCKET ; then
        echo "Creating bucket '$BUCKET'"
        ${MC} mb myminio/$BUCKET
      else
        echo "Bucket '$BUCKET' already exists."
      fi
    
    
      # set versioning for bucket
      if [ ! -z $VERSIONING ] ; then
        if [ $VERSIONING = true ] ; then
            echo "Enabling versioning for '$BUCKET'"
            ${MC} version enable myminio/$BUCKET
        elif [ $VERSIONING = false ] ; then
            echo "Suspending versioning for '$BUCKET'"
            ${MC} version suspend myminio/$BUCKET
        fi
      else
          echo "Bucket '$BUCKET' versioning unchanged."
      fi
    
      # At this point, the bucket should exist, skip checking for existence
      # Set policy on the bucket
      echo "Setting policy of bucket '$BUCKET' to '$POLICY'."
      ${MC} policy set $POLICY myminio/$BUCKET
    }
    
    # Try connecting to Minio instance
    scheme=http
    connectToMinio $scheme
    
    
    
  add-user: |-
    #!/bin/sh
    set -e ; # Have script exit in the event of a failed command.
    MC_CONFIG_DIR="/etc/minio/mc/"
    MC="/usr/bin/mc --insecure --config-dir ${MC_CONFIG_DIR}"
    
    # connectToMinio
    # Use a check-sleep-check loop to wait for Minio service to be available
    connectToMinio() {
      SCHEME=$1
      ATTEMPTS=0 ; LIMIT=29 ; # Allow 30 attempts
      set -e ; # fail if we can't read the keys.
      ACCESS=$(cat /config/rootUser) ; SECRET=$(cat /config/rootPassword) ;
      set +e ; # The connections to minio are allowed to fail.
      echo "Connecting to Minio server: $SCHEME://$MINIO_ENDPOINT:$MINIO_PORT" ;
      MC_COMMAND="${MC} config host add myminio $SCHEME://$MINIO_ENDPOINT:$MINIO_PORT $ACCESS $SECRET" ;
      $MC_COMMAND ;
      STATUS=$? ;
      until [ $STATUS = 0 ]
      do
        ATTEMPTS=`expr $ATTEMPTS + 1` ;
        echo \"Failed attempts: $ATTEMPTS\" ;
        if [ $ATTEMPTS -gt $LIMIT ]; then
          exit 1 ;
        fi ;
        sleep 2 ; # 1 second intervals between attempts
        $MC_COMMAND ;
        STATUS=$? ;
      done ;
      set -e ; # reset `e` as active
      return 0
    }
    
    # checkUserExists ($username)
    # Check if the user exists, by using the exit code of `mc admin user info`
    checkUserExists() {
      USER=$1
      CMD=$(${MC} admin user info myminio $USER > /dev/null 2>&1)
      return $?
    }
    
    # createUser ($username, $password, $policy)
    createUser() {
      USER=$1
      PASS=$2
      POLICY=$3
    
      # Create the user if it does not exist
      if ! checkUserExists $USER ; then
        echo "Creating user '$USER'"
        ${MC} admin user add myminio $USER $PASS
      else
        echo "User '$USER' already exists."
      fi
    
    
      # set policy for user
      if [ ! -z $POLICY -a $POLICY != " " ] ; then
          echo "Adding policy '$POLICY' for '$USER'"
          ${MC} admin policy set myminio $POLICY user=$USER
      else
          echo "User '$USER' has no policy attached."
      fi
    }
    
    # Try connecting to Minio instance
    scheme=http
    connectToMinio $scheme
    
    
    # Create the users
    createUser console console123 consoleAdmin
---
# Source: minio/templates/console-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: minio-console
  labels:
    app: minio
    chart: minio-1.0.4
    release: minio
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9001
      protocol: TCP
      targetPort: 9001
  selector:
    app: minio
    release: minio
---
# Source: minio/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    app: minio
    chart: minio-1.0.4
    release: minio
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: minio
    release: minio
---
# Source: minio/templates/statefulset.yaml
apiVersion: v1
kind: Service
metadata:
  name: minio-svc
  labels:
    app: minio
    chart: minio-1.0.4
    release: "minio"
    heritage: "Helm"
spec:
  publishNotReadyAddresses: true
  clusterIP: None
  ports:
    - name: http
      port: 9000
      protocol: TCP
  selector:
    app: minio
    release: minio
---
# Source: minio/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  labels:
    app: minio
    chart: minio-1.0.4
    release: minio
    heritage: Helm
spec:
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: "Parallel"
  serviceName: minio-svc
  replicas: 4
  selector:
    matchLabels:
      app: minio
      release: minio
  template:
    metadata:
      name: minio
      labels:
        app: minio
        release: minio
      annotations:
        checksum/secrets: 036f3e9f7ca3b2b0d25d701c386328aaa8bb349c9529177bcbd7a699b4d93ca9
        checksum/config: 60ae8cd023c9887cf76a5b35a0a2360df83be4b40aaa63fa637c9f4a72f5d483
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: minio
          image: minio/minio:RELEASE.2021-08-20T18-32-01Z
          imagePullPolicy: IfNotPresent

          command: [ "/bin/sh",
            "-ce",
            "/usr/bin/docker-entrypoint.sh minio -S /etc/minio/certs/ server --address :9000 --console-address :9001  http://minio-{0...3}.minio-svc.minio-ns.svc.cluster.local/export" ]
          volumeMounts:
            - name: export
              mountPath: /export            
          ports:
            - name: http
              containerPort: 9000
            - name: http-console
              containerPort: 9001
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio
                  key: rootUser
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio
                  key: rootPassword
          resources:
            requests:
              memory: 512Mi      
      volumes:
        - name: minio-user
          secret:
            secretName: minio        
  volumeClaimTemplates:
    - metadata:
        name: export
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 500Gi

NOTES:
Minio can be accessed via port 9000 on the following DNS name from within your cluster:
minio.minio-ns.svc.cluster.local

To access Minio from localhost, run the below commands:

  1. export POD_NAME=$(kubectl get pods --namespace minio-ns -l "release=minio" -o jsonpath="{.items[0].metadata.name}")

  2. kubectl port-forward $POD_NAME 9000 --namespace minio-ns

Read more about port forwarding here: http://kubernetes.io/docs/user-guide/kubectl/kubectl_port-forward/

You can now access Minio server on http://localhost:9000. Follow the below steps to connect to Minio server with mc client:

  1. Download the Minio mc client - https://docs.minio.io/docs/minio-client-quickstart-guide

  2. export ACCESS_KEY=$(kubectl get secret minio -o jsonpath="{.data.rootUser}" | base64 --decode) 
  
  3. export SECRET_KEY=$(kubectl get secret minio -o jsonpath="{.data.rootPassword}" | base64 --decode)

  4. mc alias set minio-local http://localhost:9000 "$ACCESS_KEY" "$SECRET_KEY" --api s3v4

  5. mc ls minio-local

Alternately, you can use your browser or the Minio SDK to access the server - https://docs.minio.io/
```
