### ISSUE TITLE
ingress issue

### ISSUE THREAD

**Issue by jr0dd** [minio/minio#13068]
I just wanted to report that when using the helm chart to deploy, it is assigning the main minio port and not the minio-console port for the ingress. One has to manually patch the ingress to get it to load the console.

**Comment by harshavardhana** [comment]
@jr0dd can you provide more information?  - we can fix it right away.

**Comment by jr0dd** [comment]
```

~ % kubectl get svc -n minio
NAME            TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
minio-console   ClusterIP   172.17.54.227    <none>        9001/TCP   7m8s
minio           ClusterIP   172.17.186.180   <none>        9000/TCP   7m8s
```

```

spec:
  ingressClassName: traefik
  rules:
  - host: minio.domain.tld
    http:
      paths:
      - backend:
          service:
            name: minio
            port:
              number: 9001
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - minio.domain.tld
    secretName: minio-tls
```
Here's some output from the services and ingress. The ingress is using the port `minio` instead of `minio-console`. This was configured under consoleIngress.
