### ISSUE TITLE
Minio make buckets Public - Kubernetes

### ISSUE THREAD

**Issue by Sam-Sundar** [minio/minio#13077]
Hey Devs,

We have a requirement where we have multiple `pods` of Minio in our cluster and we would like to make it public, but seems like if we run below command only one pod's resources are public, when user hits the URL again and when another pod is being served the traffic, it's still private.

```bash
mc policy set download minio/bucket
mc policy set public minio/bucket
```

So we thought of having mc client in our volume and running these commands to make it public during `pod` start, but once minio starts it's not letting bash run any other commands.
```yaml
          command: ["/bin/sh"]
          args:
           - "-c"
           - "sh -x /usr/bin/docker-entrypoint.sh && echo Public && chmod +x /storage/mc && ls -lrth /storage/ && minio server /storage && /storage/mc alias set minio http://localhost:9000 minio minio123 --api S3v4 && /storage/mc policy set download minio/bucket1 && /storage/mc policy set public minio/bucket1 && /storage/mc policy set download minio/bucket2 && /storage/mc policy set public minio/bucket2"
```
Below are the logs where we can see every commands are running before `minio server /storage` command where minio is getting initialized.

```bash
+ docker_kms_secret_encryption_env
+ '[' -f kms_master_key ']'
+ KMS_SECRET_KEY_FILE=/run/secrets/kms_master_key
+ '[' -f /run/secrets/kms_master_key ']'
+ docker_switch_user
+ '[' '!' -z '' ']'
+ exec
Public
total 21M
-rwxr-xr-x  1 root root  21M Aug 24 16:49 mc
WARNING: MINIO_ACCESS_KEY and MINIO_SECRET_KEY are deprecated.
         Please use MINIO_ROOT_USER and MINIO_ROOT_PASSWORD

 You are running an older version of MinIO released 2 months ago 
 Update: Run `mc admin update` 


Endpoint: http://10.1.137.44:9000  http://127.0.0.1:9000     

Browser Access:
   http://10.1.137.44:9000  http://127.0.0.1:9000    

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
IAM initialization complete
root@ip-10-0-1-127:/home/ubuntu#
```
Is there anyother way to make the buckets public during the deployment start itself or is there anyway where policy.json can be copied into the pod to make it public ?
