### ISSUE TITLE
add servicemonitor to chart

### ISSUE THREAD

**Issue by jr0dd** [minio/minio#13093]
It would be nice if the chart included a servicemonitor to scrape metrics or at least the ability to easily deploy one from a manifest. I did manage to deploy one, but had to patch both services because the labels are the same on the minio service and console service. I added a component label to differentiate the 2 for each service. Or if you prefer I can whip up a PR this weekend. 

For example:

minio service
```
labels:
  app: minio
  app.kubernetes.io/component: minio
  release: minio
```

console service
```
labels:
  app: minio
  app.kubernetes.io/component: console
  release: minio
```

servicemonitor
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: minio
  namespace: minio
  labels:
    app.kubernetes.io/name: minio
spec:
  endpoints:
    - port: http
      path: /minio/v2/metrics/cluster
      interval: 10s
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - minio
  selector:
    matchLabels:
      app.kubernetes.io/component: minio
```
