### ISSUE TITLE
user and password not parsed from ETCD endpoint url

### ISSUE THREAD

**Issue by msevastian** [minio/minio#13123]
We are trying to use ETCD as a backend for users and policies from external provider DBaaS
[https://compose.com/databases/etcd](https://compose.com/databases/etcd)
and having issues when ETCD endpoint has user/password in it
https://user:pass@portal1638-0.intrepid-etcd-23.113213133.composedb.com:18884
Checks with local ETCD without authorization has no errors

## Expected Behavior
Connection to ETCD cluster should happen with no issues when ETCD entrypoint has user/pass in it

## Current Behavior

```
azure-gateway    | 
azure-gateway    | API: SYSTEM()
azure-gateway    | Time: 23:10:47 UTC 08/31/2021
azure-gateway    | DeploymentID: d497b571-7b18-4d6d-8e12-6e71520d4cb4
azure-gateway    | Error: Unable to decrypt an encrypted ETCD backend for IAM users and policies: unexpected error etcdserver: user name is empty from etcd, please check your endpoints [http://root:test123456@etcd:2379] (*fmt.wrapError)
azure-gateway    |        1: cmd/iam.go:611:cmd.(*IAMSys).Init()
azure-gateway    |
azure-gateway    | API: SYSTEM()
azure-gateway    | Time: 23:10:47 UTC 08/31/2021
azure-gateway    | DeploymentID: d497b571-7b18-4d6d-8e12-6e71520d4cb4
azure-gateway    | Error: IAM sub-system is partially initialized, some users may not be available (*errors.errorString)
azure-gateway    |        1: cmd/iam.go:612:cmd.(*IAMSys).Init()
azure-gateway    | API: http://172.22.0.3:9000  http://127.0.0.1:9000 
azure-gateway    | 
azure-gateway    | Console: http://172.22.0.3:9001 http://127.0.0.1:9001
azure-gateway    |
azure-gateway    | Documentation: https://docs.min.io
```

## Possible Solution
it looks like the pkg/net [https://github.com/minio/pkg/tree/main/net](https://github.com/minio/pkg/tree/main/net) doesn't parse user/password from URL

## Steps to Reproduce (for bugs)
1) Create azure storage account minio1 (name shown for the reference)
2) Save next docker compose file
```
version: "3.7"

networks:
  app-tier:
    driver: bridge

services:

  etcd:
    container_name: etcd
    image: 'bitnami/etcd:3.5.0'
    environment:
      - ETCD_ROOT_PASSWORD=test123456
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - 2379:2379
      - 2380:2380
    networks:
      - app-tier

  minio-gateway:
    image: minio/minio:RELEASE.2021-08-31T05-46-54Z
    command: gateway azure --console-address ":9001"
    container_name: azure-gateway
    environment:
      AZURE_STORAGE_ACCOUNT: minio1
      AZURE_STORAGE_KEY: ##STORACC_KEY##
      MINIO_ROOT_USER: minioroot
      MINIO_ROOT_PASSWORD: minioroot1234567
      MINIO_ETCD_PATH_PREFIX: "minio"
      MINIO_ETCD_ENDPOINTS: "http://root:test123456@etcd:2379"
      ports:
      - 9000:9000
      - 9001:9001
    networks:
      - app-tier
```
3) `docker-compose up --force-recreate etcd`
4) Wait for etcd to start
5) Provision etcd root user and enable auth
```
docker exec -it etcd etcdctl user add root:test123456
docker exec -it etcd etcdctl user grant-role root root
docker exec -it etcd etcdctl auth enable
```
6) Run minio-gateway `docker-compose up minio-gateway`

## Context
Currently that issue blocks usage of minio ETCD as we need authorized access to it.

## Regression
No

## Your Environment
* Version used : minio/minio:RELEASE.2021-08-31T05-46-54Z
* Server setup and configuration: Compose.com (etcd 3.4.10) + Azure Cloud
* Operating System and version: Windows 10 (19042.084) + WSL2
