### ISSUE TITLE
Unable to enable auto encryption

### ISSUE THREAD

**Issue by steschuser** [minio/minio#13161]
Although I followed the tutorial and only use the https://play.min.io:7373 endpoint, auto encryption does not work

## Expected Behavior
Setting mc encrypt set sse-s3 ALIAS/BUCKET returns without error

## Current Behavior
```
mc encrypt set sse-s3 ALIAS/BUCKET

mc: <ERROR> Unable to enable auto encryption. The request signature we calculated does not match the signature you provided. Check your key and signing method.
```
## Steps to Reproduce (for bugs)
The following docker-compose
```
services:
  minio:
          #image: minio/minio:latest
    image: minio/minio:RELEASE.2021-08-25T00-41-18Z
    volumes:
      - /etc/ssl/domain/certs:/root/.minio/certs  # Our SSL Certs
      - /root/play_kes:/kes/ # The Root idenity for play.min.io
      - /srv/data01:/data01 # Some mountpoint
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_KMS_KES_ENDPOINT: "https://play.min.io:7373"
      MINIO_KMS_KES_KEY_FILE: /kes/root.key
      MINIO_KMS_KES_CERT_FILE: /kes/root.cert
      MINIO_KMS_KES_KEY_NAME: my-app-foo-funk
      MINIO_SERVER_URL: "https://storage.domain.com"
      MINIO_BROWSER_REDIRECT_URL: "https://console.domain.com"
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: secret_password
    command: minio server /data01
```
Checking *mc admin info ALIAS --json*
gives me
```
        "services": {
            "kms": {
                "status": "online",
                "encrypt": "success",
                "decrypt": "success"
            },
 ```
I can create a bucket and upload a crypted file
```
mc cp root.key ALIAS/test --encrypt ALIAS/test -q
`root.key` -> `ALIAS/test/root.key`
Total: 0 B, Transferred: 119 B, Speed: 706 B/s
```
```
mc stat ALIAS/test/root.key
Name      : root.key
Date      : 2021-09-08 16:59:29 CEST
Size      : 119 B
ETag      : fceb8c869c3ed718ba977d6b617305e7
Type      : file
Metadata  :
  Content-Type: application/octet-stream
Encrypted :
  X-Amz-Server-Side-Encryption: AES256
```
But not auto encrypt :(

## Context
Tried this many different ways,
Id like to be able to use local running KES and Vault as per recommended Setup

## Regression
Never worked for me

## Your Environment
Standalone Docker on Debain 10 Buster

Tested these Images:
image: minio/minio:latest
image: minio/minio:RELEASE.2021-08-25T00-41-18Z**
