### ISSUE TITLE
Use minio with docker registry fails

### ISSUE THREAD

**Issue by dreh23** [minio/minio#1326]
I compiled docker-registry from source and wan't to use minio as s3 storage backend. I created a bucket with mc and everything seems to work. If i push a docker image to the registry - minio throws errors and docker receives a 500 internal server error.

Log snippet minio:

`time="2016-04-18T12:05:43+02:00" level=error msg="ListObjects failed." Error={open /silo/container/registry/repo/docker/registry/v2/blobs/sha256/51/5158b4ddf6c372b919c74350b432aeedc1baa9f978ba8c11a754cbe1ea842108: no such file or directory *os.PathError [{103 pkg/fs/fs-bucket-listobjects.go fs.Filesystem.ListObjects map[]} {246 bucket-handlers.go main.storageAPI.ListObjectsHandler map[]}] map[mem.used:5.0MB host.arch:amd64 host.name:cell-vms-01 host.lang:go1.6 mem.heap.used:5.0MB mem.heap.total:22MB host.os:linux host.cpus:8 mem.total:28MB]}`

Log snippet registry:

```

192.168.1.34 - - [18/Apr/2016:12:05:40 +0200] "PATCH /v2/celluloidvfx/baseimage/blobs/uploads/b7a85bcd-50a0-4513-89b1-75e43c989a17?_state=EOCqihTRKg5sjydxYfZihquF4HNW3CLXuFDoIoww4M17Ik5hbWUiOiJjZWxsdWxvaWR2ZngvYmFzZWltYWdlIiwiVVVJRCI6ImI3YTg1YmNkLTUwYTAtNDUxMy04OWIxLTc1ZTQzYzk4OWExNyIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAxNi0wNC0xOFQxMDowNTo0MC43NDA0MzI1MVoifQ%3D%3D HTTP/1.1" 202 0 "" "docker/1.10.3 go/go1.5.3 git-commit/20f81dd kernel/3.13.0-85-generic os/linux arch/amd64"
ERRO[0070] unknown error completing upload: driver.Error{DriverName:"s3aws", Enclosed:(*awserr.requestError)(0xc8205bc180)}  go.version=go1.6 http.request.host=cell-registry-01.celluloidvfx.inc http.request.id=e9a39f24-eba8-400b-b46b-df0d45efe95a http.request.method=PUT http.request.remoteaddr=192.168.1.34:54241 http.request.uri=/v2/celluloidvfx/baseimage/blobs/uploads/b7a85bcd-50a0-4513-89b1-75e43c989a17?_state=0UP7hcmSVKtzYeO5chtZXdUbrHOSiDR91X8nXOCn3jV7Ik5hbWUiOiJjZWxsdWxvaWR2ZngvYmFzZWltYWdlIiwiVVVJRCI6ImI3YTg1YmNkLTUwYTAtNDUxMy04OWIxLTc1ZTQzYzk4OWExNyIsIk9mZnNldCI6NzM5NjE2OSwiU3RhcnRlZEF0IjoiMjAxNi0wNC0xOFQxMDowNTo0MFoifQ%3D%3D&digest=sha256%3A5158b4ddf6c372b919c74350b432aeedc1baa9f978ba8c11a754cbe1ea842108 http.request.useragent=docker/1.10.3 go/go1.5.3 git-commit/20f81dd kernel/3.13.0-85-generic os/linux arch/amd64 instance.id=8da1c812-2172-4923-994e-75957a07388c vars.name=celluloidvfx/baseimage vars.uuid=b7a85bcd-50a0-4513-89b1-75e43c989a17 version=v2.3.0-rc.1-243-g05b0ab0
ERRO[0070] error canceling upload after error: already committed  go.version=go1.6 http.request.host=cell-registry-01.celluloidvfx.inc http.request.id=e9a39f24-eba8-400b-b46b-df0d45efe95a http.request.method=PUT http.request.remoteaddr=192.168.1.34:54241 http.request.uri=/v2/celluloidvfx/baseimage/blobs/uploads/b7a85bcd-50a0-4513-89b1-75e43c989a17?_state=0UP7hcmSVKtzYeO5chtZXdUbrHOSiDR91X8nXOCn3jV7Ik5hbWUiOiJjZWxsdWxvaWR2ZngvYmFzZWltYWdlIiwiVVVJRCI6ImI3YTg1YmNkLTUwYTAtNDUxMy04OWIxLTc1ZTQzYzk4OWExNyIsIk9mZnNldCI6NzM5NjE2OSwiU3RhcnRlZEF0IjoiMjAxNi0wNC0xOFQxMDowNTo0MFoifQ%3D%3D&digest=sha256%3A5158b4ddf6c372b919c74350b432aeedc1baa9f978ba8c11a754cbe1ea842108 http.request.useragent=docker/1.10.3 go/go1.5.3 git-commit/20f81dd kernel/3.13.0-85-generic os/linux arch/amd64 instance.id=8da1c812-2172-4923-994e-75957a07388c vars.name=celluloidvfx/baseimage vars.uuid=b7a85bcd-50a0-4513-89b1-75e43c989a17 version=v2.3.0-rc.1-243-g05b0ab0
ERRO[0070] response completed with error                 err.code=unknown err.detail=s3aws: InternalError: We encountered an internal error, please try again.
    status code: 500, request id: 1NYDSKLZFCFPP19A err.message=unknown error go.version=go1.6 http.request.host=cell-registry-01.celluloidvfx.inc http.request.id=e9a39f24-eba8-400b-b46b-df0d45efe95a http.request.method=PUT http.request.remoteaddr=192.168.1.34:54241 http.request.uri=/v2/celluloidvfx/baseimage/blobs/uploads/b7a85bcd-50a0-4513-89b1-75e43c989a17?_state=0UP7hcmSVKtzYeO5chtZXdUbrHOSiDR91X8nXOCn3jV7Ik5hbWUiOiJjZWxsdWxvaWR2ZngvYmFzZWltYWdlIiwiVVVJRCI6ImI3YTg1YmNkLTUwYTAtNDUxMy04OWIxLTc1ZTQzYzk4OWExNyIsIk9mZnNldCI6NzM5NjE2OSwiU3RhcnRlZEF0IjoiMjAxNi0wNC0xOFQxMDowNTo0MFoifQ%3D%3D&digest=sha256%3A5158b4ddf6c372b919c74350b432aeedc1baa9f978ba8c11a754cbe1ea842108 http.request.useragent=docker/1.10.3 go/go1.5.3 git-commit/20f81dd kernel/3.13.0-85-generic os/linux arch/amd64 http.response.contenttype=application/json; charset=utf-8 http.response.duration=265.821485ms http.response.status=500 http.response.written=117 instance.id=8da1c812-2172-4923-994e-75957a07388c vars.name=celluloidvfx/baseimage vars.uuid=b7a85bcd-50a0-4513-89b1-75e43c989a17 version=v2.3.0-rc.1-243-g05b0ab0
192.168.1.34 - - [18/Apr/2016:12:05:43 +0200] "PUT /v2/celluloidvfx/baseimage/blobs/uploads/b7a85bcd-50a0-4513-89b1-75e43c989a17?_state=0UP7hcmSVKtzYeO5chtZXdUbrHOSiDR91X8nXOCn3jV7Ik5hbWUiOiJjZWxsdWxvaWR2ZngvYmFzZWltYWdlIiwiVVVJRCI6ImI3YTg1YmNkLTUwYTAtNDUxMy04OWIxLTc1ZTQzYzk4OWExNyIsIk9mZnNldCI6NzM5NjE2OSwiU3RhcnRlZEF0IjoiMjAxNi0wNC0xOFQxMDowNTo0MFoifQ%3D%3D&digest=sha256%3A5158b4ddf6c372b919c74350b432aeedc1baa9f978ba8c11a754cbe1ea842108 HTTP/1.1" 500 117 "" "docker/1.10.3 go/go1.5.3 git-commit/20f81dd kernel/3.13.0-85-generic os/linux arch/amd64"
ERRO[0070] unknown error reading request payload: unexpected EOF  go.version=go1.6 http.request.host=cell-registry-01.celluloidvfx.inc http.request.id=c444aee7-96ff-4cab-83df-d6477e45a632 http.request.method=PATCH http.request.remoteaddr=192.168.1.34:54232 http.request.uri=/v2/celluloidvfx/baseimage/blobs/uploads/1ba64b59-8f77-49b0-8cd7-3bec6a1c7c6e?_state=wSrCe2zEGbA8GoKyc9_xiWBLmp-PUIPQsZsWcy8sQG57Ik5hbWUiOiJjZWxsdWxvaWR2ZngvYmFzZWltYWdlIiwiVVVJRCI6IjFiYTY0YjU5LThmNzctNDliMC04Y2Q3LTNiZWM2YTFjN2M2ZSIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAxNi0wNC0xOFQxMDowNTozNS45MTEwOTYyODdaIn0%3D http.request.useragent=docker/1.10.3 go/go1.5.3 git-commit/20f81dd kernel/3.13.0-85-generic os/linux arch/amd64 instance.id=8da1c812-2172-4923-994e-75957a07388c vars.name=celluloidvfx/baseimage vars.uuid=1ba64b59-8f77-49b0-8cd7-3bec6a1c7c6e version=v2.3.0-rc.1-243-g05b0ab0
ERRO[0070] response completed with error                 err.code=unknown err.detail=unexpected EOF err.message=unknown error go.version=go1.6 http.request.host=cell-registry-01.celluloidvfx.inc http.request.id=c444aee7-96ff-4cab-83df-d6477e45a632 http.request.method=PATCH http.request.remoteaddr=192.168.1.34:54232 http.request.uri=/v2/celluloidvfx/baseimage/blobs/uploads/1ba64b59-8f77-49b0-8cd7-3bec6a1c7c6e?_state=wSrCe2zEGbA8GoKyc9_xiWBLmp-PUIPQsZsWcy8sQG57Ik5hbWUiOiJjZWxsdWxvaWR2ZngvYmFzZWltYWdlIiwiVVVJRCI6IjFiYTY0YjU5LThmNzctNDliMC04Y2Q3LTNiZWM2YTFjN2M2ZSIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAxNi0wNC0xOFQxMDowNTozNS45MTEwOTYyODdaIn0%3D http.request.useragent=docker/1.10.3 go/go1.5.3 git-commit/20f81dd kernel/3.13.0-85-generic os/linux arch/amd64 http.response.contenttype=application/json; charset=utf-8 http.response.duration=8.135768207s http.response.status=500 http.response.written=70 instance.id=8da1c812-2172-4923-994e-75957a07388c vars.name=celluloidvfx/baseimage vars.uuid=1ba64b59-8f77-49b0-8cd7-3bec6a1c7c6e version=v2.3.0-rc.1-243-g05b0ab0
192.168.1.34 - - [18/Apr/2016:12:05:35 +0200] "PATCH /v2/celluloidvfx/baseimage/blobs/uploads/1ba64b59-8f77-49b0-8cd7-3bec6a1c7c6e?_state=wSrCe2zEGbA8GoKyc9_xiWBLmp-PUIPQsZsWcy8sQG57Ik5hbWUiOiJjZWxsdWxvaWR2ZngvYmFzZWltYWdlIiwiVVVJRCI6IjFiYTY0YjU5LThmNzctNDliMC04Y2Q3LTNiZWM2YTFjN2M2ZSIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAxNi0wNC0xOFQxMDowNTozNS45MTEwOTYyODdaIn0%3D HTTP/1.1" 500 70 "" "docker/1.10.3 go/go1.5.3 git-commit/20f81dd kernel/3.13.0-85-generic os/linux arch/amd64"
```

$ ./minio version
Version: 2016-03-21T21:08:51Z
Release-Tag: RELEASE.2016-03-21T21-08-51Z
Commit-ID: 0b87c77bc23c04e84247e4e6330edbb4b7195d63

$ ./registry -v
./registry github.com/docker/distribution v2.3.0-rc.1-243-g05b0ab0

All machines:   Ubuntu 12.04.5 LTS
go version go1.6 linux/amd64

**Comment by harshavardhana** [comment]
> $ ./minio version
> Version: 2016-03-21T21:08:51Z
> Release-Tag: RELEASE.2016-03-21T21-08-51Z
> Commit-ID: 0b87c77bc23c04e84247e4e6330edbb4b7195d63
> 
> $ ./registry -v
> ./registry github.com/docker/distribution v2.3.0-rc.1-243-g05b0ab0
> 
> All machines: Ubuntu 12.04.5 LTS
> go version go1.6 linux/amd64

Can you test with the latest minio version?

**Comment by dreh23** [comment]
Registry is throwing errors and docker receives a 500.

$ ./minio version
Version: 2016-04-18T17:14:48Z
Release-Tag: DEVELOPMENT.2016-04-18T17-14-48Z
Commit-ID: b47d722d8e24599dbfae311df3fd0a245d8fc2a3

$ ./registry -v 
./registry github.com/docker/distribution v2.3.0-rc.1-245-g9d49169

$ ~/mc mb registry/repo
Bucket created successfully ‘registry/repo’.

$ docker push cell-registry-01.celluloidvfx.inc/ubuntu
The push refers to a repository [cell-registry-01.celluloidvfx.inc/ubuntu]
5f70bf18a086: Pushed 
f75f146a5022: Pushed 
711b0bd2cb6a: Pushed 
595d1d53a534: Pushing [==================================================>] 196.9 MB
Received unexpected HTTP status: 500 Internal Server Error

[Registry error log](https://gist.github.com/dreh23/08e5c79b01aced6eba5f8304ebeebe88)

**Comment by harshavardhana** [comment]
> Registry is throwing errors and docker receives a 500.
> 
> $ ./minio version
> Version: 2016-04-18T17:14:48Z
> Release-Tag: DEVELOPMENT.2016-04-18T17-14-48Z
> Commit-ID: b47d722
> 
> $ ./registry -v 
> ./registry github.com/docker/distribution v2.3.0-rc.1-245-g9d49169
> 
> $ ~/mc mb registry/repo
> Bucket created successfully ‘registry/repo’.
> 
> $ docker push cell-registry-01.celluloidvfx.inc/ubuntu
> The push refers to a repository [cell-registry-01.celluloidvfx.inc/ubuntu]
> 5f70bf18a086: Pushed 
> f75f146a5022: Pushed 
> 711b0bd2cb6a: Pushed 
> 595d1d53a534: Pushing [==================================================>] 196.9 MB
> Received unexpected HTTP status: 500 Internal Server Error

Will test this thanks.

**Comment by harshavardhana** [comment]
@dreh23 would you mind pasting your registry configs here?

**Comment by dreh23** [comment]
```
version: 0.1
log:
  fields:
    service: registry
storage:
    cache:
        blobdescriptor: inmemory
    s3:
        accesskey: LOV73F1C8EAQN1341D3C
        secretkey: yWQQ+D0ZEBKKrAqewsYgK1+CCFwmc8kCBDq7Rmce
        region: us-east-1
        regionendpoint: http://cell-vms-01.celluloidvfx.inc:9500
        bucket: repo
        #keyid: mykeyid
        secure: true
        v4auth: true
        chunksize: 5242880
        rootdirectory: /
http:
    addr: :443
    headers:
        X-Content-Type-Options: [nosniff]
    tls:
        certificate: ./certs/cell-registry-01.celluloidvfx.inc.crt
        key: ./certs/cell-registry-01.celluloidvfx.inc.key
        clientcas:
        - ./certs/ca.pem

health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
```

**Comment by harshavardhana** [comment]
```
ERRO[0213] response completed with error                 err.code=unknown err.detail=InvalidPartOrder: The list of parts was not in ascending order. The parts list must be specified in order by part number.
```

^^^ Looks like registry is sending parts in invalid order.

**Comment by dreh23** [comment]
Is this a minio bug or should I file a bug report in the registry?

**Comment by harshavardhana** [comment]
> Is this a minio bug or should I file a bug report in the registry?

We will update you tomorrow but we have some insights from our testing, haven't had time to look into docker registry code yet.

**Comment by harshavardhana** [comment]
This is fixed merged upstream patch.

**Comment by ulm0** [comment]
Just moved from filesystem storage and setup a Registry with Minio (latest) as backend and I'm getting 500's errors when pushing.

```sh
$ docker push r.ulm0.xyz/cockroach:v1.1.6-slim
The push refers to repository [r.ulm0.xyz/cockroach]
ad26c81a8728: Pushed 
139438579314: Pushed 
received unexpected HTTP status: 500 Internal Server Error
```

Registry config:

```yaml
version: 0.1
log:
  accesslog:
    disabled: true
  level: debug
  formatter: text
  fields:
    service: registry
    environment: production
  hooks:
    - type: mail
      disabled: true
      levels:
        - panic
      options:
        smtp:
          addr: mail.domain.com:587
          username: no-reply@domain.com
          password: [REDACTED]
          insecure: false
        from: no-reply@domain.com
        to:
          - mail@domain.com
storage:
  s3:
    accesskey: [REDACTED]
    secretkey: [REDACTED]
    region: cl-north-1
    regionendpoint: https://s.domain.com
    bucket: registry
    encrypt: false
    secure: true
    v4auth: true
    chunksize: 5242880
    rootdirectory: /
  delete:
    enabled: true
  redirect:
    disable: false
  cache:
    blobdescriptor: redis
  maintenance:
    uploadpurging:
      enabled: true
      age: 168h
      interval: 24h
      dryrun: false
    readonly:
      enabled: false
http:
  addr: :5000
  net: tcp
  secret: [REDACTED]
  host: https://r.ulm0.xyz
  headers:
    X-Content-Type-Options: [nosniff]
  http2:
    disabled: false
redis:
  addr: registry_cache:6379
  dialtimeout: 10ms
  readtimeout: 10ms
  writetimeout: 10ms
  pool:
    maxidle: 16
    maxactive: 64
    idletimeout: 300s
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
  tcp:
    - addr: registry_cache:6379
      timeout: 3s
      interval: 10s
      threshold: 3
```

Minio config:

```json
...
"credential": {
		"accessKey": "[REDACTED]",
		"secretKey": "[REDACTED]"
},
"region": "cl-north-1",
"browser": "on",
"domain": "s.domain.com",
...
```
