### ISSUE TITLE
MinIO S3 gateway server/console behind Nginx Kubernetes ingress returns 401 (console /api/v1/session)

### ISSUE THREAD

**Issue by danilopeixoto** [minio/minio#13278]
I'm using Bitnami Minio Helm Chart to deploy MinIO S3 gateway but I can't login to the console.
MinIO server and console are behind Nginx Kubernetes ingress. The reverse proxies enable TLS certificate (`*.domain.com`) and HTTP/2.

* `:9000` -> `storage.domain.com` (server ingress)
* `:9001` -> `s3.domain.com` (console ingress)

I set up the following environment variables:

* MINIO_SERVER_URL: https://storage.domain.dell.com
* MINIO_BROWSER_REDIRECT_URL: https://s3.domain.com

## Expected Behavior
Login to the console behind proxy.

## Current Behavior

Login page fails and redirects back to itself.
Request: `https://s3.domain.com/api/v1/session`
Status code: `401`

## Possible Solution

I can login to the console by forwarding the 9001 service port (`kubectl port-forward`)
I can list buckets from http://storage.domain.dell.com using MinIO client (HTTPS returns `x509: certificate signed by unknown authority`)

## Steps to Reproduce (for bugs)
Expose MinIO server and console behind NGINX Kubernetes ingress with TLS certificates and HTTP/2.

**Ingresses**

Console:

```yaml
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: minio-release
  namespace: minio-release
  labels:
    app.kubernetes.io/instance: minio-release
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: minio
    helm.sh/chart: minio-8.1.3
  annotations:
    kubernetes.io/ingress.class: nginx
    meta.helm.sh/release-name: minio-release
    meta.helm.sh/release-namespace: minio-release
    nginx.ingress.kubernetes.io/proxy-body-size: 2000m
spec:
  rules:
    - host: s3.domain.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: minio-release
                port:
                  name: minio-console
```

Server:

```yaml
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: minio-release-api
  namespace: minio-release
  labels:
    app.kubernetes.io/instance: minio-release
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: minio
    helm.sh/chart: minio-8.1.3
  annotations:
    kubernetes.io/ingress.class: nginx
    meta.helm.sh/release-name: minio-release
    meta.helm.sh/release-namespace: minio-release
    nginx.ingress.kubernetes.io/proxy-body-size: 2000m
spec:
  rules:
    - host: storage.domain.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: minio-release
                port:
                  name: minio-api
```

Nginx Kubernetes Ingress Controller configuration:

```
nginx-ingress-controller
    --publish-service=ingress-nginx/ingress-nginx-controller
    --election-id=ingress-controller-leader
    --ingress-class=nginx
    --configmap=ingress-nginx/ingress-nginx-controller
    --validating-webhook=:8443
    --default-ssl-certificate=ingress-nginx/tls-certs
    --enable-ssl-chain-completion=false
```

**Additional `tls-certs` information**

Public key header:
```
Bag Attributes
    localKeyID: <ommited>
    friendlyName: *.domain.com
subject=C = US, ST = <ommited>, L = <ommited>, O = <ommited>, CN = *.domain.com

issuer=C = US, O = "Entrust, Inc."... <ommited>
```

Other deployments are already using this controller successfully.

## Context
We need https://storage.domain.com and https://s3.domain.com available for everyone.

## Regression
I tested images from Bitnami and MinIO repositories (2020 and 2021 versions).

## Your Environment

* Version used (`minio --version`): DEVELOPMENT.2021-09-18T18-09-59Z
* Server setup and configuration: Bitnami Minio Helm Chart 8.1.3, Nginx Kubernetes Ingress Controller v1.0.0
