### ISSUE TITLE
mc mirror - Unable to list comparison retrying.. 502 Bad Gateway

### ISSUE THREAD

**Issue by mostafa8026** [minio/minio#13290]
I'm using the following command for mirror:

```
docker run --rm -v /sources/server-docker-yml-files/minio/mc:/root/.mc --network minio_backup minio/mc mirror --debug sg/storage/ bi/storage/
```

there are too many files (around 100 thousands), after two or more continuation, I get this error:

```
mc: <ERROR> Unable to list comparison retrying.. 502 Bad Gateway
 (1) difference.go:198 cmd.differenceInternal(..) Tags: [https://***/storage/, https://***/storage/shutterstock/]
 (0) client-s3.go:2103 cmd.(*S3Client).listRecursiveInRoutine(..)
 Release-Tag:RELEASE.2021-09-02T09-21-27Z | Commit:f661334f3d61 | Host:f21acb95f78b | OS:linux | Arch:amd64 | Lang:go1.16.7 | Mem:11 MB/76 MB | Heap:11 MB/66 MB
mc: <DEBUG> GET /storage/?delimiter=&encoding-type=url&fetch-owner=true&list-type=2&prefix=%2F HTTP/1.1
Host: ***
User-Agent: MinIO (linux; amd64) minio-go/v7.0.13 mc/RELEASE.2021-09-02T09-21-27Z
Authorization: AWS4-HMAC-SHA256 Credential=2b9f707a-5b94-482b-9601-2c52b170ef0f/20210923/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20210923T131335Z
Accept-Encoding: gzip
```

## Expected Behavior
I expect that continuation works without problem.

## Current Behavior
got an error as described above

## Possible Solution
I think, it might be related to nginx configuration, here is my config, is it ok?

```
server {
        listen       80;
        listen  [::]:80;

        listen       443 ssl;

        ssl_certificate /etc/letsencrypt/live/...
        ssl_certificate_key /etc/letsencrypt/live/...

        server_name  ***;

         # To allow special characters in headers
         ignore_invalid_headers off;
         # Allow any size file to be uploaded.
         # Set to a value such as 1000m; to restrict file size to a specific value
         client_max_body_size 0;
         # To disable buffering
         proxy_buffering off;

        location / {
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_connect_timeout       600;
            proxy_send_timeout          600;
            proxy_read_timeout          600;
            send_timeout                600;
            # Default is HTTP/1, keepalive is only enabled in HTTP/1.1
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            chunked_transfer_encoding off;

            proxy_pass http://minio.minio_backup:9000;
        }

```

## Your Environment
* Version used (`minio --version`): source: (RELEASE.2021-09-15T04-54-25Z) target: (RELEASE.2021-06-17T00-10-46Z)
* Server setup and configuration: source with docker-compose and target with k8s
* Operating System and version (`uname -a`): Linux Ubuntu-2004-focal-64-minimal 5.4.0-47-generic 51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mostafa8026** [comment]
also, in the target I have this annotations in ingress:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing-minio
  annotations:
    acme.cert-manager.io/http01-ingress-class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-body-size: 0m
```
