### ISSUE TITLE
minio on OpenEBS Local PV Device volumes

### ISSUE THREAD

**Issue by HaykManukyanAvetiky** [minio/minio#13321]
I am trying to set up Minio cluster in k8s using minio operator and  OpenEBS Local PV Device volumes for storage.
I have created the following template 
```yaml
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  creationTimestamp: null
  name: minio-tenant-1
  namespace: minio-test
scheduler:
  name: ""
spec:
  certConfig: {}
  credsSecret:
    name: minio-tenant-1-creds-secret
  image: minio/minio:RELEASE.2021-08-25T00-41-18Z
  mountPath: /data
  pools:
  - affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: v1.min.io/tenant
              operator: In
              values:
              - minio-tenant-1
          topologyKey: kubernetes.io/hostname
    resources: {}
    securityContext:
      runAsNonRoot: False
    servers: 3
    volumeClaimTemplate:
      apiVersion: v1
      kind: persistentvolumeclaims
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: minio-openebs-local-device
      status: {}
    volumesPerServer: 2
  requestAutoCert: false
status:
  availableReplicas: 0
  certificates: {}
  currentState: ""
  pools: null
  revision: 0
  syncVersion: ""

---
apiVersion: v1
data:
  accesskey: ZjEyYmE5MDItMjMyMi00NTk5LThkZjgtMjJkNDYwMzJhZGE2
  secretkey: NDQ1MjE3YjQtOGU2ZS00YWY1LWEzMDAtOTE1MDI1ZTRhMjZj
kind: Secret
metadata:
  creationTimestamp: null
  name: minio-tenant-1-creds-secret
  namespace: minio-test

---
apiVersion: v1
data:
  CONSOLE_ACCESS_KEY: YWRtaW4=
  CONSOLE_PBKDF_PASSPHRASE: ZjhmYmVlNmUtZmE5YS00MjlkLWE0OTAtZDExMTAzMzI1ZDNh
  CONSOLE_PBKDF_SALT: MDE4OTQ3YzMtNDQ2Zi00OGU5LWI0ZTEtZGRlOWFkZTQ5NDE4
  CONSOLE_SECRET_KEY: NDQyMDIwMjQtMDkxMC00ZmVjLWFhM2QtMGMxNWY5YThmN2Yx
kind: Secret
metadata:
  creationTimestamp: null
  name: minio-tenant-1-console-secret
  namespace: minio-test  
```
and my storage class is 
``` yaml

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: minio-openebs-local-device
  annotations:
    openebs.io/cas-type: local
    cas.openebs.io/config: |
      - name: StorageType
        value: device
      - name: FSType
        value: xfs
      - name: BlockDeviceTag
        value: "minio"
provisioner: openebs.io/local
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```

When I run 
` kubectl apply -f helm/templates/minio_tenant.yml `
it creates 3 pods and I don't know why they run only after ~ 17 crashloopbackoff's 
``` bash
$ kubectl get pods -n minio-test
NAME                    READY   STATUS    RESTARTS   AGE
minio-tenant-1-ss-0-0   1/1     Running   18         24h
minio-tenant-1-ss-0-1   1/1     Running   14         24h
minio-tenant-1-ss-0-2   1/1     Running   19         24h
```
before pods come up I constantly get the following error 
```bash
  $ kubectl logs -p -n minio-test minio-tenant-1-ss-0-0
ERROR Invalid command line arguments: path '/data0' cannot be served by different address on same server
      > Please provide correct combination of local/remote paths
      HINT:
        For more information, please refer to https://docs.min.io/docs/minio-erasure-code-quickstart-guide
```
Now When pods are running I am getting different error 
```
API: SYSTEM()
Time: 10:39:30 UTC 09/24/2021
DeploymentID: 4796173b-2916-40a2-9f2a-4ba6af0e81e4
Error: disk /data1 returned: disk not found, disk /data0 returned: disk not found (*errors.errorString)
       2: cmd/erasure-server-pool.go:1099:cmd.(*erasureServerPools).ListObjects()
       1: cmd/erasure-server-pool.go:1603:cmd.(*erasureServerPools).Walk.func2()
```
Though  it says   /data1  and  /data0 not found I can exec into pod and create files or list in that directory, also .minio.sys is there.
```bash
[root@minio-tenant-1-ss-0-2 /]# touch data0/test.txt
[root@minio-tenant-1-ss-0-2 /]# ls -la /data*
/data:
total 8
drwxr-xr-x 2 root root 4096 Sep 23 11:08 .
drwxr-xr-x 1 root root 4096 Sep 23 11:08 ..

/data0:
total 4
drwxr-xr-x 3 root root   40 Sep 24 10:45 .
drwxr-xr-x 1 root root 4096 Sep 23 11:08 ..
drwxr-xr-x 8 root root  111 Sep 23 11:08 .minio.sys
-rw-r--r-- 1 root root    0 Sep 24 10:45 test.txt

/data1:
total 4
drwxr-xr-x 3 root root   24 Sep 23 11:08 .
drwxr-xr-x 1 root root 4096 Sep 23 11:08 ..
drwxr-xr-x 7 root root  100 Sep 23 11:08 .minio.sys
```
everything with block devices, pv's and pvc's are ok 

```bash
$ kubectl get pvc -n minio-test
NAME                      STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                 AGE
0-minio-tenant-1-ss-0-0   Bound    pvc-3e54ee9b-47c1-43be-9d0b-b001311fa9de   1Gi        RWO            minio-openebs-local-device   24h
0-minio-tenant-1-ss-0-1   Bound    pvc-1f2af3d6-9b0e-4550-88ce-f0923242a717   1Gi        RWO            minio-openebs-local-device   24h
0-minio-tenant-1-ss-0-2   Bound    pvc-fe6f213d-d1ab-4906-b4ba-993129c99a31   1Gi        RWO            minio-openebs-local-device   24h
1-minio-tenant-1-ss-0-0   Bound    pvc-a3c49472-cf6d-4a0d-8843-c2cfb07c2610   1Gi        RWO            minio-openebs-local-device   24h
1-minio-tenant-1-ss-0-1   Bound    pvc-3c4b4aaf-5d07-4230-9f68-234ba79e0b40   1Gi        RWO            minio-openebs-local-device   24h
1-minio-tenant-1-ss-0-2   Bound    pvc-23687ec8-0195-46da-b580-de7553f02405   1Gi        RWO            minio-openebs-local-device   24h


$ kubectl get bdc -A
NAMESPACE   NAME                                           BLOCKDEVICENAME                                PHASE   AGE
openebs     bdc-pvc-1f2af3d6-9b0e-4550-88ce-f0923242a717   blockdevice-73cc2f95141f9cb40341cb0e1ed1e32b   Bound   24h
openebs     bdc-pvc-23687ec8-0195-46da-b580-de7553f02405   blockdevice-6b2de83957af3fb7ccedf9f0144d2824   Bound   24h
openebs     bdc-pvc-2b057e3f-1860-4af8-9652-e47d968713ca   blockdevice-4c8c0e652eb58a60aa74c77ac4f545aa   Bound   25h
openebs     bdc-pvc-331f448b-71c0-4d32-adf3-3a8949653c1b   blockdevice-eb1324e387bd24143bc2b1d28acffc5a   Bound   25h
openebs     bdc-pvc-3c4b4aaf-5d07-4230-9f68-234ba79e0b40   blockdevice-b20a75a9227fe4772835b70cdfb66fe1   Bound   24h
openebs     bdc-pvc-3e54ee9b-47c1-43be-9d0b-b001311fa9de   blockdevice-34d32a189c80fab7c1624d424fa45532   Bound   24h
openebs     bdc-pvc-a3c49472-cf6d-4a0d-8843-c2cfb07c2610   blockdevice-a3a51452e13a5dcdfd8fea47e6d40cd9   Bound   24h
openebs     bdc-pvc-fe6f213d-d1ab-4906-b4ba-993129c99a31   blockdevice-4e78f33f1032191cdf9cf1bd7be4c554   Bound   24h


$ kubectl get bd -A
NAMESPACE   NAME                                           NODENAME      SIZE         CLAIMSTATE   STATUS     AGE
openebs     blockdevice-34d32a189c80fab7c1624d424fa45532   fh1-kubet03   1314914304   Claimed      Active     8d
openebs     blockdevice-36b14a2d5ddcf16bc3b464eb25f48de2   fh1-kubet08   1084227584   Released     Inactive   8d
openebs     blockdevice-3707d9f4cd2330a86da262b123e56238   fh1-kubet08   5368709120   Unclaimed    Active     10d
openebs     blockdevice-431515171b62682d17f235f1a6ae1bfc   fh1-kubet03   1341128704   Unclaimed    Active     8d
openebs     blockdevice-4c8c0e652eb58a60aa74c77ac4f545aa   fh1-kubet08   1341128704   Claimed      Active     8d
openebs     blockdevice-4e78f33f1032191cdf9cf1bd7be4c554   fh1-kubet02   1341128704   Claimed      Active     8d
openebs     blockdevice-547a3e87eba5a8df034c78b07fad1c34   fh1-kubet02   1341128704   Unclaimed    Active     8d
openebs     blockdevice-6b2de83957af3fb7ccedf9f0144d2824   fh1-kubet02   1366294528   Claimed      Active     8d
openebs     blockdevice-73cc2f95141f9cb40341cb0e1ed1e32b   fh1-kubet08   1341128704   Claimed      Active     8d
openebs     blockdevice-73e123400ed91cefa7b2ff94bb925cc0   fh1-kubet02   1084227584   Released     Inactive   8d
openebs     blockdevice-776c5e435ac1a827dcfe02fecaf0ad74   fh1-kubet03   5368709120   Unclaimed    Active     10d
openebs     blockdevice-a3a51452e13a5dcdfd8fea47e6d40cd9   fh1-kubet03   1341128704   Claimed      Active     8d
openebs     blockdevice-a6860574170fddce39ea141580bb9a11   fh1-kubet03   1366294528   Unclaimed    Active     8d
openebs     blockdevice-b20a75a9227fe4772835b70cdfb66fe1   fh1-kubet08   1314914304   Claimed      Active     8d
openebs     blockdevice-c63930c59aeb14473a9de6456a738d47   fh1-kubet08   1366294528   Unclaimed    Active     8d
openebs     blockdevice-d70c47c5300c0072306cfa7218782ba2   fh1-kubet03   1084227584   Released     Inactive   8d
openebs     blockdevice-eb1324e387bd24143bc2b1d28acffc5a   fh1-kubet02   1314914304   Claimed      Active     8d
openebs     blockdevice-fc0771fc416fdcd4faafc7694c5c0b39   fh1-kubet02   5368709120   Unclaimed    Active     10d

```
Also I been able to run replicated postgres instances using same storage class and everything is ok , so I believe  that storage is OK.
 

## Expected Behavior

I expect Minio to run normally and been able to connect console using operator proxy

## Current Behavior

It shows me that pods are running but I can see wired error  in logs
```
API: SYSTEM()
Time: 10:39:30 UTC 09/24/2021
DeploymentID: 4796173b-2916-40a2-9f2a-4ba6af0e81e4
Error: disk /data1 returned: disk not found, disk /data0 returned: disk not found (*errors.errorString)
       2: cmd/erasure-server-pool.go:1099:cmd.(*erasureServerPools).ListObjects()
       1: cmd/erasure-server-pool.go:1603:cmd.(*erasureServerPools).Walk.func2()
```
and I cant access my tenant 
![image](https://user-images.githubusercontent.com/65945812/134663471-513a33f1-2fa8-4025-8b5e-2772afed5fd3.png)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio-operator`):
* Environment name and version (e.g. kubernetes v1.17.2):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your deployment file:

```bash
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:26:42Z", GoVersion:"go1.15", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.14", GitCommit:"0fd2b5afdfe3134d6e1531365fdb37dd11f54d1c", GitTreeState:"clean", BuildDate:"2021-08-11T18:02:17Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}

$ kubectl minio version
v4.2.3

$ kubectl get deployment -n openebs -o wide
NAME                          READY   UP-TO-DATE   AVAILABLE   AGE   CONTAINERS                                                 IMAGES                                                                   SELECTOR
openebs-admission-server      1/1     1            1           10d   admission-webhook                                          openebs/admission-server:2.12.1                                          app=admission-webhook
openebs-apiserver             1/1     1            1           10d   openebs-apiserver                                          openebs/m-apiserver:2.12.1                                               app=openebs,release=openebs
openebs-localpv-provisioner   1/1     1            1           10d   openebs-localpv-provisioner                                openebs/provisioner-localpv:2.12.1                                       app=openebs,release=openebs
openebs-ndm-operator          1/1     1            1           10d   openebs-ndm-operator                                       openebs/node-disk-operator:1.6.1                                         app=openebs,release=openebs
openebs-provisioner           1/1     1            1           10d   openebs-provisioner                                        openebs/openebs-k8s-provisioner:2.12.1                                   app=openebs,release=openebs
openebs-snapshot-operator     1/1     1            1           10d   openebs-snapshot-controller,openebs-snapshot-provisioner   openebs/snapshot-controller:2.12.1,openebs/snapshot-provisioner:2.12.1   app=openebs,release=openebs

```
