### ISSUE TITLE
stderr F /usr/bin/docker-entrypoint.sh: line 97: exec: minio: not found

### ISSUE THREAD

**Issue by ukd1** [minio/minio#13358]
For the latest docker release, I get `2021-10-04T22:32:31.191054491Z stderr F /usr/bin/docker-entrypoint.sh: line 97: exec: minio: not found`, vs an older release that works.

## Expected Behavior
not missing binary

## Current Behavior
missing binary?

## Steps to Reproduce (for bugs)

Results in the missing minio error, using this hash or `latest`:
```yaml
      containers:
      - name: minio
        image: minio/minio@sha256:1b8e8a565fd69107dd61f5cfeacad9e1b031a913af0cf6488b77252c716fd245
        args:
        - server
        - --address
        - :9997
        - --console-address
        - :9998
        - /export
```

Using the older release @ ed381859fcf4d797b8bc502b756f93e1558cc704f1bbc70c9aa9b9a2500e3dec, it works fine.

## Regression
Yes, I think so - but I don't have time to bisect it for you 

## Your Environment
n/a
