### ISSUE TITLE
ListObjectsV2Command returns data with undefined values

### ISSUE THREAD

**Issue by doums** [minio/minio#13485]
## Expected Behavior
An S3 request for `ListObjectsV2Command` should list the objects from a minio bucket correctly.

## Current Behavior
The command returns a partial result, with a lot of missing data.

## Steps to Reproduce (for bugs)
1. Setup a local minio server, create a public Bucket and upload files on it, for example a docker setup:
```yml
version: "3.9"
services:
  minio-server:
    container_name: minio-server
    image: minio/minio
    restart: always
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: "${CS_ACCESS_KEY_ID}"
      MINIO_ROOT_PASSWORD: "${CS_SECRET_ACCESS_KEY}"
    command: "server /data --address :9000 --console-address :9001"
    volumes:
      - "minio-data:/data"

  minio-client:
    container_name: minio-client
    image: minio/mc
    depends_on:
      - minio-server
    environment:
      MINIO_ROOT_USER: "${CS_ACCESS_KEY_ID}"
      MINIO_ROOT_PASSWORD: "${CS_SECRET_ACCESS_KEY}"
    entrypoint: ["/bin/sh","-c"]
    command:
    - |
      sleep 2
      mc alias set minio http://minio-server:9000 ${CS_ACCESS_KEY_ID} ${CS_SECRET_ACCESS_KEY}
      mc mb minio/my-bucket
      mc policy set public minio/my-bucket
```
2. From a Node app, create an S3 client for example:
```typescript
import { S3Client } from '@aws-sdk/client-s3';

// ...

    this.client = new S3Client({
      region: 'us-east-1',
      endpoint: 'http://localhost:9000',
      credentials: {
        accessKeyId: CS_ACCESS_KEY_ID, 
        secretAccessKey: CS_SECRET_ACCESS_KEY,
      },
    });
```
3. And list the object of the created bucket
```typescript
    const input = {
      Bucket: 'my-bucket',
    };
    try {
      const command = new ListObjectsV2Command(input);
      const output = await this.client.send(command);
      console.log(output);
    } catch (e: any) {
      console.log(e);
    }
```
4. Observe the log result
```
{
  '$metadata': {
    httpStatusCode: 200,
    requestId: undefined,
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  CommonPrefixes: undefined,
  Contents: undefined,
  ContinuationToken: undefined,
  Delimiter: undefined,
  EncodingType: undefined,
  IsTruncated: undefined,
  KeyCount: undefined,
  MaxKeys: undefined,
  Name: undefined,
  NextContinuationToken: undefined,
  Prefix: undefined,
  StartAfter: undefined
}
```
As you can see there are many fields `undefinied`. And there is no data to exploit from this call.
Note that I have uploaded some files in the bucket (through the web admin console).

## Your Environment

* Version used (`minio --version`): `Version: 2021-10-13T00:23:17Z`
* Server setup and configuration: look the docker config
* Operating System and version (`uname -a`): Arch Linux
