### ISSUE TITLE
Deploy MinIO as non-root user in an Enterprise cluster

### ISSUE THREAD

**Issue by konsloiz** [minio/minio#13663]
Hi. We are trying to deploy Kubeflow pipelines in an enterprise cluster. One of the basic components of KFPs is MinIO. Due to security settings, we are not allowed to deploy anything in the cluster as ROOT users. As a result, we keep getting an error and the pod is getting to a CrashLoopBackOff.

## Expected Behavior
Deploy MinIO in a non-root environment without problems.

## Current Behavior

`ERROR Unable to initialize backend mkdir /data/.minio.sys: permission denied`

## Possible Solution
Provide a docker image that doesn't require a root to initialize MinIO?

## Steps to Reproduce (for bugs)
1. Apply the deployment yaml file in a non-root crd cluster

## Context
Trying to deploy Kubeflow Pipelines in an enterprise

## Regression
No

## Your Environment
This is the yaml file used for the deployment:

``` yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  labels:
    app: minio
spec:
  selector:
    matchLabels:
      app: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - args:
        - server
        - /data
        env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: mlpipeline-minio-artifact
              key: accesskey
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: mlpipeline-minio-artifact
              key: secretkey
        image: gcr.io/ml-pipeline/minio:RELEASE.2019-08-14T20-37-41Z-license-compliance
        name: minio
        securityContext:
          runAsUser: 1000
        ports:
        - containerPort: 9000
        volumeMounts:
        - mountPath: /data
          name: data
          subPath: minio
        resources:
          requests:
            cpu: 20m
            memory: 100Mi
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: minio-pvc
```
