### ISSUE TITLE
Multi-part upload fail when using MinIO with Kubernetes in-memory volume (tmpfs)

### ISSUE THREAD

**Issue by LorisFriedel** [minio/minio#13674]
I'm running MinIO inside a Pod in an Openshift cluster and to achieve the performances I need, buckets must be stored in-memory (RAM). To do this, I simply create and use a "storage" volume inside my DeploymentConfig, which is configured to use in-memory filesystem.

## Expected Behavior
For any reasonably (1Mb -> 1Gb) sized files, upload/cp with multi-part feature enabled succeed and files are correctly uploaded to the MinIO bucket, whichever the underlying filesystem used.

## Current Behavior
When I upload/cp files with multi-part feature enabled, if more than one part is effectively uploaded to the bucket MinIO fails with a filesystem error: `Error: open /storage/.minio.sys/multipart/3b931983c842690782d88960942b2dbff6f03243dbd846b8f06d262cb7e17de0/bf9c6177-9368-4c20-a44a-e1b05d020abf/fs.json: invalid argument (*fs.PathError)`

![Screenshot 2021-11-17 at 09 07 00](https://user-images.githubusercontent.com/14200018/142163276-04ce1f04-2852-4670-80f7-47fee9010ff1.png)

## Possible Solution
The issue seems to be coming from the usage of DirectIO in:
https://github.com/minio/minio/blob/8378bc9958c69c3480e8bac42b32464cad7cfdae/internal/ioutil/read_file.go#L33
https://github.com/minio/minio/blob/8378bc9958c69c3480e8bac42b32464cad7cfdae/internal/disk/directio_unix.go#L33
https://github.com/ncw/directio/blob/17018d97cb6f2cd62f84c69903d327e596b7a93e/direct_io_unix.go#L22

Where the O_DIRECT flag is considered an "invalid argument" in this environment. I tested (in Go) this piece of code without the O_DIRECT flag and it works well.

A solution would be to let user disable the usage of DirectIO through configuration, or maybe dynamically detect if DirectIO is compatible with the current filesystem?

## Steps to Reproduce

1. Deploy this resource on an Openshift cluster (or the equivalent in a Kube cluster):
```yaml
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: minio
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: minio
    spec:
      volumes:
      - name: storage
        emptyDir:
          medium: Memory
          sizeLimit: 2Gi
      containers:
      - name: minio
        image: minio/minio:latest
        args:
        - server
        - "/storage"
        env:
        - name: MINIO_ROOT_USER
          value: root
        - name: MINIO_ROOT_PASSWORD
          value: password
        resources:
          limits:
            memory: 3Gi
          requests:
            cpu: '1'
            memory: 500Mi
        volumeMounts:
        - name: storage
          mountPath: "/storage"
        ports:
        - name: http
          containerPort: 9000
```
2. Create a bucket on this instance using the `mc` client for example
3. Create a large file (>10Mb)
4. Try to upload it to the freshly created bucket on the MinIO Pod using `mc cp`, it fails :(
5. Try the same thing with `mc cp --disable-multipart` => it works!

## Context
I'm trying to use MinIO as a local fast cache for my object storage, so it needs to run in the same Openshift namespace as my application (therefore it's deployed in Pod) and need to be fast enough to serve hundreds of clients (blob from 1Mb to 1Gb)

## Regression
No

## Your Environment
Minio Version: 2021-11-09T03:21:45Z
Openshift Client Version: 4.7.32
Openshift Server Version: 4.7.12
Kubernetes Version: v1.20.0+df9c838
OS: Linux minio-9-n7jjq 4.18.0-240.22.1.el8_3.x86_64 #1 SMP Thu Mar 25 14:36:04 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux
