### ISSUE TITLE
Base path not working for the consoleIngress

### ISSUE THREAD

**Issue by franroa** [minio/minio#13762]
The ajax calls are not being served because they aren't using the path selected in the ingress

## Expected Behavior
If I add a path in the consoleIngress it should be redirecting all calls, also the ones made with ajax for static resources

## Current Behavior
Given this code:
```
consoleIngress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  path: /minio2(/|$)(.*)
  hosts:
    - localhost
```
I would expect all calls being done to the "mino2" path, but those are the logs from the ingress controller:
```
10.244.0.1 - - [26/Nov/2021:07:31:49 +0000] "GET /minio2 HTTP/1.1" 200 2774 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0" 851 0.002 [minio-minio-console-9001] [] 10.244.3.4:9001 2781 0.004 200 541d978051a0fa8c8bc424d3e494f2b6
10.244.0.1 - - [26/Nov/2021:07:31:49 +0000] "GET /styles/root-styles.css HTTP/1.1" 404 146 "http://localhost:30123/minio2" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0" 793 0.001 [upstream-default-backend] [] 127.0.0.1:8181 146 0.000 404 0dc69e6997035a009919196a51b5cdbb
```

## Steps to Reproduce (for bugs)
Using this values:
```
consoleIngress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  path: /minio2(/|$)(.*)
  hosts:
    - localhost
```
## Context
I am trying to use one nodeport for all my services and put each service under a prefixed path

## Your Environment
* MINIO_VERSION=3.3.0
* Server setup and configuration: I am using kind and a nodeport with the nginx ingress controller
* Operating System and version: Linux francisco-HP-Spectre-x360-Convertible-15-df0xxx 5.11.0-40-generic #44~20.04.2-Ubuntu
