### ISSUE TITLE
Signed URL doesn't work (AWS JS SDK V3)

### ISSUE THREAD

**Issue by bushev** [minio/minio#13779]
After migration to AWS JS SDK V3 file uploads using signed URLs not working.

## Expected Behavior
PUT request should succeed.

## Current Behavior
403 Forbidder error
```
<?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>SignatureDoesNotMatch</Code>
    <Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>
    <Key>text.jpg</Key>
    <BucketName>videogo-files-test</BucketName>
    <Resource>/videogo-files-test/text.jpg</Resource>
    <RequestId>16BC1B96FE896459</RequestId>
    <HostId>f4164f17-e31b-4e3e-9513-465d261c1661</HostId>
</Error>
```

## Steps to Reproduce (for bugs)
1. Generate a signed URL:
```typescript
import { PutObjectCommand, S3 } from '@aws-sdk/client-s3';
import { getSignedUrl } from '@aws-sdk/s3-request-presigner';

const s3 = new S3({
  credentials: {
    accessKeyId: 'accesskey',
    secretAccessKey: 'secretkey'
  },
  region: 'us-east-1',
  forcePathStyle: true,
  endpoint: 'http://127.0.0.1:7011'
});

(async () => {
  const command = new PutObjectCommand({
    Bucket: 'files-test',
    Key: 'text.jpg'
  });

  const url = await getSignedUrl(s3, command, {
    expiresIn: 3600
  });

  console.log(`Signed URL for upload: ${url}`);
})();
```

2. Send PUT request to that URL with a file attached:

![image](https://user-images.githubusercontent.com/7535766/143932377-264ee687-cbb4-4358-be7e-455e2bfc4dec.png)

## Your Environment

Docker compose:

```
  mys3:
    image: minio/minio:RELEASE.2021-11-24T23-19-33Z
    container_name: mys3
    command: server /mnt/data
    environment:
      MINIO_ROOT_USER: accesskey
      MINIO_ROOT_PASSWORD: secretkey
    volumes:
      - ./data/minio:/mnt/data
    ports:
      - 127.0.0.1:7011:9000
```
* Version used (`minio --version`): RELEASE.2021-11-24T23-19-33Z
* Server setup and configuration: Local docker on mac
* Operating System and version (`uname -a`): Darwin Yurys-MacBook-Pro-2.local 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:01 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T6000 arm64
