### ISSUE TITLE
minio via Docker in `gateway nas` mode fails to generate events after container is stopped and restarted 

### ISSUE THREAD

**Issue by dkleissa** [minio/minio#13816]
I'm running minio via the official Docker image and docker compose. The system is running in `gateway nas` mode. I have `etcd` configured and I'm using `rabbitmq` locally for events and setting it all up via env vars.

When I configure a bucket event that includes a prefix it works as expected. e.g.:

```
mc event add alias/bucket arn:minio:sqs::_:amqp --prefix "simple-test/"
```

If I stop the container (i.e. `docker-compose down` or hitting `cntl+c` when running in the foreground) and start it again (i.e. `docker-compose up`), events stop getting emitted by minio. If I remove and re-add the same event configuration, events resume working. e.g.:

```
mc event remove alias/bucket arn:minio:sqs::_:amqp --prefix "simple-test/"
mc event add alias/bucket arn:minio:sqs::_:amqp --prefix "simple-test/"
```

I am ensuring that minio does not start until after the auth provider and rabbitmq are fully up and ready.

I'm not sure if something isn't be persisted properly in `gateway nas` mode? The event configs are there the second time the container is started, but events are not emitted. 

## Expected Behavior

I'd expect minio to load all event configurations and resume emitting events on container stop/start. 

## Current Behavior

When the container starts, any previously configured events do not emit events. If you manipulate event config in a running container it works.

## Possible Solution

As a workaround, you can simply remove and re-add all the events, but this is complex and brittle. 

## Steps to Reproduce (for bugs)

1. Start minio in `gateway nas` mode via Docker. Configure `MINIO_NOTIFY_AMQP_URL` and related env vars using a rabbitmq instance 
2. Add a bucket event configuration (e.g. `mc event add alias/bucket arn:minio:sqs::_:amqp --prefix "simple-test/"`
3. Write an object and see the event get generated
4. Stop the container
5. Start the container
6. Write an object and see NO event is seen in the queue

## Context

I'm using minio in nas mode to expose file shares programmatically via the S3 API. Events are used to do additional processing on certain objects. The container needs to be occasionally restarted or upgraded and event configurations are then effectively lost because events stop.

## Your Environment

* Version used (`minio --version`): `RELEASE.2021-11-09T03-21-45Z`
* Server setup and configuration: 

  Docker container, running `RELEASE.2021-11-09T03-21-45Z` with a slight modification of an additional script during the entrypoint to wait for auth and rabbitmq servers. Auth setup via OIDC. And etcd enabled. A slightly redacted docker-compose file is how it's run:

```
version: '3.7'

services:
  minio:
    build:
      context: ./
      dockerfile: ./datastore/Dockerfile
      args:                                                                      
        AUTH_ENDPOINT: ${AUTH_SERVICE_ENDPOINT}           
    volumes:
      - ${NAS_ROOT}:/container/vol
      - ${CONFIG_DIR}/data/events:/container/events
    expose:
      - "9000"
    user: "${UID}:${GID}"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_ETCD_ENDPOINTS: http://etcd-0:2379
      MINIO_IDENTITY_OPENID_CONFIG_URL: ${AUTH_SERVICE_ENDPOINT}/.well-known/openid-configuration
      MINIO_IDENTITY_OPENID_CLIENT_ID: MyServer
      MINIO_IDENTITY_OPENID_SCOPES: "openid,email,profile,service"
      MINIO_IDENTITY_OPENID_CLAIM_NAME: "nickname"
      MINIO_NOTIFY_AMQP_ENABLE: "on"
      MINIO_NOTIFY_AMQP_URL: "amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672"
      MINIO_NOTIFY_AMQP_EXCHANGE: "service"
      MINIO_NOTIFY_AMQP_EXCHANGE_TYPE: "direct"
      MINIO_NOTIFY_AMQP_ROUTING_KEY: "bucket_notifications"
      MINIO_NOTIFY_AMQP_MANDATORY: "on"
      MINIO_NOTIFY_AMQP_DURABLE: "on"
      MINIO_NOTIFY_AMQP_NO_WAIT: "off"
      MINIO_NOTIFY_AMQP_AUTO_DELETED: "off"
      MINIO_NOTIFY_AMQP_DELIVERY_MODE: 2
      MINIO_NOTIFY_AMQP_QUEUE_DIR: '/container/events'
      MINIO_NOTIFY_AMQP_QUEUE_LIMIT: '100000'
      MINIO_NOTIFY_AMQP_COMMENT: Notification queue for bucket events 
    command: gateway nas /container/vol --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 15s
      timeout: 5s
      retries: 3
    depends_on:
      - reverse-proxy
      - rabbitmq
      - etcd-0
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.minio.rule=Host(`${DOMAIN}`) && (PathPrefix(`/`) || PathPrefix(`/minio`))"
      - "traefik.http.routers.minio.priority=1"
      - "traefik.http.routers.minio.service=minio-store"
      - "traefik.http.services.minio-store.loadbalancer.server.port=9000"
      - "traefik.http.middlewares.ui-redirectregex.redirectregex.regex=^${EXTERNAL_HOSTNAME}/$$"
      - "traefik.http.middlewares.ui-redirectregex.redirectregex.replacement=${EXTERNAL_HOSTNAME}/ui"
      - "traefik.http.routers.minio.middlewares=ui-redirectregex@docker"
    networks:
      - internal
      - web
    restart: always
    deploy:
      mode: replicated
      replicas: 1

  etcd-0:
    image: gcr.io/etcd-development/etcd:v3.3.9
    hostname: etcd-0
    command:
      - etcd
      - --name=etcd-0
      - --data-dir=/etcd-data
      - --advertise-client-urls=http://etcd-0:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --initial-advertise-peer-urls=http://etcd-0:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-cluster=etcd-0=http://etcd-0:2380
      - --initial-cluster-state=new
      - --initial-cluster-token=tkn
    volumes:
      - etcd-0vol:/etcd-data
    ports:
      - "2379:2379"
      - "2380:2380"
    deploy:
      replicas: 1
    restart: always
    networks:
      - internal
```

* Operating System and version (`uname -a`): `Linux a2b39d4efa96 5.8.0-63-generic #71-Ubuntu SMP Tue Jul 13 15:59:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
