### ISSUE TITLE
When setting `MINIO_SERVER_URL`, several issue arise such as not being able to log into the console.

### ISSUE THREAD

**Issue by multinerd** [minio/minio#13859]
## Expected Behavior

When I set `MINIO_SERVER_URL` and `MINIO_BROWSER_REDIRECT_URL` everything should work like it did prior to setting it.

## Current Behavior

When i set the env variables below, I get an error when logging into the console via web.

```
MINIO_SERVER_URL: http://minio.mysite.com
MINIO_BROWSER_REDIRECT_URL: https://console.minio.mysite.com
```

![image](https://user-images.githubusercontent.com/6367998/145081819-9a8771b0-4c56-47c4-b00f-4d4d55d4c4b3.png)

OK, maybe my docker machine doesn't now what `minio.mysite.com` is. 
Lets add an entry in the host file. `172.19.0.2 minio.mysite.com` where the ip is my docker container.

![image](https://user-images.githubusercontent.com/6367998/145085587-45c027eb-00eb-450c-9a1e-88968824e194.png)

OK, you're trying to connect on port `80`. Lets change my `docker-compose` file

```diff
services:
  minio_web2:
    ...
-   command: server --console-address ":9001" --address ":9000" /data
+   command: server --console-address ":9001" --address ":80" /data
    ...

  minio_nginx2:
    ...
    ports:
-      - "5000:9000"  ## Client
+      - "5000:80"  ## Client
      - "5001:9001" ## Console
    ...
```

EUREKA! I'm in.

I believe that minio is appending `--address ":9000"` port to the `MINIO_SERVER_URL` value when trying to log in to the console.

I can log into the console by making the followng changes: 
- add entry to host file `172.19.0.2 minio.mysite.com` where the ip is the docker internal ip.
- update minio default port `--address ":9000"` to `--address ":80"` 
- change the exposed port on nginx to `- "5000:80"  ## Client`

This is not a viable solution because
1. I had to modify my host file.
2. Port 80 cannot be exposed on our main docker machine.

## Possible Solution

Since both client and console is bundled in one docker image, there should be a way for them to communicate internally.
Logging in for example should authenticate internally, while the `MINIO_SERVER_URL` variable is continued to be used to generate a share link.

## Steps to Reproduce (for bugs)

Provided in `Current Behavior` section.

## Context

I am trying to set up minio so that `minio.mysite.com` accesses the api and `console.minio.mysite.com` to access the console.

- minio is hosted in docker, behind nginx on a windows 10 machine. 
- web server is windows 2016 with iis acting as a reverse proxy.

## Regression

not applicable

## Your Environment

* Version used (`minio --version`): RELEASE.2021-11-24T23-19-33Z
* Server setup and configuration: 
1. Windows Server URL Rewrite rules (they just forward the requests to my docker machine)
 - Server (minio.mysite.com)
```xml
<rule name="Docker reverse proxy for minio" enabled="true" stopProcessing="true">
    <match url="(.*)" />
    <action type="Rewrite" url="http://10.200.2.67:5000/{R:1}" appendQueryString="true" logRewrittenUrl="true" />
</rule>
```
 - Console (console.minio.mysite.com)
```xml
<rule name="Docker reverse proxy for minio console" enabled="true" stopProcessing="true">
    <match url="(.*)" />
    <action type="Rewrite" url="http://10.200.2.67:5001/{R:1}" appendQueryString="true" logRewrittenUrl="true" />
</rule>
```
2. Windows 10 (docker machine)
- Docker compose
```yaml
version: '3.7'

networks:
  minio_network2:
    name: minio_network2

services:
  minio_web2:
    image: quay.io/minio/minio:latest
    container_name: minio_web2
    restart: unless-stopped
    command: server --console-address ":9001" --address ":9000" /data
    environment:
      MINIO_ROOT_USER: multinerd@mysite.com
      MINIO_ROOT_PASSWORD: super_secure_password
      MINIO_SERVER_URL: http://minio.mysite.com
      # MINIO_BROWSER_REDIRECT_URL: http://console.minio.mysite.com
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - minio_network2
    volumes:
      - ./minio-data/minio:/data

  minio_nginx2:
    image: nginx:1.19.2-alpine
    container_name: minio_nginx2
    restart: unless-stopped
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "5000:9000"  ## Client
      - "5001:9001" ## Console
    depends_on:
      - minio_web2
    networks:
      - minio_network2
```

- Nginx configs
```nginx
user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections  4096;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;
    sendfile        on;
    keepalive_timeout  65;

    # include /etc/nginx/conf.d/*.conf;

    upstream minio {
        server minio_web2:9000;
    }

    upstream console {
        ip_hash;
        server minio_web2:9001;
    }

    server {
        listen       9000;
        listen  [::]:9000;
        server_name  localhost;

        # To allow special characters in headers
        ignore_invalid_headers off;
        # Allow any size file to be uploaded.
        # Set to a value such as 1000m; to restrict file size to a specific value
        client_max_body_size 0;
        # To disable buffering
        proxy_buffering off;

        location / {
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_connect_timeout 300;
            # Default is HTTP/1, keepalive is only enabled in HTTP/1.1
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            chunked_transfer_encoding off;

            proxy_pass http://minio;
        }
    }

    server {
        listen       9001;
        listen  [::]:9001;
        server_name  localhost;

        # To allow special characters in headers
        ignore_invalid_headers off;
        # Allow any size file to be uploaded.
        # Set to a value such as 1000m; to restrict file size to a specific value
        client_max_body_size 0;
        # To disable buffering
        proxy_buffering off;

        location / {
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-NginX-Proxy true;

            # This is necessary to pass the correct IP to be hashed
            real_ip_header X-Real-IP;

            proxy_connect_timeout 300;
            
            # To support websocket
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            
            chunked_transfer_encoding off;

            proxy_pass http://console;
        }
    }
}

```

* Operating System and version (`uname -a`):
