### ISSUE TITLE
Console Ingress's destination is not the console service. Should be changed.

### ISSUE THREAD

**Issue by etamong** [minio/minio#13887]
I created ingress with a helm chart 'minio/minio', but I couldn't connect to the console with it. So I inspected them by code.

https://github.com/minio/minio/blob/bbbf25201ab3dd8f5e1f4c8e485c76dbfcebe30a/helm/minio/templates/console-ingress.yaml#L39-L52
https://github.com/minio/minio/blob/bbbf25201ab3dd8f5e1f4c8e485c76dbfcebe30a/helm/minio/templates/console-service.yaml#L5-L8
(Let's assume that our release's fullname is `minio` in below code fragments.)

## Expected Behavior

When we create Ingress Object for console service, then it should connect console  service.
like..
```
...

rules:
  - http:
      paths:
        - path:
          pathType: Prefix
          backend:
            service:
              name: minio-console
              port:
                number: 9090

...
```  
Cause console-service's name is `{{ template "minio.fullname" . }}-console`.

## Current Behavior

```
...

rules:
  - http:
      paths:
        - path:
          pathType: Prefix
          backend:
            service:
              name: minio
              port:
                number: 9090

...
```
It'll connect you to the Service `minio`, NOT `minio-console`!

## Possible Solution

Just change serviceName in `console-ingress.yaml`.
Like:
```
...

           name: {{ $fullname }}-console

...
```

**Comment by etamong** [comment]
@harshavardhana  Thanks for quick reply. 
I had to check where my HEAD is... 
BTW, another question.
It looks `console-ingress.yaml` overwrite `ingress.yaml`. ( Both object's `metadata.name` is same, `{{$fullname}}`.)
Is this the intended code?

**Comment by harshavardhana** [comment]
> I had to check where my HEAD is...
> BTW, another question.
> It looks `console-ingress.yaml` overwrite `ingress.yaml`. ( Both object's `metadata.name` is same, `{{$fullname}}`.)
> Is this the intended code?

No it shouldn't overwrite they should be separate @JhoLee

**Comment by harshavardhana** [comment]
Wait I just looked at the code we have 

> {{- $fullName := printf "%s-console" (include "minio.fullname" .) -}}

So this is used internally everywhere, looks like I need to revert the changes.

**Comment by harshavardhana** [comment]
```yaml
# Source: minio/templates/console-ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-1639245456-console
  namespace: "default"
  labels:
    app: minio
    chart: minio-3.3.4
    release: minio-1639245456
    heritage: Helm
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio-1639245456-console
                port: 
                  number: 9001
      host: "console.chart-example.local"
---
# Source: minio/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-1639245456
  namespace: "default"
  labels:
    app: minio
    chart: minio-3.3.4
    release: minio-1639245456
    heritage: Helm
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio-1639245456
                port: 
                  number: 9000
      host: "chart-example.local"

```

Here is the generated ingress they are separate.
