### ISSUE TITLE
Broken _FILE variables

### ISSUE THREAD

**Issue by ElisDN** [minio/minio#13981]
When I use `*_FILE` variables with secret files:

```
# docker-compose.yml

version: '3.9'
services:
    storage:
        image: minio/minio
        environment:
            MINIO_ROOT_USER: app
            MINIO_ROOT_PASSWORD_FILE: /run/secrets/aws_secret_access_key
        secrets:
            - aws_secret_access_key
secrets:
   aws_secret_access_key:
        file: ./secrets/aws_secret_access_key
```

this variables do not work.

## Expected Behavior
Successfully login in Dashboard and aws-cli

## Current Behavior
`Invalid Login` in Dashboard
`SignatureDoesNotMatch` in aws-cli

## Regression
#13883

## Your Environment

* Version used (`minio --version`): RELEASE.2021-12-20T22-07-16Z
* Server setup and configuration: Docker Compose

**Comment by harshavardhana** [comment]
Either your use all files or all environment not both.

**Comment by ElisDN** [comment]
> Either your use all files or all environment not both.

All files do not work too.

**Comment by ElisDN** [comment]
> Either your use all files or all environment not both.

I have already fixed it in #12813 before.

**Comment by harshavardhana** [comment]
Of course, it is working @ElisDN you just have the wrong container locally

```yaml
# docker-compose.yml

version: '3.3'
services:
    storage:
        image: minio/minio:RELEASE.2021-12-20T22-07-16Z
        command: server --console-address ":9001" /data
        environment:
            MINIO_ROOT_USER: app
            MINIO_ROOT_PASSWORD_FILE: /run/secrets/aws_secret_access_key
            _MINIO_SERVER_DEBUG: "on"
        secrets:
            - aws_secret_access_key
secrets:
   aws_secret_access_key:
        file: ./aws_secret_access_key
```

```
~  cat /tmp/aws_secret_access_key 
mysecret
```

```
~ docker-compose -f /tmp/compose.yml up
...
Starting tmp_storage_1 ... done
Attaching to tmp_storage_1
storage_1  | API: http://172.21.0.2:9000  http://127.0.0.1:9000 
storage_1  | 
storage_1  | Console: http://172.21.0.2:9001 http://127.0.0.1:9001 
storage_1  | 
storage_1  | Documentation: https://docs.min.io
storage_1  | == DEBUG Mode enabled ==
storage_1  | Currently set environment settings:
storage_1  | MINIO_ACCESS_KEY_FILE=access_key
storage_1  | _MINIO_SERVER_DEBUG=on
storage_1  | HOSTNAME=633ae829f62e
storage_1  | MINIO_KMS_SECRET_KEY_FILE=kms_master_key
storage_1  | MINIO_ROOT_USER=app
storage_1  | container=oci
storage_1  | PWD=/
storage_1  | HOME=/root
storage_1  | MINIO_ROOT_USER_FILE=access_key
storage_1  | MINIO_ROOT_PASSWORD_FILE=/run/secrets/aws_secret_access_key
storage_1  | SHLVL=0
storage_1  | MINIO_UPDATE_MINISIGN_PUBKEY=RWTx5Zr1tiHQLwG9keckT0c45M3AGeHD6IvimQHpyRywVWGbP1aVSGav
storage_1  | MINIO_SECRET_KEY_FILE=secret_key
storage_1  | PATH=/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
storage_1  | MINIO_CONFIG_ENV_FILE=config.env
storage_1  | MINIO_ROOT_PASSWORD=mysecret
storage_1  | 
storage_1  | CONSOLE_PBKDF_SALT=015cea6f-91df-4e51-9fc6-4b6a06cb3052
storage_1  | CONSOLE_PBKDF_PASSPHRASE=015cea6f-91df-4e51-9fc6-4b6a06cb3052
storage_1  | CONSOLE_MINIO_SERVER=http://172.21.0.2:9000
storage_1  | CONSOLE_MINIO_REGION=
storage_1  | CONSOLE_CERT_PASSWD=
storage_1  | ======
storage_1  | 2021/12/23 17:09:09 Serving console at http://[::]:9001

```

Check that 

```
storage_1  | MINIO_ROOT_PASSWORD=mysecret
```

Is properly set.
