### ISSUE TITLE
RAM usage is always growing until OOMKill

### ISSUE THREAD

**Issue by mortrevere** [minio/minio#14036]
## Expected Behavior

I expect MinIO to run without consuming an ever-increasing amount of RAM.

## Current Behavior
I'm filling a bug report because the RAM usage keeps growing no matter what, until instances gets OOMKill from the system.
Here is a screenshot of RAM usage over 7 days : 
![image](https://user-images.githubusercontent.com/1038894/148363419-d9d45589-fdff-4835-a433-0dc94fd8c105.png)

Sudden drops are due to the system killing MinIO for taking up too much RAM.

## Steps to Reproduce (for bugs)
Nothing special was done to get this bug. Just install MinIO on 4 identical nodes with the following docker configuration : 
```
container:
    - name: minio
    - image: quay.io/minio/minio:RELEASE.2021-10-23T03-28-24Z
    - network_mode: host
    - restart: unless-stopped
    - environment:
      - MINIO_ACCESS_KEY: xxxx
      - MINIO_SECRET_KEY: xxxx
      - MINIO_PROMETHEUS_AUTH_TYPE: "public"
    - binds:
      - /srv/minio/data:/data
    - command:
      - server
      - http://minio{1...4}-xxxx:9000/data
```

## Context
This issue affects us because we have nodes randomly failing, sometimes concurrently, resulting in downtimes on our storage backend.

## Regression
Not sure if this is a regression, as this has been happening from day one of our setup.

## Your Environment

* Version used (`minio --version`): 2021-10-23T03:28:24Z
* Server setup and configuration: Each node is identical, bare-metal servers with 12 CPU, 32G RAM and 512G of NVMe SSD.
* Operating System and version (`uname -a`): 4.19.0-18-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64 GNU/Linux

I am running MinIO with the following setup : 

```
●  minio1-xxxx:9000
   Uptime: 1 day 
   Version: 2021-10-23T03:28:24Z
   Network: 4/4 OK 
   Drives: 1/1 OK 

●  minio2-xxxx:9000
   Uptime: 17 hours 
   Version: 2021-10-23T03:28:24Z
   Network: 4/4 OK 
   Drives: 1/1 OK 

●  minio3-xxxx:9000
   Uptime: 14 hours 
   Version: 2021-10-23T03:28:24Z
   Network: 4/4 OK 
   Drives: 1/1 OK 

●  minio4-xxxx:9000
   Uptime: 17 hours 
   Version: 2021-10-23T03:28:24Z
   Network: 4/4 OK 
   Drives: 1/1 OK 

558 MiB Used, 435 Buckets, 41,482 Objects
4 drives online, 0 drives offline
```

Nothing special is happening, just a few read & write done continuously during the day. The number of concurrent connections on a given node never exceeds 200.
