### ISSUE TITLE
Keycloak IDP, policy claim missing from the JWT token, credentials will not be generated

### ISSUE THREAD

**Issue by Memo99** [minio/minio#14061]
## Expected Behavior
Login with Keycloak as IDP via Console / WebIdentity.go and list buckets

## Current Behavior
policy claim missing from the JWT token, credentials will not be generated error

## Possible Solution
Fix the policy parsing ?

## Steps to Reproduce (for bugs)
1. Created minio client in keycloak, done the necessary settings with mappers and redirects like stated in the docs
2. Added attribute consoleAdmin (also tried with readwrite) to user
3. Go to console URL, login to keycloak with user
4. Getting token (can see in mc admin trace and also in webidentity.go)
5. Token has policy  "policy": "readwrite" in jwt
6. Console returns error policy claim missing

mc admin trace log:

```
10.244.2.191:9000 [REQUEST sts.AssumeRoleWithWebIdentity] [2022-01-08T17:45:04:000] [Client IP: 10.244.2.191]
10.244.2.191:9000 POST /?Action=AssumeRoleWithWebIdentity&DurationSeconds=3600&Version=2011-06-15&WebIdentityToken=ey...
10.244.2.191:9000 Proto: HTTP/1.1
10.244.2.191:9000 Host: 10.244.2.191:9000
10.244.2.191:9000 User-Agent: Go-http-client/1.1
10.244.2.191:9000 Content-Length: 0
10.244.2.191:9000
10.244.2.191:9000 [RESPONSE] [2022-01-08T17:45:04:000] [ Duration 872µs  ↑ 31 B  ↓ 640 B ]
10.244.2.191:9000 400 Bad Request
10.244.2.191:9000 Strict-Transport-Security: max-age=31536000; includeSubDomains
10.244.2.191:9000 Vary: Origin
10.244.2.191:9000 X-Amz-Request-Id: 16C85959753B3BFD
10.244.2.191:9000 X-Xss-Protection: 1; mode=block
10.244.2.191:9000 Content-Length: 315
10.244.2.191:9000 Content-Type: application/xml
10.244.2.191:9000 Server: MinIO
10.244.2.191:9000 Accept-Ranges: bytes
10.244.2.191:9000 Content-Security-Policy: block-all-mixed-content
10.244.2.191:9000 X-Content-Type-Options: nosniff
10.244.2.191:9000 <?xml version="1.0" encoding="UTF-8"?>
<ErrorResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/"><Error><Type></Type><Code>InvalidParameterValue</Code><Message> policy claim missing from the JWT token, credentials will not be generated</Message></Error><RequestId>16C85959753B3BFD</RequestId></ErrorResponse>
```
JWT content:

```
"iat": 1641588436,
  "auth_time": 1641588373,
  "jti": "4b5cacb8-c214-4c95-b290-c9a1ce3cb0e7",
  "iss": "https://auth.example.com.tr/auth/realms/example",
  "aud": [
    "minio",
    "listings-backend"
  ],
  "sub": "0e49e36d-f08f-4eb3-9ec8-84a8e6bfe2ff",
  "typ": "ID",
  "azp": "minio",
  "session_state": "73d57924-ada3-4948-9806-67c528a4c5aa",
  "at_hash": "1jOliP2iZ4dF_Y9RKoTSuQ",
  "acr": "0",
  "sid": "73d57924-ada3-4948-9806-67c528a4c5aa",
  "upn": "xxx",
  "email_verified": false,
  "address": {},
  "name": "xxx",
  "groups": [
    "offline_access",
    "uma_authorization",
    "default-roles-example"
  ],
  "preferred_username": "xxx",
  "given_name": "xxx",
  "family_name": "xxx",
  "email": "xxx",
  "policy": "consoleAdmin"
}
```

## Context
Trying to login with Keycloak-SSO on kubernetes cluster, want to use minio as object storage for my web application. 

## Regression
No

## Your Environment
- Minio:latest is running as baremetal in kubernetes with single pod and service
- Keycloak is running in the same cluster
- ingress-nginx as reverse proxy with cors settings

## Keycloak settings
![image](https://user-images.githubusercontent.com/10103729/148655596-70c650c2-5e06-4513-9e9f-50cba5db1040.png)

## Policy
![image](https://user-images.githubusercontent.com/10103729/148655603-75d2492c-36c3-4765-9412-d169aa3b2338.png)

## User attribute
![image](https://user-images.githubusercontent.com/10103729/148655621-a239751d-1c22-4958-8e52-3e7b0f407ab2.png)

**Comment by harshavardhana** [comment]
@Memo99 what did you set as `MINIO_IDENTITY_OPENID_CLAIM_NAME=` ?

**Comment by Memo99** [comment]
Hi @harshavardhana  Thank you for your reply. I attached the .yaml file below.

## kubernetes deployment file

default value "policy"

```
apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    app: minio
spec:
  ports:
    - name: http
      port: 9000
      targetPort: 9000
    - name: console
      port: 9001
      targetPort: 9001
  selector:
    app: minio
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  labels:
    app: minio
spec:
  selector:
    matchLabels:
      app: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        # Label is used as selector in the service.
        app: minio
    spec:
      containers:
      - name: minio
        # Pulls the default Minio image from Docker Hub
        image: minio/minio:latest
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "999m"
        args:
        - server 
        - --console-address 
        - :9001
        - /storage
        env:
        # Minio access key and secret key
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: minio
              key: MINIO_ACCESS_KEY
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: minio
              key: MINIO_SECRET_KEY
        - name: MINIO_IDENTITY_OPENID_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: minio
              key: MINIO_IDENTITY_OPENID_CLIENT_SECRET
        - name: MINIO_BROWSER_REDIRECT_URL
          value: https://console.storage.example.com
        - name: MINIO_IDENTITY_OPENID_CONFIG_URL
          value: https://auth.example.com/auth/realms/example/.well-known/openid-configuration
        - name: MINIO_IDENTITY_OPENID_CLIENT_ID
          value: minio
        - name: MINIO_IDENTITY_OPENID_CLAIM_NAME
          value: policy
        - name: MINIO_IDENTITY_OPENID_REDIRECT_URI
          value: https://console.storage.example.com/oauth_callback
        ports:
        - containerPort: 9000
          hostPort: 9000
        - containerPort: 9001
          hostPort: 9001
        # Mount the volume into the pod
        volumeMounts:
        - name: storage-volume # must match the volume name, above
          mountPath: "/storage"
      

      volumes:
      - name: storage-volume
        persistentVolumeClaim:
          # Name of the PVC created earlier
          claimName: storage-pvc
```
