### ISSUE TITLE
AWS S3 Gateway and Combination of Cache generates I/O errors on Ranged Request

### ISSUE THREAD

**Issue by DiegoPino** [minio/minio#14204]
Hi, we are experiencing something similar to https://github.com/minio/minio/issues/8504 but using `docker-compose` with AWS S3 Gateway  in Combination with Caching.

Never before without caching. Errors only happen when a RANGED request is issued and are all of `read/write on closed pipe` type
Setting `MINIO_CACHE_RANGE: "off"` eliminates the errors.

e.g 
```Shell
API: GetObject(bucket=archipelago-hosting-1c090abe-2a7e-4d2a-9409-5d05e67b93fe, object=media/19e/application-altered-states-8d716848-3691-4aa8-9e77-eeb5f9d9c1da.wacz)
Time: 14:50:30 UTC 01/28/2022
DeploymentID: 3dab5c9d-eca5-448b-821b-81165e87d576
RequestID: 16CE76B449977CA3
RemoteHost: 172.18.0.4
Host: esmero-minio:9000
UserAgent: aws-sdk-php/3.204.2 OS/Linux/5.10.82-83.359.amzn2.aarch64 lang/php/7.4.20 GuzzleHttp/6.5.5 curl/7.77.0 PHP/7.4.20
Error: io: read/write on closed pipe (*errors.errorString)
       5: cmd/api-errors.go:2103:cmd.toAPIErrorCode()
       4: cmd/api-errors.go:2128:cmd.toAPIError()
       3: cmd/object-handlers.go:517:cmd.objectAPIHandlers.getObjectHandler()
       2: cmd/object-handlers.go:575:cmd.objectAPIHandlers.GetObjectHandler()
       1: net/http/server.go:2047:http.HandlerFunc.ServeHTTP()
```      

## Expected Behavior
No errors on ranged requests on cached Objects.

## Current Behavior
Error: io: read/write on closed pipe when issuing a Ranged request. This errors are permeating into our Client APP (using AWS S3 Client PHP library)

## Steps to Reproduce (for bugs)

1.  Upload an OBJECT to an AWS S3 Bucket
2. Setup MIN.IO to use S3 AWS Gateway in combination with default cache (Using e.g a standard IAM inline policy that ALLOW access to Get*, List*, Abort* to that bucket and bucket/* + general applicable to any resources with s3:ListAllMyBuckets
3. ISSUE ranged request to that OBJECT with offsets
4. Look at your minio logs (docker logs -f)

## Context
We have ranged requests to S3 to allow very large `WACZ` files (Zipped Webarchive with a TOC that allows us identify resource offsets and then request those via normal RANGED http request) to be fetched in real time. Without Caching enabled these ranged requests work perfectly and gateway (and also when using local MIN.IO storage) work well.

## Regression
No (but not sure, first time we test with Caching in production)

## Your Environment
* Version used: minio version RELEASE.2022-01-08T03-11-54Z
* Server setup and configuration: Via docker-compose, AWS S3 Gateway, Basic Cache one (including ranged requests) with a dedicated partition (correctly formatted/mounted) for this. 
* Operating System and version (`uname -a`):  aarch64 aarch64 aarch64 GNU/Linux

**Comment by harshavardhana** [comment]
> Error: io: read/write on closed pipe when issuing a Ranged request. This errors are permeating into our Client APP (using AWS S3 Client PHP library)

Can you share a sample code @DiegoPino ?

**Comment by poornas** [comment]
@DiegoPino , can you share your cache env? I was not able to repro any error with `MINIO_CACHE_RANGE=on`

**Comment by DiegoPino** [comment]
Hi @harshavardhana and @poornas , thanks so much for getting back to me:

Regarding code: we use PHP and we are using the official AWS PHP Library with the S3 Stream Wrapper (used like s3://bucket/name) mediated through Drupal, so code is a bit more complex (e.g I have to do byte to byte copying) but worked perfectly so far (for a few months already) directly on AWS S3, and Minio via local storage, Minio AWS S3 Gateway and also using Azure Gateway but I'm new to Minio Caching so never saw this error before.

This is the relevant code where I pass the request from the controller back to the wrapper

https://github.com/esmero/format_strawberryfield/blob/1d2e51d2b3d0ef07f5f6fbf5d12499e7f62b7895/src/Component/HttpFoundation/RangedRemoteFileRespone.php#L85-L113

And the actual delivery here where I copy bytes back to front 

https://github.com/esmero/format_strawberryfield/blob/1d2e51d2b3d0ef07f5f6fbf5d12499e7f62b7895/src/Component/HttpFoundation/RangedRemoteFileRespone.php#L136-L168

I can also test simply hitting via CURL the same ranges over and over (hit it hard) to trigger the error. Should be the same really. Important to note that we are not internally hitting the ranges. There are APPS (JS, JS Workers) that know how to read that TC in this large files and request concurrently those Ranges. So maybe concurrency might be the issue here. Here is an example of the full integration with the replay.web app reading that large Webarchive and reconstructing on the fly from S3 a website that can be navigated.

re Cache env:
```YML
 minio:
    container_name: esmero-minio
    restart: always
    image: minio/minio:latest
    volumes:
      - ${ARCHIPELAGO_ROOT}/data_storage/minio-data:/data:cached
      - /mnt/data/cache:/cache
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - host-net
      - esmero-net
    environment:
      MINIO_HTTP_TRACE: /tmp/minio-log.txt
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
      MINIO_CACHE_DRIVES: /cache
      MINIO_CACHE_EXCLUDE: "*.json,*.jpg,*.jpeg"
      MINIO_CACHE_QUOTA: 80
      # MINIO_CACHE_RANGE: "off"  --> with off no errors, without "on" just the default errors 
      MINIO_CACHE_AFTER: 3
      MINIO_CACHE_WATERMARK_LOW: 70
      MINIO_CACHE_WATERMARK_HIGH: 90
    command: gateway s3 https://s3.amazonaws.com/ --console-address ":9001"
```

and /mnt/data/cache is an Xfs drive/partition (host/Linux) mounted with
`UUID=db66a6cd-115c-4d6f-8e1b-eb3ce23ba99e     /mnt/data   xfs    defaults,relatime,nofail  0  2`

Hope this helps. Thanks!
