### ISSUE TITLE
2022-02-01 release broke docker-compose workflow

### ISSUE THREAD

**Issue by waxlamp** [minio/minio#14235]
## Expected Behavior

`docker-compose` workflow should continue working after updating to last night's image.

## Current Behavior

MinIO container starts up but hangs without printing its status as expected; other containers in the compose setup cannot reach it, and neither can I.

## Steps to Reproduce (for bugs)

1. Save this text as `docker-compose.yml`:

```yaml
version: '3'
services:
  minio:
    image: minio/minio:RELEASE.2022-01-28T02-28-16Z
    tty: true
    command: ["server", "/data", "--console-address", ":9001"]
    environment:
      MINIO_ROOT_USER: minioAccessKey
      MINIO_ROOT_PASSWORD: minioSecretKey
    ports:
      - 9000:9000
      - 9001:9001

  minio-broken:
    image: minio/minio:RELEASE.2022-02-01T18-00-14Z
    tty: true
    command: ["server", "/data", "--console-address", ":9001"]
    environment:
      MINIO_ROOT_USER: minioAccessKey
      MINIO_ROOT_PASSWORD: minioSecretKey
    ports:
      - 9090:9000
      - 9091:9001
```

2. Run `docker-compose up`.

This runs two MinIO containers, one from last night's release, and one from the release before that.

Note that http://localhost:9000 redirects to the MinIO login page, while http://localhost:9090 does not. Note also that only one successful status message appears on the console.

## Context

This broke a docker compose workflow that was specifying `minio/minio:latest` as the image to use. My workaround is to pin to the last working release instead.

## Regression

Seems to be. I don't know which commit was the breaking change, but the release last night exhibits the problem.

## Your Environment

* Version used (`minio --version`): see above
* Server setup and configuration: docker version 20.10.7, build v20.10.7, docker-compose version 1.28.6, build unknown
* Operating System and version (`uname -a`): n/a (I will provide this info if really needed)
