### ISSUE TITLE
The authorization header is malformed; the region is wrong; expecting 'us-east-1'.

### ISSUE THREAD

**Issue by mr-manuel** [minio/minio#14259]
## Expected Behavior
Login to the MinIO console after update to the latest version should work as expected, when I try to login through https://minio.domain.name:4001 (console url)

## Current Behavior
Instead I get `The authorization header is malformed; the region is wrong; expecting 'us-east-1'.` Even if the consigured region is us-east-1.

## Steps to Reproduce (for bugs)

1. Update to version `RELEASE.2022-02-05T04-40-59Z`
2. Try to login in the MinIO console

## Regression
Is this issue a regression? Yes
If Yes, optionally please include minio version or commit id or PR# that caused this regression, if you have these details: With `RELEASE.2022-02-01T18-00-14Z` the login worked and with `RELEASE.2022-02-05T04-40-59Z` the login stopped working.

## Your Environment

* Version used (`minio --version`): `RELEASE.2022-02-05T04-40-59Z`
* Server setup and configuration: Docker container on QNAP NAS with single disk (docker compose file below)
* Operating System and version (`uname -a`):  `Linux 5.10.60-qnap minio/minio#1 SMP Tue Dec 21 08:47:58 CST 2021 x86_64 GNU/Linux`

* Docker compose file:
```yml
version: '3.9'
services:
  minio:
    container_name: minio
    restart: always
    image: minio/minio:latest
    command: server --address ":4000" --console-address ":4001" /data
    volumes:
      - '${MINIO_ROOT_PATH}:/data'
      - '${MINIO_ROOT_PATH}/.minio:/root/.minio'
    network_mode: host
    environment:
      - 'MINIO_ROOT_USER=${MINIO_ROOT_USER}'
      - 'MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}'
      - 'MINIO_SERVER_URL=https://minio.domain.name:4000'
    extra_hosts:
      - 'minio.domain.name:127.0.0.1'
```
