### ISSUE TITLE
Helm chart service ports and target ports

### ISSUE THREAD

**Issue by mprahlkamps** [minio/minio#14253]
The helm chart provides four variables to control minio ports and service ports:

```
minioAPIPort: "9000"
minioConsolePort: "9001"

service:
  port: "9000"
consoleService:
  port: "9001"
```

I use the LoadBalancer service type and would like to be able to change the exposed port without having to change the internal port.
This is currently not possible because the `targetPort` of the service is automatically set.

I think it would be enough to change the variable [in this line](https://github.com/minio/minio/blob/0256dae6576af19f6357b7d97fa935e7a62058ce/helm/minio/templates/service.yaml#L39) and replace the hardcoded port number with `.Values.minioAPIPort`

and [in this line](https://github.com/minio/minio/blob/0256dae6576af19f6357b7d97fa935e7a62058ce/helm/minio/templates/console-service.yaml#L38) replace `.Values.consoleService.port` with `.Values.minioConsolePort`

## Your Environment
* Minio 3.5.0
