### ISSUE TITLE
prometheus metric is not working if a node is down

### ISSUE THREAD

**Issue by fcomte** [minio/minio#14280]
When a node is down I think that minio is failing to report metrics on the nodes who is working.

## Expected Behavior
We expect that remaining minio in the cluster can report metrics.

## Current Behavior
```
coder@vscode-234304-5c5dc5c56b-kfcrs:~/work$ mc admin info infra
●  minio-infrastructure-pool-0-0.minio-infrastructure-hl.minio-infra.svc.cluster.local:9000
   Uptime: offline
   Drives: 0/2 OK 

●  minio-infrastructure-pool-0-1.minio-infrastructure-hl.minio-infra.svc.cluster.local:9000
   Uptime: 2 days 
   Version: 2022-01-04T07:41:07Z
   Network: 2/3 OK 
   Drives: 2/2 OK 

●  minio-infrastructure-pool-0-2.minio-infrastructure-hl.minio-infra.svc.cluster.local:9000
   Uptime: 20 minutes 
   Version: 2022-01-04T07:41:07Z
   Network: 2/3 OK 
   Drives: 2/2 OK 

543 GiB Used, 10 Buckets, 20,765 Objects
4 drives online, 2 drives offline
```

all prometheus access are failing on the remaining two nodes.
I see this error logs

```
minio-infrastructure-pool-0-2.minio-infrastructure-hl.minio-infra.svc.cluster.local  API: SYSTEM()
minio-infrastructure-pool-0-2.minio-infrastructure-hl.minio-infra.svc.cluster.local  Time: 14:33:10 UTC 02/09/2022
minio-infrastructure-pool-0-2.minio-infrastructure-hl.minio-infra.svc.cluster.local  DeploymentID: 6460ce2f-6620-40a3-b68d-4364ff83d2a0
minio-infrastructure-pool-0-2.minio-infrastructure-hl.minio-infra.svc.cluster.local  Error: /getbucketstats "https://minio-infrastructure-pool-0-0.minio-infrastructure-hl.minio-infra.svc.cluster.local:9000/minio/peer/v17": remote server offline (*rest.NetworkError)
minio-infrastructure-pool-0-2.minio-infrastructure-hl.minio-infra.svc.cluster.local  peerAddress=minio-infrastructure-pool-0-0.minio-infrastructure-hl.minio-infra.svc.cluster.local:9000
minio-infrastructure-pool-0-2.minio-infrastructure-hl.minio-infra.svc.cluster.local         8: cmd/notification.go:610:cmd.(*NotificationSys).GetClusterBucketStats()
minio-infrastructure-pool-0-2.minio-infrastructure-hl.minio-infra.svc.cluster.local         7: cmd/bucket-replication.go:1795:cmd.getLatestReplicationStats()
minio-infrastructure-pool-0-2.minio-infrastructure-hl.minio-infra.svc.cluster.local         6: cmd/metrics-v2.go:1464:cmd.getBucketUsageMetrics.func1()
minio-infrastructure-pool-0-2.minio-infrastructure-hl.minio-infra.svc.cluster.local         5: cmd/metrics-v2.go:224:cmd.(*MetricsGroup).RegisterRead.func1.1()
minio-infrastructure-pool-0-2.minio-infrastructure-hl.minio-infra.svc.cluster.local         4: cmd/utils.go:910:cmd.(*timedValue).Get()
minio-infrastructure-pool-0-2.minio-infrastructure-hl.minio-infra.svc.cluster.local         3: cmd/metrics-v2.go:238:cmd.(*MetricsGroup).Get()
minio-infrastructure-pool-0-2.minio-infrastructure-hl.minio-infra.svc.cluster.local         2: cmd/metrics-v2.go:1737:cmd.populateAndPublish()
minio-infrastructure-pool-0-2.minio-infrastructure-hl.minio-infra.svc.cluster.local         1: cmd/metrics-v2.go:1702:cmd.ReportMetrics.func1()
```

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

Version is RELEASE.2022-01-04T07-41-07Z

**Comment by harshavardhana** [comment]
@fcomte I can't seem to reproduce this - what do you mean when Prometheus metrics don't work? - you know you need to only scrape a single endpoint. 

And that single endpoint is the ClusterIP for the tenant service that is deployed.

**Comment by harshavardhana** [comment]
> minio-infrastructure-pool-0-2.minio-infrastructure-hl.minio-infra.svc.cluster.local  API: SYSTEM()
> minio-infrastructure-pool-0-2.minio-infrastructure-hl.minio-infra.svc.cluster.local  Time: 14:33:10 UTC 02/09/2022
> minio-infrastructure-pool-0-2.minio-infrastructure-hl.minio-infra.svc.cluster.local  DeploymentID: 6460ce2f-6620-40a3-b68d-4364ff83d2a0
> minio-infrastructure-pool-0-2.minio-infrastructure-hl.minio-infra.svc.cluster.local  Error: /getbucketstats "https://minio-infrastructure-pool-0-0.minio-infrastructure-hl.minio-infra.svc.cluster.local:9000/minio/peer/v17": remote server offline (*rest.NetworkError)
> minio-infrastructure-pool-0-2.minio-infrastructure-hl.minio-infra.svc.cluster.local  peerAddress=minio-infrastructure-pool-0-0.minio-infrastructure-hl.minio-infra.svc.cluster.local:9000
> minio-infrastructure-pool-0-2.minio-infrastructure-hl.minio-infra.svc.cluster.local         8: cmd/notification.go:610:cmd.(*NotificationSys).GetClusterBucketStats()
> minio-infrastructure-pool-0-2.minio-infrastructure-hl.minio-infra.svc.cluster.local         7: cmd/bucket-replication.go:1795:cmd.getLatestReplicationStats()
> minio-infrastructure-pool-0-2.minio-infrastructure-hl.minio-infra.svc.cluster.local         6: cmd/metrics-v2.go:1464:cmd.getBucketUsageMetrics.func1()
> minio-infrastructure-pool-0-2.minio-infrastructure-hl.minio-infra.svc.cluster.local         5: cmd/metrics-v2.go:224:cmd.(*MetricsGroup).RegisterRead.func1.1()
> minio-infrastructure-pool-0-2.minio-infrastructure-hl.minio-infra.svc.cluster.local         4: cmd/utils.go:910:cmd.(*timedValue).Get()
> minio-infrastructure-pool-0-2.minio-infrastructure-hl.minio-infra.svc.cluster.local         3: cmd/metrics-v2.go:238:cmd.(*MetricsGroup).Get()
> minio-infrastructure-pool-0-2.minio-infrastructure-hl.minio-infra.svc.cluster.local         2: cmd/metrics-v2.go:1737:cmd.populateAndPublish()
> minio-infrastructure-pool-0-2.minio-infrastructure-hl.minio-infra.svc.cluster.local         1: cmd/metrics-v2.go:1702:cmd.ReportMetrics.func1()

This log is internal it has nothing to do with what metrics is displayed.

**Comment by harshavardhana** [comment]
Here is my setup a simple 4 node setup using docker-compose.yaml

```yaml

version: '3.7'

# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: minio/minio:latest
  command: server --console-address ":9001" http://minio{1...4}/data{1...2}
  expose:
    - "9000"
    - "9001"
  environment:
    MINIO_ROOT_USER: minio
    MINIO_ROOT_PASSWORD: minio123
    MINIO_PROMETHEUS_AUTH_TYPE: "public"
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3

# starts 4 docker containers running minio server instances.
# using nginx reverse proxy, load balancing, you can access
# it through port 9000.
services:
  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - /home/harsha/data1-1:/data1
      - /home/harsha/data1-2:/data2

  minio2:
    <<: *minio-common
    hostname: minio2
    volumes:
      - /home/harsha/data2-1:/data1
      - /home/harsha/data2-2:/data2

  minio3:
    <<: *minio-common
    hostname: minio3
    volumes:
      - /home/harsha/data3-1:/data1
      - /home/harsha/data3-2:/data2

  minio4:
    <<: *minio-common
    hostname: minio4
    volumes:
      - /home/harsha/data4-1:/data1
      - /home/harsha/data4-2:/data2

  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4

```

```
~ docker-compose -f docker-compose.yaml up
```

```
~  curl -s http://localhost:9000/minio/v2/metrics/cluster  |grep minio_software_version_info
# HELP minio_software_version_info MinIO Release tag for the server
# TYPE minio_software_version_info gauge
minio_software_version_info{server="minio1:9000",version="2022-02-07T08:17:33Z"} 0
minio_software_version_info{server="minio2:9000",version="2022-02-07T08:17:33Z"} 0
minio_software_version_info{server="minio3:9000",version="2022-02-07T08:17:33Z"} 0
minio_software_version_info{server="minio4:9000",version="2022-02-07T08:17:33Z"} 0
```

All running fine now take down one node

```
~ docker ps |grep minio
6020fda333c4   nginx:1.19.2-alpine             "/docker-entrypoint.…"   About a minute ago   Up About a minute             80/tcp, 0.0.0.0:9000-9001->9000-9001/tcp, :::9000-9001->9000-9001/tcp   minio_nginx_1
fe12cfc88d45   minio/minio:latest              "/usr/bin/docker-ent…"   About a minute ago   Up About a minute (healthy)   9000-9001/tcp                                                           minio_minio4_1
8eb387995a68   minio/minio:latest              "/usr/bin/docker-ent…"   About a minute ago   Up About a minute (healthy)   9000-9001/tcp                                                           minio_minio2_1
3829187ca0f0   minio/minio:latest              "/usr/bin/docker-ent…"   About a minute ago   Up About a minute (healthy)   9000-9001/tcp                                                           minio_minio1_1
3ffc46df2d35   minio/minio:latest              "/usr/bin/docker-ent…"   About a minute ago   Up About a minute (healthy)   9000-9001/tcp                                                           minio_minio3_1
```

```
~ docker stop minio_minio2_1
minio_minio2_1
```

```
~ curl -s http://localhost:9000/minio/v2/metrics/cluster  |grep minio_software_version_info

# HELP minio_software_version_info MinIO Release tag for the server
# TYPE minio_software_version_info gauge
minio_software_version_info{server="minio1:9000",version="2022-02-07T08:17:33Z"} 0
minio_software_version_info{server="minio3:9000",version="2022-02-07T08:17:33Z"} 0
minio_software_version_info{server="minio4:9000",version="2022-02-07T08:17:33Z"} 0
```

```
~ curl -s http://localhost:9000/minio/v2/metrics/cluster  |grep minio_software_version_info
# HELP minio_software_version_info MinIO Release tag for the server
# TYPE minio_software_version_info gauge
minio_software_version_info{server="minio1:9000",version="2022-02-07T08:17:33Z"} 0
minio_software_version_info{server="minio3:9000",version="2022-02-07T08:17:33Z"} 0
minio_software_version_info{server="minio4:9000",version="2022-02-07T08:17:33Z"} 0
```

```
~ curl -s http://localhost:9000/minio/v2/metrics/cluster  |grep nodes_offline
# HELP minio_cluster_nodes_offline_total Total number of MinIO nodes offline.
# TYPE minio_cluster_nodes_offline_total gauge
minio_cluster_nodes_offline_total{server="minio1:9000"} 1
```

```
~ curl -s http://localhost:9000/minio/v2/metrics/cluster  |grep nodes_online
# HELP minio_cluster_nodes_online_total Total number of MinIO nodes online.
# TYPE minio_cluster_nodes_online_total gauge
minio_cluster_nodes_online_total{server="minio1:9000"} 3
``` 

Looks like the Prometheus should be working as intended.
