### ISSUE TITLE
Helm Chart -  Create PVC when mode gateway type nas

### ISSUE THREAD

**Issue by dboc** [minio/minio#14303]
**Is your feature request related to a problem? Please describe.**

The Helm Chart do not create a PVC when set the mode "gateway" type "nas". 
See the PVC template here : https://github.com/minio/minio/blob/master/helm/minio/templates/pvc.yaml
There is an IF : ```{{- if eq .Values.mode "standalone" }} ``` that just create the PVC when standalone is set.

**Describe the solution you'd like**

The same way that MinIO Chart creates PVC when set mode "standalone", would be more pratical if the same happens when set mode "gateway" type "nas".

**Describe alternatives you've considered**

A solution is to create a previous PVC then add to the Value: ```persistence.existingClaim```

**Additional context**

The behavior could be test with this value.yaml:
```
image:
  tag: "RELEASE.2022-02-12T00-51-25Z"
mode: "gateway"
gateway:
  type: "nas"
  replicas: 2  
rootUser: "test12345678"
rootPassword: "test12345678"
persistence:
  enabled: true
  accessMode: "ReadWriteMany"
  storageClass: "nfs"
  size: 10Gi
resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    memory: 1000Gi
    cpu: 1000m
environment:
  MINIO_BROWSER: "off"
serviceAccount:
  create: false
```
