### ISSUE TITLE
S3 Gateway Fails with specified S3 endpoint

### ISSUE THREAD

**Issue by willh99** [minio/minio#14325]
## Expected Behavior

Minio should be able to work as an S3 gateway when provided valid AWS credentials through the environment and the s3 endpoint in the command line. 

## Current Behavior

We can bring up Minio and reach the login page, but upon login a 500 error is returned. The container logs report the following: 

```
API: AccountInfo()
Time: 03:14:25 UTC 02/16/2022
DeploymentID: 827552fa-84d0-4eeb-aea9-9d43cfe688bb
RequestID: 16D425BEED039885
RemoteHost: 10.15.197.124
Host: 10.15.197.124:9000
UserAgent: MinIO (linux; amd64) madmin-go/0.0.1
Error: The AWS Access Key Id you provided does not exist in our records. (minio.ErrorResponse)
       5: cmd/api-errors.go:2103:cmd.toAPIErrorCode()
       4: cmd/admin-handler-utils.go:211:cmd.toAdminAPIErrCode()
       3: cmd/admin-handler-utils.go:198:cmd.toAdminAPIErr()
       2: cmd/admin-handlers-users.go:1125:cmd.adminAPIHandlers.AccountInfoHandler()
       1: net/http/server.go:2047:http.HandlerFunc.ServeHTTP()
```

Minio appears unable to communicate with s3 and validate the credentials.

## Possible Solution

This issue is not present in `RELEASE.2021-09-24T00-24-24Z`. Subsequent images have this issue. Our guess is that these later versions are not respecting the custom endpoint and are attempting to use some default endpoint that is not valid in our AWS environment.

## Steps to Reproduce (for bugs)

We currently have Minio deployed in EKS using the currently maintained chart [here](https://github.com/minio/minio/tree/master/helm/minio). The AWS account we are using is outside of regular commercial and thus has different endpoints. We modified the chart to add the s3 gateway such that the containers command is as follows: 

 `/usr/bin/docker-entrypoint.sh minio gateway s3 https://s3.<our-region>.amazonaws.com -S /etc/minio/certs/ --address :9000 --console-address :9001` 

This is done so that Minio can communicate with the S3 endpoint in our account. We have set the following environment variables from a secret and have validated these credentials: 

```yaml
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: minio-aws-user
              key: awsAccessKeyId
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-aws-user
              key: awsSecretAccessKey
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: minio-aws-user
              key: region
```

Easiest steps to reproduce without modifying the chart are to deploy the gcs gateway and just modify the deployment's `spec.containers[0].command` and `spec.containers[0].env` with the above.

Again note that this same configuration works with release `RELEASE.2021-09-24T00-24-24Z`

It is worth noting that if you bring up the container without specifying an endpoint, the container crashes immediately with a `The AWS Access Key Id you provided does not exist in our records` error, so it would appear that the endpoint is respected upon startup but subsequent commands do not pick it up.

## Context

We're using Minio to abstract away a storage backend that could either be an S3 bucket or an HDFS cluster, so we need the gateway to work in both scenarios. Using the older release isn't great from a security perspective and we would like to keep pace with the updates and improvements of Minio while stilling using the core gateway functionality we require.

## Regression

This appears to be the first breaking commit: https://github.com/minio/minio/tree/RELEASE.2021-10-02T16-31-05Z

## Your Environment

* Version used (`minio --version`): `minio version RELEASE.2021-09-24T00-24-24Z`
* Server setup and configuration: AWS EKS cluster
* AWS Account with non-default s3 endpoints
