### ISSUE TITLE
Why does Minio take up disk space much larger than the actual object size

### ISSUE THREAD

**Issue by wzc900810** [minio/minio#14376]
Hosts configuration：
CPU：2C
MEMORY：8G
Disk space: 300G
OS：Amazon Linux release 2 (Karoo)

Minio running on 4 different hosts with 4 disks and the following is my docker-compose configuration：
```
version: '3'

services:
  minio1:
    image: docker-image.paxengine.com.cn/public/minio:RELEASE.2021-07-15
    container_name: minio1
    hostname: minio1
    restart: always
    network_mode: host
    volumes:
      - ./data:/data
    environment:
      - TZ=Asia/Shanghai
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=xxxxxxxxxxxxxxxxxxxxxxxx
      - MINIO_API_REQUESTS_MAX=30
    extra_hosts:
      - "minio1:192.168.238.130"
      - "minio2:192.168.238.131" 
      - "minio3:192.168.238.132"
      - "minio4:192.168.238.133"
    command: server --address ":9000" --console-address ":9001" http://minio{1...4}/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
```

I am using 300G disks for each Minio storage. In the process of using it, I found that the disk space occupation is very large, much larger than the actual size of the objects in the cluster, the object size is 53G large and the disk occupies at least 200G, please see the attached image. What is causing this problem?
![企业微信截图_20220222161646](https://user-images.githubusercontent.com/6902998/155091994-0b331069-74a1-4ef9-8e5a-7868c99ad657.png)
![企业微信截图_20220222161607](https://user-images.githubusercontent.com/6902998/155092010-25e35665-01d3-4b99-b2b7-985a7a18796f.png)
