### ISSUE TITLE
Minio deleted the contents of the buckets arbitrarily

### ISSUE THREAD

**Issue by Ilario847** [minio/minio#14380]
I have a **Minio Replicated** system with **4 Nodes**. It worked well for about 1 year. Then, recently, after some curruption and uploading errors, it has been decided to upgrade the Minio version several times during the last two weeks to check if the corruption problem derived from some already fixed issues. Then suddenly **files started to disappear** from Minio, more than 1TB of data has been lost.

How does distributed **minio communicates** to the others nodes **to delete** objects, and how does minio know when to delete files ?
What can be the reason for minio to delete that files ? Maybe due to corruption or inconsistence by disk damage, power blackout or upgrade/downgrade of minio version ?

## Expected Behavior
Even if the files was damaged, in a replicated system, they should be there.

## Current Behavior
Currently one of the Nodes has almost all files, another one has 50% of the data and the other two are almost empty. So, at the moment, we cannot start the cluster because we don't know if other data will keep disappearing.

## Your Environment
* Version used: from RELEASE.2020-12-23T02-24-12Z to quay.io/minio/minio two month ago. Then minio/minio:RELEASE.2022-02-07T08-17-33Z and at final step minio/minio:RELEASE.2021-12-27T07-23-18Z
* Server setup and configuration: 4 Nodes in Cluster
* Operating System and version: Docker on Ubuntu with different FileSystem across the Nodes (ZFS, ext4)

**Comment by klauspost** [comment]
@Ilario847 Do help debug this could you post your entire replication config, as well is remote setup information.

You you share information on the deleted content, does it delete from the remotes, locally, etc, provide listing examples if possible?

**Comment by Ilario847** [comment]
> @Ilario847 Do help debug this could you post your entire replication config, as well is remote setup information.
> 
> You you share information on the deleted content, does it delete from the remotes, locally, etc, provide listing examples if possible?



The kind of data content is various (Video, Audio, Documents).
Minio is installed on Docker in 4 different servers (which is the 4 Nodes of the Cluster), that runs on same LAN Network.
We use Docker Swarm as Orchestrator and this is our Stack: 

```
version: "3.7"
networks:
  minio:
    external: true
  traefik-internal:
    external: true
services:
  minio1:
    image: minio/minio:RELEASE.2021-12-27T07-23-18Z
    hostname: minio1
    volumes:
      - /minio1/data:/export
    ports:
      - "9001:9000"
    networks:
      traefik-internal:
      minio:
        aliases:
          - miniosingleshared
          - miniodata
          - minio_data
          - minio1
    deploy:
      mode: replicated
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.minioreplicated.tls=true"
        - "traefik.http.routers.minioreplicated.rule=Host(`minio-************.com`)"
        - "traefik.http.routers.minioreplicated.entrypoints=websecure"
        - "traefik.http.routers.minioreplicated.middlewares=compression-minioreplicated"
        - "traefik.http.services.minioreplicated-service.loadbalancer.server.port=9001"
        - "traefik.http.services.minioreplicated-service.loadbalancer.sticky=true"
        - "traefik.http.services.minioreplicated-service.loadbalancer.sticky.cookie.name=minioreplicated_cookie"
        - "traefik.http.services.minioreplicated-service.loadbalancer.sticky.cookie.httponly=true"
        - "traefik.http.services.minioreplicated-service.loadbalancer.sticky.cookie.secure=true"
      
      
        - "traefik.http.middlewares.compression-minioreplicated.compress=true"
        - "dns-internal=true"
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:
        constraints:
          - node.labels.minio1==true
    command: server --console-address ":9001" --address ":9000" http://minio{1...4}/export
    environment:
      MINIO_ACCESS_KEY: ************************** 
      MINIO_SECRET_KEY: ************************************** 
      MINIO_REGION: "region0"
      MINIO_DOMAIN: "minio-************.com"
      MINIO_SERVER_URL: "http://miniodata:9000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
```


minio2, minio3, minio4: same as minio1
