### ISSUE TITLE
Connection test for LDAP server failed: Error creating connection to LDAP server: LDAP Result Code 200 "Network Error": EOF

### ISSUE THREAD

**Issue by devent** [minio/minio#14441]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior
Connection to OpenLDAP server success.

## Current Behavior
```
API: SYSTEM()
Time: 08:17:17 UTC 03/02/2022
DeploymentID: fce465bd-cea7-4e20-8645-acce7e7fb5d4
Error: Unable to parse LDAP configuration: Connection test for LDAP server failed: Error creating connection to LDAP server: LDAP Result Code 200 "Network Error": EOF (*fmt.wrapError)
       7: cmd/config-current.go:553:cmd.lookupConfigs()
       6: cmd/config-current.go:801:cmd.loadConfig()
       5: cmd/config.go:235:cmd.initConfig()
       4: cmd/config.go:195:cmd.(*ConfigSys).Init()
       3: cmd/server-main.go:382:cmd.initConfigSubsystem()
       2: cmd/server-main.go:349:cmd.initServer()
       1: cmd/server-main.go:517:cmd.serverMain()
```

## Steps to Reproduce (for bugs)

Install MinIO from Helm Chart. Without LDAP everything works. Adding LDAP configuration via environment variables fails with the above mentioned error.

Relevant env:

```
        - name: MINIO_IDENTITY_LDAP_SERVER_ADDR
          value: openldap.kube-ldap.svc.cluster.local:1389
        - name: MINIO_IDENTITY_LDAP_LOOKUP_BIND_DN
          value: cn=admin,dc=muellerpublic,dc=de
        - name: MINIO_IDENTITY_LDAP_LOOKUP_BIND_PASSWORD
          value: xxx
        - name: MINIO_IDENTITY_LDAP_USER_DN_SEARCH_BASE_DN
          value: ou=People,dc=muellerpublic,dc=de
        - name: MINIO_IDENTITY_LDAP_USER_DN_SEARCH_FILTER
          value: (&(objectClass=inetOrgPerson)(memberOf=cn=Minio,ou=Group,dc=muellerpublic,dc=de)(|(uid=%s)(cn=%s)))
        - name: MINIO_IDENTITY_LDAP_TLS_SKIP_VERIFY
          value: "off"
        - name: MINIO_IDENTITY_LDAP_SERVER_INSECURE
          value: "off"
        - name: MINIO_IDENTITY_LDAP_SERVER_STARTTLS
          value: "off"
```

## Context

MinIO and OpenLDAP are installed in an Kubernetes cluster.

## Your Environment

* Version used (`minio --version`):
minio version DEVELOPMENT.2022-02-26T02-54-46Z

* Server setup and configuration:
kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:32:32Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}

* Operating System and version (`uname -a`):
Linux andrea-node-3.muellerpublic.de 5.10.0-10-amd64 #1 SMP Debian 5.10.84-1 (2021-12-08) x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
> Error: Unable to parse LDAP configuration: Connection test for LDAP server failed: Error creating connection to LDAP server: LDAP Result Code 200 "Network Error": EOF (*fmt.wrapError)

> value: openldap.kube-ldap.svc.cluster.local:1389

Looks like your LDAP is not reachable here - not sure what you want us to do here

**Comment by devent** [comment]
> > Error: Unable to parse LDAP configuration: Connection test for LDAP server failed: Error creating connection to LDAP server: LDAP Result Code 200 "Network Error": EOF (*fmt.wrapError)
> 
> > value: openldap.kube-ldap.svc.cluster.local:1389
> 
> Looks like your LDAP is not reachable here - not sure what you want us to do here

It's very much reachable. I'm using my LDAP in Gitea, Grafana, Keycloak, etc. with the exact same setup.

Is there a debugging option in MinIO that I can enable?

**Comment by ureykane** [comment]
> > > Error: Unable to parse LDAP configuration: Connection test for LDAP server failed: Error creating connection to LDAP server: LDAP Result Code 200 "Network Error": EOF (*fmt.wrapError)
> > 
> > 
> > > value: openldap.kube-ldap.svc.cluster.local:1389
> > 
> > 
> > Looks like your LDAP is not reachable here - not sure what you want us to do here
> 
> It's very much reachable. I'm using my LDAP in Gitea, Grafana, Keycloak, etc. with the exact same setup.
> 
> Is there a debugging option in MinIO that I can enable?

You can do this by setting environment variables:

`    _MINIO_SERVER_DEBUG=on`

But I suggest you to check whether the environment variable of connection information has been set successfully in the container

**Comment by devent** [comment]
Just tried in the minio container.

```
*   Trying 10.101.53.149...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x55b53a4e5ee0)
* Connected to openldap.kube-ldap.svc.cluster.local (10.101.53.149) port 1389 (#0)
> GET / HTTP/1.1
> Host: openldap.kube-ldap.svc.cluster.local:1389
> User-Agent: curl/7.64.0
> Accept: */*
> 
* Empty reply from server
* Connection #0 to host openldap.kube-ldap.svc.cluster.local left intact
curl: (52) Empty reply from server
```

Curl can at least connect to my LDAP. `openldap            ClusterIP   10.101.53.149`

> But I suggest you to check whether the environment variable of connection information has been set successfully in the container

Ok will do.

**Comment by m-mokhtarzadeh** [comment]
hello
i have same problem.
i tested in two different location, one of them with Windows Active Directory 2016 and Minio version RELEASE.2022-03-11T23-57-45Z installed in Rockylinux and another location configured with Samba Active Directory and Minio installed on CentOS 7 and also tested with container but my LDAP was reachable.

**Comment by devent** [comment]
I recreated the setup locally with docker compose. This way you can also test it. Same error.

```
Error: LDAP Result Code 200 "Network Error": EOF (*ldap.Error)
       2: cmd/iam.go:1049:cmd.(*IAMSys).purgeExpiredCredentialsForLDAP()
       1: cmd/iam.go:309:cmd.(*IAMSys).Init.func2()
```


```
version: '3'
services:
  minio:
    image: bitnami/minio:2022.3.17-debian-10-r2
    ports:
      - '9000:9000'
      - '9001:9001'
    depends_on:
      - ldap
    environment:
      - MINIO_IDENTITY_LDAP_SERVER_ADDR=ldap:1389
      - MINIO_IDENTITY_LDAP_LOOKUP_BIND_DN=cn=admin,dc=example,dc=org
      - MINIO_IDENTITY_LDAP_LOOKUP_BIND_PASSWORD=adminpassword
      - MINIO_IDENTITY_LDAP_USER_DN_SEARCH_BASE_DN=ou=People,dc=example,dc=org
      - MINIO_IDENTITY_LDAP_USER_DN_SEARCH_FILTER=(&(objectClass=inetOrgPerson)(memberOf=cn=Minio,ou=Group,dc=example,dc=org)(|(uid=%s)(cn=%s)))
      - MINIO_IDENTITY_LDAP_TLS_SKIP_VERIFY=off
      - MINIO_IDENTITY_LDAP_SERVER_INSECURE=off
      - MINIO_IDENTITY_LDAP_SERVER_STARTTLS=off
      - _MINIO_SERVER_DEBUG=on
  ldap:
    image: bitnami/openldap:2.5.11-debian-10-r58
    ports:
      - '1389:1389'
      - '1636:1636'
    environment:
      - BITNAMI_DEBUG=true
      - LDAP_ROOT=dc=example,dc=org
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_USERS=user01,user02
      - LDAP_PASSWORDS=password1,password2
    volumes:
      - 'openldap_data:/bitnami/openldap'
volumes:
  openldap_data:
    driver: local
```

Logs:

```
docker logs -f minio-docker_minio_1
 10:39:36.35 
 10:39:36.35 Welcome to the Bitnami minio container
 10:39:36.35 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-minio
 10:39:36.35 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-minio/issues
 10:39:36.36 
 10:39:36.36 INFO  ==> ** Starting MinIO setup **
minio 10:39:36.38 INFO  ==> Starting MinIO in background...
minio 10:39:41.62 INFO  ==> Adding local Minio host to 'mc' configuration...
minio 10:39:41.74 INFO  ==> Stopping MinIO...
 10:39:42.84 INFO  ==> ** MinIO setup finished! **

minio 10:39:42.90 INFO  ==> ** Starting MinIO **

API: SYSTEM()
Time: 10:39:43 UTC 03/20/2022
DeploymentID: 46c7615d-7062-447c-8c88-a452b835c68a
Error: Unable to parse LDAP configuration: LDAP Server Connection Error: Could not connect to LDAP server: LDAP Result Code 200 "Network Error": EOF (*fmt.wrapError)
       7: cmd/config-current.go:553:cmd.lookupConfigs()
       6: cmd/config-current.go:801:cmd.loadConfig()
       5: cmd/config.go:235:cmd.initConfig()
       4: cmd/config.go:195:cmd.(*ConfigSys).Init()
       3: cmd/server-main.go:382:cmd.initConfigSubsystem()
       2: cmd/server-main.go:349:cmd.initServer()
       1: cmd/server-main.go:522:cmd.serverMain()
== DEBUG Mode enabled ==
Currently set environment settings:
affinity:container==0c96beb8df8b5d9c1fd4e9a0404ab2b9862a2ec3ea1bb82d9e22c1caed893f7b
MODULE=minio
HOSTNAME=56af9d6d9ff1
MINIO_IDENTITY_LDAP_SERVER_STARTTLS=off
MINIO_FORCE_NEW_KEYS=no
MINIO_API_PORT_NUMBER=9000
MINIO_IDENTITY_LDAP_TLS_SKIP_VERIFY=off
BITNAMI_ROOT_DIR=/opt/bitnami
MINIO_BIN_DIR=/opt/bitnami/minio/bin
PWD=/opt/bitnami/minio-client
OS_FLAVOUR=debian-10
MINIO_STARTUP_TIMEOUT=10
MINIO_DAEMON_USER=minio
MINIO_IDENTITY_LDAP_LOOKUP_BIND_PASSWORD=adminpassword
MINIO_SECRETS_DIR=/opt/bitnami/minio/secrets
HOME=/
MINIO_CERTS_DIR=/certs
MINIO_CONSOLE_PORT_NUMBER=9001
MINIO_IDENTITY_LDAP_SERVER_ADDR=ldap:1389
MINIO_DATA_DIR=/data
MINIO_DEFAULT_BUCKETS=
BITNAMI_DEBUG=false
MINIO_DISTRIBUTED_MODE_ENABLED=no
MINIO_IDENTITY_LDAP_USER_DN_SEARCH_BASE_DN=ou=People,dc=example,dc=org
MINIO_SKIP_CLIENT=no
BITNAMI_IMAGE_VERSION=2022.3.17-debian-10-r2
MINIO_IDENTITY_LDAP_USER_DN_SEARCH_FILTER=(&(objectClass=inetOrgPerson)(memberOf=cn=Minio,ou=Group,dc=example,dc=org)(|(uid=%!s(MISSING))(cn=%!s(MISSING))))
MINIO_DAEMON_GROUP=minio
SHLVL=0
MINIO_LOGS_DIR=/opt/bitnami/minio/log
BITNAMI_VOLUME_DIR=/bitnami
MINIO_IDENTITY_LDAP_SERVER_INSECURE=off
BITNAMI_APP_NAME=minio
_MINIO_SERVER_DEBUG=on
MINIO_IDENTITY_LDAP_LOOKUP_BIND_DN=cn=admin,dc=example,dc=org
MINIO_BASE_DIR=/opt/bitnami/minio
OS_NAME=linux
PATH=/opt/bitnami/minio/bin:/opt/bitnami/common/bin:/opt/bitnami/minio-client/bin:/opt/bitnami/minio/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
MINIO_SCHEME=http
OS_ARCH=amd64
2022/03/20 10:39:43 Serving console at http://[::]:9001
CONSOLE_PBKDF_SALT=46c7615d-7062-447c-8c88-a452b835c68a
CONSOLE_PBKDF_PASSPHRASE=46c7615d-7062-447c-8c88-a452b835c68a
CONSOLE_MINIO_SERVER=http://172.20.0.2:9000
CONSOLE_LDAP_ENABLED=on
CONSOLE_MINIO_REGION=
CONSOLE_CERT_PASSWD=
======
API: http://172.20.0.2:9000  http://127.0.0.1:9000 

Console: http://172.20.0.2:9001 http://127.0.0.1:9001 

Documentation: https://docs.min.io
minio: <DEBUG> starting scanner cycle
minio: <DEBUG> dataUpdateTracker: cycle bloom filter: 75 -> 76
minio: <DEBUG> dataUpdateTracker: Saving: 2037433 bytes, Current idx: 76
minio: <DEBUG> starting scanner cycle
minio: <DEBUG> dataUpdateTracker: cycle bloom filter: 76 -> 77
minio: <DEBUG> dataUpdateTracker: Saving: 2037433 bytes, Current idx: 77
minio: <DEBUG> starting scanner cycle
minio: <DEBUG> dataUpdateTracker: cycle bloom filter: 77 -> 78
minio: <DEBUG> dataUpdateTracker: Saving: 2037433 bytes, Current idx: 78
minio: <DEBUG> starting scanner cycle
minio: <DEBUG> dataUpdateTracker: cycle bloom filter: 78 -> 79
minio: <DEBUG> dataUpdateTracker: Saving: 2037433 bytes, Current idx: 79
minio: <DEBUG> starting scanner cycle
minio: <DEBUG> dataUpdateTracker: cycle bloom filter: 79 -> 80

API: SYSTEM()
Time: 10:44:43 UTC 03/20/2022
DeploymentID: 46c7615d-7062-447c-8c88-a452b835c68a
Error: LDAP Result Code 200 "Network Error": EOF (*ldap.Error)
       2: cmd/iam.go:1049:cmd.(*IAMSys).purgeExpiredCredentialsForLDAP()
       1: cmd/iam.go:309:cmd.(*IAMSys).Init.func2()

API: SYSTEM()
Time: 10:44:43 UTC 03/20/2022
DeploymentID: 46c7615d-7062-447c-8c88-a452b835c68a
Error: LDAP Result Code 200 "Network Error": EOF (*ldap.Error)
       2: cmd/iam.go:1119:cmd.(*IAMSys).updateGroupMembershipsForLDAP()
       1: cmd/iam.go:310:cmd.(*IAMSys).Init.func2()
minio: <DEBUG> dataUpdateTracker: Saving: 2037433 bytes, Current idx: 80
minio: <DEBUG> starting scanner cycle
minio: <DEBUG> dataUpdateTracker: cycle bloom filter: 80 -> 81
minio: <DEBUG> dataUpdateTracker: Saving: 2037433 bytes, Current idx: 81
minio: <DEBUG> starting scanner cycle
minio: <DEBUG> dataUpdateTracker: cycle bloom filter: 81 -> 82
minio: <DEBUG> dataUpdateTracker: Saving: 2037433 bytes, Current idx: 82
minio: <DEBUG> starting scanner cycle
minio: <DEBUG> dataUpdateTracker: cycle bloom filter: 82 -> 83
minio: <DEBUG> dataUpdateTracker: Saving: 2037433 bytes, Current idx: 83
minio: <DEBUG> starting scanner cycle
minio: <DEBUG> dataUpdateTracker: cycle bloom filter: 83 -> 84
minio: <DEBUG> dataUpdateTracker: Saving: 2037433 bytes, Current idx: 84

API: SYSTEM()
Time: 10:49:43 UTC 03/20/2022
DeploymentID: 46c7615d-7062-447c-8c88-a452b835c68a
Error: LDAP Result Code 200 "Network Error": EOF (*ldap.Error)
       2: cmd/iam.go:1049:cmd.(*IAMSys).purgeExpiredCredentialsForLDAP()
       1: cmd/iam.go:309:cmd.(*IAMSys).Init.func2()

API: SYSTEM()
Time: 10:49:43 UTC 03/20/2022
DeploymentID: 46c7615d-7062-447c-8c88-a452b835c68a
Error: LDAP Result Code 200 "Network Error": EOF (*ldap.Error)
       2: cmd/iam.go:1119:cmd.(*IAMSys).updateGroupMembershipsForLDAP()
       1: cmd/iam.go:310:cmd.(*IAMSys).Init.func2()
minio: <DEBUG> starting scanner cycle
minio: <DEBUG> dataUpdateTracker: cycle bloom filter: 84 -> 85
minio: <DEBUG> dataUpdateTracker: Saving: 2037433 bytes, Current idx: 85
minio: <DEBUG> starting scanner cycle
minio: <DEBUG> dataUpdateTracker: cycle bloom filter: 85 -> 86
minio: <DEBUG> dataUpdateTracker: Saving: 2037433 bytes, Current idx: 86
minio: <DEBUG> starting scanner cycle
minio: <DEBUG> dataUpdateTracker: cycle bloom filter: 86 -> 87
minio: <DEBUG> dataUpdateTracker: Saving: 2037433 bytes, Current idx: 87

```

LDAP is running:

```
docker logs minio-docker_ldap_1    
 10:38:52.00 INFO  ==> ** Starting LDAP setup **
 10:38:52.11 INFO  ==> Validating settings in LDAP_* env vars
 10:38:52.13 INFO  ==> Initializing OpenLDAP...
 10:38:52.14 DEBUG ==> Ensuring expected directories/files exist...
 10:38:52.16 INFO  ==> Using persisted data
 10:38:52.17 INFO  ==> ** LDAP setup finished! **

 10:38:52.21 INFO  ==> ** Starting slapd **
6237043c.0d5cf860 0x7fcfc624b000 @(#) $OpenLDAP: slapd 2.5.11 (Mar  1 2022 15:23:23) $
        @bc169e08a584:/bitnami/blacksmith-sandox/openldap-2.5.11/servers/slapd
6237043c.0e2a5e5a 0x7fcfc624b000 slapd starting
6237043f.39d8bf6e 0x7fcfc4aab700 conn=1000 fd=12 ACCEPT from IP=172.20.0.2:45200 (IP=0.0.0.0:1389)
6237043f.39dbeff9 0x7fcfbffff700 conn=1000 fd=12 closed (connection lost)
62370445.036ac2e4 0x7fcfbffff700 conn=1001 fd=12 ACCEPT from IP=172.20.0.2:45208 (IP=0.0.0.0:1389)
62370445.036c29ba 0x7fcfc4aab700 conn=1001 fd=12 closed (connection lost)
62370446.159743ab 0x7fcfbffff700 conn=1002 fd=12 ACCEPT from IP=172.20.0.2:45216 (IP=0.0.0.0:1389)
62370446.159f1162 0x7fcfc4aab700 conn=1002 fd=12 closed (connection lost)
62370468.22f0ef96 0x7fcfbffff700 conn=1003 fd=12 ACCEPT from IP=172.20.0.2:45222 (IP=0.0.0.0:1389)
62370468.22f7be6c 0x7fcfc4aab700 conn=1003 fd=12 closed (connection lost)
6237046d.2bcf7eb3 0x7fcfbffff700 conn=1004 fd=12 ACCEPT from IP=172.20.0.2:45230 (IP=0.0.0.0:1389)
6237046d.2bd4ca57 0x7fcfc4aab700 conn=1004 fd=12 closed (connection lost)
6237046f.0491ffa9 0x7fcfbffff700 conn=1005 fd=12 ACCEPT from IP=172.20.0.2:45236 (IP=0.0.0.0:1389)
6237046f.0494ce80 0x7fcfc4aab700 conn=1005 fd=12 closed (connection lost)
6237059b.0e3b88fb 0x7fcfbffff700 conn=1006 fd=12 ACCEPT from IP=172.20.0.2:45240 (IP=0.0.0.0:1389)
6237059b.0e4c62ba 0x7fcfc4aab700 conn=1006 fd=12 closed (connection lost)
6237059b.0e64bc08 0x7fcfbffff700 conn=1007 fd=12 ACCEPT from IP=172.20.0.2:45242 (IP=0.0.0.0:1389)
6237059b.0e67d89c 0x7fcfc4aab700 conn=1007 fd=12 closed (connection lost)
623706c7.0e243689 0x7fcfbffff700 conn=1008 fd=12 ACCEPT from IP=172.20.0.2:45286 (IP=0.0.0.0:1389)
623706c7.0e28e44f 0x7fcfc4aab700 conn=1008 fd=12 closed (connection lost)
623706c7.0e3a9e56 0x7fcfbffff700 conn=1009 fd=12 ACCEPT from IP=172.20.0.2:45288 (IP=0.0.0.0:1389)
623706c7.0e42aacb 0x7fcfc4aab700 conn=1009 fd=12 closed (connection lost)
```

**Comment by devent** [comment]
I tried the same with the official Minio image. Same error.

```
version: '3'
services:
  minio:
    image: minio/minio:RELEASE.2022-03-17T06-34-49Z
    command: ["server", "/data", "--console-address", ":9001"]
    ports:
      - '9000:9000'
      - '9001:9001'
    depends_on:
      - ldap
    environment:
      - MINIO_IDENTITY_LDAP_SERVER_ADDR=ldap:1389
      - MINIO_IDENTITY_LDAP_LOOKUP_BIND_DN=cn=admin,dc=example,dc=org
      - MINIO_IDENTITY_LDAP_LOOKUP_BIND_PASSWORD=adminpassword
      - MINIO_IDENTITY_LDAP_USER_DN_SEARCH_BASE_DN=ou=People,dc=example,dc=org
      - MINIO_IDENTITY_LDAP_USER_DN_SEARCH_FILTER=(&(objectClass=inetOrgPerson)(memberOf=cn=Minio,ou=Group,dc=example,dc=org)(|(uid=%s)(cn=%s)))
      - MINIO_IDENTITY_LDAP_TLS_SKIP_VERIFY=off
      - MINIO_IDENTITY_LDAP_SERVER_INSECURE=off
      - MINIO_IDENTITY_LDAP_SERVER_STARTTLS=off
      - _MINIO_SERVER_DEBUG=on
    volumes:
      - 'minio_data:/data'
  ldap:
    image: bitnami/openldap:2.5.11-debian-10-r58
    ports:
      - '1389:1389'
      - '1636:1636'
    environment:
      - BITNAMI_DEBUG=true
      - LDAP_ROOT=dc=example,dc=org
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_USERS=user01,user02
      - LDAP_PASSWORDS=password1,password2
    volumes:
      - 'openldap_data:/bitnami/openldap'
volumes:
  openldap_data:
    driver: local
  minio_data:
    driver: local
```

```
docker logs -f minio-docker_minio_1

API: SYSTEM()
Time: 11:17:33 UTC 03/20/2022
DeploymentID: b6515c3c-429e-440c-977f-77f43cb8a0e8
Error: Unable to parse LDAP configuration: LDAP Server Connection Error: Could not connect to LDAP server: LDAP Result Code 200 "Network Error": dial tcp 172.23.0.2:1389: connect: connection refused (*fmt.wrapError)
       7: cmd/config-current.go:553:cmd.lookupConfigs()
       6: cmd/config-current.go:801:cmd.loadConfig()
       5: cmd/config.go:235:cmd.initConfig()
       4: cmd/config.go:195:cmd.(*ConfigSys).Init()
       3: cmd/server-main.go:382:cmd.initConfigSubsystem()
       2: cmd/server-main.go:349:cmd.initServer()
       1: cmd/server-main.go:522:cmd.serverMain()
== DEBUG Mode enabled ==
Currently set environment settings:
MINIO_ACCESS_KEY_FILE=access_key
_MINIO_SERVER_DEBUG=on
HOSTNAME=33a28a3a8a8c
MINIO_KMS_SECRET_KEY_FILE=kms_master_key
MINIO_IDENTITY_LDAP_LOOKUP_BIND_PASSWORD=adminpassword
MINIO_IDENTITY_LDAP_SERVER_STARTTLS=off
container=oci
PWD=/
HOME=/root
MINIO_IDENTITY_LDAP_TLS_SKIP_VERIFY=off
MINIO_IDENTITY_LDAP_USER_DN_SEARCH_BASE_DN=ou=People,dc=example,dc=org
MINIO_IDENTITY_LDAP_USER_DN_SEARCH_FILTER=(&(objectClass=inetOrgPerson)(memberOf=cn=Minio,ou=Group,dc=example,dc=org)(|(uid=%!s(MISSING))(cn=%!s(MISSING))))
MINIO_IDENTITY_LDAP_SERVER_ADDR=ldap:1389
MINIO_ROOT_USER_FILE=access_key
MINIO_ROOT_PASSWORD_FILE=secret_key
SHLVL=0
MINIO_UPDATE_MINISIGN_PUBKEY=RWTx5Zr1tiHQLwG9keckT0c45M3AGeHD6IvimQHpyRywVWGbP1aVSGav
MINIO_IDENTITY_LDAP_LOOKUP_BIND_DN=cn=admin,dc=example,dc=org
MINIO_SECRET_KEY_FILE=secret_key
PATH=/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
MINIO_CONFIG_ENV_FILE=config.env
MINIO_IDENTITY_LDAP_SERVER_INSECURE=off
CONSOLE_PBKDF_SALT=b6515c3c-429e-440c-977f-77f43cb8a0e8
CONSOLE_PBKDF_PASSPHRASE=b6515c3c-429e-440c-977f-77f43cb8a0e8
CONSOLE_MINIO_SERVER=http://172.23.0.3:9000
CONSOLE_LDAP_ENABLED=on
CONSOLE_MINIO_REGION=
CONSOLE_CERT_PASSWD=
======
2022/03/20 11:17:33 Serving console at http://[::]:9001
API: http://172.23.0.3:9000  http://127.0.0.1:9000 

Console: http://172.23.0.3:9001 http://127.0.0.1:9001 

Documentation: https://docs.min.io
minio: <DEBUG> starting scanner cycle
minio: <DEBUG> dataUpdateTracker: cycle bloom filter: 1 -> 2
minio: <DEBUG> dataUpdateTracker: Saving: 239713 bytes, Current idx: 2
```

Can you re-open the bug report?

**Comment by devent** [comment]
I tried with the official Minio image. Same error. Can you please reopen?

```
version: '3'
services:
  minio:
    image: minio/minio:RELEASE.2022-03-17T06-34-49Z
    command: ["server", "/data", "--console-address", ":9001"]
    ports:
      - '9000:9000'
      - '9001:9001'
    depends_on:
      - ldap
    environment:
      - MINIO_IDENTITY_LDAP_SERVER_ADDR=ldap:1389
      - MINIO_IDENTITY_LDAP_LOOKUP_BIND_DN=cn=admin,dc=example,dc=org
      - MINIO_IDENTITY_LDAP_LOOKUP_BIND_PASSWORD=adminpassword
      - MINIO_IDENTITY_LDAP_USER_DN_SEARCH_BASE_DN=ou=users,dc=example,dc=org
      - MINIO_IDENTITY_LDAP_USER_DN_SEARCH_FILTER=(&(objectClass=inetOrgPerson)(uid=%s))
      - MINIO_IDENTITY_LDAP_TLS_SKIP_VERIFY=off
      - MINIO_IDENTITY_LDAP_SERVER_INSECURE=off
      - MINIO_IDENTITY_LDAP_SERVER_STARTTLS=off
      - _MINIO_SERVER_DEBUG=on
    volumes:
      - 'minio_data:/data'
  ldap:
    image: bitnami/openldap:2.5.11-debian-10-r58
    ports:
      - '1389:1389'
      - '1636:1636'
    environment:
      - BITNAMI_DEBUG=true
      - LDAP_ROOT=dc=example,dc=org
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_USERS=user01,user02
      - LDAP_PASSWORDS=password1,password2
    volumes:
      - 'openldap_data:/bitnami/openldap'
volumes:
  openldap_data:
    driver: local
  minio_data:
    driver: local
```

```
docker logs -f minio-docker_minio_1

API: SYSTEM()
Time: 11:35:17 UTC 03/20/2022
DeploymentID: b6515c3c-429e-440c-977f-77f43cb8a0e8
Error: Unable to parse LDAP configuration: LDAP Server Connection Error: Could not connect to LDAP server: LDAP Result Code 200 "Network Error": EOF (*fmt.wrapError)
       7: cmd/config-current.go:553:cmd.lookupConfigs()
       6: cmd/config-current.go:801:cmd.loadConfig()
       5: cmd/config.go:235:cmd.initConfig()
       4: cmd/config.go:195:cmd.(*ConfigSys).Init()
       3: cmd/server-main.go:382:cmd.initConfigSubsystem()
       2: cmd/server-main.go:349:cmd.initServer()
       1: cmd/server-main.go:522:cmd.serverMain()
== DEBUG Mode enabled ==
Currently set environment settings:
MINIO_ACCESS_KEY_FILE=access_key
_MINIO_SERVER_DEBUG=on
HOSTNAME=15f4fdd441da
MINIO_KMS_SECRET_KEY_FILE=kms_master_key
MINIO_IDENTITY_LDAP_LOOKUP_BIND_PASSWORD=adminpassword
MINIO_IDENTITY_LDAP_SERVER_STARTTLS=off
container=oci
PWD=/
HOME=/root
MINIO_IDENTITY_LDAP_TLS_SKIP_VERIFY=off
MINIO_IDENTITY_LDAP_USER_DN_SEARCH_BASE_DN=ou=users,dc=example,dc=org
MINIO_IDENTITY_LDAP_USER_DN_SEARCH_FILTER=(&(objectClass=inetOrgPerson)(uid=%!s(MISSING)))
MINIO_IDENTITY_LDAP_SERVER_ADDR=ldap:1389
MINIO_ROOT_USER_FILE=access_key
MINIO_ROOT_PASSWORD_FILE=secret_key
SHLVL=0
MINIO_UPDATE_MINISIGN_PUBKEY=RWTx5Zr1tiHQLwG9keckT0c45M3AGeHD6IvimQHpyRywVWGbP1aVSGav
MINIO_IDENTITY_LDAP_LOOKUP_BIND_DN=cn=admin,dc=example,dc=org
MINIO_SECRET_KEY_FILE=secret_key
PATH=/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
MINIO_CONFIG_ENV_FILE=config.env
MINIO_IDENTITY_LDAP_SERVER_INSECURE=off
CONSOLE_PBKDF_SALT=b6515c3c-429e-440c-977f-77f43cb8a0e8
CONSOLE_PBKDF_PASSPHRASE=b6515c3c-429e-440c-977f-77f43cb8a0e8
CONSOLE_MINIO_SERVER=http://172.23.0.3:9000
CONSOLE_LDAP_ENABLED=on
CONSOLE_MINIO_REGION=
CONSOLE_CERT_PASSWD=
======
2022/03/20 11:35:17 Serving console at http://[::]:9001
API: http://172.23.0.3:9000  http://127.0.0.1:9000 

Console: http://172.23.0.3:9001 http://127.0.0.1:9001 

Documentation: https://docs.min.io
```
