### ISSUE TITLE
Notification setting for AMQP and Mysql are not functioning or configurable

### ISSUE THREAD

**Issue by koisi-io** [minio/minio#14451]
## NOTE
My Minio is a cluster with 4 nodes and 1 drive per node installed by minio-operator.I encounter 2 issues when setting notifications：
1. Successed to add a AMQP notification, but when applying it to a bucket,  It is failed with "A specified destination ARN does not exist or is not well-formed".
2. All nodes are online, but when  setting a Mysql notifications it is always failed with "one or more targets are offline".

## Expected Behavior
Successfully add AMQP or Mysql notifications configurations and can apply it to bucket.

## Current Behavior
*  I successed to add a AMQP notification by minio client, and successfully restart minio server follow the directive.But when I try to apply AMQP notification to a bucket, It is failed with "A specified destination ARN does not exist or is not well-formed".
![image](https://user-images.githubusercontent.com/25927846/156487516-e2af1bab-1f46-49d2-821c-00c76eede8af.png)

* `mc admin info` show all nodes are online, but when I try to set a Mysql notifications it is always failed with "one or more targets are offline".
![image](https://user-images.githubusercontent.com/25927846/156487160-c119e562-c32b-4581-b9e5-916590cabd58.png)

## Steps to Reproduce (for bugs)
1. Install k8s cluster with version v1.19.16 or v1.20.15
2. Install Minio operator v4.4.10
3. Install Minio cluster by minio-op with 4 nodes and 1 drive per node
4. Try to set notification configs

## Your Environment
* k8s:  v1.20.15
* minio-operator: v4.4.10
* minio server: RELEASE.2022-02-26T02-54-46Z
* minio client: RELEASE.2022-02-26T03-58-31Z
* minio cluster:  4 nodes and 1 drive per node
* Operating System:  5.4.164-1.el7.elrepo.x86_64 CentOS Linux release 7.9.2009

**Comment by harshavardhana** [comment]
@kor-coeo you need to make sure your AMQP is up and running. same for `mysql`

**Comment by koisi-io** [comment]
@hackintoshrao Hello, I have tested the amqp and mysql config, it is works on Version: 2021-12-29T06:49:06Z. But failed when switch to 2022-02-26T02:54:46Z. There is a easier way to Reproduce that just using docker-compose:
```
version: '2'

services:
  minio1:
    image: 'bitnami/minio:2022.2.26'
    ports:
      - "29000:9000"
      - "29001:9001"
    environment:
      - MINIO_ACCESS_KEY=minio-access-key
      - MINIO_SECRET_KEY=minio-secret-key
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=minio1,minio2,minio3,minio4
      - MINIO_SKIP_CLIENT=yes
  minio2:
    image: 'bitnami/minio:2022.2.26'
    environment:
      - MINIO_ACCESS_KEY=minio-access-key
      - MINIO_SECRET_KEY=minio-secret-key
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=minio1,minio2,minio3,minio4
      - MINIO_SKIP_CLIENT=yes
  minio3:
    image: 'bitnami/minio:2022.2.26'
    environment:
      - MINIO_ACCESS_KEY=minio-access-key
      - MINIO_SECRET_KEY=minio-secret-key
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=minio1,minio2,minio3,minio4
      - MINIO_SKIP_CLIENT=yes
  minio4:
    image: 'bitnami/minio:2022.2.26'
    environment:
      - MINIO_ACCESS_KEY=minio-access-key
      - MINIO_SECRET_KEY=minio-secret-key
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=minio1,minio2,minio3,minio4
      - MINIO_SKIP_CLIENT=yes
```
Config works when `image: 'bitnami/minio:2021.12.29'`
![image](https://user-images.githubusercontent.com/25927846/156492507-933843b9-152d-4e58-be99-207dc111c60d.png)
