### ISSUE TITLE
Open files and Goroutines leak

### ISSUE THREAD

**Issue by OxCom** [minio/minio#14529]
## General
Looks like in release RELEASE.2022-03-08T22-28-51Z we have a leak of open files and goroutines. See screenshot.

![image](https://user-images.githubusercontent.com/4608564/157862727-aea9fe90-2f06-4a00-8d50-3d2c4f7c2fb0.png)

On screenshot the servers has on spike of load, all other time there are no load at all. Restart can reset the list of open files and goroutines counter.

## Environment
* Version used RELEASE.2022-03-08T22-28-51Z:
* Server setup and configuration: K8S bera metal + minio operator
* Operating System and version: 
`Linux <censored> 5.4.0-100-generic #113-Ubuntu SMP Thu Feb 3 18:43:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by vadmeste** [comment]
@OxCom what you can do is when the number of goroutines is high, you run this
 `mc admin profile start --type goroutines <alias>; sleep 30; mc adin profile start <alias>`
 
 and upload the generated profile archive.

**Comment by OxCom** [comment]
@vadmeste ok, I will do fresh restart and upload them after weekends

**Comment by klauspost** [comment]
@OxCom No, when goroutines are *high*, so do not restart.

**Comment by OxCom** [comment]
@klauspost yep, on weekend there will be no load at all. Goroutines are growing all time, that means that on weekend I can expect big amount of then.
one more: maybe this is a case of restart of all servers approximately every 2 weeks without any external trigger.

**Comment by harshavardhana** [comment]
Please upgrade to the latest release.

**Comment by harshavardhana** [comment]
692 FD's is hardly anything for a distributed setup, how many servers do you have here and how many drives?

**Comment by OxCom** [comment]
@harshavardhana I have no complains about amount of the open files. I have issue that it constantly grows without any reasons. And same issue for goroutines.

Update to version RELEASE.2022-03-11T11-08-23Z shows same grow.
About setup: 5 instances each with 2 disks

@vadmeste @klauspost results of profile after 22h uptime (latest version minio):
- Open files 1.10k 
- Total Goroutines: 3.42k
[profile_1k_3k.zip](https://github.com/minio/minio/files/8237498/profile_1k_3k.zip)

**Comment by harshavardhana** [comment]
```
grep total profile-gamestream-minio-pool-0-*
profile-gamestream-minio-pool-0-0.gamestream-minio-hl.cryengine-test.svc.cluster.local:9000-goroutines-before.txt:goroutine profile: total 671
profile-gamestream-minio-pool-0-0.gamestream-minio-hl.cryengine-test.svc.cluster.local:9000-goroutines.txt:goroutine profile: total 673
profile-gamestream-minio-pool-0-1.gamestream-minio-hl.cryengine-test.svc.cluster.local:9000-goroutines-before.txt:goroutine profile: total 680
profile-gamestream-minio-pool-0-1.gamestream-minio-hl.cryengine-test.svc.cluster.local:9000-goroutines.txt:goroutine profile: total 680
profile-gamestream-minio-pool-0-2.gamestream-minio-hl.cryengine-test.svc.cluster.local:9000-goroutines-before.txt:goroutine profile: total 707
profile-gamestream-minio-pool-0-2.gamestream-minio-hl.cryengine-test.svc.cluster.local:9000-goroutines.txt:goroutine profile: total 709
profile-gamestream-minio-pool-0-3.gamestream-minio-hl.cryengine-test.svc.cluster.local:9000-goroutines-before.txt:goroutine profile: total 670
profile-gamestream-minio-pool-0-3.gamestream-minio-hl.cryengine-test.svc.cluster.local:9000-goroutines.txt:goroutine profile: total 671
profile-gamestream-minio-pool-0-4.gamestream-minio-hl.cryengine-test.svc.cluster.local:9000-goroutines-before.txt:goroutine profile: total 680
profile-gamestream-minio-pool-0-4.gamestream-minio-hl.cryengine-test.svc.cluster.local:9000-goroutines.txt:goroutine profile: total 690
```

This looks normal to me @OxCom 

250 are replication workers that are always present
100 are transition workers that are always present
16 other internal routines that are also always running

So you in total 300 extra 

What I see you are doing here is invoking something called as `mc watch` like functionality

```
grep ListenNoti *.txt |grep -v before
profile-gamestream-minio-pool-0-1.gamestream-minio-hl.cryengine-test.svc.cluster.local:9000-goroutines.txt:#	0x1d9bf34	github.com/minio/minio/cmd.objectAPIHandlers.ListenNotificationHandler+0x15b4	github.com/minio/minio/cmd/listen-notification-handlers.go:158
profile-gamestream-minio-pool-0-2.gamestream-minio-hl.cryengine-test.svc.cluster.local:9000-goroutines.txt:#	0x1d9bf34	github.com/minio/minio/cmd.objectAPIHandlers.ListenNotificationHandler+0x15b4	github.com/minio/minio/cmd/listen-notification-handlers.go:158
profile-gamestream-minio-pool-0-4.gamestream-minio-hl.cryengine-test.svc.cluster.local:9000-goroutines.txt:#	0x1d9bf34	github.com/minio/minio/cmd.objectAPIHandlers.ListenNotificationHandler+0x15b4	github.com/minio/minio/cmd/listen-notification-handlers.go:158
```

That is basically holding connections what are you doing on the client side here?  are you sure you know what you are doing here? 

NOTE: you shouldn't be using this API in a manner like regular HTTP APIs, if you use the client here it will hold the connection active and the more you call Listen() APIs it will further hold the connection as well. 

Looks like that is the fundamental reason here, there is no actually no Goroutine leak or FD leak.

**Comment by OxCom** [comment]
@harshavardhana  my bad, stopped ```mc watch``` and few listeners (were not removed), restarted instance and, however, still have grow. I will do dump in 24h again

**Comment by harshavardhana** [comment]
> @harshavardhana  my bad, stopped ```mc watch``` and few listeners (were not removed), restarted instance and, however, still have grow. I will do dump in 24h again

There is already by default 350 goroutines that are internal to us.

**Comment by OxCom** [comment]
@harshavardhana I do not care about amount of goroutines, my issue that number of them is growing without any reason for me. we excluded behavior of ```mc watch``` and I also dropped few NodeJS applications that were attached as listeners. But when I dropped this I still can see that number is growing. So I can assume that issue somewhere else

**Comment by harshavardhana** [comment]
> @harshavardhana I do not care about amount of goroutines, my issue that number of them is growing without any reason for me. we excluded behavior of ```mc watch``` and I also dropped few NodeJS applications that were attached as listeners. But when I dropped this I still can see that number is growing. So I can assume that issue somewhere else
> 

Yes but there is no profile result shared that it is growing. All the goroutines that I see that you shared are normal.

You have to give the exact profile result to show what is the goroutines that are "growing"

I can't see without any incoming calls the server would grow in goroutines. I have setup running with the same version as yours for days now with literally nothing changing.

So it is hard for me to believe whatever you are saying until proven otherwise.

**Comment by OxCom** [comment]
@harshavardhana thanks for help

**Comment by OxCom** [comment]
Unfortunately I have to reopen ticket. The state is the same:
- ```mc mirror --watch``` - removed
- ```nodejs application with event listeners (listenBucketNotification) has been stopped```
no external connections

could you please try to reproduce this on your environment?

**Comment by harshavardhana** [comment]
> Unfortunately I have to reopen ticket. The state is the same:
> 
> * `mc mirror --watch` - removed
> * `nodejs application with event listeners (listenBucketNotification) has been stopped`
>   no external connections
> 
> could you please try to reproduce this on your environment?

There is no way that can happen @OxCom please upgrade to latest and let us know 

Please provide profile captures

**Comment by OxCom** [comment]
checked with this tenant setup (local-storage classes - just disks on VMs with required size)
```yaml
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: minio
  ## Optionally pass annotations to be applied to the statefulset pods
  annotations:
    prometheus.io/path: /minio/v2/metrics/cluster
    prometheus.io/port: "9000"
    prometheus.io/scrape: "true"

spec:
  s3:
    bucketDNS: false
  ## Add environment variables to be set in MinIO container (https://github.com/minio/minio/tree/master/docs/config)
  credsSecret:
    name: minio-secret

  ## Registry location and Tag to download MinIO Server image
  image: minio/minio:RELEASE.2022-03-24T00-43-44Z
  ## Mount path where PV will be mounted inside container(s).
  mountPath: /export
  ## Sub path inside Mount path where MinIO stores data.
  subPath: /data
  ## Specification for MinIO Pool(s) in this Tenant.
  pools:
    ## Servers specifies the number of MinIO Tenant Pods / Servers in this pool.
    ## For standalone mode, supply 1. For distributed mode, supply 4 or more.
    ## Note that the operator does not support upgrading from standalone to distributed mode.
    - name: pool-0
      servers: 2
      ## volumesPerServer specifies the number of volumes attached per MinIO Tenant Pod / Server.
      volumesPerServer: 2
      ## This VolumeClaimTemplate is used across all the volumes provisioned for MinIO Tenant in this
      ## Pool.
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          storageClassName: local-storage
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi
      ## Configure security context
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
  ## Enable automatic Kubernetes based certificate generation and signing as explained in
  ## https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster
  requestAutoCert: false
  ## Prometheus setup for MinIO Tenant.
  prometheus:
    image: "quay.io/prometheus/prometheus:v2.31.1"
    diskCapacityGB: 50
    storageClassName: local-storage
    securityContext:
      fsGroup: 1000
      fsGroupChangePolicy: "OnRootMismatch"
      runAsGroup: 1000
      runAsNonRoot: true
      runAsUser: 1000
```
I did upload over 2Gb files (over 200 of them) to instance before do profiling.
there are 2 profiles: 
~ 1h after start - [1h-82-883.zip](https://github.com/minio/minio/files/8357309/1h-82-883.zip)
~ 22h after start [22h-955-1750.zip](https://github.com/minio/minio/files/8357310/22h-955-1750.zip)

There are nothing that is using MinIO. ATM the number of FD is growing for MinIO process:
```bash
minio   54212 vagrant  494u     sock    0,9      0t0 4266622 protocol: TCPv6
minio   54212 vagrant  495u     sock    0,9      0t0 4309895 protocol: TCP
minio   54212 vagrant  496u     sock    0,9      0t0 4355669 protocol: TCPv6
minio   54212 vagrant  497u     sock    0,9      0t0 4358221 protocol: TCPv6
minio   54212 vagrant  498u     sock    0,9      0t0 4299235 protocol: TCPv6
minio   54212 vagrant  499u     sock    0,9      0t0 4302017 protocol: TCP
minio   54212 vagrant  500u     sock    0,9      0t0 4310076 protocol: TCPv6
minio   54212 vagrant  501u     sock    0,9      0t0 4358222 protocol: TCPv6
minio   54212 vagrant  502u     sock    0,9      0t0 4312131 protocol: TCPv6
```
