### ISSUE TITLE
SSL Handshake error, and no possibility to add SSL cert

### ISSUE THREAD

**Issue by boul2gom** [minio/minio#14563]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

Im using [Nginx Proxy Manager](https://nginxproxymanager.com/) and MinIO in a docker compose stack :
```yaml
MinIO:
    image: minio/minio
    container_name: "MinIO"
    user: root
    networks:
      - YggServer
    volumes:
      - MinIO:/data:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw
    restart: always
    stdin_open: true
    tty: true
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=user
      - MINIO_ROOT_PASSWORD=pass
      - MINIO_DOMAIN=s3.yggdrasil80.tech
      - MINIO_SERVER_URL=https://s3.yggdrasil80.tech/
      - MINIO_BROWSER_REDIRECT_URL=https://s3-dashboard.yggdrasil80.tech/
```

## Expected Behavior

Successfull connexion to MinIO

## Current Behavior

The first time, my self-hosted Reposilite connect successfully to MinIO and publish java artifacts into, but after a reboot i got an exception (https://code.alwyn974.re/cexahejufa.sql)
When i try to add my letsencrypt generated by Nginx Proxy Manager certs to solve this SSL Handshake exception, i got :
```
MinIO         | ERROR Unable to load the TLS configuration: tls: the ECDSA curve 'P-384' is not supported
MinIO         |       > Please check your certificate
```
But i cant choose the curve, bc my certificate is generated by Nginx Proxy Manager !

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2022-03-14T18-25-24Z
* Server setup and configuration: Compose file provided above
* Operating System and version (`uname -a`): Docker container, Linux yggserver 5.10.92-v8+ #1514 SMP PREEMPT Mon Jan 17 17:39:38 GMT 2022 aarch64 GNU/Linu
