### ISSUE TITLE
[USB DRIVES] Bad performance on large datasets & hanging and failing

### ISSUE THREAD

**Issue by moracabanas** [minio/minio#14581]
## Expected Behavior
Minio performance should be ok. But I set up a standalone 8Tb disk with minio and this is the overal performance for 80Mb dataset uploading. The main issue is at this point the **uploading hangs completely**. At this point uploading speed is 100bytes/s. This is not about the HDD performance. If manually copy files using other methods I can get 100-500Kb/s on the same disk with xfs filesystem.

![image](https://user-images.githubusercontent.com/4382333/159116690-ac16f7ae-05a3-441c-b4f7-642e225d215e.png)

EDIT: now it stopped 

![image](https://user-images.githubusercontent.com/4382333/159117007-bf72fdd0-92dc-47c5-b852-2097d8a65248.png)

I setup recommended `/etc/sysctl.conf` tweaks and there is no difference. 

My disk is a generic USB3.0 8TB speeds for large files ar usually good. Is there anything to get normal speeds on dataset collections?

## Steps to Reproduce (for bugs)

1. Format a 8Tb USB3 disk with xfs and bind mount it with docker minio standalone example.
2.  Upload a 80mb dataset with 30k files

## Context
I was looking for a S3 homelab storage for large datasets with decent performance for our testing usecase.

## Your Environment

* Version used (`minio --version`): RELEASE.2022-03-17T06-34-49Z
* Server setup and configuration:  
```yaml
version: "3.4"

services: 
  # minio service
  minio:
    image: quay.io/minio/minio:RELEASE.2022-03-17T06-34-49Z
    container_name: minio
    expose:
      - "9000" # S3
      - "9001" # Console
    volumes:
      - /media/data1:/data1

    environment:
      - MINIO_ROOT_USER=************************
      - MINIO_ROOT_PASSWORD=*********************************
      - MINIO_SERVER_URL=https://s3.*********************.com
      - MINIO_DOMAIN=s3.********************.com
      - MINIO_BROWSER_REDIRECT_URL=https://storage.********************.com
    command: 'server /data1 --console-address ":9001"'
```  

* Operating System and version (`uname -a`): `Linux raspberrypi 5.10.63-v8+ #1457 SMP PREEMPT Tue Sep 28 11:27:02 BST 2021 aarch64 GNU/Linux`
