### ISSUE TITLE
MinIO is unable to initialize config with KES encryption after restart KES

### ISSUE THREAD

**Issue by pibarreche** [minio/minio#14800]
## Bug Description
MinIO is unable to initialize config with KES encryption after restart KES. When MinIO start at first time works fine, but if you restart KES Server and MinIO Server then throw an exception:

```
API: SYSTEM()
Time: 12:11:12 UTC 04/22/2022
DeploymentID: f4600abf-2edd-41e8-b796-7e89aa37869e
Error: Unable to initialize config, some features may be missing migrateMinioSysConfig: EOF (*fmt.wrapError)
       3: cmd/server-main.go:391:cmd.initConfigSubsystem()
       2: cmd/server-main.go:352:cmd.initServer()
       1: cmd/server-main.go:531:cmd.serverMain()

API: https://127.0.0.1:9000

Console: https://172.22.0.3:9001 https://127.0.0.1:9001 

Documentation: https://docs.min.io

API: SYSTEM()
Time: 12:11:12 UTC 04/22/2022
DeploymentID: f4600abf-2edd-41e8-b796-7e89aa37869e
Error: Unable to migrate IAM users and policies to new format: decryption failed: ciphertext is not authentic (*fmt.wrapError)
       1: cmd/iam.go:279:cmd.(*IAMSys).Init()

API: SYSTEM()
Time: 12:11:12 UTC 04/22/2022
DeploymentID: f4600abf-2edd-41e8-b796-7e89aa37869e
Error: IAM sub-system is partially initialized, some users may not be available (*errors.errorString)
       1: cmd/iam.go:280:cmd.(*IAMSys).Init()
```

The MinIO server is up after restart. But when you login into Console, the MinIO Server throw this exception:

```
API: SYSTEM()
Time: 12:13:07 UTC 04/22/2022
DeploymentID: f4600abf-2edd-41e8-b796-7e89aa37869e
Error: expected policy (consoleAdmin) missing from the JWT claim , rejecting the request (*errors.errorString)
       5: cmd/iam.go:1560:cmd.(*IAMSys).IsAllowedSTS()
       4: cmd/iam.go:1647:cmd.(*IAMSys).IsAllowed()
       3: cmd/admin-handlers-users.go:1078:cmd.adminAPIHandlers.AccountInfoHandler.func1()
       2: cmd/admin-handlers-users.go:1166:cmd.adminAPIHandlers.AccountInfoHandler()
       1: net/http/server.go:2047:http.HandlerFunc.ServeHTTP()
```

And you don't able to do anything on Console:
* You don't able to create/manage a bucket
* You don't able to create a new user or a new Service Account
* You don't able to create a Access Policy
* You don't have access to Monitoring Menu
* You don't have access to Support Menu
* You don't have access to Setings Menu

If you try to access to a resuorce through the API, the response is
```
 MinIO API responded with message=Access denied on the resource: XXXXXXX
```

## Expected Behavior
MinIO should back to work again after a reboot of KES Server.

## Current Behavior
After restart the KES Server and MinIO Server, it's throw an exception.

## Steps to Reproduce
1. Start KES Server
2. Start MinIO server with the KES set up
3. Create a bucket and set up the encryption option to SSE-S3
4. Create a Service Account with Policy to use the bucket created in point 3
5. Shootdown MinIO Server
6. Shootdown KES Server
7. Start KES Server
8. Start MinIO Server
9. Try to do something in Console.
10. Try to call any operation by MinIO API

## Context
Trying to test a Disaster Recovery Plan in a Stage environment. I need the MinIO instance back to work again after a reboot of KES Server and/or MinIO server.
Also I need MinIO and KES instance back to work again after a version upgrade.

## Your Environment
* Environment: Develop / Stage
* MinIO version (`minio --version`): RELEASE.2022-04-16T04-26-02Z
* KES version (`kes --version`): 0.19.2
* Server setup and configuration: Simple docker-compose using MinIO and KES with File System as key store. Following this instructions: [MinIO Object Storage](https://github.com/minio/kes/wiki/MinIO-Object-Storage)

**KES config.yml**

```yaml
address: 0.0.0.0:7373 # Listen on all network interfaces on port 7373

admin:
  identity: disabled  # We disable the admin identity since we don't need it in this guide 
   
tls:
  key: /certs/private.key   # The KES server TLS private key
  cert: /certs/public.crt  # The KES server TLS certificate

policy:
  minio: 
    allow:
    - /v1/key/create/ea029258-b591-11ec-a520-0242ac180002*
    - /v1/key/generate/ea029258-b591-11ec-a520-0242ac180002*
    - /v1/key/decrypt/ea029258-b591-11ec-a520-0242ac180002*
    identities:
    - 0a97d5c2200b7e2728175f0201eda539453f24f76eb47ea67a58b869dbce2413 # Use the identity of your client.crt
   
keystore:
  fs:
    path: ./keys # Choose a directory for the secret keys
```

**MinIO KES set up**

```yaml
environment:
      MINIO_KMS_KES_ENDPOINT: https://kes:7373
      MINIO_KMS_KES_KEY_FILE: /root/.minio/certs/kes/client/minio-client.key
      MINIO_KMS_KES_CERT_FILE: /root/.minio/certs/kes/client/minio-client.crt
      MINIO_KMS_KES_CAPATH: /root/.minio/certs/kes/server/public.crt
      MINIO_KMS_KES_KEY_NAME: ea029258-b591-11ec-a520-0242ac180002
```
