### ISSUE TITLE
minio make bucket job / make user job still in state running (but buckets and users are created successfull)

### ISSUE THREAD

**Issue by r0b1ndot** [minio/minio#14834]
**MINIO make bucket job / make user job still in state running**

i setted up MINIO via argocd.
after the cluster is running, the pod make bucket job / make user job is spawning.
that state is all the time "running" but the container did not finish, it exit's after the timeout of the crash back loop but the buckets/users are created, so the issue here looks like the state (running) did not get to an end after the job is executed.

## Expected Behavior
- after setting the users/buckets the make user/bucket pod should exit with exit 0

## Current Behavior
- make users/bucket pod exit with crash back loop / timeout but the users/buckets are created.

## Possible Solution
/

## Steps to Reproduce (for bugs)

set config like shown in environment and add/modify bucket/users section.
```
`Connecting to MinIO server: http://minio:9000

mc: <ERROR> Unable to initialize new alias from the provided credentials. Get "http://minio:9000/probe-bucket-sign-vdfsjcvhs/?location=": dial tcp CLUSTERIP:9000: connect: connection refused.
"Failed attempts: 1"
Added `myminio` successfully.
Purging bucket 'bucket1'.
Bucket 'bucket1' already exists.
Bucket 'bucket1' versioning unchanged.
Setting policy of bucket 'bucket1' to 'none'.
Access permission for `myminio/bucket1` is set to `private`
Purging bucket 'bucket2'.
Bucket 'bucket2' already exists.
Bucket 'bucket2' versioning unchanged.
Setting policy of bucket 'bucket2' to 'none'.

and for make user job:

Connecting to MinIO server: http://minio:9000

mc: <ERROR> Unable to initialize new alias from the provided credentials. Get "http://minio:9000/probe-bucket-sign-vdfsjcvhs/?location=": dial tcp CLUSTERIP:9000: connect: connection refused.

"Failed attempts: 1"
Added `myminio` successfully.
User 'minio1' already exists.
Adding policy 'consoleAdmin' for 'minio1'
Policy `consoleAdmin` is set on user `minio1`
Access permission for `myminio/bucket2` is set to `private`
```

via kubectl it looks like that:
```
kubectl get pods 
NAME                          READY   STATUS     RESTARTS   AGE
minio-7a43cda66g-vpp6h        2/2     Running    0          17m
minio-make-bucket-job-8tp22   1/2     NotReady   0          17m
minio-make-user-job-wk7nm     1/2     NotReady   0          17m

```
## Context

this issue affects me since my argo deployment don't get green since the job state is running but the tasks of the job are done.

## Regression
 NO

## Your Environment

* Version used (`minio --version`):
minio -version
minio version RELEASE.2022-04-16T04-26-02Z

minio mc version: RELEASE.2022-04-16T21-11-21Z

* Server setup and configuration:
MINIO HELM CONFIG (part of the values.yaml)

```
 users:
    - accessKey: minio1
      secretKey: passwordtest
      policy: consoleAdmin
    

  ## List of buckets to be created after minio install
  ##
  buckets:
  #   # Name of the bucket
      - name: bucket1
        policy: none
        purge: false
      - name: bucket2
        policy: none
        purge: true
```
* Operating System and version (`uname -a`):
Debian Buster
