### ISSUE TITLE
minIO - Failure with synchronizing a disabled instance

### ISSUE THREAD

**Issue by brknapik** [minio/minio#14891]
## NOTE
Hi,
After updating minIO docker image from `RELEASE.2021-12-27T07-23-18Z` version to `RELEASE.2022-05-04T07-45-27Z`, we found critical problem according to synchronization after booting up disabled instance.

## Expected Behavior

Synchronization of the content of objects with buckets for the re-enabled instance should behave in such a way that it does not overwrite out-of-date files from the disabled instance to the currently remaining machines

## Current Behavior
Turning on the instance again does not update the objects. The GUI displays the various files and directories that are stored in memory alternately. You can notice this by refreshing the page. New objects are not updated in the volumes and old objects are not deleted (e.g. deleted when the instance is unavailable). When the instance is turned on again, they are visible.

## Steps to Reproduce (for bugs)

1. Turn off one of your instances (keeping an appropriate quorum)
2. Add/Remove/Create bucket/files/subfolders
3. Turn on the instances
4. Check file directories, and compare resource between instances
5. Check GUI

## Context

_The contents of a disabled instance that has been re-enabled_
```
data1/aSsyP9Jcu6hsyBTTB/uploads/:
total 0
drwxr-xr-x. 3 root root 31 May  6 14:25 F7gTRBiPWMonijnwN
drwxr-xr-x. 4 root root 56 May  6 14:25 gW5e7LPA3wHy7Tf3drE4bcnDYcvqTqc9ar
drwxr-xr-x. 3 root root 31 May  6 14:25 mwWmTFiL25QmpZ7te
drwxr-xr-x. 3 root root 31 May  6 14:25 userData
drwxr-xr-x. 3 root root 31 May  6 14:25 voENKpKD9csmTMgyr
drwxr-xr-x. 3 root root 31 May  6 14:25 xaEMckpkPGNi4NekS
drwxr-xr-x. 3 root root 31 May  9 08:19 YqhvJDqGpqCxnrSi9

data2/aSsyP9Jcu6hsyBTTB/uploads/:
total 0
drwxr-xr-x. 3 root root 31 May  6 14:25 F7gTRBiPWMonijnwN
drwxr-xr-x. 4 root root 56 May  6 14:25 gW5e7LPA3wHy7Tf3drE4bcnDYcvqTqc9ar
drwxr-xr-x. 3 root root 31 May  6 14:25 mwWmTFiL25QmpZ7te
drwxr-xr-x. 3 root root 31 May  6 14:25 userData
drwxr-xr-x. 3 root root 31 May  6 14:25 voENKpKD9csmTMgyr
drwxr-xr-x. 3 root root 31 May  6 14:25 xaEMckpkPGNi4NekS
drwxr-xr-x. 3 root root 31 May  9 08:19 YqhvJDqGpqCxnrSi9
```

Another instance

```
data1/aSsyP9Jcu6hsyBTTB/uploads/:
total 0
drwxr-xr-x. 3 root root 31 May 11 12:15 mwWmTFiL25QmpZ7te

data2/aSsyP9Jcu6hsyBTTB/uploads/:
total 0
drwxr-xr-x. 3 root root 31 May 11 12:15 mwWmTFiL25QmpZ7te
```
## Your Environment

* Version used (`minio --version`): RELEASE.2022-05-04T07-45-27Z
* Server setup and configuration: Docker-compose
* Numer of instances: 4
* Disks: 8
* Operating System and version (`uname -a`): CentOS Linux 7 (Core) 3.10.0-1127.el7.x86_64

**Comment by harshavardhana** [comment]
Can you provide your command line for the deployment?

**Comment by brknapik** [comment]
```
version: '3.7'

services:
  minio1:
    image: minio/minio:RELEASE.2022-05-04T07-45-27Z
    volumes:
     - /home/minio/minio/certs:/root/.minio/certs/CAs
     - ./data1:/data1
     - ./data2:/data2
    expose:
      - "9000"
      - "9001"
    ports:
      - 9000:9000
      - 9001:9001
    network_mode: "host"
    environment:
      MINIO_ROOT_USER: <ADMIN>
      MINIO_ROOT_PASSWORD: <PASSWORD>
      MINIO_PROMETHEUS_AUTH_TYPE: public
      MINIO_PROMETHEUS_URL: http://<IPADDRESS>:9090
      MINIO_BROWSER_REDIRECT_URL: https://<URL>
      MINIO_SERVER_URL:  https://<URL>
      http_proxy: http://<IPADDRESSES>:8080
      HTTP_proxy: http://<IPADDRESSES>:8080
      https_proxy: http://<IPADDRESSES>:8080
      HTTPS_proxy: http://<IPADDRESSES>:8080
      no_proxy: <IPADDRESSES>
    command:
      server -S /root/.minio/certs/CAs --console-address :9001 --address :9000 <IPADDRESSES>
    healthcheck:
      test: ["CMD", "curl", "-f", "https://<IPADDRESSES>:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    extra_hosts:
      - "<IPADDRESS>"
```
