### ISSUE TITLE
Ingress Path Not Working.

### ISSUE THREAD

**Issue by Sam-Sundar-Apty** [minio/minio#14982]
Hey Team,

I'm trying to upgrade from old version of MinIo to latest one and we found we had to make multiple changes, 

```yaml
    spec:
      containers:
      - args:
        - server
        - /storage
        - --console-address
        - :9001
        env:
        - name: MINIO_ROOT_USER
          value: minio
        - name: MINIO_ROOT_PASSWORD
          value: minio123
        #- name: MINIO_BROWSER_REDIRECT_URL
        #  value: https://onprem-test.development.apty.io
        image: minio/minio:latest
        imagePullPolicy: IfNotPresent
        name: minio
        ports:
        - containerPort: 9000
          name: api-port
          protocol: TCP
        - containerPort: 9001
          name: console-port
          protocol: TCP
        resources:
```

This is my svc definition
``` bash
minio-api-service         NodePort    10.96.1.117   <none>        9000:31822/TCP                  29m
minio-service             NodePort    10.96.0.155   <none>        9001:31823/TCP                  38d
```
This is my ingress file
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  projectcontour.io/response-timeout: infinity
  name: https-ingress
  namespace: default
spec:
  rules:
  - host: onprem-test.development.apty.io
    http:
      paths:
      - backend:
          service:
            name: minio-service
            port:
              number: 9001
        path: /minio/
        pathType: Prefix
  tls:
  - hosts:
    - onprem-test.development.apty.io
    secretName: apty-onprem
status:
  loadBalancer: {}
 ```` 
 
 When i try to hit <domain>/minio, it's not opening console
 
![image](https://user-images.githubusercontent.com/83000807/170481711-41fa07c4-fa78-4ca9-b6f8-cc815867e254.png)
