### ISSUE TITLE
`metrics` endpoint unreachable in cluster if one node is down

### ISSUE THREAD

**Issue by DAGorchakov** [minio/minio#14988]
## NOTE
There is an error in Prometheus that all cluster is down in minio cluster with 5 nodes and 10 disks (2 disks for each node) if one node is down because endpoints (https://[node_name]:9000/minio/v2/metrics/cluster) on all nodes are unreachable.

## Expected Behavior
`metrics` endpoint is reachable on alive nodes if one node is down

## Current Behavior
One node down. Try to `curl` any alive node (https://[node_name]:9000/minio/v2/metrics/cluster) and finally get `time out error`

## Possible Solution
I've never faced this error before with minio v. RELEASE.2021-04-22T15-44-28Z, but I've faced it after update to RELEASE.2022-05-04T07-45-27Z

## Steps to Reproduce (for bugs)
start minio with:
```
ExecStart=/usr/local/bin/minio server --console-address :9900 --address :9000 https://minio-0{1...5}.domain.com/var/minio/data{1...2}
```
in Prometheus config:
```
# Monitoring MinIO

  - job_name: minio
    metrics_path: /minio/v2/metrics/cluster
    scheme: 'https'
    static_configs:
      - targets:
        - minio-01.domain.com:9000
        - minio-02.domain.com:9000
        - minio-03.domain.com:9000
        - minio-04.domain.com:9000
        - minio-05.domain.com:9000
        labels:
          project: minio
```
stop one service with `sudo systemctl stop minio` and see `up{job="minio",project="minio"} == 0` for all nodes for some time

## Context
dummy alerts in case when api is online annoy support team, especially at night =)

## Your Environment
* minio version RELEASE.2022-05-04T07-45-27Z
* Prometheus version 2.27.1
* Linux minio-01 3.10.0-1160.59.1.el7.x86_64 1 SMP Wed Feb 16 12:17:35 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux (Red Hat Enterprise Linux Server 7.9 (Maipo))
