### ISSUE TITLE
Minio doesn't do the same as S3 when the key starts with `s3://`.

### ISSUE THREAD

**Issue by spelufo** [minio/minio#15011]
## Expected Behavior
Minio does the same as S3 when the key starts with `s3://`.

## Current Behavior
Minio responds with bad request when sent api calls where the key starts with `s3://`.

## Possible Solution
Minio does the same as S3 when the key starts with `s3://`. Minio's behavior is "better" / safer / more consistent with the S3 documentation, arguably, but if compatibility with S3 is more important minio should probably accept these keys, like S3 does. Not my call.

## Steps to Reproduce (for bugs)
Send minio API calls where the key starts with `s3://my-bucket`.

## Context
We discovered this through trying to integrate minio with airflow. Please see [airflow issue 23965](https://github.com/apache/airflow/issues/23965) for more information.

## Your Environment
Started minio in a local kubernetes kind cluster applying the following yaml.
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: minio
  namespace: dcw-dev123
  labels:
    app: minio
spec:
  containers:
    - name: minio
      image: "quay.io/minio/minio"
      args:
        - 'server'
        - '/data'
        - '--console-address'
        - ':9001'
      env:
        - name: 'MINIO_ROOT_USER'
          value: 'AKIAIOSFODNN7EXAMPLE'
        - name: 'MINIO_ROOT_PASSWORD'
          value: 'wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY'
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: dcw-dev123
spec:
  selector:
    app: minio
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
```
