### ISSUE TITLE
Can't connect to other port than 900 with docker

### ISSUE THREAD

**Issue by bastien70** [minio/minio#15087]
## Expected Behavior
Hello, I would like to use minio with docker, but I've some errors.
I can't use port 900 (which is default) because it is already used, so I changed the port to 9004.
I want to set up a public bucket too.

My **docker-compose.yml** :

```yaml
version: '3'

services:
    minio:
        image: minio/minio
        environment:
            MINIO_ROOT_USER: minio
            MINIO_ROOT_PASSWORD: minio123
        volumes:
            - ./data/minio:/data
        command: server /data --console-address ":9001"
        ports:
            - 9004:9004
            - 9001:9001

    createbuckets:
        image: minio/mc
        depends_on:
            - minio
        entrypoint: >
            /bin/sh -c "
            /usr/bin/mc alias set myminio http://127.0.0.1:9004 minio minio123;
            /usr/bin/mc mb myminio/somebucketname;
            /usr/bin/mc policy set public myminio/somebucketname;
            exit 0;
            "
```

## Current Behavior

This is the console output : 

![image](https://user-images.githubusercontent.com/53140475/173788827-c9258dc6-aa47-4331-8cb2-6a3420810bd5.png)

Why in this line : `API: http://192.168.64.3:9000  http://127.0.0.1:9000` the target is port 9000 ??
And in the console, it says that the connection, for bucket creation.

If I create manually a bucket named "mybucket", and in PHP I try to send data on it with flysystem, like this : 

```php
$client = new S3Client([
            'version' => 'latest',
            'region' => 'eu-east-1',
            'credentials' => [
                'key' => 'minio',
                'secret' => 'minio123',
            ],
            'endpoint' => 'http://127.0.0.1:9004'
        ]);

        $adapter = new AwsS3V3Adapter(
            $client,
            'mybucket',
            'backups'
        );

        $filesystem = new Filesystem($adapter);
        $fileNameTest = sprintf('dbsaver-check-%s.txt', random_int(1, 9999));
        $filesystem->write($fileNameTest, 'DbSaver test file. Will be immediately removed.');
```
I've the following error : 

```
Error executing "PutObject" on "http://127.0.0.1:9004/mybucket/backups/dbsaver-check-8762.txt"; AWS HTTP error: cURL error 56: Recv failure: Connection reset by peer (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://127.0.0.1:9004/mybucket/backups/dbsaver-check-8762.txt
```

## Steps to Reproduce (for bugs)

Just use my docker-compose file config, with different port.

## Your Environment
Latest minio version
Linux Ubuntu
