### ISSUE TITLE
Elegant Swarm Deployment that fails

### ISSUE THREAD

**Issue by chrisbecke** [minio/minio#15138]
**Is your feature request related to a problem? Please describe.**
Docker swarm supports service templates which allows the hostname of a service to be set using variables. This allows for a very simple docker swarm deployment.

Rather than the usual 4 named services "minio1", "minio2", "minio3", "minio4" example, we can get docker to generate the hostnames on a single service using the following compose.yml - and specify replicas=4.

```yaml
version: "3.9"

services:
  minio:
    image: "minio/minio:latest"
    hostname: "minio{{.Task.Slot}}"
    command: "server http://minio{1...4}/data"
    secrets:
    - access_key
    - secret_key
    volumes:
    - data:/data
    deploy:
      replicas: 4
      placement:
        max_replicas_per_node: 1
       constraints:
       - node.labels.minio=true
    ports:
    - 9000:9000

volumes:
  data:

secrets:
  access_key:
    file: access_key
  secret_key:
    file: secret_key
```

This has clear advantages over the prior method as "minio" is now the label for the service and we can easilly examine the service to see the number of docker replicas. Additionally consumers of minio on docker swarm can just use "minio" to be loadbalanced accross all 4 minio instances using dockers service mesh.

The problem comes about because docker provides no way to pin a particular task to a particular host. So if two nodes are rebooted, it is possible for them to re-order which node is identified as "minio1" and which is "minio2". (for example). However, the local disk volume remains the same.

**Describe the solution you'd like**
minio to be - optionally - tolerant of the hostname to disk mapping changing. If a disk that was previously used by a host identified as "minio1" get picked up and used by "minio2" this should not be a problem.

**Describe alternatives you've considered**
Clearly I can continue to deploy minio using 4 seperate single replica services, but during the poc- before the problems became apparent - the benefits of being able to manage minio via a single service are hard to pass up.

Alternatively Docker need to fix their stuff as there are a number of other clustered products that have a hard binding between the data volume and the hostname - with more options to pin tasks to nodes in the docker service labels, none of these products need to change to cater for single-service deployments.

**Additional context**
Mirantis has committed to supporting docker swarm for at least another 3 years.
