### ISSUE TITLE
using _FILE environment variables doesn't work?

### ISSUE THREAD

**Issue by tamis-laan** [minio/minio#15174]
I'm using the minio docker image with docker swarm. Everything worked before I switched to docker secrets. I changed the environment variables to `*_FILE`.
``` yaml
  # Object Store
  minio:
    hostname: minio
    image: minio/minio
    volumes:
      - minio-data:/data
    secrets:
      - minio-root-user
      - minio-root-pass
      - minio-access-key
      - minio-secret-key
    environment:
      MINIO_ROOT_USER_FILE: /run/secrets/minio-root-user
      MINIO_ROOT_PASSWORD_FILE: /run/secrets/minio-root-pass
      MINIO_ACCESS_KEY_FILE: /run/secrets/minio-access-key
      MINIO_SECRET_KEY_FILE: /run/secrets/minio-secret-key
    command: server --console-address :9001 /data
    restart: unless-stopped

  # Minio deploy
  minio-deploy:
    image: minio/mc
    secrets:
      - minio-access-key
      - minio-secret-key
    entrypoint: >
      /bin/sh -c "
      until (mc config host add myminio http://minio:9000 $$(cat /run/secrets/minio-access-key) $$(cat /run/secrets/minio-secret-key)) 
      do 
        echo '...waiting...' && sleep 2;
      done;
      mc mb myminio/${SERVER_BUCKET_EVENTS};
      mc policy set download myminio/${SERVER_BUCKET_EVENTS};
      mc mb myminio/${SERVER_BUCKET_USERS};
      mc policy set download myminio/${SERVER_BUCKET_USERS};
      exit 0;
      "
    depends_on:
      - minio
    deploy:
      restart_policy:
        condition: on-failure 
```
This results in no longer being able to login. Sometimes the console gives the following error when trying to login:
`Post "http://10.0.0.65:9000/": dial tcp 10.0.0.65:9000: i/o timeout`

Also trying to push an object to a bucket generates the following error:
`S3Error: Access Denied.`

Not sure why things stopped working simply switching to docker secrets.

**Comment by harshavardhana** [comment]
> This results in no longer being able to login. Sometimes the console gives the following error when trying to login:
> `Post "http://10.0.0.65:9000/": dial tcp 10.0.0.65:9000: i/o timeout`

This has nothing to do with not being able to read credentials.



> Also trying to push an object to a bucket generates the following error:
> `S3Error: Access Denied.`

This is also not correct - this looks like your client doesn't use any authorization credentials.

**Comment by tamis-laan** [comment]
> > This results in no longer being able to login. Sometimes the console gives the following error when trying to login:
> > `Post "http://10.0.0.65:9000/": dial tcp 10.0.0.65:9000: i/o timeout`
> 
> This has nothing to do with not being able to read credentials.
So why does this happen when switching to swarm? I checked the ip `10.0.0.65` and it's correct.

**Comment by harshavardhana** [comment]
> > > This results in no longer being able to login. Sometimes the console gives the following error when trying to login:
> > > `Post "http://10.0.0.65:9000/": dial tcp 10.0.0.65:9000: i/o timeout`
> > 
> > 
> > This has nothing to do with not being able to read credentials.
> > So why does this happen when switching to swarm? I checked the ip `10.0.0.65` and it's correct.

Swarm is broken please don't use it. We do not support it and neither does docker project.

Please use kubernetes if you want swarm.

**Comment by tamis-laan** [comment]
> > > > This results in no longer being able to login. Sometimes the console gives the following error when trying to login:
> > > > `Post "http://10.0.0.65:9000/": dial tcp 10.0.0.65:9000: i/o timeout`
> > > 
> > > 
> > > This has nothing to do with not being able to read credentials.
> > > So why does this happen when switching to swarm? I checked the ip `10.0.0.65` and it's correct.
> 
> Swarm is broken please don't use it. We do not support it and neither does docker project.
> 
> Please use kubernetes if you want swarm.

Happy to use Kubernetes but this would be a big investment of time and effort, something for the future. Right now I'm trying to become operational. Everything else works perfectly on swarm, just Minio doesn't want to work when using the `_FILE` directive. 

BTW I found the problem in the client, was not using the correct access/secret keys. I fixed that problem now I'm getting:
`S3Error: The Access Key Id you provided does not exist in our records.`
So I think the `_FILE` directive is broken/bugged and so the access and secret keys are not loaded in from disk.

**Comment by tamis-laan** [comment]
If I change the environment variables from:
``` yaml
environment:
  MINIO_ROOT_USER_FILE: /run/secrets/minio-root-user # <--
  MINIO_ROOT_PASSWORD_FILE: /run/secrets/minio-root-pass # <--
  MINIO_ACCESS_KEY_FILE: /run/secrets/minio-access-key
  MINIO_SECRET_KEY_FILE: /run/secrets/minio-secret-key
```
to
``` yaml
environment:
  MINIO_SERVER_URL: http://minio:9000
  MINIO_ROOT_USER_FILE: /run/secrets/minio-access-key # <--
  MINIO_ROOT_PASSWORD_FILE: /run/secrets/minio-secret-key # <--
  MINIO_ACCESS_KEY_FILE: /run/secrets/minio-access-key
  MINIO_SECRET_KEY_FILE: /run/secrets/minio-secret-key
```
then my client and console work properly.

In other words I use the access key and secret key as the user and password my client works. I now need to longin to the console using the access and secret key. 

I'm confused why this happens, is this a bug?
