### ISSUE TITLE
Helm chart does not support special characters in access/secret key

### ISSUE THREAD

**Issue by OvervCW** [minio/minio#15221]
You can have the Helm chart in this repository create users in Minio by specifying values like this:

```yaml
users:
    - accessKey: xxx
      secretKey: xxx
      policy: consoleAdmin
```

This works fine as long as the `accessKey` and `secretKey` don't contain any special characters. However, when I tried the following values:

```yaml
users:
  - accessKey: "tv:(()KW5$`>@/c:dB6_=.4|{jv?@!"
    secretKey: ".B_ES205}Mjzrh}G{emJi'LEuUE#:R"
    policy: consoleAdmin
```

The `minio-make-user-job` pod failed with the following error:

```
/config/add-user: line 72: syntax error near unexpected token `('
```

## Expected Behavior
I expected the chart to create a user with the specified access key and secret key.

## Current Behavior
The chart fails to create the user.

## Possible Solution
The problem is that the access key and secret key are inserted verbatim into a bash script:

https://github.com/minio/minio/blob/ce667ddae007a13df0020f6879fe5e0f955ba368/helm/minio/templates/_helper_create_user.txt#L78-L88

That means that characters like ` (backtick) and ( (parenthesis) are interpreted as bash syntax rather than a literal value. The script should properly escape these values, for example by encoding them using base64.

## Steps to Reproduce (for bugs)
Deploy the chart with the values mentioned above.

## Context
I'm trying to create a user with a secure password.

## Regression
As far as I can tell this has always been broken.

## Your Environment

* Version used (`minio --version`): N/A
* Server setup and configuration: N/A
* Operating System and version (`uname -a`): N/A
