### ISSUE TITLE
default credentials will not change with env changes

### ISSUE THREAD

**Issue by E-4forlife** [minio/minio#15248]
## NOTE
All GitHub issues are addressed on a best-effort basis at MinIO's sole discretion. There are no Service Level Agreements (SLA) or Objectives (SLO). Remember our [Code of Conduct](https://github.com/minio/minio/blob/master/code_of_conduct.md) when engaging with MinIO Engineers and the larger community.

For urgent issues (e.g. production down, etc.), subscribe to [SUBNET](https://min.io/pricing?jmp=github) for direct to engineering support.
 

## Current Behavior
I am trying to set up the minio container and nonmatter what variables I use i can not change the root account and password it stays minioadmin:minioadmin the following it my sanitized docker compose.

## Steps to Reproduce (for bugs)

compose with the following docker compose 

version: '3.7'
services:
  MinIO:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: unless-stopped
    volumes:
      - /home/kolby/nfs-share:/dat
    environment:
      - MINIO_ROOT_USER:"user"
      - MINIO_ROOT_PASSWORD:"pass"
      - MINIO_SERVER_URL:"https://s3.domain.com"
      - MINIO_BROWSER_REDIRECT_URL:"https://console.domain.com"
    command: server /data --console-address ":9001"
networks:
  default:
    name: minio
## Context

 I am trying to change the default login credentials 
## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
> environment:
> - MINIO_ROOT_USER:"user"
> - MINIO_ROOT_PASSWORD:"pass"
> - MINIO_SERVER_URL:"https://s3.domain.com"
> - MINIO_BROWSER_REDIRECT_URL:"https://console.domain.com"

This is the wrong usage of the environment field it must be 

```
version: '3.7'

# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2022-07-06T20-29-49Z
  command: server --console-address ":9001" http://minio{1...4}/data{1...2}
  expose:
    - "9000"
    - "9001"
  # environment:
    # MINIO_ROOT_USER: minioadmin
    # MINIO_ROOT_PASSWORD: minioadmin
```

Look at valid example here https://github.com/minio/minio/blob/master/docs/orchestration/docker-compose/docker-compose.yaml
