### ISSUE TITLE
MinIO is unable to connect to LDAP server - says unknown host

### ISSUE THREAD

**Issue by hktegner** [minio/minio#15299]
## Expected Behavior
I expect MinIO server to come up and tell me it has successfully tested connectivity to the LDAP server.

## Actual Behavior
MinIO server says this:
```
minio_server    | API: SYSTEM()
minio_server    | Time: 20:08:18 UTC 07/14/2022
minio_server    | DeploymentID: 34c8e0c6-96a9-473f-92bd-fccb29810cff
minio_server    | Error: LDAP Result Code 200 "Network Error": dial tcp: lookup "ldap://ldap_server:10389": no such host (*ldap.Error)
minio_server    |        2: cmd/iam.go:1646:cmd.(*IAMSys).purgeExpiredCredentialsForLDAP()
minio_server    |        1: cmd/iam.go:670:cmd.(*IAMSys).Init.func2()
```
It says 'no such host', but I can get onto the minio_server and I can both ping and connect to port 10389 on ldap_server.

## Steps to Reproduce (for bugs)
1. Run the following docker-compose file
2. Observe when minio server starts up you get the error quoted above

```
version: '3'
services:
  minio_server:
    image: minio/minio:RELEASE.2021-09-18T18-09-59Z
    depends_on:
      - ldap_server
    container_name: minio_server
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=secretpassword
      - MINIO_IDENTITY_LDAP_SERVER_ADDR="ldap://ldap_server:10389"
      - MINIO_IDENTITY_LDAP_LOOKUP_BIND_DN="uid=admin,ou=system"
      - MINIO_IDENTITY_LDAP_LOOKUP_BIND_PASSWORD="secret"
      - MINIO_IDENTITY_LDAP_USER_DN_SEARCH_BASE_DN="ou=users,dc=wimpi,dc=net"
      - MINIO_IDENTITY_LDAP_USER_DN_SEARCH_FILTER="(&(objectCategory=User)(sn=%s))"
      - MINIO_IDENTITY_LDAP_GROUP_SEARCH_FILTER="(&(objectClass=groupOfNames)(member=%d))"
      - MINIO_IDENTITY_LDAP_GROUP_SEARCH_BASE_DN="ou=groups,ou=system"
    command: server /data --address :9000 --console-address :9001
  ldap_server:
    image: dwimberger/ldap-ad-it:latest
    container_name: ldap_server
    ports:
      - 10389:10389
```

## Context
This is blocking me from using MinIO server on my project. We need to be able to use corporate user identities to log on to the MinIO console.

## Regression
I've only tried this version of MinIO server.

## Your Environment
* Version used (`minio --version`): you can see the exact version from the docker-compose file above.
* Server setup and configuration: docker in WSL on a win10 laptop with 32GB and 500GB hd
* Operating System and version (`uname -a`): it's the official minio/minio image

**Comment by harshavardhana** [comment]
> minio_server    | Error: LDAP Result Code 200 "Network Error": dial tcp: lookup "ldap://ldap_server:10389": no such host (*ldap.Error)

make sure your LDAP is online before MinIO server is brought online


> image: minio/minio:RELEASE.2021-09-18T18-09-59Z

Please upgrade.

**Comment by hktegner** [comment]
@harshavardhana Did you see the docker-compose file? minio server depends on ldap_server.
```
depends_on:
      - ldap_server
```
Also, minio server continues to output this error infinitely (not only at startup). So, no, the problem is not that the ldap server is not there.

**Comment by harshavardhana** [comment]
> depends_on:
>       - ldap_server

That wont' help @hktegner you need to wait for the service using `wait-for-it.sh` like scripts.

**Comment by hktegner** [comment]
> Also, minio server continues to output this error infinitely (not only at startup). So, no, the problem is not that the ldap server is not there.

You keep ignoring the information I send you. It's quite tiring and quite disrespectful.

Although, your suggestion is correct @harshavardhana, you are ignoring the fact that I said above that once the ldap server is up, MinIO still keeps trying and failing to reach the ldap server.

**Comment by hktegner** [comment]
Also, I believe even if the ldap service was not up, the ldap container exists before minio, and MinIO should therefore not be reporting unknown host. The domain name ldap_server exists because docker resolves it to the ldap_server container.

**Comment by hktegner** [comment]
This is the error I get if I bring up the ldap server container first, and then when the ldap server API is available, I bring up minio server.

```
API: SYSTEM()
minio_server    | Time: 12:11:53 UTC 07/15/2022
minio_server    | DeploymentID: 3bb07e53-99a2-4369-b758-21eb7be73682
minio_server    | Error: LDAP Result Code 200 "Network Error": dial tcp: address tcp/10389": unknown port (*ldap.Error)
minio_server    |        3: internal/logger/logger.go:270:logger.LogIf()
minio_server    |        2: cmd/iam.go:1268:cmd.(*IAMSys).updateGroupMembershipsForLDAP()
minio_server    |        1: cmd/iam.go:341:cmd.(*IAMSys).Init.func2()
```

I've changed the address config to `MINIO_IDENTITY_LDAP_SERVER_ADDR="ldap_server:10389"`. Now it says unknown port 🤷‍♀️. (I am using Apache Directory Studio to successfully browse the ldap server on that address.)

**Comment by JonSmall** [comment]
have you resolve this problem ? I got the same 
start with ldap://, it says unknown host
start with ip:port, it says unknown port 
is it bug ？

**Comment by JonSmall** [comment]
have you resolve this problem ? I got the same
start with ldap://, it says unknown host
start with ip:port, it says unknown port
is it bug ？

**Comment by Karmashkin** [comment]
same
ldap is available and successfully used by other services (jenkins, grafana, etc.)
minio show error

docker-compose
```
version: '2.2'

services:
  minio-alpine:
    image: 'minio/minio:RELEASE.2022-08-05T23-27-09Z'
    ports:
      - "${INTERNAL_IP}:9000:9000" # Buckets
      - "${INTERNAL_IP}:9001:9001" # Console
    environment:
      - MINIO_IDENTITY_LDAP_SERVER_ADDR="openldap:389"
      - MINIO_IDENTITY_LDAP_LOOKUP_BIND_DN="cn=Manager,dc=example,dc=com"
      - MINIO_IDENTITY_LDAP_USER_DN_SEARCH_BASE_DN="dc=example,dc=com"
      - MINIO_IDENTITY_LDAP_USER_DN_SEARCH_FILTER="(&(uid=%s)(ou=Minio))"
      - MINIO_IDENTITY_LDAP_LOOKUP_BIND_PASSWORD="XXXXX"
      - MINIO_IDENTITY_LDAP_TLS_SKIP_VERIFY=on
      - MINIO_IDENTITY_LDAP_SERVER_INSECURE=on
      - MINIO_IDENTITY_LDAP_SERVER_STARTTLS=off
    volumes:
      - ./minio-alpine_data/data:/data
    command:  ["server", "--address", ":9000", "--console-address", ":9001", "/data"]

```

error
```
Error: Unable to parse LDAP configuration: LDAP Server Connection Error: Could not connect to LDAP server: LDAP Result Code 200 "Network Error": dial tcp: address tcp/389": unknown port (*fmt.wrapError)
       8: internal/logger/logger.go:259:logger.LogIf()
       7: cmd/config-current.go:572:cmd.lookupConfigs()
       6: cmd/config-current.go:871:cmd.loadConfig()
       5: cmd/config.go:235:cmd.initConfig()
       4: cmd/config.go:195:cmd.(*ConfigSys).Init()
       3: cmd/server-main.go:406:cmd.initConfigSubsystem()
       2: cmd/server-main.go:373:cmd.initServer()
       1: cmd/server-main.go:554:cmd.serverMain()
```

maybe we missed some important detail when setting it up?
Or does this bug fractally open other bugs and is it better not to use ldap with minio ?
