### ISSUE TITLE
RabbitMQ event connect issue ?

### ISSUE THREAD

**Issue by hotrungnhan** [minio/minio#15325]
## Expected Behavior
Connect normally
## Current Behavior
Minio connection is appear in rabbitmq management , but when raising an event, issue happen.

## Possible Solution
May be the issue are caused by  [amqp](https://github.com/streadway/amqp) which are now not actively maintained.
considering switching to https://github.com/rabbitmq/amqp091-go which is a fork and share the same api

## Steps to Reproduce (for bugs)

1. Use docker config like below to run minio 
2. set up an normal rabbitmq

## Context
cant publish event from rabbitmq to default exchange
## Regression
[#470 amqp](https://github.com/streadway/amqp/issues/470)

## Your Environment

* Version used (`minio --version`): RELEASE.2022-07-15T03-44-22Z.fips
* Server setup and configuration:  below
* Operating System and version (`uname -a`):  docker

![image](https://user-images.githubusercontent.com/40029631/179418254-8d7ee478-2737-4789-867e-ffe6d38d5a49.png)

Issue when publish event with rabbitmq

```
version: '3.9'

services:
  database:
    container_name: postgres
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "12345678"
    volumes:
      - ${HOME}/dev-postgres/data/:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  cache:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
  file:
    container_name: minio
    image: minio/minio
    command: "server /data --console-address \":9001\""
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: 12345678
      MINIO_NOTIFY_AMQP_ENABLE: true
      MINIO_NOTIFY_AMQP_URL: amqp://guest:guest@broker:5672
      MINIO_NOTIFY_AMQP_ROUTING_KEY: fastshare-file-upload
      MINIO_NOTIFY_AMQP_EXCHANGE_TYPE: ''
      MINIO_NOTIFY_AMQP_MANDATORY: off
      MINIO_NOTIFY_AMQP_DURABLE: on
      MINIO_NOTIFY_AMQP_DELIVERY_MODE: 2
    depends_on:
      - broker
  broker:
    container_name: rabbitmq
    image: rabbitmq:management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
      - "8080:8080"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
```
