### ISSUE TITLE
Can't connect to my hosted minIO with s3cm

### ISSUE THREAD

**Issue by klibr007** [minio/minio#15336]
## NOTE
Hello everybody I have a minIO launched in a docker-compose that is exposed behind a nginx reverse-proxy. Whenever I try to connect with s3cmd I have this error

![image](https://user-images.githubusercontent.com/50625221/179553400-2c537506-3cca-48f4-8f4c-41f62f664609.png)

here is my compose for minio
```yml
# docker-compose.yml
version: '3.7'

services:
  minio:
    image: quay.io/minio/minio:RELEASE.2022-06-20T23-13-45Z
    restart: always
    command: server /data --console-address ":9001" 
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - /srv/minio/data:/data
    environment:
      - MINIO_ROOT_USER=minioadm
      - MINIO_ROOT_PASSWORD=minioadm
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "1"
        mode: "blocking"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
```

here is my nginx conf 
```conf
server {
        listen 443 ssl;
        ssl_certificate /etc/nginx/certs/wildcard-chained.rns.seres.lan.pem;
        ssl_certificate_key /etc/nginx/certs/wildcard.rns.seres.lan.key;

        server_name    delivery-minio.rns.seres.lan;
        
        location /clicall {
            include proxy_params;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            chunked_transfer_encoding off;
	        proxy_pass http://localhost:9000;
        }

        location / {
            include proxy_params;
	        proxy_pass http://localhost:9001;
        }


        error_page 404 /404.html;
            location = /40x.html {
        }

        error_page 500 502 503 504 /50x.html;
            location = /50x.html {
        }
    }
```

here is my .s3cfg
```
host_base = delivery-minio.rns.seres.lan/clicall
host_bucket = delivery-minio.rns.seres.lan/clicall
bucket_location = us-east-1
use_https = True

# Setup access keys
access_key =  eWYmN4yPRW2kZ8dc
secret_key = ImeA0RZz27e68FbaV1oLoyYlJQfAfb3Q

# Enable S3 v4 signature APIs
signature_v2 = True
```

## Expected Behavior
To work when I try the ls commande

## Current Behavior
An error 403

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment
docker-compose on ubuntu 20

* Version used (`minio --version`): quay.io/minio/minio:RELEASE.2022-06-20T23-13-45Z
* Server setup and configuration:
* Operating System and version (`uname -a`):
