### ISSUE TITLE
Minio Console Login Bug

### ISSUE THREAD

**Issue by martinbohlmann** [minio/minio#15398]
## NOTE

When using the `latest` Minio images the console login is not possible. An error is displayed "An error has occurred \n The backend cannot be reached.". Failing images:

- quay.io/minio/minio:latest (9eb7a8c0440b)
- minio/minio:latest (d2bf99df26cc)

## Expected Behavior
The login should prompt for the user and password. Once introduced, the console should validate the input and if good, proceed to the dashboard. Working versions I have tested:  `RELEASE.2022-06-20T23-13-45Z`

- quay.io/minio/minio:RELEASE.2022-06-20T23-13-45Z (867f287c62a2)
- minio/minio:RELEASE.2022-06-20T23-13-45Z (8ba1043693e4)

## Current Behavior
As in the image below, the console tries to connect to the console port. Getting an error 500.

## Possible Solution
N/A

## Steps to Reproduce (for bugs)

Create the following `docker-compose.yaml` file and launch it `docker-compose up`. Make sure no other process is on ports `9001 and 9005`.

```
version: '3.7'

services:
  minio:
    image: quay.io/minio/minio:latest #fails
    # image: minio/minio:latest #fails
    # image: quay.io/minio/minio:RELEASE.2022-06-20T23-13-45Z # works
    # image: minio/minio:RELEASE.2022-06-20T23-13-45Z # works
    restart: always
    command: server /data --address ":9005" --console-address ":9001" 
    ports:
      - 9005:9005 # API
      - 9001:9001 # Console
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_SERVER_DEBUG
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9005/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
```

## Regression
Yes? It worked in previous version `RELEASE.2022-06-20T23-13-45Z`.

## Your Environment
* Version used: RELEASE.2022-07-24T01-54-52Z (commit-id=ce8548a1a203b247818f6913af5d885361d80c12)
* Server setup and configuration: Docker Desktop
* Operating System and version (`uname -a`): Mac

![Minio_error_latest](https://user-images.githubusercontent.com/9382438/180653921-2fe272e5-2e32-476f-a8e7-10f3a3d9c2b9.jpg)
