### ISSUE TITLE
Single docker instance: insufficient storage resources

### ISSUE THREAD

**Issue by baughmann** [minio/minio#15404]
When deploying a single Minio Docker container, I am unable to upload files through the web UI or AWS S3 SDK. I am new to troubleshooting MinIO though not to using it, so let me know if I am missing any info. 

Thanks for the amazing software BTW, makes my life a lot easier (present circumstances excepted)

## Expected Behavior
Providing access credentials, Docker volumes, and buckets are set up correctly, I should be able to upload files. This was working perfectly fine very recently with no configuration change on my part, that I'm aware of.

## Current Behavior
When uploading via pre-signed PUT utilizing the JavaScript `@aws-sdk/client-s3` at version `^3.109.0`, I receive a HTTP 503 "Service Unavailable" and corresponding stdout in the docker container with the following error:

```
API: SYSTEM()
Time: 12:37:34 UTC 07/26/2022
DeploymentID: a44e1347-d24d-4e5e-a542-19865b36bd82
Error: Storage resources are insufficient for the write operation .minio.sys/buckets/.usage-cache.bin (cmd.InsufficientWriteQuorum)
       2: internal/logger/logger.go:259:logger.LogIf()
       1: cmd/erasure-single-drive.go:3171:cmd.(*erasureSingle).nsScanner.func1()
```

When attempting to upload via the web UI, I see the error "Error: Resource requested is unreadable, please reduce your request rate" displayed in the UI and the following error in teh browser's JavaScript console 
```
POST http://localhost:9090/api/v1/buckets/volumes/objects/upload?prefix=Lw== 500 (Internal Server Error)
(anonymous) @ ListObjects.tsx:1000
a @ ListObjects.tsx:845
```

## Steps to Reproduce (for bugs)

1. Create the docker volume directory (in this case, `mkdir ~/miniodata`)
2. Start new Minio container with the following command:
    ```
    docker run  --name minio \
                --restart unless-stopped \
                -p 9090:9090 -p 9000:9000 \
                -v ~/miniodata:/data \
                -e "MINIO_ROOT_USER=minio" \
                -e "MINIO_ROOT_PASSWORD=minio" \
                minio/minio:latest server /data --console-address ":9090" 
    ```
3. Log into the console at `http://localhost:9090`
4. Create a new bucket `test`
5. Browse to bucket http://localhost:9090/buckets/test/browse
6. Attempt to upload a file utilizing the "Upload" button to the right
7. See the web UI error
8. Run `docker logs minio` and notice the error `Error: Storage resources are insufficient for the write operation`

## Context
N/A

## Regression
N/A

## Your Environment
* Version used (`minio --version`):
```
minio version RELEASE.2022-07-26T00-53-03Z (commit-id=6b4f833a1279faeafa398a9f4e6b1af4605df032)
Runtime: go1.18.4 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2022 MinIO, Inc.
```
* Server setup and configuration:
**Docker (result of `docker version`)**:
```
Client: Docker Engine - Community
 Cloud integration: v1.0.24
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:02:46 2022
 OS/Arch:           linux/amd64
 Context:           desktop-linux
 Experimental:      true

Server: Docker Desktop 4.10.1 (82475)
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:23 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        v1.1.2-0-ga916309
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
* Operating System and version (`uname -a`):
`Linux nickspc 5.15.0-41-generic #44-Ubuntu SMP Wed Jun 22 14:20:53 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by klauspost** [comment]
@harshavardhana A bit strange since it is single-drive mode. Any ideas?

**Comment by baughmann** [comment]
> @harshavardhana A bit strange since it is single-drive mode. Any ideas?

Strange indeed. Something to do with mounting/volumes on the Docker side possibly? Using the following command resolves the issue, though it does not allow me to specify the local directory for the volume. Working on that now and will post here for posterity.

```
docker run  --name minio \
            --restart unless-stopped \
            -p 9090:9090 -p 9000:9000 \
            -v miniovol:/data \
            -e "MINIO_ROOT_USER=minio" \
            -e "MINIO_ROOT_PASSWORD=minio" \
            minio/minio:latest server /data --console-address ":9090" 
```

The key difference between the command above and the one in my original post is that the one above uses a named volume rather than an anonymous one with a local mount point.

I tried this on Fedora the other day with no issues and only recently switched to Ubuntu, so maybe this is an issue with 22.04 + Docker?

Regardless, this should def be at least documented somewhere. I will update you guys with anything I find on my end.

### EDIT

Tried to use a volume with a local mount point using Docker Compose, and ended up with the same error. Here's the `docker-compose.yaml`:

```
version: '3.7'

services:
  minio:
    hostname: minio
    volumes:
      - miniodata:/data
    image: minio/minio:latest
    command: server /data --console-address ":9090"
    ports:
      - "9090:9090"
      - "9000:9000"
    expose:
      - "9000"
      - "9090"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped

volumes:
  miniodata:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/nbaughman/miniodata'
```
