### ISSUE TITLE
vanilla helm chart: make-user-job crashloopbackoff

### ISSUE THREAD

**Issue by one1zero1one** [minio/minio#15438]
Version `4.0.6` of the vanilla chart, the make user job fails with error:

```
Connecting to MinIO server: http://min-io-minio:9000
Added `myminio` successfully.                                                                                                                  cat: /config/secrets/password: No such file or directory
Stream closed EOF for data/min-io-minio-make-user-job--1-cklgb (minio-mc)
```

## Expected Behavior

The job should complete successfully.

## Current Behavior

The job fails. I have tried both adding and removing users in the `values.yaml`, no change in the behaviour.

## Steps to Reproduce (for bugs)

1. deploying minio with the following

```
dependencies:
  - name: minio
    version: 4.0.6
    repository: "https://charts.min.io/"
```

## Regression

Did not happen before 4.0.6

## Your Environment

Deploying with ArgoCD to EKS 1.22.

`values.yaml` declares couple users, policies, buckets. Everything works as expected (as it was declared before the bug was introduced).

**Comment by dormanze** [comment]
can you upload your value.yaml?
I want to see your configuration about:
![image](https://user-images.githubusercontent.com/37854724/181914210-40f54072-47ca-479b-8575-b7c233140f06.png)

**Comment by one1zero1one** [comment]
Thanks for the answer @dormanze here's the users section:

```yaml
  users:
    - accessKey: models
      existingSecret: minio-secret-models
      existingSecretKey: password
      policy: readwritemodels

    - accessKey: console
      existingSecret: minio-secret-console
      existingSecretKey: password
      policy: consoleAdmin

    - accessKey: write-creations
      existingSecret: minio-secret-creations
      existingSecretKey: passwordwrite
      policy: writecreationspolicy

    - accessKey: read-creations
      existingSecret: minio-secret-creations
      existingSecretKey: passwordread
      policy: readonlycreationspolicy

    - accessKey: argo
      existingSecret: minio-secret-argo
      existingSecretKey: passwordrw
      policy: readwriteargo
```

I checked each individual secret, all keys are present.
