### ISSUE TITLE
enable locking/retention during bucket creation

### ISSUE THREAD

**Issue by r0b1ndot** [minio/minio#15460]
**Is your feature request related to a problem? Please describe.**
i came to the problem that i need buckets with locking enabled and also a custom retention policy (2 Days).
via the mc tool and the bucket creation you can submit the '--with-lock' param https://docs.min.io/minio/baremetal/object-retention/minio-object-locking.html

for the retention you need to issue a command like:
```
mc retention set --default GOVERNANCE "2d" myminio/bucketname
```

**Describe the solution you'd like**
a clear way to set this via bucket creation would be appreciated like:

```
  buckets:
         # Name of the bucket
      - name: examplebucket
        policy: upload
        purge: true
        versioning: true
        locking: true
        object_retention: 2d
```
**Describe alternatives you've considered**
as alternative there are the known mc commands, but to get a fully automated deployment,  setting via the helm chart would be more appreciated.

**Additional context**
/
