### ISSUE TITLE
Cannot declarative users create, credentials file is invalid

### ISSUE THREAD

**Issue by CRASH-Tech** [minio/minio#15480]
Im trying to create users over helm chart, and get this error

```
job/argo-stack-minio-make-user-job po/argo-stack-minio-make-user-job-kqlrq container/minio-mc logs
  Connecting to MinIO server: http://argo-stack-minio:9000
  Added `myminio` successfully.
  credentials file is invalid
```
My values file:
```
users:
  - accessKey: workflows
    existingSecret: minio-admin-user
    existingSecretKey: workflowsSecretKey
    policy: argo-workflows-policy
```

My secret:
```
kind: Secret
apiVersion: v1
metadata:
  name: minio-admin-user
  namespace: argo-stack
data:
  rootPassword: NmY3WFU2UktoS1BiNjJvRA==
  rootUser: YWRtaW4=
  workflowsAccessKey: d29ya2Zsb3dzLWFkbWlu
  workflowsSecretKey: Znh2NTk2WE1uR2lLNkxlSw==
type: Opaque
```

## Your Environment

* Version used: RELEASE.2022-08-02T23-59-16Z
* Helm chart verssion: 4.0.10
