### ISSUE TITLE
FS Legacy Mode: `500 Internal Server Error`: s3aws: InternalError: We encountered an internal error, please try again.:`

### ISSUE THREAD

**Issue by qcasey** [minio/minio#15494]
## Expected Behavior

I'm using self-hosted Gitlab CI which pushes container images to its own registry using minio for storage. Since I updated to `minio/mino:latest` (`RELEASE.2022-08-05T23-27-09Z`), I cannot push containers from any CI jobs.

## Current Behavior

Gitlab shows a `received unexpected HTTP status: 500 Internal Server Error` in the CI logs, but in Loki I get a more helpful response:

```
"s3aws: InternalError: We encountered an internal error, please try again.: cause(readObjectStart: expect { or n, but found �, error found in #0 byte of ...\|\|..., bigger context ...\|\|...)\n\tstatus code: 500, request id: 170963FAA7B45E1F, host id: "
```

`mc admin trace` shows a bunch of these

```
2022-08-08T07:11:04.745 [500 Internal Server Error] s3.ListObjectParts 192.168.200.1:9000/gitlab-registry/docker/registry/v2/repositories/qcasey/uspsboxer-web/_uploads/41370bd1-d517-4228-86f6-c642406fc7c3/data?uploadId=bf948b2d-8041-4825-aaf4-301160691c53  192.168.200.8     527µs       ↑ 93 B ↓ 987 B
2022-08-08T07:11:04.784 [500 Internal Server Error] s3.ListObjectParts 192.168.200.1:9000/gitlab-registry/docker/registry/v2/repositories/qcasey/uspsboxer-web/_uploads/41370bd1-d517-4228-86f6-c642406fc7c3/data?uploadId=bf948b2d-8041-4825-aaf4-301160691c53  192.168.200.8     522µs       ↑ 93 B ↓ 987 B
```

## Possible Solution

Downgrade to `RELEASE.2022-08-02T23-59-16Z` and everything works again.

## Steps to Reproduce (for bugs)

1. Upgrade from [RELEASE.2022-08-02T23-59-16Z](https://hub.docker.com/layers/minio/minio/minio/RELEASE.2022-08-02T23-59-16Z/images/sha256-cd5f4c9bb64da18e0ddeb768f67bed1c2f98f547303229ffd1a4dbf154c1a6dc?context=explore) to [RELEASE.2022-08-05T23-27-09Z](https://hub.docker.com/layers/minio/minio/minio/RELEASE.2022-08-05T23-27-09Z/images/sha256-92e73a9ad481db7d5b78c5ae197a8c16e0e28924167bea57beb46dcaad09529b?context=explore)
2. Try pushing a container to self-hosted Gitlab Registry backed by minio
3. Note 500 error, container images cannot be pushed

Although CI is the main problem, manually pushing docker's `library/hello-world` from my laptop to a dummy project gives the same error, making me think it's not a size issue:

```bash
$ docker tag hello-world registry.quinncasey.com/qcasey/hello-world:hello-world
$ docker push registry.quinncasey.com/qcasey/hello-world:hello-world
The push refers to repository [registry.quinncasey.com/qcasey/hello-world]
e07ee1baac5f: Pushing [==================================================>]  14.85kB
received unexpected HTTP status: 500 Internal Server Error
```

## Regression

I believe so, yes. Downgrading to last release `RELEASE.2022-08-02T23-59-16Z` makes the problem go away

## Your Environment

* Version used (`minio --version`): `RELEASE.2022-08-05T23-27-09Z`
* Server setup and configuration: Minio in Docker behind Caddy reverse proxy
* Operating System and version (`uname -a`): Debian Host

**Comment by harshavardhana** [comment]
@qcasey what is your backend disk this looks like something is not readable from the disk are you using some network storage for backend disks? 

Also please share the server log from the deployment.

**Comment by harshavardhana** [comment]
A JSON is failing to read

> cause(readObjectStart: expect { or n, but found �, error found in #0 byte of

**Comment by harshavardhana** [comment]
Also please capture `mc support inspect alias/.minio.sys/**` and share it here..

**Comment by qcasey** [comment]
Thanks for the quick response! The backend disk is a ZFS pool on Proxmox, not NFS since it's running directly on the host.

This is my `docker-compose.yml`:

```
  minio:
    image: minio/minio:RELEASE.2022-08-02T23-59-16Z
    #image: sha256:a7e6db90957108eeda01bf9e0babffe3d893286ef1f681d6db721859f583bb18
    ports:
        - 9000:9000
        - 9001:9001
    environment:
        - "MINIO_ROOT_USER=XXXX"
        - "MINIO_ROOT_PASSWORD=XXXX"
        - "MINIO_PROMETHEUS_URL=http://192.168.1.72:9090"
    command: server --console-address ":9001" /data
    volumes:
        - /diablo/minio:/data
    restart: unless-stopped
```

I'll try the `mc support` in a minute, it's complaining about my fish shell

**Comment by qcasey** [comment]
Sorry those logs were wrong, here is what I see with the 500:

```bash
minio_1             | API: ListObjectParts(bucket=gitlab-registry, object=docker/registry/v2/repositories/qcasey/photopanda-web/_uploads/a6063d25-5958-4f69-9356-54fff1194363/data)
minio_1             | Time: 14:59:02 UTC 08/08/2022
minio_1             | DeploymentID: 9afa5a7a-f5d2-440e-8f78-538ae3687896
minio_1             | RequestID: 170966987AFD3D22
minio_1             | RemoteHost: 192.168.200.8
minio_1             | Host: 192.168.200.1:9000
minio_1             | UserAgent: docker-distribution/v3.51.1-gitlab (go1.17.6) aws-sdk-go/1.44.49 (go1.17.6; linux; amd64)
minio_1             | Error: readObjectStart: expect { or n, but found , error found in #0 byte of ...||..., bigger context ...||... (*errors.errorString)
minio_1             |        5: internal/logger/logger.go:259:logger.LogIf()
minio_1             |        4: cmd/api-errors.go:2135:cmd.toAPIErrorCode()
minio_1             |        3: cmd/api-errors.go:2160:cmd.toAPIError()
minio_1             |        2: cmd/object-multipart-handlers.go:803:cmd.objectAPIHandlers.ListObjectPartsHandler()
minio_1             |        1: net/http/server.go:2084:http.HandlerFunc.ServeHTTP()
minio_1             | 
```

**Comment by qcasey** [comment]
Similarly, `./mc support inspect johanna/.minio.sys/**` gives me 

```
mc: <ERROR> Unable to inspect file. Failed to parse server response (unexpected end of JSON input):.
```

**Comment by harshavardhana** [comment]
> Similarly, `./mc support inspect johanna/.minio.sys/**` gives me
> 
> ```
> mc: <ERROR> Unable to inspect file. Failed to parse server response (unexpected end of JSON input):.
> ```

Was this existing data? Can you `cat /data/.minio.sys/format.json` ?

**Comment by qcasey** [comment]
Yes, the minio server has been running over a year

```bash
$ dc exec minio cat /data/.minio.sys/format.json
{"version":"1","format":"fs","id":"9afa5a7a-f5d2-440e-8f78-538ae3687896","fs":{"version":"2"}}
```

**Comment by harshavardhana** [comment]
Ah yes this a change here 

```
diff --git a/cmd/fs-v1-multipart.go b/cmd/fs-v1-multipart.go
index ed1c022a3..0e836892e 100644
--- a/cmd/fs-v1-multipart.go
+++ b/cmd/fs-v1-multipart.go
@@ -517,7 +517,7 @@ func (fs *FSObjects) ListObjectParts(ctx context.Context, bucket, object, upload
                }
        }
 
-       rc, _, err := fsOpenFile(ctx, pathJoin(uploadIDDir, fs.metaJSONFile), 0)
+       rc, _, err := fsOpenFile(ctx, pathJoin(uploadIDDir, fs.metaJSONFile), 0o666)
        if err != nil {
                if err == errFileNotFound || err == errFileAccessDenied {
```

The stream that is obtained from here is resulting in this error however entirely not sure why this would happen.

**Comment by harshavardhana** [comment]
@qcasey please download https://play.min.io/testbucket/minio.gz and update the binary inside the container and let me know how it goes. 

Once the binary is updated you would have to create a new container using `dc commit` etc.

**Comment by qcasey** [comment]
```yaml
  minio:
    image: minio/minio:latest
    #image: sha256:a7e6db90957108eeda01bf9e0babffe3d893286ef1f681d6db721859f583bb18
    ports:
        - 9000:9000
        - 9001:9001
    environment:
        - "MINIO_ROOT_USER=XXXX"
        - "MINIO_ROOT_PASSWORD=XXXX"
        - "MINIO_PROMETHEUS_URL=http://192.168.1.72:9090"
    command: server --console-address ":9001" /data
    volumes:
        - /diablo/minio:/data
        - ./minio:/opt/bin/minio
    restart: unless-stopped
```

That works!

`a52957cbcaec: Pushed`

Although `support inspect johanna/.minio.sys/**` still returns `unexpected end of JSON input`. I switched further back to an image from 6 weeks ago and got the same error, so I think that may be a config issue on my end.
