### ISSUE TITLE
Minio create too many files in  `tmp/.trash` , more than 100M files. 

### ISSUE THREAD

**Issue by maslow** [minio/minio#15530]
## NOTE
<img width="506" alt="image" src="https://user-images.githubusercontent.com/7122237/184477165-3bb86176-8715-47fb-ba82-eb895adeb5af.png">

Minio create too many files in  `tmp/.trash` , more than 10M files. 

I delete these files cost several hours and it growing fastly.

## Context
We have 4 minio nodes(4 volume per node) deployed in 1 server. 

## Your Environment
* Version used (`minio --version`): v2022.4.12
* Server setup and configuration: 
```yml
version: '3.8'
services:
  oss0:
    hostname: 'oss0'
    image: 'bitnami/minio:2022.4.12'
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=oss{0...3}/data/{0...3}
      - MINIO_ETCD_ENDPOINTS=http://etcd:2379
      - MINIO_SKIP_CLIENT=yes
      - MINIO_REGION_NAME=cn-default
      - MINIO_DOMAIN=${MINIO_DOMAIN}
    ports:
      - "9000:9000"
      - "9100:9001"
    volumes:
      - /mnt/oss-0:/data
    networks:
      - oss_shared_network

  oss1:
    hostname: 'oss1'
    image: 'bitnami/minio:2022.4.12'
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=oss{0...3}/data/{0...3}
      - MINIO_ETCD_ENDPOINTS=http://etcd:2379
      - MINIO_SKIP_CLIENT=yes
      - MINIO_REGION_NAME=cn-default
      - MINIO_DOMAIN=${MINIO_DOMAIN}
    ports:
      - "9001:9000"
      - "9101:9001"
    volumes:
      - /mnt/oss-1:/data
    networks:
      - oss_shared_network

  oss2:
    hostname: 'oss2'
    image: 'bitnami/minio:2022.4.12'
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=oss{0...3}/data/{0...3}
      - MINIO_ETCD_ENDPOINTS=http://etcd:2379
      - MINIO_SKIP_CLIENT=yes
      - MINIO_REGION_NAME=cn-default
      - MINIO_DOMAIN=${MINIO_DOMAIN}
    ports:
      - "9002:9000"
      - "9102:9001"
    volumes:
      - /mnt/oss-2:/data
    networks:
      - oss_shared_network

  oss3:
    hostname: 'oss3'
    image: 'bitnami/minio:2022.4.12'
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=oss{0...3}/data/{0...3}
      - MINIO_ETCD_ENDPOINTS=http://etcd:2379
      - MINIO_SKIP_CLIENT=yes
      - MINIO_REGION_NAME=cn-default
      - MINIO_DOMAIN=${MINIO_DOMAIN}
    ports:
      - "9003:9000"
      - "9103:9001"
    volumes:
      - /mnt/oss-3:/data
    networks:
      - oss_shared_network

  etcd:
    hostname: 'etcd'
    image: 'bitnami/etcd:3.5.4'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    volumes:
      - /mnt/oss-etcd:/bitnami/etcd/data
    # ports:
    #   - 2379
    #   - 2380
    networks:
      - oss_shared_network

networks:
  oss_shared_network:
    external: true
```

* Operating System and version (`uname -a`): Linux iZ8vbgalm1f4e9ffn55w74Z 5.10.60-9.al8.x86_64 #1 SMP Mon Sep 6 21:30:37 CST 2021 x86_64 x86_64 x86_64 GNU/Linux
