### ISSUE TITLE
Compression configuration does not work

### ISSUE THREAD

**Issue by ArcherTrister** [minio/minio#15536]
I use the docker compose deployment provided in the document. When I configure the compressed environment variables according to the document, the operation succeeds but the compression configuration does not work.

```yaml
version: '3.7'

# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: quay.io/minio/minio:latest
  command: server --console-address ":9001" http://minio{1...4}/data{1...2}
  restart: always
  expose:
    - "9000"
    - "9001"
  environment:
    TZ: Asia/Shanghai
    MINIO_ROOT_USER: admin
    MINIO_ROOT_PASSWORD: xxxxxxxxx
    MINIO_COMPRESSION_ENABLE: "on"
    MINIO_COMPRESS_EXTENSIONS: ".pdf,.doc,.png,.bmp,.jpg,.jpeg,.gif,.mp4"
    MINIO_COMPRESS_MIME_TYPES: "application/pdf,application/ogg,image/gif,image/png,image/jpeg,image/bmp,image/webp"
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3

# starts 4 docker containers running minio server instances.
# using nginx reverse proxy, load balancing, you can access
# it through port 9000.
services:
  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - data1-1:/data1
      - data1-2:/data2

  minio2:
    <<: *minio-common
    hostname: minio2
    volumes:
      - data2-1:/data1
      - data2-2:/data2

  minio3:
    <<: *minio-common
    hostname: minio3
    volumes:
      - data3-1:/data1
      - data3-2:/data2

  minio4:
    <<: *minio-common
    hostname: minio4
    volumes:
      - data4-1:/data1
      - data4-2:/data2

  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  data1-1:
  data1-2:
  data2-1:
  data2-2:
  data3-1:
  data3-2:
  data4-1:
  data4-2:
```

![image](https://user-images.githubusercontent.com/35516482/184573889-d0f0c218-c2f4-45cc-b7ea-dc91b5ebfb42.png)

I also try to use the configuration [`MINIO_COMPRESSION: "on"`], but the problem remains. Could you help me?
