### ISSUE TITLE
Site replication got error: Bucket target creation error: Remote service endpoint or target bucket not available:

### ISSUE THREAD

**Issue by maslow** [minio/minio#15537]
## NOTE
I have tow minio cluster want to try `Site replication`:

- mc alias `self` as the source cluster which had buckets & users
- mc alias `remote` as the target cluster which is empty

set alias commands(the connect is ok each other): 
```bash
$ mc alias set self http://oss:9000 minio-root-user minio-root-password
Added `self` successfully.

$ mc alias set remote http://minio1:9000 minio-root-user minio-root-password
Added `remote` successfully.
```

## Current Behavior

Add replicate and got error & success message:

```bash
$ mc admin replicate add self remote
Requested sites were configured for replication successfully.
Site replication error(s): 
'ConfigureReplication' on site self (8e166409-483f-46a3-abb3-fd4c0450e153): failed(self: ConfigureReplication: Site replication error(s): 
'ConfigureReplication' on site remote (eddbc9f5-b476-4dfb-aea0-10f148b80fdb): failed(self->remote: Bucket target creation error: Remote service endpoint or target bucket not available: 000000-test 
        The specified bucket does not exist))
'ConfigureReplication' on site remote (eddbc9f5-b476-4dfb-aea0-10f148b80fdb): succeeded

```

**The users has been replicated to target cluster, but buckets & objects not.**

Logs of `self` (alias for the source cluster which had data )
```bash
oss_1                     | API: SYSTEM()
oss_1                     | Time: 05:04:58 UTC 08/15/2022
oss_1                     | DeploymentID: 8e166409-483f-46a3-abb3-fd4c0450e153
oss_1                     | Error: self: ConfigureReplication: Site replication error(s): 
oss_1                     | 'ConfigureReplication' on site remote (eddbc9f5-b476-4dfb-aea0-10f148b80fdb): failed(self->remote: Bucket target creation error: Remote service endpoint or target bucket not available: 000000-test 
oss_1                     |     The specified bucket does not exist) (*fmt.wrapError)
oss_1                     |        4: internal/logger/logger.go:259:logger.LogIf()
oss_1                     |        3: cmd/site-replication.go:4282:cmd.(*SiteReplicationSys).healBucketReplicationConfig()
oss_1                     |        2: cmd/site-replication.go:3624:cmd.(*SiteReplicationSys).healBuckets()
oss_1                     |        1: cmd/site-replication.go:3520:cmd.(*SiteReplicationSys).startHealRoutine()
oss_1                     | 
oss_1                     | API: SYSTEM()
oss_1                     | Time: 05:04:58 UTC 08/15/2022
oss_1                     | DeploymentID: 8e166409-483f-46a3-abb3-fd4c0450e153
oss_1                     | Error: self: ConfigureReplication: Site replication error(s): 
oss_1                     | 'ConfigureReplication' on site remote (eddbc9f5-b476-4dfb-aea0-10f148b80fdb): failed(self->remote: Bucket target creation error: Remote service endpoint or target bucket not available: 000000-test2 
oss_1                     |     The specified bucket does not exist) (*fmt.wrapError)
oss_1                     |        4: internal/logger/logger.go:259:logger.LogIf()
oss_1                     |        3: cmd/site-replication.go:4282:cmd.(*SiteReplicationSys).healBucketReplicationConfig()
oss_1                     |        2: cmd/site-replication.go:3624:cmd.(*SiteReplicationSys).healBuckets()
oss_1                     |        1: cmd/site-replication.go:3520:cmd.(*SiteReplicationSys).startHealRoutine()
```

Logs for `remote` (alias for the target cluster which is empty)

```bash
minio2_1   | Status:         4 Online, 0 Offline. 
minio2_1   | API: http://localhost:9000 
minio2_1   | Console: http://172.18.0.16:9001 http://127.0.0.1:9001 
minio2_1   | 
minio2_1   | Documentation: https://docs.min.io
minio4_1   | Cluster replication initialized
minio3_1   | Cluster replication initialized
minio2_1   | Cluster replication initialized
```

## Your Environment

* Version used (`minio --version`):  minio version DEVELOPMENT.2022-08-11T04-37-28Z (commit-id=d265fe7f9ed5ffa1679bcce9e20481a8d9eec73a) 【both source cluster & target cluster are same】
* Server setup and configuration: 
* Operating System and version (`uname -a`): Linux c5d0db77c76f 5.10.104-linuxkit #1 SMP PREEMPT Thu Mar 17 17:05:54 UTC 2022 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
> ```shell
> $ mc alias set self http://oss:9000 minio-root-user minio-root-password
> Added `self` successfully.
> 
> $ mc alias set remote http://minio1:9000 minio-root-user minio-root-password
> Added `remote` successfully.
> ```

You cannot attach two existing deployments @maslow only a single site can have data and your second site must be empty. 

> * Version used (`minio --version`):  minio version DEVELOPMENT.2022-08-11T04-37-28Z (commit-id=d265fe7f9ed5ffa1679bcce9e20481a8d9eec73a) 【both source cluster & target cluster are same】

Also, please use released binaries, do not build your own. 

> * mc alias `remote` as the target cluster which is empty

This doesn't look it is true.

**Comment by maslow** [comment]
Respect for your prompt reply,

I think the target cluster is empty, Is there any basis for judgment if a cluster is empty or not.

After create the cluster, I haven't doing any opreation. And the volume is initial empty also. 

This is the compose yml file for `remote`(Target cluster) :

```yml
version: '3.8'
services:
  minio1:
    hostname: 'minio1'
    image: 'bitnami/minio:2022.8.11'
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=minio1,minio2,minio3,minio4
      - MINIO_ETCD_ENDPOINTS=http://rs-etcd:2379
      - MINIO_SKIP_CLIENT=yes
      - MINIO_REGION_NAME=cn-default
      - MINIO_DOMAIN=${MINIO_DOMAIN}
    ports:
      - '9001:9000'
      - '9101:9001'
    volumes:
      - oss-data-1:/data
    networks:
      - laf_shared_network

  minio2:
    hostname: 'minio2'
    image: 'bitnami/minio:2022.8.11'
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=minio1,minio2,minio3,minio4
      - MINIO_ETCD_ENDPOINTS=http://rs-etcd:2379
      - MINIO_SKIP_CLIENT=yes
      - MINIO_REGION_NAME=cn-default
      - MINIO_DOMAIN=${MINIO_DOMAIN}
    ports:
      - '9002:9000'
      - '9102:9001'
    volumes:
      - oss-data-2:/data
    networks:
      - laf_shared_network

  minio3:
    hostname: 'minio3'
    image: 'bitnami/minio:2022.8.11'
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=minio1,minio2,minio3,minio4
      - MINIO_ETCD_ENDPOINTS=http://rs-etcd:2379
      - MINIO_SKIP_CLIENT=yes
      - MINIO_REGION_NAME=cn-default
      - MINIO_DOMAIN=${MINIO_DOMAIN}
    ports:
      - '9003:9000'
      - '9103:9001'
    volumes:
      - oss-data-3:/data
    networks:
      - laf_shared_network

  minio4:
    hostname: 'minio4'
    image: 'bitnami/minio:2022.8.11'
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=minio1,minio2,minio3,minio4
      - MINIO_ETCD_ENDPOINTS=http://rs-etcd:2379
      - MINIO_SKIP_CLIENT=yes
      - MINIO_REGION_NAME=cn-default
      - MINIO_DOMAIN=${MINIO_DOMAIN}
    ports:
      - '9004:9000'
      - '9104:9001'
    volumes:
      - oss-data-4:/data
    networks:
      - laf_shared_network

  rs-etcd:
    image: quay.io/coreos/etcd:v3.5.4
    environment:
      - ETCD_ADVERTISE_CLIENT_URLS=http://rs-etcd:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
    volumes:
      - etcd-data:/default.etcd
    ports:
      - 2379
      - 2380
    networks:
      - laf_shared_network

networks:
  laf_shared_network:
    external: true

volumes:
  oss-data-1:
  oss-data-2:
  oss-data-3:
  oss-data-4:
  etcd-data:
  
```

**Comment by maslow** [comment]
Or can you give me some possible directions to do some experiments. 

I have tested these both two cluster in Docker Desktop and also in Centos 7.9, got the same result( list in `Current Behavior`).

**Comment by maslow** [comment]
I've just try to reset the source cluster: 

Clean the container & volumes then up. 

And run add replicate operation again, got the same error. Can these ensure a empty cluster?

```bash
fugen@FG-MacBook-Pro-14 minio-replica % docker-compose down -v
Removing minio-replica_minio4_1  ... done
Removing minio-replica_minio2_1  ... done
Removing minio-replica_minio3_1  ... done
Removing minio-replica_rs-etcd_1 ... done
Removing minio-replica_minio1_1  ... done
Network laf_shared_network is external, skipping
Removing volume minio-replica_oss-data-1
Removing volume minio-replica_oss-data-2
Removing volume minio-replica_oss-data-3
Removing volume minio-replica_oss-data-4
Removing volume minio-replica_etcd-data


fugen@FG-MacBook-Pro-14 minio-replica % docker-compose up
Creating volume "minio-replica_oss-data-1" with default driver
Creating volume "minio-replica_oss-data-2" with default driver
Creating volume "minio-replica_oss-data-3" with default driver
Creating volume "minio-replica_oss-data-4" with default driver
Creating volume "minio-replica_etcd-data" with default driver
Creating minio-replica_minio2_1  ... done
Creating minio-replica_minio1_1  ... done
Creating minio-replica_minio3_1  ... done
Creating minio-replica_minio4_1  ... done
Creating minio-replica_rs-etcd_1 ... done
Attaching to minio-replica_minio1_1, minio-replica_minio2_1, minio-replica_minio4_1, minio-replica_rs-etcd_1, minio-replica_minio3_1
minio1_1   |  05:40:21.03 
minio1_1   |  05:40:21.06 Welcome to the Bitnami minio container
minio1_1   |  05:40:21.09 Subscribe to project updates by watching https://github.com/bitnami/containers
minio2_1   |  05:40:21.03 
minio1_1   |  05:40:21.11 Submit issues and feature requests at https://github.com/bitnami/containers/issues
minio1_1   |  05:40:21.14 
...
...
```

**Comment by maslow** [comment]
And just buckets cannot sync, the others replica-data synced successfully(users, policies):

<img width="606" alt="image" src="https://user-images.githubusercontent.com/7122237/184584279-cf00f5d5-4c51-4e8d-be80-1125b2afc8ed.png">

And, in the target cluster /data directory, I've found the buckets directory created but empty.
![image](https://user-images.githubusercontent.com/7122237/184584727-90e3ab8f-b80e-4293-8bc6-fd7e9e2414d9.png)


@harshavardhana anything else I can do or supply

**Comment by maslow** [comment]
> > * Version used (`minio --version`):  minio version DEVELOPMENT.2022-08-11T04-37-28Z (commit-id=d265fe7f9ed5ffa1679bcce9e20481a8d9eec73a) 【both source cluster & target cluster are same】
> 
> Also, please use released binaries, do not build your own.


OK, I replace the bitnami image with minio official image `minio/minio:RELEASE.2022-08-13T21-54-44Z`, 
same results as lists in `Current Behavior`. 
The new target cluster deployment yaml (docker-compose down -v && docker-compose up):

```yml
version: '3.8'
services:
  minio1:
    hostname: 'minio1'
    image: 'minio/minio:RELEASE.2022-08-13T21-54-44Z'
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_VOLUMES=${MINIO_VOLUMES}
      - MINIO_ETCD_ENDPOINTS=${MINIO_ETCD_ENDPOINTS}
      - MINIO_SKIP_CLIENT=yes
      - MINIO_REGION_NAME=cn-default
      - MINIO_DOMAIN=${MINIO_DOMAIN}
    command: server /data --console-address ":9001"
    ports:
      - '9001:9000'
      - '9101:9001'
    volumes:
      - oss-data-1:/data
    networks:
      - laf_shared_network

  minio2:
    hostname: 'minio2'
    image: 'minio/minio:RELEASE.2022-08-13T21-54-44Z'
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_VOLUMES=${MINIO_VOLUMES}
      - MINIO_ETCD_ENDPOINTS=${MINIO_ETCD_ENDPOINTS}
      - MINIO_SKIP_CLIENT=yes
      - MINIO_REGION_NAME=cn-default
      - MINIO_DOMAIN=${MINIO_DOMAIN}
    command: server /data --console-address ":9001"
    ports:
      - '9002:9000'
      - '9102:9001'
    volumes:
      - oss-data-2:/data
    networks:
      - laf_shared_network

  minio3:
    hostname: 'minio3'
    image: 'minio/minio:RELEASE.2022-08-13T21-54-44Z'
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_VOLUMES=${MINIO_VOLUMES}
      - MINIO_ETCD_ENDPOINTS=${MINIO_ETCD_ENDPOINTS}
      - MINIO_SKIP_CLIENT=yes
      - MINIO_REGION_NAME=cn-default
      - MINIO_DOMAIN=${MINIO_DOMAIN}
    command: server /data --console-address ":9001"
    ports:
      - '9003:9000'
      - '9103:9001'
    volumes:
      - oss-data-3:/data
    networks:
      - laf_shared_network

  minio4:
    hostname: 'minio4'
    image: 'minio/minio:RELEASE.2022-08-13T21-54-44Z'
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_VOLUMES=${MINIO_VOLUMES}
      - MINIO_ETCD_ENDPOINTS=${MINIO_ETCD_ENDPOINTS}
      - MINIO_SKIP_CLIENT=yes
      - MINIO_REGION_NAME=cn-default
      - MINIO_DOMAIN=${MINIO_DOMAIN}
    command: server /data --console-address ":9001"
    ports:
      - '9004:9000'
      - '9104:9001'
    volumes:
      - oss-data-4:/data
    networks:
      - laf_shared_network

  rs-etcd:
    image: quay.io/coreos/etcd:v3.5.4
    environment:
      - ETCD_ADVERTISE_CLIENT_URLS=${MINIO_ETCD_ENDPOINTS}
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
    volumes:
      - etcd-data:/default.etcd
    ports:
      - 2379
      - 2380
    networks:
      - laf_shared_network

networks:
  laf_shared_network:
    external: true

volumes:
  oss-data-1:
  oss-data-2:
  oss-data-3:
  oss-data-4:
  etcd-data:

```
