### ISSUE TITLE
LDAP Password information disclosure when using minio behind a proxy

### ISSUE THREAD

**Issue by Daywalker01** [minio/minio#15598]
When using minio with LDAP authentication behind a http proxy the LDAP username and password are visible in the URL parameter

## Expected Behaviour
As this is already a HTTP POST request, all sensitive Information should be put into the request body

## Current Behaviour
Currently sensitive information is put into the URL Parameter

## Possible Solution
Putting the sensitive information into the request Body

## Steps to Reproduce (for bugs)
Our docker-compose file:
```
services:
  minio:
    container_name: ${MINIO_DNS_NAME}
    hostname: ${MINIO_DNS_NAME}
    domainname: [example.org](http://example.org/)
    image: [quay.io/minio/minio:RELEASE.2022-08-22T23-53-06Z](http://quay.io/minio/minio:RELEASE.2022-08-22T23-53-06Z)
    command: server --address ":${ADDRESS_PORT}" --console-address ":${CONSOLE_ADDRESS_PORT}" --certs-dir /certs ${HOSTNAME_DIRECTORIES}
    ports:
      - "${ADDRESS_PORT}:9000/tcp"
      - "${CONSOLE_ADDRESS_PORT}:9001/tcp"
    environment:
    MINIO_ROOT_USER: ${MINIO_ROOT_USER}
    MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    MINIO_SERVER_URL: https://s3.example.org/
    MINIO_BROWSER_REDIRECT_URL: https://s3-console.example.org/
    volumes:
      - ./data1-1:/data1
      - ./ssl:/certs
```
* Putting minio behind a http loadbalancer _(haproxy in our case)_
* Configuring LDAP authentication

### Details
minio is behind a haproxy cluster and has two DNS aliases (one for the API and one for the web console)

haproxy is producing the following logs upon login on the web console:
```
Aug 25 14:18:10 [haproxy.example.org](http://haproxy.example.org/) haproxy[1053730]: 10.17.131.112:50570 [25/Aug/2022:14:18:10.711] http-in~ be_s3_minio_api/minio12 0/0/1/10/11 400 672 - - ---- 431/404/0/0/0 0/0 {[s3.example.org](http://s3.example.org/)} "POST /?Action=AssumeRoleWithLDAPIdentity&LDAPPassword=AAAAAAAAAAAAAAAAAAAAAAAAA&LDAPUsername=USERNAME&Version=2011-06-15 HTTP/1.1"
```
_(hostnames, usernames and password are redacted of course)_

## Context
Sensitive information should never be transferred as a URL Parameter and always be part of the request body.
In case of a proxy server, anybody having access to the proxy's log files can just write down the sensitive information.
Logging of the URL parameter is default in haproxy (we just added the Host header in curly braces)

## Regression
security wise, yes I guess?

## Your Environment
haproxy 2.0 LTS on Ubuntu 20.04 LTS
