### ISSUE TITLE
Drive `/disk1/minio` is part of root drive, will not be used 

### ISSUE THREAD

**Issue by lazywhite** [minio/minio#15720]
I'm trying to deploy a minio distributed cluster inside k3s,  I used 3 replicas statefulset, each pod mount a local-path pvc , then minio refuse to start because it think /disk1 mount point is part of root drive.  Also I used hostpath volume, still the same problem
Is there any way to make it work? 

## Your Environment
minio image: minio/minio:RELEASE.2022-09-01T23-53-36Z
k3s:  v1.24.4+k3s1 (c3f830e9)

statefulset: 
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: {{ .Release.Namespace }}
  labels:
    app: minio
spec:
  serviceName: minio-headless
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: main 
        image: {{ .Values.image.registry -}}/{{- .Values.image.repository -}}: {{- .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - sh
        - -euc
        - |
          mkdir -p /disk1/minio
          minio server --console-address :9001 http://minio-{0...2}.minio-headless.{{- .Release.Namespace -}}.svc.cluster.local:9000/disk1/minio
        env:
        - name: "MINIO_ACCESS_KEY"
          value: "minio"
        - name: "MINIO_SECRET_KEY"
          value: "miniosecret"
        - name: "MINIO_PROMETHEUS_AUTH_TYPE"
          value: "public"
        - name: "MINIO_UPDATE"
          value: "off"
        ports:
        - containerPort: 9000
          protocol: TCP

        volumeMounts:
        - mountPath: /etc/localtime
          name: timezone
          readOnly: true
        - mountPath: /disk1
          name: disk1
      volumes:
      - name: timezone
        hostPath: 
          path: /etc/localtime
          type: File
  volumeClaimTemplates:
  - metadata:
      name: disk1
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local-path
      resources:
        requests:
          storage: 1Gi
```

service.yaml 
```
apiVersion: v1
kind: Service
metadata:
  name: minio-headless
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: minio
  type: ClusterIP
  clusterIP: None

```

**Comment by harshavardhana** [comment]
You cannot use root drives with MinIO if you want to use root drives set environment values such as 

- CI=true
- MINIO_CI_CD=true

**Comment by lazywhite** [comment]
```
ERROR Invalid command line arguments: lookup minio-1.minio-headless.default.svc.cluster.local on 10.43.0.10:53: no such host
      > Please provide correct combination of local/remote paths
```

after add that two env, minio server failed to start because of dns resolve error, how to solve this problem  @harshavardhana

**Comment by lazywhite** [comment]
> ```
> ERROR Invalid command line arguments: lookup minio-1.minio-headless.default.svc.cluster.local on 10.43.0.10:53: no such host
>       > Please provide correct combination of local/remote paths
> ```
> 
> after add that two env, minio server failed to start because of dns resolve error, how to solve this problem @harshavardhana

solved, just add 'sleep 30' before start minio server, so coredns will add dns entry for them

**Comment by harshavardhana** [comment]
> ERROR Invalid command line arguments: lookup minio-1.minio-headless.default.svc.cluster.local on 10.43.0.10:53: no such host
>       > Please provide correct combination of local/remote paths

yeah, this is your DNS problem your headless services are not routable. Your headless service is wrong it's not a `ClusterIP` 

```
apiVersion: v1
kind: Service
metadata:
  name: minio-headless
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: minio
  type: ClusterIP
  clusterIP: None
```

@lazywhite no - no sleep is required you are doing it wrong

```yaml
## Create headless service to StatefulSet to work.
apiVersion: v1
kind: Service
metadata:
  name: minio-dist-erasure-headless-test
  labels:
    app: minio-dist-erasure-headless-test
spec:
  ports:
  - port: 9000
  clusterIP: None
  selector:
    app: minio-dist-erasure-app-test
---
## Run minio dist erasure StatefulSet.
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio-dist-erasure-test
spec:
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: "Parallel"
  serviceName: "minio-dist-erasure-headless-test"
  replicas: 4
  selector:
    matchLabels:
      app: minio-dist-erasure-app-test
  template:
    metadata:
      labels:
        app: minio-dist-erasure-app-test
    spec:
      containers:
      - name: minio-dist-erasure-test
        env:
        - name: MINIO_ROOT_USER
          value: "minio"
        - name: MINIO_ROOT_PASSWORD
          value: "minio123"
        image: minio/minio:RELEASE.2022-09-17T00-09-45Z
        imagePullPolicy: IfNotPresent
        args:
        - server
        - http://minio-dist-erasure-test-{0...3}.minio-dist-erasure-headless-test.default.svc.cluster.local/data/dist
        ports:
        - containerPort: 9000
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
            ephemeral-storage: 1024Mi
```
