### ISSUE TITLE
Copying files via MinIO client times out randomly

### ISSUE THREAD

**Issue by alfonsrv** [minio/minio#15754]
## NOTE

Copying files manually via `mc` times out without any apparent cause. Copying via applications like Veeam works as expected and when running something like iperf from within the container, it doesn't interrupt either.

I already tried slimming it down to multiple 100GB files, but the error occurs after ~200MB already. I would expect `mc` to auto-retry the transfer after it failed. Using `mc` on Windows; no Firewall in-between, but connected directly.

Command used: `mc cp --recursive "X:\B2C-202209" hypers3/hyperv2/manual/kkh --retention-duration "400d" --retention-mode GOVERNANCE`

## Logs

<details>
  <summary>Server Log</summary>
  
```
s3hyper  | API: PutObjectPart(bucket=hyperv2, object=manual/kkh/B2C-202209/B2C-202209.7z.004)
s3hyper  | Time: 17:15:26 UTC 09/24/2022
s3hyper  | DeploymentID: 634495c9-2c8c-444a-84b0-51451f794597
s3hyper  | RequestID: 1717DB2D554B75F3
s3hyper  | RemoteHost: 10.115.5.1
s3hyper  | Host: hyper.s3.domain.tld:9000
s3hyper  | UserAgent: MinIO (windows; amd64) minio-go/v7.0.34 mc/RELEASE.2022-08-28T20-08-11Z
s3hyper  | Error: read tcp 172.31.0.2:9000->10.115.5.1:64024: read: connection timed out (*net.OpError)
s3hyper  |        5: internal/logger/logger.go:278:logger.LogIf()
s3hyper  |        4: cmd/erasure-encode.go:87:cmd.(*Erasure).Encode()
s3hyper  |        3: cmd/erasure-single-drive.go:2296:cmd.(*erasureSingle).PutObjectPart()
s3hyper  |        2: cmd/object-handlers.go:2914:cmd.objectAPIHandlers.PutObjectPartHandler()
s3hyper  |        1: net/http/server.go:2084:http.HandlerFunc.ServeHTTP()
```
</details>

<details>
  <summary>Client Log</summary>
  
```
mc: <ERROR> Failed to copy `X:\B2C-202209\B2C-202209.7z.012`. Put "https://hyper.s3.domain.tld:9000/hyperv2/manual/kkh/B2C-202209/B2C-202209.7z.012?partNumber=36&uploadId=a3dbf0db-de24-4533-a78e-33c8861d6802": read tcp 10.115.5.1:64042->10.115.5.15:9000: wsarecv: Connection was closed by the remote host.
```
</details>

## Environment

Using a Docker container with the following `compose` setup

```yml
version: '3.7'

services:
  minio:
    image: quay.io/minio/minio:RELEASE.2022-07-04T21-02-54Z
    container_name: s3hyper
    restart: unless-stopped
    command: server /data --console-address ":9002"
    env_file: .env
    ports:
      - "9000:9000"
      - "9002:9002"
    volumes:
      - data:/data
      - config:/root/.minio
    extra_hosts:
      - "hyper.s3.domain.tld:127.0.0.1"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STORAGE_PATH}/data
  config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STORAGE_PATH}/config
```

<details>
  <summary>mc client version info</summary>
  
```
mc version RELEASE.2022-08-28T20-08-11Z (commit-id=a64491e101feeaf68735a20c204d06993ba531e5)
Runtime: go1.18.5 windows/amd64
Copyright (c) 2015-2022 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
```
</details>
