### ISSUE TITLE
Helm chart - purge is a required parameter when specifying versioning

### ISSUE THREAD

**Issue by mdragilev** [minio/minio#15901]
## NOTE
The helm chart accepts buckets values to set up the initial set of buckets.  One of the parameters is versioning (enable / disable for a bucket).  However, the helm chart helper method is called as `createBucket {{ .name }} {{ .policy }} {{ .purge }} {{ .versioning }}` using positional parameters.. If purge is not provided, then versioning value will become the 3rd positional parameter.  Which both sets the wrong value for purge and versioning.

- [function call](https://github.com/minio/minio/blob/master/helm/minio/templates/_helper_create_bucket.txt#L121)
- [function](https://github.com/minio/minio/blob/master/helm/minio/templates/_helper_create_bucket.txt#L48)

## Expected Behavior
Specifying the following values should enable versioning

```
  buckets:
    - name: some-bucket
      policy: download
      versioning: true
```

## Current Behavior
However, the example above enables purge and disables versioning due to the behavior described above.

The example below works, but that required digging into the helm chart itself and there is no other feedback when `purge` setting is missing.

```
  buckets:
    - name: some-bucket
      policy: download
      purge: false 
      versioning: true
```

## Possible Solution
Provide defaults for the call into createBucket at the call site or use named parameters instead of positional ones.

## Your Environment
```
minio version RELEASE.2022-09-17T00-09-45Z (commit-id=d89f6af6c4ab280140627974252077fba47bbb79)
Runtime: go1.18.6 linux/amd64
Linux minio-6b4f4f57cf-24d5r 5.4.0-1085-aws #92~18.04.1-Ubuntu SMP Wed Aug 31 17:21:08 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
