### ISSUE TITLE
MinIO Helm Chart v5.0.0 cannot be downloaded (Error 404)

### ISSUE THREAD

**Issue by R-Studio** [minio/minio#15940]
## Expected Behavior
You can download/use the new v5.0.0 MinIO Helm Chart from repo `https://charts.min.io/`.

## Current Behavior
The Helm Chart cannot be found. Following error occurs if try to download (install/template) the Helm Chart:
`Error: failed to fetch https://charts.min.io/helm-releases/minio-5.0.0.tgz : 404 Not Found`

## Steps to Reproduce (for bugs)
1. Add the Helm repo: `helm repo add minio https://charts.min.io/`
2. Try to install or run ` template`: `helm template minio/minio`
3. Error occurs: `Error: failed to fetch https://charts.min.io/helm-releases/minio-5.0.0.tgz : 404 Not Found`

**Comment by harshavardhana** [comment]
its not released yet, how are you able to get it? the index only has

```
apiVersion: v1
entries:
  minio:
  - apiVersion: v1
    appVersion: RELEASE.2022-10-24T18-35-07Z
    created: "2022-10-24T13:36:32.958627308-07:00"
    description: Multi-Cloud Object Storage
    digest: 2d3d884490ea1127742f938bc9382844bae713caae08b3308f766f3c9000659a
    home: https://min.io
    icon: https://min.io/resources/img/logo/MINIO_wordmark.png
    keywords:
    - minio
    - storage
    - object-storage
    - s3
    - cluster
    maintainers:
    - email: dev@minio.io
      name: MinIO, Inc
    name: minio
    sources:
    - https://github.com/minio/minio
    urls:
    - https://charts.min.io/helm-releases/minio-4.1.0.tgz
    version: 4.1.0
```
