### ISSUE TITLE
Unable to initialize config system: migrateConfigToMinioSys: Storage resources are insufficient for the write operation

### ISSUE THREAD

**Issue by Ploppz** [minio/minio#15991]
I have a problem running minio in docker. I get this error:

```
API: SYSTEM()
Time: 14:12:22 UTC 11/01/2022
DeploymentID: aff881b0-558d-40cb-a27f-5b99011c7d92
Error: write /home/user/s3/.minio.sys/tmp/95cf644e-ca26-4dad-b095-46516525209d/xl.meta: invalid argument (*fs.PathError)
       6: internal/logger/logger.go:258:logger.LogIf()
       5: cmd/storage-errors.go:168:cmd.osErrToFileErr()
       4: cmd/xl-storage.go:2395:cmd.(*xlStorage).RenameData()
       3: cmd/xl-storage-disk-id-check.go:373:cmd.(*xlStorageDiskIDCheck).RenameData()
       2: cmd/erasure-object.go:761:cmd.renameData.func1()
       1: internal/sync/errgroup/errgroup.go:123:errgroup.(*Group).Go.func1()
Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to initialize config system: migrateConfigToMinioSys: Storage resources are insufficient for the write operation .minio.sys/config/config.json)
```

I have enough storage space for sure.
This is my Dockerfile:

```Dockerfile
FROM alpine:3.16.2

RUN apk add tree
RUN apk add curl

RUN curl -o /usr/bin/minio https://dl.minio.io/server/minio/release/linux-amd64/minio
RUN chmod +x /usr/bin/minio

RUN adduser -D -s /bin/bash user
# RUN passwd -d user
# RUN echo "user   ALL=(ALL) ALL" >> /etc/sudoers
USER user
WORKDIR /home/user

RUN mkdir -p /home/user/s3/test-bucket
RUN mkdir -p /home/user/s3/test-bucket2
RUN mkdir -p /home/user/s3/analysis
RUN mkdir -p /home/user/s3/external

ENV MINIO_ACCESS_KEY 123456789
ENV MINIO_SECRET_KEY 123456789

CMD minio server --address 0.0.0.0:9000 /home/user/s3
```

I run it simply with `docker run -p 9000:9000 minio`

## Your Environment

* Version used (`minio --version`):
```
$ minio --version
minio version RELEASE.2022-10-29T06-21-33Z (commit-id=d765b89a63c225ca271ef6d031a7bcc8fe9137df)
Runtime: go1.19.2 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2022 MinIO, Inc.
```
Executed inside docker container

* Operating System and version (`uname -a`):
```
$ uname -a
Linux nadir 6.0.6-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 29 Oct 2022 14:08:39 +0000 x86_64 GNU/Linux
```

**Comment by harshavardhana** [comment]
> Error: write /home/user/s3/.minio.sys/tmp/95cf644e-ca26-4dad-b095-46516525209d/xl.meta: invalid argument (*fs.PathError)

We require that your backend filesystem supports O_DIRECT - it looks like its returning error when we want to write to disk. we also need support for O_DSYNC by the backend filesystem. 

Looks like there is some bug in the OS you are using with kernel 6.x

**Comment by Ploppz** [comment]
Thanks for the swift reply.
Minio worked fine on this computer a week ago.
Trying to understand how this is possible because I have not changed my file system in any way either.
I did rebuild the image since then getting a more up-to-date minio.
Did possibly minio not require O_DIRECT up until recently?

**Comment by vadmeste** [comment]
> Did possibly minio not require O_DIRECT up until recently?

Maybe we were running MinIO with an older version which uses FS mode, but this was deprecated since some time.

Besides,  I tried with your dockerfile and it works just fine in my machine. I have some doubts that you are not really using the latest MinIO version

**Comment by LilMonk** [comment]
I'm using a docker-compose for using Minio. I'm on a linux machine.
```shell
$ uname -a
Linux pop-os 6.0.3-76060003-generic #202210211149~1666452039~22.04~1891946 SMP PREEMPT_DYNAMIC Sat O x86_64 x86_64 x86_64 GNU/Linux

```
 
For me this yaml gave me the above error:
```yaml
version: '3.7'
services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: 'minio'
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    command: server /data --console-address ":9001"
    volumes:
      - ./minio_storage1:/data
```
This error may be due to non-root user permission. I am trying to mount the volume onto the host so the docker container is complaining about this. 

So opting to docker managed volume solves this:
```yaml
version: '3.7'
services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: 'minio'
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    command: server /data --console-address ":9001"
    volumes:
      - minio_storage:/data
volumes:
  minio_storage: {}
```

I have found some resources to implement a workaround for this issue:
[Non root user write to linux](https://stackoverflow.com/questions/45518681/let-non-root-user-write-to-linux-host-in-docker)
[Tool to change the user in docker container](https://github.com/boxboat/fixuid)
[Non root issue for linux](https://devops.stackexchange.com/questions/12713/docker-mounts-files-as-uid-1001)
[How to set user and group in Docker Compose](https://blog.giovannidemizio.eu/2021/05/24/how-to-set-user-and-group-in-docker-compose/) <- I have tried this but it didn't work for me.

If any one finds any solution please do share here.
