### ISSUE TITLE
Versioning breaks after failed DeleteBucket - SNSD setup

### ISSUE THREAD

**Issue by hanssv** [minio/minio#16041]
## Expected Behavior
When deleting an existing object in a versioned (`Status=Enabled`) bucket, without specifying the versionId, I expect a delete marker to be created, and the object to no longer be visible when listing objects. If I list all object versions I expect to see both object version(s) and a delete marker.

## Current Behavior
No delete marker is created, and therefore the object is still part of object list, and in the list of all object versions there is no delete marker.

## Possible Solution
You can still remove object versions, by explicilty giving the versionId to `DeleteObject`. But versioning doesn't work as expected.

## Steps to Reproduce (for bugs)

1. `aws s3 mb s3://<bucket>`
2. `aws s3api put-bucket-versioning --bucket <bucket> --versioning-configuration Status=Enabled`
3. `aws s3 cp <file> s3://<bucket>` 
4. `aws s3 rb s3://<bucket>`
5. `aws s3 rm s3://<bucket>/<file>`
6. `aws s3 ls s3://<bucket>` - and here `<file>` is still part of the listing despite the `rm`.

Note: Steps 1-3, and 5-6 can also be performed using `mc`. Step 4 should be done using the S3 API directly (`mc` is so helpful that it checks if the bucket is empty before even trying, and thus does not trigger the problem).

## Context
We ran into this issue trying to cleanup after a test, deleting what we thought was an empty bucket, and then getting into this weird state. 

## Regression
Don't know.

## Your Environment

* Version used (`minio --version`): docker image `minio:RELEASE.2022-10-29T06-21-33Z`
* Server setup and configuration: minimal docker-compose
* Operating System and version (`uname -a`): Darwin Hans-MBPro2021 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000 arm64

**Comment by harshavardhana** [comment]
> * Server setup and configuration: minimal docker-compose

Can you provide the entire setup? - this doesn't look correct.

**Comment by hanssv** [comment]
Yes, no problem, this is the docker-compose entry for MinIO:
```  
minio-server:
    image: quay.io/minio/minio:RELEASE.2022-10-29T06-21-33Z
    environment:
      MINIO_ROOT_USER: minioadmin00
      MINIO_ROOT_PASSWORD: minioadmin00
    command:
      - server
      - /data
      - --address
      - ':9000'
      - --console-address
      - ':9090'
    ports:
      - '9000:9000'
      - '9090:9090'
```
