### ISSUE TITLE
Make Minio easier to use as an S3 stand-in for local development

### ISSUE THREAD

**Issue by cies** [minio/minio#16095]
**Is your feature request related to a problem? Please describe.**
We (like many) have a `docker-compose` managed set of backend services that all devs run locally (MySQL, Redis, ElasticMQ and some stand-in for S3). I picked Minio because it is a serious project (in Go, actively developed, also usable as an S3 replacement in prod setups, no JVM/Python/etc dependency so small container size).

I've struggled getting Minio to work for local development. I cannot get the containerized Minio (official, latest Docker hub) to accept connections from both my host machine (runs our app, connects over `http://localhost:4000`) and from the docker network (runs a dockerized versino of our app, over `http://s3:4000`). Lots of "connection refused".

I'm not sure why dockered Minio is so picky. There are quite some mentions of the "connection refused" problem in the Github issues and on Stackoverflow. Some answers propose some changes to the `/etc/hosts` file. I did not get it to work.

**Describe alternatives you've considered**
I tried `s3-ninja`, and it works out of the box. I'm really not sure what makes the difference: it's pretty much the same docker-compose stanza, but pointing to the other docker image.

**Describe the solution you'd like**
Minio be suuuuper easy to set up in a local development environment. Thereby increasing the adoption of Minio as the de facto S3 stand-in for devs (and test/CI situations).

**Additional context**
My two docker-compose stanzas (top one never worked for me, bottom one worked on first attempt):

```
  s3:
    image: minio/minio
    volumes:
      - s3_data:/data
    ports:
      - 4000
      - 4999
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio_secret # at least 8 characters or won't start
      MINIO_STORAGE_USE_HTTPS: False
      MINIO_SERVER_URL: "http://localhost:4000"
    command: server --address ":4000" --console-address ":4999" /data
```

```
  s3:
    image: scireum/s3-ninja
    volumes:
      - s3_data:/home/sirius/data
    ports:
      - "4000:9000"
 ```
