### ISSUE TITLE
Inaccessible host: 'localhost' at port '9000'

### ISSUE THREAD

**Issue by arifszn** [minio/minio#16116]
I am trying to connect a minio server with aws-sdk in my nestjs project via docker composer.

The docker composer file looks something like this:

```yml
version: '3'
services:
  minio:
    image: 'minio/minio:latest'
    ports:
      - '${FORWARD_MINIO_PORT:-9000}:9000'
      - '${FORWARD_MINIO_CONSOLE_PORT:-9090}:9090'
    environment:
      MINIO_ROOT_USER: 'root'
      MINIO_ROOT_PASSWORD: 'password'
    volumes:
      - 'minio:/data/minio'
    command: minio server /data/minio --console-address ":9090"
volumes:
  minio:
    driver: local
```

And in the code, I am defining the endpoint like this:

```ts
new S3({
  endpoint: 'http://localhost:9000',
  s3ForcePathStyle: true
})
```

but it results in the error:
```
Inaccessible host: `localhost' at port `9000'. This service may not be available in the `us-east-1' region.
```

However, if I set the endpoint like this, it works perfectly.
```ts
new S3({
  endpoint: {
    protocol: 'http:',
    host: 'localhost:9000',
    port: 9000,
    hostname: 'minio',
    href: 'http://localhost:9000/',
  },
  s3ForcePathStyle: true
})
```

But it looks very weird and I have no explanation why it is working like that but not working when I define only `endpoint: 'http://localhost:9000'`.

Please note I can access the minio dashboard at http://127.0.0.1:9090, http://localhost:9090/.
