### ISSUE TITLE
Not able to run multinode configuration with docker-compose

### ISSUE THREAD

**Issue by huvalk** [minio/minio#16141]
I am trying to run docker containers with minio on two hosts in one network. Container network type is 'bridge'. I am not using swarm or network overlay, thus i have no choice but specify minio nodes adresses matching to ip address of the host, e.g.  ```server http://172.31.0.9{0...1}/data```. But it looks like minio doesnt allow me to do this.

## Expected Behavior
Both containers successfuly starts and connects to each other

## Current Behavior
Minio doesnt start. This error appears in logs every few seconds
```
Unable to read 'format.json' from http://172.31.0.90:9002/data: Do not upgrade one server at a time - please follow the recommended guidelines mentioned here https://github.com/minio/minio#upgrading-minio for your environment

API: SYSTEM()
Time: 17:59:04 UTC 11/28/2022
Error: Read failed. Insufficient number of drives online (*errors.errorString)
       6: internal/logger/logger.go:258:logger.LogIf()
       5: cmd/prepare-storage.go:251:cmd.connectLoadInitFormats()
       4: cmd/prepare-storage.go:311:cmd.waitForFormatErasure()
       3: cmd/erasure-server-pool.go:95:cmd.newErasureServerPools()
       2: cmd/server-main.go:741:cmd.newObjectLayer()
       1: cmd/server-main.go:576:cmd.serverMain()
Waiting for a minimum of 1 drives to come online (elapsed 2s)
```

## Possible Solution
As a workaround network type can be changed to 'host'. In this case minio works as expected.

## Steps to Reproduce (for bugs)
1. Start docker-compose on two nodes
```
version: '3.9'

services:
  minio1:
    image: minio/minio:RELEASE.2022-11-11T03-44-20Z
    command: server http://172.31.0.9{0...1}/data
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - data1:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  data1:
```

## Context
It appears that this problem would not come up, if I used network overlay. But in my opinion this is unreasonable complication. More so I had created elk cluster on same nodes and it didnt have any problems with nodes addresses.

## Your Environment
Image I am using is - minio/minio:RELEASE.2022-11-11T03-44-20Z
docker-compose v2.6.1
docker 20.10.17, build 100c701

**Comment by harshavardhana** [comment]
you cannot randomly choose your own IP here @huvalk you need to let docker give you the IP

**Comment by harshavardhana** [comment]
Don't engineer this yourself look at the relevant docs - https://github.com/minio/minio/tree/master/docs/orchestration/docker-compose

```yaml
version: '3.7'

# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2022-11-26T22-43-32Z
  command: server --console-address ":9001" http://minio{1...4}/data{1...2}
  expose:
    - "9000"
    - "9001"
  # environment:
    # MINIO_ROOT_USER: minioadmin
    # MINIO_ROOT_PASSWORD: minioadmin
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3

# starts 4 docker containers running minio server instances.
# using nginx reverse proxy, load balancing, you can access
# it through port 9000.
services:
  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - data1-1:/data1
      - data1-2:/data2

  minio2:
    <<: *minio-common
    hostname: minio2
    volumes:
      - data2-1:/data1
      - data2-2:/data2

  minio3:
    <<: *minio-common
    hostname: minio3
    volumes:
      - data3-1:/data1
      - data3-2:/data2

  minio4:
    <<: *minio-common
    hostname: minio4
    volumes:
      - data4-1:/data1
      - data4-2:/data2

  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  data1-1:
  data1-2:
  data2-1:
  data2-2:
  data3-1:
  data3-2:
  data4-1:
  data4-2:
```
