### ISSUE TITLE
Cannot browse a bucket after upgrading RELEASE.2022-12-07T00-56-37Z

### ISSUE THREAD

**Issue by Fredouye** [minio/minio#16200]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

Hi

since upgrading to `RELEASE.2022-12-07T00-56-37Z`, I cannot browse a bucket, all I get is and endless "loading..." indicator.
Going back to `RELEASE.2022-12-02T19-19-22Z`fixes the issue.

## Expected Behavior

Browsing a repo should display its content.

## Steps to Reproduce (for bugs)

Install RELEASE.2022-12-07T00-56-37Z, create a repo, try to browse it.
Install a previous release, create a repo, upgrade to RELEASE.2022-12-07T00-56-37Z, try to browse the repo.

In both cases, I get and endless "loading..." indicator.

## Regression

Yes, going back to `RELEASE.2022-12-02T19-19-22Z`fixes the issue.

## Your Environment

Docker 20.10.21 running on RHEL 9.

docker-compose.yml :
```
networks:
  traefik:
    external: true

services:
   minio:
#       image: minio/minio:RELEASE.2022-12-02T19-19-22Z
       image: minio/minio:latest
       command: server --console-address ":9001" /data
       volumes:
          - ./data:/data
       networks:
          - traefik
       environment:
          - MINIO_ROOT_USER=minioadmin
          - MINIO_ROOT_PASSWORD=minioadmin
          - MINIO_DOMAIN=minio.foo.com
          - MINIO_SERVER_URL=https://minio.foo.com
          - MINIO_BROWSER_REDIRECT_URL=https://console.minio.foo.com
       labels:
          - "traefik.enable=true"
          # Console
          - "traefik.http.routers.minio-console.rule=Host(`console.minio.foo.com`)"
          - "traefik.http.routers.minio-console.entrypoints=https"
          - "traefik.http.routers.minio-console.tls.certresolver=le"
          - "traefik.http.routers.minio-console.service=minio-console"
          - "traefik.http.services.minio-console.loadbalancer.server.port=9001"
          # APi
          - "traefik.http.routers.minio.rule=Host(`minio.foo.com`)"
          - "traefik.http.routers.minio.entrypoints=https"
          - "traefik.http.routers.minio.tls.certresolver=le"
          - "traefik.http.routers.minio.service=minio"
          - "traefik.http.services.minio.loadbalancer.server.port=9000"
```
