### ISSUE TITLE
How to proxy minio with ingress-nginx

### ISSUE THREAD

**Issue by JDer-liuodngkai** [minio/minio#16214]
I deployed a standalone minio on my kubernetes cluster via helm. But I can't proxy minio through ingress-nginx when using the service name in nginx.ingress.kubernetes.io/upstream-vhost, but it works well when i use the clusterIP of service. This is the ingress yaml I use:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: minio-bucket-1edb2ca4
  namespace: minio
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/upstream-vhost: minio:9000
spec:
  rules:
  - http:
      paths:
      - path: /minio-*
        backend:
          serviceName: minio
          servicePort: 9000
```

I want to proxy bucket 'minio-1edb2ca4' in minio through the ingress. When I access the connection shared by the minio through this ingress I get the following error:
```
<Error>
<Code>SignatureDoesNotMatch</Code>
<Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>
<Key>2022-6/69b47458e66311eca9e6ee49a8ed890b/20220110161903.png</Key>
<BucketName>1edb2ca4</BucketName>
<Resource>/1edb2ca4/2022-6/69b47458e66311eca9e6ee49a8ed890b/20220110161903.png</Resource>
<RequestId>16FAE81E626255BD</RequestId>
<HostId>6ad3e992-9b54-4926-8ee8-4ef22ecbf27f</HostId>
</Error>
```

But when I replace the service name with service ip, it works well, just like the following:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: minio-bucket-1edb2ca4
  namespace: minio
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/upstream-vhost: xxx.xxx.xxx.xxx.:9000
spec:
  rules:
  - http:
      paths:
      - path: /minio-*
        backend:
          serviceName: minio
          servicePort: 9000
```
Hope you give me some advice, thanks.
