### ISSUE TITLE
docker - default bucket not created

### ISSUE THREAD

**Issue by danielzzz** [minio/minio#16264]
It seems that the default bucket nor keys are not created when using docker

## Steps to Reproduce (for bugs)
I am using the following config and .env file
```
version: '3'
services:
  minio:
        image: quay.io/minio/minio
        command: server --console-address ":9001" /data
        volumes:
            - ./files:/data
        ports:
            - "35000:9000"
            - "35001:9001"
        environment:
            MINIO_ROOT_USER: ${MINIO_ADMIN}
            MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
            MINIO_SERVER_ACCESS_KEY: ${MINIO_SERVER_ACCESS_KEY}
            MINIO_SERVER_SECRET_KEY: ${MINIO_SERVER_SECRET_KEY}
            # MINIO_ACCESS_KEY: ${MINIO_SERVER_ACCESS_KEY}
            # MINIO_SECRET_KEY: ${MINIO_SERVER_SECRET_KEY}
            MINIO_DEFAULT_BUCKETS: ${MINIO_DEFAULT_BUCKETS}
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
            interval: 30s
            timeout: 20s
```

```
MINIO_ADMIN=admin
MINIO_PASSWORD=adminadmin
MINIO_ENDPOINT="http://scriptomat.minio:9000"
MINIO_SERVER_ACCESS_KEY=Qc43MGOVsIOd7b0d
MINIO_SERVER_SECRET_KEY=dzOkI4kGZPkSeTAZsHSFXzRNVWMBcmB4
MINIO_DEFAULT_BUCKETS="test:public"

```

but while the root user/password works the other settings seems to be ignored...

there is no bucket nor keys created.

am I doing something wrong? 

thank you!
dan
