### ISSUE TITLE
Web Session timeout is very short with OPENID identity Auth method 

### ISSUE THREAD

**Issue by abdennour** [minio/minio#16308]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior
Regardless the identity provider, the web session timeout should be the same. 

## Current Behavior
When connecting Minio with an identity provider thru OIDC method, the web session expires quickly. If no activities on the website for almost 1 minute, you will get your self logged out. 

## Possible Solution

Expecting to provide an env vars like `MINIO_IDENTITY_OPENID_SESSION_TIMEOUT=3600s`

## Steps to Reproduce (for bugs)

1. Install minio using bitnami helm chart (version `11.10.24`)
2. Configuring new client in the keycloak realm, then Setting the following env vars in minio: 
```yaml
    - name: MINIO_IDENTITY_OPENID_CONFIG_URL
      value: "https://sso.comp.lan/auth/realms/myrealm/.well-known/openid-configuration" 
    - name: MINIO_IDENTITY_OPENID_CLIENT_ID
      value: "minio" # ENV
    - name: MINIO_IDENTITY_OPENID_CLIENT_SECRET
      value: "xxxxxxx-xxx-xxxx-xxxx-xxxxxxx" # ENV
    - name: MINIO_IDENTITY_OPENID_SCOPES
      value: "openid,profile,email,groups"
    - name: MINIO_IDENTITY_OPENID_CLAIM_NAME
      value: "groups"
    - name: MINIO_IDENTITY_OPENID_REDIRECT_URI
      value: https://minio.comp.lan/oauth_callback # ENV
    - name: MINIO_IDENTITY_OPENID_COMMENT
      value: Comp SSO
```
4. Upgrading the helm release & Navigating to Website again

===> the Login works fine however the web session is very short & it expires as soon as you stop navigating/clicking here and there.

## Context
RBAC with OIDC

## Regression
N/A
## Your Environment
* Version used (`minio --version`):
```
minio version DEVELOPMENT.2022-12-12T19-27-27Z (commit-id=a469e6768df4d5d2cb340749fa58e4721a7dee96)
Runtime: go1.18.9 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2022 MinIO, Inc.
```

* Server setup and configuration: kubernetes .1.24
* Operating System and version (`uname -a`): `Linux minio-s3-main-0 4.18.0-372.26.1.el8_6.x86_64 #1 SMP Sat Aug 27 02:44:20 EDT 2022 x86_64 GNU/Linux`
