### ISSUE TITLE
Helm chart default values way over-provisioned defaults

### ISSUE THREAD

**Issue by nodesocket** [minio/minio#16347]
**Is your feature request related to a problem? Please describe.**
By default, the Helm chart sets `replicas: 16`, `persistence.size: 500 Gi`, and `resource.requests.memory: 16Gi`. These don't seem like very sane defaults, especially `replicas` and `resource.requests.memory`.

**Describe the solution you'd like**
Modify the default `values.yaml` to:

```
replicas: 4
```

```
persistence.size: 8 Gi
```

```
    resources:
      requests:
        memory: 256Mi
        cpu: 1
      limits:
        cpu: 1
```
