### ISSUE TITLE
Add a way to disable DNS caching during startup

### ISSUE THREAD

**Issue by theSuess** [minio/minio#16355]
**Is your feature request related to a problem? Please describe.**

In a Kubernetes environment, if the container starts before the DNS records have been fully propagated, the DNS cache stores a negative result which causes the startup to be delayed by a minute (https://github.com/minio/minio/blob/master/cmd/common-main.go#L120).

During this timeframe each failing lookup logs an error which puts heavy load on the logging system, resulting in ~150000 lines of log messages for a simple 2 Nodes/2 Disks setup.

**Describe the solution you'd like**

Introduce an option to disable the DNS lookup cache

**Describe alternatives you've considered**

Alternatively, introducing an exponential back off approach would at least remediate the log spam

**Additional context**
If this is something desirable, I can implement it myself, I just wanted to open up the issue for discussion.

**Comment by harshavardhana** [comment]
> During this timeframe each failing lookup logs an error which puts heavy load on the logging system, resulting in ~150000 lines of log messages for a simple 2 Nodes/2 Disks setup.

The logging itself can be turned off for similar-looking logs, however, the DNS will be available if you use a headless service for a stateful set when the pod gets scheduled, and this doesn't change once the "pod has started". So what you are saying doesn't make sense.

I suspect there is a deployment issue here, can you share how you deployed MinIO? share the yaml file of your deployment pattern.

**Comment by theSuess** [comment]
Slowed down DNS propagation is the only thing which makes sense to me. 

The Kubernetes spec never guarantees that propagation is finished before the pod is started, especially if the Kubernetes DNS resolver utilizes caching itself.

> Depending on how DNS is configured in your cluster, you may not be able to look up the DNS name for a newly-run Pod immediately. This behavior can occur when other clients in the cluster have already sent queries for the hostname of the Pod before it was created. Negative caching (normal in DNS) means that the results of previous failed lookups are remembered and reused, even after the Pod is running, for at least a few seconds.

https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#stable-network-id

Modifying the global DNS settings is not an option for us as this would kill performance in other parts of the system.

These are the relevant parts of my deployment, but I think this has to be fixed in software:
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio-auxiliary
spec:
  podManagementPolicy: Parallel
  replicas: 2
  selector:
    matchLabels:
      name: minio-auxiliary
  serviceName: minio-auxiliary-hl
  template:
    metadata:
      labels:
        name: minio-auxiliary
    spec:
      containers:
      - args:
        - server
        - --console-address
        - :9090
        - http://minio-auxiliary-{0...1}.minio-auxiliary-hl:9000/export/data{0...1}
        env:
        - name: MINIO_STORAGE_CLASS_STANDARD
          value: EC:2
        envFrom:
        - secretRef:
            name: minio-auxiliary
        image: quay.io/minio/minio:RELEASE.2022-10-21T22-37-48Z
        imagePullPolicy: IfNotPresent
        name: minio
        ports:
        - containerPort: 9000
          name: http
        - containerPort: 9090
          name: console
        volumeMounts:
        - mountPath: /export/data0
          name: data0
        - mountPath: /export/data1
          name: data1
  updateStrategy:
    type: RollingUpdate
---
apiVersion: v1
kind: Service
metadata:
  name: minio-auxiliary-hl
spec:
  ports:
  - name: http
    port: 9000
    targetPort: 9000
  - name: console
    port: 9090
    targetPort: 9090
  publishNotReadyAddresses: true
  selector:
    name: minio-auxiliary
```

And this is the recurring error I get in the first 60 seconds:
```
API: SYSTEM()
Time: 08:35:53 UTC 01/04/2023
Error: lookup minio-auxiliary-0.minio-auxiliary-hl on 10.76.0.10:53: no such host (*net.DNSError)
       host="minio-auxiliary-0.minio-auxiliary-hl", elapsedTime="1 second elapsed"
       6: internal/logger/logger.go:259:logger.LogIf()
       5: cmd/endpoint.go:478:cmd.Endpoints.UpdateIsLocal()
       4: cmd/endpoint.go:633:cmd.CreateEndpoints()
       3: cmd/endpoint-ellipses.go:373:cmd.createServerEndpoints()
       2: cmd/server-main.go:194:cmd.serverHandleCmdArgs()
       1: cmd/server-main.go:462:cmd.serverMain()
```
