### ISSUE TITLE
Broken pipe when using Kubernetes and port forwarding 9001

### ISSUE THREAD

**Issue by juliev0** [minio/minio#16369]
## Expected Behavior
Prior to  `minio/minio:RELEASE.2022-12-12T19-27-27Z`, I am able to run minio server in kubernetes with this yaml:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  labels:
    app: minio
spec:
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      automountServiceAccountToken: false
      containers:
        - name: main
          image: minio/minio
          imagePullPolicy: Always
          env:
            - name: MINIO_ACCESS_KEY
              value: admin
            - name: MINIO_SECRET_KEY
              value: password
          ports:
            - containerPort: 9000
              name: api
            - containerPort: 9001
              name: dashboard
          command: [minio, server, --console-address, ":9001", /data]
          lifecycle:
            postStart:
              exec:
                command: [mkdir, -p, /data/my-bucket]
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 10
```
and then port forward the pod to my local machine using:
`kubectl port-forward <podname> 9001:9001`
and then successfully bring up localhost:9001 in my browser and log in.

## Current Behavior
As of `minio/minio:RELEASE.2022-12-12T19-27-27Z`, this no longer works. Instead I see a broken pipe error in the terminal and the browser hangs.
```E0105 09:00:38.691734   27179 portforward.go:378] error copying from remote stream to local connection: readfrom tcp6 [::1]:9002->[::1]:62674: write tcp6 [::1]:9002->[::1]:62674: write: broken pipe```

Interestingly, I was able to run just the docker container outside K8S and map the port, so I'm not sure what the difference might be.

## Your Environment
I'm on an M1 Mac running Monterey 12.6, but have also confirmed my colleague who is using a non-M1 Mac is experiencing the same.
