### ISSUE TITLE
The content of the cache bucket cannot be displayed

### ISSUE THREAD

**Issue by ghost** [minio/minio#16428]
`MinIO VERSION  2023-01-12T02:06:16Z`

![image](https://user-images.githubusercontent.com/71524776/213076089-23f68f49-e569-4ae1-ba6f-5bdcf3b4e59f.png)
![image](https://user-images.githubusercontent.com/71524776/213076112-6c7c2974-2933-4226-9979-15e2b7735497.png)
![image](https://user-images.githubusercontent.com/71524776/213076466-0154c339-3254-4511-91cb-c09650077aba.png)

deployment file：

`docker-compose.yml`:
```yml
version: '3.7'

# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2023-01-12T02-06-16Z
  command: server --console-address ":9001" http://minio{1...4}/data{1...2}
  expose:
    - "9000"
    - "9001"
  environment:
    MINIO_ROOT_USER: admin
    MINIO_ROOT_PASSWORD: admin@123
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3

# starts 4 docker containers running minio server instances.
# using nginx reverse proxy, load balancing, you can access
# it through port 9000.
services:
  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - /data/minio/data1-1:/data1
      - /data/minio/data1-2:/data2

  minio2:
    <<: *minio-common
    hostname: minio2
    volumes:
      - /data/minio/data2-1:/data1
      - /data/minio/data2-2:/data2

  minio3:
    <<: *minio-common
    hostname: minio3
    volumes:
      - /data/minio/data3-1:/data1
      - /data/minio/data3-2:/data2

  minio4:
    <<: *minio-common
    hostname: minio4
    volumes:
      - /data/minio/data4-1:/data1
      - /data/minio/data4-2:/data2

  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  data1-1:
  data1-2:
  data2-1:
  data2-2:
  data3-1:
  data3-2:
  data4-1:
  data4-2:

```

`nginx.conf`:
```shell
user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;


events {
    worker_connections  2048;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;

    client_max_body_size 3072m;
    client_header_timeout 600s;
    client_body_timeout 600s;
    proxy_connect_timeout 75s;
    proxy_read_timeout 1800s;
    proxy_send_timeout 1800s;


    upstream minio_cluster1 {
      server minio1:9000;
      server minio2:9000;
      server minio3:9000;
      server minio4:9000;
    }


    upstream minio_cluster2 {
      server minio1:9001;
      server minio2:9001;
      server minio3:9001;
      server minio4:9001;
    }


    server {
      listen 9000;
      server_name minio;
      location / {
        proxy_buffering off;
        proxy_set_header Host $http_host;
        proxy_pass http://minio_cluster1;
      }
    }

    server {
      listen 9001;
      server_name minio;
      location / {
        proxy_buffering off;
        proxy_set_header Host $http_host;
        proxy_pass http://minio_cluster2;
      }
    }


}

```
