### ISSUE TITLE
docker compose multicontainer not starting

### ISSUE THREAD

**Issue by vandman** [minio/minio#16457]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior
Normal start of the service via:
```shell
docker compose up -d
```

## Current Behavior
3 out of 4 of the server constantly restart.
3 out of 4 container does not get an ip address on 01_front network (docker inspect minio...) .

## Possible Solution
???

## Steps to Reproduce (for bugs)
The last 3 releases has the problem.
so with the following release:
 ```shell
docker compose up -d
```
RELEASE.2023-01-20T02-05-44Z
RELEASE.2023-01-18T04-36-38Z
RELEASE.2023-01-12T02-06-16Z

The problem does not seems to come from "docker" or "docker compose" as the server start and work untill the release RELEASE.2023-01-06T18-11-18Z.

## Your Environment
here is the docker-compose.yml:
```
version: '3.7'

# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2023-01-06T18-11-18Z
#  image: quay.io/minio/minio
  restart: unless-stopped
  command: server --console-address ":9001" http://minio{1...4}/data
  expose:
    - "9000"
    - "9001"
  networks:
    - front
  environment:
    MINIO_ROOT_USER: ${MINIO_ROOT_USER}
    MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    MINIO_STORAGE_CLASS_STANDARD: 2
    MINIO_PROMETHEUS_JOB_ID: ${MINIO_PROMETHEUS_JOB_ID}
    MINIO_PROMETHEUS_URL: ${MINIO_PROMETHEUS_URL}
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3

x-minio-common-labels: &minio-common-labels
  traefik.enable: true
  traefik.docker.network: 01_front
  # Entrypoint and TLS
  ## API
  traefik.http.routers.minio-api.rule: "Host(`s3.a.exemple.fr`)"
  traefik.http.routers.minio-api.entrypoints: "http,https"
  traefik.http.routers.minio-api.tls: true
  traefik.http.routers.minio-api.tls.certresolver: le
  traefik.http.routers.minio-api.service: minio-api
  ## Console
  traefik.http.routers.minio-console.rule: "Host(`c.s3.a.exemple.fr`)"
  traefik.http.routers.minio-console.entrypoints: "http,https"
  traefik.http.routers.minio-console.tls: true
  traefik.http.routers.minio-console.tls.certresolver: le
  traefik.http.routers.minio-console.service: minio-console
  ## Service
  ## SameSit can be none, lax, strict
  traefik.http.services.minio-api.loadbalancer.server.port: 9000
  traefik.http.services.minio-api.loadbalancer.sticky.cookie: true
  traefik.http.services.minio-api.loadbalancer.sticky.cookie.name: minio
  traefik.http.services.minio-api.loadbalancer.sticky.cookie.samesite: strict
  traefik.http.services.minio-api.loadbalancer.sticky.cookie.secure: true
  traefik.http.services.minio-console.loadbalancer.server.port: 9001
  traefik.http.services.minio-console.loadbalancer.sticky.cookie: true
  traefik.http.services.minio-console.loadbalancer.sticky.cookie.name: minio
  traefik.http.services.minio-console.loadbalancer.sticky.cookie.samesite: strict
  traefik.http.services.minio-console.loadbalancer.sticky.cookie.secure: true
  # Middlewares
  traefik.http.routers.minio-api.middlewares: "force-https,minio"
  traefik.http.routers.minio-console.middlewares: "force-https,minio-known-ip,minio,minio-console-chain"
  # Middlewares nc force https and adds additional headers
  traefik.http.middlewares.minio-console-chain.chain.middlewares: "force-https,minio-known-ip,minio"
  traefik.http.middlewares.minio-known-ip.ipwhitelist.sourcerange: "192.168.200.0/24"
  traefik.http.middlewares.force-https.redirectscheme.scheme: https
  traefik.http.middlewares.force-https.redirectscheme.permanent: true
  traefik.http.middlewares.minio.headers.customFrameOptionsValue: SAMEORIGIN
  traefik.http.middlewares.minio.headers.framedeny: true
  traefik.http.middlewares.minio.headers.stsincludesubdomains: true
  traefik.http.middlewares.minio.headers.stspreload: true
  traefik.http.middlewares.minio.headers.stsseconds: 15552000
  traefik.http.middlewares.minio.headers.contentTypeNosniff: true

# starts 4 docker containers running minio server instances.
# using nginx reverse proxy, load balancing, you can access
# it through port 9000.
services:
  minio1:
    <<: *minio-common
    container_name: minio1
    hostname: minio1
    volumes:
      - /media/minio1/data:/data
    labels:
      << : *minio-common-labels
      ## API
      traefik.http.routers.minio-api-1.rule: "Host(`1.s3.a.exemple.fr`)"
      traefik.http.routers.minio-api-1.entrypoints: "http,https"
      traefik.http.routers.minio-api-1.tls: true
      traefik.http.routers.minio-api-1.tls.certresolver: le
      traefik.http.routers.minio-api-1.service: minio-api
      ## Console
      traefik.http.routers.minio-console-1.rule: "Host(`c1.s3.a.exemple.fr`)"
      traefik.http.routers.minio-console-1.entrypoints: "http,https"
      traefik.http.routers.minio-console-1.tls: true
      traefik.http.routers.minio-console-1.tls.certresolver: le
      traefik.http.routers.minio-console-1.service: minio-console
      # Middlewares
      traefik.http.routers.minio-api-1.middlewares: "force-https,minio"
      traefik.http.routers.minio-console-1.middlewares: "force-https,minio-known-ip,minio,minio-console-chain"

  minio2:
    <<: *minio-common
    container_name: minio2
    hostname: minio2
    volumes:
      - /media/minio2/data:/data
    labels:
      << : *minio-common-labels
      ## API
      traefik.http.routers.minio-api-2.rule: "Host(`2.s3.a.exemple.fr`)"
      traefik.http.routers.minio-api-2.entrypoints: "http,https"
      traefik.http.routers.minio-api-2.tls: true
      traefik.http.routers.minio-api-2.tls.certresolver: le
      traefik.http.routers.minio-api-2.service: minio-api
      ## Console
      traefik.http.routers.minio-console-2.rule: "Host(`c2.s3.a.exemple.fr`)"
      traefik.http.routers.minio-console-2.entrypoints: "http,https"
      traefik.http.routers.minio-console-2.tls: true
      traefik.http.routers.minio-console-2.tls.certresolver: le
      traefik.http.routers.minio-console-2.service: minio-console
      # Middlewares
      traefik.http.routers.minio-api-2.middlewares: "force-https,minio"
      traefik.http.routers.minio-console-2.middlewares: "force-https,minio-known-ip,minio,minio-console-chain"

  minio3:
    <<: *minio-common
    container_name: minio3
    hostname: minio3
    volumes:
      - /media/minio3/data:/data
    labels:
      << : *minio-common-labels
      ## API
      traefik.http.routers.minio-api-3.rule: "Host(`3.s3.a.exemple.fr`)"
      traefik.http.routers.minio-api-3.entrypoints: "http,https"
      traefik.http.routers.minio-api-3.tls: true
      traefik.http.routers.minio-api-3.tls.certresolver: le
      traefik.http.routers.minio-api-3.service: minio-api
      ## Console
      traefik.http.routers.minio-console-3.rule: "Host(`c3.s3.a.exmple.fr`)"
      traefik.http.routers.minio-console-3.entrypoints: "http,https"
      traefik.http.routers.minio-console-3.tls: true
      traefik.http.routers.minio-console-3.tls.certresolver: le
      traefik.http.routers.minio-console-3.service: minio-console
      # Middlewares
      traefik.http.routers.minio-api-3.middlewares: "force-https,minio"
      traefik.http.routers.minio-console-3.middlewares: "force-https,minio-known-ip,minio,minio-console-chain"

  minio4:
    <<: *minio-common
    container_name: minio4
    hostname: minio4
    volumes:
      - /media/minio4/data:/data
    labels:
      << : *minio-common-labels
      ## API
      traefik.http.routers.minio-api-4.rule: "Host(`4.s3.a.exemple.fr`)"
      traefik.http.routers.minio-api-4.entrypoints: "http,https"
      traefik.http.routers.minio-api-4.tls: true
      traefik.http.routers.minio-api-4.tls.certresolver: le
      traefik.http.routers.minio-api-4.service: minio-api
      ## Console
      traefik.http.routers.minio-console-4.rule: "Host(`c4.s3.a.exemple.fr`)"
      traefik.http.routers.minio-console-4.entrypoints: "http,https"
      traefik.http.routers.minio-console-4.tls: true
      traefik.http.routers.minio-console-4.tls.certresolver: le
      traefik.http.routers.minio-console-4.service: minio-console
      # Middlewares
      traefik.http.routers.minio-api-4.middlewares: "force-https,minio"
      traefik.http.routers.minio-console-4.middlewares: "force-https,minio-known-ip,minio,minio-console-chain"
      
networks:
  front:
    name: 01_front
    external: true
```
* Operating System and version:
```shell
root@serveur-a:~#uname -a
Linux serveur-a 5.10.0-20-amd64 #1 SMP Debian 5.10.158-2 (2022-12-13) x86_64 GNU/Linux

root@serveur-a:~# docker version
Client: Docker Engine - Community
 Version:           20.10.23
 API version:       1.41
 Go version:        go1.18.10
 Git commit:        7155243
 Built:             Thu Jan 19 17:34:13 2023
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.23
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.10
  Git commit:       6051f14
  Built:            Thu Jan 19 17:32:04 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.15
  GitCommit:        5b842e528e99d4d4c1686467debf2bd4b88ecd86
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

root@serveur-a:~# docker compose version
Docker Compose version v2.15.1
```
