### ISSUE TITLE
can't list files in web console

### ISSUE THREAD

**Issue by trim21** [minio/minio#16537]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior
should be able to show files

## Current Behavior

always loading, and 500 error message

`GET https://minio.trim21.cn/api/v1/subnet/info`

![image](https://user-images.githubusercontent.com/13553903/216715037-a8200ca3-f065-44b0-8fef-79538d3e0e34.png)

## Possible Solution

I don't know

## Steps to Reproduce (for bugs)

I'm running minio with very basic config

1.

```
  minio:
    image: 'minio/minio:RELEASE.2023-01-31T02-24-19Z'
    command: 'server /mnt/ --console-address ":8999"'
    networks:
      - infra
    restart: unless-stopped
    expose:
      - 9000
    ports:
      - "127.0.0.1:8999:8999"
      - "127.0.0.1:9000:9000"
    environment:
      MINIO_ROOT_USER: "..."
      MINIO_ROOT_PASSWORD: "..."
      MINIO_PROMETHEUS_AUTH_TYPE: public
      CONSOLE_MINIO_SERVER: "..."
    volumes:
      - "./minio:/mnt"
```

1. start docker image
2. login
3. create a bucket
4. try to browse files with web console

## Your Environment

* Version used (`minio --version`): `RELEASE.2023-01-31T02-24-19Z`
* Server setup and configuration: docker
* Operating System and version (`uname -a`): `Linux VM-0-2-ubuntu 5.4.0-77-generic #86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
