### ISSUE TITLE
Can't see the image in a direct link.

### ISSUE THREAD

**Issue by vladutt** [minio/minio#16544]
Hello!
Guys, I have an issue regarding images uploaded to minio. I can download them and preview, but i can't share direct link or use the link in a img tag, because when I access the direct link to that img (ex: http://127.0.0.1:9090/qrs/39/example-2.png) i receive... `cannot be displayed because it contains errors`.

## Expected Behavior
Should display the image in browser. Like in preview... (img)
![image](https://user-images.githubusercontent.com/20255285/216960971-f7266141-2a26-4345-b0c9-75b055aa12be.png)

## Current Behavior
![image](https://user-images.githubusercontent.com/20255285/216961169-ca7b6d1a-4aba-4152-930b-f6166edf8433.png)

## Possible Solution
I have no idea, but images works fine in any version from RELEASE.2020.x

## Steps to Reproduce (for bugs)
Run any minio version from 2023 / latest, upload an image and try to share of the image.

It happens with every image.

## Your Environment

* Version used (`minio --version`): RELEASE.2023-01-25T00-19-54Z
* Server setup and configuration:  
docker-compose.yml
```
version: 3

services:

     minio:
        hostname: minio
        image: minio/minio:RELEASE.2023-01-25T00-19-54Z
        container_name: minio
        ports:
            - "9876:9000"
            - "9090:9090"
        volumes:
            - cdn_data:/data
        environment:
            MINIO_ACCESS_KEY: minioadmin
            MINIO_SECRET_KEY: minioadmin
        command: server /data
volumes:
    cdn_data:
```
* Operating System and version (`uname -a`): Linux minio 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux (from docker container)
