### ISSUE TITLE
minio doesn't list folders

### ISSUE THREAD

**Issue by fabioportieri** [minio/minio#16663]
Follow up of those tickets

https://github.com/minio/minio/issues/10817
https://github.com/minio/minio/issues/6047

friendly remainder to make the behaviour as close as possible to aws S3, since it's supposed to be compatible

C:\lavoro\workspace\fdp\kubernetes>mc ls -r local/test-versioned/JUnitTest/

[2023-02-20 10:57:17 CET]    26B STANDARD pippo/pluto/testFile_1=_-.remote
[2023-02-20 10:57:17 CET]    26B STANDARD pippo/pluto/testFile_2.remote
[2023-02-20 10:57:17 CET]    26B STANDARD pippo/topolino/testFile_3.remote
[2023-02-20 10:57:17 CET]    26B STANDARD pippo/topolino/testFile_4.remote

## Expected Behavior

to show not only files but even directories, as pointed out in the example in 
https://github.com/minio/minio/issues/10817

## Current Behavior

only files are listed

Thank you

**Comment by harshavardhana** [comment]
You didn't create any folders here @fabioportieri 

Also you haven't really mentioned anything about your setup.

You have also referred some random historical issues that do not make sense anymore. Please make sure to report issues properly by stating your deployment MinIO version and also how is the deployment configured.

We cannot imagine your setup. I am going to close this issue until we get some information in.

**Comment by fabioportieri** [comment]
this is my bucket configuration

![image](https://user-images.githubusercontent.com/6490539/220078855-1112e052-3ce5-4922-9419-75040c10c6b2.png)

folders, that i can see via dashboard, but can't via mc ls or java sdk api: (note emptyDir)

![image](https://user-images.githubusercontent.com/6490539/220079115-0dff6e8e-c3b0-48ee-aa06-cd0163b1b378.png)

![image](https://user-images.githubusercontent.com/6490539/220079223-a7941773-a989-404a-9a26-8585ec01e183.png)


minio version is the latest, pulled from 
https://quay.io/repository/minio/minio?tab=tags&tag=latest
deployed via kubernetes


the deployment files:

```yml
# Deploys a new MinIO Pod into the metadata.namespace Kubernetes namespace
#
# The `spec.containers[0].args` contains the command run on the pod
# The `/data` directory corresponds to the `spec.containers[0].volumeMounts[0].mountPath`
# That mount path corresponds to a Kubernetes HostPath which binds `/data` to a local drive or volume on the worker node where the pod runs
#
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: minio
  name: minio
  namespace: default
spec:
  containers:
  - name: minio
    image: quay.io/minio/minio:latest
    command:
    - /bin/bash
    - -c
    args:
    - minio server /data --console-address :9090
    volumeMounts:
    - mountPath: /data
      name: localvolume # Corresponds to the `spec.volumes` Persistent Volume
  nodeSelector:
    kubernetes.io/hostname: minikube # Specify a node label associated to the Worker Node on which you want to deploy the pod.
  volumes:
  - name: localvolume
    hostPath: # MinIO generally recommends using locally-attached volumes
      path: /mnt/disk1/data # Specify a path to a local drive or volume on the Kubernetes worker node
      type: DirectoryOrCreate # The path to the last directory must exist
---
apiVersion: v1
kind: Service
metadata:
  # This name uniquely identifies the service
  name: minio-console-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
  selector:
    # Looks for labels `app:minio` in the namespace and applies the spec
    app: minio
---
apiVersion: v1
kind: Service
metadata:
  # This name uniquely identifies the service
  name: minio-api-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    # Looks for labels `app:minio` in the namespace and applies the spec
    app: minio
```

hope i'm not forgetting anything, the issues i posted are those i found relevant to my issue, how come they do not make sense anymore? also in the https://github.com/minio/minio/issues/10817 i'm under the impression that minio is supposed to list directories:
![image](https://user-images.githubusercontent.com/6490539/220080729-ffbb35dc-3b76-4b21-9ead-cdd74745a637.png)


 but in my case it doesn't do so, i expected the dirs to be listed too, besides the files: 
emptyDir/
pippo/
pippo/pluto/
pippo/topolino/


Thank you
