### ISSUE TITLE
CreateBucket using virtual host-style - incorrect header in response

### ISSUE THREAD

**Issue by hanssv** [minio/minio#16729]
When creating a bucket using virtual host-style addressing the response headers include `location=/` where it should be `location=/<bucket-name>` 

## Expected Behavior
`Response headers: {'Accept-Ranges': 'bytes', 'Content-Length': '0', 'Content-Security-Policy': 'block-all-mixed-content', 'Location': '/foobar', 'Server': 'MinIO', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'Vary': 'Origin, Accept-Encoding', 'X-Amz-Bucket-Region': 'us-west-1', 'X-Amz-Id-2': 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', 'X-Amz-Request-Id': '1747FD0AE6009647', 'X-Content-Type-Options': 'nosniff', 'X-Xss-Protection': '1; mode=block', 'Date': 'Tue, 28 Feb 2023 12:33:29 GMT'}`

## Current Behavior

` Response headers: {'Accept-Ranges': 'bytes', 'Content-Length': '0', 'Content-Security-Policy': 'block-all-mixed-content', 'Location': '/', 'Server': 'MinIO', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'Vary': 'Origin, Accept-Encoding', 'X-Amz-Bucket-Region': 'us-west-1', 'X-Amz-Id-2': 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', 'X-Amz-Request-Id': '1747FCFC4831F19D', 'X-Content-Type-Options': 'nosniff', 'X-Xss-Protection': '1; mode=block', 'Date': 'Tue, 28 Feb 2023 12:32:26 GMT'}`
## Possible Solution
Instead of an obscure use of `getObjectLocation` just set the header to the correct value (`/<bucket>`).

## Steps to Reproduce (for bugs)

1. Ensures MinIO is setup to use virtual host-style addressing (i.e. set `MINIO_DOMAIN`) 
2. Create a bucket using virtual host-style addressing (for example using `addressing-style = virtual` in aws config)
3. Check the response headers

## Context
Incompatible to AWS S3

## Regression
No

## Your Environment
* Version used (`minio --version`):
`RELEASE.2023-02-27T18-10-45Z`
* Server setup and configuration:
Setup using docker-compose:
```
  minio-server:
    image: quay.io/minio/minio:RELEASE.2023-02-27T18-10-45Z
    environment:
      MINIO_ROOT_USER: minioadmin00
      MINIO_ROOT_PASSWORD: minioadmin00
      MINIO_DOMAIN: 127-0-0-1.nip.io
    command:
      - server
      - /data
      - --address
      - ':9100'
      - --console-address
      - ':9190'
    ports:
      - '9100:9100'
      - '9190:9190'
```
* Operating System and version (`uname -a`):
`Darwin Hans-MBPro2021.local 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000 arm64`
