### ISSUE TITLE
Error "%s resolves to localhost in a containerized deployment"

### ISSUE THREAD

**Issue by posliedov** [minio/minio#16754]
#### docker-compose.yaml

```yaml
version: '3.7'

services:
  minio:
    container_name: minio
    #image: minio/minio:RELEASE.2023-01-02T09-40-09Z
    image: minio/minio:RELEASE.2023-01-06T18-11-18Z
    network_mode: "host"
    volumes:
      - /data/minio:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: pa…rd
      MINIO_SERVER_URL: "https://minio.example.lan"
      MINIO_BROWSER_REDIRECT_URL: "https://minio-admin.example.lan"
    command: server --console-address ":9001" http://minio{01...04}.example.lan/data
    restart: unless-stopped
```

## Expected Behavior
All nodes should start without errors and discover each other

## Current Behavior
Every node has the same error, only the fqdn of the node in the logs is different:
```
Recreating minio ... done
Attaching to minio
minio    |
minio    | API: SYSTEM()
minio    | Time: 19:30:20 UTC 03/03/2023
minio    | Error: minio01.example.lan resolves to localhost in a containerized deployment, waiting for it to resolve to a valid IP (*errors.errorString)
minio    |        host="minio01.example.lan", elapsedTime="1 second elapsed"
minio    |        8: internal/logger/logger.go:258:logger.LogIf()
minio    |        7: internal/logger/logonce.go:104:logger.(*logOnceType).logOnceIf()
minio    |        6: internal/logger/logonce.go:135:logger.LogOnceIf()
minio    |        5: cmd/endpoint.go:489:cmd.Endpoints.UpdateIsLocal()
minio    |        4: cmd/endpoint.go:674:cmd.CreateEndpoints()
minio    |        3: cmd/endpoint-ellipses.go:383:cmd.createServerEndpoints()
minio    |        2: cmd/server-main.go:220:cmd.serverHandleCmdArgs()
minio    |        1: cmd/server-main.go:524:cmd.serverMain()
```

## Possible Solution
Use release `2023-01-02T09-40-09Z` that does not have this problem
(The problem is present from the `2023-01-06T18-11-18Z` version to the current one)

## Your Environment

* Version used (`minio --version`): `2023-02-27T18-10-45Z`
* Server setup and configuration: `Docker 20.10.5`
* Operating System and version (`uname -a`): `Linux minio01.example.lan 5.10.0-10-amd64 #1 SMP Debian 5.10.84-1 (2021-12-08) x86_64 GNU/Linux`
* `cat /etc/hosts` (according to https://www.debian.org/doc/manuals/debian-reference/ch05.en.html#_the_hostname_resolution):
```bash
127.0.0.1	localhost
127.0.1.1	minio01.example.lan	minio01

# The following lines are desirable for IPv6 capable hosts
::1	localhost	ip6-localhost ip6-loopback
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
```
