### ISSUE TITLE
get input/output error (*fs.PathError) in docker

### ISSUE THREAD

**Issue by ycyin** [minio/minio#16998]
## Expected Behavior
upload success.

## Current Behavior
```
API: PutObject(bucket=agile-service, object=1/eb2e147a710448f49c7d5c0ec40b2101@.gitlab-ci.yml)
Time: 09:10:40 UTC 04/07/2023
DeploymentID: 33190e30-9ad7-4ff3-9105-39e91ab8635d
RequestID: 17539C073DB66F44
RemoteHost: 10.0.0.19
Host: minio:9000
UserAgent: MinIO (amd64; amd64) minio-java/0.4.8
Error: write /export/.minio.sys/buckets/agile-service/1/eb2e147a710448f49c7d5c0ec40b2101@.gitlab-ci.yml/fs.json: input/output error (*fs.PathError)
       5: internal/logger/logger.go:259:logger.LogIf()
       4: cmd/api-errors.go:2185:cmd.toAPIErrorCode()
       3: cmd/api-errors.go:2210:cmd.toAPIError()
       2: cmd/object-handlers.go:1936:cmd.objectAPIHandlers.PutObjectHandler()
       1: net/http/server.go:2109:http.HandlerFunc.ServeHTTP()
```
## Possible Solution

At first I suspected it was a problem with my disk, but by testing this is no problem
```bash
[root@o0000344041-app ~]# badblocks -v /dev/mapper/vg_data-lv_minio
Checking blocks from 0 to 314572799
Checking for bad blocks (read-only test): 

done                                                 
Pass completed, 0 bad blocks found. (0/0/0 errors)
```
Is it my OS problem or the environment?
## Steps to Reproduce (for bugs)

1. use API upload or minio console 

## Context

File uploads occasionally fail, especially small file uploads (less than 1MB)
## Regression

like this issue <https://github.com/minio/minio/issues/13306#issue-1007402533>,but i did not use NFS Server as in this ISSUE
## Your Environment

* Version used (`minio --version`):  **minio version RELEASE.2022-10-24T18-35-07Z (commit-id=fc6c7949727ec261cd57fbdb02fa7575d0fd8e61)**
* Server setup and configuration:  
  docker version : **Server Version: 20.10.9**
  docker compose version： **Docker Compose version v2.3.3**
  docker-compose yaml：
```yaml
version: '2'

services:
  minio:
    container_name: minio
    image: minio:RELEASE.2022-10-24T18-35-07Z
    expose:
      - '9000'
      - '9001'
    command: minio server  /export --console-address :9001
    environment:
      - MINIO_ACCESS_KEY=root
      - MINIO_SECRET_KEY=****
      - SET_CONTAINER_TIMEZONE=true
    volumes:
      - 'minio_data:/export'
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - c7n_overlay

volumes:
  minio_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /DATA/minio/data
networks:
  c7n_overlay:
    external: true
```
* Operating System and version (`uname -a`): **` Linux o0000344041-app 3.10.0-957.el7.x86_64 #1 SMP Thu Oct 4 20:48:51 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux `**
