### ISSUE TITLE
Drive path full

### ISSUE THREAD

**Issue by j-wsl** [minio/minio#17055]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior
Drive is not full plenty of space available

## Current Behavior
Docker instance is giving the "drive path full" error when it is not

## Steps to Reproduce (for bugs)
Docker compose server is:
```
  minio:
    image: minio/minio
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /data/loki-data && \
        mkdir -p /data/loki-ruler &&
        minio server /data --console-address ":9001"
    environment:
      - MINIO_ACCESS_KEY=loki
      - MINIO_SECRET_KEY=supersecret
      - MINIO_PROMETHEUS_AUTH_TYPE=public
      - MINIO_UPDATE=off
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./.data/minio:/data
    networks:
      - loki
 ```

Error seen is:
```
API: PutObject(bucket=loki-data, object=fake/99edd65e6a3e69b1:1878fa17213:1878fa2d241:4d1b8a8c)
Time: 09:33:39 UTC 04/20/2023
DeploymentID: 4e4410e1-ac77-4331-9981-b0480d77cc53
RequestID: 17579AD37C2AC0E2
RemoteHost: 172.20.0.15
Host: minio:9000
UserAgent: aws-sdk-go/1.44.102 (go1.19.5; linux; amd64)
Error: drive path full (cmd.StorageErr)
       7: internal/logger/logger.go:258:logger.LogIf()
       6: cmd/erasure-object.go:1271:cmd.erasureObjects.putObject()
       5: cmd/erasure-object.go:954:cmd.erasureObjects.PutObject()
       4: cmd/erasure-sets.go:767:cmd.(*erasureSets).PutObject()
       3: cmd/erasure-server-pool.go:960:cmd.(*erasureServerPools).PutObject()
       2: cmd/object-handlers.go:1865:cmd.objectAPIHandlers.PutObjectHandler()
       1: net/http/server.go:2122:http.HandlerFunc.ServeHTTP()
```

Output of df -H:
```
[root@b73abe8df62d /]# df -H
Filesystem      Size  Used Avail Use% Mounted on
overlay         1.1T  350G  665G  35% /
tmpfs            68M     0   68M   0% /dev
shm              68M     0   68M   0% /dev/shm
/dev/sda1       1.1T  350G  665G  35% /data
tmpfs            34G     0   34G   0% /proc/acpi
tmpfs            34G     0   34G   0% /sys/firmware
```

## Your Environment
OS: Docker
```
[root@b73abe8df62d /]# uname -a
Linux b73abe8df62d 5.10.0-21-cloud-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 x86_64 x86_64 GNU/Linux
```
Version:
```
[root@b73abe8df62d /]# minio --version
minio version RELEASE.2023-04-13T03-08-07Z (commit-id=a42650c065fe22c6a6d3ce526d80c5354d4bceac)
Runtime: go1.20.3 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2023 MinIO, Inc.
```
