### ISSUE TITLE
Able to delete non-empty buckets and data is not deleted

### ISSUE THREAD

**Issue by ydkn** [minio/minio#17078]
## NOTE

Current version ([RELEASE.2023-04-20T17-56-55Z](https://github.com/minio/minio/releases/tag/RELEASE.2023-04-20T17-56-55Z)) does not check if a bucket is empty when deleted and retains the content which is available again when a bucket with the same name is created again.
This seams to be related when having multiple server pools.

## Expected Behavior
When a non-empty bucket is trying to be deleted return the same error message as previously:

```bash
aws --endpoint https://my-minio s3 rb s3://foobar 
remove_bucket failed: s3://foobar An error occurred (BucketNotEmpty) when calling the DeleteBucket operation: The bucket you tried to delete is not empty
```

## Current Behavior
A non-empty bucket can be deleted and after creating it again the old content is still present

## Possible Solution
n/a

## Steps to Reproduce (for bugs)
```bash
aws --endpoint https://my-minio s3 mb s3://foobar
make_bucket: foobar
```

```bash
aws --endpoint https://my-minio s3 ls
2023-04-25 19:19:37 foobar
```

```bash
aws --endpoint https://my-minio s3 cp 20230414_171256.jpg s3://foobar/20230414_171256.jpg
upload: Downloads/20230414_171256.jpg to s3://foobar/20230414_171256.jpg
```

```bash
aws --endpoint https://my-minio s3 cp 20230414_171256.jpg s3 ls s3://foobar/
2023-04-25 19:20:26    1478891 20230414_171256.jpg
```

```bash
aws --endpoint https://my-minio s3 cp 20230414_171256.jpg s3 rb s3://foobar 
remove_bucket: foobar
```

```bash
aws --endpoint https://my-minio s3 cp 20230414_171256.jpg s3 ls s3://foobar/
An error occurred (NoSuchBucket) when calling the ListObjectsV2 operation: The specified bucket does not exist
```

```bash
aws --endpoint https://my-minio s3 cp 20230414_171256.jpg s3 mb s3://foobar                                                                 
make_bucket: foobar
```

```bash
aws --endpoint https://my-minio s3 cp 20230414_171256.jpg s3 ls s3://foobar/                                                                
2023-04-25 19:20:26    1478891 20230414_171256.jpg
```

## Context
9 server pools with 4-6 servers each

## Regression
looks like https://github.com/minio/minio/pull/16859 introduced the bug.

## Your Environment
* Version used (`minio --version`): RELEASE.2023-04-20T17-56-55Z
* Server setup and configuration: 9 server pools, no tls
* Operating System and version (`uname -a`): docker

**Comment by harshavardhana** [comment]
> ```shell
> ```shell
> aws --endpoint https://my-minio s3 ls
> 2023-04-25 19:19:37 foobar
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> ```shell
> aws --endpoint https://my-minio s3 cp 20230414_171256.jpg s3://foobar/20230414_171256.jpg
> upload: Downloads/20230414_171256.jpg to s3://foobar/20230414_171256.jpg
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> ```shell
> aws --endpoint https://my-minio s3 cp 20230414_171256.jpg s3 ls s3://foobar/
> upload: Downloads/20230414_171256.jpg to s3://foobar/20230414_171256.jpg
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> ```shell
> aws --endpoint https://my-minio s3 cp 20230414_171256.jpg s3 ls s3://foobar/
> 2023-04-25 19:20:26    1478891 20230414_171256.jpg
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> ```shell
> aws --endpoint https://my-minio s3 cp 20230414_171256.jpg s3 rb s3://foobar 
> remove_bucket: foobar
> ```
> ```

These commands look all interleaved on each other you are doing `cp` and `rb` in the same command line.

**Comment by ydkn** [comment]
This was only to demonstrate how to reproduce it, all commands where executed in this order on the same command line with multiple seconds in between each other.

**Comment by ydkn** [comment]
I just updated the commands to reproduce it: there was one wrong output that I messed up during copying. Now it is accurate.

**Comment by harshavardhana** [comment]
It looks like your 9 pools are not behaving correctly, can you share your server configuration here including all the command line flags?

**Comment by ydkn** [comment]
Using the k8s operator. see attached manifest.
Same behaviour on a fresh/empty cluster with the same manifest. Rolling back to _RELEASE.2023-03-20T20-16-18Z_ also solves the problem.

```yaml
---
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: minio
  namespace: minio
spec:
  credsSecret:
    name: minio-user-root
  exposeServices: {}
  image: minio/minio:RELEASE.2023-04-20T17-56-55Z
  mountPath: /export
  env:
    - name: MINIO_REGION
      value: us-west-1
    - name: MINIO_BROWSER
      value: "on"
    - name: MINIO_STORAGE_CLASS_STANDARD
      value: EC:2
    - name: MINIO_STORAGE_CLASS_RRS
      value: EC:2
    - name: MINIO_PROMETHEUS_AUTH_TYPE
      value: public
  pools:
    - name: directpv-0
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: v1.min.io/pool
                    operator: In
                    values:
                      - directpv-0
              topologyKey: kubernetes.io/hostname
      resources:
        requests:
          cpu: "3"
          memory: 8Gi
        limits:
          cpu: "8"
          memory: 8Gi
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: Always
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      servers: 4
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: "7990000000000"
          storageClassName: directpv-min-io
      volumesPerServer: 1
    - name: directpv-1
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: v1.min.io/pool
                    operator: In
                    values:
                      - directpv-1
              topologyKey: kubernetes.io/hostname
      resources:
        requests:
          cpu: "3"
          memory: 8Gi
        limits:
          cpu: "8"
          memory: 8Gi
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: Always
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      servers: 4
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: "7990000000000"
          storageClassName: directpv-min-io
      volumesPerServer: 1
    - name: directpv-2
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: v1.min.io/pool
                    operator: In
                    values:
                      - directpv-2
              topologyKey: kubernetes.io/hostname
      resources:
        requests:
          cpu: "3"
          memory: 8Gi
        limits:
          cpu: "8"
          memory: 8Gi
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: Always
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      servers: 4
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: "7990000000000"
          storageClassName: directpv-min-io
      volumesPerServer: 1
    - name: directpv-3
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: v1.min.io/pool
                    operator: In
                    values:
                      - directpv-3
              topologyKey: kubernetes.io/hostname
      resources:
        requests:
          cpu: "3"
          memory: 8Gi
        limits:
          cpu: "8"
          memory: 8Gi
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: Always
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      servers: 4
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: "7990000000000"
          storageClassName: directpv-min-io
      volumesPerServer: 1
    - name: directpv-4
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: v1.min.io/pool
                    operator: In
                    values:
                      - directpv-4
              topologyKey: kubernetes.io/hostname
      resources:
        requests:
          cpu: "3"
          memory: 8Gi
        limits:
          cpu: "8"
          memory: 8Gi
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: Always
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      servers: 4
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: "7990000000000"
          storageClassName: directpv-min-io
      volumesPerServer: 1
    - name: directpv-5
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: v1.min.io/pool
                    operator: In
                    values:
                      - directpv-5
              topologyKey: kubernetes.io/hostname
      resources:
        requests:
          cpu: "3"
          memory: 8Gi
        limits:
          cpu: "8"
          memory: 8Gi
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: Always
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      servers: 4
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: "7990000000000"
          storageClassName: directpv-min-io
      volumesPerServer: 1
    - name: directpv-6
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: v1.min.io/pool
                    operator: In
                    values:
                      - directpv-6
              topologyKey: kubernetes.io/hostname
      resources:
        requests:
          cpu: "3"
          memory: 8Gi
        limits:
          cpu: "8"
          memory: 8Gi
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: Always
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      servers: 6
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: "7990000000000"
          storageClassName: directpv-min-io
      volumesPerServer: 1
    - name: directpv-7
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: v1.min.io/pool
                    operator: In
                    values:
                      - directpv-7
              topologyKey: kubernetes.io/hostname
      resources:
        requests:
          cpu: "3"
          memory: 8Gi
        limits:
          cpu: "8"
          memory: 8Gi
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: Always
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      servers: 6
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: "7990000000000"
          storageClassName: directpv-min-io
      volumesPerServer: 1
    - name: directpv-8
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: v1.min.io/pool
                    operator: In
                    values:
                      - directpv-8
              topologyKey: kubernetes.io/hostname
      resources:
        requests:
          cpu: "3"
          memory: 8Gi
        limits:
          cpu: "8"
          memory: 8Gi
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: Always
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      servers: 6
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: "7990000000000"
          storageClassName: directpv-min-io
      volumesPerServer: 1
  requestAutoCert: false
```
