### ISSUE TITLE
Multiple similar audit webhook events

### ISSUE THREAD

**Issue by ondrejmo** [minio/minio#17280]
## Expected Behavior

Each audit webhook `requestID` should be sent exactly once.

## Current Behavior

After updating to `RELEASE.2023-05-18T00-05-36Z`, from `RELEASE.2023-05-04T21-44-30Z`. Every audit event sent to by the webhook is receiver exactly ten times instead of once.

## Possible Solution

Unfortunately, I have no idea as to what could fix this, except for downgrading to the aforementioned older release, which fixes the behavior.

## Steps to Reproduce (for bugs)

1. Using k3s version `1.26`
2. Deploy these manifests (some irrelevant parts are censored/removed)
    ```yaml
    ---

    apiVersion: v1
    kind: Secret
    metadata:
      name: minio-config

    stringData:
      MINIO_ROOT_USER: changeme
      MINIO_ROOT_PASSWORD: changeme
      MINIO_BROWSER_REDIRECT: "off"
      MINIO_REGION_NAME: west-us
      MINIO_NOTIFY_REDIS_ENABLE: "on"
      MINIO_NOTIFY_REDIS_ADDRESS: redis.storage.svc:6379
      MINIO_NOTIFY_REDIS_KEY: minio
      MINIO_NOTIFY_REDIS_PASSWORD: changeme
      MINIO_NOTIFY_REDIS_FORMAT: access # https://min.io/docs/minio/linux/reference/minio-server/minio-server.html#envvar.MINIO_NOTIFY_REDIS_FORMAT
      MINIO_AUDIT_WEBHOOK_ENABLE_AGGREGATOR: "on"
      MINIO_AUDIT_WEBHOOK_ENDPOINT_AGGREGATOR: http://aggregator.monitoring.svc/minio

    ---

    apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: node4-minio
      labels:
        name: minio

    spec:
      capacity:
        storage: 256Gi
      volumeMode: Filesystem
      accessModes:
        - ReadWriteOnce
      persistentVolumeReclaimPolicy: Retain
      storageClassName: ext4
      local:
        path: /mnt/disk0/public
      nodeAffinity:
        required:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - node4.example.foobar

    ---

    apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: node5-minio
      labels:
        name: minio

    spec:
      capacity:
        storage: 256Gi
      volumeMode: Filesystem
      accessModes:
        - ReadWriteOnce
      persistentVolumeReclaimPolicy: Retain
      storageClassName: ext4
      local:
        path: /mnt/disk0/public
      nodeAffinity:
        required:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - node5.example.foobar

    ---

    apiVersion: v1
    kind: Service
    metadata:
      name: minio
      labels:
        app.kubernetes.io/name: minio

    spec:
      selector:
        app.kubernetes.io/name: minio
      ports:
        - name: api
          port: 9000
        - name: console
          port: 9001

    ---

    apiVersion: v1
    kind: Service
    metadata:
      name: minio-hl

    spec:
      clusterIP: None
      selector:
        app.kubernetes.io/name: minio
      ports:
        - name: api
          port: 9000
        - name: console
          port: 9001

    ---

    apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      name: minio

    spec:
      replicas: 2
      serviceName: minio-hl
      podManagementPolicy: Parallel
      selector:
        matchLabels:
          app.kubernetes.io/name: minio
      template:
        metadata:
          labels:
            app.kubernetes.io/name: minio
        spec:
          automountServiceAccountToken: false
          securityContext:
            runAsUser: 1000
            runAsGroup: 1066
            fsGroup: 1066
            fsGroupChangePolicy: OnRootMismatch
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - topologyKey: kubernetes.io/hostname
                  labelSelector:
                    matchExpressions:
                      - {key: app.kubernetes.io/name, operator: In, values: [minio]}
          containers:
            - name: minio
              image: quay.io/minio/minio:RELEASE.2023-05-18T00-05-36Z
              command: [ /bin/sh, -c ]
              args:
                - minio server --json --console-address=0.0.0.0:9001 http://minio-{0...1}.minio-hl.storage.svc.cluster.local/mnt/minio
              ports:
                - name: api
                  containerPort: 9000
                - name: console
                  containerPort: 9001
              readinessProbe:
                httpGet:
                  path: /minio/health/live
                  port: 9000
              livenessProbe:
                httpGet:
                  path: /minio/health/live
                  port: 9000
              envFrom:
                - secretRef:
                    name: minio-config
              volumeMounts:
                - name: minio
                  mountPath: /mnt/minio
      volumeClaimTemplates:
        - metadata:
            name: minio
          spec:
            storageClassName: ext4
            selector:
              matchLabels:
                name: minio
            accessModes: 
              - ReadWriteOnce
            resources:
              requests:
                storage: 256Gi
    ```

## Context

Events are received by the vector.dev, http_server source, it can temporarily be using the deduplication transformation and matching the `requestID`.

## Regression

Yes, I believe this is a regression, last working version is listed above.

## Environment

Ubuntu 22.04 (updated last week), amd64, k3s 1.26.4+k3s1.
