### ISSUE TITLE
Deployment fails on OpenShift 4.13

### ISSUE THREAD

**Issue by Roming22** [minio/minio#17378]
## Expected Behavior

Given the following subscription and clusterrole/clusterrolebinding:
```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openshift-minio-apply-tenants
rules:
  - apiGroups:
      - minio.min.io
    resources:
      - tenants
    verbs:
      - "get"
      - "create"
      - "update"
      - "patch"
      - "delete"
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
      - services
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openshift-minio-apply-tenants
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openshift-minio-apply-tenants
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: minio-operator
  namespace: openshift-operators
spec:
  channel: stable
  installPlanApproval: Automatic
  name: minio-operator
  source: certified-operators
  sourceNamespace: openshift-marketplace
```
I would expect MinIO to deploy successfully on OCP 4.13.

Note that the given configuration is currently deployed successfully on OCP 4.12.

## Current Behavior

* The `0-storage-pool-0-0` and `1-storage-pool-0-0` PVCs are successfully deployed.
* The `storage-pool-0-0` pod ends up in `CrashLoopBackOff` with the following logs:
```
API: SYSTEM()
Time: 19:43:33 UTC 06/07/2023
Error: Drive /export0, path (.minio.sys/pool.bin) returned an error (file access denied) (*fmt.wrapError)
14: internal/logger/logger.go:259:logger.LogIf()
13: internal/logger/logonce.go:104:logger.(*logOnceType).logOnceIf()
12: internal/logger/logonce.go:135:logger.LogOnceIf()
11: cmd/erasure-object.go:526:cmd.readAllXL()
10: cmd/erasure-object.go:594:cmd.erasureObjects.getObjectFileInfo()
9: cmd/erasure-object.go:220:cmd.erasureObjects.GetObjectNInfo()
8: cmd/erasure-sets.go:932:cmd.(*erasureSets).GetObjectNInfo()
7: cmd/config-common.go:33:cmd.readConfigWithMetadata()
6: cmd/config-common.go:55:cmd.readConfig()
5: cmd/erasure-server-pool-decom.go:399:cmd.(*poolMeta).load()
4: cmd/erasure-server-pool-decom.go:504:cmd.(*erasureServerPools).Init()
3: cmd/erasure-server-pool.go:144:cmd.newErasureServerPools()
2: cmd/server-main.go:700:cmd.newObjectLayer()
1: cmd/server-main.go:534:cmd.serverMain()
API: SYSTEM()
Time: 19:43:33 UTC 06/07/2023
Error: Drive /export1, path (.minio.sys/pool.bin) returned an error (file access denied) (*fmt.wrapError)
14: internal/logger/logger.go:259:logger.LogIf()
13: internal/logger/logonce.go:104:logger.(*logOnceType).logOnceIf()
12: internal/logger/logonce.go:135:logger.LogOnceIf()
11: cmd/erasure-object.go:526:cmd.readAllXL()
10: cmd/erasure-object.go:594:cmd.erasureObjects.getObjectFileInfo()
9: cmd/erasure-object.go:220:cmd.erasureObjects.GetObjectNInfo()
8: cmd/erasure-sets.go:932:cmd.(*erasureSets).GetObjectNInfo()
7: cmd/config-common.go:33:cmd.readConfigWithMetadata()
6: cmd/config-common.go:55:cmd.readConfig()
5: cmd/erasure-server-pool-decom.go:399:cmd.(*poolMeta).load()
4: cmd/erasure-server-pool-decom.go:504:cmd.(*erasureServerPools).Init()
3: cmd/erasure-server-pool.go:144:cmd.newErasureServerPools()
2: cmd/server-main.go:700:cmd.newObjectLayer()
1: cmd/server-main.go:534:cmd.serverMain()
ERROR Unable to initialize backend: Prefix access is denied: .minio.sys/pool.bin
```

## Possible Solution

The `file access denied` might point to a permission issue.
Because the container is starting, I do not think that the permission issue is an RBAC issue related to the ClusterRole.

## Steps to Reproduce (for bugs)

1. Deploy an OCP 4.13 cluster.
2. Apply the YAML given in the `Expected Behavior` section.
3. Validate that the `storage-pool-0-0` pod does not start successfully.

## Context

MinIO is deployed by developers on their development clusters.
We're currently working on the migration from OCP 4.12 to OCP 4.13.

## Regression

No.

## Your Environment

* Red Hat OCP 4.13
