### ISSUE TITLE
Helm standalone installation with TLS on OpenShift fails

### ISSUE THREAD

**Issue by razvan** [minio/minio#17432]
## NOTE

Installation of a standalone Minio with TLS enabled fails on OpenShift. Specifically the post job container minio-make-user fails with:

```
minio-make-user mc: <ERROR> Unable to save new mc config. open /etc/minio/mc/$tmpfile.config.json.25775977: permission denied.
```

## Expected Behavior

Installation should be successful.

## Steps to Reproduce (for bugs)

Run the following command:

```
helm install minio \
      --namespace $NAMESPACE \
      --version 5.0.10 \
      --values helm-minio-values.yaml \
      --repo https://charts.min.io/ minio
```
`helm-minio-values.yaml` contents:
```
---
mode: standalone
replicas: 1
persistence:
  enabled: false

buckets:
  - name: mybucket
    policy: none

users:
  - accessKey: miniouser
    secretKey: miniopassword
    policy: readwrite

service:
  type: NodePort

consoleService:
  type: NodePort

securityContext:
  enabled: false

resources:
  requests:
    memory: 1Gi
    cpu: "512m"
  limits:
    memory: "1Gi"
    cpu: "1"

makeBucketJob:
  securityContext:
    enabled: false
  resources:
    requests:
      memory: 128Mi
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "500m"

makeUserJob:
  securityContext:
    enabled: false
  resources:
    requests:
      memory: 128Mi
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "500m"

makePolicyJob:
  securityContext:
    enabled: false
  resources:
    requests:
      memory: 128Mi
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "500m"

makeCustomCommandJob:
  securityContext:
    enabled: false
  resources:
    requests:
      memory: 128Mi
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "500m"

makeServicesAccountJob:
  securityContext:
    enabled: false
  resources:
    requests:
      memory: 128Mi
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "500m"

tls:
  enabled: true
  certSecret: minio-tls-certificates
  publicCrt: tls.crt
  privateKey: tls.key
```

## Your Environment

* Helm chart: 5.0.10
* OpenShift: 4.11.39
