### ISSUE TITLE
specify passive ftp ip address

### ISSUE THREAD

**Issue by AxisNL** [minio/minio#17457]
Hey, I'm trying out minio in docker to perhaps replace an old ftp server, and I see I can specify the passive ftp range. But can I also set the ip address? The docs don't mention it, so I assume it's not in there yet.

When I run minio in docker, using for example this docker-compose.yml file:

version: '3'

```
services:
  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
      - "8021:8021"
      - "30000-30100:30000-30100"
    volumes:
      - /Users/angelo/minio-data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" --ftp="address=:8021" --ftp="passive-port-range=30000-30100" /data

```

I can connect to port 21, but I can't get a directory listing, because the ftp server instructs the client to connect to the inside address of the container, in this case 172.18.0.2 port: 30003:

```
Command:	PWD
Response: 	257 "/" is the current directory
Command:	TYPE I
Response: 	200 Type set to binary
Command:	PASV
Response: 	227 Entering Passive Mode (172,18,0,2,117,51)
Command:	MLSD
```

Which will not work, because my client can't connect to the internal docker network on the host of course.

I could imagine it would be necessary to be able to set something like a --ftp="passive-host-ip=192.168.0.10" option or something?

I don't have that much experience with docker, perhaps the host networking mode is a workaround there, but that doesn't work in everyone's development environment (mac, etc.), and I guess not everyone wants the host mode.

Edit: oh and by the way, it's not limited to docker setups. A lot of people have their ftp server in a DMZ with an internal ip address, and do NATting from the internet. You need to configure the external ip address, or all your remote clients will be shown your internal ip address.

Angelo.
