### ISSUE TITLE
[helm-chart] Race condition when creating users/policies via chart

### ISSUE THREAD

**Issue by fernferret** [minio/minio#17492]
## Expected Behavior

When I install the fresh helm chart, a policy is created, then the user is assigned that policy.

## Current Behavior

I believe this race condition is most common when installing a fresh chart.

If the `minio-make-user` container finishes before `minio-make-policy` a user is created, but no policy is assigned:

```
kubectl logs -n minio minio-post-job-kpq6v -c minio-make-user
Connecting to MinIO server: http://minio:9000
mc: <ERROR> Unable to initialize new alias from the provided credentials. Get "http://minio:9000/probe-bucket-sign-vz1kivnhnzn4/?location=": dial tcp 10.120.143.162:9000: connect: connection refused.
"Failed attempts: 1"
mc: <ERROR> Unable to initialize new alias from the provided credentials. Get "http://minio:9000/probe-bucket-sign-ky499ni4djfc/?location=": dial tcp 10.120.143.162:9000: connect: connection refused.
"Failed attempts: 2"
Added `myminio` successfully.
Creating user 'loki'
Added user `loki` successfully.
Adding policy 'loki' for 'loki'
mc: <ERROR> Unable to make user/group policy association. The canned policy does not exist. (Specified canned policy does not exist).
```

```
kubectl logs -n minio minio-post-job-kpq6v -c minio-make-policy
Connecting to MinIO server: http://minio:9000
mc: <ERROR> Unable to initialize new alias from the provided credentials. Get "http://minio:9000/probe-bucket-sign-kgfkxlxjoz6l/?location=": dial tcp 10.120.143.162:9000: connect: connection refused.
"Failed attempts: 1"
Added `myminio` successfully.
Checking policy: foo:admins (in /config/policy_0.json)
Creating policy 'foo:admins'
Created policy `foo:admins` successfully.
Checking policy: foo/admins (in /config/policy_1.json)
Creating policy 'foo/admins'
Created policy `foo/admins` successfully.
Checking policy: loki (in /config/policy_2.json)
Creating policy 'loki'
Created policy `loki` successfully.
```

When I re-deploy the helm chart, the user's policy is correctly associated!

## Possible Solution

Maybe the job could use `initContainers` to run these jobs serially, so that we always run `minio-make-policy` before `minio-make-user`?

I'm not sure if there is any association between the `minio-make-bucket` and the others.

If you'd like me to open a PR I'm willing to but would want some guidance on the desired behavior of `minio-make-bucket` 🚀 

## Steps to Reproduce (for bugs)

1. Install the minio helm chart `5.0.11` with this values file:
   ```yaml
   rootUser: "admin"
   rootPassword: "admin123"

   fullnameOverride: minio

   # This is my single node instance, run in standalone mode. See foo/minio for the
   # full distributed setup.
   mode: standalone

   securityContext:
     # This is used to auto chown -R /chmod -R the "local" volume. It won't work
     # with "hostPath" types. Without this setting the chown/chmod will happen
     # *every* restart. With OnRootMismatch it will only run when a new volume is
     # setup, like when we delete volumes or move to a new node.
     fsGroupChangePolicy: OnRootMismatch

   persistence:
     enabled: true
     storageClass: "local-path"

   # This is the api ingress. This is where you'll point the "mc" client at.
   ingress:
     enabled: true
     path: /
     hosts:
       - minio.dev.example.com

   resources:
     requests:
       memory: 2Gi

   # This is the web UI. It's only used for humans to manage MinIO.
   consoleIngress:
     enabled: true
     path: /
     hosts:
       - minio-console.dev.example.com

   environment:
     # OIDC Settings
     MINIO_IDENTITY_OPENID_CONFIG_URL: https://dex.dev.example.com/.well-known/openid-configuration
     MINIO_IDENTITY_OPENID_CLIENT_ID: minio
     MINIO_IDENTITY_OPENID_CLAIM_NAME: groups
     # MINIO_IDENTITY_OPENID_CLAIM_PREFIX: ""
     MINIO_IDENTITY_OPENID_SCOPES: openid,profile,email,groups
     MINIO_IDENTITY_OPENID_REDIRECT_URI: https://minio-console.dev.example.com/oauth_callback

   policies:
     - name: foo:admins # GitHub OIDC login
       statements:
         - actions:
             - "admin:*"
         - actions:
             - "s3:*"
           resources:
             - 'arn:aws:s3:::*'
     - name: foo/admins # Gitlab OIDC login
       statements:
         - actions:
             - "admin:*"
         - actions:
             - "s3:*"
           resources:
             - 'arn:aws:s3:::*'
     - name: loki
       statements:
         - actions:
             - "s3:*"
           resources:
             - 'arn:aws:s3:::loki-chunks/*'
             - 'arn:aws:s3:::loki-ruler/*'
             - 'arn:aws:s3:::loki-admin/*'

   users:
     - accessKey: loki
       secretKey: lokiloki
       policy: loki

   buckets:
     # NOTE: These are single-node so I don't specify versioning at all.
     - name: thanos
       policy: none
       purge: false
     - name: loki-chunks
       policy: none
       purge: false
     - name: loki-ruler
       policy: none
       purge: false
     - name: loki-admin
       policy: none
       purge: false
     - name: testa
       policy: none
       purge: false
     - name: testb
       policy: none
       purge: false
     - name: testc
       policy: none
       purge: false
     - name: testd
       policy: none
       purge: false
   ```
2. Check the `loki` user, I used the UI but you could also use `mc` to see it's missing a policy. I believe this is a race condition based on how long containers take to pull, so it might not happen if the stars do or don't align correctly.

## Context

I'm re-installing minio (single node) in my lab and am starting totally from scratch. I noticed this on a fresh install.

Fixing this will help users who are installing MinIO in a lab/dev/preproduction environment re-create instances.

## Regression

I don't think so, I haven't been using the helm chart based policies very long.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

```
bash-4.4$ minio --version
minio version RELEASE.2023-06-19T19-52-50Z (commit-id=f9b8d1c6999e65ab31899cbbe0314f5a4e5257c3)
Runtime: go1.19.10 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2023 MinIO, Inc.
```

configuration attached above (helm chart)

OS: Kubernetes (kubeadm provisioned) 1.26.6, Ubuntu, kernel:

```
uname -r
5.15.0-75-generic
```
