### ISSUE TITLE
XMinioStorageFull but have 3TB (43%) remaining

### ISSUE THREAD

**Issue by richardhundt** [minio/minio#17596]
## NOTE
I'm using a boto3 python client to move data from S3 to Minio. My NVMe has a simple partitioning scheme, with the 7.3T partition mounted on `/`. There's definitely tons of space left:

```
ClientError('An error occurred (XMinioStorageFull) when calling the CreateMultipartUpload operation: Storage backend has reached its minimum free drive threshold. Please delete a few objects to proceed.') 
```

Here's the disk:
```
$ df -h 
Filesystem      Size  Used Avail Use% Mounted on
tmpfs           6,3G  3,0M  6,3G   1% /run
/dev/nvme0n1p2  7,3T  3,0T  4,0T  43% /
tmpfs            32G  482M   31G   2% /dev/shm
tmpfs           5,0M  4,0K  5,0M   1% /run/lock
tmpfs            32G     0   32G   0% /run/qemu
/dev/nvme0n1p1  513M  6,1M  506M   2% /boot/efi
tmpfs           6,3G   12M  6,3G   1% /run/user/1000
```

## Steps to Reproduce (for bugs)

1. upload 4,944,147 objects totalling 1.1TB
2. try to upload more

## Context

I'm running under docker-compose with a local volume. I don't seem to have hit any inode limits as I can still create entries under `$HOME/.local/share/docker/volumes/<name>_minio_data/_data/<bucket>`.

```yaml
# docker-compose.yaml
version: "3"
name: "..."
services:
  minio:
    image: docker.io/minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "minio_data:/data"
volumes:
  minio_data:
    driver: local
```

## Your Environment

* Version used (`minio --version`):
minio version RELEASE.2022-08-13T21-54-44Z (commit-id=49862ba3470335decccecb27649167025e18c406)
Runtime: go1.18.5 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2022 MinIO, Inc.
* Server setup and configuration:
running the official latest Docker image.
* Operating System and version (`uname -a`):
Linux 6fb9db817819 5.19.0-46-generic 47~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 21 15:35:31 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
