### ISSUE TITLE
Dynamic Reload of CA certificates not working and breaking connection with KES - x509: certificate has expired

### ISSUE THREAD

**Issue by Mladen-Karadimov** [minio/minio#17698]
## NOTE
Hello,

I have local setup with minio, kes and cert manager for certifications. We have started experiencing problems every 3 months when cert manager certificates expires as minio loses connection to kes.

```
API: PutObject(bucket=test, object=20230720/.../cat_preview.jpg)
Time: 15:19:12 UTC 07/20/2023
DeploymentID: 163d1a97-fc8a-470c-bdb4-9610e77783e9
RequestID: 17739C7E80B2E6E4
RemoteHost: 10.42.0.146
Host: minio.default.svc.cluster.local:9000
UserAgent: MinIO (linux; amd64) minio-go/v6.0.57
Error: x509: certificate has expired or is not yet valid: current time 2023-07-20T15:19:12Z is after 2023-07-20T15:05:57Z (x509.CertificateInvalidError)
       5: internal/logger/logger.go:258:logger.LogIf()
       4: cmd/api-errors.go:2344:cmd.toAPIErrorCode()
       3: cmd/api-errors.go:2369:cmd.toAPIError()
       2: cmd/object-handlers.go:1851:cmd.objectAPIHandlers.PutObjectHandler()
       1: net/http/server.go:2109:http.HandlerFunc.ServeHTTP()
```

The problem is that when the root certificate expires it's not reloaded in app so the connection to KES is lost as explained above.
The CA is mapped as kubernetes volume from kubernetes secret - visible as a symlink.

## Expected Behavior
Reload the CA certificate from `--certs-dir` when it's rotated.
**OR**
Reload the CA certificate from `MINIO_KMS_KES_CAPATH` when it's rotated.

## Current Behavior
Server cert of minio reloads but not CA :(.

## Steps to Reproduce
In order to test this i have create certificates with expiration 1h, renewal 40 minutes - both server certs and issuer's cert.

```

```yaml
      - name: minio
        image: minio/minio:RELEASE.2023-07-18T17-49-40Z
        command: ["minio"]
        args: ["server", "--certs-dir=/etc/minio-tls", "--console-address=:9001", "/data"]
....
        env:
        - name: MINIO_KMS_KES_CAPATH
          value: "/etc/kes-tls/public.crt"  # tried CA as well
....
        volumeMounts:
        - name: minio-certificate
          mountPath: /etc/minio-tls
          readOnly: true
        - name: kes-certificate
          mountPath: /etc/kes-tls
      volumes:
        - name: kes-certificate
          secret:
            secretName: kes-certificate
            items:
            - key: tls.crt
              path: public.crt
        - name: minio-certificate
          secret:
            secretName: minio-certificate
            items:
            - key: tls.key
              path: private.key
            - key: tls.crt
              path: public.crt
            - key: ca.crt
              path: CAs/ca.crt
```
^ In the above config we have 2 possibilities of loading a refreshed CAs for the requests to KES, but none of them works.
Volumes are attached as `symlinks` and their content changes on every renewal.
```bash
[root@minio-0 minio-tls]# pwd
/etc/minio-tls
[root@minio-0 minio-tls]# ls -lah
total 4.0K
drwxrwxrwt 3 root root  140 Jul 20 16:48 .
drwxr-xr-x 1 root root 4.0K Jul 20 14:11 ..
drwxr-xr-x 3 root root  100 Jul 20 16:48 ..2023_07_20_16_48_10.4242671205
lrwxrwxrwx 1 root root   32 Jul 20 16:48 ..data -> ..2023_07_20_16_48_10.4242671205
lrwxrwxrwx 1 root root   10 Jul 20 14:11 CAs -> ..data/CAs
lrwxrwxrwx 1 root root   18 Jul 20 14:11 private.key -> ..data/private.key
lrwxrwxrwx 1 root root   17 Jul 20 14:11 public.crt -> ..data/public.crt
[root@minio-0 minio-tls]# cd CAs/
[root@minio-0 CAs]# ls -lah
total 4.0K
drwxr-xr-x 2 root root   60 Jul 20 16:48 .
drwxr-xr-x 3 root root  100 Jul 20 16:48 ..
-rw-r--r-- 1 root root 1.1K Jul 20 16:48 ca.crt

#############################
[root@minio-0 kes-tls]# pwd
/etc/kes-tls
[root@minio-0 kes-tls]# ls -lah
total 4.0K
drwxrwxrwt 3 root root  100 Jul 20 16:47 .
drwxr-xr-x 1 root root 4.0K Jul 20 14:11 ..
drwxr-xr-x 2 root root   60 Jul 20 16:47 ..2023_07_20_16_47_05.1214625593
lrwxrwxrwx 1 root root   32 Jul 20 16:47 ..data -> ..2023_07_20_16_47_05.1214625593
lrwxrwxrwx 1 root root   17 Jul 20 14:11 public.crt -> ..data/public.crt
```

## Possible Solution
- https://github.com/minio/minio/blob/master/cmd/common-main.go#L935-L972 - I see here we are ignoring the CA cert changes and only carrying about server cert and key. 
1. Dynamic reload `CAs/` directory like server cert and key. 
2. Dynamic reload of `MINIO_KMS_KES_CAPATH` cert file for connection to kes

## Context
I think this should affect everybody who uses our setup with cert manager.

## Your Environment
* Version used (`minio --version`): RELEASE.2023-07-18T17-49-40Z (tested on RELEASE.2022-10-24T18-35-07Z - same result)
* Server setup and configuration: explained above
* Operating System and version (`uname -a`): ubuntu 20 + k3s.
