### ISSUE TITLE
Helm chart cannot increase dynamic PVC size

### ISSUE THREAD

**Issue by D1StrX** [minio/minio#17761]
## Expected Behavior

Able to increase the PVC size from the helm chart and applying with helm upgrade.

## Current Behavior

`helm upgrade <releasename> -n <namespace> minio/minio  -f values.yml`
Error: UPGRADE FAILED: cannot patch "minio" with kind StatefulSet: StatefulSet.apps "minio" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'ordinals', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden 
## Steps to Reproduce (for bugs)

1. Deploy helm chart with dynamic pvc provisioning (change size to bigger size (5Gi -> 10Gi))
```yaml
...
persistence:
  enabled: true
  annotations: {}
  existingClaim: ""
  storageClass: "<csi-driver>"
  volumeName: ""
  accessMode: ReadWriteOnce
  size: 5Gi # change this size from 5Gi to eg 10Gi

  ## If subPath is set mount a sub folder of a volume instead of the root of the volume.
  ## This is especially handy for volume plugins that don't natively support sub mounting (like glusterfs).
  ##
  subPath: ""
...
```
2. `helm upgrade <releasename> -n <namespace> minio/minio  -f values.yml`

## Context

Needs to expand the size of the Tenant.

## Regression

No

## Your Environment

* Version used (`minio --version`):  minio-5.0.13            RELEASE.2023-07-07T07-13-57Z
* Server setup and configuration: Helm v3
* Operating System and version (`uname -a`): K8s
