### ISSUE TITLE
"The following environment variables are unknown: MINIO_IDENTITY_LDAP_USER_DN_SEARCH_BA" while setup LDAP

### ISSUE THREAD

**Issue by sKuhLight** [minio/minio#17836]
## Expected Behavior
If I setup LDAP via minio webUI or docker it should just work.

## Current Behavior
If i set up LDAP via minio webUI i get the error message "The following environment variables are unknown: MINIO_IDENTITY_LDAP_USER_DN_SEARCH_BA" on save.
I run minIO in docker and also tried to set it via environment variables like this:
```- MINIO_IDENTITY_LDAP_SERVER_ADDR="192.168.44.10:389"
- MINIO_IDENTITY_LDAP_LOOKUP_BIND_DN="CN=LDAP minio,OU=Dienstkonten,OU=Woob,DC=Woob,DC=rz"
- MINIO_IDENTITY_LDAP_LOOKUP_BIND_PASSWORD="1234"
- MINIO_IDENTITY_LDAP_USER_DN_SEARCH_BASE="DC=Woob,DC=rz"      
- MINIO_IDENTITY_LDAP_USER_DN_SEARCH_FILTER="(|(sAMAccountName=%s)(userPrincipalName=%s))"
- MINIO_IDENTITY_LDAP_GROUP_SEARCH_BASE_DN="CN=Entwicklung,OU=Gruppen,OU=Woob,DC=Woob,DC=rz"
- MINIO_IDENTITY_LDAP_GROUP_SEARCH_FILTER="(member={0})"
- MINIO_IDENTITY_LDAP_TLS_SKIP_VERIFY="on"
- MINIO_IDENTITY_LDAP_SERVER_INSECURE="on"
```
In this case the LDAP configuration is still empty if I access the WebUI.
I tried it with and without the environment variables set.

## Your Environment

* Version used (`minio --version`): 2023-07-21T21:12:44Z
* Server setup and configuration: Docker Compose on Debian
* heres the part of my docker compose file
```
  minio:
    image: minio/minio
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /data/loki-data && \
        mkdir -p /data/loki-ruler &&
        minio server /data --console-address ":9001" 
    environment:
      - MINIO_ROOT_USER=loki
      - MINIO_ROOT_PASSWORD=1234
      - MINIO_PROMETHEUS_AUTH_TYPE=public
      - MINIO_UPDATE=off
      - MINIO_IDENTITY_LDAP_SERVER_ADDR="192.168.1.10:389"
      - MINIO_IDENTITY_LDAP_LOOKUP_BIND_DN="CN=LDAP a,OU=Dienstkonten,OU=aa,DC=a,DC=rz"
      - MINIO_IDENTITY_LDAP_LOOKUP_BIND_PASSWORD="/"
      - MINIO_IDENTITY_LDAP_USER_DN_SEARCH_BASE="DC=aa,DC=rz"      
      - MINIO_IDENTITY_LDAP_USER_DN_SEARCH_FILTER="(|(sAMAccountName=%s)(userPrincipalName=%s))"
      - MINIO_IDENTITY_LDAP_GROUP_SEARCH_BASE_DN="CN=Entwicklung,OU=Gruppen,OU=aa,DC=aa,DC=rz"
      - MINIO_IDENTITY_LDAP_GROUP_SEARCH_FILTER="(member={0})"
      - MINIO_IDENTITY_LDAP_TLS_SKIP_VERIFY="on"
      - MINIO_IDENTITY_LDAP_SERVER_INSECURE="on"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./.data/minio:/data
    networks:
      - loki
```
