### ISSUE TITLE
When I removed the "s3:PutObject" from the Policy and clicked to enter the bucket, the page rendering was abnormal

### ISSUE THREAD

**Issue by xingchenxuup** [minio/minio#17846]
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListAllMyBuckets"
            ],
            "Resource": [
                "arn:aws:s3:::*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetBucketLocation",
                "s3:GetBucketPolicyStatus",
                "s3:GetBucketTagging",
                "s3:HeadBucket",
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::mytestbucket",
                "arn:aws:s3:::mytestbucket/*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetObject",
                "s3:PutObject"
            ],
            "Resource": [
                "arn:aws:s3:::mytestbucket/*"
            ]
        }
    ]
}
```
I can open the page correctly when I haven't deleted "s3:PutObject"
![image](https://github.com/minio/console/assets/76467253/dc6c8a93-f055-42ec-b447-539b63ea66e3)

After I remove "s3:PutObject", click to enter the bucket as shown in the following figure
![image](https://github.com/minio/console/assets/76467253/ee3978a3-c84a-4211-8249-a3648fe75743)

Here is my mini version information
The version is the latest version pulled from the dockerhub
```yaml

version: "3.5"
services:
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./minio/data:/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio2023
      - MINIO_SERVER_URL=http://192.168.1.8:9000
      
 ```
