### ISSUE TITLE
Updating the MINIO_SERVER_URL to actual dns is resulting in failure in loading the web console

### ISSUE THREAD

**Issue by priyakavalii** [minio/minio#17848]
Updating the MINIO_SERVER_URL to actual DNS is resulting in the failure in loading the web console, console login error says **S3 API Requests must be made to API port**

## Expected Behavior

console login should work without any issues.

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2022-12-07T00-56-37Z (commit-id=04ae9058ed5b135c27a3662b1153e129e5cf1483)
* Server setup and configuration: 

```
  minio:
    image: minio/minio
    restart: always
    container_name: minio
    labels:
      - traefik.enable=true
      - traefik.http.routers.console.entrypoints=https
      - traefik.http.routers.console.rule=Host(`storage.app`)
      - traefik.http.routers.console.tls=true
      - traefik.http.routers.console.tls.certresolver=letsencrypt
      - traefik.http.routers.console.service=console
      - traefik.http.services.console.loadbalancer.server.port=9001

      - traefik.http.routers.api.entrypoints=https2
      - traefik.http.routers.api.rule=Host(`storage.app`)
      - traefik.http.routers.api.tls=true
      - traefik.http.routers.api.tls.certresolver=letsencrypt
      - traefik.http.routers.api.service=api
      - traefik.http.services.api.loadbalancer.server.port=9000

    command: minio server /data --console-address :9001
    environment:
       MINIO_SERVER_URL: https://storage.app
```

* Operating System and version (`uname -a`): Docker Image
