### ISSUE TITLE
Lifecycle is inactive in MinIO Console

### ISSUE THREAD

**Issue by milad2golnia** [minio/minio#17959]
Lifecycle tab in MinIO console is grayed out as you can see below:
![image](https://github.com/minio/minio/assets/30959658/4bba459d-890c-47ea-b5e0-a03bccb0b063)
I searched a lot among the documentation to find out why it is grayed out but I didn't find anything, can you please refer me to a documentation about how to activate it?
I just find the comment of a user in Reddit who was suggesting it is so because I'm started MinIO in stand alone mode. Is it correct?
Also another user in same discussion suggested that it is just inaccessible through the Console but we can use its functionality through 'mc' or **[Javascript SDK](https://min.io/docs/minio/linux/developers/javascript/API.html)**?
## Expected Behavior
I should be able to click on Lifecycle tab.
If Lifecycle is not accessible at least following line of [Javascript SDK](https://min.io/docs/minio/linux/developers/javascript/API.html) should raise an error instead of returning normally:
```
      await this.minioClient.setBucketLifecycle(tempBucketName, {
        Rule: [
          {
            ID: 'Delete not used temporary files',
            Status: 'Enabled',
            Filter: {
              Prefix: '',
            },
            Expiration: {
              Days: `1`,
            },
          },
        ],
      });
    }
```

## Current Behavior
It is grayed out and disabled.
Also `setBucketLifecycle` function of [Javascript SDK](https://min.io/docs/minio/linux/developers/javascript/API.html) returns normally instead of raising an error.
## Possible Solution
There are 3 possible solutions:
1. It should be active for Deletion of objects because deletion process doesn't need Distributed Mode.
2. Add documentation about it and tell users that it is not available in stand-alone mode and they should activate Distributed mode even for Expiry feature. Also you should specify that is it completely unavailable or it is just inaccessible thorough Console?
3. `setBucketLifecycle` function of [Javascript SDK](https://min.io/docs/minio/linux/developers/javascript/API.html) should raise an error with obvious reason instead of just returning normally.
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

Here is how I deployed MinIO:
```
services:
minio1:
    image: quay.io/minio/minio:RELEASE.2022-05-19T18-20-59Z
    ports: 
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: ****
      MINIO_ROOT_PASSWORD: ****
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - data1:/data 
    command: server --console-address ":9001" /data
```

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2022-05-19T18-20-59Z
* Server setup and configuration: Mentioned earlier
* Operating System and version (`uname -a`): Linux d244d9882f42 5.15.0-46-generic #49-Ubuntu SMP Thu Aug 4 18:03:25 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
