### ISSUE TITLE
Minio doesn't write anything to /data directory

### ISSUE THREAD

**Issue by iQiexie** [minio/minio#18022]
When bring down the minio container with `docker-compose down` command and then start the minio container again with the `docker-compose up --build` command, all the data (buckets, for example) is gone. I fugured that it happens because minio doesn't write anything to /data directory inside the container

## Expected Behavior
The data expected to persist after container restart

## Current Behavior
Data deletes and when running minio nothing is written into /data directory

## Steps to Reproduce (for bugs)
create a `docker-comcpose.yaml` file with the following content:

```
version: "3"

services:
  blueberry-minio:
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    container_name: blueberry-minio
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    image: bitnami/minio:latest
    env_file:
      - ../.env  # MINIO_ROOT_USER, MINIO_ROOT_PASSWORD
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio-data:/data

volumes:
  minio-data:
```

1.  Start minio with `docker compose up`
2. Navigate to http://localhost:9001/ and create a bucket
3. Veryfy that /data is empty: `docker exec blueberry-minio ls /data`
4. Restart minio with `docker compose down && docker compose up`
5. Navigate to http://localhost:9001/buckets and see that there're no buckets

## Your Environment
```
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy
```

```
Runtime: go1.20.8 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2023 MinIO, Inc.
```

```
Linux zerolab 5.15.0-75-generic #82-Ubuntu SMP Tue Jun 6 23:10:23 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```
