### ISSUE TITLE
MinIO Community Helm Chart - MINIO_IDENTITY_OPENID_REDIRECT_URI not set

### ISSUE THREAD

**Issue by michaelsatish** [minio/minio#18234]
## Expected Behavior
Setting the redirect uri as part of helm install should create the environmental variable `MINIO_IDENTITY_OPENID_REDIRECT_URI`

```yaml
oidc:
  ...
  redirectUri: "https://<custom domain>/oauth_callback"
```

## Current Behavior
The environmental variable in question is not seen on the pod.

![image](https://github.com/minio/minio/assets/20645040/2536be9d-a9e6-4acf-a750-cf56ca071a3b)

## Possible Solution
Update the deployment template to include the following. This is missing.
```yaml
 {{- if .Values.oidc.enabled }}
    - name: MINIO_IDENTITY_OPENID_REDIRECT_URI
      value: {{ .Values.oidc.redirectUri }}
````

## Your Environment
Minio image: RELEASE.2023-10-07T15-07-38Z
Helm chart version: 5.0.14
