### ISSUE TITLE
Helm: Trying to start standalone with single replica and nfs volume

### ISSUE THREAD

**Issue by hardillb** [minio/minio#18337]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior

I expect the helm chart to deploy cleanly and the application to run

## Current Behavior

Minio container fails to start with the following error:

```
kubectl -n minio logs pod/minio-5b6b999d48-v9mf4
Formatting 1st pool, 1 set(s), 1 drives per set.
WARNING: Host local has more than 0 drives of set. A host failure will result in data becoming unavailable.
Formatting 1st pool, 1 set(s), 1 drives per set.
WARNING: Host local has more than 0 drives of set. A host failure will result in data becoming unavailable.
ERROR Unable to initialize backend: drive not found
```

## Steps to Reproduce (for bugs)

1. Add helm chart `helm repo add minio https://charts.min.io/`
2. Install with `helm install --namespace minio minio minio/minio -f values.yml`
3. where `values.yml`
    ```yaml
    rootUser: root
    rootPassword: password
    environment:
      MINIO_DOMAIN: s3.public.domain.com,s3.k8s.loc
    persistence:
      enabled: true
    replicas: 1
    mode: standalone
    resources:
      requests:
        memory: 512Mi
    ingress:
      enabled: true
      hosts:
        - "*.s3.public.domain.com"
        - "*.s3.k8s.loc"
    consoleIngress:
      enabled: true
      hosts:
        - "minio.k8s.loc"
    ```

Default nfs storage class is marked as default and volumes are provisioned correctly

## Context

I can't use minio for local projects

## Regression

NA

## Your Environment

* Version used (`minio --version`): What ever the helm chart installs (container tag RELEASE.2023-09-30T07-02-29Z)
* Server setup and configuration: microk8s
* Operating System and version (`uname -a`): host os for K8s Ubuntu 20.04
