### ISSUE TITLE
Can't login console for admin user after upgrading Minio version

### ISSUE THREAD

**Issue by rensongqi** [minio/minio#18366]
## NOTE
Minio was upgraded from version `RELEASE.2022-08-25T07-17-05Z` to `RELEASE.2023-10-24T04-42-36Z`. At the same time I changed the `MINIO_ROOT_PASSWORD` variable. After restarting the Minio service I can't log in to the minio console using the admin user, but the common user is able to login.

## Expected Behavior
admin user can login successfully.

## Current Behavior
admin user failed to login console. err: `invalid session`
![image](https://github.com/minio/minio/assets/49969527/73a0a908-7148-4caa-b021-12ae2cd211b5)

The minio server reports the following error message:
```
API: SYSTEM()
Time: 11:45:02 UTC 11/01/2023
DeploymentID: 6ceb2766-7648-4c40-8c67-f1f94eac329d
Error: The TagKey you have provided is invalid (*tags.errTag)
       5: internal/logger/logger.go:258:logger.LogIf()
       4: internal/logger/logger.go:388:logger.CriticalIf()
       3: cmd/bucket-object-lock.go:47:cmd.(*BucketObjectLockSys).Get()
       2: cmd/admin-handlers-users.go:1391:cmd.adminAPIHandlers.AccountInfoHandler()
       1: net/http/server.go:2136:http.HandlerFunc.ServeHTTP()
critical: "GET /minio/admin/v3/accountinfo": {}
goroutine 5759482 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x5e
github.com/minio/minio/cmd.serverMain.func7.setCriticalErrorHandler.func2.1()
        github.com/minio/minio/cmd/generic-handlers.go:545 +0x2cf
panic({0x265e1c0?, 0x610c320?})
        runtime/panic.go:914 +0x21f
github.com/minio/minio/internal/logger.CriticalIf(...)
        github.com/minio/minio/internal/logger/logger.go:389
github.com/minio/minio/cmd.(*BucketObjectLockSys).Get(0x26b4ae0?, {0xc027903a28, 0x10})
        github.com/minio/minio/cmd/bucket-object-lock.go:47 +0x14c
github.com/minio/minio/cmd.adminAPIHandlers.AccountInfoHandler({}, {0x4a7f180, 0xc01371f3f8}, 0xc00cc67700)
        github.com/minio/minio/cmd/admin-handlers-users.go:1391 +0x14b2
net/http.HandlerFunc.ServeHTTP(0x50f2b14?, {0x4a7f180?, 0xc01371f3f8?}, 0x4aaf898?)
        net/http/server.go:2136 +0x29
github.com/minio/minio/cmd.adminMiddleware.func1.httpTraceAll.httpTrace.func1({0x4a7f180, 0xc01371f3f8}, 0xc01371f3f8?)
        github.com/minio/minio/cmd/http-tracer.go:188 +0xef
github.com/minio/minio/cmd.adminMiddleware.func1({0x4a7f180, 0xc01371f3f8}, 0xc00cc67600)
        github.com/minio/minio/cmd/admin-router.go:132 +0x2df
net/http.HandlerFunc.ServeHTTP(0x604dfa0?, {0x4a7f180?, 0xc01371f3f8?}, 0x4?)
        net/http/server.go:2136 +0x29
github.com/klauspost/compress/gzhttp.NewWrapper.func1.1({0x4a7e8b0, 0xc00faa8d10}, 0x1b?)
        github.com/klauspost/compress@v1.17.0/gzhttp/compress.go:492 +0x4fc
net/http.HandlerFunc.ServeHTTP(0xc01756be60?, {0x4a7e8b0?, 0xc00faa8d10?}, 0x0?)
        net/http/server.go:2136 +0x29
github.com/minio/minio/cmd.setBucketForwardingMiddleware.func1({0x4a7e8b0, 0xc00faa8d10}, 0xc00cc67600)
        github.com/minio/minio/cmd/generic-handlers.go:455 +0x294
net/http.HandlerFunc.ServeHTTP(0xc014480000?, {0x4a7e8b0?, 0xc00faa8d10?}, 0xc00cb1c140?)
        net/http/server.go:2136 +0x29
github.com/minio/minio/cmd.setUploadForwardingMiddleware.func1({0x4a7e8b0, 0xc00faa8d10}, 0xc00cc67600)
        github.com/minio/minio/cmd/generic-handlers.go:568 +0x18e
net/http.HandlerFunc.ServeHTTP(0x29e9c20?, {0x4a7e8b0?, 0xc00faa8d10?}, 0x39?)
        net/http/server.go:2136 +0x29
github.com/minio/minio/cmd.setRequestValidityMiddleware.func1({0x4a7e8b0?, 0xc00faa8d10}, 0xc00cc67600)
        github.com/minio/minio/cmd/generic-handlers.go:438 +0x162d
net/http.HandlerFunc.ServeHTTP(0xc01756bf20?, {0x4a7e8b0?, 0xc00faa8d10?}, 0x1?)
        net/http/server.go:2136 +0x29
github.com/minio/minio/cmd.setRequestLimitMiddleware.func1({0x4a7e8b0?, 0xc00faa8d10}, 0xc00cc67600)
        github.com/minio/minio/cmd/generic-handlers.go:133 +0x662
net/http.HandlerFunc.ServeHTTP(0x2af79ef?, {0x4a7e8b0?, 0xc00faa8d10?}, 0x218748b?)
        net/http/server.go:2136 +0x29
github.com/minio/minio/cmd.setCrossDomainPolicyMiddleware.func1({0x4a7e8b0?, 0xc00faa8d10?}, 0x6?)
        github.com/minio/minio/cmd/crossdomain-xml-handler.go:42 +0xf1
net/http.HandlerFunc.ServeHTTP(0xc00cc67600?, {0x4a7e8b0?, 0xc00faa8d10?}, 0xc01d7a3990?)
        net/http/server.go:2136 +0x29
github.com/minio/minio/cmd.setBrowserRedirectMiddleware.func1({0x4a7e8b0, 0xc00faa8d10}, 0xc00cc67600)
        github.com/minio/minio/cmd/generic-handlers.go:163 +0x17c
net/http.HandlerFunc.ServeHTTP(0x0?, {0x4a7e8b0?, 0xc00faa8d10?}, 0x5d85720?)
        net/http/server.go:2136 +0x29
github.com/minio/minio/cmd.setAuthMiddleware.func1({0x4a7e8b0, 0xc00faa8d10}, 0xc00cc67600)
        github.com/minio/minio/cmd/auth-handler.go:636 +0x6a2
net/http.HandlerFunc.ServeHTTP(0x4a84a98?, {0x4a7e8b0?, 0xc00faa8d10?}, 0x4a5e360?)
        net/http/server.go:2136 +0x29
github.com/minio/minio/cmd.httpTracerMiddleware.func1({0x4a7ee20, 0xc00153dce0}, 0xc00cc67500)
        github.com/minio/minio/cmd/http-tracer.go:88 +0x3b4
net/http.HandlerFunc.ServeHTTP(0x28b5240?, {0x4a7ee20?, 0xc00153dce0?}, 0xa?)
        net/http/server.go:2136 +0x29
github.com/minio/minio/cmd.addCustomHeadersMiddleware.func1({0x4a7ee20, 0xc00153dce0}, 0xc01756bec0?)
        github.com/minio/minio/cmd/generic-handlers.go:533 +0x438
net/http.HandlerFunc.ServeHTTP(0xc00cc67400?, {0x4a7ee20?, 0xc00153dce0?}, 0x69c9df?)
        net/http/server.go:2136 +0x29
github.com/minio/mux.(*Router).ServeHTTP(0xc0012c89c0, {0x4a7ee20, 0xc00153dce0}, 0xc00cc67400)
        github.com/minio/mux@v1.9.0/mux.go:214 +0x1f7
github.com/minio/minio/cmd.corsHandler.(*Cors).Handler.func2({0x4a7ee20, 0xc00153dce0}, 0xc00cc67400)
        github.com/rs/cors@v1.10.0/cors.go:279 +0x184
net/http.HandlerFunc.ServeHTTP(0xc00cb1daa0?, {0x4a7ee20?, 0xc00153dce0?}, 0x0?)
        net/http/server.go:2136 +0x29
github.com/minio/minio/cmd.serverMain.func7.setCriticalErrorHandler.func2({0x4a7ee20?, 0xc00153dce0?}, 0xc012e004d0?)
        github.com/minio/minio/cmd/generic-handlers.go:557 +0x78
net/http.HandlerFunc.ServeHTTP(0x278aa40?, {0x4a7ee20?, 0xc00153dce0?}, 0x7f13754e4480?)
        net/http/server.go:2136 +0x29
github.com/minio/minio/internal/http.(*Server).Init.func1({0x4a7ee20?, 0xc00153dce0?}, 0xc01275c000?)
        github.com/minio/minio/internal/http/server.go:123 +0x19c
net/http.HandlerFunc.ServeHTTP(0x610c320?, {0x4a7ee20?, 0xc00153dce0?}, 0xc00cb1db50?)
        net/http/server.go:2136 +0x29
net/http.serverHandler.ServeHTTP({0xc022736f90?}, {0x4a7ee20?, 0xc00153dce0?}, 0x6?)
        net/http/server.go:2938 +0x8e
net/http.(*conn).serve(0xc00f9d5a70, {0x4a84a98, 0xc0015c3cb0})
        net/http/server.go:2009 +0x5f4
created by net/http.(*Server).Serve in goroutine 194
        net/http/server.go:3086 +0x5cb
```

I've tried using Chrome and FireFox but it does not work!

## Steps to Reproduce (for bugs)
1. Changed the `image` field of docker-compose.yml to the new version of the image
2. Changed the `MINIO_ROOT_PASSWORD` variable
3. Save the docker-compose.yml file and exec `docker-compose up -d` command 

## Regression
No

## Your Environment
* Version used (`minio --version`):
```
minio version RELEASE.2023-10-24T04-42-36Z (commit-id=2dc917e87f12166e4cfc3b1be24cf2bf70b29bbd)
Runtime: go1.21.3 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2023 MinIO, Inc.
```
* Server setup and configuration:
```
Minio services deployed using docker-compose: Docker version: 22.06.0-beta.0
```
Minio Server Environment:
```
MINIO_ACCESS_KEY_FILE=access_key
LANG=C.utf8
TZ=Asia/Shanghai
HOSTNAME=minio1
MINIO_KMS_SECRET_KEY_FILE=kms_master_key
MINIO_ROOT_USER=admin
container=oci
PWD=/
HOME=/root
TERM=xterm
MINIO_ROOT_USER_FILE=access_key
MINIO_ROOT_PASSWORD=miniopass
MINIO_ROOT_PASSWORD_FILE=secret_key
SHLVL=1
MINIO_DOMAIN=ossapi.cowarobot.cn
MINIO_UPDATE_MINISIGN_PUBKEY=RWTx5Zr1tiHQLwG9keckT0c45M3AGeHD6IvimQHpyRywVWGbP1aVSGav
MINIO_SECRET_KEY_FILE=secret_key
PATH=/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
MINIO_CONFIG_ENV_FILE=config.env
_=/usr/bin/env
```
docker-compose.yml:
```yml
version: '3.7'

x-minio-common: &minio-common
  #image: "harbor.cowarobot.cn/minio/minio:RELEASE.2022-08-25T07-17-05Z"
  image: "harbor.cowarobot.cn/library/minio/minio:RELEASE.2023-10-24T04-42-36Z"
  command: server --console-address ":9001" http://minio{1...3}/data{0...5}
  expose:
    - "9000"
    - "9001"

  extra_hosts:
    minio1: 172.17.1.107
    minio2: 172.17.1.108
    minio3: 172.17.1.109
  depends_on:
    - nginx
  environment:
    MINIO_ROOT_USER: admin
    MINIO_ROOT_PASSWORD: miniopass
    MINIO_DOMAIN: ossapi.cowarobot.cn
    #MINIO_STORAGE_CLASS_STANDARD: "EC:3"
    #MINIO_STORAGE_CLASS_RRS: "EC:2"
    TZ: Asia/Shanghai
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 5

services:
  minio1:
    <<: *minio-common
    container_name: minio1
    hostname: minio1
    volumes:
      - /minio0:/data0
      - /minio1:/data1
      - /minio2:/data2
      - /minio3:/data3
      - /minio4:/data4
      - /minio5:/data5
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: always
    network_mode: host

  minio2:
    <<: *minio-common
    container_name: minio2
    hostname: minio2
    volumes:
      - /minio0:/data0
      - /minio1:/data1
      - /minio2:/data2
      - /minio3:/data3
      - /minio4:/data4
      - /minio5:/data5
    ports:
      - "9000:9000"
      - "9001:9001"

  minio3:
    <<: *minio-common
    container_name: minio3
    hostname: minio3
    volumes:
      - /minio0:/data0
      - /minio1:/data1
      - /minio2:/data2
      - /minio3:/data3
      - /minio4:/data4
      - /minio5:/data5
    ports:
      - "9000:9000"
      - "9001:9001"

  nginx:
    image: "harbor.cowarobot.cn/library/nginx:1.19.2-alpine"
    container_name: nginx-minio
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "30009:9000"
      - "30099:9001"
    extra_hosts:
      minio1: 172.16.100.107
      minio2: 172.16.100.108
      minio3: 172.16.100.109
```

* Operating System and version (`uname -a`):
```
Linux shjdpelk01 3.10.0-1160.71.1.el7.x86_64 #1 SMP Tue Jun 28 15:37:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
