### ISSUE TITLE
`curl` no longer available in container image, can no longer healthcheck

### ISSUE THREAD

**Issue by andrewazores** [minio/minio#18371]
## Expected Behavior
Minio images previously had `curl` on the `$PATH`, which was very useful for defining container healthchecks with ex. docker/podman.

## Current Behavior
`curl` is no longer on the `$PATH`, so existing healthcheck definitions now fail and the container health is erroneously deemed unhealthy, leading to restarts or failed deployments.

## Steps to Reproduce (for bugs)
See https://github.com/andrewazores/minio-healthcheck-reproducer

## Context
I use Minio as an S3 implementation in a development/smoketest environment using docker-compose. Being able to define a healthcheck for the service is important for obvious reasons, and it's normal for the healthchecks to be run by exec-ing a process within the container.

## Regression
Yes, I believe due to https://github.com/minio/minio/pull/18329

## Your Environment
* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

```bash
# minio --version
minio version RELEASE.2023-11-01T01-57-10Z (commit-id=55e713db0a367f6cccee00af49f00c269e6ca619)
Runtime: go1.21.3 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2023 MinIO, Inc.
```

```bash
$ docker-compose --version
docker-compose version 1.29.2, build unknown
$ uname -r
6.5.7-200.fc38.x86_64
$ podman --version
podman version 4.7.0
$ echo $DOCKER_HOST
unix:///run/user/1001/podman/podman.sock
```

**Comment by andrewazores** [comment]
After #18370 I guess the fix/workaround would be to replace `curl` healthchecks with something using `mc` instead?

**Comment by harshavardhana** [comment]
curl cannot be added unfortunately back to the container, you should use different healthcheck mechanisms. 

These health checks are wrong - these are not doing anything for you other than verify if port is available or not. 

```
    healthcheck:
      test: curl --fail http://localhost:9001 || exit 1
      interval: 5s
      retries: 1
      start_period: 5s
      timeout: 5s
```

If you still want to do this naive way to manage containers

```
    healthcheck:
      test: timeout 5s bash -c ':> /dev/tcp/127.0.0.1/9081' || exit 1
      interval: 5s
      retries: 1
      start_period: 5s
      timeout: 5s
```
