### ISSUE TITLE
docker compose healthcheck no longer works

### ISSUE THREAD

**Issue by zebehringer** [minio/minio#18372]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

We have a docker compose file defining a container with the minio/minio:latest image, along with this healthcheck section
```
    healthcheck:
      test: curl -f http://localhost:9000/minio/health/live
      interval: 1s
      timeout: 5s
      retries: 30
```
## Expected Behavior

the container should report as healthy fairly quickly

## Current Behavior

the container fails to report healthy after ~30s, resulting in unhealthy

## Steps to Reproduce (for bugs)

1. create a docker-compose.yaml file with this conten
```
services:
  minio:
    image: minio/minio:RELEASE.2023-10-24T04-42-36Z
    entrypoint: sh
    command:
      -c 'mkdir -p /data/sis-api-production && mkdir -p /data/reports && minio
      server --console-address :9001 /data'
    ports:
      - 80:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password
    healthcheck:
      test: curl -f http://localhost:9000/minio/health/live
      interval: 1s
      timeout: 5s
      retries: 30
```
2. run `docker compose up -d`
3. after 30 seconds run `docker ps` | grep minio`

## Context

We use minio in our CI pipelines, which are currently failing

## Regression
Is this issue a regression? Yes (imo)
It started on Nov 1. Pinning the last release (RELEASE.2023-10-24T04-42-36Z) gets us past the problem

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
curl cannot be added unfortunately back to the container, you should use different healthcheck mechanisms. 

These health checks are wrong - these are not doing anything for you other than verify if port is available or not. 

```
    healthcheck:
      test: curl --fail http://localhost:9001 || exit 1
      interval: 5s
      retries: 1
      start_period: 5s
      timeout: 5s
```

If you still want to do this naive way to manage containers

```
    healthcheck:
      test: timeout 5s bash -c ':> /dev/tcp/127.0.0.1/9081' || exit 1
      interval: 5s
      retries: 1
      start_period: 5s
      timeout: 5s
```

Closing as duplicate of #18371
