### ISSUE TITLE
MINIO_USERNAME env var not working in latest release (groupadd command not found)

### ISSUE THREAD

**Issue by pechanuda** [minio/minio#18380]
From version: `RELEASE.2023-11-01T18-37-25Z ` and `RELEASE.2023-11-01T01-57-10Z`

## Expected Behavior
User can be added with ENV VARS `MINIO_USERNAME`, `MINIO_GROUPNAME`

## Current Behavior
Attempt to add user with variables ends up with failure:
```
minio_1  | /usr/bin/docker-entrypoint.sh: line 18: groupadd: command not found
minio_1  | /usr/bin/docker-entrypoint.sh: line 21: exec: setpriv: not found
```

## Possible Solution
N/A

## Steps to Reproduce (for bugs)
run following docker-compose.yaml:
```
version: '3'
services:
  minio:
    ### last one working with groupadd / useradd working
    # image: quay.io/minio/minio:RELEASE.2023-10-25T06-33-25Z
    ### latest
    image: quay.io/minio/minio:RELEASE.2023-11-01T18-37-25Z
    volumes:
      - ./data:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: 'minio_user'
      MINIO_ROOT_PASSWORD: 'minio_password'
      MINIO_ADDRESS: ':9000'
      MINIO_CONSOLE_ADDRESS: ':9001'
      MINIO_USERNAME: 'test-user'
      MINIO_GROUPNAME: 'test-user'
    command: minio server /data
```

## Context
- I'm using image which is adding the user and then running the server with it
## Regression
Yes
(last working version: `RELEASE.2023-10-25T06-33-25Z`)

## Your Environment
- see Steps to reproduce
