### ISSUE TITLE
presign not work after upgrade

### ISSUE THREAD

**Issue by nanamicat** [minio/minio#18510]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior

presign works

## Current Behavior

After upgrade minio from `RELEASE.2021-06-17T00-10-46Z` to `RELEASE.2023-11-20T22-40-07Z`, presign request return `400 Bad Request`.

## Steps to Reproduce (for bugs)

1. minio server on non-standard port.
2. create presign url using JavaScript `@aws-sdk/s3-client`, `PUTObject` Command
3. request this url.

## Context

I've noticed #14709 saying aws s3 sdk does not include :port in signed host, but I checked its code and ensure the :port is included
and it works well with older version minio server.
```javascript
{
  method: 'PUT',
  hostname: 'lolo-pt.minio.mycard.moe',
  port: 9002,
  body: undefined,
  protocol: 'https:',
  path: '/a1e03049-ad40-4dff-b2b6-36da272fb7ba.unitypackage',
  username: undefined,
  password: undefined,
  fragment: undefined,
  headers: {
    'content-type': 'application/octet-stream',
    host: 'lolo-pt.minio.mycard.moe:9002',
    'user-agent': 'aws-sdk-js/3.451.0 ua/2.0 os/linux#6.1.0-13-amd64 lang/js md/nodejs#20.9.0 api/s3#3.451.0'
  },
  query: {
    'x-id': 'PutObject',
    'X-Amz-Content-Sha256': 'UNSIGNED-PAYLOAD',
    'X-Amz-Algorithm': 'AWS4-HMAC-SHA256',
    'X-Amz-Credential': '*****/20231122/us-west-1/s3/aws4_request',
    'X-Amz-Date': '20231122T183008Z',
    'X-Amz-Expires': '86400',
    'X-Amz-SignedHeaders': 'host',
    'X-Amz-Signature': '686771599f764e3dd88793f425d098fdeb982a0b8b1a0885421894828372758b'
  }
}
```

## Your Environment

* Version used (`minio --version`):
`RELEASE.2023-11-20T22-40-07Z`
* Server setup and configuration:
```yaml
  minio2:
    restart: always
    image: quay.io/minio/minio:RELEASE.2023-11-20T22-40-07Z
    command: server --address ":443" /data --console-address ":9001"
    ports:
      - 9001:9001
      - 9002:443
    environment:
      MINIO_ROOT_USER: ***
      MINIO_ROOT_PASSWORD: ***
    volumes:
      - /data2/minio/data:/data
      - /root/certs/***/fullchain.pem:/root/.minio/certs/public.crt:ro
      - /root/certs/***/privkey.pem:/root/.minio/certs/private.key:ro
```
* Operating System and version (`uname -a`):
`Linux minio 6.0.5-x64v1-xanmod1 #0~20221026.git15d787e SMP PREEMPT_DYNAMIC Wed Oct 26 15:19:36 U x86_64 GNU/Linux`
