### ISSUE TITLE
Get panic after upgrade to RELEASE.2023-12-02T10-51-33Z

### ISSUE THREAD

**Issue by elct9620** [minio/minio#18602]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior

The MinIO server runs correctly.

## Current Behavior

Every 3 ~ 5 seconds raises a panic and the server is restarted.

## Steps to Reproduce (for bugs)

1. Run 2 site using `docker-compose up` in version `RELEASE.2023-11-20T22-40-07Z`
2. Setup site replicate mode
3. Upgrade to `RELEASE.2023-12-02T10-51-33Z`

## Context

The error logs
```
minio-next-1  | Cluster replication initialized
minio-next-1  | MinIO Object Storage Server
minio-next-1  | Copyright: 2015-2023 MinIO, Inc.
minio-next-1  | License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
minio-next-1  | Version: RELEASE.2023-12-02T10-51-33Z (go1.21.4 linux/amd64)
minio-next-1  |
minio-next-1  | Status:         1 Online, 0 Offline.
minio-next-1  | S3-API: http://172.18.0.2:9000  http://127.0.0.1:9000
minio-next-1  | Console: [MASKED]
minio-next-1  |
minio-next-1  | Documentation: https://min.io/docs/minio/linux/index.html
minio-next-1  | Warning: The standard parity is set to 0. This can lead to data loss.

minio-next-1  | panic: runtime error: invalid memory address or nil pointer dereference
minio-next-1  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2387956]
minio-next-1  |
minio-next-1  | goroutine 3050 [running]:
minio-next-1  | github.com/minio/minio/cmd.(*SiteReplicationSys).SiteReplicationMetaInfo(0x609f540, {0x49f14d0, 0xc00de57bd0}, {0x4a1d4d8?, 0xc0010ea6c0}, {0x0, 0x0, 0x0, 0x0, 0x0, ...})
minio-next-1  |         github.com/minio/minio/cmd/site-replication.go:3734 +0x3996
minio-next-1  | github.com/minio/minio/cmd.(*SiteReplicationSys).siteReplicationStatus.func1()
minio-next-1  |         github.com/minio/minio/cmd/site-replication.go:2729 +0x9f
minio-next-1  | github.com/minio/minio/cmd.(*SiteReplicationSys).concDo.func1(0x0)
minio-next-1  |         github.com/minio/minio/cmd/site-replication.go:2222 +0x135
minio-next-1  | created by github.com/minio/minio/cmd.(*SiteReplicationSys).concDo in goroutine 2133
minio-next-1  |         github.com/minio/minio/cmd/site-replication.go:2218 +0x25f
minio-next-1 exited with code 2
```

## Regression

Yes

## Your Environment

* Version used (`minio --version`): `RELEASE.2023-12-02T10-51-33Z`
* Server setup and configuration: 
```yaml
version: '3.8'
services:
  minio:
    image: minio/minio:RELEASE.2023-12-02T10-51-33Z
    command: "server /data --console-address :9001"
    environment:
      MINIO_ROOT_USER: [MASKED]
      MINIO_ROOT_PASSWORD: [MASKED]
      MINIO_BROWSER_REDIRECT_URL: [MASKED]
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: always
    volumes:
      - /volume3/minio:/data
    logging:
      driver: json-file
```
* Operating System and version (`uname -a`): `Linux AotokiNAS 4.4.302+ #69057 SMP Mon Nov 13 14:19:30 CST 2023 x86_64 GNU/Linux synology_geminilake_920+`
