### ISSUE TITLE
tls: failed to verify certificate: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by tibuntu** [minio/minio#18626]
Hello, after the recent update our MinIO Tenants started to crash. They were updated by the minio-operator and after the update they complained about the certificate of the operator.

## Expected Behavior
MinIO is able to start without any issues.

## Current Behavior
```
ERROR Unable to validate passed arguments in MINIO_ARGS:env+tls://3po7MUBi6NFvjoSJ657L:<redact>@operator.minio-operator.svc.cluster.local:4222/webhook/v1/getenv/tenant/tenant: Get "https://operator.minio-operator.svc.bit-test.local:4222/webhook/v1/getenv/tenant/tenant?key=MINIO_ARGS": tls: failed to verify certificate: x509: certificate signed by unknown authority
```

## Possible Solution
Rolling back to the previous MinIO version fixed the issue for us.

We deleted the kubernetes secrets `operator-tls` and `operator-webhook-secret` which caused a re-creation by the operator, but the Tenants still complained about the certificates.

## Steps to Reproduce (for bugs)
Have a tenant like this:

```yaml
kind: Tenant
metadata:
  name: myTenant
  namespace: myTenant
spec:
  certConfig:
    commonName: '*.myTenant-tenant.myTenant.svc.cluster.local'
    dnsNames:
    - myTenant-pool-0-0.myTenant.myTenant.svc.cluster.local
    organizationName:
    - system:nodes
  configuration:
    name: myTenant-minio-secret
  credsSecret:
    name: myTenant-minio-secret
  env:
  - name: MINIO_IDENTITY_OPENID_CONFIG_URL
    value: https://gitlab.com/.well-known/openid-configuration
  - name: MINIO_IDENTITY_OPENID_CLIENT_ID
    value: 761b347c741b6f791adccf28faf04319df868342a91b0269b04ad8d31052fe23
  - name: MINIO_IDENTITY_OPENID_SCOPES
    value: openid,profile,email
  - name: MINIO_IDENTITY_OPENID_CLAIM_NAME
    value: groups_direct
  - name: MINIO_IDENTITY_OPENID_REDIRECT_URI
    value: https://console-myTenant-minio.my-domain.com/oauth_callback
  - name: MINIO_BROWSER
    value: "on"
  - name: MINIO_STORAGE_CLASS_STANDARD
    value: EC:2
  exposeServices:
    console: true
    minio: true
  image: minio:RELEASE.2023-12-09T18-17-51Z
  imagePullPolicy: IfNotPresent
  imagePullSecret:
    name: regcred
  mountPath: /export
  podManagementPolicy: Parallel
  pools:
  - affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: v1.min.io/tenant
              operator: In
              values:
              - myTenant
            - key: v1.min.io/pool
              operator: In
              values:
              - pool-1
          topologyKey: kubernetes.io/hostname
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
    name: pool-1
    resources:
      requests:
        cpu: 30m
        memory: 8000M
    securityContext:
      runAsGroup: 1000
      runAsUser: 1000
      seccompProfile:
        type: RuntimeDefault
    servers: 2
    volumeClaimTemplate:
      metadata:
        name: data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
        storageClassName: myStorageClass
    volumesPerServer: 2
  requestAutoCert: false
  serviceAccountName: myTenant
  users:
  - name: myTenant-minio
 ```

The operator is deployed via Helm with the following values:

```yaml
operator:
  image:
    repository: minio-operator/operator
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  containerSecurityContext:
    runAsNonRoot: true
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
  resources:
    requests:
      cpu: 10m
      memory: 30M
    limits:
      cpu: 30m
      memory: 200M
console:
  image:
    repository: minio-operator/console
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    seccompProfile:
      type: RuntimeDefault
  containerSecurityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    capabilities:
      drop:
        - ALL
  resources:
    requests:
      cpu: 10m
      memory: 50M
    limits:
      cpu: 30m
      memory: 100M
  volumes:
    - name: certs
      emptyDir: {}
  volumeMounts:
    - mountPath: /.console/certs
      name: certs
```

## Regression
Yes
After update: RELEASE.2023-12-09T18-17-51Z
Before update: RELEASE.2023-12-07T04-16-00Z
