### ISSUE TITLE
Elevated errors rate on one node only in a distributed setup

### ISSUE THREAD

**Issue by ClementGautier** [minio/minio#18830]
I have deployed a Minio cluster of 1 pool, 4 server, 4 disks per servers.
During our load tests I see a ~1% error rate (mix of 503 and 504) on get/put/list objects.

## Expected Behavior
I would expect either homogenous failures across all nodes (if it's a load issue) or no errors at all (if it's an issue with one disk for exemple it should be able to write elsewhere).

## Current Behavior
On the console I see that it's a single node that is responsible for the errors:

![image](https://github.com/minio/minio/assets/660091/c4619c47-31f7-4e3b-9df1-3f9a4cfca013)

The weird thing is I have nothing either in the logs or when I use `mc admin trace`, errors aren't showing up in tracing.

I tried to restart the impacted pod, rescheduling the pod on another server (and re-mounting the disks) and it didn't solved the issue.

My guess is that it have something to do with one of the disks on that node but I don't now how to detect that.

## Possible Solution
Having some tool to detect disk issues or expose more logs by default to understand what went wrong would be nice

## Steps to Reproduce (for bugs)
Install minio operator, setup the tenant with a pool like that:
```
pools:
    - name: pool-0
      servers: 4
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 100Gi
          storageClassName: silver-xfs
      volumesPerServer: 4
```

## Context
I'm trying to create a in-house object storage as a backup plan for our current saas provider

## Regression
No

## Your Environment
Version `quay.io/minio/minio:RELEASE.2023-01-02T09-40-09Z` 
Minio Operator version `5.0.11`
Custom TLS + Encryption enabled
