### ISSUE TITLE
One of the nodes in minio is faulty, and restarting the service fails

### ISSUE THREAD

**Issue by rensongqi** [minio/minio#18892]
## NOTE
There are three minio nodes, the minio3 node suddenly fails. The previous log messages:
```
API: SYSTEM()
Time: 06:13:56 UTC 01/27/2024
DeploymentID: 6ceb2766-7648-4c40-8c67-f1f94eac329d
Error: Failure in periodic refresh for IAM (took 586.09s): unable to load the policy doc `carlog`: Operation timed out (*errors.errorString)
       2: internal/logger/logger.go:258:logger.LogIf()
       1: cmd/iam.go:375:cmd.(*IAMSys).periodicRoutines()

API: SYSTEM()
Time: 06:18:49 UTC 01/27/2024
DeploymentID: 6ceb2766-7648-4c40-8c67-f1f94eac329d
Error: Operation timed out (cmd.OperationTimedOut)
       2: internal/logger/logger.go:258:logger.LogIf()
       1: cmd/bucket-metadata-sys.go:533:cmd.(*BucketMetadataSys).refreshBucketsMetadataLoop()

API: SYSTEM()
Time: 06:23:43 UTC 01/27/2024
DeploymentID: 6ceb2766-7648-4c40-8c67-f1f94eac329d
Error: unable to load user during STS purge: Operation timed out (R1PSRN4Y2TKTK42TBWKV/identity.json) (*fmt.wrapError)
       4: internal/logger/logger.go:258:logger.LogIf()
       3: cmd/iam-object-store.go:406:cmd.(*IAMObjectStore).PurgeExpiredSTS()
       2: cmd/iam-store.go:486:cmd.(*IAMStoreSys).PurgeExpiredSTS()
       1: cmd/iam.go:389:cmd.(*IAMSys).periodicRoutines()

API: SYSTEM()
Time: 06:28:37 UTC 01/27/2024
DeploymentID: 6ceb2766-7648-4c40-8c67-f1f94eac329d
Error: Operation timed out (cmd.OperationTimedOut)
       2: internal/logger/logger.go:258:logger.LogIf()
       1: cmd/bucket-metadata-sys.go:533:cmd.(*BucketMetadataSys).refreshBucketsMetadataLoop()

API: SYSTEM()
Time: 06:33:30 UTC 01/27/2024
DeploymentID: 6ceb2766-7648-4c40-8c67-f1f94eac329d
Error: unable to load user during STS purge: Operation timed out (FWHNGMKHA7URTYGXFYAZ/identity.json) (*fmt.wrapError)
       4: internal/logger/logger.go:258:logger.LogIf()
       3: cmd/iam-object-store.go:406:cmd.(*IAMObjectStore).PurgeExpiredSTS()
       2: cmd/iam-store.go:486:cmd.(*IAMStoreSys).PurgeExpiredSTS()
       1: cmd/iam.go:389:cmd.(*IAMSys).periodicRoutines()

API: SYSTEM()
Time: 06:38:23 UTC 01/27/2024
DeploymentID: 6ceb2766-7648-4c40-8c67-f1f94eac329d
Error: Operation timed out (cmd.OperationTimedOut)
       2: internal/logger/logger.go:258:logger.LogIf()
       1: cmd/bucket-metadata-sys.go:533:cmd.(*BucketMetadataSys).refreshBucketsMetadataLoop()

API: SYSTEM()
Time: 06:43:16 UTC 01/27/2024
DeploymentID: 6ceb2766-7648-4c40-8c67-f1f94eac329d
Error: unable to load user during STS purge: Operation timed out (UXVOY401CPUMVO8QH1HI/identity.json) (*fmt.wrapError)
       4: internal/logger/logger.go:258:logger.LogIf()
       3: cmd/iam-object-store.go:406:cmd.(*IAMObjectStore).PurgeExpiredSTS()
       2: cmd/iam-store.go:486:cmd.(*IAMStoreSys).PurgeExpiredSTS()
       1: cmd/iam.go:389:cmd.(*IAMSys).periodicRoutines()
IAM expired STS purge took 1759.87s

API: SYSTEM()
Time: 06:50:37 UTC 01/27/2024
DeploymentID: 6ceb2766-7648-4c40-8c67-f1f94eac329d
Error: Operation timed out (cmd.OperationTimedOut)
       2: internal/logger/logger.go:258:logger.LogIf()
       1: cmd/bucket-metadata-sys.go:533:cmd.(*BucketMetadataSys).refreshBucketsMetadataLoop()

API: SYSTEM()
Time: 07:02:51 UTC 01/27/2024
DeploymentID: 6ceb2766-7648-4c40-8c67-f1f94eac329d
Error: Operation timed out (cmd.OperationTimedOut)
       2: internal/logger/logger.go:258:logger.LogIf()
       1: cmd/bucket-metadata-sys.go:533:cmd.(*BucketMetadataSys).refreshBucketsMetadataLoop()

API: ListObjectsV2(bucket=ai-panoptic)
Time: 07:03:22 UTC 01/27/2024
DeploymentID: 6ceb2766-7648-4c40-8c67-f1f94eac329d
RequestID: 17AE22477408E671
RemoteHost: 172.31.10.45
Host: minio3:9000
UserAgent: MinIO (linux; amd64) minio-go/v7.0.64 MinIO Console/(dev)
Error: Marking minio1:9000 offline temporarily; caused by Post "http://minio1:9000/minio/peer/v33/getmetacache": dial tcp 172.17.1.107:9000: connect: connection timed out (*fmt.wrapError)
      11: internal/logger/logonce.go:118:logger.(*logOnceType).logOnceIf()
      10: internal/logger/logonce.go:149:logger.LogOnceIf()
       9: internal/rest/client.go:319:rest.(*Client).Call()
       8: cmd/peer-rest-client.go:68:cmd.(*peerRESTClient).callWithContext()
       7: cmd/peer-rest-client.go:552:cmd.(*peerRESTClient).GetMetacacheListing()
       6: cmd/metacache-server-pool.go:126:cmd.(*erasureServerPools).listPath()
       5: cmd/erasure-server-pool.go:1461:cmd.(*erasureServerPools).ListObjects()
       4: cmd/erasure-server-pool.go:1234:cmd.(*erasureServerPools).ListObjectsV2()
       3: cmd/bucket-listobjects-handlers.go:210:cmd.objectAPIHandlers.listObjectsV2Handler()
       2: cmd/bucket-listobjects-handlers.go:156:cmd.objectAPIHandlers.ListObjectsV2Handler()
       1: net/http/server.go:2136:http.HandlerFunc.ServeHTTP()

API: ListObjectsV2(bucket=ai-panoptic)
Time: 07:03:22 UTC 01/27/2024
DeploymentID: 6ceb2766-7648-4c40-8c67-f1f94eac329d
RequestID: 17AE22477408E671
RemoteHost: 172.31.10.45
Host: minio3:9000
UserAgent: MinIO (linux; amd64) minio-go/v7.0.64 MinIO Console/(dev)
Error: Post "http://minio1:9000/minio/peer/v33/getmetacache": dial tcp 172.17.1.107:9000: connect: connection timed out (*rest.NetworkError)
       8: internal/logger/logonce.go:118:logger.(*logOnceType).logOnceIf()
       7: internal/logger/logonce.go:149:logger.LogOnceIf()
       6: cmd/metacache-server-pool.go:137:cmd.(*erasureServerPools).listPath()
       5: cmd/erasure-server-pool.go:1461:cmd.(*erasureServerPools).ListObjects()
       4: cmd/erasure-server-pool.go:1234:cmd.(*erasureServerPools).ListObjectsV2()
       3: cmd/bucket-listobjects-handlers.go:210:cmd.objectAPIHandlers.listObjectsV2Handler()
       2: cmd/bucket-listobjects-handlers.go:156:cmd.objectAPIHandlers.ListObjectsV2Handler()
       1: net/http/server.go:2136:http.HandlerFunc.ServeHTTP()

API: ListObjectsV2(bucket=ai-panoptic)
Time: 07:03:25 UTC 01/27/2024
DeploymentID: 6ceb2766-7648-4c40-8c67-f1f94eac329d
RequestID: 17AE22484CC8B2FB
RemoteHost: 172.31.10.45
Host: minio3:9000
UserAgent: MinIO (linux; amd64) minio-go/v7.0.64 MinIO Console/(dev)
Error: Marking minio2:9000 offline temporarily; caused by Post "http://minio2:9000/minio/peer/v33/getmetacache": dial tcp 172.17.1.108:9000: connect: connection timed out (*fmt.wrapError)
      11: internal/logger/logonce.go:118:logger.(*logOnceType).logOnceIf()
      10: internal/logger/logonce.go:149:logger.LogOnceIf()
       9: internal/rest/client.go:319:rest.(*Client).Call()
       8: cmd/peer-rest-client.go:68:cmd.(*peerRESTClient).callWithContext()
       7: cmd/peer-rest-client.go:552:cmd.(*peerRESTClient).GetMetacacheListing()
       6: cmd/metacache-server-pool.go:126:cmd.(*erasureServerPools).listPath()
       5: cmd/erasure-server-pool.go:1461:cmd.(*erasureServerPools).ListObjects()
       4: cmd/erasure-server-pool.go:1234:cmd.(*erasureServerPools).ListObjectsV2()
       3: cmd/bucket-listobjects-handlers.go:210:cmd.objectAPIHandlers.listObjectsV2Handler()
       2: cmd/bucket-listobjects-handlers.go:156:cmd.objectAPIHandlers.ListObjectsV2Handler()
       1: net/http/server.go:2136:http.HandlerFunc.ServeHTTP()

API: ListObjectsV2(bucket=ai-panoptic)
Time: 07:03:25 UTC 01/27/2024
DeploymentID: 6ceb2766-7648-4c40-8c67-f1f94eac329d
RequestID: 17AE22484CC8B2FB
RemoteHost: 172.31.10.45
Host: minio3:9000
UserAgent: MinIO (linux; amd64) minio-go/v7.0.64 MinIO Console/(dev)
Error: Post "http://minio2:9000/minio/peer/v33/getmetacache": dial tcp 172.17.1.108:9000: connect: connection timed out (*rest.NetworkError)
       8: internal/logger/logonce.go:118:logger.(*logOnceType).logOnceIf()
       7: internal/logger/logonce.go:149:logger.LogOnceIf()
       6: cmd/metacache-server-pool.go:137:cmd.(*erasureServerPools).listPath()
       5: cmd/erasure-server-pool.go:1461:cmd.(*erasureServerPools).ListObjects()
       4: cmd/erasure-server-pool.go:1234:cmd.(*erasureServerPools).ListObjectsV2()
       3: cmd/bucket-listobjects-handlers.go:210:cmd.objectAPIHandlers.listObjectsV2Handler()
       2: cmd/bucket-listobjects-handlers.go:156:cmd.objectAPIHandlers.ListObjectsV2Handler()
       1: net/http/server.go:2136:http.HandlerFunc.ServeHTTP()

API: SYSTEM()
Time: 07:03:27 UTC 01/27/2024
DeploymentID: 6ceb2766-7648-4c40-8c67-f1f94eac329d
Error: Write failed. Insufficient number of drives online (offline-disks=2/3) (*fmt.wrapError)
       6: internal/logger/logger.go:258:logger.LogIf()
       5: cmd/erasure-encode.go:115:cmd.(*Erasure).Encode()
       4: cmd/erasure-object.go:949:cmd.erasureObjects.putMetacacheObject()
       3: cmd/metacache-set.go:767:cmd.(*erasureObjects).saveMetaCacheStream.func3()
       2: cmd/metacache-stream.go:792:cmd.newMetacacheBlockWriter.func1.2()
       1: cmd/metacache-stream.go:808:cmd.newMetacacheBlockWriter.func1()

API: SYSTEM()
Time: 07:03:31 UTC 01/27/2024
DeploymentID: 6ceb2766-7648-4c40-8c67-f1f94eac329d
Error: Write failed. Insufficient number of drives online (offline-disks=2/3) (*fmt.wrapError)
       6: internal/logger/logger.go:258:logger.LogIf()
       5: cmd/erasure-encode.go:115:cmd.(*Erasure).Encode()
       4: cmd/erasure-object.go:949:cmd.erasureObjects.putMetacacheObject()
       3: cmd/metacache-set.go:767:cmd.(*erasureObjects).saveMetaCacheStream.func3()
       2: cmd/metacache-stream.go:792:cmd.newMetacacheBlockWriter.func1.2()
       1: cmd/metacache-stream.go:808:cmd.newMetacacheBlockWriter.func1()

```

The following log is generated after minio3 is restarted:

```
API: SYSTEM()
Time: 02:38:31 UTC 01/29/2024
DeploymentID: 6ceb2766-7648-4c40-8c67-f1f94eac329d
Error: Operation timed out (cmd.OperationTimedOut)
       2: internal/logger/logger.go:258:logger.LogIf()
       1: cmd/bucket-metadata-sys.go:533:cmd.(*BucketMetadataSys).refreshBucketsMetadataLoop()
Exiting on signal: TERMINATED

API: SYSTEM()
Time: 02:55:21 UTC 01/29/2024
DeploymentID: 6ceb2766-7648-4c40-8c67-f1f94eac329d
Error: Failure in periodic refresh for IAM (took 8101.46s): unable to load the policy doc `carlog`: context canceled (*errors.errorString)
       2: internal/logger/logger.go:258:logger.LogIf()
       1: cmd/iam.go:375:cmd.(*IAMSys).periodicRoutines()

API: SYSTEM()
Time: 02:55:21 UTC 01/29/2024
DeploymentID: 6ceb2766-7648-4c40-8c67-f1f94eac329d
Error: Failure in periodic STS purge for IAM (took 0.00s): context canceled (*errors.errorString)
       2: internal/logger/logger.go:258:logger.LogIf()
       1: cmd/iam.go:390:cmd.(*IAMSys).periodicRoutines()

API: SYSTEM()
Time: 02:55:23 UTC 01/29/2024
DeploymentID: 6ceb2766-7648-4c40-8c67-f1f94eac329d
Error: timed out. some connections are still active. goroutines written to /tmp/minio-goroutines-3034688298.txt (*errors.errorString)
       3: internal/logger/logger.go:258:logger.LogIf()
       2: cmd/signals.go:54:cmd.handleSignals.func2()
       1: cmd/signals.go:81:cmd.handleSignals()

API: SYSTEM()
Time: 02:55:35 UTC 01/29/2024
Error: WARNING: Expected number of all hosts (3) to be remote +1 (3) (*errors.errorString)
       7: internal/logger/logger.go:258:logger.LogIf()
       6: cmd/peer-rest-client.go:799:cmd.newPeerRestClients()
       5: cmd/notification.go:1092:cmd.NewNotificationSys()
       4: cmd/server-main.go:321:cmd.initAllSubsystems()
       3: cmd/server-main.go:624:cmd.serverMain.func4()
       2: cmd/server-main.go:433:cmd.bootstrapTrace()
       1: cmd/server-main.go:623:cmd.serverMain()
WARNING: Detected Linux kernel version older than 4.0.0 release, there are some known potential performance problems with this kernel version. MinIO recommends a minimum of 4.x.x linux kernel version for best performance
Waiting for atleast 1 remote servers with valid configuration to be online
Following servers are currently offline or unreachable [http://minio1:9000/data0 is unreachable: Post "http://minio1:9000/minio/bootstrap/v1/verify": dial tcp 172.17.1.107:9000: connect: connection timed out http://minio2:9000/data0 is unreachable: Post "http://minio2:9000/minio/bootstrap/v1/verify": dial tcp 172.17.1.108:9000: connect: connection timed out http://minio3:9000/data0 is unreachable: Post "http://minio3:9000/minio/bootstrap/v1/verify": dial tcp 172.17.1.109:9000: connect: connection timed out]
Waiting for atleast 1 remote servers with valid configuration to be online
Following servers are currently offline or unreachable [http://minio1:9000/data0 is unreachable: Post "http://minio1:9000/minio/bootstrap/v1/verify": dial tcp 172.17.1.107:9000: connect: connection timed out http://minio2:9000/data0 is unreachable: Post "http://minio2:9000/minio/bootstrap/v1/verify": dial tcp 172.17.1.108:9000: connect: connection timed out http://minio3:9000/data0 is unreachable: Post "http://minio3:9000/minio/bootstrap/v1/verify": dial tcp 172.17.1.109:9000: connect: connection timed out]
Waiting for atleast 1 remote servers with valid configuration to be online
Following servers are currently offline or unreachable [http://minio1:9000/data0 is unreachable: Post "http://minio1:9000/minio/bootstrap/v1/verify": dial tcp 172.17.1.107:9000: connect: connection timed out http://minio2:9000/data0 is unreachable: Post "http://minio2:9000/minio/bootstrap/v1/verify": dial tcp 172.17.1.108:9000: connect: connection timed out http://minio3:9000/data0 is unreachable: Post "http://minio3:9000/minio/bootstrap/v1/verify": dial tcp 172.17.1.109:9000: connect: connection timed out]
Exiting on signal: TERMINATED
ERROR Unable to start the server: context canceled

API: SYSTEM()
Time: 03:04:57 UTC 01/29/2024
Error: WARNING: Expected number of all hosts (3) to be remote +1 (3) (*errors.errorString)
       7: internal/logger/logger.go:258:logger.LogIf()
       6: cmd/peer-rest-client.go:799:cmd.newPeerRestClients()
       5: cmd/notification.go:1092:cmd.NewNotificationSys()
       4: cmd/server-main.go:321:cmd.initAllSubsystems()
       3: cmd/server-main.go:624:cmd.serverMain.func4()
       2: cmd/server-main.go:433:cmd.bootstrapTrace()
       1: cmd/server-main.go:623:cmd.serverMain()
WARNING: Detected Linux kernel version older than 4.0.0 release, there are some known potential performance problems with this kernel version. MinIO recommends a minimum of 4.x.x linux kernel version for best performance
Waiting for atleast 1 remote servers with valid configuration to be online
Following servers are currently offline or unreachable [http://minio1:9000/data0 is unreachable: Post "http://minio1:9000/minio/bootstrap/v1/verify": dial tcp 172.17.1.107:9000: connect: connection timed out http://minio2:9000/data0 is unreachable: Post "http://minio2:9000/minio/bootstrap/v1/verify": dial tcp 172.17.1.108:9000: connect: connection timed out http://minio3:9000/data0 is unreachable: Post "http://minio3:9000/minio/bootstrap/v1/verify": dial tcp 172.17.1.109:9000: connect: connection timed out]
Waiting for atleast 1 remote servers with valid configuration to be online
Following servers are currently offline or unreachable [http://minio1:9000/data0 is unreachable: Post "http://minio1:9000/minio/bootstrap/v1/verify": dial tcp 172.17.1.107:9000: connect: connection timed out http://minio2:9000/data0 is unreachable: Post "http://minio2:9000/minio/bootstrap/v1/verify": dial tcp 172.17.1.108:9000: connect: connection timed out http://minio3:9000/data0 is unreachable: Post "http://minio3:9000/minio/bootstrap/v1/verify": dial tcp 172.17.1.109:9000: connect: connection timed out]
Waiting for atleast 1 remote servers with valid configuration to be online
```

Checked the physical disk. No errors.

## Expected Behavior
minio3 should work fine

## Current Behavior
minio1 and minio2 are working
minio3 does not work properly

## Possible Solution
disk reason?

## Regression
No

## Your Environment
* Version used (`minio --version`):
```
minio version RELEASE.2023-10-24T04-42-36Z (commit-id=2dc917e87f12166e4cfc3b1be24cf2bf70b29bbd)
Runtime: go1.21.3 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2023 MinIO, Inc.
```
* Server setup and configuration:
```
Minio services deployed using docker-compose: Docker version: 22.06.0-beta.0
```
Minio Server Environment:
```
MINIO_ACCESS_KEY_FILE=access_key
LANG=C.utf8
TZ=Asia/Shanghai
HOSTNAME=minio1
MINIO_KMS_SECRET_KEY_FILE=kms_master_key
MINIO_ROOT_USER=admin
container=oci
PWD=/
HOME=/root
TERM=xterm
MINIO_ROOT_USER_FILE=access_key
MINIO_ROOT_PASSWORD=miniopass
MINIO_ROOT_PASSWORD_FILE=secret_key
SHLVL=1
MINIO_DOMAIN=ossapi.cowarobot.cn
MINIO_UPDATE_MINISIGN_PUBKEY=RWTx5Zr1tiHQLwG9keckT0c45M3AGeHD6IvimQHpyRywVWGbP1aVSGav
MINIO_SECRET_KEY_FILE=secret_key
PATH=/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
MINIO_CONFIG_ENV_FILE=config.env
_=/usr/bin/env
```
docker-compose.yml:
```yml
version: '3.7'

x-minio-common: &minio-common
  #image: "harbor.cowarobot.cn/minio/minio:RELEASE.2022-08-25T07-17-05Z"
  image: "harbor.cowarobot.cn/library/minio/minio:RELEASE.2023-10-24T04-42-36Z"
  command: server --console-address ":9001" http://minio{1...3}/data{0...5}
  expose:
    - "9000"
    - "9001"

  extra_hosts:
    minio1: 172.17.1.107
    minio2: 172.17.1.108
    minio3: 172.17.1.109
  depends_on:
    - nginx
  environment:
    MINIO_ROOT_USER: admin
    MINIO_ROOT_PASSWORD: miniopass
    MINIO_DOMAIN: ossapi.cowarobot.cn
    #MINIO_STORAGE_CLASS_STANDARD: "EC:3"
    #MINIO_STORAGE_CLASS_RRS: "EC:2"
    TZ: Asia/Shanghai
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 5

services:
  minio1:
    <<: *minio-common
    container_name: minio1
    hostname: minio1
    volumes:
      - /minio0:/data0
      - /minio1:/data1
      - /minio2:/data2
      - /minio3:/data3
      - /minio4:/data4
      - /minio5:/data5
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: always
    network_mode: host

  minio2:
    <<: *minio-common
    container_name: minio2
    hostname: minio2
    volumes:
      - /minio0:/data0
      - /minio1:/data1
      - /minio2:/data2
      - /minio3:/data3
      - /minio4:/data4
      - /minio5:/data5
    ports:
      - "9000:9000"
      - "9001:9001"

  minio3:
    <<: *minio-common
    container_name: minio3
    hostname: minio3
    volumes:
      - /minio0:/data0
      - /minio1:/data1
      - /minio2:/data2
      - /minio3:/data3
      - /minio4:/data4
      - /minio5:/data5
    ports:
      - "9000:9000"
      - "9001:9001"

  nginx:
    image: "harbor.cowarobot.cn/library/nginx:1.19.2-alpine"
    container_name: nginx-minio
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "30009:9000"
      - "30099:9001"
    extra_hosts:
      minio1: 172.16.100.107
      minio2: 172.16.100.108
      minio3: 172.16.100.109
```

* Operating System and version (`uname -a`):
```
Linux shjdpelk01 3.10.0-1160.71.1.el7.x86_64 #1 SMP Tue Jun 28 15:37:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
