### ISSUE TITLE
expand second pool failed

### ISSUE THREAD

**Issue by hofarah** [minio/minio#18967]
# Add new pool to existing cluster 
My current cluster size is 3 and have 6 drive for each node.
I want to add new pool with size 3 and 14 drive for each nodes
I apply this docker-compose for 3 old server and 3 new servers  
```
version: '3.7'
 
services:
  minio:
    image: example.com/minio:bullseye-2023-06-09
    container_name: minio
    hostname: minio
    restart: always
    volumes:
      - /core/db/minio-data:/minio_disks
    network_mode: host
    environment:
      MINIO_ACCESS_KEY: ACCESS_KEY
      MINIO_SECRET_KEY: SECRET_KEY
    extra_hosts:
      - minio.gap20-storage:172.15.52.14
      - minio.gap21-storage:172.15.52.15
      - minio.gap22-storage:172.15.52.16
      - minio.gap17-storage:172.15.52.34
      - minio.gap18-storage:172.15.52.35
      - minio.gap19-storage:172.15.52.36
    command: minio server --address ${IP}:9000  http://minio.gap{17...19}-storage/minio_disks/data{1...6}  http://minio.gap{20...22}-storage/minio_disks/data{1...14} --console-address ":9001"
```

## Expected Behavior
healthy clusters

## Current Behavior
ERROR Unable to initialize backend: parity validation returned an error: parity 4 should be less than or equal to 3 <- (4, 6), for pool(2nd)

## Environment

* Version used = minio version RELEASE.2023-06-09T07-32-12Z.2023-06-09T07-32-12Z (commit-id=6b7c98bd0fde630c6aee78d702b9d37b0200f52c)

* Operating System and version=Linux minio 5.10.0-22-amd64 #1 SMP Debian 5.10.178-3 (2023-04-22) x86_64 GNU/Linux
