### ISSUE TITLE
Browser video preview not working. "Error Getting Metadata Status: undefined" in browser console 

### ISSUE THREAD

**Issue by rameshdon1** [minio/minio#19070]
Here is my docker-compose file

```
version: "3.9"

services:
  minio:
    container_name: minio
    image: quay.io/minio/minio:latest
    restart: unless-stopped
    networks:
      - traefik
    volumes:
      - ./minio_data:/data
    environment:
      - MINIO_ROOT_USER=specux-minio
      - MINIO_ROOT_PASSWORD=Specux9869@
      - MINIO_BROWSER_REDIRECT_URL=https://minio.specux.com
      - MINIO_SERVER_URL=https://s3.specux.com

    command: server /data --console-address ":9001"
    labels:
      - traefik.http.routers.minio-api.rule=Host(`s3.specux.com`)
      - traefik.http.routers.minio-api.service=minio-api-service
      - traefik.http.services.minio-api-service.loadbalancer.server.port=9000

      - traefik.http.routers.minio-dash.rule=Host(`minio.specux.com`)
      - traefik.http.routers.minio-dash.service=minio-dash-service
      - traefik.http.services.minio-dash-service.loadbalancer.server.port=9001

networks:
  traefik:
    driver: bridge
    external: true

volumes:
  minio_data:
    driver: local
```

I am getting this error in the console and the image preview is also not working. It just shows the non-functional video player in the frontend.

Previously it was working, but suddenly the preview in browser is not working. But accessing the file through s3 api url is working fine.

What could be the issue here?

![image](https://github.com/minio/minio/assets/139542777/a9933964-fe4d-4f39-9d6c-f66928ce9861)
