### ISSUE TITLE
Access keys stopped working after configuring site replication

### ISSUE THREAD

**Issue by pedrocrc** [minio/minio#19311]
## Expected Behavior
My existing access keys should keep working

## Current Behavior
Existing access keys stopped working after configuring site replication. Then I disabled site replication and the access keys worked again.

## Steps to Reproduce (for bugs)

1. Have two min.io clusters deployed by min.io operator. Both clusters use OIDC authentication with exactly same OIDC configurations. Both clusters are deployed on kubernetes and both of them have 4 nodes, with 2 drivers per node, using EC:2. They are deployed on the same kubernetes cluster. The only difference between the two of them is the storageclass, that send the PVCs of each one to a different physical storage.
2. The first cluster (cluster A) is full of buckets, objects, policies and several OIDC users have access keys configured to them, that are working just fine.
3. The second cluster (cluster B) has just been deployed, using same min.io image of cluster A. It's empty of buckets, objects or policies.
4. Through the min.io console on cluster A, I set up the site replication using the root credentials of both clusters (the root credentials are different and were randomly created by min.io operator upon cluster deployment)
5. The form submission completes successfully and the buckets, objects and everything started replicating
6. All the objects were successfully replicated, all the policies also, all the access keys are replicated, as shown at min.io console at each cluster. I've also downloaded the iam configuration of both clusters using mc admin cluster iam export after the replication configuration and they seem the same
7. Every OIDC user is able to access min.io with their permissions through the console, but when they try to access using their existing access keys, they get a denied message
8. I tried creating new access keys for those OIDC users and same problem happens
9. I tried creating local users and creating access keys for them, and same problem happens
10. Then I had to rollback the replication configuration, because the access keys were critical to production services. 
11. I disabled site replication through min.io console, by deleting the other cluster's entry
12. After disabling the site replication, all those access keys returned to normal and can access the objects they are allowed to seamlessly

## Context
During the period from configuring site replication and disabling it, my access keys lost all their access, impacting production services

## Your Environment
* Version used (`minio --version`): minio/minio:RELEASE.2024-03-05T04-48-44Z
* Server setup and configuration: 
```yaml
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: *****
  namespace: *****
scheduler:
  name: ''
spec:
  configuration:
    name: *****
  credsSecret:
    name: *****
  exposeServices: {}
  features:
    domains:
      console: *****
      minio:
        - *****
  imagePullSecret: {}
  mountPath: /export
  pools:
    - affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: v1.min.io/tenant
                    operator: In
                    values:
                      - *****
                  - key: v1.min.io/pool
                    operator: In
                    values:
                      - pool-0
              topologyKey: kubernetes.io/hostname
      name: pool-0
      resources:
        limits:
          cpu: '4'
          memory: 32Gi
        requests:
          cpu: '1'
          memory: 16Gi
      runtimeClassName: ''
      servers: 4
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: '10995116277760'
          storageClassName: *****
        status: {}
      volumesPerServer: 2
  requestAutoCert: false
---
config.env: >-
export MINIO_IDENTITY_OPENID_CONFIG_URL="***"
export MINIO_IDENTITY_OPENID_CLIENT_ID="minio"
export MINIO_IDENTITY_OPENID_CLAIM_NAME="policy"
export MINIO_IDENTITY_OPENID_SCOPES="openid,profile,email"
export MINIO_ROOT_PASSWORD="***"
export MINIO_ROOT_USER="***"
export MINIO_STORAGE_CLASS_STANDARD="EC:2"
export MINIO_IDENTITY_OPENID_CLIENT_SECRET="***"
export MINIO_PROMETHEUS_AUTH_TYPE="public"
export MINIO_PROMETHEUS_JOB_ID="minio"
export MINIO_PROMETHEUS_URL="***"
export MINIO_BROWSER="on"
```
* Operating System and version (`uname -a`): the min.io cluster is deployed on kubernetes based on kubeadm v1.27.6 with nodes based on Ubuntu Server 22.04 LTS
