### ISSUE TITLE
Error batch replication: runtime error

### ISSUE THREAD

**Issue by lbouquinD** [minio/minio#19347]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior

Replication have to start   and replicate my data. 

## Current Behavior
minio client failed  to run replication with this issue: 

```
panic: "POST /minio/admin/v3/start-job": runtime error: invalid memory address or nil pointer dereference
goroutine 124707 [running]:
runtime/debug.Stack()
 runtime/debug/stack.go:24 +0x5e
github.com/minio/minio/cmd.serverMain.func8.setCriticalErrorHandler.func2.1()
 github.com/minio/minio/cmd/generic-handlers.go:555 +0x97
panic({0x289a060?, 0x6425330?})
 runtime/panic.go:914 +0x21f
net/http.(*Transport).roundTrip(0x0, 0xc10dd5c600)
 net/http/transport.go:514 +0x2d
net/http.(*Transport).RoundTrip(0xc10c173340?, 0x4cffe60?)
 net/http/roundtrip.go:17 +0x13
net/http.send(0xc10dd5c600, {0x4cffe60, 0x0}, {0x1?, 0x0?, 0x0?})
 net/http/client.go:260 +0x606
net/http.(*Client).send(0xc10bff4ff0, 0xc10dd5c600, {0x0?, 0x0?, 0x0?})
 net/http/client.go:181 +0x98
net/http.(*Client).do(0xc10bff4ff0, 0xc10dd5c600)
 net/http/client.go:724 +0x912
net/http.(*Client).Do(...)
 net/http/client.go:590


```

## Steps to Reproduce (for bugs)

1. configure replication_batch_file like that: 
```
  replicate:
  apiVersion: v1
  source:
    type: minio 
    bucket: test
    endpoint: "https://minio1-test:20502"
    credentials:
      accessKey: "minioadmin" 
      secretKey: "mypassword" 
    snowball:
       disable:  true
  
  target:
    type: minio
    bucket: test
    endpoint: "https://minio-cluster2-1-test:20512"
    credentials:
      accessKey: "minioadmin" 
      secretKey: "mypassword" 
    
    retry:
      attempts: 10 
      delay: "500ms"  
```
2. Set  alias: `mc alias set local/ https://minio1-test:20502 minioadmin mypassword --insecure`
3.  Launch batch  replication: `mc batch start  local ./barchreplication.yaml`

## Your Environment
* Version used (`minio --version`): 
```
minio  --version
minio version RELEASE.2024-03-10T02-53-48Z (commit-id=88a89213ff6663f2d3ee1de7f3293497ab9844e8)
Runtime: go1.21.8 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2024 MinIO, Inc.
```

* Server setup and configuration: Red Hat Enterprise Linux release 8.7 (Ootpa)
* Operating System and version (`uname -a`): Linux myVM 4.18.0-425.3.1.el8.x86_64  SMP Fri Sep 30 11:45:06 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by vadmeste** [comment]
@lbouquinD can you upload the batch yaml file here as a file ? I am not able to reproduce.

**Comment by lbouquinD** [comment]
[batch_replication.yaml.zip](https://github.com/minio/minio/files/14771620/batch_replication.yaml.zip)

```
replicate:
  apiVersion: v1
  source:
    type: minio 
    bucket: test
    endpoint: "https://minio1-test:20502"
    credentials:
      accessKey: "minioadmin" 
      secretKey: "mypassword" 
    snowball:
       disable:  true
  
  target:
    type: minio
    bucket: test
    endpoint: "https://minio-cluster2-1-test:20512"
    credentials:
      accessKey: "minioadmin" 
      secretKey: "mypassword" 
    
    retry:
      attempts: 10 
      delay: "500ms" 
```

**Comment by vadmeste** [comment]
@lbouquinD still not able to reproduce. Can you please provide the whole stack trace that you have ?

**Comment by lbouquinD** [comment]
Yes. here the full stack when I launch  mc batch replicate command 
[stack-error_logs.txt](https://github.com/minio/minio/files/14771830/stack-error_logs.txt)

**Comment by vadmeste** [comment]
The stacktrace shows it is a golang bug. What is your load balancer here ? 

In fact, if you are going to run this batch yaml in minio1-test and wants to copy data from minio1, you will have
to avoid specifying this as endpoint:

```
    endpoint: "https://minio1-test:20502"
    credentials:
      accessKey: "minioadmin" 
      secretKey: "mypassword" 
```

**Comment by lbouquinD** [comment]
To test it I don't use load balancer. But in production mode we'll use  2 haproxy  + keepalived  + VIP to  HA

I launch since minio{1...3}-test to   replicate to  minio-cluster2-{1...3}-test  

If I comment the following code I have the same error. 
```
    endpoint: "https://minio1-test:20502"
    credentials:
      accessKey: "minioadmin" 
      secretKey: "mypassword" 

```
