### ISSUE TITLE
Cannot login to console on one node

### ISSUE THREAD

**Issue by henrywhitaker3** [minio/minio#19387]
I have got two nodes running in docker, each with the following:

```
services:
  minio:
    container_name: minio
    image: minio/minio:latest
    restart: unless-stopped
    hostname: "minio-{x}.lab"
    command: server --console-address ":9001" http://minio-{1...2}.lab:9000/data
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./minio:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_SERVER_URL=https://s3.domain.com
      - MINIO_BROWSER_REDIRECT_URL=https://minio.domain.com
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:9000/minio/health/live"]
      interval: 1m30s
      timeout: 20s
      retries: 3
      start_period: 3m
```

Both are behind a tcp load balancer which handles the TLS temrination. If I go to http://minio-1.lab:9001, then I can login to the console, but I cannot login the console on the second node, I get a 401 invalid login error. Using s3cmd will work on both nodes, and mc admin works with the same username/password I'm trying to use in the browser on both nodes, it's just the console on node 2.

## Your Environment

* Version used (`minio --version`): `RELEASE.2024-03-30T09-41-56Z`
* Server setup and configuration: docker
* Operating System and version (`uname -a`): `Linux minio-2 5.15.0-101-generic #111-Ubuntu SMP Tue Mar 5 20:16:58 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`
