### ISSUE TITLE
Users, Policies, Access keys disappear from UI after docker restart when data is on NFS/SMB share

### ISSUE THREAD

**Issue by bestrocker221** [minio/minio#19416]
Docker compose deployment of Minio:
```
version: '3'
services:
  minio:
    image: quay.io/minio/minio
    user: "1000:1000" #(tried without as well)
    ports:
      - 9100:9000
      - 9190:9090
    volumes:
      - /mnt/DATA/MINIO:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=blah
      - MINIO_SERVER_URL=https://blah
      - MINIO_BROWSER_REDIRECT_URL=https://blah
    command: server /data --console-address ":9090"
    restart: always
```

## Expected Behavior
Minio working normally

## Current Behavior
No Users, Access keys, Policies are displayed anymore

## Steps to Reproduce (for bugs)
1.Start a new docker compose of minio as above
2. Login to UI
3. Create user, policy, access key
4. Restart Minio
5. Login to UI
6. There is no user, policy or access key anymore!

in the filesystem i can see there are the associated "xl.meta" but in the UI nothing is shown.

I noticed because my user could no longer push to the bucket, and indeed its user and access key were not there anymore.

The /mnt/DATA is an NFS share where the files and dirs are mounted with the same user (1000:1000) which has rw access.

Important: It works if the data volume resides on the same disk, when the data volume is on the share it writes to it but it behaves inconsistently (hence this issue). The same setup above worked for more than 6 months

## Your Environment

* Version used (`minio --version`): 2024-03-30T09:41:56Z
* Server setup and configuration: docker compose on Debian 6.1.0-18-amd64
