### ISSUE TITLE
Expected number of all hosts to be remote

### ISSUE THREAD

**Issue by sangrepura** [minio/minio#19439]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

I am experiencing the same issue as reported here: #10783

```
API: SYSTEM.peers
Time: 17:59:13 UTC 04/08/2024
Error: Expected number of all hosts (4) to be remote +1 (4) (*errors.errorString)
       8: internal/logger/logger.go:259:logger.LogIf()
       7: cmd/logging.go:42:cmd.peersLogIf()
       6: cmd/peer-rest-client.go:631:cmd.newPeerRestClients()
       5: cmd/notification.go:1163:cmd.NewNotificationSys()
       4: cmd/server-main.go:400:cmd.initAllSubsystems()
       3: cmd/server-main.go:715:cmd.serverMain.func4()
       2: cmd/server-main.go:512:cmd.bootstrapTrace()
       1: cmd/server-main.go:714:cmd.serverMain()
ERROR Unable to configure server grid RPC services: grid: local host not found
```

I am using Docker swarm with this config:
```
version: "3.8"

services:
  minio1:
    image: minio/minio:latest
    networks:
      - traefik-public
    environment:
      MINIO_ROOT_USER: *********
      MINIO_ROOT_PASSWORD: ***************
    command: server --console-address ":9001" http://minio{1...4}/data
    volumes:
      - /mnt/data/minio/minio1:/data
  
  minio2:
    image: minio/minio:latest
    networks:
      - traefik-public
    environment:
      MINIO_ROOT_USER: *********
      MINIO_ROOT_PASSWORD: ***************
    command: server --console-address ":9001" http://minio{1...4}/data
    volumes:
      - /mnt/data/minio/minio2:/data
 
  minio3:
    image: minio/minio:latest
    networks:
      - traefik-public
    environment:
      MINIO_ROOT_USER: *********
      MINIO_ROOT_PASSWORD: ***************
    command: server --console-address ":9001" http://minio{1...4}/data
    volumes:
      - /mnt/data/minio/minio3:/data

  minio4:
    image: minio/minio:latest
    networks:
      - traefik-public
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: JHY4zoQMXqbqjQ
    command: server --console-address ":9001" http://minio{1...4}/data
    volumes:
      - /mnt/data/minio/minio4:/data

networks:
  traefik-public:
    external: true
```

## Steps to Reproduce (for bugs)

Setup a swarm
Deploy stack

## Your Environment

* Version used (`minio --version`): latest
* Server setup and configuration: Docker Swarm
* Operating System and version (`uname -a`): Ubuntu 22.04 LTS

**Comment by harshavardhana** [comment]
You need to make sure to not use docker swarm, docker swarm is a terrible orchestration implementation. 

Either use docker compose or kubernetes statefulsets.

**Comment by ronnostic** [comment]
@harshavardhana Thank you for the quick response.  I understand that you seem to have strong opinions about this, but not everyone agrees with this sentiment. Many do not want or need the management overhead of Kubernetes, and Swarm + Portainer is a lightweight alternative. 

However, I did figure out a workable solution.
- added an internal network
- added env vars:
      MINIO_DISTRIBUTED_MODE_ENABLED: "yes"
      MINIO_DISTRIBUTED_NODES: minio1,minio2,minio3,minio4
- added a hostname to easch service
- deployed with `docker stack`

This is 100% working so I'll just leave this here just for anyone else who comes across this:

tags: traefik docker swarm miio letsencrypt

```
version: "3.8"

services:
  minio1:
    image: minio/minio:latest
    hostname: minio1
    networks:
      - traefik-public
      - minio-internal
    environment:
      MINIO_ROOT_USER: ***
      MINIO_ROOT_PASSWORD: ***
      MINIO_DISTRIBUTED_MODE_ENABLED: "yes"
      MINIO_DISTRIBUTED_NODES: minio1,minio2,minio3,minio4
    command: server --console-address ":9001" http://minio{1...4}/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - /mnt/data/minio/minio1:/data
    deploy:
      labels:
        - "traefik.enable=true"

        # MINIO console
        - "traefik.http.routers.minio1.tls=true"
        - "traefik.http.routers.minio1.service=minio1"
        - "traefik.http.routers.minio1.rule=Host(`minio.mydomain.com`)"
        - "traefik.http.routers.minio1.entrypoints=websecure"
        - "traefik.http.routers.minio1.tls.certresolver=leresolver"
        - "traefik.http.services.minio1.loadbalancer.server.port=9001"
        - "traefik.http.services.minio1.loadbalancer.sticky.cookie.name=stickycookie"
        - "traefik.http.services.minio1.loadbalancer.sticky.cookie.secure=true"
        # MINIO api
        - "traefik.http.routers.miniocdn1.tls=true"
        - "traefik.http.routers.miniocdn1.service=miniocdn1"
        - "traefik.http.routers.miniocdn1.rule=Host(`s3.mydomain.com`)"
        - "traefik.http.routers.miniocdn1.entrypoints=websecure"
        - "traefik.http.routers.miniocdn1.tls.certresolver=leresolver"
        - "traefik.http.services.miniocdn1.loadbalancer.server.port=9000"
        - "traefik.http.services.miniocdn1.loadbalancer.sticky.cookie.name=stickycookie"
        - "traefik.http.services.miniocdn1.loadbalancer.sticky.cookie.secure=true"
  minio2:
    image: minio/minio:latest
    hostname: minio2
    networks:
      - traefik-public
      - minio-internal
    environment:
      MINIO_ROOT_USER: ***
      MINIO_ROOT_PASSWORD: ***
      MINIO_DISTRIBUTED_MODE_ENABLED: "yes"
      MINIO_DISTRIBUTED_NODES: minio1,minio2,minio3,minio4
    command: server --console-address ":9001" http://minio{1...4}/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - /mnt/data/minio/minio2:/data
    deploy:
      labels:
        - "traefik.enable=true"

        # MINIO console
        - "traefik.http.routers.minio2.tls=true"
        - "traefik.http.routers.minio2.service=minio2"
        - "traefik.http.routers.minio2.rule=Host(`minio.mydomain.com`)"
        - "traefik.http.routers.minio2.entrypoints=websecure"
        - "traefik.http.routers.minio2.tls.certresolver=leresolver"
        - "traefik.http.services.minio2.loadbalancer.server.port=9001"
        - "traefik.http.services.minio2.loadbalancer.sticky.cookie.name=stickycookie"
        - "traefik.http.services.minio2.loadbalancer.sticky.cookie.secure=true"
        # MINIO api
        - "traefik.http.routers.miniocdn2.tls=true"
        - "traefik.http.routers.miniocdn2.service=miniocdn2"
        - "traefik.http.routers.miniocdn2.rule=Host(`s3.mydomain.com`)"
        - "traefik.http.routers.miniocdn2.entrypoints=websecure"
        - "traefik.http.routers.miniocdn2.tls.certresolver=leresolver"
        - "traefik.http.services.miniocdn2.loadbalancer.server.port=9000"
        - "traefik.http.services.miniocdn2.loadbalancer.sticky.cookie.name=stickycookie"
        - "traefik.http.services.miniocdn2.loadbalancer.sticky.cookie.secure=true"

  minio3:
    image: minio/minio:latest
    hostname: minio3
    networks:
      - traefik-public
      - minio-internal
    environment:
      MINIO_ROOT_USER: ***
      MINIO_ROOT_PASSWORD: ***
      MINIO_DISTRIBUTED_MODE_ENABLED: "yes"
      MINIO_DISTRIBUTED_NODES: minio1,minio2,minio3,minio4
    command: server --console-address ":9001" http://minio{1...4}/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - /mnt/data/minio/minio3:/data
    deploy:
      labels:
        - "traefik.enable=true"

        # MINIO console
        - "traefik.http.routers.minio3.tls=true"
        - "traefik.http.routers.minio3.service=minio3"
        - "traefik.http.routers.minio3.rule=Host(`minio.mydomain.com`)"
        - "traefik.http.routers.minio3.entrypoints=websecure"
        - "traefik.http.routers.minio3.tls.certresolver=leresolver"
        - "traefik.http.services.minio3.loadbalancer.server.port=9001"
        - "traefik.http.services.minio3.loadbalancer.sticky.cookie.name=stickycookie"
        - "traefik.http.services.minio3.loadbalancer.sticky.cookie.secure=true"
        # MINIO api
        - "traefik.http.routers.miniocdn3.tls=true"
        - "traefik.http.routers.miniocdn3.service=miniocdn3"
        - "traefik.http.routers.miniocdn3.rule=Host(`s3.mydomain.com`)"
        - "traefik.http.routers.miniocdn3.entrypoints=websecure"
        - "traefik.http.routers.miniocdn3.tls.certresolver=leresolver"
        - "traefik.http.services.miniocdn3.loadbalancer.server.port=9000"
        - "traefik.http.services.miniocdn3.loadbalancer.sticky.cookie.name=stickycookie"
        - "traefik.http.services.miniocdn3.loadbalancer.sticky.cookie.secure=true"

  minio4:
    image: minio/minio:latest
    hostname: minio4
    networks:
      - traefik-public
      - minio-internal
    environment:
      MINIO_ROOT_USER: ***
      MINIO_ROOT_PASSWORD: ***
      MINIO_DISTRIBUTED_MODE_ENABLED: "yes"
      MINIO_DISTRIBUTED_NODES: minio1,minio2,minio3,minio4
    command: server --console-address ":9001" http://minio{1...4}/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - /mnt/data/minio/minio4:/data
    deploy:
      labels:
        - "traefik.enable=true"

        # MINIO console
        - "traefik.http.routers.minio4.tls=true"
        - "traefik.http.routers.minio4.service=minio4"
        - "traefik.http.routers.minio4.rule=Host(`minio.mydomain.com`)"
        - "traefik.http.routers.minio4.entrypoints=websecure"
        - "traefik.http.routers.minio4.tls.certresolver=leresolver"
        - "traefik.http.services.minio4.loadbalancer.server.port=9001"
        - "traefik.http.services.minio4.loadbalancer.sticky.cookie.name=stickycookie"
        - "traefik.http.services.minio4.loadbalancer.sticky.cookie.secure=true"
        # MINIO api
        - "traefik.http.routers.miniocdn4.tls=true"
        - "traefik.http.routers.miniocdn4.service=miniocdn4"
        - "traefik.http.routers.miniocdn4.rule=Host(`s3.mydomain.com`)"
        - "traefik.http.routers.miniocdn4.entrypoints=websecure"
        - "traefik.http.routers.miniocdn4.tls.certresolver=leresolver"
        - "traefik.http.services.miniocdn4.loadbalancer.server.port=9000"
        - "traefik.http.services.miniocdn4.loadbalancer.sticky.cookie.name=stickycookie"
        - "traefik.http.services.miniocdn4.loadbalancer.sticky.cookie.secure=true"

networks:
  traefik-public:
    external: true
  minio-internal:
    external: true
```
