### ISSUE TITLE
[HELP] Docker configuration MINIO_SERVER_URL invalid login

### ISSUE THREAD

**Issue by QYG2297248353** [minio/minio#19487]
My `docker-compose.yml` file
```
networks:
    1panel-network:
        external: true
services:
    minio:
        command: server /data --console-address :9001 --address :9000
        container_name: ${CONTAINER_NAME}
        deploy:
            resources:
                limits:
                    cpus: ${CPUS}
                    memory: ${MEMORY_LIMIT}
        environment:
            - MINIO_API_ROOT_ACCESS=on
            - MINIO_ROOT_USER=${PANEL_MINIO_ROOT_USER}
            - MINIO_ROOT_PASSWORD=${PANEL_MINIO_ROOT_PASSWORD}
            - MINIO_BROWSER=${MINIO_BROWSER}
            - MINIO_BROWSER_LOGIN_ANIMATION=${MINIO_BROWSER_LOGIN_ANIMATION}
            - MINIO_BROWSER_SESSION_DURATION=${MINIO_BROWSER_SESSION_DURATION}
            - MINIO_BROWSER_REDIRECT=true
            - MINIO_DOMAIN=${MINIO_DOMAIN}
            - MINIO_SERVER_URL=${MINIO_SERVER_URL}
            - MINIO_BROWSER_REDIRECT_URL=${MINIO_BROWSER_REDIRECT_URL}
        healthcheck:
            interval: 30s
            retries: 3
            test:
                - CMD
                - curl
                - -f
                - -I
                - http://localhost:9000/minio/health/live
            timeout: 20s
        image: ${MINIO_IMAGE}
        labels:
            createdBy: Apps
        logging:
            driver: json-file
            options:
                max-file: "10"
                max-size: 5M
        networks:
            - 1panel-network
        ports:
            - ${HOST_IP}:${PANEL_APP_PORT_HTTP}:9001
            - ${HOST_IP}:${PANEL_APP_PORT_API}:9000
        restart: always
        volumes:
            - ${MINIO_ROOT_PATH}/data:/data
            - ${MINIO_ROOT_PATH}/certs:/root/.minio/certs
version: "3"

```
My `.env` file
```
CONTAINER_NAME="minio"
CPUS=0
HOST_IP=""
MEMORY_LIMIT=0
MINIO_BROWSER="on"
MINIO_BROWSER_LOGIN_ANIMATION="on"
MINIO_BROWSER_REDIRECT_URL=""
MINIO_BROWSER_SESSION_DURATION="6h"
MINIO_DOMAIN=""
MINIO_IMAGE="minio/minio:RELEASE.2024-04-06T05-26-02Z"
MINIO_ROOT_PATH="/home/data/minio"
MINIO_SERVER_URL=""
PANEL_APP_PORT_API=9000
PANEL_APP_PORT_HTTP=9001
PANEL_MINIO_ROOT_PASSWORD="password"
PANEL_MINIO_ROOT_USER="root"

```

Can be used and logged in normally when not using the following configuration or using `127.0.0.1` configuration.
config 1:
```
MINIO_DOMAIN=""
MINIO_SERVER_URL=""
MINIO_BROWSER_REDIRECT_URL=""
```
config 2:
```
MINIO_DOMAIN="127.0.0.1"
MINIO_SERVER_URL="http://127.0.0.1:9000"
MINIO_BROWSER_REDIRECT_URL="http://127.0.0.1:9001"
```
But I can't log in when I use the domain name as the variable value, It can be confirmed that the service starts normally, and the API and WebUI have displayed the configured domain name in the log.

I want to see the specific log in the container, but I can't find the location of the log.

I can't log in normally when I use the following configuration, but I can access the login page normally.
```
MINIO_DOMAIN="f.demo.com"
MINIO_SERVER_URL="http://f.demo.com"
MINIO_BROWSER_REDIRECT_URL="http://minio.demo.com"
```
For the specific forwarding path, I drew a picture for reference. Although I can use Java SDK service normally through reverse proxy without configuring the domain name, when Minio WebUI shares my file, it shows that 127.0.0.1 can't share the file normally even if it is changed to the corresponding domain name, prompting that the verification is abnormal. And I don't want to replace it manually every time.
![Minio](https://github.com/minio/minio/assets/56836951/da34ab6d-2853-4f9e-9cdf-7ae634f6dba2)
