### ISSUE TITLE
Random invalid session and inconsistent service accounts

### ISSUE THREAD

**Issue by pschichtel** [minio/minio#19510]
This is a follow up to #19217 and #19201

After my vacation I just verified the state of the minio installation again after the previous issues.

## Expected Behavior

Once logged in I'd expect not to randomly receive "invalid session" warnings or to get randomly logged out when navigating to certain pages (e.g. the Site Replication config page).

I would also expect to the same service accounts on my root user every time I refresh the Access Keys page (or when directly accessing `/api/v1/service-accounts`).

## Current Behavior

I randomly get invalid session responses ("The Access Key Id you provided does not exist in our records.") from the backend and on some pages, that leads to a redirect to the login page.

I also get a different list service accounts every time I refresh, sometimes it doesn't even include the site-replicator-0 account, which would explain why I'm still seeing #19217. Actually in my tests now by refreshing `/api/v1/service-accounts` a bunch of times, I rarely get all 4 service accounts.

The backup site still occasionally logs this as in #19217:

```
minio-1  | API: SRPeerBucketOps(bucket=154a22a1-8dca-4e64-98d8-687376a04d32)
minio-1  | Time: 16:58:03 UTC 04/15/2024
minio-1  | DeploymentID: bc54da3b-88f4-4a0d-a9d4-2365bf5a0d80
minio-1  | RequestID: 17C68294B9A6D50A
minio-1  | RemoteHost: 
minio-1  | Host: 
minio-1  | UserAgent: MinIO (linux; amd64) madmin-go/2.0.0
minio-1  | Error: Site replication error(s): 
minio-1  | 'ConfigureReplication' on site Production (bf3123cf-9753-4ea4-a46f-535599899c4c): failed(Backup->Production: Bucket target creation error: Remote service endpoint offline, target bucket: 154a22a1-8dca-4e64-98d8-687376a04d32 or remote service credentials: site-replicator-0 invalid 
minio-1  | 	The Access Key Id you provided does not exist in our records.) (*errors.errorString)
minio-1  |        4: internal/logger/logger.go:259:logger.LogIf()
minio-1  |        3: cmd/logging.go:30:cmd.adminLogIf()
minio-1  |        2: cmd/admin-handlers-site-replication.go:142:cmd.adminAPIHandlers.SRPeerBucketOps()
minio-1  |        1: net/http/server.go:2136:http.HandlerFunc.ServeHTTP()
```

## Steps to Reproduce (for bugs)

I'm still not sure how I arrived at this state, I assume by enabling site replication.

I've checked that KES is working on both the production and the backup site. At this point I'm not even able to disable site replication on the production site, because I get constantly logged out (redirected to login page) from the page.

The single-node backup instance does not observe this behavior. there, I never get invalid session responses, I always get the same 4 service accounts on the root user (including site-replicator-0) and I can also access the Site Replication page.

## Context

It makes using the minio console difficult. I assume, replication from backup to production would not reliably work (or be a lot slower), but that's not currently something I need to do.

Interestingly `mcli admin user svcacct list production admin` always returns the complete list of service accounts for my root user, although not always in the same order, but that doesn't matter. S3 clients in general don't seem to be affected, at least not functionally.

To elaborate on the setup:

2 sites:

1. site (production): 5 nodes, each with 1 disk, deployed via minio-operator to k8s, kes configured against a vault running in the same k8s
2. site (backup): 1 node with 1 disk, deployed via docker-compose, kes configured with filesystem, containing the necessary keys from vault (to decouple the backup site from the k8s).

The keys between the KES deployments are identical (replicated files from production site can be decrypted on backup site. The production KES setup is responsive and can successfully access the vault (I created and deleted a test key to confirm).

## Your Environment

* Version used (`minio --version`): `RELEASE.2024-04-06T05-26-02Z`
* Server setup and configuration: deployed by operator (5.0.14), replicating to a single-node setup on the same version deployed with docker-compose.
* Operating System and version (`uname -a`): `Linux  6.1.0-17-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.69-1 (2023-12-30) x86_64 GNU/Linux`

**Comment by jiuker** [comment]
@pschichtel Do you only have one KES server for production?

**Comment by pschichtel** [comment]
@jiuker production has 3, backup has 1

**Comment by jiuker** [comment]
> @jiuker production has 3, backup has 1

Does the 3 KES server have the same keys for production? @pschichtel

**Comment by pschichtel** [comment]
They are all connected to the same vault (with a dedicated V2 KV engine for minio), so I'd assume so. How can I check?

**Comment by jiuker** [comment]
Could you check the key `site-replicator-0`'s value have changed always?  @pschichtel

**Comment by pschichtel** [comment]
Not sure what you mean

**Comment by jiuker** [comment]
> Not sure what you mean

Check for overlapping value assignments between two clients

**Comment by pschichtel** [comment]
Sorry for being confused!

> Could you check the key site-replicator-0's value have changed always?

By key, do you mean a KES key or an access key/secret access key? There is no "site-replicator-0" KES key, so I assume access key. What do you mean by "value" then?

> Check for overlapping value assignments between two clients

What do you mean by "value assignments"? And what clients?


I just checked with mcli again (`mcli admin user svcacct info production site-replicator-0`) and every now and then I get `mcli: <ERROR> Unable to get information of the specified service account. The specified service account is not found (Specified service account does not exist).`, so there must be an instance that doesn't have the account I guess. Didn't notice it yesterday weirdly. If it doesn't fail with said error, then it returns this consistently:

```
AccessKey: site-replicator-0
ParentUser: root-user
Status: on
Name: 
Description: 
Policy: implied
Expiration: no-expiry
```

**Comment by jiuker** [comment]
I only found a strange case where when I open two minio login pages in one browser at the same time, there have one said that `{"detailedMessage":"Access Denied.","message":"invalid session"}
`, but I can access it normally with two browsers. I don't know if it's similar to your case? @pschichtel

**Comment by pschichtel** [comment]
@jiuker I have the occasional case, where the page after login stays blank, because `/api/v1/session` returns `invalid session` / `The Access Key Id you provided does not exist in our records.`. I don't need a two tabs/browsers for that.

I think you case sounds like a race condition on the shared cookies/localStorage/sessionStorage between the browser tabs, that are not shared between browsers.

**Comment by jiuker** [comment]
> @jiuker I have the occasional case, where the page after login stays blank, because `/api/v1/session` returns `invalid session` / `The Access Key Id you provided does not exist in our records.`. I don't need a two tabs/browsers for that.
> 
> I think you case sounds like a race condition on the shared cookies/localStorage/sessionStorage between the browser tabs, that are not shared between browsers.

Yeah. Will return back to login page for `/api/v1/session` return that `{"detailedMessage":"Access Denied.","message":"invalid session"}` when fresh the page. It looks like your case. So I guess that could be a console issue. What's the page you view when that happen. @pschichtel

**Comment by pschichtel** [comment]
@jiuker I don't think it is limited to a specific page, I've seen it happen on several different pages.

> So I guess that could be a console issue.

I'm not so sure anymore, because I get errors with mcli too, that doesn't go through the console, right?

**Comment by harshavardhana** [comment]
We can't reproduce any of the issues reported here.

**Comment by pschichtel** [comment]
How can I properly clear replication settings from both sites? then I could test the production cluster without site replication and see if that helps.

**Comment by poornas** [comment]
$ mc admin replicate remove sitea siteb  --force

**Comment by pschichtel** [comment]
I just noticed, even the replication rules on buckets are completely inconsistent from refresh to refresh.

@poornas thanks, I'll try that next week.

**Comment by pschichtel** [comment]
Bucket versioning is also affected. it seems like everything somehow related to site replication is completely inconsistent between the nodes of the production cluster. It also seems to have gotten worse since I last checked last week.

**Comment by pschichtel** [comment]
@poornas I removed the backup site from replication and it's all fine now. Should the `site-replicator-0` account disappear? Or should I clean that account up before re-enabling replication?

**Comment by jiuker** [comment]
Remove `site-replication` and `site-replicator-0` account disappear. You cannot remove that account, it's interval account.

**Comment by pschichtel** [comment]
Are you saying it should automatically disappear after removing site-replication? Because it hasn't so far, neither in the production site nor in the backup site. Both sites don't have any other replication rules.

So I'll delete the service accounts to have a clean state.

**Comment by jiuker** [comment]
> Are you saying it should automatically disappear after removing site-replication? Because it hasn't so far, neither in the production site nor in the backup site. Both sites don't have any other replication rules.
> 
> So I'll delete the service accounts to have a clean state.

Yeah. It should disappear. If not, you can try delete it for I didn't reproduce your case.

**Comment by pschichtel** [comment]
I removed the accounts, I'll upgrade both instances to latest now and then setup replication again in the evening.

**Comment by pschichtel** [comment]
I remember @harshavardhana saying something about this in a past issue: The /v1/service-accounts endpoint is rather slow (400-900 ms "wait" time in the browser) given that this is a small cluster (5 nodes) and only 3 service accounts exist and my connection is basically local, this feels noticeable slow in the UI. This is still the case even after disabling replication. Is the timing within a normal range or would this be worth investigating? I originally thought this is caused by the replication problem, but apparently it isn't.

**Comment by harshavardhana** [comment]
> I remember @harshavardhana saying something about this in a past issue: The /v1/service-accounts endpoint is rather slow (400-900 ms "wait" time in the browser) given that this is a small cluster (5 nodes) and only 3 service accounts exist and my connection is basically local, this feels noticeable slow in the UI. This is still the case even after disabling replication. Is the timing within a normal range or would this be worth investigating? I originally thought this is caused by the replication problem, but apparently it isn't.

Can you share mc admin trace -a output while browsing this element in the UI?

**Comment by pschichtel** [comment]
It's currently pretty noisy, I can do that in the evening. Or would there be a way to filter its output?

**Comment by klauspost** [comment]
Tracing only the call itself will not show what is going on, so filtering is not too feasible here.

You can try `--response-duration=20ms` to filter out the fastest requests - but it may not have what we need.

**Comment by pschichtel** [comment]
@harshavardhana https://gist.github.com/pschichtel/c62d0eb9e46adb5472bf103a4b9cac85

I filtered out a bunch of log lines obviously related to S3 file accesses.

**Comment by pschichtel** [comment]
OK so I wiped my backup site and enabled replication again. Replication has completed over night. /service-accounts is still slow (possibly even a bit slower, but not sure), but so far I haven't observed any invalid session responses and the list of service accounts in production seems to be consistent.

**Comment by harshavardhana** [comment]
```
2024-04-29T18:42:17.368 [200 OK] admin.ListServiceAccounts production-2.prod-hl.minio.svc.cluster.local:9000/minio/admin/v3/list-service-accounts?user=  10.16.101.254    70.091ms     ⇣  70.085266ms  ↑ 242 B ↓ 259 B
2024-04-29T18:42:17.512 [200 OK] admin.InfoServiceAccount production-1.prod-hl.minio.svc.cluster.local:9000/minio/admin/v3/info-service-account?accessKey=access-key-c  10.16.101.254    33.786ms     ⇣  33.778568ms  ↑ 242 B ↓ 330 B
2024-04-29T18:42:17.621 [200 OK] admin.InfoServiceAccount production-0.prod-hl.minio.svc.cluster.local:9000/minio/admin/v3/info-service-account?accessKey=access-key-a  10.16.101.254    70.136ms     ⇣  70.129695ms  ↑ 242 B ↓ 516 B
2024-04-29T18:42:17.765 [200 OK] admin.InfoServiceAccount production-3.prod-hl.minio.svc.cluster.local:9000/minio/admin/v3/info-service-account?accessKey=access-key-b  10.16.101.254    73.995ms     ⇣  73.985804ms  ↑ 242 B ↓ 611 B
```

Looks like wrong implementation by Console UI. Going serially per key info at a time.

**Comment by pschichtel** [comment]
That's what I thought when I saw the trace lines. Should a create an issue over at minio/console or will you handle that "internally" ?

**Comment by harshavardhana** [comment]
Will handle it internally.

**Comment by pschichtel** [comment]
I've just applied yesterday's minio release to the sites and that also hasn't reintroduced the issue. I'll monitor this for the rest of the week and if it stays without issues I'll close the issue.

**Comment by harshavardhana** [comment]
Checking how things are going @pschichtel ?

**Comment by harshavardhana** [comment]
> Will handle it internally.

sent PRs for this newer console release will handle these changes without making double the calls.

**Comment by harshavardhana** [comment]
Closing this since I haven't heard and assuming this has been resolved.

**Comment by pschichtel** [comment]
Yeah I haven't had issues so far.

**Comment by pschichtel** [comment]
@harshavardhana now after the upgrade to `RELEASE.2024-05-01T01-11-10Z` I once again have the issue that service accounts seem to be inconsistent between nodes (`/api/v1/service-accounts` reporting different sets). However this time I don't have any "invalid session" issues so far. At least the site-replicator-0 service account is consistently contained in the response of the service accounts api and so far the backup site is not complaining either.

I wonder if this is something caused by the upgrade process of the operator?

Should I open a new issue for this?

**Comment by pschichtel** [comment]
At least it seems to be limited to the console API, running `mcli admin user svcacct list production root` continuously in a loop hasn't shown any differences except for order.

**Comment by pschichtel** [comment]
@harshavardhana after upgrading to `RELEASE.2024-05-10T01-41-38Z` today the console is once again barely usable due to random invalid session and inconsistent service accounts. S3 seems unaffected so far (site replication to backup is unaffected and `mcli admin user svcacct list production root` has been showing consistent results for a while now.)

I'm now convinced that that the upgrade as performed by the operator seems to cause or at least worsen this issue.

Should I create a new issue? possibly over at minio/console ?

**Comment by harshavardhana** [comment]
This generally I don't it to occur unless someone actively wipes your credentials.

**Comment by harshavardhana** [comment]
Can you collect both sites all their backend .minio.sys folder and share it with us ?

**Comment by pschichtel** [comment]
@harshavardhana Seems there is quite a bit of information in there that I don't think I can just share. Is it possible to limit the requested files? Otherwise I'd first have to clear internally if it's ok to share this stuff.

What I noticed while poking around:

* deleting a service account via minio client works and is correctly reflected in the /service-account response (in those cases that don't fail with "invalid session")
* it doesn't matter which of the nodes receive the request, they all randomly fail with invalid session. (I assume they internally redistribute the requests?)
* the service account files in .minio.sys seem reasonably similar
* none of the service accounts have expiry dates, but in the /service-accounts endpoint some say `"expiration": "0001-01-01T00:00:00Z"` and others say `"expiration": "1970-01-01T00:00:00Z"`. not sure what that is about.
* the /service-accounts endpoint is currently all or nothing: either it shows invalid session or it shows all service accounts. I'd say ~2/3 of the time it fails with invalid session.

**Comment by pschichtel** [comment]
Ha... I found the offender. I slowly, one-by-one went through the pods (from last to first similar to the sts controller), deleted them and let the sts controller recreate them. between each pod I repeatedly checked the the /service-accounts endpoint. pods 4, 3 and 2 did nothing, restarting the pod 1 completely resolved the issue.

**Comment by harshavardhana** [comment]
> Ha... I found the offender. I slowly, one-by-one went through the pods (from last to first similar to the sts controller), deleted them and let the sts controller recreate them. between each pod I repeatedly checked the the /service-accounts endpoint. pods 4, 3 and 2 did nothing, restarting the pod 1 completely resolved the issue.

Do you have logs from this pod before deleting it ?

**Comment by pschichtel** [comment]
I do, but I don't think there was anything of interest. I'll check...

**Comment by pschichtel** [comment]
here you go: [production-1-logs.txt](https://github.com/minio/minio/files/15279785/production-1-logs.txt)

I noticed that the cluster once lost the quorum. The log file btw includes both the update and my restart the fixed the problem.

**Comment by pschichtel** [comment]
Minor update on this: Apparently this happened again at some point in the last 3 weeks. Sadly this time I don't know which node was affected, but the upgrade to yesterdays's release resolved the issue for now (probably because all nodes got restarted). I'll keep monitoring.

**Comment by pschichtel** [comment]
I once again had this after the upgrade to the newest release. Restarting the nodes one by one once again solved it.

**Comment by harshavardhana** [comment]
I suspect this is due to #19905 and has been around since 03-28 release

**Comment by pschichtel** [comment]
Timing-wise that sounds reasonable. Will the fix help immediately with the next upgrade or will it require me to cycle the deployment one more time?

**Comment by pschichtel** [comment]
Just upgraded to `RELEASE.2024-06-11T03-13-30Z` and immediately after the deployment has converged I was practically unable to login until I cycled the 4th node. after cycling additional nodes afterwards the situation got worse for a moment for now I once again have a stable with no failing requests in the console. I'll report back to you if it stays this way.

**Comment by klauspost** [comment]
@pschichtel Don't do rolling upgrades.

**Comment by pschichtel** [comment]
@klauspost how am I supposed to do upgrades with the operator?

**Comment by pschichtel** [comment]
Is there any documentation on the topic of upgrades in kubernetes with the operator at all? The operator seems to just do a StatefulSet update which in turn triggers a rolling upgrade last to first (that's k8s' default strategy iirc). The main documentation on upgrades doesn't seem appliable to a) containerized deployments and b) kubernetes deployments, given that overwriting a binary in a container isn't really useful, when the overwrite is lost after restarting the process.

Also does this apply only to rolling _upgrades_ or to rolling restarts in general ? because I'm pretty sure I triggered this issue with just a rolling _restart_ on the exact same version.

**Comment by harshavardhana** [comment]
Operator upgrades first the binary inside the container via pushing the binary directly to the pods, once the pod is restarted() it proceeds to updating the container image which does rolling. 

If the first step fails, I suspect the operator is still doing a statefulset update.

**Comment by harshavardhana** [comment]
So your operator logs will have some information regarding this.

**Comment by pschichtel** [comment]
I'll can check that

**Comment by pschichtel** [comment]
I've seen this line both in this production multi-node setup as well as in a homelab deployment also using the operator:

```
E0611 ...       1 main-controller.go:1500] error syncing 'minio/tenant': Tar file extraction failed for file index: 2, with: EOF
```

**Comment by harshavardhana** [comment]
> I've seen this line both in this production multi-node setup as well as in a homelab deployment also using the operator:
> 
> ```
> E0611 ...       1 main-controller.go:1500] error syncing 'minio/tenant': Tar file extraction failed for file index: 2, with: EOF
> ```

yeah this means upgrade would have failed.

**Comment by harshavardhana** [comment]
this is the exact reason why you face this problem.

**Comment by pschichtel** [comment]
I'd argue the operator would better stop and enter an error state, when a correct upgrade is not possible.

How can we find the cause of the `Tar file extraction failed for file index: 2, with: EOF` error? As I said: It happens in completely independent setups with different networks and different host systems (different hardware, different kernel, different distro), however they are both in k0s and they both use a similarly configured tenant created through the helm chart, the values:

```yaml
tenant:
  image:
    repository: quay.io/minio/minio
    tag: 'RELEASE.2024-06-11T03-13-30Z'
  name: tenant
  configuration:
    name: credentials
  pools:
  - name: main
    servers: 5
    volumesPerServer: 1
    storageClassName: ''
    size: 123123123
    labels:
      velero.io/exclude-from-backup: "true"
  metrics:
    enabled: true
  certificate:
    requestAutoCert: true
  env:
  - name: MINIO_OPERATOR_TLS_ENABLE
    value: "off"
  - name: MINIO_DOMAIN
    value: "minio.example.org"
  - name: MINIO_BROWSER_REDIRECT_URL
    value: "https://console.minio.example.org"
  - name: MINIO_SERVER_URL
    value: "https://minio.example.org"
  log:
    disabled: true
  prometheus:
    disabled: true
  prometheusOperator: true
```

**Comment by pschichtel** [comment]
also there is no NetworkPolicy and also no outbound firewall in general, so there is no reason why the operator shouldn't be able to download and distribute the minio binaries.

**Comment by pschichtel** [comment]
@harshavardhana todays minio release seems to have a few changes relevant to this issue (especially the binary validation). is it worth testing with this version or would the operator likely still fail to update the binary?

**Comment by harshavardhana** [comment]
> @harshavardhana todays minio release seems to have a few changes relevant to this issue (especially the binary validation). is it worth testing with this version or would the operator likely still fail to update the binary?

Not really that seems to be a different problem, I will investigate it later coming week.

**Comment by pschichtel** [comment]
OK, great. Tag me if you need something tested.

**Comment by harshavardhana** [comment]
I think k0s is causing these problems, what is your container runtime?

**Comment by pschichtel** [comment]
k0s' default: containerd/runc, nothing fancy. The affected clusters are on k0s 1.29.x and 1.30.x

**Comment by pschichtel** [comment]
This is the k0sctl config I use to deploy the single-node home lab:

```yaml
apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
  - ssh:
      address: ...
      user: ...
      port: ...
      keyPath: ...
    role: single
    privateInterface: ...
    privateAddress: &ip ...
    # This currently won't work: https://github.com/k0sproject/k0sctl/issues/476
    # installFlags: ['--kubelet-extra-args="--cpu-manager-policy=static"']
    installFlags: ['--profile=enable-swap']
  k0s:
    version: v1.30.2+k0s.0
    dynamicConfig: false
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: ClusterConfig
      metadata:
        name: k0s
      spec:
        api:
          address: *ip
          externalAddress: ...
          k0sApiPort: 9443
          port: 6443
          sans:
          - ...
          - *ip
          - 127.0.0.1
        extensions:
          helm:
            charts: null
            repositories: null
          storage: {}
        installConfig:
          users:
            etcdUser: etcd
            kineUser: kube-apiserver
            konnectivityUser: konnectivity-server
            kubeAPIserverUser: kube-apiserver
            kubeSchedulerUser: kube-scheduler
        network:
          calico: null
          dualStack: {}
          kubeProxy:
            mode: iptables
          kuberouter:
            autoMTU: true
            mtu: 0
            # removing these will break networking
            peerRouterASNs: ""
            peerRouterIPs: ""
          podCIDR: 10.244.0.0/16
          provider: kuberouter
          serviceCIDR: 10.96.0.0/12
        storage:
          etcd:
            externalCluster: null
            peerAddress: *ip
          type: etcd
        workerProfiles:
        - name: enable-swap
          values:
            memorySwap:
              swapBehavior: LimitedSwap
            featureGates:
              NodeSwap: true
```

most of the values are defaults
