### ISSUE TITLE
mnio always oom

### ISSUE THREAD

**Issue by waymen** [minio/minio#19592]
k8s config:
```
      containers:
        - name: minio
          image: minio/minio:RELEASE.2024-04-18T19-09-19Z
          command:
            - /bin/bash
            - -c
          args:
            - minio server /data --console-address :9001
          resources:
            limits:
              memory: "1Gi"
```
