### ISSUE TITLE
Can't deploy on Docker Swarm

### ISSUE THREAD

**Issue by asijoumi** [minio/minio#19610]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

Hi ! I used the docker-compose.yaml located on the documentation (https://github.com/minio/minio/blob/master/docs/orchestration/docker-compose/docker-compose.yaml) and change it a little bit. But I was unable to used it on docker swarm.

## Steps to Reproduce (for bugs)

docker-compose.yml

```yaml
version: '3.7'

x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2024-04-18T19-09-19Z
  command: server --console-address ":9001" http://minio{1...4}/data
  healthcheck:
    test: ["CMD", "mc", "ready", "local"]
    interval: 5s
    timeout: 5s
    retries: 5

services:
  minio1:
    <<: *minio-common
    volumes:
      - minio1:/data
    networks:
      minio:
        aliases:
          - minio1
  minio2:
    <<: *minio-common
    volumes:
      - minio2:/data
    networks:
      minio:
        aliases:
          - minio2
  minio3:
    <<: *minio-common
    volumes:
      - minio3:/data
    networks:
      minio:
        aliases:
          - minio3
  minio4:
    <<: *minio-common
    volumes:
      - minio4:/data
    networks:
      minio:
        aliases:
          - minio4

volumes:
  minio1:
  minio2:
  minio3:
  minio4:

networks:
  minio:
    driver: overlay

```

To easily test it, you can use https://labs.play-with-docker.com

```bash
docker stack deploy -c minio.yaml minio
```

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by jiuker** [comment]
What's the error log ? @asijoumi

**Comment by asijoumi** [comment]
Hi @jiuker, I have this : 

```
minio_minio1.1.r19hdu824jv3@worker2    | Error: Unable to resolve DNS for http://minio3/data: lookup minio3 on 127.0.0.11:53: no such host (*fmt.wrapError)
minio_minio1.1.r19hdu824jv3@worker2    |        host="minio3", elapsedTime="1 second elapsed"
minio_minio1.1.r19hdu824jv3@worker2    |       10: internal/logger/logonce.go:118:logger.(*logOnceType).logOnceIf()
minio_minio1.1.r19hdu824jv3@worker2    |        9: internal/logger/logonce.go:149:logger.LogOnceIf()
minio_minio1.1.r19hdu824jv3@worker2    |        8: cmd/logging.go:82:cmd.bootLogOnceIf()
minio_minio1.1.r19hdu824jv3@worker2    |        7: cmd/endpoint.go:869:cmd.PoolEndpointList.UpdateIsLocal()
minio_minio1.1.r19hdu824jv3@worker2    |        6: cmd/endpoint.go:1007:cmd.CreatePoolEndpoints()
minio_minio1.1.r19hdu824jv3@worker2    |        5: cmd/endpoint-ellipses.go:508:cmd.createServerEndpoints()
minio_minio1.1.r19hdu824jv3@worker2    |        4: cmd/server-main.go:344:cmd.serverHandleCmdArgs()
minio_minio1.1.r19hdu824jv3@worker2    |        3: cmd/server-main.go:687:cmd.serverMain.func2()
minio_minio1.1.r19hdu824jv3@worker2    |        2: cmd/server-main.go:512:cmd.bootstrapTrace()
minio_minio1.1.r19hdu824jv3@worker2    |        1: cmd/server-main.go:683:cmd.serverMain()
```

**Comment by jiuker** [comment]
I think that's network issue. Not for minio.

**Comment by asijoumi** [comment]
It seems strange that the exemple of the documentation won't work with Docker Swarm...

Ok, do you have an exemple of deployment of minio with docker-compose ?

**Comment by jiuker** [comment]
> It seems strange that the exemple of the documentation won't work with Docker Swarm...
> 
> Ok, do you have an exemple of deployment of minio with docker-compose ?

You mentioned one could be ok.

**Comment by asijoumi** [comment]
@jiuker, it is not woking ...

I copied the docker-compose.yml from the documentation : 

```yml
version: '3.7'

# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2024-04-18T19-09-19Z
  command: server --console-address ":9001" http://minio{1...4}/data{1...2}
  expose:
    - "9000"
    - "9001"
  # environment:
    # MINIO_ROOT_USER: minioadmin
    # MINIO_ROOT_PASSWORD: minioadmin
  healthcheck:
    test: ["CMD", "mc", "ready", "local"]
    interval: 5s
    timeout: 5s
    retries: 5

# starts 4 docker containers running minio server instances.
# using nginx reverse proxy, load balancing, you can access
# it through port 9000.
services:
  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - data1-1:/data1
      - data1-2:/data2

  minio2:
    <<: *minio-common
    hostname: minio2
    volumes:
      - data2-1:/data1
      - data2-2:/data2

  minio3:
    <<: *minio-common
    hostname: minio3
    volumes:
      - data3-1:/data1
      - data3-2:/data2

  minio4:
    <<: *minio-common
    hostname: minio4
    volumes:
      - data4-1:/data1
      - data4-2:/data2

  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  data1-1:
  data1-2:
  data2-1:
  data2-2:
  data3-1:
  data3-2:
  data4-1:
  data4-2:
```

![Capture web_25-4-2024_154110_labs play-with-docker com](https://github.com/minio/minio/assets/25631702/3a538c5a-bbf6-4808-9d9b-f0d9475d6840)

Docker compose and Docker Swarm are not the same. So you do have an example for Docker Swarm ?

**Comment by jiuker** [comment]
> @jiuker, it is not woking ...
> 
> I copied the docker-compose.yml from the documentation :
> 
> ```yaml
> version: '3.7'
> 
> # Settings and configurations that are common for all containers
> x-minio-common: &minio-common
>   image: quay.io/minio/minio:RELEASE.2024-04-18T19-09-19Z
>   command: server --console-address ":9001" http://minio{1...4}/data{1...2}
>   expose:
>     - "9000"
>     - "9001"
>   # environment:
>     # MINIO_ROOT_USER: minioadmin
>     # MINIO_ROOT_PASSWORD: minioadmin
>   healthcheck:
>     test: ["CMD", "mc", "ready", "local"]
>     interval: 5s
>     timeout: 5s
>     retries: 5
> 
> # starts 4 docker containers running minio server instances.
> # using nginx reverse proxy, load balancing, you can access
> # it through port 9000.
> services:
>   minio1:
>     <<: *minio-common
>     hostname: minio1
>     volumes:
>       - data1-1:/data1
>       - data1-2:/data2
> 
>   minio2:
>     <<: *minio-common
>     hostname: minio2
>     volumes:
>       - data2-1:/data1
>       - data2-2:/data2
> 
>   minio3:
>     <<: *minio-common
>     hostname: minio3
>     volumes:
>       - data3-1:/data1
>       - data3-2:/data2
> 
>   minio4:
>     <<: *minio-common
>     hostname: minio4
>     volumes:
>       - data4-1:/data1
>       - data4-2:/data2
> 
>   nginx:
>     image: nginx:1.19.2-alpine
>     hostname: nginx
>     volumes:
>       - ./nginx.conf:/etc/nginx/nginx.conf:ro
>     ports:
>       - "9000:9000"
>       - "9001:9001"
>     depends_on:
>       - minio1
>       - minio2
>       - minio3
>       - minio4
> 
> ## By default this config uses default local driver,
> ## For custom volumes replace with volume driver configuration.
> volumes:
>   data1-1:
>   data1-2:
>   data2-1:
>   data2-2:
>   data3-1:
>   data3-2:
>   data4-1:
>   data4-2:
> ```
> 
> ![Capture web_25-4-2024_154110_labs play-with-docker com](https://private-user-images.githubusercontent.com/25631702/325634407-3a538c5a-bbf6-4808-9d9b-f0d9475d6840.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNTMyOTUsIm5iZiI6MTcxNDA1Mjk5NSwicGF0aCI6Ii8yNTYzMTcwMi8zMjU2MzQ0MDctM2E1MzhjNWEtYmJmNi00ODA4LTlkOWItZjBkOTQ3NWQ2ODQwLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNVQxMzQ5NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMmI1N2FmYjM3M2I4YzZhZjY5MzdmMTY1ZmVkY2FjNjNjZmYwZTk0MTRhN2RmMThlYzc4MTA5ZjdmNWU0ZTMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vZd76JwjSXcG07JkxqttLobgpkC3SzA66cMlwWjeJg4)
> 
> Docker compose and Docker Swarm are not the same. So you do have an example for Docker Swarm ?

You need to check your host. Like firework or others.

**Comment by klauspost** [comment]
It seems like something is wrong with your environment, since `minio1` hosts cannot be resolved.

**Comment by asijoumi** [comment]
It's strange ... You can test this example : 

```yml
version: '3.7'

x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2024-04-18T19-09-19Z
  command: server --console-address ":9001" http://minio_minio{1...4}/data
  networks:
    - minio
  healthcheck:
    test: ["CMD", "mc", "ready", "local"]
    interval: 5s
    timeout: 5s
    retries: 5

services:
  minio1:
    <<: *minio-common
    volumes:
      - minio1:/data
  minio2:
    <<: *minio-common
    volumes:
      - minio2:/data
  minio3:
    <<: *minio-common
    volumes:
      - minio3:/data
  minio4:
    <<: *minio-common
    volumes:
      - minio4:/data

  nginx:
    image: nginx:1.19.2-alpine
    networks:
      - minio
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4

volumes:
  minio1:
  minio2:
  minio3:
  minio4:

networks:
  minio:
    driver: overlay
    attachable: true
```

After that run : 

```shell
docker run --rm -it --network=minio_minio node:18-alpine sh
```

Then : 

```shell
apk add curl
```

And : 

```shell
curl http://minio_nginx
```

We got an answer from nginx .. It's the same docker stack. Docker was able to resolve the nginx domain name but not the minio ?
