### ISSUE TITLE
auth v2 not available anymore (which means - AWS Java SDK V2 cannot connect)

### ISSUE THREAD

**Issue by radekapreel** [minio/minio#19720]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior
Ability to set auth to v2 via some configuration property.
The [docs](https://min.io/docs/minio/linux/administration/identity-access-management.html) state that:
```
The process of verifying the identity of a connecting client. MinIO requires clients authenticate using [AWS Signature Version 4 protocol](https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-authenticating-requests.html) with support for the deprecated Signature Version 2 protocol.
```

## Current Behavior
Only v4 works. Or at least multiple different SO topics point to the fact that MinIO dosn't accept auth v2 and that's why I'm getting those errors:
- The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256. (Service: S3, Status Code: 400...
- The specified bucket is not valid

And yes, that bucket is valid, because the MinIO JAVA client uses literally the same string as a bucket name and it works

## Possible Solution
Bring back the v2 support

## Steps to Reproduce (for bugs)
1. Start minio with a docker compose:
```
version: '3'

services:
  minio:
    image: docker.io/bitnami/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - minionetwork
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=your_username
      - MINIO_ROOT_PASSWORD=your_pasword
      - MINIO_DEFAULT_BUCKETS=test-minio-s3

networks:
  minionetwork:
    driver: bridge

volumes:
  minio_data:
    driver: local
```

2. setup aws s3 java client v2
```
        S3Client client = S3Client.builder()
                .endpointOverride(URI.create(config.getUrl()))
                .httpClientBuilder(ApacheHttpClient.builder())
                .credentialsProvider(
                        StaticCredentialsProvider.create(
                                AwsBasicCredentials.builder()
                                        .accessKeyId(config.getUsername())
                                        .secretAccessKey(config.getPassword())
                                        .build()
                        )
                )
                .build();
```

3. try to upload a document
```
        PutObjectRequest objectRequest = PutObjectRequest.builder()
                .bucket(config.getBucketName())
                .key(info.getPath())
                .build();

        InputStream bais = new BufferedInputStream(info.getContent());

        final var putObjectResponse = client.putObject(objectRequest,
                RequestBody.fromInputStream(bais, bais.available())
        );

        bais.close();
```

4. Observe error:
```
software.amazon.awssdk.services.s3.model.S3Exception: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256. (Service: S3, Status Code: 400, Request ID: 17CE2050B24A0BDF)

```

## Context
This guy already described this:
https://stackoverflow.com/questions/78444784/aws-java-sdk-2-putobject-minio-the-authorization-mechanism-you-have-provide

My question is: Is there any working example of a minio server working with a new version of AWS Java SDK (V2)?
There seems to be a problem with the V2 SDK using V2 auth by default and I didn't find any way to change that behavior

I'd be happy with either:
changing the client to work with auth v4
changing the server to work with auth v2

## Your Environment

* Version used 2024-05-10T01:41:38Z (taken from the UI)
* Server setup and configuration: visible in the docker compose
* Operating System and version: not relevant
