### ISSUE TITLE
Time Zone Settings Not Effective in Docker Container

### ISSUE THREAD

**Issue by freemankevin** [minio/minio#19760]
I am encountering an issue where the time zone settings in the MinIO Docker container do not take effect. I have tried setting the time zone using both the TZ environment variable and by mapping the `/etc/localtime` file, but the container still does not reflect the correct time zone (Asia/Shanghai).

### Steps to Reproduce
1. Pull the latest MinIO Docker image.
2. Configure `docker-compose.yml` with the necessary time zone settings.
3. Run the container using `docker-compose up`.
4. Check the time inside the container using `docker exec -it [container_name] date`.

### Expected Behavior
The time inside the container should reflect the Asia/Shanghai time zone when checked.

### Actual Behavior
The container time does not change and does not reflect the Asia/Shanghai time zone.

### Environment Details
- MinIO Version: minio/minio:latest
- Docker Version: v25.0.5
- Docker Compose Version: v2.24.5
- Operating System and Version:  MacBook M2 

### Configuration Used
```yaml
# version: '3.8'

services:
  minio:
    image: minio/minio:latest
    volumes:
      - ./data:/data
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - TZ=Asia/Shanghai
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    command: server /data --console-address ":9001"
```

**Comment by harshavardhana** [comment]
We do not care about your local tz. All time in MinIO is UTC

**Comment by DanielBoettner** [comment]
@FreemanKevin 

You can try the following (works for me).
You can obviously change the default for the build arg to 'Asia/Shanghai'

For minio/minio

```Dockerfile
ARG TZ=Europe/Berlin
# Stage 1: Use a Debian-based image to download and set up the timezone files
FROM debian:latest AS builder
ARG TZ
ENV TZ=${TZ}

# Install tzdata package and create necessary timezone files
RUN apt-get update && \
    apt-get install -y tzdata && \
    ln -sf /usr/share/zoneinfo/${TZ} /etc/localtime && \
    echo "${TZ}" > /etc/timezone

# Stage 2: Start with the official MinIO image
FROM minio/minio:latest
ARG TZ
ENV TZ=${TZ}
# Copy timezone files from the builder stage
COPY --from=builder /etc/localtime /etc/localtime
COPY --from=builder /etc/timezone /etc/timezone
COPY --from=builder /usr/share/zoneinfo/${TZ} /usr/share/zoneinfo/${TZ}

# Set environment variable for the timezone

# Expose the port MinIO uses
EXPOSE 9000

# Start MinIO server
CMD ["minio", "server", "/data"]
```

For minio/mc

```Dockerfile
ARG TZ=Europe/Berlin

FROM debian:latest AS builder
ARG TZ
ENV TZ=${TZ}

RUN apt-get update && \
    apt-get install -y tzdata && \
    ln -sf /usr/share/zoneinfo/${TZ} /etc/localtime && \
    echo "${TZ}" > /etc/timezone

FROM minio/mc:latest
ARG TZ
ENV TZ=${TZ}

# Copy timezone files from the builder stage
COPY --from=builder /etc/localtime /etc/localtime
COPY --from=builder /etc/timezone /etc/timezone
COPY --from=builder /usr/share/zoneinfo/${TZ} /usr/share/zoneinfo/${TZ}
```

## Usage

In your docker-compose file. Simply reference the Dockerfile and give a build argument.

```yml
minio-service:
  build:
    context: .
    dockerfile: path/to/minio/Dockerfile
    args:
      TZ: {TZ}
```
