### ISSUE TITLE
Health-check and some log problems with custom port

### ISSUE THREAD

**Issue by senolatac** [minio/minio#19860]
## Expected Behavior
- healty containers
-  no error on console.

## Current Behavior
- unhealty containers
- And I got error like: 
```
cn-minio2: Error: Drive: http://minio4:9005/data2 returned drive not found (*fmt.wrapError)
cn-minio2:        endpoint="http://minio4:9005/data2"
cn-minio2:        4: internal/logger/logger.go:258:logger.LogAlwaysIf()
cn-minio2:        3: cmd/logging.go:57:cmd.peersLogAlwaysIf()
cn-minio2:        2: cmd/prepare-storage.go:51:cmd.init.func22.1()
cn-minio2:        1: cmd/erasure-sets.go:239:cmd.(*erasureSets).connectDisks.func2()
```
- Other error is: https://github.com/minio/minio/discussions/17875

## Possible Solution
checked this https://github.com/minio/minio/issues/18389 one but no solution yet.

## Steps to Reproduce (for bugs)

1. `docker compose up -d`
2.  wait and you will see containers as unhealty.
3. And I got error like: 
```
cn-minio2: Error: Drive: http://minio4:9005/data2 returned drive not found (*fmt.wrapError)
cn-minio2:        endpoint="http://minio4:9005/data2"
cn-minio2:        4: internal/logger/logger.go:258:logger.LogAlwaysIf()
cn-minio2:        3: cmd/logging.go:57:cmd.peersLogAlwaysIf()
cn-minio2:        2: cmd/prepare-storage.go:51:cmd.init.func22.1()
cn-minio2:        1: cmd/erasure-sets.go:239:cmd.(*erasureSets).connectDisks.func2()
```

## Regression
Provided via docker-compose.yaml

## Your Environment
My docker-compose looks like:

- MINIO_PORT=9005
- CONSOLE_PORT=9006

```
version: '3.8'

# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2024-05-28T17-19-04Z
  command: server --address ":${MINIO_PORT}" --console-address ":${CONSOLE_PORT}" http://minio{1...4}/data{1...2}
  expose:
    - '${MINIO_PORT}'
    - '${CONSOLE_PORT}'
  environment:
    MINIO_ROOT_USER: minioadmin
    MINIO_ROOT_PASSWORD: minioadmin
  healthcheck:
    test: ["CMD", "mc", "ready", "local"]
    interval: 5s
    timeout: 5s
    retries: 5

# starts 4 docker containers running minio server instances.
# using nginx reverse proxy, load balancing, you can access
services:
  svc-minio1:
    <<: *minio-common
    hostname: minio1
    container_name: cn-minio1
    volumes:
      - ./minio-volumes/data1-1:/data1
      - ./minio-volumes/data1-2:/data2

  svc-minio2:
    <<: *minio-common
    hostname: minio2
    container_name: cn-minio2
    volumes:
      - ./minio-volumes/data2-1:/data1
      - ./minio-volumes/data2-2:/data2

  svc-minio3:
    <<: *minio-common
    hostname: minio3
    container_name: cn-minio3
    volumes:
      - ./minio-volumes/data3-1:/data1
      - ./minio-volumes/data3-2:/data2

  svc-minio4:
    <<: *minio-common
    hostname: minio4
    container_name: cn-minio4
    volumes:
      - ./minio-volumes/data4-1:/data1
      - ./minio-volumes/data4-2:/data2

  svc-nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    container_name: cn-minio-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/templates/nginx.conf.template:ro
    environment:
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx
      MINIO_PORT: ${MINIO_PORT}
      CONSOLE_PORT: ${CONSOLE_PORT}
    ports:
      - "${MINIO_PORT}:${MINIO_PORT}"
      - "${CONSOLE_PORT}:${CONSOLE_PORT}"
    depends_on:
      - svc-minio1
      - svc-minio2
      - svc-minio3
      - svc-minio4
```

**Comment by senolatac** [comment]
Health-check solved like:

```
x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2024-05-28T17-19-04Z
  command: server --address ":${MINIO_PORT}" --console-address ":${CONSOLE_PORT}" http://minio{1...4}/data{1...2}
  expose:
    - '${MINIO_PORT}'
    - '${CONSOLE_PORT}'
  environment:
    MINIO_ROOT_USER: minioadmin
    MINIO_ROOT_PASSWORD: minioadmin
    MC_HOST_custom: http://localhost:${MINIO_PORT}
  healthcheck:
    test: ["CMD", "mc", "ready", "custom"]
    interval: 5s
    timeout: 5s
    retries: 5
```

but console logs still continue...
