### ISSUE TITLE
Why  cannot we access the published minio port from browser?

### ISSUE THREAD

**Issue by theaungmyatmoe** [minio/minio#19863]
# Why we cannot access the published minio port from browser?

I published the port 9000 to the host machine, however it seems not working at all.

## Expected Behavior
When I first try with the mini and past two months, the published port is fine. But now it cannot be accessible  via the browser even the console is fine.

## Current Behavior
<img width="1470" alt="Screenshot 2024-06-03 at 5 21 09 PM" src="https://github.com/minio/minio/assets/65492233/4e412736-f09d-4a41-8e3b-2d7e1b879191">

## Possible Solution
I tried to fix like below.
```yaml
  minio:
    image: minio/minio:latest
    ports:
      - 9000:9000
      - ${FORWARD_MINIO_CONSOLE_PORT:-8900}:8900
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
    volumes:
      - minio:/data/minio
    networks:
      - development
    command:
      - minio server /data/minio --console-address ":8900"
      - --address 0.0.0.0:9000
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:${FORWARD_MINIO_PORT}/minio/health/live
      retries: 3
      timeout: 5s


  

  create-bucket:
    image: minio/mc:latest
    entrypoint: [ "/bin/sh", "-c" ]
    command: |
      "
      # set host alias
      mc alias set minio http://minio:9000 root password

      # create IAM user
      # ref: https://min.io/docs/minio/linux/administration/identity-access-management/minio-user-management.html#id5
      mc admin user add minio access_key secret_key
      mc admin policy attach minio readwrite --user=access_key

      # create bucket
      mc mb minio/breeze
      mc anonymous set upload minio/breeze
      mc anonymous set download minio/breeze
      mc anonymous set public minio/breeze
      exit 0;
      "
    networks:
      - development

```

## Steps to Reproduce (for bugs)
- Run the docker compose up minio and create-bucket. Then try to open the image via browser. (not from console, please open from API)

## Context
I am using Laravel and Spatie Media Libary for that case.
Here is my possible fix. Read and write inside the container is fine. But outside of the docker look failing.

```env

# Minio
FILESYSTEM_DRIVER=s3
MEDIA_DISK=s3

AWS_ACCESS_KEY_ID=access_key
AWS_SECRET_ACCESS_KEY=secret_key
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=breeze
AWS_USE_PATH_STYLE_ENDPOINT=true
AWS_ENDPOINT=minio:9000
AWS_URL=http://localhost:9000

```

## Regression
I don't think so.

## Your Environment

- Version used (`minio --version`): 
```sh-5.1# minio --version
minio version RELEASE.2024-05-10T01-41-38Z (commit-id=b5984027386ec1e55c504d27f42ef40a189cdb55)
Runtime: go1.22.3 linux/arm64
License: GNU AGPLv3 - https://www.gnu.org/licenses/agpl-3.0.html
Copyright: 2015-2024 MinIO, Inc.
```
- Server setup and configuration: Above docker compose file.
- Operating System and version (`uname -a`): 
```➜  breeze git:(main) ✗ uname -a
Darwin aungmyatmoe.local 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:19:22 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T8112 arm64
➜  breeze git:(main) ✗ 

```
