### ISSUE TITLE
Cant login in my minio dashboard

### ISSUE THREAD

**Issue by stormyark** [minio/minio#19941]
This is my docker-compose.yml

```
services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    volumes:
      - ./minio-data:/data
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password
      MINIO_SERVER_URL: https://s3.stormyark.de
    command: server /data --console-address ":9090"
```
with some additional network configuration to make my nginx reverse proxy working.

When I try to login with those credentials It says Invalid login.

![image](https://github.com/minio/minio/assets/81960990/9bf443ca-a675-47a4-8cd3-448a10fae0f7)

No matter what I try I cant login

This is what I put in my Advanced in my nginx proxy manager

```# Allow special characters in headers
ignore_invalid_headers off;
# Allow any size file to be uploaded.
# Set to a value such as 1000m; to restrict file size to a specific value
client_max_body_size 0;
# Disable buffering
proxy_buffering off;
proxy_request_buffering off;```
