### ISSUE TITLE
WebSocket Connection Errors and Object Visibility Issues When Accessing MinIO via NGINX Ingress Domain

### ISSUE THREAD

**Issue by ovaliburak** [minio/minio#20016]
**Environment Details:**
- **MinIO Version:** RELEASE.2024-05-01T01-11-10Z
- **Kubernetes Version:** 1.29
- **Deployment Method:** Helm Chart
- **Infrastructure:** Vanilla K8S

**Problem Description:**
When accessing the MinIO Console through NGINX Ingress using a fully qualified domain name (`tmsconsole.xxx.com`), WebSocket connections repeatedly fail with errors such as "Error in WebSocket connection". This issue does not occur when accessing the MinIO Console directly using the LoadBalancer's IP address.

**Error Observed:**
WebSocket disconnections and failures as shown in the developer console:

![websocket](https://github.com/minio/minio/assets/66214278/6e51cf88-2460-460c-ab79-a25984acc6e8)

**Steps to Reproduce:**
1. Deploy MinIO using the provided Helm chart configuration with the specified values in `tenant.yaml`.
```
tenant:
  certificate:
    requestAutoCert: false     
  name: tms 
  configuration:
    name: tms-env-configuration
  pools: 
    - servers: 1
      name: pool
      size: 200Mi
      volumesPerServer: 1
ingress:
  api:
    enabled: true
    ingressClassName: "nginx"
    tls:
    - hosts:
      - tmsapi.xxx.com
      secretName: nginxsecret
    host: tmsapi.xxx.com
    path: /
    pathType: Prefix
  console:
    enabled: true
    ingressClassName: "nginx"
    tls:
    - hosts:
      - tmsconsole.xxx.com
      secretName: nginxsecret 
    host: tmsconsole.xxx.com
    path: /
    pathType: Prefix
```

2. Access the MinIO Console through the domain name configured in NGINX Ingress (`tmsconsole.xxx.com`).
ingress.yaml:
```
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-set-header: |
      Upgrade $http_upgrade;
      Connection $connection_upgrade;
    nginx.ingress.kubernetes.io/upgrade-insecure-requests: "1"
spec:
  ingressClassName: nginx
  rules:
  - host: tmsapi.xxx.com
    http:
      paths:
      - backend:
          service:
            name: minio
            port:
              name: http-minio
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - tmsapi.xxx.com
    secretName: nginxsecret
---
metadata:
  annotations:
    meta.helm.sh/release-name: tms2
    meta.helm.sh/release-namespace: tms2
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-set-header: |
      Upgrade $http_upgrade;
      Connection $connection_upgrade;
    nginx.ingress.kubernetes.io/upgrade-insecure-requests: "1"
spec:
  ingressClassName: nginx
  rules:
  - host: tmsconsole.xxx.com
    http:
      paths:
      - backend:
          service:
            name: tms-console
            port:
              name: http-console
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - tmsconsole.xxx.com
    secretName: nginxsecret
```

4. Observe the repeated WebSocket errors in the browser's developer console when trying to view or interact with bucket contents.
![image](https://github.com/minio/minio/assets/66214278/40b9e93b-8438-45ad-a566-4393f51d5ac8)

**Expected Behavior:**
WebSocket connections should remain stable, and the MinIO Console should function identically whether accessed via the domain name through NGINX Ingress.

**Additional Configuration Details:**
- NGINX Ingress is configured to handle SSL termination.
- HAProxy is used for TCP load balancing and SSL pass-through to NGINX Ingress.
- The relevant HAProxy configurations: 

```
frontend kubernetes-ingress-https
    bind *:443
    default_backend kubernetes-worker-nodes-https

backend kubernetes-worker-nodes-https
    balance leastconn
    option tcp-check
    server workernode-01 10.34.43.17:443 check fall 3 rise 2 #Ingress 443
```
