### ISSUE TITLE
access- and secret-key suddenly invalid

### ISSUE THREAD

**Issue by sebhoss** [minio/minio#20120]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior

We are using minio-operator and have deployed several tenants using the Tenant CRD. The access- and secret-key configured in that tenant should continue to work indefinitely.

## Current Behavior

In one of our tenants, the configured access- and secret-key no longer works. We can not use `mc` to connect to this instance anymore. The log output reads: `The Access Key Id you provided does not exist in our records.` We have not changed any keys ourselves and have verified that the keys in the Tenant custom resource are exactly the one we are using while trying to connect. The log output of the running minio pods show nothing besides the typical startup message.

## Possible Solution

Since that one tenant is used for testing only, we are going to throw that one away and re-create it. Before doing that, we can offer it as some kind of debugging instance in case there is an interest in figuring out why this happened?

## Steps to Reproduce (for bugs)

Well we do not know but could help in reproducing it

## Context

This tenant is used for testing only and it does not really affect us

## Regression

Maybe? We have updated minio to its latest release recently and only noticed failed logins after, but we have not checked whether logins worked before the update. The version we know worked in the past was `RELEASE.2024-06-22T05-26-45Z` and we are currently running `RELEASE.2024-07-16T23-46-41Z`. Downgrading to the older version however did not fix the login issue for us. 

## Your Environment

* Version used (`minio --version`):
```
minio version RELEASE.2024-07-16T23-46-41Z (commit-id=3535197f993dea840dcb96302ba4d883dc619097)
Runtime: go1.22.5 linux/amd64
License: GNU AGPLv3 - https://www.gnu.org/licenses/agpl-3.0.html
Copyright: 2015-2024 MinIO, Inc.
```
* Server setup and configuration: Kubernetes with minio-operator using the official minio images
* Operating System and version (`uname -a`): `Linux test-pool-0-0 5.15.0-116-generic #126~20.04.1-Ubuntu SMP Mon Jul 1 15:40:07 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by harshavardhana** [comment]
@sebhoss are you using LDAP?

**Comment by harshavardhana** [comment]
> In one of our tenants, the configured access- and secret-key no longer works. We can not use `mc` to connect to this instance anymore. The log output reads: `The Access Key Id you provided does not exist in our records.` We have not changed any keys ourselves and have verified that the keys in the Tenant custom resource are exactly the one we are using while trying to connect. The log output of the running minio pods show nothing besides the typical startup message.

Can you check on your drives and PVs the credentials exist on `/backend_mount/.minio.sys/config/iam/`  ?

**Comment by sebhoss** [comment]
We are not using LDAP but use static credentials. Our Tenant resource looks like this (simplified):

```yaml
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: test
  namespace: minio-tenant-test
spec:
  configuration:
    name: storage-configuration
  users:
    - name: storage-user
  mountPath: /export
  subPath: /data
```

and the `storage-user` secret like this:

```yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  creationTimestamp: "2024-02-16T09:35:01Z"
  name: storage-user
  namespace: minio-tenant-test
stringData:
  CONSOLE_ACCESS_KEY: some-access-key
  CONSOLE_SECRET_KEY: some-secret-key
```

The credentials do NOT exist in `.minio.sys/config/iam`:

```console
$ ls -la /export/data/.minio.sys/config/iam/
total 12
drwxr-sr-x 3 1000 1000 4096 Jun 26 07:10 .
drwxr-sr-x 4 1000 1000 4096 Jun 26 07:10 ..
drwxr-sr-x 2 1000 1000 4096 Jun 26 07:10 format.json
```

Is there a way to re-create the missing users folder? Can I just copy that from a working instance and it should work?
