### ISSUE TITLE
Self-signed certificate CA not trusted: minio and kes

### ISSUE THREAD

**Issue by ladderschool** [minio/minio#20159]
# Problem
Hello, I'll try to be as verbose as possible show you a weird bug I've encountered. I have a nodejs application that uses the AWS SDK to connect to my minio S3 storage and facilitates the upload process. I have no issues saving to buckets or encrypting them. Either from my nodejs app or the console web ui, both allow me to use or configure the minio API. The problem is on the minio system itself. I appreciate any help and thank you for taking the time to read this.

## Environment
- Main host system runs Docker
- My web app runs in a container and accesses the minio API by hostname
- minio runs in a container (only :9001 exposed to internet)
- kes runs in a container (not exposed to internet at all)
- hashicorp vault runs in a container (not exposed to internet at all)

## Setup
First, I created a self-signed certificate for my minio and kes servers.
```
openssl genrsa -out minio_ca.key 4096
openssl req -x509 -new -nodes -key minio_ca.key -sha256 -days 3650 -out minio_ca.crt
openssl genrsa -out minio.key 2048
openssl req -new -key minio.key -out minio.csr

cat > minio.cnf <<EOF
[req]
req_extensions = v3_req
distinguished_name = req_distinguished_name
[req_distinguished_name]
[ v3_req ]
basicConstraints = CA:FALSE
keyUsage = nonRepudiation, digitalSignature, keyEncipherment
subjectAltName = @alt_names
[alt_names]
DNS.1 = minio-dw-woossgo
DNS.2 = localhost
IP.1 = 127.0.0.1
IP.2 = 0.0.0.0
EOF

openssl x509 -req -in minio.csr -CA minio_ca.crt -CAkey minio_ca.key -CAcreateserial -out minio.crt -days 3650 -sha256 -extfile minio.cnf -extensions v3_req
```
* I did the same on the KES server for the self-signed certificates there

I have exported the minio_ca.crt file to my web app's ca-certificates folder and ran update-ca-certificates. I tested with curl -v https://minio-dw-woossgo:9000 and have indeed a trusted TLS handshake. I also generated self-signed certificates for KES and followed the same steps of trusting the KES CA certificate on my hashicorp vault server. Again from vault, I can curl -v https://kes-dw-woossgo:7373 and see a successful TLS handshake. As I mentioned in my intro, the encryption key for buckets works. I can log into the minio web ui and use the KMS server through KES. Again, my web app can upload to minio's encrypted buckets I have set up. 

Then I deployed minio using the docker compose (see below). When I check my containers I see the following output:
```
MinIO Object Storage Server
Copyright: 2015-2024 MinIO, Inc.
License: GNU AGPLv3 - https://www.gnu.org/licenses/agpl-3.0.html
Version: RELEASE.2024-07-16T23-46-41Z (go1.22.5 linux/amd64)

API: https://0.0.0.0:9000 
WebUI: <internal ip:9001>
Docs: https://min.io/docs/minio/linux/index.html
```
And for the KES server:
```
Version                           2024-06-17T15-47-05Z    commit=12195cc387d860517221548b6297471c92978f68
Runtime                           go1.22.4 linux/amd64    compiler=gc
License                           AGPLv3                  https://www.gnu.org/licenses/agpl-3.0.html
Copyright                         MinIO, Inc.  2015-2024  https://min.io

KMS       Hashicorp Vault: https://vault-dw-w48swo0:8200
API       · https://127.0.0.1:7373
          · https://<internal ip:7373>
Admin     xyz
Logs
error=stderr level=INFO
audit=stdout level=INFO
=> Server is up and running...
```

Looks good, right? It works too as I mentioned. However here is where the problems begin.

## Expected Behavior
When I run
```
mc alias set local https://localhost:9000 user password
mc ready local
curl -v https://localhost:9000
```
I shouldn't get any certificate errors.

## Current Behavior
1. I have to run
```
mc alias set local https://localhost:9000 user password --insecure
```
Otherwise I get error
```
mc: <ERROR> Unable to initialize new alias from the provided credentials. Get "https://localhost:9000": tls: failed to verify certificate: x509: certificate signed by unknown authority.
```

2. I have to run
```
mc ready local --insecure
```
Otherwise I get error
```
The cluster is unreachable: Get "https://localhost:9000/minio/health/cluster": tls: failed to verify certificate: x509: certificate signed by unknown authority
```

3. When I run
```
curl -v https://localhost:9000 # Same for :9001 console web ui because it also uses the minio_ca.crt
```
I get a TLS handshake error
```
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection
curl: (60) SSL certificate problem: unable to get local issuer certificate
```

4. I can't test curl from my KES server, since the command is not found. I suspect similar issues though, because when I try to run "kes status" in an interactive shell in my KES container I get:
```
Error: not authorized: insufficient permissions
```
This shouldn't happen because I have set the SSL_CERT_FILE and other environment variables on this local machine. I attached my config.yml so you can see where I set up TLS on KES.

~BONUS 1~
I've mentioned that I can access the web ui over the internet, right? Well, it uses the self-signed certificate to create the https connection. I have to trust it and "accept the risk". Is there any way to prevent it from using that certificate? For internet access I run my docker host with traefik, when creating the container I'd like to let traefik handle the https connection with letsencrypt. This works for all my other apps, but the web ui prefers the certificate in /root/.minio/certs/CAs What would preferable is to attach that self-signed certificate to the API only and leave the web ui alone.

~BONUS 2~
I am confused about something. When I deploy my minio container without MINIO_ROOT_USER and MINIO_ROOT_PASSWORD, I can see several errors in the log output for minio:
```
FATAL Unable to generate root access key using KMS: insufficient permissions to perform KMS operation
```
Why is the root user necessary for me to even establish a connection to the KES server? I didn't see this documented anywhere.

## Conclusion
In fact, when I try to curl -v https://kes-dw-woossgo:7373 I also get the same TLS handshake issue. This leads me to believe that the root CA certificates I have added to /root/.minio/certs* are not recognized, neither the minio_ca.crt or the kes_ca.crt. Interestingly enough, since my minio API uses an API key to communicate the KES it all works out in the end. This issue from what I could gather (and I read every single previous issue on this github) are system wide issues. I do not see this problem on my hashcorp vault or web app container because ...

## Possible Solution
I properly updated their certificate stores. Instead of using UBI micro, I believe I need to use UBI minimal which has a package manager to install ca-certificates and update the local system store correctly. Sadly, the official minio/minio docker image is built on UBI micro. How do I solve this problem?

## Steps to Reproduce (for bugs)
1. Generate keys and certificates as above
2. Use my docker compose file as above
3. Docker exec -it <container running minio> sh
4. Try 'mc ready local' or use curl to check the TLS handshake

## Context
I am trying to get healtchecks to pass and overall establish correct trust between my services with the self-signed minio CA certificate.

## Your Environment
minio version RELEASE.2024-07-16T23-46-41Z (commit-id=3535197f993dea840dcb96302ba4d883dc619097)
Runtime: go1.22.5 linux/amd64
License: GNU AGPLv3 - https://www.gnu.org/licenses/agpl-3.0.html
Copyright: 2015-2024 MinIO, Inc.

## Docker compose
```
version: "3.8"

volumes:
  minio-dw:
    name: minio-dw
    external: false

services:
  kes:
    image: 'minio/kes:latest'
    command: 'server --config /data/config/config.yml'
    restart: unless-stopped
    environment:
      - KES_SERVER=https://0.0.0.0:7373
      - KES_CLIENT_KEY=/ssl/kes.key
      - KES_CLIENT_CERT=/ssl/kes.crt
      - KES_SERVER_KEY=/ssl/kes.key
      - KES_SERVER_CERT=/ssl/kes.crt
      - SSL_CERT_FILE=/ssl/kes_ca.crt
      - MINIO_IDENTITY=XYZ
      - ROOT_IDENTITY=XYZ
    volumes:
      - /data/kes/config/:/data/config/
      - /data/kes/ssl/:/ssl/
      - /data/vault/ssl/tls_local_key.pem:/vault/ssl/vault_key.pem
      - /data/vault/ssl/tls_local_cert.pem:/vault/ssl/vault_cert.pem
      - /data/vault/ssl/rootCA.crt:/usr/local/share/ca-certificates/vault_ca.crt

  minio:
    image: 'minio/minio:latest'
    command: 'server /storage --address "0.0.0.0:9000" --console-address ":9001" --anonymous'
    ports:
      - '9001:9001' # Not mapping API port intentionally to keep it only accessible on intranet
    environment:
      - MINIO_BROWSER=on
      - MINIO_DOMAIN=minio-dw-woossgo
      - MINIO_API_ROOT_ACCESS=on
      - MINIO_ROOT_USER=XYZ
      - MINIO_ROOT_PASSWORD=XYZ
      - MINIO_KMS_KES_ENDPOINT=https://kes-dw-woossgo:7373
      - MINIO_KMS_KES_KEY_NAME=KEY_XYZ
      - MINIO_KMS_KES_API_KEY=XYZ
      - MINIO_KMS_KES_CAPATH=/root/.minio/certs/CAs/kes_ca.crt
    volumes:
      - minio-dw:/storage
      - /data/minio/ssl/minio.key:/root/.minio/certs/private.key
      - /data/inio/ssl/minio.crt:/root/.minio/certs/public.crt
      - /data/minio/ssl/minio_ca.crt:/root/.minio/certs/CAs/minio_ca.crt
      - /data/kes/ssl/kes_ca.crt:/root/.minio/certs/CAs/kes_ca.crt
    healthcheck: # Won't work because we need to login with --insecure and set the alias correctly
      test: ["CMD", "mc", "ready", "local", "--insecure"]
      interval: 10s
      timeout: 5s
    restart: unless-stopped
    depends_on:
      - kes
```
## KES config.yml
```
address: 0.0.0.0:7373
root: ${ROOT_IDENTITY}

admin:
  identity: xyz

tls:
  key: /ssl/kes.key
  cert: /ssl/kes.crt
  ca: /ssl/kes_ca.crt

api:
  /v1/ready:
    skip_auth: true
    timeout:   10s

policy:
  minio-server:
    allow:
    - /v1/key/create/*
    - /v1/key/generate/*
    - /v1/key/decrypt/*
    - /v1/key/bulk/decrypt
    - /v1/key/list/*
    - /v1/status
    - /v1/metrics
    - /v1/log/audit
    - /v1/log/error
    identities:
    - ${MINIO_IDENTITY}

cache:
  expiry:
    any: 5m0s
    unused: 20s
    offline: 0s

log:
  error: on

keystore:
   vault:
     endpoint: https://vault-dw-w48swo0:8200
     version:  v1
     engine:   kv
     approle:
       id:     "xyz"
       secret: "xyz"
     tls:
       key: "/vault/ssl/vault_key.pem"
       cert: "/vault/ssl/vault_cert.pem"
       ca: "/usr/local/share/ca-certificates/vault_ca.crt"
     status:
       ping: 90s
```
