### ISSUE TITLE
update to RELEASE.2024-07-26T20-48-21Z  /data: drive not found: Invalid arguments specified.

### ISSUE THREAD

**Issue by uranus829** [minio/minio#20174]
Hello,I am update to  RELEASE.2024-07-26T20-48-21Z from Version 2022-01-04T07:41:07Z ,Please help, thank you. After I downgraded to the original version, docker started normally.

docker run --name jms_minio -d -p 9000:9000 -p 9001:9001 -e MINIO_ROOT_USER=minio -e MINIO_ROOT_PASSWORD=sDQ5Lr6kxhNVun8h -e "TZ=Asia/Shanghai" -e "MINIO_REGION=cn-north-1" -v /data/jumpserver/minio/data:/data -v /data/jumpserver/minio/config:/root/.minio --restart=always minio/minio:RELEASE.2024-07-26T20-48-21Z server /data --console-address ":9001"

[root@node1 docker.service.d]# docker ps
CONTAINER ID   IMAGE                                      COMMAND                  CREATED         STATUS                          PORTS     NAMES
d0d9a49e340a   minio/minio:RELEASE.2024-07-26T20-48-21Z   "/usr/bin/docker-ent…"   2 minutes ago   Restarting (1) 50 seconds ago             jms_minio

[root@node1 docker.service.d]# docker logs jms_minio
FATAL Unable to use the drive /data: drive not found: Invalid arguments specified
FATAL Unable to use the drive /data: drive not found: Invalid arguments specified
FATAL Unable to use the drive /data: drive not found: Invalid arguments specified
FATAL Unable to use the drive /data: drive not found: Invalid arguments specified
FATAL Unable to use the drive /data: drive not found: Invalid arguments specified
FATAL Unable to use the drive /data: drive not found: Invalid arguments specified
FATAL Unable to use the drive /data: drive not found: Invalid arguments specified
FATAL Unable to use the drive /data: drive not found: Invalid arguments specified

**Comment by harshavardhana** [comment]
> Invalid arguments specified

runs perfectly fine for me

```
docker run --name jms_minio -d -p 9000:9000 -p 9001:9001 -e MINIO_ROOT_USER=minio -e MINIO_ROOT_PASSWORD=sDQ5Lr6kxhNVun8h -e "TZ=Asia/Shanghai" -e "MINIO_REGION=cn-north-1" -v /data/jumpserver/minio/data:/data -v /data/jumpserver/minio/config:/root/.minio --restart=always minio/minio:latest server /data --console-address ":9001"
Unable to find image 'minio/minio:latest' locally
latest: Pulling from minio/minio
5f328c14e09d: Pull complete 
239eda461bd8: Pull complete 
64330a1bebde: Pull complete 
f5cfb10a9d41: Pull complete 
63815c4b9450: Pull complete 
8f5875e37113: Pull complete 
f48762d96a86: Pull complete 
a2d8d64aa607: Pull complete 
Digest: sha256:9ef3d0514c0636e86e3db6b2a21c21d4035c17a47ea5464658f2f5d24afd15c6
Status: Downloaded newer image for minio/minio:latest
ca28b7babc6d6715549537918af9f1705449726dfec0fcf13b1c5db8cee5b258

```

```
docker logs ca28b7babc6d
INFO: Formatting 1st pool, 1 set(s), 1 drives per set.
INFO: WARNING: Host local has more than 0 drives of set. A host failure will result in data becoming unavailable.
MinIO Object Storage Server
Copyright: 2015-2024 MinIO, Inc.
License: GNU AGPLv3 - https://www.gnu.org/licenses/agpl-3.0.html
Version: RELEASE.2024-07-26T20-48-21Z (go1.22.5 linux/amd64)

API: http://172.17.0.2:9000  http://127.0.0.1:9000 
WebUI: http://172.17.0.2:9001 http://127.0.0.1:9001 

Docs: https://min.io/docs/minio/linux/index.html
```

**Comment by harshavardhana** [comment]
> Hello,I am update to RELEASE.2024-07-26T20-48-21Z from Version 2022-01-04T07:41:07Z ,

this is too old of a release jump, are you using FS mode? https://min.io/docs/minio/linux/operations/install-deploy-manage/migrate-fs-gateway.html - read this first.

**Comment by sober-wang** [comment]
on k8s 
FATAL Unable to use the drive /home: drive not found: Invalid arguments specified
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-bandwidth
  labels:
      app: test-bandwidth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      annotations:
        kubernetes.io/ingress-bandwidth: 1M
        kubernetes.io/egress-bandwidth: 1M
      labels:
        app: minio
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        args:
        - minio server /home --console-address :9090
        env:
        - name: MINIO_ROOT_PASSWORD
          value: minioadmin
        - name: MINIO_ROOT_USER
          value: minioadmin
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: quay.io/minio/minio:latest
        name: minio-server
        ports:
        - containerPort: 9000
          name: endpoint
          protocol: TCP
        - containerPort: 9090
          name: console
          protocol: TCP
        volumeMounts:
        - mountPath: /home
          name: nfs-data
      volumes:
      - name: nfs-data
        nfs:
          path: /
          server:  10.10.10.10
```
the same problem arises!
