### ISSUE TITLE
x509: certificate signed by unknown authority using mkcert and docker

### ISSUE THREAD

**Issue by jcwirko** [minio/minio#20205]
## Subject of the issue

mc: Unable to initialize new alias from the provided credentials. Get "https://localhost:9001/": tls: failed to verify certificate: x509: certificate signed by unknown authority.

## Your environment
* docker
* mkcert
* 
## Steps to reproduce
I have created a docker compose with a minio service, the application web is working, the issue is when I try to use the API with port 9001. I got an error related to x509: certificate signed by unknown authority.

I have generated certs with mkcert, then I have in my host machine the public.crt, private.key and then inside CAs the rootCA-key and rootCA.

<img width="201" alt="image" src="https://github.com/user-attachments/assets/c854e573-fac8-41ba-848a-bf9da282b429">

All of this I copy into the docker container:

 ```
 findra-minio:
    container_name: findra-minio
    image: minio/minio
    command: server --certs-dir /root/.minio/certs --console-address ":${FORWARD_MINIO_CONSOLE_PORT:-9002}" --address ":${FORWARD_MINIO_PORT:-9001}" /data 
    ports:
      - '${FORWARD_MINIO_PORT:-9001}:9001'
      - '${FORWARD_MINIO_API_PORT:-9002}:9002'
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_SERVER_URL: "https://localhost:9001"
    healthcheck:
      test: timeout 5s bash -c ':> /dev/tcp/localhost/9001' || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - type: volume
        source: findra_minio
        target: /data
      - type: bind
        source: ./config/certs
        target: /root/.minio/certs
    networks:
      - backend
```

and the issue is when I want to use the mc command line. What am I doing wrong? I followed the documentations and I copy all the certs that mkcert generated.

## Expected behaviour
I should use the command line without get an error. x509: certificate signed by unknown authority.

## Actual behaviour
I get x509: certificate signed by unknown authority error message

Log
```

[+] Running 2/2
 ✔ Volume "finaldraw_findra_minio"  Created                                                                                                                          0.0s 
 ✔ Container findra-minio           Started                                                                                                                          0.5s 
docker exec -it findra-minio mc alias set finaldraw https://localhost:9001 minio 12345678
mc: Configuration written to `/tmp/.mc/config.json`. Please update your access credentials.
mc: Successfully created `/tmp/.mc/share`.
mc: Initialized share uploads `/tmp/.mc/share/uploads.json` file.
mc: Initialized share downloads `/tmp/.mc/share/downloads.json` file.
mc: <ERROR> Unable to initialize new alias from the provided credentials. Get "https://localhost:9001": dial tcp [::1]:9001: connect: connection refused.
```

```
user@juan finaldraw % docker compose logs findra-minio
findra-minio  | INFO: Formatting 1st pool, 1 set(s), 1 drives per set.
findra-minio  | INFO: WARNING: Host local has more than 0 drives of set. A host failure will result in data becoming unavailable.
findra-minio  | MinIO Object Storage Server
findra-minio  | Copyright: 2015-2024 MinIO, Inc.
findra-minio  | License: GNU AGPLv3 - https://www.gnu.org/licenses/agpl-3.0.html
findra-minio  | Version: RELEASE.2024-07-31T05-46-26Z (go1.22.5 linux/arm64)
findra-minio  | 
findra-minio  | API: https://localhost:9001 
findra-minio  | WebUI: https://172.18.0.7:9002 https://127.0.0.1:9002  
findra-minio  | 
findra-minio  | Docs: https://min.io/docs/minio/linux/index.html
juanblariza@JuanB finaldraw %
```

My OS is iOS.
