### ISSUE TITLE
HostPath Persistent Volume doesn't work on Windows + Docker Desktop + HyperV backend

### ISSUE THREAD

**Issue by SledgeHammer01** [minio/minio#20237]
* Windows 11 Pro x64
* Docker Desktop 4.25.1 w/ Kubernetes enabled and **HyperV backend** (NOT WSL since its very flakey)
* Deployed via Bitnami Helm (I understand you don't support that chart, but its a Minio issue, it seems)

When I use an existing hostPath PersistentVolume / PersistentVolumeClaim, Minio fails to start up with "Operation not permitted" error. This seems to be because the container is run as non-root.

So, I modified the Values to **run as root** and Minio still gets a CrashLoopBackoff with no error message. This is the last log message. It seems like there is some failure on writing to the hostPath with HyperV. I initially opened a bug with Bitnami, but they said it is a Minio issue.

```
 18:36:29.01 INFO  ==>
 18:36:29.01 INFO  ==> ** Starting MinIO setup **
```

I have the same exact set up with another application (localstack) and it is able to write to the mount under HyperV.

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /host_mnt/c/users/xxx/.minio
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio
  namespace: minio
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
```
