### ISSUE TITLE
Prometheus scrape error: expected a valid start token, got "<" ("INVALID") while parsing: "<"

### ISSUE THREAD

**Issue by urbaman** [minio/minio#20240]
All of a sudden, prometheus has a scrape error to all of the endopoints: `expected a valid start token, got "<" ("INVALID") while parsing: "<"`

Deployed with helm, created a job with multiple endpoints (cluster, node, bucket...)

Already tryed to set MINIO_PROMETHEUS_AUTH_TYPE=publi c to no avail

## Expected Behavior

The prometheus scapes work

## Current Behavior

The scrapes fail with `expected a valid start token, got "<" ("INVALID") while parsing: "<"`

## Steps to Reproduce (for bugs)

1. Installed operator and tenent via helm chart
2. Configured prometheus, verified that tne tenant console also connected to prometheus
3. All of a sudden the problem triggered, tryed changing the configuration, restaring the pool pods, ...
 you have these details. -->

## Your Environment
* Version used (`minio --version`): minio version RELEASE.2024-07-16T23-46-41Z (commit-id=3535197f993dea840dcb96302ba4d883dc619097)
* Server setup and configuration: Ubuntu 22.04.4, Kubeadm 1.30.3, Helm
* Operating System and version (`uname -a`): Linux k8cp1 5.15.0-117-generic #127-Ubuntu SMP Fri Jul 5 20:13:28 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
> All of a sudden, prometheus has a scrape error to all of the endopoints: `expected a valid start token, got "<" ("INVALID") while parsing: "<"`
> 
> Deployed with helm, created a job with multiple endpoints (cluster, node, bucket...)
> 
> Already tryed to set MINIO_PROMETHEUS_AUTH_TYPE=publi c to no avail
> 
> ## Expected Behavior
> The prometheus scapes work
> 
> ## Current Behavior
> The scrapes fail with `expected a valid start token, got "<" ("INVALID") while parsing: "<"`
> 
> ## Steps to Reproduce (for bugs)
> 1. Installed operator and tenent via helm chart
> 2. Configured prometheus, verified that tne tenant console also connected to prometheus
> 3. All of a sudden the problem triggered, tryed changing the configuration, restaring the pool pods, ...
>    you have these details. -->
> 
> ## Your Environment
> * Version used (`minio --version`): minio version RELEASE.2024-07-16T23-46-41Z (commit-id=3535197f993dea840dcb96302ba4d883dc619097)
> * Server setup and configuration: Ubuntu 22.04.4, Kubeadm 1.30.3, Helm
> * Operating System and version (`uname -a`): Linux k8cp1 5.15.0-117-generic [Accessing dir as object should return ObjectNotFound #127](https://github.com/minio/minio/pull/127)-Ubuntu SMP Fri Jul 5 20:13:28 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

It looks like you are getting an authentication error,

Can you do curl on the same endpoint?

**Comment by urbaman** [comment]
I'm probably messing around with the minio and minio-hl services.
They seemd to both respond (I saw two different scrape jobs created by my serviceMonitors), then only minio-hl responds now.

The problem is that the serviceMonitor.selector.matchLabels is of no help to discard the minio service that is not responding to the scrapes.

Is ther a way to properly set a serviceMonitor to injest the scrape settings to prometheus through the operator?

Thank you.

**Comment by urbaman** [comment]
So the following serviceMonitor matchLabel selects both of the services, but only minio-hl works, while minio fires the error:

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: minio-sm-cluster
  namespace: minio
  labels:
    v1.min.io/tenant: minio
    release: kube-prometheus-stack
spec:
  jobLabel: cluster-job
  endpoints:
  - bearerTokenSecret:
      key: cluster-token
      name: minio-metrics-bearer-tokens
    path: /minio/v2/metrics/cluster
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
  selector:
    matchLabels:
      v1.min.io/tenant: minio
```

![image](https://github.com/user-attachments/assets/1b67ab0f-e08c-43b5-8f81-12c91078fb92)


If I could understand why minio does not want to accept the connection (while minio-hl does), I could add a label to the minio service and just select it for scraping:

```
serviceMetadata:
    minioServiceLabels:
      label: minio-svc
```

**Comment by harshavardhana** [comment]
Well port 9443 is Console UI - that has no Prometheus metrics. 

You need to enable only for port 9000 which seems to be working fine.

**Comment by urbaman** [comment]
And that's strange, in the deployed tenant I see the following services:

```
kubectl get svc -n minio
NAME            TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
minio           ClusterIP   10.1.180.244   <none>        443/TCP    19h
minio-console   ClusterIP   10.1.89.8      <none>        9443/TCP   19h
minio-hl        ClusterIP   None           <none>        9000/TCP   19h
operator        ClusterIP   10.1.53.93     <none>        4221/TCP   24h
sts             ClusterIP   10.1.27.177    <none>        4223/TCP   24h
```

minio has port 443, minio-console port 9443, minio-hl port 9000

minio and minio-hl (ports 443 and 9000) have

```
metadata:
  labels:
    v1.min.io/tenant: minio
```

and should be addressed by the selector of my serviceMonitor

```
  selector:
    matchLabels:
      v1.min.io/tenant: minio
```

while minio-console has

```
metadata:
  labels:
    v1.min.io/tenant: minio-console
```

and should not be addressed.

There's something strange happening...

**Comment by urbaman** [comment]
So finally found a working servicemonitor, adding the "port" spec:

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: minio-sm-cluster
  namespace: minio
  labels:
    v1.min.io/tenant: minio
    release: kube-prometheus-stack
spec:
  jobLabel: cluster-job
  endpoints:
  - bearerTokenSecret:
      key: cluster-token
      name: minio-metrics-bearer-tokens
    path: /minio/v2/metrics/cluster
    scheme: https
    port: https-minio
    tlsConfig:
      insecureSkipVerify: true
  selector:
    matchLabels:
      v1.min.io/tenant: minio
```

Also deleted all of the old servicemonitors before recreating them with the new specs, to be sure there was no cache in k8s/prometheus-operator or else.

Now only 12 targets per metrics endpoint (cluster, bucket, node, resource) get scraped, with two jobs (minio, minio-hl) for each of the six nodes, all pointing to port 9000 (both minio and minio-hl jobs as both minio and minio-hl services talk to the pod port 9000).

Will probably try with podmonitors instead of servicemonitors to avoid job duplication, or adding a label to the minio service and targeting that label in the servicemonitor.

Thank you very much.

**Comment by AndreaValerio17** [comment]
As of Prometheus Operator v0.65.1, the `scrapeConfig` Custom Resource Definition (CRD) is included, which I used to apply the Prometheus configuration generated by the command `mc prometheus generate` to my cluster.

Here’s a step-by-step guide on how I did it:

0. First, verify that your Prometheus instance has a `scrapeConfigSelector` field and note the label associated with it:

   ```bash
   kubectl get prom -n cattle-monitoring-system rancher-monitoring-prometheus -o yaml | grep scrapeConfigSelector -A 2 ```

1. Generate the Prometheus job configuration using the following MinIO command:

  ```bash
  mc admin prometheus generate ALIAS
  ```
2. Insert the bearer token into a Kubernetes Secret. Replace YOUR-TOKEN-HERE with your actual token:

```yaml

apiVersion: v1
kind: Secret
metadata:
  name: minio-token
  namespace: myminio
type: Opaque
data:
  cluster-token: YOUR-TOKEN-HERE
  ```
3. Write a scrapeConfig manifest and apply it to your cluster, ensuring that the labels match your Prometheus scrapeConfigSelector and any other relevant configurations:

``` yaml

apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  labels:
    release: rancher-monitoring # Ensure this matches your Prometheus scrapeConfigSelector
  name: tenant-monitoring
  namespace: myminio
spec:
  authorization:
    credentials:
      key: cluster-token
      name: minio-token
    type: Bearer
  metricsPath: /minio/v2/metrics/cluster
  scheme: HTTPS
  staticConfigs:
    - labels:
        cluster: myminio
      targets:
        - yourminio.minio.example.org
  tlsConfig:
    insecureSkipVerify: true
  ```
With this, I was able to scrape metrics from MinIO using Prometheus.
