### ISSUE TITLE
Batch Replication stopped working, docs don't help

### ISSUE THREAD

**Issue by fibbs** [minio/minio#20348]
I was successfully running Batch Replication to "pull" Prometheus metrics written by Thanos Sidecars from another MinIO installation with version RELEASE.2024-03-15T01-07-19Z on both sides, in order to make metrics available to one big datastore being consumed by Thanos compactor, Thanos store etc in an environment where push-communication from one to the other cluster is not allowed due to network zone concept.

my `replication.yaml` that I was successfully using looked like this:

```yaml
replicate:
  apiVersion: v1
  source:
    type: minio
    bucket: thanos-metrics
    endpoint: "https://my-remote-minio-api"
    path: "on"
    credentials:
      accessKey: "remote"
      secretKey: "supersecure"

  target:
    type: minio
    bucket: thanos-metrics
    endpoint: "local"

  flags:
    filter:
      newerThan: "12h" # match objects newer than this value (e.g. 7d10h31s)
      #olderThan: "2h" # match objects older than this value (e.g. 7d10h31s)
      #createdAfter: "date" # match objects created after "date"
      #createdBefore: "date" # match objects created before "date"

    notify:
      endpoint: "http://echo-server" # notification endpoint to receive job status events
    #  token: "Bearer xxxxx" # optional authentication token for the notification endpoint

    retry:
      attempts: 3 # number of retries for the job before giving up
      delay: "500ms" # least amount of delay between each retry
```

I had an echo server configured to see "some" kind of response from these jobs and had/have the plan to implement a little webservice converting MinIOs batch job notification message into Prometheus Pushgateway format later on.

In my echoserver I saw messages that the jobs were actually successfully executed and bytes were transferred. I want basically to transfer every block of prometheus metrics that is on the remote side to the local bucket, every few hours.

Now that I have upgraded to helm Chart 6.0.3 and therefore my MinIO Tenant is on version RELEASE.2024-08-03T04-33-23Z, the jobs could not be started anymore:

```
mc batch start minio-1-int  replicate.yaml
mc: <ERROR> Unable to start job. Invalid arguments specified.
```

I tried to dig into the documentation again and found that apparently the `endpoint: "local"` was either a misunderstanding by me (but working perfectly find) or the behavior has been changed. The documentation is quite unclear and misleading here, but as far as I understood I can just "leave both `credentials` and `endpoint` out for either the source or the target, depending on which of them is meant to be the **local** side". So I just removed the `endpoint: "local"` line of my replicate.yaml which made the job been accepted again:

```
mc batch start minio-1-int  replicate.yaml
Successfully started 'replicate' job `replicate-MTnMwRQRU3LQZH6pTXJzZC:1` on '2024-08-29 09:50:10.726328421 +0000 UTC'
```

Unfortunately, no data are being transferred at all:

```
mc batch status minio-1-int replicate-MTnMwRQRU3LQZH6pTXJzZC:1
mc: Unable to find an active job, attempting to list from previously run jobs
✔ ✔ ✔
JobType:       	replicate
Objects:       	0
Versions:      	0
FailedObjects: 	0
Throughput:    	0 B/s
IOPs:          	0.00 objs/s
Transferred:   	0 B
Elapsed:       	31.307067ms
CurrObjName:
```

I also tried playing with the filters, like taking them away entirely which *should* cause Batch Replication to act just like rsync (if I understand documentation correctly), but it doesn't work at all. Also, I am very sure there actually IS data to synchronize on the source MinIO bucket, which is not yet on the target one.

I also tried to switch from `apiVersion: v1` to `apiVersion: v2` but that lead to the error message `Invalid arguments specified` again.

## Expected Behavior
Batch Replication should work the same way as in RELEASE.2024-03-15T01-07-19Z without necessary changes, and if those were needed, documentation should state that clearly.

## Current Behavior
See above, replication just doesn't work

## Possible Solution
I am out of ideas....

## Steps to Reproduce (for bugs)
See above

## Context
I try to synchronize to minIO buckets on two minIO instances by "pull" mechanism, meaning that the target system must connect to the source system to fetch the data. Push mechanism as being used for MinIO replication is not an option here due to network zone separation.

## Regression
Is this issue a regression? Yes
If Yes, optionally please include minio version or commit id or PR#: see above

## Your Environment
* Kubernetes 1.28
* Helm install with Operator, Helm chart version 6.0.3 for operator, 6.0.2 for Tenant (due to issue https://github.com/minio/operator/issues/2298

**Comment by fibbs** [comment]
Upgraded my tenants to RELEASE.2024-08-17T01-24-54Z. Same behavior, no changes.

**Comment by vadmeste** [comment]
>     endpoint: "local"

Yes, this needs to be removed after the upgrade. 

Otherwise, can you run this `mc admin trace --call=batch-replication <ALIAS>`, keep it running and then run your batch yaml file in another terminal ?

Do you see any error pasted by the trace ?

**Comment by fibbs** [comment]
Thanks @vadmeste, the trace approach sounds very promising. Unfortunately, in my case it outputs exactly nothing at all when having the command running it and then starting the batch job from another terminal. It behaves just like the batch job would never be doing anything.

**Comment by vadmeste** [comment]
@fibbs do you see any logs in MinIO server ? also do not forget that the batch yaml only replicates new objects (objects older than 7 hours are excluded), are you sure you have objects that match your criteria

**Comment by fibbs** [comment]
absolutely nothing.

I also played around with the tracing. I can trace S3 accesses though, and I see a lot of things as expected, but my job just get "ignored". I am really out of ideas.

**Comment by vadmeste** [comment]
@fibbs are you sure that you have objects eligible to be replicated ? because you have this:

```
  flags:
    filter:
      newerThan: "12h" 
```

**Comment by fibbs** [comment]
Yes, I am very sure. BUT I of course don't trust myself, so I have done the following, unfortunately without success (yet).

I have switched to another MinIO tenant running in a test K8S cluster of mine, version RELEASE.2024-08-03T04-33-23Z.

I have upgraded `mc` command to latest version, created a new file with the `mc batch generate` command and have made the very basic settings there: no filters, no snowball, no prefixes, no notify, just fetching stuff from bucket `fibbs` on the "play.min.io" to the `test` bucket in my own tenant.

The file is the following and should be testable for anyone with a MinIO that has internet access, as it uses play.min.io as the source:

```yaml
replicate:
  apiVersion: v1
  source:
    type: minio
    bucket: fibbs
    endpoint: "https://play.min.io"
    path: "on"
    credentials:
      accessKey: Q3AM3UQ867SPQQA43P2F
      secretKey: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
  target:
    type: minio
    bucket: test
  flags:
    retry:
      attempts: 10 # number of retries for the job before giving up
      delay: "500ms" # least amount of delay between each retry
```

MinIO accepts this file:

```
mc batch start minio-1-lab-inqbeo replicate.yaml
Successfully started 'replicate' job `replicate-n39saQ8ztAPiD5YEAvFVdp:0` on '2024-08-30 15:06:40.52382943 +0000 UTC'
```

`mc admin trace --call brep minio-1-lab-inqbeo` (in another terminal at the time of starting the batch` shows NOTHING.

Nothing is being copied (of course, I have placed some objects on play.min.io's "fibbs" bucket before:

```
mc batch status minio-1-lab-inqbeo/ replicate-n39saQ8ztAPiD5YEAvFVdp:0
mc: Unable to find an active job, attempting to list from previously run jobs
✔ ✔ ✔
JobType:       	replicate
Objects:       	0
Versions:      	0
FailedObjects: 	0
Throughput:    	0 B/s
IOPs:          	0.00 objs/s
Transferred:   	0 B
Elapsed:       	367.304268ms
CurrObjName:
```

So, the only thing I can imagine doing wrong is that I understood something wrong in the documentation and I miss something in my replicate.yaml file... can you point me to where my mistake might be?

**Comment by fibbs** [comment]
OK, I think I've found it. With the new file I was playing around and going through the keys shown and found that as soon as I add a `prefix` to the source part, it suddenly works again.

I have placed a "directory" `testprefix` in my **fibbs** bucket on play.min.io and placed the same objects there as on the "root" level.

I now have modified my replicate.yaml file to be like this:

```yaml
replicate:
  apiVersion: v1
  source:
    type: minio
    bucket: fibbs
    endpoint: "https://play.min.io"
    prefix: "testbucket"
    path: "on"
    credentials:
      accessKey: Q3AM3UQ867SPQQA43P2F
      secretKey: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
  target:
    type: minio
    bucket: test
  flags:
    retry:
      attempts: 10 # number of retries for the job before giving up
      delay: "500ms" # least amount of delay between each retry
```

...and suddenly it started syncing stuff. I also now see the files being downloaded with the `mc trace` command:

```
2024-08-30T17:18:15.904 [BATCHREPLICATION] Replication() (job-name=replicate-MNucgi4QDJf87YyaoaB4tk:1,attempts=1st) minio-1-pool-0-1.minio-1-hl.minio-1.svc.cluster.local:9000 testprefix/testfile5m_2 (versionID=null) 4.921334797s
2024-08-30T17:18:15.907 [BATCHREPLICATION] Replication() (job-name=replicate-MNucgi4QDJf87YyaoaB4tk:1,attempts=1st) minio-1-pool-0-1.minio-1-hl.minio-1.svc.cluster.local:9000 testprefix/testfile5m_1 (versionID=null) 5.083752623s
2024-08-30T17:18:20.972 [BATCHREPLICATION] Replication() (job-name=replicate-MNucgi4QDJf87YyaoaB4tk:1,attempts=1st) minio-1-pool-0-1.minio-1-hl.minio-1.svc.cluster.local:9000 testprefix/testfile5m_3 (versionID=null) 4.308242025s
2024-08-30T17:18:20.991 [BATCHREPLICATION] Replication() (job-name=replicate-MNucgi4QDJf87YyaoaB4tk:1,attempts=1st) minio-1-pool-0-1.minio-1-hl.minio-1.svc.cluster.local:9000 testprefix/testfile5m_4 (versionID=null) 4.327747324s
```

But I didn't provide a prefix because I wanted the entire bucket to be "synced".... so I came up with the solution to supply `prefix: ""` and et voila: it works!

I believe this is a bug because docs and the generated file clearly state `prefix` is optional.
