### ISSUE TITLE
Helm install failure because of post-job.yaml

### ISSUE THREAD

**Issue by slim0** [minio/minio#20463]
## General summary

Starting with the default `values.yaml` file provided by the minio helm package, we wanted to not create any user during the `post-job` kubernetes Job.
To do that, we provided an empty list to the `users` value.

```yaml
users: []
```

Because `buckets`, `customCommands` and `svcaccts` values were also provided with an empty list (which is the default configuration), **and** `policies`  were provided, it ends with a deployment error.

## Expected Behavior
The helm deployment to work :)

## Current Behavior
The helm deployment is not working, with the following error:

```
Error: post-upgrade hooks failed: unable to build kubernetes object for post-upgrade hook minio/templates/post-job.yaml: error validating "": error validating data: ValidationError(Job.spec.template.spec): missing required field "containers" in io.k8s.api.core.v1.PodSpec
```

## Possible Solution
We added a dummy `customCommands`:

```yaml
customCommands:
  - command: "admin user list myminio"
```

## Steps to Reproduce (for bugs)

1. Create a `values.yaml` file :
```yaml
image:
  tag: RELEASE.2024-04-18T19-09-19Z
persistence:
  size: 10Gi
replicas: 2
resources:
  requests:
    memory: 1Gi
users: []
policies:
- name: fakePolicy
  statements:
  - actions:
    - s3:*
    resources:
    - arn:aws:s3:::test
```

2. Add minio helm repository: `helm repo add minio https://charts.min.io/`
3. Run helm installation: `helm install -f values.yaml minio/minio --generate-name`
