### ISSUE TITLE
batch expiry job doesn't report delete marker metrics in batch-status

### ISSUE THREAD

**Issue by krisis** [minio/minio#20506]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

batch-expiry jobs don't report delete marker status in batch-status. The metrics are calculated but aren't available via exported types in `madmin-go`'s [`ExpirationInfo`](https://github.com/minio/madmin-go/blob/main/metrics.go#L509).

## Expected Behavior

batch-status output for batch-expiry job should include delete marker stats when applicable.
## Current Behavior

batch-expiry jobs don't report delete marker status in batch-status. 
## Steps to Reproduce (for bugs)

1. Use the following yaml to start a batch expiry job
```
expire:
  apiVersion: v1
  bucket: mybucket  # Bucket where this job will expire matching objects from
  rules:
    - type: deleted # objects with delete marker as their latest version
      name: "*" # match object names that satisfy the wildcard expression.
      olderThan: 1h

  retry:
    attempts: 3 # number of retries for the job before giving up
    delay: 500ms # least amount of delay between each retry
```
2. For the above yaml to work, you need the following
- `mc mb ALIAS/mybucket`
- `mc version enable ALIAS/mybucket`
- Upload a few objects and delete some of them; To create delete markers
3. Now run, `mc batch start ALIAS /path/to/expire.yaml`
4. `mc batch status ALIAS $JOBID`
This will not display any delete marker stats.

## Regression

No

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):
