### ISSUE TITLE
GET PresignedURL behind Traefik Fails with SignatureDoesNotMatch

### ISSUE THREAD

**Issue by b-mounir-dev** [minio/minio#20594]
Encountering a `SignatureDoesNotMatch` error when trying to access GET PresignedURL behind Traefik.

This is my configuration:

`compose.yml`
```yml
services:
  # ....
  appminio:
    container_name: app-minio
    image: minio/minio:latest
    restart: unless-stopped
    command: minio server /var/lib/minio/data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
      MINIO_SERVER_URL: https://minio.example.com
      MINIO_BROWSER_REDIRECT_URL: https://console.example.com
    networks:
      - core
    expose:
      - 9000
      - 9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - volume-minio:/data
```

`Dockerfile`
```dockerfile
# ...
ENV MINIO_ENDPOINT="appminio:9000"
ENV MINIO_ACCESS_KEY="access"
ENV MINIO_SECRET_KEY="secret"
# ...
```
