### ISSUE TITLE
MINIO_LOGGER_WEBHOOK broken -  context deadline exceeded, since RELEASE.2024-09-22T00-33-43Z

### ISSUE THREAD

**Issue by markush81** [minio/minio#20630]
Configurung `MINIO_LOGGER_WEBHOOK_*` doesn't send logs to the Webhook.

## Expected Behavior

Logs are sent.

## Current Behavior

No Logs are sent.

## Steps to Reproduce (for bugs)

I tracked the down the release where behavior changed, but couldn't find any notes to that in Release Notes or documentation.

With release `RELEASE.2024-09-09T16-59-28Z` everything is working fine. 

![Screenshot 2024-11-10 at 11 27 13](https://github.com/user-attachments/assets/8bff1a61-c9e1-4501-a1f2-80c19482144c)

So everything fine here, the relevant audit entries and the error entry

Since release `RELEASE.2024-09-22T00-33-43Z` the Audit Webhook works, but Log Webhook gives

```
Error: unable to send audit/log entry(s) to 'minio-http-logger-DEFAULT' err 'http://elasticsearch:9200/minio4/_doc returned 'Post "http://elasticsearch:9200/minio4/_doc": context deadline exceeded', please check your endpoint configuration': 1 (*fmt.wrapError)
       4: internal/logger/logonce.go:64:logger.(*logOnceType).logOnceConsoleIf()
       3: internal/logger/logonce.go:157:logger.LogOnceConsoleIf()
       2: cmd/logging.go:132:cmd.configLogOnceConsoleIf()
       1: internal/logger/target/http/http.go:442:http.(*Target).startQueueProcessor()
```

![Screenshot 2024-11-10 at 11 48 56](https://github.com/user-attachments/assets/60d639b3-98d0-4794-aee2-4b69b29f467c)

Docker Compose Config

```
services:
  minio:
    container_name: minio
    hostname: minio
    image: quay.io/minio/minio:RELEASE.2024-09-22T00-33-43Z #RELEASE.2024-09-13T20-26-02Z #RELEASE.2024-09-09T16-59-28Z #RELEASE.2024-09-13T20-26-02Z
    command: server /data --address 0.0.0.0:9000 --console-address 0.0.0.0:9001
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_LOGGER_WEBHOOK_ENABLE_DEFAULT: on
      MINIO_LOGGER_WEBHOOK_ENDPOINT_DEFAULT: "http://elasticsearch:9200/minio4/_doc"
      MINIO_LOGGER_WEBHOOK_AUTH_TOKEN_DEFAULT: "Basic ZWxhc3RpYzpzZWNyZXQ="
      MINIO_AUDIT_WEBHOOK_ENABLE_DEFAULT: on
      MINIO_AUDIT_WEBHOOK_ENDPOINT_DEFAULT: http://elasticsearch:9200/minio4/_doc
      MINIO_AUDIT_WEBHOOK_AUTH_TOKEN_DEFAULT: "Basic ZWxhc3RpYzpzZWNyZXQ="

...
```
* no worries, fake credentials :D

## Your Environment

```
MinIO Object Storage Server
Copyright: 2015-2024 MinIO, Inc.
License: GNU AGPLv3 - https://www.gnu.org/licenses/agpl-3.0.html
Version: RELEASE.2024-09-22T00-33-43Z (go1.22.7 linux/arm64)
```
