### ISSUE TITLE
Issues Setting Prometheus Integration Environment Variables in MinIO Kubernetes helm chart

### ISSUE THREAD

**Issue by SyntaxJuggler** [minio/minio#20657]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## General Summary
I am experiencing an issue where I am unable to set specific environment variables necessary for Prometheus integration within the MinIO management panel despite following the configuration guidelines.

## Expected Behavior
I expect to set `MINIO_PROMETHEUS_URL` and `MINIO_PROMETHEUS_JOB_ID` environment variables to display Prometheus metrics on the MinIO control panel.

## Current Behavior
Despite setting the environment variables in a Kubernetes Secret and through Helm chart values as described in the documentation, they are not being recognized or applied within the MinIO deployment. When checking the environment variables using `kubectl exec` and viewing the `/tmp/minio/config.env`, the specified variables are not present or contain incorrect values.

## Possible Solution
Not obligatory, but suggest a fix/reason for the bug, or ideas how to implement the addition or change.

## Steps to Reproduce (for bugs)
1. Set up the Kubernetes Secret with the following values:
    ```
    apiVersion: v1
    kind: Secret
    type: Opaque
    metadata:
      name: minio-config-secret
    stringData:
      config.env: |
        export MINIO_PROMETHEUS_URL='http://prometheus-kube-prometheus-prometheus.prometheus.svc.cluster.local:9090'
        export MINIO_PROMETHEUS_JOB_ID="minio-job"
    ```
2. Deploy MinIO using Helm with the following value set for `existingSecret: true`.
3. Check the environment variables using `kubectl exec <pod-name> -- env`
4. Check the file `/tmp/minio/config.env`.

## Context
I am trying to integrate Prometheus with MinIO to monitor performance metrics directly from the MinIO console but am unable to do so due to this issue.

## Regression
No

## Your Environment
* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):
