### ISSUE TITLE
Reverse Proxying MinIO API through Nginx Returns 400 or 403

### ISSUE THREAD

**Issue by apolloxie** [minio/minio#20765]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior

When using Nginx Proxy Manager as a reverse proxy for MINIO's API, it should be accessible and function properly without any HTTP error codes.
## Current Behavior

After setting up Nginx Proxy Manager as a reverse proxy for MINIO's API, requests are met with HTTP 400 Bad Request or HTTP 403 Forbidden responses instead of the expected successful response.

## Possible Solution

One workaround is to bypass Nginx Proxy Manager and access MINIO directly via its IP address. However, this does not solve the underlying issue with the reverse proxy setup.
## Steps to Reproduce (for bugs)

1. The config for location / 
```plaintext
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
# proxy_set_header Origin "*";
# add_header 'Access-control-Allow-0rigin' '*';
# proxy_set_header Host "minio.abc.com:9443";
# proxy_set_header Host "minio.abc.com";
# proxy_set_header Host "127.0.0.1";
# proxy_set_header Host $http_host;
# proxy_set_header Host $host;
real_ip_header X-Real-IP;
proxy_connect_timeout 300;
chunked_transfer_encoding off;
proxy_set_header Connection "";
proxy_http_version 1.1;
```
2. If I use the directive proxy_set_header Host $http_host, it returns a 400 Bad Request. Otherwise, it returns a 403 Forbidden, and the mc command reports an error: "The request signature we calculated does not match the signature you provided. Check your key and signing method."
## Context

This issue prevents us from accessing MINIO services through a user-friendly domain name and potentially limits the functionality provided by Nginx Proxy Manager, such as SSL termination and path-based routing. It affects our ability to integrate MINIO into our production environment seamlessly.
## Regression

No
## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):
Docker-compose File:
```yaml
version: '3.8'
services:
  minio:
    image: 'minio/minio'
    restart: always
    ports:
      - '39001:9001'
      - '39000:9000'
    volumes:
      - /mnt/ALFD-HDD/app-data/minio/data:/mnt/data
    environment:
      - MINIO_ROOT_USER=username
      - MINIO_ROOT_PASSWORD=password
     # - MINIO_SERVER_URL=http://minio.abc.com
      - MINIO_BROWSER_REDIRECT_URL=https://minio-console.abc.com:9443
    command: server /mnt/data --console-address ":9001"
```
