### ISSUE TITLE
[ERROR] Docker images are no longer compatible as before

### ISSUE THREAD

**Issue by freemankevin** [minio/minio#20778]
### Image version used
`minio/minio:RELEASE.2024-11-07T00-52-20Z`

### Here are the image details
```shell
            "OnBuild": null,
            "Labels": {
                "architecture": "x86_64",
                "build-date": "2024-08-27T19:24:54",
                "com.redhat.component": "ubi9-micro-container",
                "com.redhat.license_terms": "https://www.redhat.com/en/about/red-hat-end-user-license-agreements#UBI",
                "description": "MinIO object storage is fundamentally different. Designed for performance and the S3 API, it is 100% open-source. MinIO is ideal for large, private cloud environments with stringent security requirements and delivers mission-critical availability across a diverse range of workloads.",
                "distribution-scope": "public",
                "io.buildah.version": "1.29.0",
                "io.k8s.description": "Very small image which doesn't install the package manager.",
                "io.k8s.display-name": "Ubi9-micro",
                "io.openshift.expose-services": "",
                "maintainer": "MinIO Inc <dev@min.io>",
                "name": "MinIO",
                "release": "RELEASE.2024-11-07T00-52-20Z",
                "summary": "MinIO is a High Performance Object Storage, API compatible with Amazon S3 cloud storage service.",
                "url": "https://access.redhat.com/containers/#/registry.access.redhat.com/ubi9/ubi-micro/images/9.4-15",
                "vcs-ref": "cd5996c9b8b99b546584696465f8f39ec682078c",
                "vcs-type": "git",
                "vendor": "MinIO Inc <dev@min.io>",
                "version": "RELEASE.2024-11-07T00-52-20Z"
            }
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 165054987,
        "VirtualSize": 165054987,
```

### compose startup error log

`minio.yml`
```yml
  minio:
    image: "${MINIO_IMAGE}"
    #read_only: true
    deploy:
      resources:
        limits:
          memory: 4096M
    networks:
      - middleware 
    container_name: minio
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/minio/data:/data
    restart: always

```

```shell
minio  | Fatal glibc error: CPU does not support x86-64-v2
minio  | Fatal glibc error: CPU does not support x86-64-v2
minio  | Fatal glibc error: CPU does not support x86-64-v2
minio  | Fatal glibc error: CPU does not support x86-64-v2
```

## My Environment

```shell
[root@localhost installmiddleware]# cat /etc/.productinfo 
Kylin Linux Advanced Server
release V10 SP3 2403/(Halberd)-x86_64-Build20/20240426
[root@localhost installmiddleware]# 
[root@localhost installmiddleware]# 
[root@localhost installmiddleware]# uname -r 
4.19.90-89.11.v2401.ky10.x86_64
[root@localhost installmiddleware]# uname -a
Linux localhost.localdomain 4.19.90-89.11.v2401.ky10.x86_64 #1 SMP Tue May 7 18:33:01 CST 2024 x86_64 x86_64 x86_64 GNU/Linux
[root@localhost installmiddleware]# 
[root@localhost installmiddleware]# docker info
Client: Docker Engine - Community
 Version:    24.0.2
 Context:    default
 Debug Mode: false

Server:
 Containers: 5
  Running: 3
  Paused: 0
  Stopped: 2
 Images: 8
 Server Version: 24.0.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1c90a442489720eec95342e1789ee8a5e1b9536f
 runc version: v1.1.8-0-g82f18fe0
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
 Kernel Version: 4.19.90-89.11.v2401.ky10.x86_64
 Operating System: Kylin Linux Advanced Server V10 (Halberd)
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 30.15GiB
 Name: localhost.localdomain
 ID: bc284ede-265a-42dc-9b98-f0d73aa9a82c
 Docker Root Dir: /data/docker
 Debug Mode: false
 Experimental: true
 Insecure Registries:
  0.0.0.0/0
  127.0.0.0/8
 Registry Mirrors:
  https://ustc-edu-cn.mirror.aliyuncs.com/
 Live Restore Enabled: true

```
