### ISSUE TITLE
Can't change bucket policy

### ISSUE THREAD

**Issue by iutx** [minio/minio#20792]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

Can't fetch `set-policy` api.

## Expected Behavior

Set bucket policy from private to public.

## Current Behavior

Can't set bucket policy, api fetch result is `Empty reply from server`

## Steps to Reproduce (for bugs)

1. Create a new bucket, not set quota and version.
2. Set policy from private to public

## Context

curl fetch result
```shell
curl 'http://minio.internal.domain/api/v1/buckets/demo/set-policy' \
  -X 'PUT' \
  -H 'Accept: */*' \
  -H 'Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json' \
  -H 'Cookie: ***' \
  -H 'Origin: http://minio.internal.haihua.com.cn' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0' \
  --data-raw '{"access":"PUBLIC","definition":"{\n    \"Version\": \"2012-10-17\",\n    \"Statement\": [\n        \n    ]\n}"}'
curl: (52) Empty reply from server
```

Others api can fetch success, e.g.
<img width="1325" alt="Clipboard_Screenshot_1735177694" src="https://github.com/user-attachments/assets/be95a7d6-6af0-40ac-abb5-b74078e71f0f" />

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

 Image: minio/minio:RELEASE.2024-12-18T13-15-44Z-cpuv1
 Deploy way: minio-operator, version: v5.0.15
 KES?: not set
 Kubernetes: v1.30.1
 OS: Linux erda-prod-lb-01 5.5.5-1.el7.elrepo.x86_64 #1 SMP Wed Feb 19 07:54:53 EST 2020 x86_64 x86_64 x86_64 GNU/Linux
 storage-configuration:
```shell
  config.env: |-
    export MINIO_ROOT_USER="minio"
    export MINIO_ROOT_PASSWORD="**"
    export MINIO_PUBLIC_ENDPOINT="https://domain"
    export MINIO_BROWSER_REDIRECT_URL="http://minio.internal.domain"
```

**Comment by iutx** [comment]
tenant config:
```yaml
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  labels:
    app: minio
  name: minio
  namespace: minio-prod
spec:
  configuration:
    name: storage-configuration
  env: []
  externalCaCertSecret: []
  externalCertSecret: []
  externalClientCertSecrets: []
  features:
    bucketDNS: false
    domains: {}
  image: minio/minio:RELEASE.2024-12-18T13-15-44Z-cpuv1
  imagePullSecret: {}
  mountPath: /export
  podManagementPolicy: Parallel
  pools:
  - name: pool-0
    resources: 
      limits:
        cpu: "2"
        memory: 4Gi
      requests:
        cpu: "1"
        memory: 2Gi
    securityContext:
      fsGroup: 1000
      fsGroupChangePolicy: OnRootMismatch
      runAsGroup: 1000
      runAsNonRoot: true
      runAsUser: 1000
    servers: 1
    volumeClaimTemplate:
      apiVersion: v1
      kind: persistentvolumeclaims
      metadata: {}
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Ti
        storageClassName: dice-nfs-volume
    volumesPerServer: 1
  requestAutoCert: false
  users:
  - name: storage-user
  ```
