### ISSUE TITLE
it is not possible to change API and console port inside docker env

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [minio/minio#20804]
I have simple compose file 

```
version: '3.2'
services:
  minio:
    container_name: minio
    image: minio/minio:RELEASE.2024-12-18T13-15-44Z
    networks:
      - minio
    environment:
      - MINIO_CONFIG_ENV_FILE=/etc/config.env
      - MINIO_OPTS="--address :8050 --console-address :8051"

    volumes:
      - ./conf/config.env:/etc/config.env
      - ./data:/mnt/data
    restart: unless-stopped
    command:
      - 'server --console-address :8051 --address :8050'
    ports:
      - "8050:8050"
      - "8051:8051"

```

## Expected Behavior

All have to work normally

## Current Behavior

after start i get 
```

‘server --console-address :8051 --address :8050’ is not a minio sub-command. See ‘minio --help’.
‘server --console-address :8051 --address :8050’ is not a minio sub-command. See ‘minio --help’.
‘server --console-address :8051 --address :8050’ is not a minio sub-command. See ‘minio --help’.
‘server --console-address :8051 --address :8050’ is not a minio sub-command. See ‘minio --help’.
‘server --console-address :8051 --address :8050’ is not a minio sub-command. See ‘minio --help’.
‘server --console-address :8051 --address :8050’ is not a minio sub-command. See ‘minio --help’.
```

It feels like functionality to change port on minio completely broken. 

if to set in compose : 
```
    command:
      - 'server'
      - ' --console-address ":8051"'
      - ' --address ":8050"'
```

It starts but using random ports . So command line arguments ignored. 

if to use : 

```
    environment:
      - MINIO_CONFIG_ENV_FILE=/etc/config.env
      - MINIO_OPTS="--address :8050 --console-address :8051"
#      - MINIO_ADDRESS=":8050"
      - MINIO_CONSOLE_ADDRESS="minio:8051"
```

I get : 

```
FATAL Unable to split host port "minio:8051": invalid port number
FATAL Unable to split host port "minio:8051": invalid port number
FATAL Unable to split host port "minio:8051": invalid port number
```

**Comment by jpVm5jYYRE1VIKL** [comment]
if to make : 
```
    environment:
      - MINIO_CONFIG_ENV_FILE=/etc/config.env
      - MINIO_OPTS="--address :8050 --console-address :8051"
#      - MINIO_ADDRESS=":8050"
      - MINIO_CONSOLE_ADDRESS=":8051"

```
then : 
```
FATAL Unable to split host port ":8051": invalid port number
FATAL Unable to split host port ":8051": invalid port number
```
if to make : 
```
    environment:
      - MINIO_CONFIG_ENV_FILE=/etc/config.env
      - MINIO_OPTS="--address :8050 --console-address :8051"
#      - MINIO_ADDRESS=":8050"
      - MINIO_CONSOLE_ADDRESS="0.0.0.0:8051"

```
then : 

```
FATAL Unable to split host port "0.0.0.0:8051": invalid port number
FATAL Unable to split host port "0.0.0.0:8051": invalid port number

```

if to make : 
```
    environment:
      - MINIO_CONFIG_ENV_FILE=/etc/config.env
      - MINIO_OPTS="--address :8050 --console-address :8051"
#      - MINIO_ADDRESS=":8050"
      - MINIO_CONSOLE_ADDRESS="8051"

```
then : 
```
FATAL Unable to start listening on console port: address "8051": missing port in address
FATAL Unable to start listening on console port: address "8051": missing port in address
FATAL Unable to start listening on console port: address "8051": missing port in address
```

**Comment by harshavardhana** [comment]
Just do this, I don't know what you are doing.

```
  command: server --address ":9090" --console-address ":9001" http://minio{1...4}/pdata{1...2} http://minio{5...8}/pdata{1...2}
  expose:
    - "9090"
    - "9001"
```

**Comment by jpVm5jYYRE1VIKL** [comment]
Did like you suggested : 
```
    restart: unless-stopped
    command:
      - server --address ":8050" --console-address ":8051" http://minio{1...4}/pdata{1...2} http://minio{5...8}/pdata{1...2}
    ports:
      - "8050:9000"
      - "8051:9001"
```

in logs : 


```
‘server --address ":8050" --console-address ":8051" http://minio{1...4}/pdata{1...2} http://minio{5...8}/pdata{1...2}’ is not a minio sub-command. See ‘minio --help’.

‘server --address ":8050" --console-address ":8051" http://minio{1...4}/pdata{1...2} http://minio{5...8}/pdata{1...2}’ is not a minio sub-command. See ‘minio --help’.

‘server --address ":8050" --console-address ":8051" http://minio{1...4}/pdata{1...2} http://minio{5...8}/pdata{1...2}’ is not a minio sub-command. See ‘minio --help’.

‘server --address ":8050" --console-address ":8051" http://minio{1...4}/pdata{1...2} http://minio{5...8}/pdata{1...2}’ is not a minio sub-command. See ‘minio --help’.

‘server --address ":8050" --console-address ":8051" http://minio{1...4}/pdata{1...2} http://minio{5...8}/pdata{1...2}’ is not a minio sub-command. See ‘minio --help’.

‘server --address ":8050" --console-address ":8051" http://minio{1...4}/pdata{1...2} http://minio{5...8}/pdata{1...2}’ is not a minio sub-command. See ‘minio --help’.

‘server --address ":8050" --console-address ":8051" http://minio{1...4}/pdata{1...2} http://minio{5...8}/pdata{1...2}’ is not a minio sub-command. See ‘minio --help’.

‘server --address ":8050" --console-address ":8051" http://minio{1...4}/pdata{1...2} http://minio{5...8}/pdata{1...2}’ is not a minio sub-command. See ‘minio --help’.

‘server --address ":8050" --console-address ":8051" http://minio{1...4}/pdata{1...2} http://minio{5...8}/pdata{1...2}’ is not a minio sub-command. See ‘minio --help’.

‘server --address ":8050" --console-address ":8051" http://minio{1...4}/pdata{1...2} http://minio{5...8}/pdata{1...2}’ is not a minio sub-command. See ‘minio --help’.
```

**Comment by harshavardhana** [comment]
> version: '3.2'

Perhaps your broken local deployment for docker-compose

```
docker-compose -f minio-erasure.yaml up
Recreating minio_minio1_1 ... done
Attaching to minio_minio1_1
minio1_1  | MinIO Object Storage Server
minio1_1  | Copyright: 2015-2025 MinIO, Inc.
minio1_1  | License: GNU AGPLv3 - https://www.gnu.org/licenses/agpl-3.0.html
minio1_1  | Version: RELEASE.2024-12-18T13-15-44Z (go1.23.4 linux/amd64)
minio1_1  | 
minio1_1  | API: http://172.18.0.2:9090  http://127.0.0.1:9090 
minio1_1  | WebUI: http://172.18.0.2:9091 http://127.0.0.1:9091 
minio1_1  | 
minio1_1  | Docs: https://docs.min.io
minio1_1  | WARN: Detected default credentials 'minioadmin:minioadmin', we recommend that you change these values with 'MINIO_ROOT_USER' and 'MINIO_ROOT_PASSWORD' environment variables
```

```yaml
version: '3.7'

# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2024-12-18T13-15-44Z
  command: server --address ":9090" --console-address ":9091" /data
  expose:
    - "9090"
    - "9091"
  environment:
    MINIO_CI_CD: "on"
  healthcheck:
    test: ["CMD", "mc", "ready", "local"]
    interval: 5s
    timeout: 5s
    retries: 5

services:
  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - data:/data

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  data:
```
