### ISSUE TITLE
Helm Chart: Implement Object Lifecycle Management on Bucket creation

### ISSUE THREAD

**Issue by schroedermatthias** [minio/minio#20805]
**Is your feature request related to a problem? Please describe.**
I want to have Object Lifecycle Management as Code (defined in my Helm values).

**Describe the solution you'd like**
The current bucket creation syntax only allows the following properties: `name, policy, purge, versioning, objectlocking`.
It would be great to have a property called `lifecycleConfig`  that gets interpreted when the bucket creation script runs. 

Suggestion:

```
buckets:
  - name: "my-bucket"
    policy: "none"
    lifecycleConfig:
      rules:
        - id: "ExpireOldObjects"
          prefix: ""
          status: "Enabled"
          expiration:
            days: 30
```

**Describe alternatives you've considered**
Setting via mc is possible, but I want to have it IAC.

**Additional context**
See https://min.io/docs/minio/linux/administration/object-management/object-lifecycle-management.html
