### ISSUE TITLE
release.2025-02-07t23-21-09z: Checksum requires Client with TrailingHeaders enabled

### ISSUE THREAD

**Issue by ro0NL** [minio/minio#20912]
Our tests suddenly exit with `ftp_fput(): error during transfer: Checksum requires Client with TrailingHeaders enabled` since this version.

Using docker compose:

```
    minio:
        image: 'minio/minio:RELEASE.2025-02-03T21-03-04Z'
        restart: unless-stopped
        command:
            - 'server'
            - '--console-address=:9001'
            - '--ftp=address=:8021'
            - '--sftp=address=:8022'
            - '--sftp=ssh-private-key=/root/.ssh/id_rsa'
            - '/data'
```
