### ISSUE TITLE
Broken link in the docs

### ISSUE THREAD

**Issue by kasir-barati** [minio/minio#20940]
## NOTE

In [this page](https://github.com/minio/minio/blob/master/docs/debugging/README.md) the [`mc admin trace`](https://github.com/minio/mc/blob/master/docs/minio-admin-complete-guide.md#command-trace---display-minio-server-http-trace) is a broken link

## Expected Behavior

Open the page

## Current Behavior

Broken

## Possible Solution

Just go to that page

## Steps to Reproduce (for bugs)

n/a.

## Context

docs

## Regression

n/a

## Your Environment

n/a.

**Comment by kasir-barati** [comment]
And the docker compose in the docs does not work: https://github.com/minio/minio/blob/60446e7ac0b1875c769f1ad6f45cd3be8d718f85/docs/orchestration/docker-compose/docker-compose.yaml#L14

Here is my compose file and it is unhealthy:
```yml
services:
  minio:
    image: minio/minio
    ports:
      - 9000:9000 # API
      - 9001:9001 # console
    volumes:
      - minio:/data
    env_file:
      - .env
    command: server /data --console-address ":9001" --address ":9090"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 3

volumes:
  minio:
```

While it is up and running.
