### ISSUE TITLE
Unable to start a replication job using the MinIO batch framework (XMinioAdminInvalidArgument)

### ISSUE THREAD

**Issue by qjoly** [minio/minio#20984]
Unable to start a replication job using the MinIO batch framework due to the error: `XMinioAdminInvalidArgument`.

## Expected Behavior
The replication job should start successfully when using the provided configuration file and command.

## Current Behavior
The job fails with the error: `XMinioAdminInvalidArgument` and the message "Invalid arguments specified."

## Steps to Reproduce (for bugs)
1. Use the following configuration file (`replication-job.yaml`):
```yaml
replicate:
  apiVersion: v1
  source:
    type: minio
    bucket: abra
    credentials:
      accessKey: Q3AM3UQ867SPQQA43P2F
      secretKey: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG

  target:
    type: minio
    bucket: cadabra
    endpoint: "https://play.min.io/"
    credentials:
      accessKey: Q3AM3UQ867SPQQA43P2F
      secretKey: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
  flags:
    retry:
      attempts: 3 
      delay: "500ms"
```

2.  Run the command:
```bash
mc batch start playminio replication-job.yaml --debug
```
3. Observe the error:

```bash
mc batch start playminio playminio.yaml --debug
mc: <DEBUG> POST /minio/admin/v3/start-job HTTP/1.1
Host: play.min.io
User-Agent: MinIO (darwin; arm64) madmin-go/3.0.70 mc/RELEASE.2025-02-04T04-57-50Z
Content-Length: 577
Accept-Encoding: zstd,gzip
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20250226//s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: 6cedfbce8139a87327d1f2a178cdd6a42aa612b20d2bf21a0ec166ade73c70e9
X-Amz-Date: 20250226T153324Z

mc: <DEBUG> HTTP/1.1 400 Bad Request
Content-Length: 246
Accept-Ranges: bytes
Connection: keep-alive
Content-Type: application/json
Date: Wed, 26 Feb 2025 15:33:25 GMT
Server: nginx/1.18.0 (Ubuntu)
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Bucket-Region: us-east-1
X-Amz-Id-2: 3e996b2f640d7e065d3a5c4e39a5538cefb82e3e77771990265e4698d8681eac
X-Amz-Request-Id: 1827CBEE54B6436A
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block

{"Code":"XMinioAdminInvalidArgument","Message":"Invalid arguments specified.","Resource":"/minio/admin/v3/start-job","Region":"us-east-1","RequestId":"1827CBEE54B6436A","HostId":"3e996b2f640d7e065d3a5c4e39a5538cefb82e3e77771990265e4698d8681eac"}
mc: <DEBUG> TLS Certificate found: 
mc: <DEBUG>  >> Country: US
mc: <DEBUG>  >> Organization: Let's Encrypt
mc: <DEBUG>  >> Expires: 2025-04-17 05:49:37 +0000 UTC
mc: <DEBUG> TLS Certificate found: 
mc: <DEBUG>  >> Country: US
mc: <DEBUG>  >> Organization: Internet Security Research Group
mc: <DEBUG>  >> Expires: 2027-03-12 23:59:59 +0000 UTC
mc: <DEBUG> Response Time:  680.760875ms

mc: <ERROR> Unable to start job. Invalid arguments specified.
 (0) batch-start.go:103 cmd.mainBatchStart(..)
 Commit:318e7070718f | Release-Tag:RELEASE.2025-02-04T04-57-50Z | Host:qjoly-mac | OS:darwin | Arch:arm64 | Lang:go1.23.5 | Mem:2.3 MiB/14 MiB | Heap:2.3 MiB/7.3 MiB. 
```

## Your Environment
  - Version used (minio --version):
        MinIO Server: RELEASE.2025-02-18T16-25-55Z
        MinIO Client (mc): RELEASE.2025-02-15T10-36-16Z
  - Server setup and configuration:
        MinIO server running in a Kubernetes cluster.
        Replication job configured between a source bucket (test) and a target bucket (quentin).
  - Operating System and version (uname -a):
        Host: macOS (arm64) (I also tried the mc inside the minio container)
        Container: Linux (amd64), hosted on a kubernetes cluster

**Comment by shtripat** [comment]
Try with below YAML and it should work. As you run the job against a MinIO alias already, no need to pass creds for source.

```
replicate:
  apiVersion: v1
  source:
    type: minio
    bucket: abra
  target:
    type: minio
    bucket: cadabra
    endpoint: "https://play.min.io/"
    credentials:
      accessKey: Q3AM3UQ867SPQQA43P2F
      secretKey: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
  flags:
    retry:
      attempts: 3
      delay: "500ms"
```
