### ISSUE TITLE
Virtual Hosts - List Bucket return empty list

### ISSUE THREAD

**Issue by dbuchhorn** [minio/minio#20990]
I would like to use minio with virtual host. I run a minio docker container. After creating a test bucket und put some files in it the buckets can be listed but the files in a bucket can't. I also do an inspection with "mc admin trace". If the path style is used then the xml contains the files but with virtual hosts the xml contains no files. The "Host" header contains the right subdomain. I use the amazon s3 java library to create the request.

## Expected Behavior
- files should be listed in virtual host style

## Current Behavior
- files not listed in virtual host style

## Steps to Reproduce (for bugs)
docker-compose.yaml
```
services:
  minio:
    image: quay.io/minio/minio:RELEASE.2025-02-18T16-25-55Z
    container_name: minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    ports:
      - "19001:9001"
      - "19000:9000"
    volumes:
      - ./data:/data
    environment:
      - TZ=Europe/Berlin
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:?MINIO_ROOT_USER not set}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:?MINIO_ROOT_PASSWORD not set}
      - MINIO_SERVER_URL=http://minio:9000
      - MINIO_BROWSER_REDIRECT_URL=http://minio.example.net:19001
      - MINIO_DOMAIN="minio.example.net"
      - MINIO_BROWSER_LOGIN_ANIMATION=off
    networks:
      - external_net

networks:
  external_net:
    external: true
```

.env file
```
MINIO_ROOT_USER="root"
MINIO_ROOT_PASSWORD="password"
```

resolve minio.example.net and test.minio.example.net to 127.0.0.1

## Your Environment
* minio version RELEASE.2025-02-18T16-25-55Z (commit-id=90f5e1e5f62cbc47be6d0a3ca0634bfd84c2248c)
  Runtime: go1.23.6 linux/amd64
* also testen on a raspberry pi 4
* Operating System and version (`uname -a`): 5.15.167.4-microsoft-standard-WSL2 (Ubuntu 24.04)
* Docker version: 28.0.0
