### ISSUE TITLE
Transforms with Object Lambda The security token included in the request is invalid

### ISSUE THREAD

**Issue by mmahditalachi** [minio/minio#21104]
## Expected Behavior  
I am trying to use MinIO Object Transforms following the official documentation [here](https://min.io/docs/minio/linux/developers/transforms-with-object-lambda.html#).  
I expect to generate a presigned URL that allows me to download the transformed object successfully.  

## Current Behavior  
When I try to download the object using the presigned URL, I receive the following error response:  

```
<?xml version="1.0" encoding="UTF-8"?>\n
<Error>
    <Code>InvalidTokenId</Code>
    <Message>The security token included in the request is invalid</Message>
    <Key>000bd20a46790a88ff79cc3d4f5d21e0d6e121b6dc9fe10c76271f379af5fb2f.txt</Key>
    <BucketName>place</BucketName>
    <Resource>/place/000bd20a46790a88ff79cc3d4f5d21e0d6e121b6dc9fe10c76271f379af5fb2f.txt</Resource>
    <RequestId>183298B2B91FD9C9</RequestId>
    <HostId>dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8</HostId>
</Error>
```  

## Possible Solution  
- Verify that the object lambda ARN and webhook endpoint are correctly set up.  
- Check whether MinIO has any additional authorization requirements for Object Transforms.  
- Debug the request flow to confirm that the security token is being correctly passed.  

## Steps to Reproduce (for bugs)  

1. Run MinIO using the following `docker-compose.yml` file:  

   ```yaml
   services:
     minio:
       image: minio/minio:latest
       command: server /data --console-address ":9001"
       container_name: minio
       ports:
         - "90:9000"
         - "9001:9001"
       environment:
         MINIO_ROOT_USER: admin
         MINIO_ROOT_PASSWORD: password
         MINIO_LAMBDA_WEBHOOK_ENABLE_resize-image: on
         MINIO_LAMBDA_WEBHOOK_ENDPOINT_resize-image: http://alphabeta-transformer-api:5000/transform
         MINIO_LOG_LEVEL: debug
       volumes:
         - ./data:/data
       restart: always
   ```

2. Start a simple Flask-based webhook handler:  

   ```python
   from flask import Flask, request, abort, make_response
   import requests

   app = Flask(__name__)

   @app.route('/', methods=['POST'])
   def get_webhook():
      if request.method == 'POST':
         event = request.json

         object_context = event["getObjectContext"]
         s3_url = object_context["inputS3Url"]
         request_route = object_context["outputRoute"]
         request_token = object_context["outputToken"]

         r = requests.get(s3_url)
         original_object = r.content.decode('utf-8')

         transformed_object = original_object.swapcase()

         resp = make_response(transformed_object, 200)
         resp.headers['x-amz-request-route'] = request_route
         resp.headers['x-amz-request-token'] = request_token
         return resp
      else:
         abort(400)

   if __name__ == '__main__':
      app.run()
   ```

3. Run the following Python client code to generate a presigned URL and attempt to fetch the transformed object:  

   ```python
   from minio import Minio
   import requests
   from datetime import timedelta

   minio_endpoint = '127.0.0.1:90'
   minio_access_key = 'access'
   minio_secret_key = 'secret'

   s3Client = Minio(minio_endpoint, access_key=minio_access_key, secret_key=minio_secret_key, secure=False)

   lambda_arn = 'arn:minio:s3-object-lambda::resize-image:webhook'

   bucket_name = 'place'
   object_name = '000bd20a46790a88ff79cc3d4f5d21e0d6e121b6dc9fe10c76271f379af5fb2f.txt'
   expiration = timedelta(seconds=1000)  

   req_params = {'lambdaArn': lambda_arn, "width": "10"}
   presigned_url = s3Client.presigned_get_object(bucket_name, object_name, expires=expiration, extra_query_params=req_params)
   print(presigned_url)

   response = requests.get(presigned_url)

   if response.status_code == 200:
       content = response.content
       print("Transformed data:\n", content)
   else:
       print("Failed to download the data. Status code:", response.status_code, "Reason:", response.reason)
       print("\n", response.content)
   ```

4. Observe the error message in the response.  

## Context  
This issue prevents me from successfully using MinIO Object Transforms via presigned URLs. My goal is to process objects dynamically using a webhook before they are downloaded.  

## Regression  
Not sure if this is a regression. I am using the latest version of MinIO.  

## Your Environment  
- **MinIO Version:** (`latest`)  
- **Server Setup and Configuration:** Running via Docker Compose  
- **Operating System:** (`ubuntu 22.04`)  

---
