### ISSUE TITLE
MinIO Console Fails to Authenticate Behind HTTPS Reverse Proxy (caddy V2)

### ISSUE THREAD

**Issue by Novapixel1010** [minio/minio#21186]
### Summary

When running the official MinIO Docker container behind a local reverse proxy (Caddy) with a self-signed TLS certificate, the MinIO console fails to authenticate, returning a `401 Unauthorized` error even with correct credentials.

---

### 🧪 Environment

- **MinIO Image**: `minio/minio` (official Docker image)
- **OS (host)**: Debian 12 with portainer
- **Reverse Proxy**: Caddy v2 (self-hosted with HTTPS enabled)
- **Domain setup**:
  - `https://console.storage.in.com` → MinIO Console (port 9001)
  - `https://storage.in.com` → S3 API (port 9005)

---

### 🔍 Steps to Reproduce

1. Run MinIO in Docker using the official image, exposing ports 9005 and 9001.
2. Configure Caddy as a reverse proxy to serve HTTPS via its local CA.
3. Set `MINIO_SERVER_URL=https://storage.in.com` in the environment.
4. Mount the Caddy root CA at `/root/.minio/certs/CAs/myCA.crt` inside the container.
5. Try to log in to the MinIO console via `https://console.storage.in.com`.

---

### ❌ Expected Behavior

The login should succeed using the provided `MINIO_ROOT_USER` and `MINIO_ROOT_PASSWORD` credentials.

---

### ❌ Actual Behavior

- The login fails with a `401 Unauthorized` error.
- Curl requests to the S3 API over HTTPS from within the container also fail with: 
`curl: (35) TLS connect error: error:0A000438:SSL routines::tlsv1 alert internal error`

## Possible Solution
Not sure yet. 
- Maybe an image that you can trust certs for having custom certs.
- Is there a need for minio to trust the certs? I thought that is handled by the browser and the web server

## caddy config

```caddyfile

# minio domains
*.storage.in.com {
  reverse_proxy localhost:9007 {
    header_up Host {host}
    header_up X-Forwarded-Host {host}
    header_up X-Real-IP {remote}
    header_up X-Forwarded-For {remote}
    header_up X-Forwarded-Proto {scheme}
    header_up Connection ""
    header_up Upgrade {>Upgrade}
  }

  # Remove body size limits (like client_max_body_size 0)
  request_body {
    max_size 0
  }
}

console.storage.in.com {
  reverse_proxy localhost:9001 {
    header_up Host {host}
    header_up X-Forwarded-Host {host}
    header_up X-Real-IP {remote}
    header_up X-Forwarded-For {remote}
    header_up X-Forwarded-Proto {scheme}
    header_up X-NginX-Proxy true
    header_up Connection ""
    header_up Upgrade {>Upgrade}
  }

  # Optional: No size limits and chunk handling
  request_body {
    max_size 0
  }
}

```

## compose file

```
services:
  minio:
    image: minio/minio
    container_name: minio
    # restart: always
    ports:
      - "9007:9000"   # S3 API
      - "9001:9001"   # Web Console
    volumes:
      - /portainer/Files/AppData/minio:/data
      - /var/lib/caddy/.local/share/caddy/pki/authorities/local/root.crt:/root/.minio/certs/CAs/myCA.crt
    environment:
      MINIO_ROOT_USER: mike
      MINIO_ROOT_PASSWORD: Nova-tech
      MINIO_BROWSER_REDIRECT_URL: https://console.storage.in.com
      MINIO_SERVER_URL: https://storage.in.com

    command: server /data --address ":9000" --console-address ":9001"

```
