### ISSUE TITLE
minio_bucket metrics missing on v3

### ISSUE THREAD

**Issue by alexifsp** [minio/minio#21301]
Trying to use minio_bucket_* metrics but they are missing on v3 api.

## Expected Behavior

Enabling metrics on minio does not bring minio_bucket_* on api v3. 
On api v2 metrics are available.

All other metrics seems to work fine. Without any issue.
Performed various actions on bucket_apis but yet no metric available. Same procedure executed on v2 is working just fine.

Used following configuration:

```yaml
apiVersion: minio.min.io/v2
    kind: Tenant
    metadata:
      name: minio-multi-node
    spec:
      imagePullPolicy: Always
      requestAutoCert: false
      env:
        - name: MINIO_PROMETHEUS_AUTH_TYPE
          value: public
      poolsMetadata:
        annotations:
          prometheus.io/path: "/minio/metrics/v3"
          prometheus.io/port: "9000"
          prometheus.io/scrape: "true"
      buckets:
        - name: tempo-storage
      configuration:
        name: minio-tenant-config
      pools:
        - servers: 4
          name: pool
          volumesPerServer: 2
          volumeClaimTemplate:
            metadata:
              name: data
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Gi
```
