### ISSUE TITLE
Missing administrator function on left navigation bar

### ISSUE THREAD

**Issue by J4CkM4n** [minio/minio#21347]
## Expected Behavior
The left navigation bar should have more functions for administrators / root

Version: RELEASE.2025-04-22T22-12-26Z
![Image](https://github.com/user-attachments/assets/726ca839-b715-4577-b801-9bfb235998d6)

## Current Behavior
The left navigation bar is missing all administrative functions.

Version: RELEASE.2025-05-24T17-08-30Z (latest)
![Image](https://github.com/user-attachments/assets/3be912bd-1a2e-49f6-96dd-9cf8ef841a0c)

## Steps to Reproduce (for bugs)

1. docker pull the latest version
2. docker create minio container with console on 9001 port
3. access console with pre-configed root user

```
services:
    minio:
        ports:
            - 9000:9000
            - 9001:9001
        container_name: minio
        volumes:
            - ./data:/data
        environment:
            - MINIO_ROOT_USER=ROOT_USER
            - MINIO_ROOT_PASSWORD=ROOT_PW
        image: quay.io/minio/minio:latest
        command: server /data --console-address ":9001"
```

## Context

I can't edit any setting for the bucket.

## Your Environment
* Version used (`minio --version`): RELEASE.2025-05-24T17-08-30Z (go1.24.3 linux/amd64)
* Server setup and configuration: Docker Compose
* Operating System and version (`uname -a`): Debian 12 with docker
