### ISSUE TITLE
LDAP authentication fails in Console with valid config, no logs or errors

### ISSUE THREAD

**Issue by 8Iue** [minio/minio#21350]
## Expected Behavior

When LDAP authentication is correctly configured, users belonging to the right LDAP groups should be able to log in to the MinIO Console (deployed via Helm) with their LDAP credentials.

---

## Current Behavior

* Logging in to the Console with valid LDAP credentials **fails silently** (404 or blank/no error).
* No relevant LDAP error logs are shown in MinIO container logs or via `mc admin trace`.
* When an **incorrect** LDAP bind password is set, MinIO logs the expected "invalid credentials" error and retries.
* When the **correct** password is set, the connection is healthy, no errors in logs, but authentication never succeeds. `tcpdump` never shows outbound traffic on our LDAP server

---

## Possible Solution

It appears the issue could be a regression in recent MinIO/Console releases related to LDAP auth, possibly in the Console backend’s integration with LDAP or the way users/groups are mapped. See below for full context and steps.

---

### 1. Deploy MinIO via Helm with the following environment (values redacted):

```yaml
tenant:
  name: 'tenant-gitlab-ci'
  mountPath: '/export'
  requestAutoCert: true
  env:
    - name: 'MINIO_LOG_LEVEL'
      value: 'debug'
    - name: 'MINIO_IDENTITY_LDAP_ENABLE'
      value: 'on'
    - name: 'MINIO_IDENTITY_LDAP_SERVER_ADDR'
      value: '<redacted>:636'
    - name: 'MINIO_IDENTITY_LDAP_LOOKUP_BIND_DN'
      value: '<redacted>'
    - name: 'MINIO_IDENTITY_LDAP_LOOKUP_BIND_PASSWORD'
      value: '<redacted>'
    - name: 'MINIO_IDENTITY_LDAP_USER_DN_SEARCH_BASE_DN'
      value: 'ou=people,<redacted>'
    - name: 'MINIO_IDENTITY_LDAP_USER_DN_SEARCH_FILTER'
      value: '(uid=%s)'
    - name: 'MINIO_IDENTITY_LDAP_USER_DN_ATTRIBUTES'
      value: 'cn'
    - name: 'MINIO_IDENTITY_LDAP_GROUP_SEARCH_BASE_DN'
      value: 'ou=groups,<redacted>'
    - name: 'MINIO_IDENTITY_LDAP_GROUP_SEARCH_FILTER'
      value: '(&(objectClass=groupOfNames)(member=%d))'
    - name: 'MINIO_IDENTITY_LDAP_TLS_SKIP_VERIFY'
      value: 'off'
    - name: 'MINIO_IDENTITY_LDAP_SERVER_INSECURE'
      value: 'off'
    - name: 'MINIO_IDENTITY_LDAP_SERVER_STARTTLS'
      value: 'off'
  image:
    repository: 'minio/minio'
    tag: 'RELEASE.2025-05-24T17-08-30Z'
  exposeServices:
    minio: true
    console: true
ingress:
  api:
    enabled: true
    host: '<redacted>'
    tls:
      - hosts:
          - '<redacted>'
        secretName: '<redacted>'
    path: '/'
    pathType: 'Prefix'
  console:
    enabled: true
    host: '<redacted>'
    tls:
      - hosts:
          - '<redacted>'
        secretName: '<redacted>'
    path: '/'
    pathType: 'Prefix'
```

#### Example:

```bash
$ ldapsearch -H ldaps://<redacted>:636 \
  -D "<redacted>" \
  -W \
  -b "ou=people,<redacted>" "(uid=<user>)"
```

* Returns the correct entry, as do group membership queries.

### 3. MinIO's own config confirms LDAP variables are picked up:

```bash
$ mc idp ldap info tenant-gitlab-ci

enable: on
group_search_base_dn: ou=groups,<redacted>  (environment)
group_search_filter: (&(objectClass=groupOfNames)(member=%d))  (environment)
lookup_bind_dn: <redacted>  (environment)
server_addr: <redacted>:636  (environment)
user_dn_attributes: cn  (environment)
user_dn_search_base_dn: ou=people,<redacted>  (environment)
user_dn_search_filter: (uid=%s)  (environment)
```

### 4. Behavior:

* If you set a **wrong bind password**, pod logs show:

  ```
  Error: Unable to load LDAP configuration (LDAP configuration will be disabled!): LDAP Lookup Bind Error: Error connecting as LDAP Lookup Bind user: LDAP Lookup Bind user invalid credentials error: LDAP Result Code 49 "Invalid Credentials"
  ```
* If you set the **correct password**, there is **no error**, pods are healthy, but LDAP authentication from Console never succeeds (404, no error, nothing in logs).

* Upon trying to login from the Console, `tcpdump` shows **no outbound traffic** to our LDAP server, as if MinIO is only attempting local logins. In fact, using the local `MINIO_ROOT_USER` and `MINIO_ROOT_PASSWORD`, authentication works.

### 5. User/group search via ldapsearch is correct:

```bash
ldapsearch -H ldaps://<redacted>:636 \
  -D "<redacted>" \
  -W \
  -b "ou=groups,<redacted>" "(|(cn=<group>))" member | grep <user>
```

Shows expected group membership.

### 6. No relevant logs appear on Console login attempts, not in:

* `kubectl logs` from the minio pods: `$ sudo kubectl -n tenant-gitlab-ci logs -f sts/tenant-gitlab-ci-pool-0 -f`
* `mc admin trace -v tenant-gitlab-ci --debug --all -e`

### 7. Browser Network tab during Console login shows a 404 on the `/api/v1/login` POST.

---

## Context

* We need to enable LDAP authentication for MinIO Console logins using existing LDAP user/group infrastructure.
* The configuration matches documentation and prior working setups, but **no logins succeed** with the latest MinIO Helm deployment.
* LDAP bind and search are confirmed working externally and via logs.
* We believe this is a regression or bug in the Console authentication flow with LDAP.

---

LDAP authentication was previously working on our prior-to-upgrade version: `RELEASE.2023-07-21T20-44-27Z`.

Issue persists across full redeploy, different Helm config, and also with minimal LDAP config.

---

## Your Environment

* **Version used:**

  ```
  minio version RELEASE.2025-05-24T17-08-30Z
  ```
* **Server setup:**

  * Kubernetes (Helm chart: minio/operator 7.1.1, minio/tenant 7.1.1)
  * Custom LDAP, TLS, Console ingress (see above)
  * Ubuntu 22.04
* **Operating System and version:**

  ```
  $ uname -a
  Linux master00 5.15.0-139-generic #149-Ubuntu SMP Fri Apr 11 22:06:13 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
  ```

---

**If you need any more logs or a test environment, please let me know.**

This is blocking our ability to enable LDAP logins for end users.
