### ISSUE TITLE
Hot reloading of certs is not working in official docker container image

### ISSUE THREAD

**Issue by fosple** [minio/minio#21369]
## NOTE
Hot reloading of certs as implemented in [certs.go](https://github.com/harshavardhana/minio/blob/master/pkg/certs/certs.go) does not work as expected.

I have mounted the cert file via `docker compose` `volumes` tag (see the `docker-compose.yml` file I have attached in `## Your Environment` part). I have mounted the cert files as regular files, no symlinks. If I do changes on the docker host (debian), the cert is not reloaded (as it should according to the code in [certs.go](https://github.com/harshavardhana/minio/blob/master/pkg/certs/certs.go) using `fsnotify` via `notify.Watch`).

Even if I go inside the container:
`docker compose exec -it minio sh`
and try to change the file to something new:
`echo "<NEW-VALID-CERT-CONTENT>" > public.crt`

The file does not get reloaded. 

Why is this an issue? It is recommended to reload certs frequently, e.g. via `step-ca`. To avoid downtime restarting the server every time is not an option.

## Expected Behavior
Changed certificates should be hot reloaded automatically.

## Current Behavior
If certs are changed they are not automatically reloaded.

## Possible Solution
- Define a config variable `https-certificates-reload-period` after what time certs are reloaded (see Keycloak https://www.keycloak.org/server/enabletls `https-certificates-reload-period` as example how to implement it)
- Offer command via cli client `mc` to reload certs (similar to e.g. postgres which reloads certs via `postgres pg_ctl reload`)

In my opinion trusting fsnotify to catch filesystem write events is not the best option as this might not work across different environments. A more explicit reload option is way better here, like reloading on a schedule or trigger reloads manually.

## Steps to Reproduce
- Copy `docker-compose.yml` file from below
- In same directory create folder `certs` and files `./certs/minio.key` and `./certs/minio.crt` with valid cert content
- Start docker container `docker compose up minio`
- Change `./certs/minio.crt` content on host
   - Check used cert: `curl -k -v https://localhost:9000`
   - Still old cert is used
- Change `/opt/minio/certs/public.crt` inside container: 
   - `docker compose exec -it minio sh`
   - Inside container: `echo "<NEW-VALID-CERT-CONTENT>" > public.crt`
   - Check used cert: `curl -k -v https://localhost:9000`
   - Still old cert is used

## Your Environment
Official minio docker container from [https://hub.docker.com/r/minio/minio](https://hub.docker.com/r/minio/minio) `minio/minio:latest`

`minio --version`
```
minio version RELEASE.2025-05-24T17-08-30Z (commit-id=ecde75f9112f8410cb6cacb4b76193f1475b587e)
Runtime: go1.24.3 linux/amd64
License: GNU AGPLv3 - https://www.gnu.org/licenses/agpl-3.0.html
Copyright: 2015-2025 MinIO, Inc.
```

`docker-compose.yml`:

```
services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/mnt/data
      - ./certs/minio.key:/opt/minio/certs/private.key
      - ./certs/minio.crt:/opt/minio/certs/public.crt
    environment:
      MINIO_ROOT_USER: <USERNAME>
      MINIO_ROOT_PASSWORD: <PASSWORD>
    command: server /mnt/data --console-address ":9001" --certs-dir /opt/minio/certs
volumes:
  minio_data: {}
```

Docker Host: 
Debian 12 "bookworm"
