### ISSUE TITLE
Does mc admin have a command to take one drive offline manually?

### ISSUE THREAD

**Issue by 0akarma** [minio/minio#21396]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

Some drives are facing error like `input/output error` when deploying the minio server with docker.
Besides, my server reboot and the disk in `/etc/fstab` can not mount on the path.
In this situtaion, how can I do(maybe using mc admin ?) to take the error drives offline and avoid taking the server offline.

## Current Behavior

The deploying `docker-compose` file is as followed.
```
version: '3.7'

# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: minio/minio:RELEASE.2023-06-29T05-12-28Z
  command: server --config-dir /config --address ":9000" --console-address ":9001" "http://bigdata0{1...4}.localhost/minio/disk{1...10}"
  environment:
    MINIO_ROOT_USER: root
    MINIO_ROOT_PASSWORD: root
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3

# starts 4 docker containers running minio server instances.
# using nginx reverse proxy, load balancing, you can access
# it through port 9000.
services:
  minio:
    <<: *minio-common
    network_mode: host
    restart: always
    volumes:
     - ./data/config:/config
     - /minio:/minio


  


```

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):
