### ISSUE TITLE
Minio ignores/overrides Content Type specified at upload

### ISSUE THREAD

**Issue by olalonde** [minio/minio#2798]
## Expected behaviour

If the Content Type is passed when uploading an object, Minio should not attempt to double guess it / ignore it.
## Actual behaviour

I'm setting a custom Content Type when putting an object but subsequent calls to HEAD/GET return a different Content Type.
## Steps to reproduce the behaviour

I'm putting an object (using aws-sdk-js) with the following params:

``` javascript
{ ContentType: 'audio/mp4',
  Bucket: 'filepunk-test',
  Key: 'audio/whistling', }
```

Head returns:

``` javascript
 { AcceptRanges: 'bytes',
  LastModified: 'Wed, 28 Sep 2016 00:46:07 GMT',
  ContentLength: '299850',
  ContentType: 'text/plain; charset=utf-8',
  Metadata: {} }
```

Get returns:

``` javascript
{ AcceptRanges: 'bytes',
  LastModified: 'Wed, 28 Sep 2016 00:46:07 GMT',
  ContentLength: '299850',
  ContentType: 'video/mp4',
  Metadata: {},
```

It's now `video/mp4` instead of `audio/mp4`.

Strangely, if I do the same put _without_ specifying a content type, head/get will now return a content type of `application/octet-stream` instead of `video/mp4`.
## Minio version

`minio/minio` docker image. I'm using docker-compose:

``` yaml
minio:
  image: minio/minio
  ports:
    - "9000:9000"
  volumes:
    - ./test/.minio/data:/export
    - ./test/.minio/config:/root/.minio
  environment:
    - "MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE"
    - "MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
```
## System information

Docker for Mac
