### ISSUE TITLE
server: Running minio server on a node absent in arguments leads to panic

### ISSUE THREAD

**Issue by krisis** [minio/minio#3438]
When Minio is run in a distributed setup, e.g a 4 node setup, if an additional server instance is run on a different node with the same argument as the 4 nodes participating in the distributed setup, the additional server crashes with the following panic.
```
minio5_1  | panic: runtime error: index out of range
minio5_1  | 
minio5_1  | goroutine 72 [running]:
minio5_1  | panic(0xab3b60, 0xc420012090)
minio5_1  | 	/home/kp/code/go1.7.1/go/src/runtime/panic.go:500 +0x1a1
minio5_1  | github.com/minio/minio/vendor/github.com/minio/dsync.lock.func1(0xc42043fb40, 0x1e, 0xc4202eb340, 0x4, 0x4, 0xc420291f80, 0x2, 0xa79000, 0xeeaf60, 0xc420264e40)
minio5_1  | 	/home/kp/code/go1.7.1/workspace/src/github.com/minio/minio/vendor/github.com/minio/dsync/drwmutex.go:171 +0x788
minio5_1  | created by github.com/minio/minio/vendor/github.com/minio/dsync.lock
minio5_1  | 	/home/kp/code/go1.7.1/workspace/src/github.com/minio/minio/vendor/github.com/minio/dsync/drwmutex.go:192 +0xf4
```
## Expected Behavior

The additional server should detect that it is not part of the distributed setup and exit gracefully.

## Current Behavior

We observe a panic.

## Possible Solution

Needs to be discussed.

## Steps to Reproduce (for bugs)

1. Modify the docker-compose.yml as below
2. ``docker-compose -f docker-compose.yml up``

```
version: '2'

# starts 4 docker containers running minio server instances. Each
# minio server's web interface will be accessible on the host at port
# 9001 through 9004.
services:
  minio1:
    image: minio/minio:local-dev
    ports:
      - "9001:9000"
    volumes:
      - "/mnt/export/minio1:/export"
      - "/mnt/export/config-1:/root/.minio"
    environment:
      _MINIO_CACHE: "off"
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export
  minio2:
    image: minio/minio:local-dev
    ports:
      - "9002:9000"
    volumes:
      - "/mnt/export/minio2:/export"
      - "/mnt/export/config-2:/root/.minio"
    environment:
      _MINIO_CACHE: "off"
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export
  minio3:
    image: minio/minio:local-dev
    ports:
      - "9003:9000"
    volumes:
      - "/mnt/export/minio3:/export"
      - "/mnt/export/config-3:/root/.minio"
    environment:
      _MINIO_CACHE: "off"
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export
  minio4:
    image: minio/minio:local-dev
    ports:
      - "9004:9000"
    volumes:
      - "/mnt/export/minio4:/export"
      - "/mnt/export/config-4:/root/.minio"
    environment:
      _MINIO_CACHE: "off"
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export
  minio5:
    image: minio/minio:local-dev
    ports:
      - "9005:9000"
    environment:
      _MINIO_CACHE: "off"
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export
```

## Context

This was identified while reviewing code and was validated by the above steps.

## Your Environment

* Version used: Source commit-id ``8e66510``
* Environment name and version (e.g. nginx 1.9.1): N/A
* Server type and version: N/A
* Operating System and version: Ubuntu Xenial
* Link to your project:
