### ISSUE TITLE
docs: document running Minio distributed cluster using docker swarm

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#3489]
Using Docker 1.12's swarm mode you can create a scalable cluster.

## Expected Behavior
We need to document swarm cluster.

## Current Behavior
We do not have a way to configure swarm networking with Minio distributed setup.

## Possible Solution
https://github.com/itzg/dockerfiles/wiki/Swarm-mode-production-grade-Elasticsearch-cluster

## Context
While we are documenting kubernetes, we need to document docker swarm as well.

**Comment by krishnasrinivas** [comment]
@harshavardhana https://github.com/minio/minio/issues/2825 mentions swarm and mesos in addition to kubernetes.

**Comment by harshavardhana** [comment]
We can avoid meta bugs and open relevant bugs for each.  Work is spread out properly so that others can chime in as well.

**Comment by harshavardhana** [comment]
https://twitter.com/alexellisuk/status/818533286880444416/photo/1 Thanks to @alexellis

**Comment by alexellis** [comment]
Hi, play-with-docker.com will give you a fast, free and disposable test environment for swarm mode.

What were thoughts around elastic search mentioned above?

**Comment by Berndinox** [comment]
I don't won't to be the bad one, but the current solution: https://github.com/minio/minio/pull/3684/commits/dab13356e66cad7cb82429f4e7ae4f8a6885fef3#diff-0561b01489902088c403efe7d90e083a isn't that nice.

Wouldn't it be nicer to make just one service and that one able to replicate. 

May in a similar way to that:

```
  docker network create --driver overlay --subnet 172.20.0.0/24 consul
  docker service create --network=consul --name=consul -e CONSUL_BIND_INTERFACE='eth0' -e 'CONSUL_LOCAL_CONFIG={"leave_on_terminate": true}' --mode global -p 8500:8500 consul agent -server -ui -client=0.0.0.0 -bootstrap-expect 3 -retry-join 172.20.0.3 -retry-join 172.20.0.4 -retry-join 172.20.0.5 -retry-interval 5s

```

Like this:
`docker network create --driver overlay --subnet 172.20.0.0/24 minio`
```

version: '3'

services:
  minio:
    image: minio:latest
    volumes:
      - minio-shared-data:/export
    ports:
      - "9001:9000"
    networks:
      minio:
        aliases:
          - minio
    environment:
      MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
      MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    deploy:
      replicas: 3
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
    command: server http://172.20.0.3/export http://172.20.0.4/export http://172.20.0.5/export http://172.20.0.6/export

volumes:
  minio-shared-data:

networks:
  minio:
    driver: overlay
```

PS: Havn't tried yet

Seems aliases for Service tasks do not work yet, in future it should be possible to use http://minio.1/export

**Comment by nitisht** [comment]
Thanks! This looks interesting, let me try it out.

**Comment by alexellis** [comment]
Can you be any more objective than "not that nice"? What are the pros/cons?

**Comment by Berndinox** [comment]
Sure,

when every tasks is split up into it's own service you will loose the internal load balancing mechanism of swarm. With the approach to start all tasks under one service you got internal load-balancing. As you can see i do not use ip 172.20.0.1 & 2. The Gateway is .1 and the Swarm LB will be .2.
So if you do a "curl http://minio:9000" from within a container connected to that network, you will connect to IP .2

**My final solution:**
1)
Traefik for Letsencrypt Cert and Proxyin:
https://github.com/containous/traefik/issues/1091#issuecomment-278148852
2)
`docker network create --driver overlay --subnet 172.21.0.0/24 minio`
3)
```
version: '3'

services:
  minio:
    image: minio/minio
    volumes:
      - miniodata:/export
    networks:
      minio:
      proxy:
        aliases:
          - minio
    environment:
      - MINIO_ACCESS_KEY=${USER}
      - MINIO_SECRET_KEY=${PASSWORD}
    deploy:
      replicas: 3
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      labels:
        - "traefik.port=80"
        - "traefik.docker.network=proxy"
        - "traefik.frontend.rule=Host:${DOMAIN}"
        - "traefik.backend=minio"
        - "traefik.frontend.entryPoints=http,https"
    command: server http://172.21.0.3/export http://172.21.0.4/export http://172.21.0.5/export

volumes:
  miniodata:
    driver: local-persist
    driver_opts:
      mountpoint: /mnt/glusterfs/docker/minio/export

networks:
  minio:
    external:
      name: minio
  proxy:
    external:
      name: proxy
```
