### ISSUE TITLE
Pushing images to Docker Registry using minio as s3 backend causes registry crash

### ISSUE THREAD

**Issue by ennetech** [minio/minio#3661]
When pushing to remote registry, after uploading one layer the request hungs up ("Retrying in" loop) and the docker registry crashes, this does not happen when using Amazon S3

Registry crash:
```
172.17.0.1 - - [30/Jan/2017:14:21:55 +0000] "PATCH /v2/mybuntu/blobs/uploads/3d1290e8-7e74-4c18-ab7e-41436e4f7a65?_state=GQSm5TAX-kXDvBSLFkihft9vISS5UbQlvGFpS3xVqvl7Ik5hbWUiOiJudWJ1bnR1IiwiVVVJRCI6IjNkMTI5MGU4LTdlNzQtNGMxOC1hYjdlLTQxNDM2ZTRmN2E2NSIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAxNy0wMS0zMFQxNDoyMTo1NS44NTYxNTkxMVoifQ%3D%3D HTTP/1.1" 202 0 "" "docker/1.13.0 go/go1.7.3 git-commit/49bf474 kernel/4.4.0-59-generic os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.0 \\(linux\\))"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4a8122]

goroutine 39 [running]:
panic(0xb96fe0, 0xc420012060)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/docker/distribution/registry/storage/driver/s3-aws.(*driver).copy.func1(0xc42049a180, 0x1, 0xc42030dd80, 0x1066a40, 0xc42049c440, 0xc4202a1320, 0x5b, 0xc420241dc0, 0x69, 0xc42049e0f0, ...)
        /go/src/github.com/docker/distribution/registry/storage/driver/s3-aws/s3.go:742 +0x592
created by github.com/docker/distribution/registry/storage/driver/s3-aws.(*driver).copy
        /go/src/github.com/docker/distribution/registry/storage/driver/s3-aws/s3.go:748 +0x6aa
```

Docker registry config:
```
version: 0.1
log:
    fields:
        service: registry
http:
    addr: :5000
storage:
    cache:
        layerinfo: inmemory
    s3:
        accesskey: [MINIO_KEY]
        secretkey: [MINIO_SECRET]
        region: us-east-1
        regionendpoint: http://minio.mycompany.com:9000/
        bucket: docker-registry
        encrypt: false
        secure: true
        v4auth: true
        chunksize: 5242880
        rootdirectory: /
```

Dockerfile used to build the image:
```
FROM registry:2
COPY config.yml /etc/docker/registry/config.yml
```

Steps to reproduce:
```
docker build . --tag=my-registry
docker run -p 9001:5000 my-registry

docker push localhost:9001/mybuntu
```
Minio version: 2017-01-25T03:14:52Z
Docker version: 1.13.0, build 49bf474
Registry version: v2

any hints?

**Comment by harshavardhana** [comment]
Can you use region endpoint with https ? Looks like redirection is not handled properly by docker registry.

**Comment by ennetech** [comment]
I will configure it and report back

**Comment by harshavardhana** [comment]
> I will configure it and report back

You need to use 'https://' scheme if you are using 'secure: true' or 'http://' if you are using 'secure: false'  - Minio server if configured with TLS will re-direct the request to a TLS connection if the request is made with scheme 'http://' while server is configured with TLS. 

There are other users who have used registry successfully so please let us know how it goes.

**Comment by ennetech** [comment]
updated config:
```
version: 0.1
log:
    fields:
        service: registry
http:
    addr: :5000
storage:
    cache:
        layerinfo: inmemory
    s3:
        accesskey: [MINIO_KEY]
        secretkey: [MINIO_SECRET]
        region: us-east-1
        regionendpoint: https://minio.mycompany.com:9000/
        bucket: docker-registry
        encrypt: false
        secure: true
        v4auth: true
        chunksize: 5242880
        rootdirectory: /
```

updated dockerfile (installs le CA)
```
FROM registry:2
COPY config.yml /etc/docker/registry/config.yml
COPY lets-encrypt-x3-cross-signed.pem /usr/local/share/ca-certificates/le.crt
RUN update-ca-certificates
```

followed config procedure for https on minio:
```
letsencrypt certonly -d minio.mycompany.com --email me@mycompany.com --agree-tos
ln -s /etc/letsencrypt/live/minio.mycompany.com/cert.pem /root/.minio/certs/public.crt
ln -s /etc/letsencrypt/live/minio.mycompany.com/privkey.pem /root/.minio/certs/private.key
```

but the error remains the same, i've also tried disabling certificates on minio and setting 'secure: false' and using the http schema
