### ISSUE TITLE
Performance degradation with distributed minio and an offline cluster.

### ISSUE THREAD

**Issue by efarrer** [minio/minio#4183]
## Expected Behavior
Writes should continue to perform well when a node is offline.

## Current Behavior
There is a noticeable delay with put_object when a node if offline (even though a write quorum exists). 

## Possible Solution
Adding a circuit breaker (https://en.wikipedia.org/wiki/Circuit_breaker_design_pattern) would allow a minio cluster to perform well when a node was know to be down. The initial write(s) would still be slower until the circuit breaker was triggered but thereafter it would perform well. This would enable maintenance on individual nodes without negatively impacting the performance of clients.

## Steps to Reproduce (for bugs)
1. Start a 4 node distributed cluster (I used the docker-compose https://raw.githubusercontent.com/minio/minio/master/docs/orchestration/docker-compose/docker-compose.yaml)
2. Configure a host: mc config host add node1 http://127.0.0.1:9001 minio minio123 S3v4
3. Create a bucket: mc mb node1/test
4. Create a file: dd if=/dev/zero of=./file bs=1024 count=1024
5. Copy that file to the bucket:  time mc cp ./file node1/test/first
6. Note how fast it uploads
7. Stop a node: docker-compose stop minio2
8. Re-copy that file to the bucket:  time mc cp ./file node1/test/second
9. Note it's much slower.
10. Repeating 8-10 always takes a long time.

## Context
I'm evaluating minio for use in a production environment. We'll need to deploy periodic security updates on minio nodes and will not want this to have an adverse effect on performance.

## Your Environment
* Version used (`minio version`):
Version: 2017-04-25T01:27:49Z
Release-Tag: RELEASE.2017-04-25T01-27-49Z
Commit-ID: 710db6bdadb1b228bf6dee7e2a6958000091125b
* Environment name and version (e.g. nginx 1.9.1): N/A
* Server type and version: N/A
* Operating System and version (`uname -a`):
Running in docker on a linux host (see docker-compose file linked above)
Host: Linux xenial 4.4.0-72-generic #93-Ubuntu SMP Fri Mar 31 14:07:41 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
* Link to your project: N/A

**Comment by harshavardhana** [comment]
> Stop a node: docker-compose stop minio2
> Re-copy that file to the bucket: time mc cp ./file node1/test/second
> Note it's much slower.

If a disk is offline no state is remembered as such each on Minio - each POSIX call is retried once on the aforementioned disk which went offline. But there shouldn't be a performance drop.  So for example if you node happen to come back online it would transparently work. 

@efarrer can you tell us how slower? what is the measurement and what is the slowness factor that you see?  do you expect to see nodes going down and coming up all the time in a production env? does starting the node back performance behavior change?

**Comment by efarrer** [comment]
How much slower:
  Before shutting down a node: real    0m 0.07s
  After shutting down a node: real    0m 4.27s
  After restarting the node: real    0m 0.05s

I don't anticipate nodes going down and coming up all the time, but I do anticipate us applying security updates frequently a node at a time. Doing an apt-get update + reboot could take > 2 minutes doing it for all nodes (one at a time) would cause several minutes of degraded behavior.

**Comment by jonandernovella** [comment]
@efarrer @harshavardhana I am experiencing a very similar thing. I have seen a very relevant slowdown with the latest release.

**Comment by harshavardhana** [comment]
> @efarrer @harshavardhana I am experiencing a very similar thing. I have seen a very relevant slowdown with the latest release.

This is not the same as your issue @jonandernovella - your issue needs to be investigated further.

**Comment by harshavardhana** [comment]
> How much slower:
> Before shutting down a node: real 0m 0.07s
> After shutting down a node: real 0m 4.27s
> After restarting the node: real 0m 0.05s

This is consistent because `mc cp` does 4 sets of listing operations and then decides to start copying i.e doing a PutObject operation - each operation is a separate List(). Now on server side each call is retried exactly once so it is consistent that you saw the delay.

For example in my tests
```
time cp ~/Downloads/ubuntu-16.04.1-desktop-amd64.iso container/testbucket
...4.1-desktop-amd64.iso:  1.41 GB / 1.41 GB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00% 80.84 MB/s 17s
real	0m18.340s
user	0m11.800s
sys	0m1.728s
```

```
time cp ~/Downloads/ubuntu-16.04.1-desktop-amd64.iso container/testbucket/newfile
...4.1-desktop-amd64.iso:  1.41 GB / 1.41 GB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00% 91.33 MB/s 15s
real	0m24.619s
user	0m10.220s
sys	0m1.620s
```

Now let me do without doing a compounded call i.e by avoiding all the listing operations - rather use a simple PutObject() operation from minio-go

After all the disks were up
```
time ./putobject
2017/04/26 23:45:01 Uploaded my-objectname  of size:  1513308160 Successfully.

real	0m14.307s
user	0m10.176s
sys	0m1.528s
```

After of the disk was down
```
$ time ./putobject
2017/04/26 23:45:58 Uploaded my-objectname  of size:  1513308160 Successfully.

real	0m14.813s
user	0m10.292s
sys	0m1.252s
```

Also remind you i am testing the latest master which has gotten some optimizations to reduce the overall chattiness of the system. 

Sample code used for putobject
```go
package main

import (
	"log"
	"os"

	"github.com/minio/minio-go"
)

func main() {
	// Note: YOUR-ACCESSKEYID, YOUR-SECRETACCESSKEY, my-testfile, my-bucketname and
	// my-objectname are dummy values, please replace them with original values.

	// Requests are always secure (HTTPS) by default. Set secure=false to enable insecure (HTTP) access.
	// This boolean value is the last argument for New().

	// New returns an Amazon S3 compatible client object. API compatibility (v2 or v4) is automatically
	// determined based on the Endpoint value.
	s3Client, err := minio.New("172.29.0.2:9000", "abcd123", "abcd12345", false)
	if err != nil {
		log.Fatalln(err)
	}

	object, err := os.Open("/home/harsha/Downloads/ubuntu-16.04.1-desktop-amd64.iso")
	if err != nil {
		log.Fatalln(err)
	}
	defer object.Close()

	n, err := s3Client.PutObject("testbucket", "my-objectname", object, "application/octet-stream")
	if err != nil {
		log.Fatalln(err)
	}
	log.Println("Uploaded", "my-objectname", " of size: ", n, "Successfully.")
}
```

So from a client perspective i would say you would see a delay due to a retry but the retry window is small and it should . You might also want to wait for the new release which we will perhaps get it out in another 2 weeks which has improvements to avoid chattiness which could result from node going down.

**Comment by efarrer** [comment]
Thanks for the information.
I tested using the python client calling put_object (instead of mc cp) with the RELEASE.2017-04-25T01-27-49Z release. When a node is down put'ing an object takes about 1 second longer than if all nodes are up. I'll retest with the latest (unreleased) code and post the results.

**Comment by efarrer** [comment]
Retested with DEVELOPMENT.2017-04-27T06-30-39Z and I'm seeing the same behavior of about a one second additional delay when a node is down.

Here's the docker-compose.yaml file
```
`version: '2'

# starts 4 docker containers running minio server instances. Each
# minio server's web interface will be accessible on the host at port
# 9001 through 9004.
services:
  minio1:
    image: minio/minio:edge
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio1/myexport http://minio2/myexport http://minio3/myexport http://minio4/myexport
    working_dir: /myexport
  minio2:
    image: minio/minio:edge
    ports:
      - "9002:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio1/myexport http://minio2/myexport http://minio3/myexport http://minio4/myexport
    working_dir: /myexport
  minio3:
    image: minio/minio:edge
    ports:
      - "9003:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio1/myexport http://minio2/myexport http://minio3/myexport http://minio4/myexport
    working_dir: /myexport
  minio4:
    image: minio/minio:edge
    ports:
      - "9004:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio1/myexport http://minio2/myexport http://minio3/myexport http://minio4/myexport
    working_dir: /myexport`
```
And this is the python client code:
```
`#!/usr/bin/env python
from minio import Minio
from minio.error import (ResponseError)

import random
import string
import io
import time

video_count = 300*1000
bucket_size=1000 # Must be a power of 10
bucket='videos'

def compute_prefix(i):
    if i < bucket_size:
        return "___"
    else:
        return '{:03d}'.format(i % bucket_size)


# Initialize minioClient with an endpoint and access/secret keys.
minioClient = Minio('127.0.0.1:9001',
                    access_key='minio',
                    secret_key='minio123',
                    secure=False)

try:
    minioClient.make_bucket(bucket, location="us-east-1")
except ResponseError as e:
    if e.code == 'BucketAlreadyOwnedByYou':
        pass
    else:
        raise

for i in range(0, video_count):
    video_name = "{}/{}.mpg".format(compute_prefix(i), i)
    video_contents = bytearray.fromhex('{:08x}'.format(i))
    video_file = io.BytesIO(video_contents)

    print "Uploading {}".format(video_name)
    start = time.time()
    minioClient.put_object(bucket, video_name, video_file, len(video_contents), 'application/octet-stream')
    print "Uploaded in {}".format(time.time()-start)
    contents = minioClient.get_object(bucket, video_name)
    assert contents.data == video_contents`
```
I'll try and dig into the code to see exactly why it's slower.
