### ISSUE TITLE
Minio not accepting flags in Kubernetes

### ISSUE THREAD

**Issue by jfusterm** [minio/minio#4724]
When deploying a Minio `StatefulSet` in Kubernetes and using flags under `spec.template.spec.containers.args`, like `--address 0.0.0.0:9000`, the `StatefulSet` never gets deployed properly due to an error `Incorrect Usage: flag provided but not defined: -address 0.0.0.0:9000`

## Expected Behavior
Deploy the Minio cluster via a `StatefulSet` successfully. 

## Current Behavior
Not being able to deploy the Minio cluster.

## Steps to Reproduce (for bugs)
Using this `minio.yaml`

```yaml
apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    app: minio
  namespace: kube-system
spec:
  clusterIP: None
  ports:
    - port: 9000
      name: minio
  selector:
    app: minio
---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: kube-system
spec:
  type: NodePort
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
    nodePort: 32100
  selector:
    app: minio
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: minio
  namespace: kube-system
spec:
  serviceName: minio
  replicas: 4
  template:
    metadata:
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        env:
        - name: MINIO_ACCESS_KEY
          value: "minio"
        - name: MINIO_SECRET_KEY
          value: "minio123"
        image: minio/minio:latest
        args:
        - server
        - --address 0.0.0.0:9000
        - http://minio-0.minio.kube-system.svc.cluster.local/data
        - http://minio-1.minio.kube-system.svc.cluster.local/data
        - http://minio-2.minio.kube-system.svc.cluster.local/data
        - http://minio-3.minio.kube-system.svc.cluster.local/data
        ports:
        - containerPort: 9000
          hostPort: 9000
        volumeMounts:
        - name: data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
        volume.beta.kubernetes.io/storage-class: glusterfs
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
```

1. `kubectl apply -f minio.yaml`
2. `kubectl get pods -l app=minio`
```
NAME      READY     STATUS             RESTARTS   AGE
minio-0   1/1       Running            0          43s
minio-1   1/1       Running            0          35s
minio-2   1/1       Running            0          31s
minio-3   0/1       CrashLoopBackOff   1          20s
```
3. `kubectl logs minio-3`
```bash
Waiting for all hosts to resolve.......All hosts are resolving proceeding to initialize Minio.
Incorrect Usage: flag provided but not defined: -address 0.0.0.0:9000

NAME:
  minio server - Start object storage server.

USAGE:
  minio server [FLAGS] PATH [PATH...]

FLAGS:
  --address value               Bind to a specific ADDRESS:PORT, ADDRESS can be an IP or hostname. (default: ":9000")
  --config-dir value, -C value  Path to configuration directory. (default: "/root/.minio")
  --quiet                       Disable startup information.
  --help, -h                    Show help.
...
```

The same occurs using flags like `--config-dir` or `-C`.

```yaml
        args:
        - server
        - --config-dir /tmp
        - http://minio-0.minio.kube-system.svc.cluster.local/data
        - http://minio-1.minio.kube-system.svc.cluster.local/data
        - http://minio-2.minio.kube-system.svc.cluster.local/data
        - http://minio-3.minio.kube-system.svc.cluster.local/data
```
This results in `Incorrect Usage: flag provided but not defined: -config-dir /tmp`

```yaml
        args:
        - server
        - -C /tmp
        - http://minio-0.minio.kube-system.svc.cluster.local/data
        - http://minio-1.minio.kube-system.svc.cluster.local/data
        - http://minio-2.minio.kube-system.svc.cluster.local/data
        - http://minio-3.minio.kube-system.svc.cluster.local/data
```

This results in `Incorrect Usage: flag provided but not defined: -C /tmp`

Without any flag.

```yaml
        args:
        - server
        - http://minio-0.minio.kube-system.svc.cluster.local/data
        - http://minio-1.minio.kube-system.svc.cluster.local/data
        - http://minio-2.minio.kube-system.svc.cluster.local/data
        - http://minio-3.minio.kube-system.svc.cluster.local/data
```
Using this, everything works ok.

```bash
....All hosts are resolving proceeding to initialize Minio.
Created minio configuration file successfully at /root/.minio

Initializing data volume for the first time.
[01/04] http://minio-0.minio.kube-system.svc.cluster.local:9000/data - 5.0 GiB online
[02/04] http://minio-1.minio.kube-system.svc.cluster.local:9000/data - 5.0 GiB online
[03/04] http://minio-2.minio.kube-system.svc.cluster.local:9000/data - 5.0 GiB online
[04/04] http://minio-3.minio.kube-system.svc.cluster.local:9000/data - 5.0 GiB online
Endpoint:  http://10.2.203.10:9000  http://127.0.0.1:9000
AccessKey: minio
SecretKey: minio123

Browser Access:
   http://10.2.203.10:9000  http://127.0.0.1:9000

Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
   $ mc config host add myminio http://10.2.203.10:9000 minio minio123

Object API (Amazon S3 compatible):
   Go:         https://docs.minio.io/docs/golang-client-quickstart-guide
   Java:       https://docs.minio.io/docs/java-client-quickstart-guide
   Python:     https://docs.minio.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.minio.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.minio.io/docs/dotnet-client-quickstart-guide

Drive Capacity: 9.9 GiB Free, 10 GiB Total
Status:         4 Online, 0 Offline. We can withstand [2] drive failure(s).
```

## Context
I'm just testing Minio and its configuration to deploy a Minio cluster under Kubernetes.

## Your Environment

* Version used (`minio version`): Using `minio/minio:latest`, as of today:
```
Version: 2017-07-24T18:27:35Z
Release-Tag: RELEASE.2017-07-24T18-27-35Z
Commit-ID: 461d60095df56cdb1370f20135429a5a24b400b3
```

* Environment: Kubernetes version `1.7.2` running on VMs, kubedns `1.14.4`,  Docker version `Docker version 1.12.6, build 78d1802` and GlusterFS as storage provisioner.
* Operating System and version (`uname -a`): Debian 9 `Linux worker-2 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2 (2017-06-12) x86_64 GNU/Linux`
