### ISSUE TITLE
Can't start a distributed Minio with TLS

### ISSUE THREAD

**Issue by jfusterm** [minio/minio#4726]
After having deployed properly a distributed Minio under Kubernetes, I have tried to do the same with TLS without any luck, so I don't know if I'm missing something.

## Expected Behavior
Start a distributed Minio with TLS under Kubernetes.

## Current Behavior
Getting error type `TLS handshake failed with new connection...` and `...connection reset by peer`

## Steps to Reproduce (for bugs)

Using this `minio.yaml`

```yaml
apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    app: minio
  namespace: kube-system
spec:
  clusterIP: None
  ports:
    - port: 9000
      name: minio
  selector:
    app: minio
---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: kube-system
spec:
  type: NodePort
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
    nodePort: 32100
  selector:
    app: minio
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: minio
  namespace: kube-system
spec:
  serviceName: minio
  replicas: 4
  template:
    metadata:
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        env:
        - name: MINIO_ACCESS_KEY
          value: "minio"
        - name: MINIO_SECRET_KEY
          value: "minio123"
        image: minio/minio:latest
        args:
        - server
        - https://minio-0.minio.kube-system.svc.cluster.local/data
        - https://minio-1.minio.kube-system.svc.cluster.local/data
        - https://minio-2.minio.kube-system.svc.cluster.local/data
        - https://minio-3.minio.kube-system.svc.cluster.local/data
        ports:
        - containerPort: 9000
          hostPort: 9000
        volumeMounts:
        - name: data
          mountPath: /data
        - name: tls-certificates
          mountPath: /root/.minio/certs/
      volumes:
      - hostPath:
          path: /var/minio/tls
        name: tls-certificates
  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
        volume.beta.kubernetes.io/storage-class: glusterfs
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
```

On each Kubernetes node I have under `/var/minio/tls` the keys `public.crt` and `private.key`. 

```sh
$ openssl x509 -in public.crt -text -noout
...
        Validity
            Not Before: Jul 26 12:30:00 2017 GMT
            Not After : Jul 24 12:30:00 2027 GMT
        Subject: C = US, ST = State, L = Location, O = Organization, CN = minio
...
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Extended Key Usage:
                TLS Web Server Authentication, TLS Web Client Authentication
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Subject Key Identifier:
                80:16:B4:3F:84:16:39:AF:10:1A:38:EC:70:EB:AE:11:71:AC:3B:B1
            X509v3 Authority Key Identifier:
                keyid:35:E6:13:DA:C3:65:49:A0:E8:2C:EF:D5:C8:B0:78:9E:8F:20:A5:9B

            X509v3 Subject Alternative Name:
                DNS:*.minio.kube-system.svc.cluster.local
...
```

The certificate was issued to allow `*.minio.kube-system.svc.cluster.local`. 

1. `kubectl apply -f minio.yaml`
2. `kubectl get pods -l app=minio`

```sh
NAME      READY     STATUS    RESTARTS   AGE
minio-0   1/1       Running   0          16s
minio-1   1/1       Running   0          12s
minio-2   1/1       Running   0          8s
minio-3   1/1       Running   0          4s
```

3. `kubectl logs minio-3`

```sh
Waiting for all hosts to resolve.......All hosts are resolving proceeding to initialize Minio.
Created minio configuration file successfully at /root/.minio
time="2017-07-26T13:13:38Z" level=error msg="TLS handshake failed with new connection 10.2.133.242:33408 at server 10.2.226.114:9000" cause="read tcp 10.2.226.114:9000->10.2.133.242:33408: read: connection reset by peer" source="[listener.go:154:github.com/minio/minio/pkg/http.(*httpListener).start.func2()]"
time="2017-07-26T13:13:38Z" level=error msg="TLS handshake failed with new connection 10.2.133.242:33418 at server 10.2.226.114:9000" cause="read tcp 10.2.226.114:9000->10.2.133.242:33418: read: connection reset by peer" source="[listener.go:154:github.com/minio/minio/pkg/http.(*httpListener).start.func2()]"
time="2017-07-26T13:13:38Z" level=error msg="TLS handshake failed with new connection 10.2.203.50:40430 at server 10.2.226.114:9000" cause="read tcp 10.2.226.114:9000->10.2.203.50:40430: read: connection reset by peer" source="[listener.go:154:github.com/minio/minio/pkg/http.(*httpListener).start.func2()]"
time="2017-07-26T13:13:38Z" level=error msg="TLS handshake failed with new connection 10.2.203.50:40438 at server 10.2.226.114:9000" cause="read tcp 10.2.226.114:9000->10.2.203.50:40438: read: connection reset by peer" source="[listener.go:154:github.com/minio/minio/pkg/http.(*httpListener).start.func2()]"
time="2017-07-26T13:13:39Z" level=error msg="TLS handshake failed with new connection 10.2.38.117:34354 at server 10.2.226.114:9000" cause="read tcp 10.2.226.114:9000->10.2.38.117:34354: read: connection reset by peer" source="[listener.go:154:github.com/minio/minio/pkg/http.(*httpListener).start.func2()]"
time="2017-07-26T13:13:39Z" level=error msg="TLS handshake failed with new connection 10.2.133.242:33422 at server 10.2.226.114:9000" cause="read tcp 10.2.226.114:9000->10.2.133.242:33422: read: connection reset by peer" source="[listener.go:154:github.com/minio/minio/pkg/http.(*httpListener).start.func2()]"
time="2017-07-26T13:13:40Z" level=error msg="TLS handshake failed with new connection 10.2.133.242:33426 at server 10.2.226.114:9000" cause="read tcp 10.2.226.114:9000->10.2.133.242:33426: read: connection reset by peer" source="[listener.go:154:github.com/minio/minio/pkg/http.(*httpListener).start.func2()]"
time="2017-07-26T13:13:40Z" level=error msg="TLS handshake failed with new connection 10.2.203.50:40448 at server 10.2.226.114:9000" cause="read tcp 10.2.226.114:9000->10.2.203.50:40448: read: connection reset by peer" source="[listener.go:154:github.com/minio/minio/pkg/http.(*httpListener).start.func2()]"
time="2017-07-26T13:13:42Z" level=error msg="TLS handshake failed with new connection 10.2.133.242:33432 at server 10.2.226.114:9000" cause="read tcp 10.2.226.114:9000->10.2.133.242:33432: read: connection reset by peer" source="[listener.go:154:github.com/minio/minio/pkg/http.(*httpListener).start.func2()]"
...
```

I've used both `http` and `https` just in case with the same result.

```yaml
        args:
        - server
        - http://minio-0.minio.kube-system.svc.cluster.local/data
        - http://minio-1.minio.kube-system.svc.cluster.local/data
        - http://minio-2.minio.kube-system.svc.cluster.local/data
        - http://minio-3.minio.kube-system.svc.cluster.local/data
```

```yaml
        args:
        - server
        - https://minio-0.minio.kube-system.svc.cluster.local/data
        - https://minio-1.minio.kube-system.svc.cluster.local/data
        - https://minio-2.minio.kube-system.svc.cluster.local/data
        - https://minio-3.minio.kube-system.svc.cluster.local/data
```

## Context
Trying to create a ditributed Minio with TLS under Kubernetes.

With just one Minio instance, the service works perfectly under TLS, but not starting a distributed Minio. 

## Your Environment

* Version used (`minio version`): Using `minio/minio:latest`, as of today:
```
Version: 2017-07-24T18:27:35Z
Release-Tag: RELEASE.2017-07-24T18-27-35Z
Commit-ID: 461d60095df56cdb1370f20135429a5a24b400b3
```

* Environment: Kubernetes version `1.7.2` running on VMs, kubedns `1.14.4`,  Docker version `Docker version 1.12.6, build 78d1802` and GlusterFS as storage provisioner.
* Operating System and version (`uname -a`): Debian 9 `Linux worker-2 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2 (2017-06-12) x86_64 GNU/Linux`
* Certificates: Attached. The `public.crt` has the CA concatenated.
[certs.zip](https://github.com/minio/minio/files/1176675/certs.zip)
