### ISSUE TITLE
Network problem in new version on swarm mode

### ISSUE THREAD

**Issue by grachevko** [minio/minio#4814]
On docker image with tag `RELEASE.2017-06-13T19-01-01Z` all work fine.
But if update to `RELEASE.2017-08-05T00-00-53Z` or `RELEASE.2017-07-24T18-27-35Z` on every nodes result is: 
```
.Failed to lookup minio1
.Failed to lookup minio2
.Failed to lookup minio3
.Failed to lookup minio4
.Failed to lookup minio5
.Failed to lookup minio6
Failed to resolve hosts.. retrying after 1 second.
```

Here is docker stack config:
```
version: '3.3'

services:
    minio1: &minio
        image: minio/minio:RELEASE.2017-06-13T19-01-01Z
        command:
            - minio
            - server
            - http://minio1/export
            - http://minio2/export
            - http://minio3/export
            - http://minio4/export
            - http://minio5/export
            - http://minio6/export
        secrets:
            - source: minio_access_key
              target: access_key
            - source: minio_secret_key
              target: secret_key
        volumes:
            - type: bind
              source: /otrada/1/fp-minio1
              target: /export
        networks:
            - minio
        deploy:
            mode: global
            placement:
                constraints:
                    - node.labels.name == s1

    minio2:
        <<: *minio
        volumes:
            - type: bind
              source: /otrada/2/fp-minio2
              target: /export
        networks:
            minio:
            fp:
                aliases:
                  - minio
        deploy:
            mode: global
            placement:
                constraints:
                    - node.labels.name == s1

    minio3:
        <<: *minio
        volumes:
            - type: bind
              source: /otrada/1/fp-minio3
              target: /export
        deploy:
            mode: global
            placement:
                constraints:
                    - node.labels.name == s2
    minio4:
        <<: *minio
        volumes:
            - type: bind
              source: /otrada/2/fp-minio4
              target: /export
        deploy:
            mode: global
            placement:
                constraints:
                    - node.labels.name == s2
    minio5:
        <<: *minio
        volumes:
            - type: bind
              source: /otrada/1/fp-minio5
              target: /export
        deploy:
            mode: global
            placement:
                constraints:
                    - node.labels.name == s3
    minio6:
        <<: *minio
        volumes:
            - type: bind
              source: /otrada/2/fp-minio6
              target: /export
        deploy:
            mode: global
            placement:
                constraints:
                    - node.labels.name == s3

networks:
    fp:
        external: true
    minio:
        driver: overlay

secrets:
    minio_access_key:
        external: true
    minio_secret_key:
        external: true
```

I guess it must be related to docker swarm, but on `RELEASE.2017-06-13T19-01-01Z` version all is good.

```
$ docker version 
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:23:31 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:19:04 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
