### ISSUE TITLE
How to initialize distributed minio servers in docker-compose?

### ISSUE THREAD

**Issue by hegphegp** [minio/minio#4848]
After I run distributed minio servers in docker-compose, I visit the servers websites by url, then I login the websites, the page alter("Server not initialized, please try again");
## Expected Behavior
Which commands to use to initialize the servers

The docker-compose.yml is
```
version: '2'
services:
  minio1:
    image: minio/minio
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio1/myexport http://minio2/myexport http://minio3/myexport http://minio4/myexport 
  minio2:
    image: minio/minio
    ports:
      - "9002:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio1/myexport http://minio2/myexport http://minio3/myexport http://minio4/myexport 
  minio3:
    image: minio/minio
    ports:
      - "9003:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio1/myexport http://minio2/myexport http://minio3/myexport http://minio4/myexport 
  minio4:
    image: minio/minio
    ports:
      - "9004:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio1/myexport http://minio2/myexport http://minio3/myexport http://minio4/myexport
```
