### ISSUE TITLE
[Dockerfile] Add support to create a bucket on startup

### ISSUE THREAD

**Issue by yagonobre** [minio/minio#4882]
## Expected Behavior
If the user set the env `CREATE_BUCKET`, the docker entrypoint will create a bucket in minio
## Current Behavior
It is not possible
## Possible Solution
Add `mc` to minio server dockerfile

## Context
When I use minio chart as a dependency of another helm charts, I need to create a bucket manually
 
## Your Environment
* Version used (`minio version`): RELEASE.2017-08-05T00-00-53

is a PR welcome?

**Comment by harshavardhana** [comment]
This is not correct @yagonobre you should use external tools such that `mc`.  Minio starts with a clean instance it will confusing for our users on Minio's different modes of operation. 

You can simply orchestrate this yourself and carry this following compose config file. 

```yml
version: "2"
services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    volumes:
      - ./test/.minio/data:/export
      - ./test/.minio/config:/root/.minio
    environment:
      - "MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE"
      - "MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
    command: server /export

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 AKIAIOSFODNN7EXAMPLE wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY;
      /usr/bin/mc rm -r --force myminio/somebucketname;
      /usr/bin/mc mb myminio/somebucketname;
      /usr/bin/mc policy download myminio/somebucketname;
      exit 0;
      "
```
