### ISSUE TITLE
"Waiting for first server to come online" takes forever

### ISSUE THREAD

**Issue by matti** [minio/minio#4897]
## Expected Behavior
servers initialize and boot.

## Current Behavior
Sometimes (?) it seems that when starting 4 servers at the same time, all servers just keep printing

`Initializing data volume for first time. Waiting for first server to come online (elapsed **minutes**)`

## Steps to Reproduce (for bugs)
1. Start servers with fresh data volumes at the same time
2. ???
3. profit

## Your Environment
* Version used (`minio version`): latest
* Environment name and version (e.g. nginx 1.9.1): kontena/coreos/docker
* Operating System and version (`uname -a`): coreos stable

**Comment by matti** [comment]
Fixed this by adding "sleep 5 * instance_number"

**Comment by fwessels** [comment]
@matti What is the environment that you are running the distributed servers in? 

Eg. are they run in containers or are they run on separate servers?

**Comment by matti** [comment]
Containers with kontena.io

**Comment by matti** [comment]
And four servers in the same datacenter

**Comment by harshavardhana** [comment]
> Containers with kontena.io

Do you have a sample configuration or command line on how you deployed?  were your ACCESS_KEY and SECRET_KEY same on all the nodes?

**Comment by matti** [comment]
Using standard minio:latest, here is the (fixed) entrypoint:

```
#!/usr/bin/env sh
set -e

servers=""
for i in `seq 1 $KONTENA_SERVICE_INSTANCES`; do
  servers="$servers http://web-$i:9000/data/$i"
done

case $KONTENA_SERVICE_INSTANCE_NUMBER in
  1) sleep 3 ;;
  2) sleep 6 ;;
  3) sleep 9 ;;
  4) sleep 12 ;;
esac

exec /usr/bin/docker-entrypoint.sh minio server $servers
```

**Comment by matti** [comment]
kontena stack yml looks like this:

```
stack: minio
version: 0.0.1

variables:
  MINIO_ACCESS_KEY:
    type: string
    from:
      - random_string: 16

  MINIO_SECRET_KEY:
    type: string
    from:
      - random_string: 16

services:
  web:
    image: myminio
    stateful: true
    instances: 4
    deploy:
      strategy: ha
      interval: 1d
      min_health: 0.75
    health_check:
      protocol: http
      port: 9000
      uri: /minio/login
      initial_delay: 60
      interval: 10
      timeout: 1
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - KONTENA_SERVICE_INSTANCES=4
      - KONTENA_LB_INTERNAL_PORT=9000
      - KONTENA_LB_VIRTUAL_HOSTS=minio.mydomain.com
    affinity:
      - label!=og-minio=no
    links:
      - ingress-lb/lb
    volumes:
      - data:/data
volumes:
  data:
    external:
      name: ${STACK}-data
```
