### ISSUE TITLE
Minio returns "The specified bucket is not valid"

### ISSUE THREAD

**Issue by ItalyPaleAle** [minio/minio#4948]
Background: I have been using Minio Gateway to Azure to backup my laptop using [Arq 5](https://www.arqbackup.com/).

After working flawlessly for a very long time, suddenly a month ago Minio stopped working. When Arq tries to list files, it gets an error saying "The specified bucket is not valid". This is the URL requested:

`https://minio.lacasetta.xyz/alessandro-mbp-arq/?prefix=3FA96B40-45FA-40D1-B03C-6176D84383AD/packsets/F4D40593-98FA-4ACF-AA22-767FC14B3CCE-trees/&delimiter=/&marker=3FA96B40-45FA-40D1-B03C-6176D84383AD/packsets/F4D40593-98FA-4ACF-AA22-767FC14B3CCE-trees/d9fb3d4ca39de9a43c5c6221d9b3b3d412157b30.pack`

(Note: the DNS name is internal in my LAN only, so it won't work here).

The file is there: using the Minio browser, I can see that in the bucket `alessandro-mbp-arq` the file `3FA96B40-45FA-40D1-B03C-6176D84383AD/packsets/F4D40593-98FA-4ACF-AA22-767FC14B3CCE-trees/d9fb3d4ca39de9a43c5c6221d9b3b3d412157b30.pack` does exist. The file also exists on Azure.

I am not sure why Minio would return this weird error, at this point. The "folder" in which the file is located is fairly large, with 606 files. Also, there are lots of files in the bucket.

I'm running Minio via Docker, using the latest tag (latest release).

Everything on the Azure Account is encrypted (end-to-end), so if you're interested in having the key to try replicating the issue please reach out to me!

## Expected Behavior
Minio should return a valid answer and not an error.

## Current Behavior
Minio responds with "The specified bucket is not valid"

## Steps to Reproduce (for bugs)
I'm running Minio via Docker with the following Compose file:

```
version: '3.1'

services:
  minio-gateway:
    image: minio/minio:latest
    command: 'gateway azure --address :443'
    networks:
      containernet:
        ipv4_address: 10.3.2.2
    restart: always
    ports:
      - '443:443'
    secrets:
      - access_key
      - secret_key
    volumes:
      - /etc/minio:/root/.minio

secrets:
   access_key:
     file: /etc/docker-secrets/minio-gateway/access_key.txt
   secret_key:
     file: /etc/docker-secrets/minio-gateway/secret_key.txt

networks:
  containernet:
    external:
      name: containernet
```

Then use Arq to backup my laptop.

Minio reports this in its logs:

````
time="2017-09-21T01:20:17Z" level=error msg="Unable to list objects." cause="Bucket name invalid: alessandro-mbp-arq" source="[gateway-handlers.go:723:gatewayAPIHandlers.ListObjectsV1Handler()]" stack="gateway-azure.go:266:(*azureObjects).ListObjects gateway-handlers.go:714:(GatewayLayer).ListObjects-fm gateway-handlers.go:721:gatewayAPIHandlers.ListObjectsV1Handler gateway-router.go:107:(gatewayAPIHandlers).ListObjectsV1Handler-fm"
````

Please let me know if you'd like the access keys to the Azure Storage Account.
