### ISSUE TITLE
Mirroring a cluster to a single instance doesn't work

### ISSUE THREAD

**Issue by davidgeorgealex** [minio/minio#4991]
I have a Minio cluster that contains 3 instances, each with 2 disks (so 6 disks in total) and a Minio instance in single mode. I want to be able to mirror the files uploaded in the cluster to the Minio in single mode. For this I run `mc mirror` from one instance from the cluster to the Minio in single mode mode.

## Expected Behavior
The files uploaded in the cluster, from any instance, should be mirrored to the Minio in single mode.

## Current Behavior
Only the files uploaded to the instance that was using in the `mc mirror` command goes to the Minio in single mode.

## Steps to Reproduce (for bugs)
1. Run the docker-compose file uploaded (uploaded in txt, because .yml is not permitted - change the suffix before running) that contains the Minio cluster and Minio in single mode setup
[docker-compose.txt](https://github.com/minio/minio/files/1339833/docker-compose.txt)
2. Check if the instances are accessible from the browser (localhost:9001-9004)
3. Create two buckets in the cluster (bb1 and bb2)
4. docker run --network=<<networkNameUsedByTheInitialInstances>> -it --entrypoint=/bin/sh minio/mc:RELEASE.2017-06-15T03-38-43Z
5. mc config host add source http://minio1:9000 minio minio123
6. mc config host add target http://minioSingle:9000 minio minio123
7. mc mirror -w --force --remove source target
8. Upload a file using http://localhost:9002/minio/bb1/ and one using http://localhost:9001/minio/bb1/
9. You can see that only the file uploaded from the :9001 will be visible (:9001 is the instance that was provided in the mirror command), even if you can see both files in the cluster.

## Context
I want to mirror a minio cluster to a single instance without carrieng from which instance in the cluster the file gets uploaded.

## Your Environment

* Version used (`minio version`): the versions are in the docker-compose file and in the mc run command
* Environment name and version (e.g. nginx 1.9.1): Ubuntu 16.04.2 LTS

**Comment by davidgeorgealex** [comment]
The issue is present with the edge version as well (use for both minio and mc)

**Comment by harshavardhana** [comment]
Just tested a local distributed instance,  mc cp to a different instance seems to be working fine. @davidgeorgealex . Checking through browser uploads.

**Comment by harshavardhana** [comment]
Browser uploads seems to be working as well. NOTE i am running a local instance distributed setup not in docker, will try to replicate docker now.

**Comment by harshavardhana** [comment]
Reproduced it using docker compose, investigating further..

**Comment by harshavardhana** [comment]
@davidgeorgealex sorry for the delay, will send a fix for this - this week.  Thanks for reaching out to me to slack.

**Comment by davidgeorgealex** [comment]
@harshavardhana No problem. Have a great day!

**Comment by harshavardhana** [comment]
@davidgeorgealex so i have a work-around solution for the time being, while we fix this problem on our end. while i traced back the history on this issue, the bug has occurred and pretty much affects some of our releases since April of this year. 

```de204a0a52e6b13fec2d25b73102239891e6de35``` there were some fixes to mitigate this problem, but looks like its not fixed yet.

Work-around is here for you for the time being. 

```yml
version: '2'

services:
  minio1:
    container_name: minio1
    image: minio/minio
    ports:
      - "9001:9000"
    volumes:
    - minio11:/export1
    - minio12:/export2
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server --address "minio1:9000" http://minio1/export1 http://minio1/export2 http://minio2/export1 http://minio2/export2 http://minio3/export1 http://minio3/export2
  minio2:
    container_name: minio2
    image: minio/minio
    ports:
      - "9002:9000"
    volumes:
    - minio21:/export1
    - minio22:/export2
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server --address "minio2:9000" http://minio1/export1 http://minio1/export2 http://minio2/export1 http://minio2/export2 http://minio3/export1 http://minio3/export2
  minio3:
    container_name: minio3
    image: minio/minio
    ports:
      - "9003:9000"
    volumes:
    - minio31:/export1
    - minio32:/export2
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server --address "minio3:9000" http://minio1/export1 http://minio1/export2 http://minio2/export1 http://minio2/export2 http://minio3/export1 http://minio3/export2
  minioSingle:
      container_name: minioSingle
      image: minio/minio
      ports:
        - "9004:9000"
      volumes:
      - minioS:/export
      environment:
        MINIO_ACCESS_KEY: minio
        MINIO_SECRET_KEY: minio123
      command: server /export

volumes:
  minio11:
  minio12:
  minio21:
  minio22:
  minio31:
  minio32:
  minioS:
```
