### ISSUE TITLE
Standalone minio exits after 3 minutes when deployed to docker swarm

### ISSUE THREAD

**Issue by shane151** [minio/minio#5057]
I am deploying a standalone instance of minio on docker swarm, but the minio process exits after 3 minutes.

The container is exposed through a traefik proxy

## Expected Behavior
Minio container starts and keep running

## Current Behavior
The container runs for 3 minutes and then exits with
"Exiting on signal terminated"

## Possible Solution
This behaviour is not seen when running older versions
image: minio/minio:RELEASE.2017-08-05T00-00-53Z
image: minio/minio:RELEASE.2017-07-24T18-27-35Z
image: minio/minio:RELEASE.2017-06-13T19-01-01Z

This problem seems to have been introduced in the last release.

## Steps to Reproduce (for bugs)
docker stack deploy with the following compose file

```yml
version: "3"
services:
  minio:
    # image: minio/minio:latest
    image: minio/minio:RELEASE.2017-09-29T19-16-56Z
    # image: minio/minio:RELEASE.2017-08-05T00-00-53Z
    # image: minio/minio:RELEASE.2017-07-24T18-27-35Z
    # image: minio/minio:RELEASE.2017-06-13T19-01-01Z
    # image: minio/minio:RELEASE.2017-05-05T01-14-51Z
    # image: minio/minio:RELEASE.2017-04-29T00-40-27Z
    # image: minio/minio:RELEASE.2017-03-16T21-50-32Z
    # image: minio/minio:RELEASE.2017-02-16T01-47-30Z
    command: server /export
    networks:
      - proxy
    volumes:
      - ${PWD}/export:/export
    environment:
      MINIO_ACCESS_KEY: XXXXXXXXXXXXXX
      MINIO_SECRET_KEY: YYYYYYYYYYYYYY
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=proxy"
        - "traefik.frontend.rule=Host:s3.mydomain.com"
        - "traefik.port=9000"
networks:
  proxy:
    external: true  
```

## Your Environment
* Version used (`minio version`): docker image minio/minio:RELEASE.2017-09-29T19-16-56Z
* Environment name and version : Ubuntu 16.04 / Docker 17.09.0-ce
* Operating System and version (`uname -a`): Linux 4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
