### ISSUE TITLE
Minio refuses to start with mounted ZFS sub filesystems

### ISSUE THREAD

**Issue by iiroj** [minio/minio#5080]
After `RELEASE.2017-09-29T19-16-56Z` Minio refuses to start in Docker when I mount my ZFS filesystem into `/export`, because my mount-point includes further sub filesystems. This is pretty basic for ZFS, but I haven't found a workaround for Minio.

```
❯ zfs list                        
NAME                    USED  AVAIL  REFER  MOUNTPOINT
data                    145G  2.49T   106G  /mnt/data
data/backups            673M  2.49T   673M  /mnt/data/backups
data/downloads         38.5G  2.49T  38.5G  /mnt/data/downloads
```

```
❯ cat docker-compose.yml
...
minio:
    image: minio/minio:RELEASE.2017-08-05T00-00-53Z
    command: server /export
    restart: unless-stopped
    env_file: /etc/minio.env
    networks:
      - nginx_minio
    volumes:
      - /mnt/data:/export
...
```

## Expected Behavior
Minio starts and has the `downloads` and `backups` buckets.

## Current Behavior
Minio fails to start with:

```
minio_1         | time="2017-10-18T04:42:48Z" level=fatal msg="Invalid command line arguments server=‘:9000’, args=[/export]" cause="Cross-device mounts detected on path (/export) at following locations [/export/downloads /export/backups]. Export path should not have any sub-mounts, refusing to start." source="[server-main.go:96:serverHandleCmdArgs()]" 
```

## Steps to Reproduce (for bugs)

1. Create a zfs filesystem `data` at `/mnt/data`
2. Create further filesystems inside it, `data/test1`, `data/test2`
3. Start minio `RELEASE.2017-09-29T19-16-56Z` in Docker, with volume `/mnt/data:/export`
4. Observe as minio refuses to start

## Context
I have two ZFS filesystems that I mount (actually mounting the containing filesystem) into a Docker container running Minio. This allows me to easily have all the filesystems as buckets.

## Your Environment

* Version used (`minio version`): RELEASE.2017-08-05T00-00-53Z
* Server type and version: Docker version 17.09.0-ce, build afdb6d4
* Operating System and version (`uname -a`): Linux nas 4.10.0-33-generic #37-Ubuntu SMP Fri Aug 11 10:55:28 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
This is on purpose . You cannot move files between buckets and these cause issues for us. Is it possible to avoid ?

**Comment by krishnasrinivas** [comment]
@iiroj previously even though minio would start you would not be able to upload files into backup and download directory. This is because when an object is uploaded we first stage it to a tmp location and then rename it to the actual location. The rename call across different mounts would fail. Hence instead of failing during operation we decided to fail early during boot-up itself.

**Comment by iiroj** [comment]
@krishnasrinivas Thank you for the explanation. If I am doing it wrong, is there some official way of handling this situation, or should I run two Minio instances?

EDIT: That is to say, previously it has been working really well. I have multiple computers backing up to the `backups` bucket, and all downloads going to `downloads`, using minio with the S3 protocol. I haven't had any issues with uploading files.

**Comment by krishnasrinivas** [comment]
> @krishnasrinivas Thank you for the explanation. If I am doing it wrong, is there some official way of handling this situation, or should I run two Minio instances?

yes, you can run two minio instances.

> EDIT: That is to say, previously it has been working really well. I have multiple computers backing up to the backups bucket, and all downloads going to downloads, using minio with the S3 protocol. I haven't had any issues with uploading files.

are you sure? need to check how ZFS behaves for renames across mount points.

**Comment by harshavardhana** [comment]
> are you sure? need to check how ZFS behaves for renames across mount points.

We could perhaps test this feature while starting the server, i.e does the backend FS indeed support cross device links and then allow if its allowed by the backend filesystem @krishnasrinivas

**Comment by krishnasrinivas** [comment]
https://unix.stackexchange.com/questions/276600/how-to-move-files-from-one-zfs-filesystem-to-a-different-zfs-filesystem-in-the-s
https://github.com/zfsonlinux/zfs/issues/2991

these links indicate that rename wont work across different zfs file systems.

**Comment by iiroj** [comment]
Alright, so the previous version seems to work ”by accident” in my use case, since my computers treat the two buckets seperately and data does not move between them.

It seems one solution would be being able to have Docker mounts directly as buckets. For example mounting two different devices as two buckets.

For now I’ll just migrate to two seperate minio instances. Is there an example on how to handle this with a single nginx reverse-proxy? I did find the example `docker-compose.yml` which describes running multiple minio instances.

**Comment by iiroj** [comment]
It seems minio is refusing to start a bit earlier, because `/mnt/data` is its own filesystem as well.

Is there no way around this other than migrating `/mnt/data/backups` and `/mnt/data/downloads` to regular folders instead of filesystems?

**Comment by iiroj** [comment]
Alright, solved this by removing extraneous datasets inside `data`. Set up two minio instances, load-balanced with nginx, while I was at it. It's working now! Thanks.

```
❯ cat docker-compose.yml
...
minio1:
    image: minio/minio:latest
    command: server /data
    restart: unless-stopped
    env_file: /etc/minio.env
    networks:
      - nginx_minio
    volumes:
      - /mnt/data:/data

  minio2:
    image: minio/minio:latest
    command: server /data
    restart: unless-stopped
    env_file: /etc/minio.env
    networks:
      - nginx_minio
    volumes:
      - /mnt/data:/data
```

```
❯ cat nginx.conf
...
upstream Minio {
    server minio1:9000;
    server minio2:9000;
}
```

**Comment by taisph** [comment]
We mount a number of local folders inside the minio container during development to mimic a production environment with proper single filesystem storage. This check now prevents us from doing that.

Ie. docker-compose.yml volumes:
```
    volumes:
      - ./organization/resources/pdfs:/data/templates
      - ./resources/processes/:/data/processes/core/
      - ./organization/resources/processes/:/data/processes/organization/
```

**Comment by harshavardhana** [comment]
> We mount a number of local folders inside the minio container during development to mimic a production environment with proper single filesystem storage. This check now prevents us from doing that.

Yes, it is expected @taisph renames don't work across devices, we do not support this use case.

**Comment by taisph** [comment]
@harshavardhana I understand why you want this in production environments. It makes complete sense. But it kills minio for us in development where we need to test that various services can talk to minio and retrieve files. Would you consider a "i-know-what-im-doing" switch to allow minio to run anyway after throwing a big fat warning?

**Comment by harshavardhana** [comment]
> @harshavardhana I understand why you want this in production environments. It makes complete sense. But it kills minio for us in development where we need to test that various services can talk to minio and retrieve files. Would you consider a "i-know-what-im-doing" switch to allow minio to run anyway after throwing a big fat warning?

We cannot just turn it on and off - here is a more technical explanation. Renames are integral to Minio we leverage the atomicity of renames in our codebase. It provides protection against accidental deletions, namespace corruptions, makes the server more responsive under concurrent environments. It is our design philosophy that we need to provide strict consistency i.e read-after-write. 

If we remove this and add somehow to copy the data to the sub-volumes it would open up Minio server to racy calls and would lack consistency, you and everyone else who deploys in this manner is going to lose data at some point even in the case where you know what you are doing in this situation. That is not acceptable to us as a storage product we have to provide utmost importance to keep your data safe. This is one of that classical reasons why renames across devices are not supported in POSIX calls it is inherently unsafe.

**Comment by krishnasrinivas** [comment]
@taisph just curious, in the "test" environment do you upload files to minio?

**Comment by taisph** [comment]
@krishnasrinivas Not currently.

Just to clarify: We have a number of services that expect to pull certain required files using Minio/S3 when they run in production. In order to make development as frictionless as possible for all team members while keeping close to the production environment, we mount the local folders with the required files as shared folders into the minio docker container, so they only need to restart the specific container they are working with to have it pull the files it needs from the minio container. If we were to drop shared folders, we would need to rebuild the minio container on every file change to copy the changed files in, as well as restart the specific container they are working on.

**Comment by develar** [comment]
So disappointing.

My use case:

1. Scaleway gives your SSD NVME devices, each 50 GB size. Problem is that total amount of data more than 50 GB. So, machine has several 50 GB devices.

2. You define docker volumes like:

```
volumes:
  gh-data-eu:
    driver: local
    driver_opts:
      type: ext4
      device: /dev/vdb
```

Here `/dev/vdb` it is 50 GB device.

3. minio service volumes:

```
volumes:
      - type: volume
        source: gh-data
        target: /data/gh-data/other
        volume:
          nocopy: true
      - type: volume
        source: gh-data-eu
        target: /data/gh-data/eu
        volume:
          nocopy: true
```

I don't use Minio for users — instead, NGINX serves files to user (the same volume configuration, NGINX works well). Minio is used to upload/inspect and so on.

Question is — why forbid and do not support? I understand that `rename` doesn't work across devices, but atomic doesn't make sense in my case (well, I control upload), and in any case you can use target bucket device instead of tmp.
