### ISSUE TITLE
Docker: Create bucket and set global policy

### ISSUE THREAD

**Issue by tillkruss** [minio/minio#5184]
I'm not sure if this is the right place to ask questions, I'm sorry if it isn't.

I would like to _create a bucket_ and _set a global policy_ (for all future uploaded files) when the Minio docker container is build. Is that possible?

This is my Minio setup in my `docker-compose.yml`:

```yaml
minio:
  image: minio/minio
  volumes:
    - minio:/data
  ports:
    - "9001:9000"
  environment:
    - MINIO_ACCESS_KEY=minio
    - MINIO_SECRET_KEY=password
  command: server /data
```
