### ISSUE TITLE
How to configure with nginx ingress controller for kubernetes

### ISSUE THREAD

**Issue by arrowcircle** [minio/minio#5212]
Hi! I am trying to set up minio in kubernetes cluster behind nginx ingress controller and lets encrypt (kube lego)

### mc client lists directories
```
mc ls minio
```
### Web browser connection works
Possible to log in and see buckets/files via https web interface

### mc ls minio
When I try to ls, it says:
```
mc ls minio
mc: <ERROR> Unable to list folder. The access key ID you provided does not exist in our records.
```
But key and secret are from minio startup log.
In this time minio logs looks like:
```
time="2017-11-17T13:36:09Z" level=error msg="{\"method\":\"GET\",\"reqURI\":\"/\",\"header\":{\"Authorization\":[\"AWS4-HMAC-SHA256 Credential=L1JANZ2UTHYU2VI2JDXS/20171117/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=5f070467694013b533960ebdea15686716715c9242babf2054bc3e2ce804a82a\"],\"Connection\":[\"close\"],\"Host\":[\"s3.kubernetes.mydomain.com\"],\"User-Agent\":[\"Minio (linux; amd64) minio-go/4.0.0 mc/2017-10-14T00:51:16Z\"],\"X-Amz-Content-Sha256\":[\"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\"],\"X-Amz-Date\":[\"20171117T133609Z\"],\"X-Forwarded-For\":[\"10.233.65.0\"],\"X-Forwarded-Host\":[\"s3.kubernetes.mydomain.com\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Original-Uri\":[\"/\"],\"X-Real-Ip\":[\"10.233.65.0\"],\"X-Scheme\":[\"https\"]}}" cause="Signature does not match" source="[auth-handler.go:122:checkRequestAuthType()]"
time="2017-11-17T13:36:09Z" level=error msg="{\"method\":\"GET\",\"reqURI\":\"/\",\"header\":{\"Authorization\":[\"AWS4-HMAC-SHA256 Credential=L1JANZ2UTHYU2VI2JDXS/20171117/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=5f070467694013b533960ebdea15686716715c9242babf2054bc3e2ce804a82a\"],\"Connection\":[\"close\"],\"Host\":[\"s3.kubernetes.mydomain.com\"],\"User-Agent\":[\"Minio (linux; amd64) minio-go/4.0.0 mc/2017-10-14T00:51:16Z\"],\"X-Amz-Content-Sha256\":[\"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\"],\"X-Amz-Date\":[\"20171117T133609Z\"],\"X-Forwarded-For\":[\"10.233.65.0\"],\"X-Forwarded-Host\":[\"s3.kubernetes.mydomain.com\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Original-Uri\":[\"/\"],\"X-Real-Ip\":[\"10.233.65.0\"],\"X-Scheme\":[\"https\"]}}" cause="Signature does not match" source="[auth-handler.go:122:checkRequestAuthType()]"
```
### Web browser client
When I open the page and try to connect, it shows
```
The access key ID you provided does not exist in our records
```
Logs for this request:
```
time="2017-11-17T13:37:09Z" level=error msg="Unable to login request from 10.233.64.7:48640" cause="The access key ID you provided does not exist in our records" source="[web-handlers.go:351:(*webAPIHandlers).Login()]"
time="2017-11-17T13:43:55Z" level=error msg="Unable to login request from 10.233.64.7:49472" cause="The access key ID you provided does not exist in our records" source="[web-handlers.go:351:(*webAPIHandlers).Login()]"
```

## Possible Solution
Maybe provide some configuration for nginx ingress controller not to mess with headers.
Here is request to echoheaders service in the same cluster with same settings
```
curl https://echo.kubernetes.mydomain.com


Hostname: echoheaders-68577dffbc-l2np8

Pod Information:
	node name:	node2
	pod name:	echoheaders-68577dffbc-l2np8
	pod namespace:	default
	pod IP:	10.233.65.14

Server values:
	server_version=nginx: 1.13.3 - lua: 10008

Request Information:
	client_address=10.233.66.17
	method=GET
	real path=/
	query=
	request_version=1.1
	request_uri=http://echo.kubernetes.mydomain.com:8080/

Request Headers:
	accept=*/*
	connection=close
	host=echo.kubernetes.mydomain.com
	user-agent=curl/7.54.0
	x-forwarded-for=10.233.64.0
	x-forwarded-host=echo.kubernetes.mydomain.com
	x-forwarded-port=443
	x-forwarded-proto=https
	x-original-uri=/
	x-real-ip=10.233.64.0
	x-scheme=https

Request Body:
	-no body in request-

```

## Steps to Reproduce (for bugs)
1. Apply minio standalone as described here https://github.com/minio/minio/blob/master/docs/orchestration/kubernetes-yaml/ (stop on service)
2. Use this service definition:
```
apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: minio
```
3. Apply nginx-ingress with these configs
```
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-ingress
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: default-http-backend
  labels:
    app: default-http-backend
  namespace: nginx-ingress
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: default-http-backend
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: default-http-backend
        # Any image is permissable as long as:
        # 1. It serves a 404 page at /
        # 2. It serves 200 on a /healthz endpoint
        image: gcr.io/google_containers/defaultbackend:1.4
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 10m
            memory: 20Mi
          requests:
            cpu: 10m
            memory: 20Mi
---

apiVersion: v1
kind: Service
metadata:
  name: default-http-backend
  namespace: nginx-ingress
  labels:
    app: default-http-backend
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: default-http-backend
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-configuration
  namespace: nginx-ingress
  labels:
    app: nginx-ingress
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: tcp-services
  namespace: nginx-ingress
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: udp-services
  namespace: nginx-ingress
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-ingress-serviceaccount
  namespace: nginx-ingress

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: nginx-ingress-clusterrole
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - endpoints
      - nodes
      - pods
      - secrets
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "extensions"
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
        - events
    verbs:
        - create
        - patch
  - apiGroups:
      - "extensions"
    resources:
      - ingresses/status
    verbs:
      - update

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: nginx-ingress-role
  namespace: nginx-ingress
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - pods
      - secrets
      - namespaces
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      # Defaults to "<election-id>-<ingress-class>"
      # Here: "<ingress-controller-leader>-<nginx>"
      # This has to be adapted if you change either parameter
      # when launching the nginx-ingress-controller.
      - "ingress-controller-leader-nginx"
    verbs:
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: nginx-ingress-role-nisa-binding
  namespace: nginx-ingress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nginx-ingress-role
subjects:
  - kind: ServiceAccount
    name: nginx-ingress-serviceaccount
    namespace: nginx-ingress
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: nginx-ingress-clusterrole-nisa-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nginx-ingress-clusterrole
subjects:
  - kind: ServiceAccount
    name: nginx-ingress-serviceaccount
    namespace: nginx-ingress
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-ingress-controller
  namespace: nginx-ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-ingress
  template:
    metadata:
      labels:
        app: nginx-ingress
      annotations:
        prometheus.io/port: '10254'
        prometheus.io/scrape: 'true'
    spec:
      serviceAccountName: nginx-ingress-serviceaccount
      containers:
        - name: nginx-ingress-controller
          image: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.9.0-beta.17
          args:
            - /nginx-ingress-controller
            - --default-backend-service=$(POD_NAMESPACE)/default-http-backend
            - --configmap=$(POD_NAMESPACE)/nginx-configuration
            - --tcp-services-configmap=$(POD_NAMESPACE)/tcp-services
            - --udp-services-configmap=$(POD_NAMESPACE)/udp-services
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
          - name: http
            containerPort: 80
          - name: https
            containerPort: 443
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 10254
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 10254
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  selector:
    app: nginx-ingress

```
4. Apply kube lego
```
apiVersion: v1
kind: Namespace
metadata:
  name: kube-lego
---
apiVersion: v1
metadata:
  name: kube-lego
  namespace: kube-lego
data:
  # modify this to specify your address
  lego.email: "admin@domain.com"
  # configure letsencrypt's production api
  lego.url: "https://acme-v01.api.letsencrypt.org/directory"
  # lego.url: "https://acme-staging.api.letsencrypt.org/directory"
  lego.log_level: debug
kind: ConfigMap
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-lego-serviceaccount
  namespace: kube-lego
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: kube-lego-clusterrole
rules:
  # Allow to do *everything* with ingresses. I can't find any use of ingress/status in the kube-lego
  # source code
  # TODO: this should be trimmed further, I don't see any use of PATCH and UPDATE insofar
  - apiGroups:
    - extensions
    resources:
    - ingresses
    verbs:
    - get
    - update
    - create
    - list
    - patch
    - delete
    - watch
  # allow global access to manage secrets (to write the keys)
  - apiGroups:
    - ""
    resources:
    - secrets
    verbs:
    - get
    - create
    - update
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: kube-lego-role
  namespace: kube-lego
rules:
  - apiGroups:
    - ""
    resources:
    - services
    verbs:
    - create
    - get
    - delete
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: kube-lego-role-binding
  namespace: kube-lego
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kube-lego-role
subjects:
  - kind: ServiceAccount
    name: kube-lego-serviceaccount
    namespace: kube-lego
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kube-lego-clusterrole-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-lego-clusterrole
subjects:
  - kind: ServiceAccount
    name: kube-lego-serviceaccount
    namespace: kube-lego
    apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      name: kube-lego
      namespace: kube-lego
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            app: kube-lego
        spec:
          serviceAccountName: kube-lego-serviceaccount
          containers:
          - name: kube-lego
            image: jetstack/kube-lego:0.1.5
            imagePullPolicy: Always
            ports:
            - containerPort: 8080
            env:
            - name: LEGO_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: kube-lego
                  key: lego.log_level
            - name: LEGO_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: kube-lego
                  key: lego.email
            - name: LEGO_URL
              valueFrom:
                configMapKeyRef:
                  name: kube-lego
                  key: lego.url
            - name: LEGO_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: LEGO_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            readinessProbe:
              httpGet:
                path: /healthz
                port: 8080
              initialDelaySeconds: 5
              timeoutSeconds: 1
```
5. Apply minio ingress without tls
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: minio-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: s3.kubernetes.domain.com
    http:
      paths:
        - path:
          backend:
            serviceName: minio-service
            servicePort: 9000
```
6. Apply ingress with tls
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: minio-ingress
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - s3.kubernetes.domain.com
    secretName: minio-tls
  rules:
  - host: s3.kubernetes.domain.com
    http:
      paths:
        - path:
          backend:
            serviceName: minio-service
            servicePort: 9000

```

## Context
I am trying to set up minio in kubernetes cluster with nginx-ingress-controller and lets-encrypt (kube-lego)

## Your Environment
Kubernetes 1.8.3
