### ISSUE TITLE
invalid memory address or nil pointer dereference when running over GlusterFS mount point

### ISSUE THREAD

**Issue by OsamaJBR** [minio/minio#5564]
I've created a minio cluster on glusterfs before using Docker Swarm and everything was ok.

Now I'm creating a new one and I'm facing this error:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb61713]

goroutine 1 [running]:
github.com/minio/minio/cmd.initFormatFS(0x7ffd3c0c3eab, 0x7, 0xc4204ea720, 0x24, 0x0)
    /q/.q/sources/gopath/src/github.com/minio/minio/cmd/format-fs.go:241 +0x343
github.com/minio/minio/cmd.newFSObjectLayer(0x7ffd3c0c3eab, 0x7, 0xc420256000, 0xc4200001a8, 0xc4200a1858, 0xc4200a18b0)
    /q/.q/sources/gopath/src/github.com/minio/minio/cmd/fs-v1.go:138 +0x2eb
github.com/minio/minio/cmd.newObjectLayer(0xc4201f4f80, 0x1, 0x1, 0x2, 0xc4201f5bd0, 0x0, 0xc4201f78c0)
    /q/.q/sources/gopath/src/github.com/minio/minio/cmd/server-main.go:250 +0x2c7
github.com/minio/minio/cmd.serverMain(0xc4200db760)
    /q/.q/sources/gopath/src/github.com/minio/minio/cmd/server-main.go:222 +0x7b4
github.com/minio/minio/vendor/github.com/minio/cli.HandleAction(0xf4d860, 0x1172360, 0xc4200db760, 0xc420059900, 0x0)
    /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:499 +0x7c
github.com/minio/minio/vendor/github.com/minio/cli.Command.Run(0x112963b, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x11432f4, 0x1c, 0x0, ...)
    /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/command.go:214 +0xa99
github.com/minio/minio/vendor/github.com/minio/cli.(*App).Run(0xc42023cb60, 0xc42000e090, 0x3, 0x3, 0x0, 0x0)
    /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:260 +0x758
github.com/minio/minio/cmd.Main(0xc42000e090, 0x3, 0x3)
    /q/.q/sources/gopath/src/github.com/minio/minio/cmd/main.go:149 +0x8d
main.main()
    /q/.q/sources/gopath/src/github.com/minio/minio/main.go:71 +0x108
```
Docker stack:
```
services:
  server:
    image: minio/minio
    command: server /export
    networks:
      - default
    environment:
      - MINIO_BROWSER=off
      - MINIO_ACCESS_KEY=PZ56IU0PO1UQAQO2VLOX
      - MINIO_SECRET_KEY=qqpxwij3uQRoDChSP3rrBw9bnYpuyx+5JQwkd/D2
    volumes:
      - type: bind
        source: /data/minio-data/
        target: /export
      - type: bind
        source: /data/config/
        target: /root/.minio
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 4
        delay: 5s
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 1024M
```
**where /data is a glusterfs mount point**

**Both /data/config and /data/minio-data are empty.**

Minio Version:
```
VERSION:
  2018-01-18T20:33:21Z
```

Docker Version:
```
# docker --version
Docker version 17.12.0-ce, build c97c6d6
```
GlusterFS version:
```
 # gluster --version
glusterfs 3.12.6
```

Host Info:
```
 # uname -a
Linux node01 4.13.0-32-generic #35~16.04.1-Ubuntu SMP Thu Jan 25 10:13:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
