### ISSUE TITLE
MINIO_REGION is not working

### ISSUE THREAD

**Issue by ArchiFleKs** [minio/minio#5593]
## Expected Behavior

region = "" in config.json should be set to the value of MINIO_REGION

## Current Behavior

region = "" in config.json even if MINIO_REGION is set

## Possible Solution

I had to override manually the config.json

## Steps to Reproduce (for bugs)

start minio with the MINIO_REGION env

## Context

I'm trying to create GCP regional bucket by default and not multi regional US, it is working with the CLI, with mc mb mygcs/test-minio-cstb --region europe-west1 but I want it to be the default behavior.

## Your Environment
* Version used (`minio version`): RELEASE.2018-02-09T22-40-05Z
* Environment name and version (e.g. nginx 1.9.1): Kubernetes 1.9
* Server type and version: GKE
* Operating System and version (`uname -a`): COS

**Comment by poornas** [comment]
@ArchiFleKs, this is intended behavior. The config.json entry for minio server is meant to be modified by user if a default region other than `us-east-1` is required. The MINIO_REGION env variable will override the region specified in the config.json, but is not intended to persist it to config.json. From mc, mb needs to specify --region to server configured region.

**Comment by ArchiFleKs** [comment]
Ok but when I used the ENV var it is not working by default. But when I
override the variable in config.json it is. So maybe there is a difference
between how the two are handle ?

**Comment by ArchiFleKs** [comment]
By working I meant when I set the environment variable MINIO_REGION and
create a bucket without any parameter except bucket name it still default
to US in GCP. But when I set it in config.json directly it creates a
regional bucket in the right region (europe-west1 in my case) that’s the
behavior I was expecting from setting the ENV var.
Le jeu. 1 mars 2018 à 22:18, Kévin Lefevre <lefevre.kevin@gmail.com> a
écrit :

> Ok but when I used the ENV var it is not working by default. But when I
> override the variable in config.json it is. So maybe there is a difference
> between how the two are handle ?

**Comment by poornas** [comment]
@ArchiFleKs , how are you starting the minio server? Do you see any region on the startup banner when you set region in config.json or by setting the env variable

**Comment by ArchiFleKs** [comment]
I'm using a Kubernetes deployment. Juste like the example. I have nothing either way on the startup banner:

```


               *** Warning: Not Ready for Production ***

Endpoint:  http://10.48.5.26:9000  http://127.0.0.1:9000
AccessKey: minio
SecretKey: XXXXXXXX

Browser Access:
   http://10.48.5.26:9000  http://127.0.0.1:9000

Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
   $ mc config host add mygcs http://10.48.5.26:9000 minio XXXXXXXXXXX

Object API (Amazon S3 compatible):
   Go:         https://docs.minio.io/docs/golang-client-quickstart-guide
   Java:       https://docs.minio.io/docs/java-client-quickstart-guide
   Python:     https://docs.minio.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.minio.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.minio.io/docs/dotnet-client-quickstart-guide
```

**Comment by ArchiFleKs** [comment]
My deployment object:

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  # This name uniquely identifies the Deployment
  name: minio
  labels:
    app: minio
spec:
  selector:
    matchLabels:
      app: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        # Label is used as selector in the service.
        app: minio
    spec:
      # Refer to the secret created earlier
      volumes:
      - name: minio-gcs-credentials
        secret:
          # Name of the Secret created earlier
          secretName: minio-gcs-credentials
      - name: minio-config
        configMap:
          name: minio-config
      containers:
      - name: minio
        # Pulls the default Minio image from Docker Hub
        image: minio/minio:RELEASE.2018-02-09T22-40-05Z
        args:
        - gateway
        - gcs
        - $(GCP_PROJECT_ID)
        env:
        # Minio access key and secret key
        - name: MINIO_REGION
          value: "europe-west1"
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-access-key-secret
              key: MINIO_ACCESS_KEY
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio-access-key-secret
              key: MINIO_SECRET_KEY
        # Google Cloud Service uses this variable
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/etc/credentials/credentials.json"
        - name: GCP_PROJECT_ID
          value: "REDACTED"
        ports:
        - containerPort: 9000
          hostPort: 9000
        # Mount the volume into the pod
        volumeMounts:
        - name: minio-gcs-credentials
          mountPath: "/etc/credentials"
          readOnly: true
        - name: minio-config
          mountPath: "/root/.minio/config.json"
          subPath: "config.json"
```
