### ISSUE TITLE
Multipart uploads do not return complete Location url, but only a path

### ISSUE THREAD

**Issue by tusbar** [minio/minio#5687]
## Expected Behavior

I am using aws-sdk for JavaScript to upload some files using `s3.upload()`, which handles multipart, if needed.

Whenever the upload is multipart, the `Location` returned is not a fully qualified URL, but just a path to the file in the bucket.

## Current Behavior
Simple PutObject result:
```js
{ ETag: '"592e87c9e988e73fcba4325a3fd51678"',
  Location: 'http://localhost:9000/bucket/bar',
  key: 'bar',
  Key: 'bar',
  Bucket: 'bucket' }
```

(The lowercase `key` is added by `aws-sdk` with a nice `// will stay undocumented` next to it 🤒)

CompleteMultipart result:
```js
{ Location: '/bucket/bar',
  Bucket: 'bucket',
  Key: 'bar',
  ETag: 'cf5a72c91537bbec5828c3260aeb33ea-37' }
```

## Possible Solution
It happens here: https://github.com/minio/minio/blob/9ede179a21c447f1ba87d5ad62ad3b87f6506eb1/cmd/object-handlers.go#L1305

Maybe something like this should be used instead:
https://github.com/minio/minio/blob/9ede179a21c447f1ba87d5ad62ad3b87f6506eb1/cmd/api-response.go#L285-L300

## Steps to Reproduce (for bugs)
1. Upload using multipart
2. Inspect api response

## Context
I believe those two should return similar responses.

## Your Environment
* Version used (`minio version`):
  Version: 2018-03-19T19:22:06Z
  Release-Tag: RELEASE.2018-03-19T19-22-06Z
  Commit-ID: a4d2e2b4283b228c34ca2fe0aa007d792a726c3a

* Operating System and version (`uname -a`): docker for mac with
```yml
  minio:
    image: minio/minio:RELEASE.2018-03-19T19-22-06Z
    command: server /data
    volumes:
      - minio-data:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: secret
    ports:
      - 9000:9000
```
