### ISSUE TITLE
How to see access error logs within Docker

### ISSUE THREAD

**Issue by mlschuh** [minio/minio#5710]
I'm trying to diagnose a presigned URL problem and it would be great to see the error logs from minio. Reviewing all of the issues here show that the logging is in a state of flux so it's rather confusing to know what I have to do to view them. What is it that I need to do to view the errors?

Running inside docker swarm with the official minio image `minio/minio:RELEASE.2018-03-19T19-22-06Z`

**Comment by nitisht** [comment]
@mlschuh you can use the `MINIO_HTTP_TRACE` environment variable and pass the location where you want to save the log. Later you can retrieve the file from the container from given path.

Here is a sample:

```
sudo docker run -p 9000:9000 \
  -e "MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE" \
  -e "MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY" \
  -e "MINIO_HTTP_TRACE=/tmp/minio.log"
  -v /mnt/data:/data \
  -v /mnt/config:/root/.minio \
  minio/minio:RELEASE.2018-03-19T19-22-06Z server /data
```

Here, the logs will be stored in `/tmp/minio.log`

**Comment by mlschuh** [comment]
That is perfect! Thanks!

**Comment by mlschuh** [comment]
(oopsie, didn't mean to close)

**Comment by nitisht** [comment]
Great! Closing this as answered @mlschuh . Feel free to reach out on slack : https://minio.slack.com for further queries.

**Comment by pburkholder** [comment]
Within `docker-compose.yml` I find this works fine:

```yaml
  storage:
    restart: always
    networks:
      default:
        aliases:
          - bor.minio
    image: minio/minio:latest
    ports:
      - 4554:80
    environment:
      MINIO_DOMAIN: "s3-us-west-1.amazonaws.com"
      MINIO_ACCESS_KEY: ACCESS_KEY_ID
      MINIO_SECRET_KEY: secret123
      MINIO_HTTP_TRACE: /dev/stdout
    command: minio server --address 0.0.0.0:80 /var/data/fakes3
    volumes:
      - storage_data:/var/data/fakes3:delegated
```
