### ISSUE TITLE
Getting 500's when Docker pushing

### ISSUE THREAD

**Issue by ulm0** [minio/minio#5765]
Just moved from filesystem storage and setup a Registry with Minio (latest) as backend and I'm getting 500's errors when pushing.

## Expected Behavior

Be able to push without getting 500 back

## Current Behavior

```sh
$ docker push r.ulm0.xyz/cockroach:v1.1.6-slim
The push refers to repository [r.ulm0.xyz/cockroach]
ad26c81a8728: Pushed 
139438579314: Pushed 
received unexpected HTTP status: 500 Internal Server Error
```

Logs in Registry say `error: unknown blob`, though i'm just migrating images i had in the same registry but with filesystem storage

## Context

Minio is being used as backend storage for docker registry as s3 driver

## Your Environment

* Minio: latest tag for docker image

* Docker running in swarm mode

* Reverse Proxy: Traefik 1.5.4 (for both minio and registry)

* Operating System and version: `Linux NAS-Server 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

* Registry config:

```yaml
version: 0.1
log:
  accesslog:
    disabled: true
  level: debug
  formatter: text
  fields:
    service: registry
    environment: production
  hooks:
    - type: mail
      disabled: true
      levels:
        - panic
      options:
        smtp:
          addr: mail.domain.com:587
          username: no-reply@domain.com
          password: [REDACTED]
          insecure: false
        from: no-reply@domain.com
        to:
          - mail@domain.com
storage:
  s3:
    accesskey: [REDACTED]
    secretkey: [REDACTED]
    region: cl-north-1
    regionendpoint: https://s.ulm0.xyz
    bucket: registry
    encrypt: false
    secure: true
    v4auth: true
    chunksize: 5242880
    rootdirectory: /
  delete:
    enabled: true
  redirect:
    disable: false
  cache:
    blobdescriptor: redis
  maintenance:
    uploadpurging:
      enabled: true
      age: 168h
      interval: 24h
      dryrun: false
    readonly:
      enabled: false
http:
  addr: :5000
  net: tcp
  secret: [REDACTED]
  host: https://r.ulm0.xyz
  headers:
    X-Content-Type-Options: [nosniff]
  http2:
    disabled: false
redis:
  addr: registry_cache:6379
  dialtimeout: 10ms
  readtimeout: 10ms
  writetimeout: 10ms
  pool:
    maxidle: 16
    maxactive: 64
    idletimeout: 300s
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
  tcp:
    - addr: registry_cache:6379
      timeout: 3s
      interval: 10s
      threshold: 3
```

* Minio config:

```json
...
"credential": {
		"accessKey": "[REDACTED]",
		"secretKey": "[REDACTED]"
},
"region": "cl-north-1",
"browser": "on",
"domain": "s.ulm0.xyz",
...
```

**Comment by ulm0** [comment]
as @harshavardhana suggested in #1326 I removed the `domain` directive.

```json
...
"credential": {
		"accessKey": "[REDACTED]",
		"secretKey": "[REDACTED]"
},
"region": "cl-north-1",
"browser": "on",
"domain": "",
...
```

Error still showing up. When 500 error occurs i retry...sometimes it works after several attempts.

**Comment by ulm0** [comment]
Though I was able to push the image (after hitting `docker push ...` for a while), I'm unable to pull the image

```sh
$ docker pull r.ulm0.xyz/cockroach:v1.1.6-slim
Error response from daemon: manifest for r.ulm0.xyz/cockroach:v1.1.6 not found
```

Image appears to be present in the repository

```sh
$ reg -r r.ulm0.xyz ls
Repositories for r.ulm0.xyz
REPO                TAGS
cockroach           v1.1.6-slim

$ reg -r r.ulm0.xyz tags cockroach
v1.1.6-slim
```

![screenshot from 2018-04-04 03-48-11](https://user-images.githubusercontent.com/13160093/38292696-0a7ec822-37bb-11e8-8fae-b425bf9122a3.png)

**Comment by ulm0** [comment]
Traefik settings for the minio service in the `docker-compose.yml`

```yaml
deploy:
      labels:
        - "traefik.backend.loadbalancer.stickiness=true"
        - "traefik.backend.loadbalancer.swarm=true"
        - "traefik.backend=minio"
        - "traefik.docker.network=the-force"
        - "traefik.entrypoints=https"
        - "traefik.frontend.headers.SSLProxyHeaders=X-Forwarded-For:https"
        - "traefik.frontend.headers.STSSeconds=315360000"
        - "traefik.frontend.headers.browserXSSFilter=true"
        - "traefik.frontend.headers.contentTypeNosniff=true"
        - "traefik.frontend.headers.customrequestheaders=X-Forwarded-Ssl:on"
        - "traefik.frontend.passHostHeader=true"
        - "traefik.frontend.passTLSCert=true"
        - "traefik.frontend.rule=Host:s.ulm0.xyz"
        - "traefik.port=9000"
```

**Comment by ulm0** [comment]
Started all over (deleted minio data), but tried a different approach this time, pointing to the minio DNS in the overlay network, both registry and minio are on a shared network named `minio-storage`.

Registry config:

* Service name is also minio_storage, 'cause of compose file service block

```yaml
...
s3:
    accesskey: [REDACTED]
    secretkey: [REDACTED]
    region: cl-north-1
    regionendpoint: http://minio_storage:9000
    secure: false
...
```

Result:

Completely unable to interact with the registry

```sh
$ docker push r.ulm0.xyz/cockroach:v1.1.6-slim
The push refers to repository [r.ulm0.xyz/cockroach]
ad26c81a8728: Retrying in 14 seconds
139438579314: Waiting
```
