### ISSUE TITLE
In 4 disks setup, console message and `mc admin info` always show two disks down in each nodes

### ISSUE THREAD

**Issue by balamurugana** [minio/minio#5871]
In four disks distribute setup, console message and `mc admin info` always show two disks down in each peers.

On node1:
```
$ rm -fr /mnt/sd{d..g}/bala/*; ./minio server http://minio2/mnt/sd{d..e}1/bala/d1 http://minio3/mnt/sd{d..e}1/bala/d1


API: SYSTEM()
Time: 18:27:32 PDT 04/30/2018
Error: disk not found
       endpoint=minio3:9000
       1: cmd/prepare-storage.go:39:cmd.glob..func4.1()
       2: cmd/xl-sets.go:180:cmd.(*xlSets).connectDisks()
       3: cmd/xl-sets.go:260:cmd.newXLSets()
       4: cmd/server-main.go:300:cmd.newObjectLayer()
       5: cmd/server-main.go:263:cmd.serverMain()

API: SYSTEM()
Time: 18:27:32 PDT 04/30/2018
Error: disk not found
       endpoint=minio3:9000
       1: cmd/prepare-storage.go:39:cmd.glob..func4.1()
       2: cmd/xl-sets.go:180:cmd.(*xlSets).connectDisks()
       3: cmd/xl-sets.go:260:cmd.newXLSets()
       4: cmd/server-main.go:300:cmd.newObjectLayer()
       5: cmd/server-main.go:263:cmd.serverMain()
Drive Capacity: 6.0 TiB Free, 7.3 TiB Total
Status:         2 Online, 2 Offline.

Endpoint:  http://192.168.1.92:9000  http://65.19.167.92:9000  http://172.17.0.1:9000  http://192.168.122.1:9000  http://127.0.0.1:9000
AccessKey: minio
SecretKey: minio123
Region:    us-east-1
```

On node2:
```
$ rm -fr /mnt/sd{d..g}/bala/*; ./minio server http://minio2/mnt/sd{d..e}1/bala/d1 http://minio3/mnt/sd{d..e}1/bala/d1


API: SYSTEM()
Time: 18:17:55 PDT 04/30/2018
Error: unformatted disk found
       endpoint=minio3:9000
       1: cmd/prepare-storage.go:39:cmd.glob..func4.1()
       2: cmd/xl-sets.go:180:cmd.(*xlSets).connectDisks()
       3: cmd/xl-sets.go:260:cmd.newXLSets()
       4: cmd/server-main.go:300:cmd.newObjectLayer()
       5: cmd/server-main.go:263:cmd.serverMain()

API: SYSTEM()
Time: 18:17:55 PDT 04/30/2018
Error: unformatted disk found
       endpoint=minio3:9000
       1: cmd/prepare-storage.go:39:cmd.glob..func4.1()
       2: cmd/xl-sets.go:180:cmd.(*xlSets).connectDisks()
       3: cmd/xl-sets.go:260:cmd.newXLSets()
       4: cmd/server-main.go:300:cmd.newObjectLayer()
       5: cmd/server-main.go:263:cmd.serverMain()
Drive Capacity: 6.0 TiB Free, 7.3 TiB Total
Status:         2 Online, 2 Offline.

Endpoint:  http://65.19.167.93:9000  http://192.168.1.93:9000  http://172.17.0.1:9000  http://192.168.122.1:9000  http://192.168.14.1:9000  http://192.168.99.1:9000  http://127.0.0.1:9000
AccessKey: minio
SecretKey: minio123
Region:    us-east-1
```

`mc admin info`:
```
$ mc admin info local/
●  localhost:9000
   Uptime : online since 2 minutes ago
  Version : 2018-05-01T00:58:41Z
   Region : us-east-1
 SQS ARNs : <none>
    Stats : Incoming 27KiB, Outgoing 25KiB
  Storage : Total 7.3TiB, Free 6.0TiB
    Disks : 2, 2


●  minio3:9000
   Uptime : online since 8 seconds ago
  Version : 2018-05-01T00:58:54Z
   Region : us-east-1
 SQS ARNs : <none>
    Stats : Incoming 2.7KiB, Outgoing 876B
  Storage : Total 7.3TiB, Free 6.0TiB
    Disks : 2, 2


```

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
```
Version: 2018-05-01T00:58:54Z
Release-Tag: DEVELOPMENT.2018-05-01T00-58-54Z
Commit-ID: 4f68e0109cf58c1a127de8e1abf4593c4e69b93d
```
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:
*  mc version:
```
Version: 2018-05-01T01:14:17Z
Release-tag: DEVELOPMENT.2018-05-01T01-14-17Z
Commit-id: 1b794a4ae1af46bdeb86fbdb7ba16bbd31366d83
```

**Comment by harshavardhana** [comment]
@balamurugana are you sure you don't have firewall enabled? - or I am not able to understand this... I can successfully run a 4 disk setup just fine.

**Comment by harshavardhana** [comment]
For example 

```yml
version: '2'

# starts 4 docker containers running minio server instances. Each
# minio server's web interface will be accessible on the host at port
# 9001 through 9004.
services:
 minio1:
  image: minio/minio:dev
  volumes:
   - data1:/data1/sdd1
   - data2:/data2/sdd1
  ports:
   - "9001:9000"
  environment:
   MINIO_ACCESS_KEY: minio
   MINIO_SECRET_KEY: minio123
  command: server http://minio1/data1/sdd1 http://minio1/data2/sdd1 http://minio2/data1/sdd1 http://minio2/data2/sdd1
 minio2:
  image: minio/minio:dev
  volumes:
   - data3:/data1/sdd1
   - data4:/data2/sdd1
  ports:
   - "9002:9000"
  environment:
   MINIO_ACCESS_KEY: minio
   MINIO_SECRET_KEY: minio123
  command: server http://minio1/data1/sdd1 http://minio1/data2/sdd1 http://minio2/data1/sdd1 http://minio2/data2/sdd1

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  data1:
  data2:
  data3:
  data4:
```

Runs completely fine. Are you trying to say that we say "offline disks" both in case of actually offline and `unformatted` ?
