### ISSUE TITLE
Question(s): Distributed Minio without erasure code? How to dynamically extend capacity?

### ISSUE THREAD

**Issue by tobias74** [minio/minio#5879]
I would like to run minio simply as a storage solution, which stores objects without any redundancy or fail-safe-mechanics. The disks I use are redundant themselves so I do not think I need an extra level of security here. Suffice it to say my data is not even that important.

How can I run minio without redundant data storage?

My use-case:

I have a single minio-instance (tenant?) that rules over a single disk with 500GB. Now when that disk is filled up I would like to add another minio-instance on it's own hardware with antoher disk which only has 10GB (bear with me on this)

For testing-purposes I tried this scenario (without actually uploading 500GB of data in the first instance) and just added a new minio-instance with said 10GB drive. This did not work at all, I needed 4 instances, so I added another 2 minios with 10GB each. Now what I got was a minio-system with 37GB capacity. What I wanted was a minio-system with 530GB capacity.

Is there any way to achieve this? (The numbers 500GB and 10GB are insane, I know, I just want to clarify my situation)

**Comment by fwessels** [comment]
If you do not want any redundancy or data integrity protection, then you should run Minio in "File System" mode, meaning that you just supply a single file path. (If you supply four or more, then Minio switches to Erasure Code mode, meaning that the objects are going to be striped between the different disks.)

In File System mode, it is really up to the underlying disk file system to provide the storage space, and in case you can grow/repartition the capacity of the underlying disk(s) then this will do it for you.

As an alternative, you can spin up another copy of Minio on a second disk (also FS mode), however this instance will of course have another port number. By design we do not allow disks/file paths to be added "on demand" as this brings a whole plethora of challenges with it which become non-trivial at large scale (think peta scale here). Instead we advocate scaling with simplicity by adding instances over time and choosing the scaling size appropriately (eg. if 500 GB will last you one year, then add another 500 GB in a year's time or so.)

**Comment by deekoder** [comment]
@tobias74  let us know if you want to discuss this further. Please drop into our slack channel at https://slack.minio.com to chat with us. Closing this for now. Please feel free to reactivate if you want to discuss this further here.

**Comment by kawaii** [comment]
Sorry to hijack this issue thread, but seems that your Slack is down (keeps timing out for me) and I have a somewhat similar query. :)

We'd like to run two Minio servers, both in different remote data centres and sync between them in **file system mode** since we simply don't have the resource allocation to give this client erasure code (they have 2TB of images). Is there any way I can do something like this to accomplish this?
```
services:
 minio1:
  image: minio/minio
  volumes:
   - volume1:/export
  ports:
   - "9001:9000"
  environment:
   MINIO_ACCESS_KEY: password
   MINIO_SECRET_KEY: password
  command: server /export http://minio2/export

 minio2:
  image: minio/minio
  volumes:
   - volume2:/export
  ports:
   - "9002:9000"
  environment:
   MINIO_ACCESS_KEY: password
   MINIO_SECRET_KEY: password
  command: server /export http://minio1/export
```
Each time Minio assumes I'm trying to use erasure code mode and says I need 4 endpoints. Simply trying to have a two node master-slave (hot standby, not written to by the application) deployment.

Thanks!
