### ISSUE TITLE
Update disk usage Prometheus metric during runtime

### ISSUE THREAD

**Issue by FUSAKLA** [minio/minio#6072]
## Expected Behavior
I would expect Prometheus metric `minio_disk_storage_used_bytes` to show actual space occupied by the minio instance.

## Current Behavior
The metric contains value loaded on startup but does not update because of use `ConstMetric` which cannot be updated. 
https://github.com/minio/minio/blob/5282639f3c5ea871a1351498d2aa0553760f20fe/cmd/metrics.go#L136

## Possible Solution
It should be probably `NewGauge` or implemented in some way that is shows actual value.

## Steps to Reproduce (for bugs)
1. start minio
2. go to `<host>:<port>/minio/prometheus/metrics` and save the value of a `minio_disk_storage_used_bytes` metric 
3. insert some document
4. repeat step `2` and compare the new value with the old one

## Context
This disallows users to monitor disk space usage of minio 

## Your Environment
Running latest stable release of upstream minio docker image `RELEASE.2018-06-09T03-43-35Z` in kubernetes `1.10.0` with mounted storage folder

**Comment by nitisht** [comment]
@sinhaashish do you mind taking a look

**Comment by sinhaashish** [comment]
@nitisht checking it..

**Comment by FUSAKLA** [comment]
Actually it looks like it's not updating in the web UI also

Here you can see that the bucket contains file with size `3.41 MB` and the bucket used is `Used: 209 bytes`
![screenshot-20180624075049-1294x295](https://user-images.githubusercontent.com/6112562/41816365-56c68514-7783-11e8-9594-dd286ded8aa6.png)

**Comment by harshavardhana** [comment]
Usage gets updated every 12 hrs so if you upload an object you won't usage updated right away.

**Comment by FUSAKLA** [comment]
Ok I didn't know that, my bad sorry

But my minio instances are now running for 2 days, contain around 100MB but the metric and the usage are still the same as on startup

**Comment by harshavardhana** [comment]
> But my minio instances are now running for 2 days, contain around 100MB but the metric and the usage are still the same as on startup

what is your backend filesystem here? @FUSAKLA are you running under erasure coding or single export?

**Comment by FUSAKLA** [comment]
It's running in default configuration with just specified path to `/storage` which is mounted on kubernetes node host
```
/dev/sda2               351.8G     38.8G    313.0G  11% /storage
```
I suppose it`s SSD. (I don't have acess to the node directly)

Sorry I'm new to Minio so I don't know answer if I'm running under `erasure coding or single export` bud if you could direct me how do I find out I'll be happy to answer.

**Comment by harshavardhana** [comment]
@FUSAKLA if you share your kubernetes yaml we can see under in which mode you might be running.

**Comment by FUSAKLA** [comment]
Ok there it is
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: minio
  name: minio
  namespace: monitoring-sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - k8s-w1.fusakla.cz
            weight: 100
          - preference:
              matchExpressions:
              - key: node/dedicated
                operator: In
                values:
                - minio
            weight: 10
      containers:
      - args:
        - server
        - /storage
        env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: access-key
              name: minio
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: secret-key
              name: minio
        image: minio/minio:RELEASE.2018-06-09T03-43-35Z
        imagePullPolicy: Always
        name: minio
        ports:
        - containerPort: 9000
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 500Mi
        volumeMounts:
        - mountPath: /storage
          name: data
      securityContext: {}
      volumes:
      - hostPath:
          path: /var/opt/k8s/mnt/sandbox/minio/data/
          type: ""
        name: data
```
