### ISSUE TITLE
Minio does not detect a secure connection (SSE-C) when running behind a reverse proxy (Traefik)

### ISSUE THREAD

**Issue by ghost** [minio/minio#6093]
Minio does not detect a secure connection (SSE-C) when running behind a reverse proxy (Traefik).

## Expected Behavior

SSE-C ``mc cp --encrypt-key`` should work when a host has ``https://``.

## Current Behavior

SSE-C ``mc cp --encrypt-key`` does not work against the host which has TLS enabled ``https://``.

```
$ mc config host ls myminio
myminio:  https://redacted.com  accesskey  s3cr3tkey  s3v4  auto

$ mc cp --encrypt-key "myminio/test/=32bytelongsecretstring" secret2.txt myminio/test/
mc: <ERROR> Failed to copy `secret2.txt`. Requests specifying Server Side Encryption with Customer provided keys must be made over a secure connection.
mc: <ERROR> Session safely terminated. To resume session `mc session resume GCvWcjCB`
```

## Possible Solution

Minio server should either figure it is running behind a reverse proxy ( ``X-Forwarded-Proto: https`` can help, though, probably not too secure) or should rather have a server flag to amend ``globalIsSSL`` value.

Or maybe simply let SSE-C work whenever the host has ``https://`` ?

## Steps to Reproduce (for bugs)

1.  Complete configuration

- docker-compose.yml:

```
version: '3'

networks:
  oasis: {}

services:
  minio:
    restart: unless-stopped
    image: minio/minio
    networks:
      - oasis
    volumes:
      - /srv/data/minio:/data
    command: server /data
    environment:
      - "MINIO_ACCESS_KEY=redacted"
      - "MINIO_SECRET_KEY=redacted"
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host: redacted.com"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.port=9000"

  traefik:
    restart: unless-stopped
    image: traefik:1.6-alpine
    volumes:
      - /srv/data/traefik/acme:/etc/traefik/acme
      - /srv/data/traefik/traefik.toml:/etc/traefik/traefik.toml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro # listen to the Docker events.
    networks:
      - oasis
    ports:
      - "127.0.0.1:8080:8080"
      - "80:80"
      - "443:443"
```

- /srv/data/traefik/traefik.toml:

```
logLevel = "INFO"
defaultEntryPoints = ["http", "https"]

[api]
  dashboard = true

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
    permanent = true
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
    minVersion = "VersionTLS12"
    cipherSuites = ["TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256", "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384", "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA", "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA"]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "redacted.com"
watch = true
exposedbydefault = false

[acme]
entryPoint = "https"
email = "redacted@redacted.com"
storage = "/etc/traefik/acme/acme.json"
OnHostRule = true
acmeLogging = true
caServer = "https://acme-v02.api.letsencrypt.org/directory"
[acme.httpChallenge]
entryPoint = "http"
```

2. start the traefik and minio services ``docker-compose up -d``
3. ``mc config host add myminio https://redacted.com accesskey s3cr3tkey``
4. ``mc mb myminio/test``
5. ``mc cp --encrypt-key "myminio/test/=32bytelongsecretstring" secret2.txt myminio/test/``

## Your Environment

* Version used (`minio version`): ``2018-06-22T23:48:46Z``
* Environment name and version (e.g. nginx 1.9.1): ``traefik v1.6.4``, ``docker 18.03.1-ce``
* Server type and version: ``CentOS 7``
* Operating System and version (`uname -a`): ``Linux redacted 3.10.0-862.3.3.el7.x86_64 #1 SMP Fri Jun 15 04:15:27 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux``

**Comment by aead** [comment]
@arno01 Thanks for filing this issue.
First of all, both options (`X-Forwarded-Proto` header and `https://` host-prefix) are not reliable indicators for a TLS connection - for your case that may be true, but not in the general case.

AFAICS this is should be solved at traefik's side - See:
 - https://github.com/containous/traefik/issues/3038
 - https://github.com/containous/traefik/issues/364

You can also take a look at `insecureSkipVerify` at https://docs.traefik.io/configuration/commons/
So I recommend to use a minio container containing/generating a public/private key-pair.
In the traefik-config you specify `insecureSkipVerify = true` if you trust your backend network.

**Comment by ghost** [comment]
I have managed to make this working without using the ``insecureSkipVerify = true``.

Here are my steps if someone finds this interesting:

## Generate a self-signed server certificate with self-signed CA

- Create openssl configuration file:

```
cat > openssl.cnf << EOF
[ req ]
distinguished_name = req_distinguished_name
[req_distinguished_name]
[ v3_ca ]
basicConstraints = critical, CA:TRUE
keyUsage = critical, digitalSignature, keyEncipherment, keyCertSign
[ v3_req_server ]
basicConstraints = CA:FALSE
keyUsage = critical, digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth
subjectAltName = @alt_names
[ alt_names ]
IP.1 = 172.19.0.11
EOF
```

> ``172.19.0.11`` - is the IP of a minio container. Since, it seems that Traefik speaks with the backend _only_ by IP.  
> I have been also trying ``DNS.1 = minio``, ``DNS.2 = my.minio.com`` instead of using the ``IP.1``, but it does not seem to be working as apparently Traefik is talking to the backend by IP rather than the hostname.  
> Otherwise, ``insecureSkipVerify = true`` might come handy, but I am not in favor of this global setting.

- Generate self-signed CA bits:

```
openssl ecparam -name prime256v1 -genkey -noout -out ca.key
chmod 0600 ca.key
openssl req -x509 -new -sha256 -nodes -key ca.key -days 3650 -out ca.crt \
            -subj "/CN=my-CA"  -extensions v3_ca -config ./openssl.cnf
```

- Generate self-signed server certificate signed by your CA key:

```
openssl ecparam -name prime256v1 -genkey -noout -out private.key
chmod 0600 private.key
openssl req -new -sha256 -key private.key -subj "/CN=my.minio.com" \
  | openssl x509 -req -sha256 -CA ca.crt -CAkey ca.key -CAcreateserial \
                 -out public.crt -days 365 \
                 -extensions v3_req_server -extfile ./openssl.cnf
```

- Copy self-signed server certificate to Minio container:

``private.key``, ``public.crt`` files should go to ``/root/.minio/certs/`` if you are running Minio under root. I am using ``volumes`` to mount a host path with these certs.

Then, restart Minio docker container.

- Copy self-signed CA certificate to Traefik container:

If you are using Alpine Traefik image, then the correct path is ``/usr/local/share/ca-certificates/``, otherwise one of these https://golang.org/src/crypto/x509/root_linux.go

Once copied, you have to run ``update-ca-certificates`` command which will update ``/etc/ssl/certs/ca-certificates.crt`` file. Only after that, you can start the Traefik.

> I use ``command: sh -c "update-ca-certificates && traefik"`` in my docker-compose and ``volumes`` to pass the ``/usr/local/share/ca-certificates`` (in Traefik docker container) along with the ``ca.crt`` file from the host.

Traefik would need a self-signed CA certificate added only once (until it will change or expire, of course).

The server certificate generation part (``private.key`` and ``public.crt`` bits) can be put in a simple script to start before starting the ``minio server``. This would allow the x509 SAN ``IP.1`` part to get dynamically generated.

I am wondering whether Traefik can be instructed to use a hostname for the backend certificate verification, so we would not have to be explicitly specifying the IP as x509 SAN and could instead rely on the DNS in x509 SAN.

**Upd** on x509 SAN -> it looks like this is not something new :-/

https://github.com/containous/traefik/issues/489#issuecomment-310029305
https://github.com/containous/traefik/issues/2770#issuecomment-374926137

**Upd2** I quickly talked to @dtomcej at the Traefik Slack support channel, basically he also confirmed that _ideal_ way would be to have a script which would generate own cert on startup with the IP in SAN.

With the docker service provider, Traefik is pulling the container IP from the container spec. It does not pull the container hostname since they are either random (so no difference as if we were to update IP in SAN for new x509's) or not random, which means if you have 2 containers with the same URL the routing will blow up. 

If we would still want to stick to DNS in SAN, then we could use a static config - ``[file]`` backend, could be used https://docs.traefik.io/configuration/backends/file/
But this way we would lose healthchecks/loadbalancing (by traefik) and sticky sessions, while the only gain - is easier TLS on the backend.

**Comment by ghost** [comment]
Here is the script I eventually ended up with https://git.nixaid.com/arno/gencert
It allows running Minio server with the TLS, hence SSE-C is enabled.

The drawbacks of this approach:
- [operational] it requires self-signed CA certs shared when running multiple Minio servers;
- [operational] every X years it requires updating the CA certificate in the Traefik's (or any other reverse proxy) container;
- [security] the CA key will have to be spread all over the environment. Theoretically, this could be solved by HashiCorp's Vault, but that won't be nice & small way of running things;

**Comment by harshavardhana** [comment]
> The drawbacks of this approach:
> 
> [operational] it requires self-signed CA certs shared when running multiple Minio servers;
> [operational] every X years it requires updating the CA certificate in the Traefik's (or any other reverse proxy) container;
> [security] the CA key will have to be spread all over the environment. Theoretically, this could be solved by HashiCorp's Vault, but that won't be nice & small way of running things;

This is an incorrect assumption and lets clarify why, while it is a bit tedious to have TLS certs configured it shouldn't be considered as a drawback in a deployment. Securing your storage server should be of utmost importance when encryption is in question. 

Most of these steps can be automated, in-fact just replacing the certs is enough for Minio server to pick it up without even restarting the server to allow for rotating new keys. So at best all you are doing is running a single `openssl` command to rotate certs.

You can even protect the key with a password as well which can be provided to Minio server before startup to decode the key. If you still happen to think this is complex, you can use client-side encryption which would work even over an insecure connection.

**Comment by ghost** [comment]
@harshavardhana I absolutely agree with you and fully understand the importance of securing the storage server.

But, do not we want to cover the use case when one trusts his internal network and does not require all the hassle with TLS, i.e. when one is running a small deployment for personal use, secured by a reverse proxy with TLS termination at.

I believe something like ``allowInsecureSSE = true`` Minio server switch would just cover this kind of use case.

What do you think?

**Comment by aead** [comment]
@arno01 Thank you very much for sharing how you solved the issue :heart: 

> But, do not we want to cover the use case when one trusts his internal network and does not require all the hassle with TLS, i.e. when one is running a small deployment for personal use, secured by a reverse proxy with TLS termination at.

> I believe something like allowInsecureSSE = true Minio server switch would just cover this kind of use case.

> What do you think?

I've some concerns about that proposal.
1. If you have a small deployment (e.g. for personal use) why at all use a reverse-proxy for TLS and than use a (insecure) backend connection to a minio server instead of running a minio server with TLS without reverse-proxy?
2. If you trust your backend and don't want to deal with CA-validity why not generate a cert once and use `insecureSkipVerify`?

> [security] the CA key will have to be spread all over the environment. Theoretically, this could be solved by HashiCorp's Vault, but that won't be nice & small way of running things;

Also esp. that point would be completely dismissed by using an `allowInsecureSSE = true` option.

In general I agree with @harshavardhana here that most of the operational part can be automated.
Also I don't see how `allowInsecureSSE = true` should improve security and also don't think it makes smaller deployments (significantly) simpler.

**Comment by ghost** [comment]
@aead 

well, the good news is that the automation part has already been done and is described in the gencert script [readme](https://git.nixaid.com/arno/gencert#usage-example) I have shared :-)
Though, I am still not very happy that I need to run it each time before Minio server starts (see more below).

I basically thought that ``allowInsecureSSE = true`` feature would be an easy one to implement. But if it is not, then I am giving up.  ¯\_(ツ)_/¯

Nevertheless, I would like to answer to your concerns:

> 1. If you have a small deployment (e.g. for personal use) why at all use a reverse-proxy for TLS and than use a (insecure) backend connection to a minio server instead of running a minio server with TLS without reverse-proxy?

Simple. Some are running more than a single application in their environment and choose to use a single solution to manage their certificates, which happens to be a reverse proxy.
Then, even if not taking the certificates into account at all, [here](https://www.nginx.com/resources/glossary/reverse-proxy-server/) are some common uses of using a reverse proxy server, but I bet you know this anyway ;-)

Just to bring more light on my case, so you can understand my concern better.
Besides Minio, I am running Nextcloud (personal cloud), Ghost/Jekyll (blogging), Flarum (forum), Gitea (personal github), mysql, postgres, and few more containers.
I am using Traefik which offers automated certificate provisioning (i.e. Let's Encrypt). (_maybe later also an automated DNS provisioning, or if one uses Kubernetes ingress as a reverse proxy, i.e. [this](https://github.com/kubernetes-incubator/external-dns) supports that; an yes, I have been using lovely Kubernetes for my personal deployment_).

Traefik is handling all the TLS/(+routing/etc...) hassle on its own and all I need is a simplistic configuration (in my first [comment](https://github.com/minio/minio/issues/6093#issue-336169280) you can see my complete Traefik configuration).

While we could just have ``allowInsecureSSE = true`` in Minio for those who **know** what they are doing, instead we are left with either one of these options:

- **A)** Use Traefik's ``insecureSkipVerify = true`` and (_not_) everyone is happy (see below why _not_);
- **B)** Use a custom script (e.g. [gencert](https://git.nixaid.com/arno/gencert)) which will be running right before Minio server starts;

In my case I went with the option **B.**, but am still not very happy about it since it requires running a [gencert](https://git.nixaid.com/arno/gencert) script each time before running the Minio server. And after some (long) time will require updating the CA certificate (I believe it won't last 10 years long as there will be many changes done in x509 format, the way certs are generated/propagated to the CA bundle, etc..).

If I were absolutely happy with the option **A.**, then I would not even bother creating this issue.

> 2. If you trust your backend and don't want to deal with CA-validity why not generate a cert once and use insecureSkipVerify?

True. Though, many are not happy with ``insecureSkipVerify = true`` since it is a global argument, until [this](https://github.com/containous/traefik/issues/3038) is implemented. But even then, this still leaves us with the necessity of performing an extra step to generate the certs, even it can be just a single _openssl_ command (e.g. ``openssl req -new -sha256 -newkey ec:<(openssl ecparam -name prime256v1) -days 36500 -nodes -x509 -keyout private.key -out public.crt -subj "/C=US"``)

**Upd:** Maybe Minio server could generate a basic x509 self-signed cert on its own (i.e. ``genSelfSignedCert = true`` flag or something like that) so it would automatically offer SSE-C out of a box? And then, having [this proposal](https://github.com/containous/traefik/issues/3038) implemented would make everyone happy :-)

**Upd2:** (just for the record) here is the docker-compose config I ended up with, by using the [gencert](https://git.nixaid.com/arno/gencert) script:

```
version: '3'

networks:
  oasis: {}

services:
  minio:
    restart: unless-stopped
    image: minio/minio
    networks:
      - oasis
    volumes:
      - /srv/data/minio:/data
      - /srv/data/minio/start/gencert.sh:/gencert.sh:ro
    entrypoint: sh -c "cd /root/.minio/certs && /gencert.sh --cn minio.example.com && minio server /data"
    environment:
      - "MINIO_ACCESS_KEY=redacted"
      - "MINIO_SECRET_KEY=redacted"
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host: minio.example.com"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.port=9000"

  traefik:
    restart: unless-stopped
    image: traefik:1.6-alpine
    volumes:
      - /srv/data/traefik/acme:/etc/traefik/acme
      - /srv/data/traefik/traefik.toml:/etc/traefik/traefik.toml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro # listen to the Docker events.
      - /srv/data/traefik/ca-certs:/usr/local/share/ca-certificates:ro
    command: sh -c "update-ca-certificates && traefik"
    networks:
      - oasis
    ports:
      - "127.0.0.1:8080:8080"
      - "80:80"
      - "443:443"
```

**Upd3**:

> Also I don't see how ``allowInsecureSSE = true`` should improve security and also don't think it makes smaller deployments (significantly) simpler.

Well, from the name of this argument it would be clear that it is not meant for improving security ;-)
But you are right about the latter, it would not really make small deployments _significantly_ simpler, especially having the reverse proxy which would not be verifying the x509 certs (e.g. ``insecureSkipVerify = true`` in Traefik).

The whole point of having ``allowInsecureSSE = true`` was that people who **know** what they are doing could benefit from it and skip running (including automating it) ``openssl`` command prior starting Minio server, even if they automated it. Probably I am asking for too much :-)
