### ISSUE TITLE
Unable to write data as Hive table with Spark

### ISSUE THREAD

**Issue by NicolasDutronc** [minio/minio#6191]
Hi there ! I'm trying to setup the Hive metastore with Minio as a storage backend in order to be able to write Spark Dataframes to Minio as Hive tables. I'm using ```data.write.saveAsTable("tableName")```.

## Expected Behavior
It should reach the metastore to write metadata and write the Dataframe to Minio.

## Current Behavior

* With `aws-java-sdk 1.10.6` (included in hadoop 2.8.3): ```
org.apache.hadoop.fs.s3a.AWSClientIOException: innerMkdirs on s3a://hive/hive-warehouse/cards/_temporary/0: com.amazonaws.AmazonClientException: Unable to verify integrity of data upload. Client calculated content hash (contentMD5: 1B2M2Y8AsgTpgAmY7PhCfg== in base 64) didn't match hash (etag: null in hex) calculated by Amazon S3. You may need to delete the data stored in Amazon S3. (metadata.contentMD5: null, md5DigestStream: com.amazonaws.services.s3.internal.MD5DigestCalculatingInputStream@4b99fa92, bucketName: hive, key: hive-warehouse/cards/_temporary/0/): Unable to verify integrity of data upload. Client calculated content hash (contentMD5: 1B2M2Y8AsgTpgAmY7PhCfg== in base 64) didn't match hash (etag: null in hex) calculated by Amazon S3. You may need to delete the data stored in Amazon S3. (metadata.contentMD5: null, md5DigestStream: com.amazonaws.services.s3.internal.MD5DigestCalculatingInputStream@4b99fa92, bucketName: hive, key: hive-warehouse/cards/_temporary/0/)```
* With `aws-java-sdk 1.11.234` (as suggested in the [cookbook](https://github.com/minio/cookbook/blob/master/docs/apache-spark-with-minio.md): ```java.lang.NoClassDefFoundError: Could not initialize class org.xerial.snappy.Snappy```

## Your Environment

* minio/minio:RELEASE.2018-07-13T00-09-07Z
* spark-2.2.1-bin-without-hadoop
* Hadoop 2.8.3
* Hive 2.3.3

**Comment by nitisht** [comment]
> With aws-java-sdk 1.11.234 (as suggested in the cookbook: java.lang.NoClassDefFoundError: Could not initialize class org.xerial.snappy.Snappy

Have you seen this solution @NicolasDutronc https://stackoverflow.com/questions/45050937/error-could-not-initialize-class-org-xerial-snappy-snappy

**Comment by NicolasDutronc** [comment]
I tried several things and I almost got it to work. I added manually the snappy jar into my spark/jars folder.
Now when I execute `saveAsTable`, the data is correctly saved in Minio (there is `_SUCCESS` file beside the data). However the table is not registered in the metastore and I received this exception:
```
org.apache.spark.sql.AnalysisException: org.apache.hadoop.hive.ql.metadata.HiveException: MetaException(message:Got exception: java.nio.file.AccessDeniedException s3a://hive/warehouse/cards: getFileStatus on s3a://hive/warehouse/cards: com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: null), S3 Extended Request ID: null);
```

I guess the error is due to the fact that `s3a://hive/warehouse/cards` is not a file but a directory but I am not sure...

Any idea ?

**Comment by nitisht** [comment]
> I guess the error is due to the fact that s3a://hive/warehouse/cards is not a file but a directory but I am not sure...

This may be the case, how are you running Minio server? I mean is it erasure code? Also, if you can provide detailed steps I can try to reproduce the situation

**Comment by NicolasDutronc** [comment]
I'm running minio as a docker container with docker-compose:
```
version: "3"
services:

  minio:
    image: minio/minio:RELEASE.2018-07-13T00-09-07Z
    container_name: minio
    ports:
      - "9000:9000"
    command: minio server /data
    environment:
      MINIO_ACCESS_KEY: localKey
      MINIO_SECRET_KEY: localSecret
    volumes:
      - "./minioData:/data"

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: metastore
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
```

I started a local spark standalone cluster with 1 master and 1 worker, the hive metastore service and zeppelin which I use to write spark code. I added the spark dependencies as it is specified in the cookbook as well as the [spark-hive](https://mvnrepository.com/artifact/org.apache.spark/spark-hive_2.11/2.2.1) dependency. Note that I also excluded `com.fasterxml.jackson.core` and `com.amazonaws` from the `hadoop-aws` dependency and `org.apache.hadoop` from the `spark-hive` dependency.
I can confirm Spark can speak to the metastore by listing the databases.

Here is the `hive-site.xml` conf file that you have to copy into your `$SPARK_HOME/conf` directory as well as in your `$HIVE_HOME/conf` directory:
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet type="text/xsl" href="configuration.xsl"?>

<configuration>

    <property>
        <name>javax.jdo.option.ConnectionURL</name>
        <value>jdbc:postgresql://127.0.0.1/metastore</value>
    </property>

    <property>
        <name>javax.jdo.option.ConnectionDriverName</name>
        <value>org.postgresql.Driver</value>
    </property>

    <property>
        <name>javax.jdo.option.ConnectionUserName</name>
        <value>user</value>
    </property>

    <property>
        <name>javax.jdo.option.ConnectionPassword</name>
        <value>password</value>
    </property>

    <property>
        <name>datanucleus.autoCreateSchema</name>
        <value>false</value>
    </property>

    <property>
        <name>hive.metastore.uris</name>
        <value>thrift://127.0.0.1:9083</value>
        <description>IP address (or fully-qualified domain name) and port of the metastore host</description>
    </property>

    <property>
        <name>hive.metastore.schema.verification</name>
        <value>true</value>
    </property>

    <property>
        <name>hive.metastore.warehouse.dir</name>
        <value>s3a://hive/warehouse</value>
    </property>

</configuration>
```

And here is the `spark-defaults.conf` file:
```
spark.sql.hive.metastore.jars maven
spark.sql.hive.metastore.version 1.2.1
```

Start the Minio server and the database:
* ```docker-compose up -d```.

Start the local standalone Spark cluster:
* ```$SPARK_HOME/sbin/start-master.sh```;
* ```$SPARK_HOME/sbin/start-slave.sh spark://<master-addess>:7077``` (check the UI at `localhost:8080` to retrieve the master's address and to see if everything goes well).

Start the Hive Metastore:
* Init the database: ```$HIVE_HOME/bin/schematool -dbType postgres -initSchema``` (if you have a database client, you can see that there are a lot of tables that were created);
* start the metastore: ```$HIVE_HOME/bin/hive --service metastore```.

Create a DataFrame and try to save it as a table: ```df.write.saveAsTable```.

Tell me if there is anything unclear.

**Comment by nitisht** [comment]
Can you try erasure code setup and try once: https://docs.minio.io/docs/deploy-minio-on-docker-compose if it still doesn't work, we'll need to try it out locally to figure out the problem

**Comment by NicolasDutronc** [comment]
I tried with this:
```
version: "3"
services:

  minio1:
    image: minio/minio:RELEASE.2018-07-13T00-09-07Z
    container_name: minio1
    ports:
      - "9001:9000"
    command: server http://minio1/data http://minio2/data http://minio3/data http://minio4/data
    environment:
      MINIO_ACCESS_KEY: localKey
      MINIO_SECRET_KEY: localSecret
    volumes:
      - "./minioData1:/data"
  minio2:
    image: minio/minio:RELEASE.2018-07-13T00-09-07Z
    container_name: minio2
    ports:
      - "9002:9000"
    command: server http://minio1/data http://minio2/data http://minio3/data http://minio4/data
    environment:
      MINIO_ACCESS_KEY: localKey
      MINIO_SECRET_KEY: localSecret
    volumes:
      - "./minioData2:/data"
  minio3:
    image: minio/minio:RELEASE.2018-07-13T00-09-07Z
    container_name: minio3
    ports:
      - "9003:9000"
    command: server http://minio1/data http://minio2/data http://minio3/data http://minio4/data
    environment:
      MINIO_ACCESS_KEY: localKey
      MINIO_SECRET_KEY: localSecret
    volumes:
      - "./minioData3:/data"

  minio4:
    image: minio/minio:RELEASE.2018-07-13T00-09-07Z
    container_name: minio4
    ports:
      - "9004:9000"
    command: server http://minio1/data http://minio2/data http://minio3/data http://minio4/data
    environment:
      MINIO_ACCESS_KEY: localKey
      MINIO_SECRET_KEY: localSecret
    volumes:
      - "./minioData4:/data"

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: metastore
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
```

I get the same results.
