### ISSUE TITLE
How can I make minio more verbose?

### ISSUE THREAD

**Issue by groundnuty** [minio/minio#6212]
I'm running the newest version of minio on kubernetes. I would like to get a bit more logs then:
~~~
> kubectl logs -f metadata-volume-s3-krakow-7df45494d6-5f4nq
Created minio configuration file successfully at /root/.minio

Endpoint:  http://10.32.5.57:9000  http://127.0.0.1:9000
AccessKey: xxx
SecretKey: xxx

Browser Access:
   http://10.32.5.57:9000  http://127.0.0.1:9000

Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
   $ mc config host add myminio http://10.32.5.57:9000 accessKey verySecretKey

Object API (Amazon S3 compatible):
   Go:         https://docs.minio.io/docs/golang-client-quickstart-guide
   Java:       https://docs.minio.io/docs/java-client-quickstart-guide
   Python:     https://docs.minio.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.minio.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.minio.io/docs/dotnet-client-quickstart-guide
~~~

I failed to find any information on this in the official documentation. Can I somehow make minio to put more verbosity on the stdout? or at least some other log file?

**Comment by nitisht** [comment]
@groundnuty Minio only logs serious issues on the console, this is by design. However you can log all the HTTP requests by using the `MINIO_HTTP_TRACE` environment variable. Set `MINIO_HTTP_TRACE` to a file path and Minio will write trace information to that file.

**Comment by groundnuty** [comment]
Thank you for your help. I solved my problem (maybe someone will find it useful):

Kubernetes (helm) snippet:
```
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image }}
        imagePullPolicy: {{ template "imagePullPolicy" dict "root" . }}
        env:
          - name: MINIO_ACCESS_KEY
            value: {{ .Values.key_id }}
          - name: MINIO_SECRET_KEY
            value: {{ .Values.access_key }}
        {{- if .Values.log_file }}
          - name: MINIO_HTTP_TRACE
            value: {{ .Values.log_file }}
        {{- end }}
        command:
          - "/bin/sh"
          - "-c"
          - >
            tail -F /minio.log &
            minio server /data ;
        ports:
          - containerPort: {{ .Values.port }}
        readinessProbe:
          tcpSocket:
            port: {{ .Values.port }}
        livenessProbe:
          exec:
            command:
              - "/usr/bin/healthcheck.sh"
```

Anyway, I think that it would be a bit nicer if the main binary/entrypoint was able to send logs to stdout instead of employing such small hacks.
