### ISSUE TITLE
Minio 500 internal error on startup

### ISSUE THREAD

**Issue by Ex-Ark** [minio/minio#6213]
Using latest release minio no longer run on startup (500 internal error)

## Expected Behavior
`docker-compose up minio` should succeed

## Current Behavior
Error: Unexpected error, please report this issue at https://github.com/minio/minio/issues
minio_1                       |        1: cmd/fs-v1-helpers.go:337:cmd.fsCreateFile()
minio_1                       |        2: cmd/fs-v1.go:870:cmd.(*FSObjects).putObject()
minio_1                       |        3: cmd/fs-v1.go:780:cmd.(*FSObjects).PutObject()
minio_1                       |        4: cmd/notification.go:538:cmd.saveConfig()
minio_1                       |        5: cmd/policy.go:216:cmd.savePolicyConfig()
minio_1                       |        6: cmd/fs-v1.go:1230:cmd.(*FSObjects).SetBucketPolicy()
minio_1                       |        7: cmd/bucket-policy-handlers.go:88:cmd.objectAPIHandlers.PutBucketPolicyHandler()
minio_1                       |        8: cmd/api-router.go:103:cmd.(objectAPIHandlers).PutBucketPolicyHandler-fm()
minio_1                       |        9: net/http/server.go:1947:http.HandlerFunc.ServeHTTP()

## Possible Solution
Using previous release fixed it for me
`minio/minio:RELEASE.2018-07-23T18-34-49Z`

## Steps to Reproduce (for bugs)
1. docker-compose pull minio
2. docker-compose up --build minio_init

## Your Environment
docker-compose.yml
```
--- file server ---#
  minio:
    image: minio/minio
    ports:
      - 9000:9000
    command: server /data
    environment: &MINIO_CREDENTIALS
      MINIO_ACCESS_KEY: access
      MINIO_SECRET_KEY: secret

  #--- init the upload bucket ---#
  minio_init:
    depends_on:
      - minio
    image: minio/mc
    entrypoint: sh
    command:
      - -c
      - |
          while ! nc -z minio 9000; do echo 'Waiting for minio to be ready...' && sleep 0.1; done
          sleep 5
          mc config host add dogs http://minio:9000 access secret
          mc mb dogs/woof
          mc policy download dogs/woof
```
* Version used (`latest`):
* Environment name and version (Ubuntu):
* Operating System and version (`Linux vidar 3.16.0-5-amd64 #1 SMP Debian 3.16.51-3+deb8u1 (2018-01-08) x86_64 GNU/Linux`):

**Comment by kannappanr** [comment]
@Ex-Ark Thanks for filing this issue. We will try to reproduce this issue and get back to you.

**Comment by kannappanr** [comment]
@Ex-Ark I tried to reproduce this issue and was unable to do so.

I got the following error

```
$docker-compose up  --build minio_init
ERROR: The Compose file './docker-compose.yaml' is invalid because:
Unsupported config option for minio_init: 'depends_on'
```

Is it possible that you are running an older version of `docker-compose`

I removed the `mc` part of it and did all the commands in the `yaml` file and it worked.

**Comment by kannappanr** [comment]
I changed the `yaml` file a little bit

```
﻿minio:
    image: minio/minio
    ports:
        - '9000:9000'
    command: 'server /data'
    environment:
        MINIO_ACCESS_KEY: minio
        MINIO_SECRET_KEY: minio123
minio_init:
    links:
        - minio
    image: minio/mc
    entrypoint: sh
    command:
        - '-c'
        - "while ! nc -z minio 9000; do echo 'Waiting for minio to be ready...' && sleep 0.1; done\nsleep 5\nmc config host add dogs http://minio:9000 minio minio123\nmc mb dogs/woof\nmc policy download dogs/woof\n"
```

The version of `minio` running is `2018-07-31T02:11:47Z` which is the latest.

Here is my output
```
$ docker-compose up

Starting docker1_minio_1
Starting docker1_minio_init_1
Attaching to docker1_minio_1, docker1_minio_init_1
minio_1       | 
minio_1       | Endpoint:  http://172.17.0.2:9000  http://127.0.0.1:9000
minio_1       | AccessKey: minio 
minio_1       | SecretKey: minio123 
minio_1       | 
minio_1       | Browser Access:
minio_1       |    http://172.17.0.2:9000  http://127.0.0.1:9000
minio_1       | 
minio_1       | Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
minio_1       |    $ mc config host add myminio http://172.17.0.2:9000 minio minio123
minio_1       | 
minio_1       | Object API (Amazon S3 compatible):
minio_1       |    Go:         https://docs.minio.io/docs/golang-client-quickstart-guide
minio_1       |    Java:       https://docs.minio.io/docs/java-client-quickstart-guide
minio_1       |    Python:     https://docs.minio.io/docs/python-client-quickstart-guide
minio_1       |    JavaScript: https://docs.minio.io/docs/javascript-client-quickstart-guide
minio_1       |    .NET:       https://docs.minio.io/docs/dotnet-client-quickstart-guide
minio_init_1  | Added `dogs` successfully.
minio_init_1  | Bucket created successfully `dogs/woof`.
minio_init_1  | Access permission for `dogs/woof` is set to `download`
docker1_minio_init_1 exited with code 0
```
