### ISSUE TITLE
Minio can't detect local machine on Docker 18.06 with Swarm

### ISSUE THREAD

**Issue by rafaelsierra** [minio/minio#6240]
## Current Behavior
```
ERROR Invalid command line arguments: no endpoint pointing to the local machine is found.
      > Please provide correct combination of local/remote paths.
      HELP:
        For more information, please refer to https://docs.minio.io/docs/minio-erasure-code-quickstart-guide
```

## Steps to Reproduce (for bugs)
1. Install Docker CE 18.06
1. Have 2 docker secrets created: `minio_access_key` and `minio_secret_key`
1. Deploy the following stack (`docker stack deploy -c this-file.yml minio`): 
```
version: "3.4"

services:
  minio1: &minio
    image: minio/minio:latest
    volumes:
      - minio1-data:/export1
      - minio2-data:/export2
    ports:
      - "9001:9000"
    networks:
      - minio
    command: server http://minio1/export1 http://minio1/export2 http://minio2/export1 http://minio2/export2
    secrets:
      - secret_key
      - access_key

  minio2:
    <<: *minio
    volumes:
      - minio3-data:/export1
      - minio4-data:/export2
    ports:
      - "9002:9000"

volumes:
  minio1-data:
  minio2-data:
  minio3-data:
  minio4-data:

networks:
  minio:
    driver: overlay

secrets:
  secret_key:
    external:
      name: minio_secret_key
  access_key:
    external:
      name: minio_access_key
```

## Context
Docker CE 18.06 was [recently released](https://github.com/docker/docker-ce/releases/tag/v18.06.0-ce) and it is not compatible with Minio without having to introduce docker-version specific changes (such as prepending `tasks.` to the hostname of each disk)

## Your Environment

* Version used (`minio version`): 2018-08-02T23:11:36Z

This is an issue exclusive to Docker 18.06, on 18.03 the same YML file works fine.

**Comment by alshabib** [comment]
fwiw, using the following stack is a workaround.

```
version: '3.1'

services:
  minio1:
    image: minio/minio:RELEASE.2018-07-31T02-11-47Z
    volumes:
      - minio1-data:/export
    ports:
      - "9001:9000"
    networks:
      - minio_distributed
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
    command: server http://tasks.minio1/export http://minio2/export http://minio3/export http://minio4/export
    secrets:
      - secret_key
      - access_key

  minio2:
    image: minio/minio:RELEASE.2018-07-31T02-11-47Z
    volumes:
      - minio2-data:/export
    ports:
      - "9002:9000"
    networks:
      - minio_distributed
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
    command: server http://minio1/export http://tasks.minio2/export http://minio3/export http://minio4/export
    secrets:
      - secret_key
      - access_key

  minio3:
    image: minio/minio:RELEASE.2018-07-31T02-11-47Z
    volumes:
      - minio3-data:/export
    ports:
      - "9003:9000"
    networks:
      - minio_distributed
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
    command: server http://minio1/export http://minio2/export http://tasks.minio3/export http://minio4/export
    secrets:
      - secret_key
      - access_key

  minio4:
    image: minio/minio:RELEASE.2018-07-31T02-11-47Z
    volumes:
      - minio4-data:/export
    ports:
      - "9004:9000"
    networks:
      - minio_distributed
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
    command: server http://minio1/export http://minio2/export http://minio3/export http://tasks.minio4/export
    secrets:
      - secret_key
      - access_key

volumes:
  minio1-data:

  minio2-data:

  minio3-data:

  minio4-data:

networks:
  minio_distributed:
    driver: overlay

secrets:
  secret_key:
    external: true
  access_key:
    external: true
```

**Comment by nitisht** [comment]
This looks like an issue with Docker Engine as reported on Docker repos

- https://github.com/docker/for-linux/issues/375
- https://github.com/docker/distribution/issues/2654
- https://github.com/docker/for-win/issues/2327

AFAICS there is not much we can do here except updating our sample yaml files. 
Lets wait to see how they are planning to address this. If required, we'll update the sample yaml files.

**Comment by harshavardhana** [comment]
> This looks like an issue with Docker Engine as reported on Docker repos
> 
> docker/for-linux#375
> docker/distribution#2654
> docker/for-win#2327
> AFAICS there is not much we can do here except updating our sample yaml files.
> Lets wait to see how they are planning to address this. If required, we'll update the sample yaml files.

Workaround is stick to 18.03-ce for now until a formal fix is present in docker upstream.

**Comment by meirhazonAnyVision** [comment]
Hi, I have used 18.03-ce but still having this issue, 
docker run -p 9000:9000 --name minio --env-file /root/.aws -v /data:/data  minio/minio:RELEASE.2018-07-31T02-11-47Z  server http://10.132.0.4/data http://10.132.0.13/data http://10.132.0.22/data http://10.132.0.23/data
Unable to find image 'minio/minio:RELEASE.2018-07-31T02-11-47Z' locally
RELEASE.2018-07-31T02-11-47Z: Pulling from minio/minio
911c6d0c7995: Already exists 
920d9e56e1a2: Pull complete 
e7dba93e232f: Pull complete 
Digest: sha256:ccb86b6562886af613f5750d6eb756bdf49f352fd7996dbaa4d25bb303baf33e
Status: Downloaded newer image for minio/minio:RELEASE.2018-07-31T02-11-47Z
ERROR Invalid command line arguments: no endpoint pointing to the local machine is found.
      > Please provide correct combination of local/remote paths.
      HELP:
        For more information, please refer to https://docs.minio.io/docs/minio-erasure-code-quickstart-guide

Please help.
Thanks

**Comment by nitisht** [comment]
@meirhazon1 can you try this approach https://github.com/minio/minio/issues/6240#issuecomment-410321828

**Comment by meirhazonAnyVision** [comment]
Hi,
Can you please share in what way this is different? how can the minio identify the local node when using a compose file?
Thank you,
Meir

**Comment by fsdaniel** [comment]
@meirhazon1 service name 'minio1' is directly related to the command to join on http://minio1/export. 

This resource will hopefully be of use to you :)
https://docs.docker.com/compose/networking/

**Comment by meirhazonAnyVision** [comment]
Hi,
so, the alias minion1 is the local host? when having multiple nodes, how should I set the minion1 alias?
I understand the overlay network part, why cant I use docker network? I guess it is also a limitation with Kubernetes, isn't it?
Thanks

**Comment by meirhazonAnyVision** [comment]
Hi
I also tried using docker-ce-18.03.1.ce-1.el7.centos.x86_64
I have given the local node the alias minio1
the nodes are just hanging, all 4. 
docker run -p 9000:9000 --name minio --env-file /root/.aws -v /data:/data  minio/minio:RELEASE.2018-07-31T02-11-47Z  server http://10.132.0.4/data http://minio1/data http://10.132.0.22/data http://10.132.0.23/data
Unable to find image 'minio/minio:RELEASE.2018-07-31T02-11-47Z' locally
RELEASE.2018-07-31T02-11-47Z: Pulling from minio/minio
911c6d0c7995: Already exists 
920d9e56e1a2: Pull complete 
e7dba93e232f: Pull complete 
Digest: sha256:ccb86b6562886af613f5750d6eb756bdf49f352fd7996dbaa4d25bb303baf33e
Status: Downloaded newer image for minio/minio:RELEASE.2018-07-31T02-11-47Z

Thanks

**Comment by harshavardhana** [comment]
> Hi
> I also tried using docker-ce-18.03.1.ce-1.el7.centos.x86_64
> I have given the local node the alias minio1
> the nodes are just hanging, all 4.
> docker run -p 9000:9000 --name minio --env-file /root/.aws -v /data:/data minio/minio:RELEASE.2018-07-31T02-11-47Z server http://10.132.0.4/data http://minio1/data http://10.132.0.22/data http://10.132.0.23/data
> Unable to find image 'minio/minio:RELEASE.2018-07-31T02-11-47Z' locally
> RELEASE.2018-07-31T02-11-47Z: Pulling from minio/minio
> 911c6d0c7995: Already exists
> 920d9e56e1a2: Pull complete
> e7dba93e232f: Pull complete
> Digest: sha256:ccb86b6562886af613f5750d6eb756bdf49f352fd7996dbaa4d25bb303baf33e
> Status: Downloaded newer image for minio/minio:RELEASE.2018-07-31T02-11-47Z

you have to set access and secret keys. And i see that you are also not deploying using the yaml stack ? @meirhazon1 ?

**Comment by harshavardhana** [comment]
you don't need to run manually using `docker run` you will simply do `docker stack deploy`

**Comment by harshavardhana** [comment]
> Hi,
> Can you please share in what way this is different? how can the minio identify the local node when using a compose file?

Well in compose file you define your services if you are running manually i.e using `docker run` make sure you to specify ACCESS and SECRET keys as mentioned here

https://docs.minio.io/docs/minio-docker-quickstart-guide.html

For docker swarm you should use this 

https://docs.minio.io/docs/deploy-minio-on-docker-swarm.html

**Comment by meirhazonAnyVision** [comment]
Hi,

Yes, the keys are at "--env-file /root/.aws" 

I do not wish to use swarm. I do not wish to use an overlay network.

[root@redis1a ~]# cat .aws 
MINIO_ACCESS_KEY=test
MINIO_SECRET_KEY=testtest

I get the same thing, it hangs.

[root@cassandra2 ~]# docker run -p 9000:9000 --name minio -e "MINIO_ACCESS_KEY=test" -e "MINIO_SECRET_KEY=testtest" -v /data:/data  minio/minio:RELEASE.2018-07-31T02-11-47Z  server http://minio1/data http://10.132.0.13/data http://10.132.0.22/data http://10.132.0.23/data

Please help. Thanks

**Comment by nitisht** [comment]
> I do not wish to use swarm. I do not wish to use an overlay network.

Are there any reasons to use Docker? You use the Minio binary, it will bring down the complexity

**Comment by meirhazonAnyVision** [comment]
Hi, Yes, I am doing a POC, It need to support Dokcker, swarm and kubernetes. 
Is it an issue having the minio use a different network than an overlay network?
As I am doing a POC, could you please have more specific answers. 
Thanks

**Comment by nitisht** [comment]
okay, can you please join us on Slack, so we can avoid creating noise on this issue. [https://minio.slack.com/] . You can ping me @ nitish on Slack

**Comment by meirhazonAnyVision** [comment]
I have already joined yesterday but you answered at this board. we will continue at slack. Thanlks

**Comment by meirhazonAnyVision** [comment]
I cant get hold of you on Slack, can you message me there?

**Comment by ntim** [comment]
Hi, another fix for the meantime is to set the hostname in the service definition:

```
services:
  minio1:
    image: minio/minio:RELEASE.2018-07-31T02-11-47Z
    hostname: minio1
    ...
```

**Comment by harshavardhana** [comment]
> services:
>   minio1:
>     image: minio/minio:RELEASE.2018-07-31T02-11-47Z
>     hostname: minio1
>     ...

this looks like a really good alternative @nitisht

**Comment by nitisht** [comment]
Thanks @ntim 

> this looks like a really good alternative @nitisht

Yes, this is perfect. Should we update our docs with this @harshavardhana

**Comment by harshavardhana** [comment]
Yes I think so @nitisht

**Comment by rohitnagesh** [comment]
Tried this, hostname is working from the same container, but when calling from another container its failing. [Link](https://stackoverflow.com/questions/52099248/host-name-not-working-with-docker-swarm-mode)

**Comment by XiaoqinLI** [comment]
Hey Guys, @nitisht , @harshavardhana 
I have a follow up question after following some suggestion above.
Currently on Docker 18.06, and tried the work around given above. My docker compose file is:
```
version: '3.1'

services:
  minio1:
    image: minio/minio
    hostname: minio1
    volumes:
      - /mnt/data1:/data1
      - /mnt/data2:/data2
      - /mnt/config:/root/.minio
    ports:
      - "9001:9000"
    networks:
      - minio_distributed
    deploy:
      restart_policy:
        delay: 120s
        condition: on-failure
      placement:
        constraints:
          - node.labels.minio1==true
    command: server http://tasks.minio1/data1 http://tasks.minio1/data2 http://minio2/data1 http://minio2/data2
    secrets:
      - secret_key
      - access_key

  minio2:
    image: minio/minio
    hostname: minio2
    volumes:
      - /mnt/data1:/data1
      - /mnt/data2:/data2
      - /mnt/config:/root/.minio
    ports:
      - "9002:9000"
    networks:
      - minio_distributed
    deploy:
      restart_policy:
        delay: 120s
        condition: on-failure
      placement:
        constraints:
          - node.labels.minio2==true
    command: server http://tasks.minio2/data1 http://tasks.minio2/data2 http://minio1/data1 http://minio1/data2
    secrets:
      - secret_key
      - access_key

networks:
  minio_distributed:
    driver: overlay

secrets:
  secret_key:
    external: true
  access_key:
    external: true
```
However, on one of the two servers, the container shows the following error log:
ERROR Unable to initialize backend: http://minio1:9000/data1 format error: UUID on positions 0:0 do not match with, expected 8b960cb4-c564-42c9-ba9e-c001011c3166 got 2f0af721-ccc1-46fa-a7e5-d0c22b8c6c28.

Could anyone help me with this?
Thanks a lot
