### ISSUE TITLE
Deployed Minio Kubernetes Distriubuted Log Message "Waiting for the first server to format the disks."

### ISSUE THREAD

**Issue by mitchellmaler** [minio/minio#6281]
I have deployed Minio in Kubernetes in distributed mode and the servers are not starting up correctly and complaining about waiting for disks to be formatted. I am not 100% how to troubleshoot this issue. I have checked that the mount point is completly empty and also each pod can reolve each other using the provided server url.

## Expected Behavior
All disks setup and the cluster starts running.

## Current Behavior
The cluster is not initialized, waiting for disks.

deployment file
```
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: minio
  namespace: cts-cernerdevtools-minio
spec:
  serviceName: minio-internal
  replicas: 4
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        envFrom:
        - secretRef:
            name: minio-secret
        image: minio/minio:latest
        args:
        - server
        - http://minio-0.minio-internal.cts-cernerdevtools-minio.svc.cluster.local/data/minio
        - http://minio-1.minio-internal.cts-cernerdevtools-minio.svc.cluster.local/data/minio
        - http://minio-2.minio-internal.cts-cernerdevtools-minio.svc.cluster.local/data/minio
        - http://minio-3.minio-internal.cts-cernerdevtools-minio.svc.cluster.local/data/minio
        ports:
        - containerPort: 9000
        # These volume mounts are persistent. Each pod in the PetSet
        # gets a volume mounted based on this field.
        volumeMounts:
        - name: data
          mountPath: /data
  # These are converted to volume claims by the controller
  # and mounted at the paths mentioned above.
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Gi
      storageClassName: default
---
apiVersion: v1
kind: Service
metadata:
  name: minio-internal
  namespace: cts-cernerdevtools-minio
  labels:
    app: minio
spec:
  clusterIP: None
  ports:
    - port: 9000
      name: minio
  selector:
    app: minio
```

logs
```
[minio-3] Waiting for the first server to format the disks.
[minio-2] Waiting for the first server to format the disks.
[minio-3] Waiting for the first server to format the disks.
[minio-2] Waiting for the first server to format the disks.
[minio-1] Waiting for the first server to format the disks.
[minio-3] Waiting for the first server to format the disks.
[minio-3] Waiting for the first server to format the disks.
[minio-2] Waiting for the first server to format the disks.
[minio-0] Waiting for all other servers to be online to format the disks.
[minio-3] Waiting for the first server to format the disks.
[minio-2] Waiting for the first server to format the disks.
[minio-2] Waiting for the first server to format the disks.
[minio-2] Waiting for the first server to format the disks.
[minio-3] Waiting for the first server to format the disks.
[minio-3] Waiting for the first server to format the disks.
[minio-3] Waiting for the first server to format the disks.
[minio-2] Waiting for the first server to format the disks.
[minio-1] Waiting for the first server to format the disks.
[minio-3] Waiting for the first server to format the disks.
[minio-2] Waiting for the first server to format the disks.
[minio-0] Waiting for all other servers to be online to format the disks.
[minio-3] Waiting for the first server to format the disks.
[minio-2] Waiting for the first server to format the disks.
[minio-2] Waiting for the first server to format the disks.
[minio-2] Waiting for the first server to format the disks.
[minio-2] Waiting for the first server to format the disks.
[minio-3] Waiting for the first server to format the disks.
[minio-1] Waiting for the first server to format the disks.
[minio-3] Waiting for the first server to format the disks.
[minio-2] Waiting for the first server to format the disks.
[minio-0] Waiting for all other servers to be online to format the disks.
```
