### ISSUE TITLE
In distributed mode Prometheus scraping gets multiple (as many as replica) duplicate results.

### ISSUE THREAD

**Issue by sanverm2** [minio/minio#6348]
I have a distribute mode Minio installation and I have enabled Prometheus scraping  by adding annotations.  The Prometheus is getting monitoring data but seems like they are duplicate and as many as number of replica. 

The results are coming per replica whereas it should be per service ( one in this case).

The following result gives an impression that there are four Minio Services and each having 4 disks.
Whereas It is just one Minio instance backed up by four replica having one disk each. 

![image](https://user-images.githubusercontent.com/28093961/44520441-5c29ae80-a6bf-11e8-8ad6-aa9df38ee2a1.png)

Details of annotations:

```
root@sanjay-ubt-master:~# kubectl -n kube-system describe svc minio-ibm-minio-objectstore 
Name:              minio-ibm-minio-objectstore
Namespace:         kube-system
Labels:            app=ibm-minio-objectstore
                   chart=ibm-minio-objectstore-1.6.0
                   heritage=Tiller
                   release=minio
Annotations:       prometheus.io/path=/minio/prometheus/metrics
                   prometheus.io/port=9000
                   prometheus.io/scheme=https
                   prometheus.io/scrape=true
Selector:          app=ibm-minio-objectstore,release=minio
Type:              ClusterIP
IP:                None
Port:              service  9000/TCP
TargetPort:        9000/TCP
Endpoints:         10.1.137.209:9000,10.1.180.216:9000,10.1.236.91:9000 + 1 more...
Session Affinity:  None
Events:            <none>

root@sanjay-ubt-master:~# kubectl -n kube-system describe endpoints minio-ibm-minio-objectstore 
Name:         minio-ibm-minio-objectstore
Namespace:    kube-system
Labels:       app=ibm-minio-objectstore
              chart=ibm-minio-objectstore-1.6.0
              heritage=Tiller
              release=minio
Annotations:  <none>
Subsets:
  Addresses:          10.1.137.209,10.1.180.216,10.1.236.91,10.1.54.147
  NotReadyAddresses:  <none>
  Ports:
    Name     Port  Protocol
    ----     ----  --------
    service  9000  TCP

Events:  <none>
root@sanjay-ubt-master:~# 


```

**Comment by nitisht** [comment]
Thanks for the issue @sanverm2 we'll take a look and fix it soon.

**Comment by sinhaashish** [comment]
@sanverm2  : Can you please share your `prometheus.yml` wanted to see the  `scrape_configs`

**Comment by sanverm2** [comment]
I am not sure if I can share the whole configuration, but I am sharing endpoint jobs because they drive  the Minio scrapping. 
```
  # Scrape config for service endpoints.
  #
  # The relabeling allows the actual service scrape endpoint to be configured
  # via the following annotations:
  #
  # * `prometheus.io/scrape`: Only scrape services that have a value of `true`
  # * `prometheus.io/scheme`: If the metrics endpoint is secured then you will need
  # to set this to `https` & most likely set the `tls_config` of the scrape config.
  # * `prometheus.io/path`: If the metrics path is not `/metrics` override this.
  # * `prometheus.io/port`: If the metrics are exposed on a different port to the
  # service then set this appropriately.
  - job_name: 'kubernetes-service-endpoints'

    kubernetes_sd_configs:
      - role: endpoints

    relabel_configs:
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
        action: drop
        regex: (https?)
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
        action: replace
        target_label: __scheme__
        regex: (https?)
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
        action: replace
        target_label: __address__
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
      - action: labelmap
        regex: __meta_kubernetes_service_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_service_name]
        action: replace
        target_label: kubernetes_name

  # Scrape config for service endpoints with tls enabled.
  #
  # The relabeling allows the actual service scrape endpoint to be configured
  # via the following annotations:
  #
  # * `prometheus.io/scrape`: Only scrape services that have a value of `true`
  # * `prometheus.io/scheme`: If the metrics endpoint is secured then you will need
  # to set this to `https` & most likely set the `tls_config` of the scrape config.
  # * `prometheus.io/path`: If the metrics path is not `/metrics` override this.
  # * `prometheus.io/port`: If the metrics are exposed on a different port to the
  # service then set this appropriately.
  - job_name: 'kubernetes-service-endpoints-with-tls'

    kubernetes_sd_configs:
      - role: endpoints

    relabel_configs:
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
        action: keep
        regex: (https?)
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_namespace]
        action: replace
        target_label: __address__
        regex: (\d+).(\d+).(\d+).(\d+):(\d+);(.+)
        replacement: $1-$2-$3-$4.$6.pod.cluster.local:$5
      - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
        action: replace
        target_label: __address__
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
      - action: labelmap
        regex: __meta_kubernetes_service_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_service_name]
        action: replace
        target_label: kubernetes_name

    scheme: https

    tls_config:
      ca_file: /********/tls.crt  ==>  This has valid path .
      cert_file: /***********/tls.crt
      key_file: /***********/tls.key
      insecure_skip_verify: true
```
