### ISSUE TITLE
Minio running on Swarm as Azure gateway exits by itself after a few minutes

### ISSUE THREAD

**Issue by victornoel** [minio/minio#6393]
## Expected Behavior

Minio should run without stopping.

## Current Behavior

After a few minutes, minio exits with the message:
```
Exiting on signal terminated
```

## Possible Solution

Disabling healthcheck seems to fix the problem (see #5057)

## Steps to Reproduce (for bugs)

Use the following docker swarm stack file:
```yaml
version: "3.6"

services:
  minio:
    image: minio/minio
    command: gateway azure
    environment:
      # minio will prefix those names with /run/secrets/
      MINIO_ACCESS_KEY_FILE: azure_access_key
      MINIO_SECRET_KEY_FILE: azure_secret_key
    networks:
      - webgateway
    secrets:
      - azure_access_key
      - azure_secret_key
    deploy:
      replicas: 1
      labels:
        traefik.enable: "true"
        traefik.frontend.rule: Host:upload.domain-name.com
        traefik.backend: upload-prod
        traefik.port: 9000
        traefik.docker.network: webgateway

networks:
  # traefik should also be in this network, see README
  webgateway:
    external: true

secrets:
  azure_access_key:
    file: ./azure_access_key
  azure_secret_key:
    file: ./azure_secret_key
```

## Your Environment
* Version used (`minio version`): 2018-08-25T01:56:38Z
* Environment name and version (e.g. nginx 1.9.1): docker 18.03.1-ce
