### ISSUE TITLE
"No such heal process is running on the server" when initiate new heal process

### ISSUE THREAD

**Issue by slavashvets** [minio/minio#6469]
## Expected Behavior
Heal process is initiated and I see heal progress bar

## Current Behavior
Heal process is initiated, but I see the error:

```
mc.exe: <DEBUG> POST /minio/admin/v1/heal/ HTTP/1.1
Host: *************
User-Agent: Minio (windows; amd64) madmin-go/0.0.1 mc/2018-09-10T23:39:12Z
Content-Length: 33
Authorization: AWS4-HMAC-SHA256 Credential=ecare/20180914//s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: 252ced5f76ee87b1cbc3dbac225d1e6a804a865bc6ceab23d153bddac8cb1875
X-Amz-Date: 20180914T092106Z
Accept-Encoding: gzip

mc.exe: <DEBUG> HTTP/1.1 200 OK
Transfer-Encoding: chunked
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/json
Date: Fri, 14 Sep 2018 09:21:07 GMT
Server: Minio/RELEASE.2018-09-12T18-49-56Z (linux; amd64)
Set-Cookie: 5a532e1390e2b34b5ff62203eed1510d=6900bfd940a906b8102e4763cee6b6e5; path=/; HttpOnly; Secure
Vary: Origin
X-Amz-Bucket-Region: us-east-1
X-Amz-Request-Id: 155439BF907B7B3C
X-Xss-Protection: 1; mode=block

mc.exe: <DEBUG> Response Time:  476.0273ms

mc.exe: <DEBUG> POST /minio/admin/v1/heal/?clientToken=383875d7-9fc4-4627-8984-26e393ace8c2 HTTP/1.1
Host: *************
User-Agent: Minio (windows; amd64) madmin-go/0.0.1 mc/2018-09-10T23:39:12Z
Content-Length: 0
Authorization: AWS4-HMAC-SHA256 Credential=ecare/20180914//s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20180914T092106Z
Accept-Encoding: gzip

mc.exe: <DEBUG> HTTP/1.1 400 Bad Request
Transfer-Encoding: chunked
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/json
Date: Fri, 14 Sep 2018 09:21:08 GMT
Server: Minio/RELEASE.2018-09-12T18-49-56Z (linux; amd64)
Set-Cookie: 5a532e1390e2b34b5ff62203eed1510d=c0cd94c8958e9cff99d7f694db327c67; path=/; HttpOnly; Secure
Vary: Origin
X-Amz-Bucket-Region: us-east-1
X-Amz-Request-Id: 155439BF9E833CB6
X-Xss-Protection: 1; mode=block

b0
{"Code":"XMinioHealNoSuchProcess","Message":"No such heal process is running on the server","Resource":"/minio/admin/v1/heal/","RequestId":"155439BF9E833CB6","HostId":"3L137"}

0

mc.exe: <DEBUG> Response Time:  213.0122ms

mc.exe: <ERROR> Unable to display follow heal status. No such heal process is running on the server
 (0) /q/.q/sources/gopath/src/github.com/minio/mc/cmd/admin-heal.go:130 cmd.mainAdminHeal(..)
 Commit:c352cadd4be2 | Release-Tag:RELEASE.2018-09-10T23-39-12Z | Host:spbws-prc554 | OS:windows | Arch:amd64 | Lang:go1.10.2 | Mem:2.7MB/8.0MB | Heap:2.7MB/4.9MB
```
## Possible Solution
No ideas

## Steps to Reproduce (for bugs)

```
 mc admin heal --debug -r qa/
```

## Context
Heal works well but it's not possible to check the status

## Environment
Client version:

```
$ mc version
Version: 2018-09-10T23:39:12Z
Release-tag: RELEASE.2018-09-10T23-39-12Z
Commit-id: c352cadd4be2c6bed64884c78d1e8a8ac6efaf3f
```
Server version:

```
Minio/RELEASE.2018-09-12T18-49-56Z (linux; amd64)
```

**Comment by kannappanr** [comment]
@slavashvets Thanks for filing this issue. We will try to repro the issue. Can you also provide more information about your setup about how many nodes and disks you have etc.

**Comment by slavashvets** [comment]
Cluster: Openshift 3.6 (StatefulSet)

Config:
```yaml
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: minio-distributed
  labels:
    app: minio
spec:
  podManagementPolicy: Parallel
  serviceName: minio-distributed
  replicas: 4
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      podManagementPolicy: Parallel
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - minio
                topologyKey: kubernetes.io/hostname
      containers:
        - name: minio
          envFrom:
            - secretRef:
                name: minio-vars
          image: [[ custom minio image ]]
          command:
            - /app/minio
          args:
            - --config-dir=/app/config
            - server
            - http://minio-distributed-0.minio-distributed/app/data
            - http://minio-distributed-1.minio-distributed/app/data
            - http://minio-distributed-2.minio-distributed/app/data
            - http://minio-distributed-3.minio-distributed/app/data
          ports:
            - containerPort: 9000
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /app/data
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: 9000
            initialDelaySeconds: 20
            failureThreshold: 10
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 600
          resources:
            requests:
              cpu: 100m
              memory: 500Mi
            limits:
              cpu: 1000m
              memory: 1Gi
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
```
Dockerfile of my minio image:
```Dockerfile
FROM centos:7.3.1611

RUN mkdir /app

RUN useradd --uid 1001 --gid 0 --home /app app && \
    chmod -R 775 /app

WORKDIR /app

ADD entrypoint.sh .

RUN curl -o minio https://dl.minio.io/server/minio/release/linux-amd64/archive/minio.RELEASE.2018-09-12T18-49-56Z && \
    chmod +x minio && \
    mkdir config && \
    mkdir data  && \
    chown 1001:0 -R . && chmod 777 -R .

USER 1001

ENV MINIO_ACCESS_KEY="demoaccesskey"
ENV MINIO_SECRET_KEY="mysecret"
ENV MINIO_REGION="us-east-1"

VOLUME /app/config
VOLUME /app/data

EXPOSE 9000

ENTRYPOINT [ "./entrypoint.sh" ]
```
