### ISSUE TITLE
Openshift: Insufficient permissions to access path, `/.minio`

### ISSUE THREAD

**Issue by FedericoPonzi** [minio/minio#6524]
## Expected Behavior

Tryied to deploy minio on Openshift,  using the generated kubernetes deployment file and have a minio succesfully deployed.

## Current Behavior

The config is succesfully submitted, but it goes in crash loop:
```
ERROR Unable to initialize configuration files: 
Insufficient permissions to access path, `/.minio`.
 > Please ensure the specified path can be accessed.
```
## Context
I've tried to debug the problem, by accessing the pod/container:
```
 $ whoami
whoami: unknown uid 1000130000 #For some reason, the terminal is not run by a root user - dunno why
/ $ ls -a
.           data        lib         root        storage     var
..          dev         media       run         sys
.dockerenv  etc         mnt         sbin        tmp
bin         home        proc        srv         usr
```
There is no .minio file.
In the pod page, these are the info about the container:
```
Containers
minio
Image: minio/minio
Command: <image-entrypoint> server /storage
Ports: 9000/TCP
Mount: storage → /storage read-write
Mount: default-token-7dc89 → /var/run/secrets/kubernetes.io/serviceaccount read-only
```

## Steps to Reproduce (for bugs)

1. Generate a kubernetes config
2. Use `oc create -f deployment.yml`

## Your Environment

OpenShift:  Running (openshift v3.10.0+e3465d0-44)
minishift v1.24.0+8a904d0

As an addition, here is the deployment.yml:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # This name uniquely identifies the PVC. Will be used in deployment below.
  name: minio-pv-claim
  labels:
    app: minio-storage-claim
spec:
  # Read more about access modes here: http://kubernetes.io/docs/user-guide/persistent-volumes/#access-modes
  accessModes:
    - ReadWriteOnce
  resources:
    # This is the request for storage. Should be available in the cluster.
    requests:
      storage: 50Gi
  # Uncomment and add storageClass specific to your requirements below. Read more https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1
  #storageClassName:
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  # This name uniquely identifies the Deployment
  name: minio-deployment
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        # Label is used as selector in the service.
        app: minio
    spec:
      # Refer to the PVC created earlier
      volumes:
      - name: storage
        persistentVolumeClaim:
          # Name of the PVC created earlier
          claimName: minio-pv-claim
      containers:
      - name: minio
        # Pulls the default Minio image from Docker Hub
        image: minio/minio
        args:
        - server
        - /storage
        env:
        # Minio access key and secret key
        - name: MINIO_ACCESS_KEY
          value: "RC2O1H9T9QW2ZY7Z4UR5"
        - name: MINIO_SECRET_KEY
          value: "dFbDCSRFL4OmFepfG4dSGF1fHcuV5ht3Z3Y8IW6U"
        ports:
        - containerPort: 9000
        # Mount the volume into the pod
        volumeMounts:
        - name: storage # must match the volume name, above
          mountPath: "/storage"
---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  type: LoadBalancer
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: minio
```

**Comment by nitisht** [comment]
@FedericoPonzi we are addressing this issue with #6160 , meanwhile you can try something like this under the `image` section of yaml file?

```yaml
image: minio/minio:RELEASE.2018-09-25T21-34-43Z
args:
- -C
- /data
- server
- /data
```

Here, we're using the `-C` flag to use a custom config directory that is `/data`. Note that you'll need to change the mount paths based on your setup.
