### ISSUE TITLE
Error: "The disk size is less than the minimum threshold" in minikube

### ISSUE THREAD

**Issue by melnikaite** [minio/minio#6528]
## Expected Behavior
minio is up and running

## Current Behavior
shows error: "The disk size is less than the minimum threshold"

## Steps to Reproduce (for bugs)
1. minikube start
2. kubectl apply -f k8s.secret.yaml
3. kubectl apply -f k8s.persistent-volume.yaml
4. kubectl apply -f k8s.persistent-volume-claim.yaml
5. kubectl apply -f k8s.service.yaml
6. kubectl apply -f k8s.deployment.yaml
7. kubectl logs -l app=minio

## Context
Running minio in minikube

## Your Environment
* Version used (`minio version`): RELEASE.2018-09-25T21-34-43Z
* Environment name and version (e.g. nginx 1.9.1): minikube version: v0.28.2
* Operating System and version (`uname -a`): OS X 10.13.6
* Configs: [k8s.zip](https://github.com/minio/minio/files/2421064/k8s.zip)

**Comment by harshavardhana** [comment]
> ##
> 1. minikube start
> 2. kubectl apply -f k8s.secret.yaml
> 3. kubectl apply -f k8s.persistent-volume.yaml
> 4. kubectl apply -f k8s.persistent-volume-claim.yaml
> 5. kubectl apply -f k8s.service.yaml
> 6. kubectl apply -f k8s.deployment.yaml
> 7. kubectl logs -l app=minio

The reasoning is that by default /var/minio host path doesn't have space in minikube VM @melnikaite so you are better off 

```
cat k8s.persistent-volume.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-volume
  labels:
    type: local
    app: minio
spec:
  storageClassName: minio
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/vda1/minio
```

**Comment by melnikaite** [comment]
I don't have `/mnt/vda1/minio` in my minikube, only `/dev/sda1`. Are there any value that will work on both GKE and minikube?
Currently it works with `/data` in minikube.
[df.txt](https://github.com/minio/minio/files/2421436/df.txt)

**Comment by harshavardhana** [comment]
> I don't have `/mnt/vda1/minio` in my minikube, only `/dev/sda1`. Are there any value that will work on both GKE and minikube?
> Currently it works with `/data` in minikube.
> [df.txt](https://github.com/minio/minio/files/2421436/df.txt)

yep /mnt/sda1 will work too @melnikaite - host path needs to point to a proper disk where the required storage can be claimed from.

**Comment by melnikaite** [comment]
According to this [doc](https://cloud.google.com/container-optimized-os/docs/concepts/disks-and-filesystem#filesystem) in Container-Optimized OS for persitent storage recommended `/home` and `var` paths. They are available on both minikube and GKE. I successfully mounted persistent volume to `/var/db` for postgres, but minikube doesn't show size for `/var`, so I can't run minio.

Is it possible to disable disk size check in minio?

Workaround: `echo "sudo mkdir /data/minio; sudo ln -s /data/minio /var/minio; exit" | minikube ssh`

**Comment by harshavardhana** [comment]
> Is it possible to disable disk size check in minio?

No it is not possible @melnikaite

**Comment by nitisht** [comment]
@melnikaite closing this as working as intended, feel free to reopen if there are further questions.

**Comment by billcrook** [comment]
This prevents one from using a mounted disk in minikube as minio storage. I would like to start minio with pre-populated buckets on minikube, but it is not possible. Is there another way to achieve this?

**Comment by harshavardhana** [comment]
You can use 1.1GiB to cirumvent this

**Comment by billcrook** [comment]
Can you elaborate? Thanks for your help.

**Comment by harshavardhana** [comment]
In your kubernetes yaml, choose 1.1GiB for your PV

**Comment by billcrook** [comment]
Unfortunately, I still see `ERROR Unable to initialize backend: The disk size is less than the minimum threshold` when using a persistent volume of size 1.1G with a persistent volume claim of 1G. The local disk is correctly mounted in the container via minikube.

Any other recommendations?

My configuration:
`minikube mount tests/data/s3/:/s3-data`

```
kind: PersistentVolume
apiVersion: v1
metadata:
  name: minio-pv
  labels:
    app: minio
spec:
  storageClassName: minio
  capacity:
    storage: 1.1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/s3-data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minio-pvc
spec:
  storageClassName: minio
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: minio
```

**Comment by harshavardhana** [comment]
This should work 

```
kind: PersistentVolume
apiVersion: v1
metadata:
  name: minio-pv
  labels:
    app: minio
spec:
  storageClassName: minio
  capacity:
    storage: 1.1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/s3-data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minio-pvc
spec:
  storageClassName: minio
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1.1Gi
  selector:
    matchLabels:
      app: minio
```

Just make sure that `df -h /s3-data` shows at least 1G disk space free.
