### ISSUE TITLE
minio1_1      | ERROR Invalid command line arguments: use path style endpoint for FS setup.

### ISSUE THREAD

**Issue by flik** [minio/minio#6803]
## Expected Behavior
It should work

## Current Behavior
minio1_1      | ERROR Invalid command line arguments: use path style endpoint for FS setup.

## Steps to Reproduce (for bugs)
Run the command: docker-compose up -d
then check logs: docker-compose logs 

minio1_1      | ERROR Invalid command line arguments: use path style endpoint for FS setup.
minio1_1      |       > Please check the FS endpoint.
minio1_1      |       HELP:
minio1_1      |         FS mode requires only one writable disk path.
minio1_1      |       Example 1:
minio1_1      |          $ minio server /data/minio/
xdev_minio1_1 exited with code 1

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`): image: minio/minio:RELEASE.2018-11-06T01-01-02Z
* Environment name and version (e.g. nginx 1.9.1): 
* Server type and version:
* Operating System and version (`uname -a`): mac osx
* Link to your project:

**Comment by kannappanr** [comment]
@flik You probably are using `URL type endpoint` like 

`minio server http://127.0.0.1:9000/tmp/b`

You will have to do something like

`minio server /data/dir`

**Comment by flik** [comment]
Here is my docker-compose.yml file:
```
version: '3'
services:
 minio1:
  image: minio/minio:RELEASE.2018-11-06T01-01-02Z
  volumes:
   - data1:/data
  ports:
   - "9001:9000"
  environment:
   MINIO_ACCESS_KEY: minio
   MINIO_SECRET_KEY: minio123
  command: server http://minio1/data  

volumes:
  data1:
```

**Comment by kannappanr** [comment]
The following `yaml` file works in my setup. The only difference between the one that you pasted and the one that I have is that the command is changed to `command: server /data  `
```
version: '3'
services:
 minio1:
  image: minio/minio:RELEASE.2018-11-06T01-01-02Z
  volumes:
   - data1:/data
  ports:
   - "9001:9000"
  environment:
   MINIO_ACCESS_KEY: minio
   MINIO_SECRET_KEY: minio123
  command: server /data  

volumes:
  data1:
```
