### ISSUE TITLE
Too many 'List Buckets' calls

### ISSUE THREAD

**Issue by ccpu** [minio/minio#6806]
Hi,

I am experimenting with minio with the b2 gateway and I have noticed that it makes too many calls to 'b2_list_buckets', something like 3000 or more a day.

wondering if its intended behavior, so it can detect the changes! is there any option to limit the calls?

## Expected Behavior
be able to control the call rates.

## Current Behavior
making too many calls to 'b2_list_buckets'.

## Possible Solution
implementing some sort of event base technics.
be able to limit the calls.

## Steps to Reproduce (for bugs)
using docker compose to lunch server:
```
services:
  minio2:
    container_name: minio-b2
    image: minio/minio
    restart: always
    volumes:
      - path to local :/data
    environment:
      MINIO_ACCESS_KEY: <access key>
      MINIO_SECRET_KEY: <secret key>
      MINIO_HTTP_TRACE: /data/minio.log
    ports:
      - 9001:9000
    command: gateway b2
```
## Context

not affecting me, just trying to understand how it works, is it necessary to make that many calls?

## Regression
NO

Thanks,
