### ISSUE TITLE
minio behind proxy and presigned urls

### ISSUE THREAD

**Issue by runar-indico** [minio/minio#6853]
Currently, we have deployed `minio` as a microservice in kubernetes. When we generate the `presigned url`, it returns it as

`
http://minio:9000/cjofm194t001t07122rc3jcx0/201811211513503.mp4?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=admin%2F20181122%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20181122T072255Z&X-Amz-Expires=184&X-Amz-SignedHeaders=host&X-Amz-Signature=460b9b46f5fac13f29de4372dd7c1e8d6d6c747510761695a40d6b9ff08ba7d8
`

This works on the internal network in kubernetes. For public access, we rewrite the url as ``` `https://example.com/minio/cjofm194t001t0...```

However, the signing fails here. This might be due to our ingress controller (see below for our config) , which seems to touch the urls and some headers. Do minio read any of this upon verification of the signature?

## Expected Behavior

The url should resolve into a valid file download.

## Current Behavior

Upon requesting the generated public url, I get this message (as XML):

`
The request signature we calculated does not match the signature you provided. Check your key and signing method.
`

## Possible Solution

Some changes to my ingress controller will probably resolve this.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

Running on kubernetes, behind the following ingress: 

```yaml
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: ingress-minio-minion
 annotations:
   kubernetes.io/ingress.class: "nginx"
   nginx.ingress.kubernetes.io/rewrite-target: /
spec:
 rules:
 - host: {{.host}}
   http:
     paths:
     - path: /minio/
       backend:
         serviceName: minio
         servicePort: 9000
```

Which generates the following location in nginx:
```nginx
        location ~* "^/minio/(?<baseuri>.*)" {

            set $namespace      "demo";
            set $ingress_name   "ingress-minio-minion";
            set $service_name   "minio";
            set $service_port   "9000";
            set $location_path  "/minio/";

            rewrite_by_lua_block {

                balancer.rewrite()

            }

            log_by_lua_block {

                balancer.log()

                monitor.call()
            }

            if ($scheme = https) {
                more_set_headers                        "Strict-Transport-Security: max-age=15724800; includeSubDomains";
            }

            port_in_redirect off;

            set $proxy_upstream_name "demo-minio-9000";

            # enforce ssl on server side
            if ($redirect_to_https) {

                return 308 https://$best_http_host$request_uri;

            }

            client_max_body_size                    1m;

            proxy_set_header Host                   $best_http_host;

            # Pass the extracted client certificate to the backend

            # Allow websocket connections
            proxy_set_header                        Upgrade           $http_upgrade;

            proxy_set_header                        Connection        $connection_upgrade;

            proxy_set_header X-Request-ID           $req_id;
            proxy_set_header X-Real-IP              $the_real_ip;

            proxy_set_header X-Forwarded-For        $the_real_ip;

            proxy_set_header X-Forwarded-Host       $best_http_host;
            proxy_set_header X-Forwarded-Port       $pass_port;
            proxy_set_header X-Forwarded-Proto      $pass_access_scheme;

            proxy_set_header X-Original-URI         $request_uri;

            proxy_set_header X-Scheme               $pass_access_scheme;

            # Pass the original X-Forwarded-For
            proxy_set_header X-Original-Forwarded-For $http_x_forwarded_for;

            # mitigate HTTPoxy Vulnerability
            # https://www.nginx.com/blog/mitigating-the-httpoxy-vulnerability-with-nginx/
            proxy_set_header Proxy                  "";

            # Custom headers to proxied server

            proxy_connect_timeout                   5s;
            proxy_send_timeout                      60s;
            proxy_read_timeout                      60s;

            proxy_buffering                         off;
            proxy_buffer_size                       4k;
            proxy_buffers                           4 4k;
            proxy_request_buffering                 on;

            proxy_http_version                      1.1;

            proxy_cookie_domain                     off;
            proxy_cookie_path                       off;

            # In case of errors try the next upstream server before returning an error
            proxy_next_upstream                     error timeout;
            proxy_next_upstream_tries               3;

            rewrite "(?i)/minio/(.*)" /$1 break;
            rewrite "(?i)/minio/$" / break;
            proxy_pass http://upstream_balancer;

            proxy_redirect                          off;

        }
```

**Comment by harshavardhana** [comment]
you cannot rewrite URLs unfortunately, your presigned URL should be generated from the client side pointing to your proxy endpoint instead of kubernetes hostname.

**Comment by runar-indico** [comment]
Ok, I might add that this is working correctly under a regular nginx-config like this:

```
location /minio/ {
      proxy_pass http://minio:9000/;
  }
```

That leads me to think that some of the headers are involved in how the signature is verified. Or is it based purely on the url?

**Comment by nitisht** [comment]
Headers are involved @runar-indico , please refer this for S3v4 signature calculation : https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-header-based-auth.html

**Comment by nitisht** [comment]
closing this as answered @runar-indico . Feel free to reopen if there any further questions

**Comment by Jimmyscene** [comment]
> you cannot rewrite URLs unfortunately, your presigned URL should be generated from the client side pointing to your proxy endpoint instead of kubernetes hostname.

@harshavardhana  Could you elaborate on how to do this? I have a repo [here](https://github.com/Jimmyscene/miniomemes) which demonstrates the issue similar to runar-indico , I believe, however I'm not sure how he got it to work with that simple nginx config, which is identical to mine.

My problem is two-fold:
1) I cannot instantiate a minio client with a path based route, ie https://localhost/minio, thus even if I tried to generate the presigned URL client side, I'd still be unable to.

2) Wouldn't generating the URL client side require the client have access to the server credentials?

**Comment by runar-indico** [comment]
I might elaborate a bit here on my setup. I actually define two routes for minio, since it expects to sit at the root of the domain, one for the generated url and minio by itself, `https://example.com/minio` pointing to `http://minio` and https://example.com/miniobrowser`  pointing to `http://minio/minio`. Using this, I am able to rewrite the generated url into a valid form, since nginx converts it back to the original url, and also have access to the minio-ui in the browser at `/miniobrowser`.

As for generating the url, you would want to do this on the server-side.

**Comment by mrceresa** [comment]
Dear all,
we've a similar problem with minio on kubernetes behind an ingress:
* The minio server works perfectly on the internal cluster (i.e. from pods)
* Our ingress defines /minio as the location (i.e. example.com/minio)
* We cannot use the presigned urls because the server generates the url relative to /, not /minio (i.e. example.com/bucketname/ instead of example.com/**minio**/bucketname/) so the ingress controller never forwards the request to the service.
* If I manually add the path (i.e. example.com/minio/bucketname/etc...) the request reaches the server, but the auth fails.
* Even if I enables the "HTTP Trace" variable, the logs only contain the healthz request, not the requests I with the presigned url

I've looked into the nginx conf of the ingress controller and it is a bit complicated, but the proxy-pass suggested by @runar-indico is:
`proxy_pass http://upstream_balancer;`

I can post the full configuration and/or change the ingress to add more routes but I didn't really understand how to fix that.

Thank you for any help you might provide!

Best,

Mario

**Comment by fwwucn** [comment]
@mrceresa For those who has the similar issue:
I resolved the error 'The request signature we calculated does not match the signature you provided. Check your key and signing method.' just by setting Host in header. (tested on minikube 1.0.0 & kubectl 1.14.0)

Please follow the 2 steps: 
1. No need to deploy minio with https, just use http and replace the original presigned url generated by minio like `http://minio:9000/${bucketName}/...` with your ingress minio path like `https://${YOUR_MINIKUBE_IP}/minio` in your backend service.

2. Use more_set_input_headers instead of proxy_set_header.
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-minio
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_input_headers 'Host: minio:9000';
spec:
  rules:
    - http:
        paths:
          - path: /minio/?(.*)
            backend:
              serviceName: minio
              servicePort: 9000
```

**Comment by n1ru4l** [comment]
Nginx Docker Image Solution:

**Dockerfile**
```docker
FROM nginx:alpine

COPY nginx.default.conf /etc/nginx/conf.d/default.conf
COPY build /usr/share/nginx/html 

EXPOSE 7011
```


**nginx.default.conf**
```
server {
    listen       7011;
    server_name  localhost;
 
    location / {
        client_max_body_size 50M;
        proxy_pass http://storage-s3:9000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host 'storage-s3:9000';
    }
}
```

**docker-compose.yml**
```
version: "3.7"

services:
  storage-s3:
    image: minio/minio
    tmpfs:
      - /data:rw
      - /root/.minio:rw
    environment:
      MINIO_ACCESS_KEY: "lubitz"
      MINIO_SECRET_KEY: "12345678"
    networks:
      - internal
    command: server start

  storage-s3-proxy:
    build:
      context: "./packages/s3-local-proxy"
    ports:
      - "7011:7011"
   networks:
     - internal
networks:
  internal:
```

**Comment by jgato** [comment]
I dont know if it is the same issue, but it seems similar. We have a minio deployment with kubernetes (and Rancher), and an Ingress Controller to act as proxy for minio.

Through the proxy I can access to Minio login screen. using my credentials this works ok, I see by one second accessing to Minio but I am forwarded back to the login screen. What could be happening?

The ingress controller is pretty simple:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
  creationTimestamp: "2019-12-02T08:51:40Z"
  generation: 14
  labels:
    cattle.io/creator: norman
  name: minio
spec:
  rules:
  - host: host.example.com
    http:
      paths:
      - backend:
          serviceName: ingress-44dff34d7f1d082970c54202869f36b2
          servicePort: 9000


```
