### ISSUE TITLE
Minio in docker does not generate a config.json file in the desired location

### ISSUE THREAD

**Issue by ccpu** [minio/minio#6912]
I am having a problem making minio generates a config.json file outside the docker container.

it does generate the JSON file when using the local server, however, when using b2/aws gateway it fails to generate the JSON file.

also, I can not find it in docker itself under '/root/.minio' directory. 

## Expected Behavior
Be able to have access to config.json outside the docker container.

## Current Behavior
it does generate the config file when configuring minio for the local server, but it won't do same for the b2/aws gateways.

## Steps to Reproduce (for bugs)
using docker docker-compose file:
```
  minio2:
    container_name: minio-b2
    image: minio/minio
    restart: on-failure
    volumes:
      - e:/Docker/data/minio/b2:/data
      - e:/Docker/data/minio/b2/config:/root/.minio
    environment:
      MINIO_ACCESS_KEY: access-key
      MINIO_SECRET_KEY: secret-key
      MINIO_HTTP_TRACE: /data/minio.log
    ports:
      - 9001:9000
    command: --config-dir /data/config gateway b2
```
## Context
i am trying to centerlize configuration file, so multiple minio instance can have access. to the same configuration file.

Thanks,
