### ISSUE TITLE
Accessing Minio NAS gateway using mc command it is not able to connect and fetch data consistently

### ISSUE THREAD

**Issue by sanverm2** [minio/minio#6960]
I am seeing issue with NAS gateway. I have created a PVC ( with accessModes: ReadWriteMany  using glusterFS)) . I am using replica 4. However, when accessing it using mc command it is not able to connect and fetch data consistently.

```
image:
  repository: minio/minio
  tag: RELEASE.2018-11-30T03-56-59Z
  pullPolicy: IfNotPresent

## Set default image, imageTag, and imagePullPolicy for the `mc` (the minio
## client used to create a default bucket).
##
mcImage:
  repository: minio/mc
  tag: RELEASE.2018-11-30T01-52-08Z
  pullPolicy: IfNotPresent
```

STEPS: 
Creating PVC ( using glusterFS as it must support rw many ) .

```
root@sanverm-master:~/test-dir/minio_test# vim pvc.yaml 
root@sanverm-master:~/test-dir/minio_test# cat pvc.yaml 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: gluster1
 annotations:
   volume.beta.kubernetes.io/storage-class: glusterfs
spec:
 accessModes:
  - ReadWriteMany
 resources:
   requests:
     storage: 10Gi

root@sanverm-master:~/test-dir/minio_test# kubectl get pvc
NAME       STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
gluster1   Bound     pvc-17b44424-fe00-11e8-9d67-00000a290c67   10Gi       RWX            glusterfs      19h
root@sanverm-master:~/test-dir/minio_test# kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS    CLAIM                                       STORAGECLASS               REASON    AGE
pvc-17b44424-fe00-11e8-9d67-00000a290c67   10Gi       RWX            Delete           Bound     default/gluster1                            glusterfs                            19h

```

Deploying Minio as NAS gateway:
```
root@sanverm-master:~/test-dir/minio_test# cat values_nas.yaml 
minioAccessSecret: "minio"

nasgateway:
  enabled: true
  # Number of parallel instances
  replicas: 4
  # Generally for NAS Gateway, you'd like to bind the PVC to a specific PV. To ensure that happens, PV to bind to should have
  # a label like "pv: <value>", use value here.
  pv: "pvc-17b44424-fe00-11e8-9d67-00000a290c67"
root@sanverm-master:~/test-dir/minio_test# helm install --debug --name minio  -f ./test-dir/minio_test/values_nas.yaml   ./ibm-minio-objectstore/stable/ibm-minio-objectstore/ --tls
``` 

Accessing NAS gateway.

```
/ # mc config host add myminio http://minio-ibm-minio-objectstore:9000 admin adm
in1234 S3v4
Added `myminio` successfully.
/ # 
/ # 
/ # 
/ # ls myminio
ls: myminio: No such file or directory
/ # mc ls myminio
/ # mc ls myminio
/ # mc ls myminio
/ # mc mb myminio/test
Bucket created successfully `myminio/test`.
/ # mc ls myminio/test
/ # mc ls myminio/test
mc: <ERROR> Unable to stat `myminio/test`. Bucket `test` does not exist.
/ # mc ls myminio/test
mc: <ERROR> Unable to stat `myminio/test`. Bucket `test` does not exist.
/ # mc ls myminio/test
/ # mc ls myminio/test
mc: <ERROR> Unable to stat `myminio/test`. Bucket `test` does not exist.
/ # mc ls myminio/test
/ # mc ls myminio/test
/ # mc ls myminio/test
/ # mc ls myminio/test
/ # mc ls myminio/test
/ # mc ls myminio/test
mc: <ERROR> Unable to stat `myminio/test`. Bucket `test` does not exist.
/ # mc ls myminio/test

```
Note: There are intermittent  ```Unable to stat `myminio/test`. Bucket `test` does not exist.`` messages seen.
