### ISSUE TITLE
The cluster is restarted successfully only when all nodes are started.

### ISSUE THREAD

**Issue by R-omk** [minio/minio#6995]
I have a docker stack with six nodes.

```
docker stack deploy --compose-file=docker-compose.yaml   minio_test
```

Then I emulate the loss of nodes and restore one 

```
docker service scale  minio_test_minio6=0 minio_test_minio5=0
```

```
docker service scale  minio_test_minio5=1
```

## Expected Behavior
`./mc admin info  mini`
Should show that the test_minio5 node is running.

## Current Behavior

Both  test_minio5 and test_minio6   is offline

Now  if I restart cluster  via `./mc admin service restart mini`  or via docker (or any other restart ) the cluster will never come up, although five of the six nodes are available.

**that is, if for some reason at least one node does not start, we lose the availability of the entire cluster**

## Steps to Reproduce (for bugs)
partially described above

## Context
Docker swarm node on one node,  each service has its own volume

## Your Environment
* Version used (`minio version`): Version : 2018-12-06T01:27:43Z
* Docker Version:           18.09.0
* Operating System and version :Ubuntu 18.04.1 LTS  Linux  4.15.0-42-generic

**Comment by nitisht** [comment]
We'll take a look on why this is happening @R-omk

**Comment by R-omk** [comment]
ok, here is my stack file

```yml
version: '3.7'


x-service-minio-proto: &service-minio-proto
  image: minio/minio
  healthcheck:
    disable: true
  networks:
   - minio_distributed
  environment:
   MINIO_ACCESS_KEY: dfsdf
   MINIO_SECRET_KEY: 12345678
  deploy:
   restart_policy:
    delay: 10s
    max_attempts: 10
    window: 60s
  command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export http://minio5/export http://minio6/export 


services:

 minio1:
  <<: *service-minio-proto
  hostname: minio1
  volumes:
   - v1:/export
  ports:
   - "9001:9000"

 minio2:
  <<: *service-minio-proto
  hostname: minio2
  volumes:
   - v2:/export
  ports:
   - "9002:9000"

 minio3:
  <<: *service-minio-proto
  hostname: minio3
  volumes:
   - v3:/export
  ports:
   - "9003:9000"
   
 minio4:
  <<: *service-minio-proto
  hostname: minio4
  volumes:
   - v4:/export
  ports:
   - "9004:9000"
   
 minio5:
  <<: *service-minio-proto
  hostname: minio5
  volumes:
   - v5:/export
  ports:
   - "9005:9000"
   
 minio6:
  <<: *service-minio-proto
  hostname: minio6
  volumes:
   - v6:/export
  ports:
   - "9006:9000"   

volumes:
  v1:
  v2:
  v3:
  v4:
  v5:
  v6:

networks:
 minio_distributed:
  driver: overlay


```
