### ISSUE TITLE
Docker Swarm and minio distributed - secrets issue

### ISSUE THREAD

**Issue by waqarkhan3389** [minio/minio#7009]
Following this doc https://docs.minio.io/docs/deploy-minio-on-docker-swarm - results in the error below. 

Maybe this is docker secrets issue - can I set up the stack on swarm via a different method?

**"starting container failed: RemoveSecretsPath failed: remove /var/lib/docker/containers/c6c4623343663d14cf3d551ae9067d32b2df7239e4f6d32fb36f7cd8cc13704b/secrets/access_key: read-only file system"**

## Expected Behavior

Swarm services should start

## Current Behavior

"starting container failed: RemoveSecretsPath failed: remove /var/lib/docker/containers/c6c4623343663d14cf3d551ae9067d32b2df7239e4f6d32fb36f7cd8cc13704b/secrets/access_key: read-only file system"

## Steps to Reproduce (for bugs)
Follow this doc for Centos 7 https://docs.minio.io/docs/deploy-minio-on-docker-swarm

**Comment by nitisht** [comment]
>  can I set up the stack on swarm via a different method?

Yes, please try this yaml file, https://github.com/minio/minio/blob/master/docs/orchestration/docker-swarm/docker-compose.yaml

**Comment by waqarkhan3389** [comment]
Seeing this: 

services.minio2.environment.0 must be a string

**Comment by Praveenrajmani** [comment]
@waqark3389  I used exactly the same docker compose file as provided in the docs 

```
version: '3.1'

services:
  minio1:
    image: minio/minio:RELEASE.2018-12-19T23-46-24Z
    hostname: minio1
    volumes:
      - minio1-data:/export
    ports:
      - "9001:9000"
    networks:
      - minio_distributed
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:
        constraints:
          - node.labels.minio1==true
    command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export
    secrets:
      - secret_key
      - access_key

  minio2:
    image: minio/minio:RELEASE.2018-12-19T23-46-24Z
    hostname: minio2
    volumes:
      - minio2-data:/export
    ports:
      - "9002:9000"
    networks:
      - minio_distributed
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:
        constraints:
          - node.labels.minio2==true
    command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export
    secrets:
      - secret_key
      - access_key

  minio3:
    image: minio/minio:RELEASE.2018-12-19T23-46-24Z
    hostname: minio3
    volumes:
      - minio3-data:/export
    ports:
      - "9003:9000"
    networks:
      - minio_distributed
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:
        constraints:
          - node.labels.minio3==true
    command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export
    secrets:
      - secret_key
      - access_key

  minio4:
    image: minio/minio:RELEASE.2018-12-19T23-46-24Z
    hostname: minio4
    volumes:
      - minio4-data:/export
    ports:
      - "9004:9000"
    networks:
      - minio_distributed
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:
        constraints:
          - node.labels.minio4==true
    command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export
    secrets:
      - secret_key
      - access_key

volumes:
  minio1-data:

  minio2-data:

  minio3-data:

  minio4-data:

networks:
  minio_distributed:
    driver: overlay

secrets:
  secret_key:
    external: true
  access_key:
    external: true
```

i don't see any error here.
Can you remove `rm -rf /var/lib/docker/containers/c6c4623343663d14cf3d551ae9067d32b2df7239e4f6d32fb36f7cd8cc13704b/secrets/` and try again

And it would be better if you provide us the docker version
