### ISSUE TITLE
federation: When nodes IPs change, old IPs in etcd are not removed

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#7092]
## Expected Behavior
One docker node changing its IP address should not affect regular behavior

## Current Behavior
One docker node has its IP address changed, proxying S3 requests between nodes doesn't work anymore.

## Possible Solution
When a node is restarted, it has to list all etcd entries (A map of bucket -> IP addresses). Now, if a bucket is found in etcd and locally but one of the IP addresses doesn't correspond to the IP of the current node and to any node in the same cluster, then fix it.

## Steps to Reproduce (for bugs)
1. Use the following docker script:
```
version: '3'
services:
  
  minio-server-muc:
    image: minio/minio:edge
    ports:
      - 80:80
    volumes:
      - minio-server_muc_demo4_data_vol:/data
      - minio-server_muc_demo4_logs_vol:/logs
    command: minio gateway --address :80 nas /data
    environment:
      - "MINIO_ACCESS_KEY=S2Q3CDB1FOPP24M9DGS2"
      - "MINIO_SECRET_KEY=EpIb-urpHW9rXNNdtHUS6X7SuElYXO-4b7k_H_ki"
      - "MINIO_REGION=MUC"
      - "MINIO_ETCD_ENDPOINTS=http://etcd-server-muc:2379"
      - "MINIO_DOMAIN=tracecloud.test"
      - "MINIO_PUBLIC_IPS=172.18.0.2"
    networks:
      minio_network:
        ipv4_address: 172.18.0.2
  
  minio-server-sc:
    image: minio/minio:edge
    ports:
      - 90:80
    volumes:
      - minio-server_sc_demo4_data_vol:/data
      - minio-server_sc_demo4_logs_vol:/logs
    command: minio gateway --address :80 nas /data
    environment:
      - "MINIO_ACCESS_KEY=S2Q3CDB1FOPP24M9DGS2"
      - "MINIO_SECRET_KEY=EpIb-urpHW9rXNNdtHUS6X7SuElYXO-4b7k_H_ki"
      - "MINIO_REGION=SC"
      - "MINIO_ETCD_ENDPOINTS=http://etcd-server-muc:2379"
      - "MINIO_DOMAIN=tracecloud.test"
      - "MINIO_PUBLIC_IPS=172.18.0.3"
    networks:
      minio_network:
        ipv4_address: 172.18.0.3

  etcd-server-muc:
    image: quay.io/coreos/etcd:v3.1.10
    ports:
      - 2379:2379
      - 2380:2380
    environment:
      - "ALLOW_NONE_AUTHENTICATION=yes"
      - "ETCD_ADVERTISE_CLIENT_URLS=http://etcd-server-muc:2379"
      - "ETCD_LISTEN_CLIENT_URLS=http://172.18.0.6:2379"
    networks:
      minio_network:
        ipv4_address: 172.18.0.6

volumes:
  minio-server_muc_demo4_data_vol:
  minio-server_muc_demo4_logs_vol:
  minio-server_sc_demo4_data_vol:
  minio-server_sc_demo4_logs_vol:

networks:
 minio_network:
   driver: bridge
   ipam:
    config:
      - subnet: 172.18.0.0/24
```
2. `docker-compose up`
This will start and etcd server, and two Minio instances called local_muc and local_sc.

3. Add two new aliases for local_muc and local_sc in mc
4. mc mb local_muc/testbucket; mc cp testfile local_muc/testbucket/
5. mc cat local_sc/testbucket/testfile to be sure that the federation setup is working properly.
6. Now stop docker-compose (Control-C)
7. Edit docker-compose.yaml by replacing 172.18.0.2 with 172.18.0.102 and 172.18.0.3 with 172.18.0.103
8. `docker-compose up` again
9. `mc cat local_sc/testbucket/testfile`

```
minio-server-sc_1   | 2019-01-16 11:31:34.560392 I | http: proxy error: dial tcp 172.18.0.2:80: connect: no route to host
```
 
## Context
Fixing a bug

## Regression
No

## Your Environment
All
