### ISSUE TITLE
Unable to start minio in container with TLS (probably doc issue)

### ISSUE THREAD

**Issue by cjeanneret** [minio/minio#7183]
Hello,
I'm struggling getting minio starting with TLS. Here's the command I'm launching:
```
podman run -v "minio-data:/data:rw,z" -v "minio-config:/root/.minio:rw,z" --net host -e MINIO_PUBLIC_IPS=$(hostname -f) -e MINIO_DOMAIN=object.domain.tld -e MINIO_ACCESS_KEY=FooBar -e MINIO_SECRET_KEY=FooBarBaz minio/minio --anonymous -S /root/.minio/certs server https://node01.domain.tld:9000/data https://node02.domain.tld:9000/data https://node03.domain.tld:9000/data https://node04.domain.tld:9000/data
```

Into the "minio-config" volume (mounted as /root/.minio in the container), I have the "certs" directory with a "private.key" and a "pblic.crt" file, as well as a CAs directory containing ipa.domain.tld.pem.

The certificate is signed by a freeIPA instance, and I get it using ipa-getcert.

The certificate is signed for the following name:
```
DNS:node01.domain.tld
```

The ```hostname -f``` returns node01.domain.tld as well.

I'm a bit stuck with that config, and would really appreciate some precisions about the mandatory content of the certificate, and the way minio does actually detect the certificate...

Thank you!

Cheers,

C.

**Comment by kannappanr** [comment]
@cjeanneret We will try to reproduce this issue and get back to you.

**Comment by kannappanr** [comment]
@calvernaz Is the file name `pblic.crt` a typo? Because it should be `public.crt`.

**Comment by cjeanneret** [comment]
Hello,

duh, yes, typo in here, name are correct on the instance.

Cheers,

C.

**Comment by cjeanneret** [comment]
Hello,

Small precision: I'm unable to request a certificate with an IP address (freeIPA limitation) - so I just hope it's not how minio searches for its certificate... ?

Also, I've double-checked, apparently I don't have any SELinux issue that would prevent access to the files (no "denied" in the audit.log).

Cheers,

C.

**Comment by cjeanneret** [comment]
Me again,
found out my issue: the container engine I'm using, podman, doesn't store its data where I thought when using named volume (new feature), and of course, I copied the certificate/keys to the "wrong" location.... yay.

So PEBKAC. Should have checked the mounted volume content before, sorry!

**Comment by irhawks** [comment]
@cjeanneret Hi, I'm trying to integrate FreeIPA LDAP Authentication with Minio STS Service based on https://github.com/minio/minio/blob/master/docs/sts/ldap.md (This article may use OpenLDAP instead of FreeIPA). However it does not work. I think this is due to some mistakes in configuration but I cannot find why minio cannot connect freeipa via ldaps. Here is my docker-compose.yml:

```
version: '3'
services:
  ipa:
    image: freeipa/freeipa-server
    restart: unless-stopped
    hostname: ipa.example.org
    domainname: ""
    command: ipa-server-install
    environment:
      - PASSWORD=admin123
    tty: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./ipa-data:/data:Z
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    command:
      - -U 
      - --domain=example.org
      - --realm=example.org
      - --ds-password=admin123
      - --admin-password=admin123
      - --no-ntp
      - --no-host-dns
      - --no-dnssec-validation
      - --setup-dns
      - --allow-zone-overlap
      - --no-forwarders
  minio:
    image: minio/minio:RELEASE.2020-03-09T18-26-53Z
    ports:
      - "9000:9000"
    command: server /data
    environment:
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=admin123
      - MINIO_IDENTITY_LDAP_SERVER_ADDR="ipa:636"
      - MINIO_IDENTITY_LDAP_USERNAME_FORMAT="uid={username},cn=users,cn=accounts,dc=example,dc=org"
      - MINIO_IDENTITY_LDAP_GROUP_SEARCH_BASE_DN="dc=example,dc=org"
      - MINIO_IDENTITY_LDAP_GROUP_SEARCH_FILTER="(&(objectclass=person)(memberOf={usernamedn}))"
      - MINIO_IDENTITY_LDAP_GROUP_NAME_ATTRIBUTE="cn"
      - MINIO_IDENTITY_LDAP_STS_EXPIRY=60h
      - MINIO_IDENTITY_LDAP_TLS_SKIP_VERIFY=on
```

I'm hoping that you can provide some debug options and test commands to check if minio have successfully integrated with freeipa, such as `ldap.status` info shown in `mc admin --json info minio`.
