### ISSUE TITLE
S3 Gateway Disk Caching seems to be broken?

### ISSUE THREAD

**Issue by baka-yuki** [minio/minio#7325]
## Expected Behavior

Uploading/Downloading a file through the Minio browser client should result in the file being stored in disk cache.

## Current Behavior

Uploading/Downloading a file functions, but bypasses cache. Nothing is added to the cache pool.

## Possible Solution

No idea.

## Steps to Reproduce (for bugs)

1. Use `docker stack deploy` to bring up a minio instance similar to below:
```
version: '3.1'

services:
  # Define Minio Service for storage backend
  minio:
    image: minio/minio:RELEASE.2019-02-26T19-51-46Z
    volumes:
      - /srv/EXT/pool:/data
      - ./minio:/root/.minio
    ports:
      - "9000:9000"
    environment:
      - "MINIO_ACCESS_KEY_FILE=minio_s3_access_key"
      - "MINIO_SECRET_KEY_FILE=minio_s3_secret_key"
      - "MINIO_SSE_VAULT_APPROLE_ID=[...]"
      - "MINIO_SSE_VAULT_APPROLE_SECRET=[...]"
      - "MINIO_SSE_VAULT_ENDPOINT=http://vault:8200"
      - "MINIO_SSE_VAULT_KEY_NAME=archive"
      - "MINIO_SSE_VAULT_AUTH_TYPE=approle"
      - "MINIO_SSE_AUTO_ENCRYPTION=on"
      - "MINIO_CACHE_DRIVES=/data"
      - "MINIO_CACHE_EXPIRY=90"
      - "MINIO_CACHE_MAXUSE=90"
    command: gateway s3 https://s3.wasabisys.com
    restart: always
    secrets:
      - minio_s3_access_key
      - minio_s3_secret_key

secrets:
  minio_s3_access_key:
    external: true
  minio_s3_secret_key:
    external: true
```
2. Attempt to upload/download a file through the minio browser

## Context

Uploading/Downloading should result in files being created in the disk cache. No information is output to logs.

## Regression

Seems like it might be? Previously #6314 had a similar issue that was marked as resolved.

## Your Environment

* Version used (`minio version`):
```
[zyradyl@thoth Thoth]$ docker exec -it thoth_minio.1.nhyjul36203ibft37qkc99hjv minio version
Version: 2019-02-26T19:51:46Z
Release-Tag: RELEASE.2019-02-26T19-51-46Z
Commit-ID: 78d116c487278350406e8957d7d35e47caa963d6
```
* Environment name and version (e.g. nginx 1.9.1):
```
[zyradyl@thoth Thoth]$ docker version
Client:
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        774a1f4
 Built:             Thu Feb 28 06:33:21 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       774a1f4
  Built:            Thu Feb 28 06:02:24 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```
* `docker logs`
```
[zyradyl@thoth Thoth]$ docker logs thoth_minio.1.nhyjul36203ibft37qkc99hjv

Cache Capacity: 10 TiB Free, 10 TiB Total
Endpoint:  http://10.255.0.127:9000  http://10.0.19.10:9000  http://172.19.0.4:9000  http://127.0.0.1:9000

Browser Access:
   http://10.255.0.127:9000  http://10.0.19.10:9000  http://172.19.0.4:9000  http://127.0.0.1:9000

Object API (Amazon S3 compatible):
   Go:         https://docs.minio.io/docs/golang-client-quickstart-guide
   Java:       https://docs.minio.io/docs/java-client-quickstart-guide
   Python:     https://docs.minio.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.minio.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.minio.io/docs/dotnet-client-quickstart-guide
```

**Comment by poornas** [comment]
notice that you have KMS and auto encryption enabled - any object uploaded thru browser will be automatically encrypted. Objects that are encrypted will not be  saved to cache

**Comment by baka-yuki** [comment]
Interesting, I was not aware of this. Is there any way to use KMS & Cache together? I had assumed minio would write the encrypted object to cache and remote.

**Comment by poornas** [comment]
@zyradyl, currently this is not possible.

**Comment by harshavardhana** [comment]
It is a security risk, so we don't allow it.

**Comment by baka-yuki** [comment]
Fair, thanks so much! I will mark this as resolved.

**Comment by calclavia** [comment]
I'm running into a similar issue when using Minio as a gateway to Amazon S3 and `/mnt/cache` folder is empty even though I've downloaded files.

Is there an easy way to see what's in the cache or how much data is currently cached?

helm chart configs
```
# Custom Minio config on top of the Helm charts
image:
  tag: RELEASE.2019-06-19T18-24-42Z

s3gateway:
  enabled: true
  replicas: 1
  serviceEndpoint: "https://s3.amazonaws.com"

persistence:
  enabled: false

accessKey: ...
secretKey: ...

environment:
  MINIO_ACCESS_KEY: ...
  MINIO_SECRET_KEY: ...
  
  MINIO_CACHE_DRIVES: "/mnt/cache"
  MINIO_CACHE_EXPIRY: "90"
  MINIO_CACHE_MAXUSE: "70"
```
