### ISSUE TITLE
'TLS handshake error from 172.17.0.1:59810: remote error: tls: unknown certificate' error when using minio with https in kubernetes

### ISSUE THREAD

**Issue by fwwucn** [minio/minio#7480]
## Expected Behavior
Successfully call getPresignedObjectUrl with Java SDK.

## Current Behavior
Got an exception when calling getPresignedObjectUrl with Java SDK.
`Error: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

Error shown in the log of minio pod:
`2019-04-04 03:14:31.066233 I | http: TLS handshake error from 172.17.0.1:59810: remote error: tls: unknown certificate`

But MinIO Browser https://192.168.99.166:32000/ seems work well (show page successfully with my non-secure self-signed certificate).

## Steps to Reproduce (for bugs)
1. Deploy docker image minio/minio:latest without TLS, and confirmed that getPresignedObjectUrl works well.
2. Follow the [guide](https://github.com/minio/minio/tree/master/docs/tls/kubernetes) to generate a self signed certificate with openssl.conf:
```
[req]
distinguished_name = req_distinguished_name
x509_extensions = v3_req
prompt = no

[req_distinguished_name]
C = US
ST = VA
L = Somewhere
O = MyOrg
OU = MyOU
CN = localhost

[v3_req]
subjectAltName = @alt_names

[alt_names]
IP.1 = 192.168.99.166
```
`openssl req -x509 -nodes -days 730 -newkey rsa:2048 -keyout private.key -out public.crt -config openssl.conf`
`kubectl create secret generic tls-ssl-minio --from-file=private.key --from-file=public.crt`
I confirmed that tls-ssl-minio secret created successfully, and included 2 items: private.key and public.crt in its Data.

3. Update minio-deployment.yaml as below:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: minio
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio
    spec:
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: minio-pv-claim
        - name: secret-volume
          secret:
            secretName: tls-ssl-minio
            items:
              - key: public.crt
                path: public.crt
              - key: private.key
                path: private.key
              - key: public.crt
                path: CAs/public.crt
      containers:
        - name: minio
          image: minio/minio
          args:
            - server
            - /storage
          env:
            - name: MINIO_ACCESS_KEY
              value: "xxxxx"
            - name: MINIO_SECRET_KEY
              value: "xxxxxxxx"
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: storage # must match the volume name, above
              mountPath: "/storage"
            - name: secret-volume
              mountPath: /root/.minio/certs
```

4. Rerun my program to call getPresignedObjectUrl, it throws the above exception.

## Context
My frontend and backend microservices are deployed via minikube on macOS, and use ingress controller to reverse proxy, so my apps used https with the default Kubernetes Ingress Controller Fake Certificate, which requires that my frontend to use minio presigned url with https, otherwise it will report error that calling http in https.

**Do I still need to copy private.key and public.crt into /root/.minio/certs in case of using self-signed certificate? If yes, how to copy into the pod in minikube?
In the [guide](https://github.com/minio/minio/tree/master/docs/tls/kubernetes), just mentioned that 'If you're using certificates provided by a CA, ...', how about in case of self-signed certificate? Is it still need to update this yaml?**

## My Environment
minio version shown in MinIO Browser:
```
VERSION
2019-03-27T22:35:21Z
MEMORY
Used: 7.9 MB | Allocated: 64 MB | Used-Heap: 7.9 MB | Allocated-Heap: 66 MB
PLATFORM
Host: minio-9d659d794-kmf4r | OS: linux | Arch: amd64
RUNTIME
Version: go1.12 | CPUs: 2
```
minikube: 1.0.0
kubectl: 1.14.0
OS: macOS 10.14.3

**Comment by nitisht** [comment]
can you log on to the MinIO container and verify if the certs and keys are stored at expected locations. Specially if `/root/.minio/certs/CAs` has the same `public.crt` file that you created

**Comment by fwwucn** [comment]
@nitisht Seems has the same public.crt.
```
$ kubectl exec minio-9d659d794-xb8xm -- ls -la /root/.minio/certs
total 4
drwxrwxrwt    3 root     root           140 Apr  4 05:48 .
drwxr-xr-x    3 root     root          4096 Apr  4 05:48 ..
drwxr-xr-x    3 root     root           100 Apr  4 05:48 ..2019_04_04_05_48_08.001120324
lrwxrwxrwx    1 root     root            31 Apr  4 05:48 ..data -> ..2019_04_04_05_48_08.001120324
lrwxrwxrwx    1 root     root            10 Apr  4 05:48 CAs -> ..data/CAs
lrwxrwxrwx    1 root     root            18 Apr  4 05:48 private.key -> ..data/private.key
lrwxrwxrwx    1 root     root            17 Apr  4 05:48 public.crt -> ..data/public.crt

$ kubectl exec minio-9d659d794-xb8xm -- ls -la /root/.minio/certs/..2019_04_04_05_48_08.001120324
total 8
drwxr-xr-x    3 root     root           100 Apr  4 05:48 .
drwxrwxrwt    3 root     root           140 Apr  4 05:48 ..
drwxr-xr-x    2 root     root            60 Apr  4 05:48 CAs
-rw-r--r--    1 root     root          1708 Apr  4 05:48 private.key
-rw-r--r--    1 root     root          1241 Apr  4 05:48 public.crt

$ kubectl exec minio-9d659d794-xb8xm -- ls -la /root/.minio/certs/..2019_04_04_05_48_08.001120324/CAs
total 4
drwxr-xr-x    2 root     root            60 Apr  4 05:48 .
drwxr-xr-x    3 root     root           100 Apr  4 05:48 ..
-rw-r--r--    1 root     root          1241 Apr  4 05:48 public.crt
```

And also view the content of both public.crt, they are totally same.
```
$ kubectl exec minio-9d659d794-xb8xm -- cat /root/.minio/certs/..2019_04_04_05_48_08.001120324/public.crt
$ kubectl exec minio-9d659d794-xb8xm -- cat /root/.minio/certs/..2019_04_04_05_48_08.001120324/CAs/public.crt
```

**Comment by nitisht** [comment]
can you try connecting to this MinIO instance with `mc` - you may need to use the `--insecure` flag..

**Comment by fwwucn** [comment]
Yes, I can connect with `--insecure`, but no clue found.
```
$ mc config host add minio https://192.168.99.166:32000 minio minio123 --insecure
Added `minio` successfully.
$ mc ls minio --insecure
[2019-04-03 23:55:22 CST]      0B 00000001/
```

Or do you have other approaches (TLS way is not my purpose) or best practice, to let a HTTPS web app access a VALID presigned HTTPS url generated by minio in k8s?
My web app (also deployed in k8s) wants to use presigned url to upload/download file, so it calls its 'storage service' to get a presigned url from minio. 

My original solution is that:
The 'storage service' is deployed to connect minio service in k8s like this (deployment file):
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: storage
spec:
  template:
    metadata:
      labels:
        app: storage
    spec:
      containers:
        - name: storage
          image: storage-service:0.0.1
          env:
            - name: MINIO_ENDPOINT
              value: "http://minio:9000"
...
```
Because minio endpoint is specified as `http://minio:9000`, which means directly access with service name since 'storage service' and minio are in the same namespace of the same cluster node, the format of presigned url generated by minio will be `http://minio:9000/$(bucket-name)/$(filename)?...`. The problem is that, this kind of url can not be resolved by my web app (although my web app and minio are also in the same namespace of the same node, DNS seems not work). If I replace minio:9000 with the external endpoint IP, signature verification will be failed.

In fact, I faced the same problem as [this issue](https://github.com/minio/minio/issues/6853#issuecomment-463298285), it is still not resolved and I can't figure out a solution, so I'm trying TLS way as a workaround, that is to expose minio as an external endpoint as https://192.168.99.166:32000 to be accessed by both web app and storage service, but I was taken into this TLS handshake error again.

**Comment by fwwucn** [comment]
For those who has the similar issue:
I resolved the error 'The request signature we calculated does not match the signature you provided. Check your key and signing method.' just by setting Host in header. (tested on minikube 1.0.0 & kubectl 1.14.0)

Please follow the 2 steps: 
1. No need to deploy minio with https, just use http and replace the original presigned url generated by minio like `http://minio:9000/${bucketName}/...` with your ingress minio path like `https://${YOUR_MINIKUBE_IP}/minio` in your backend service.

2. Use more_set_input_headers instead of proxy_set_header.
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-minio
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_input_headers 'Host: minio:9000';
spec:
  rules:
    - http:
        paths:
          - path: /minio/?(.*)
            backend:
              serviceName: minio
              servicePort: 9000
```
