### ISSUE TITLE
Registry with minio cluster no works

### ISSUE THREAD

**Issue by revengel** [minio/minio#7748]
I have some minio cluster on 4 servers. Minio items running in docker and connect by overlay network.

```yaml
version: '3.7'

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "5"

x-deploy:
  &default-deploy
  endpoint_mode: vip
  restart_policy:
    condition: on-failure
    delay: 10s
    max_attempts: 10
    window: 60s
  update_config:
    order: start-first
    parallelism: 2
    delay: 10s


x-service-minio-proto: &service-minio-proto
  image: minio/minio:edge
  logging: *default-logging
  command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export
  environment:
    MINIO_ACCESS_KEY: "some_access_key"
    MINIO_SECRET_KEY: "some_secret_key"
    MINIO_REGION: "us-east-1"
  healthcheck:
    disable: true

services:
    minio1:
    <<: *service-minio-proto
    hostname: minio1
    volumes:
      - /data/volumes/minio-data1/_data:/export
    deploy:
      << : *default-deploy
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.minio1 == true


  minio2:
    <<: *service-minio-proto
    hostname: minio2
    volumes:
      - /data/volumes/minio-data2/_data:/export
    deploy:
      << : *default-deploy
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.minio2 == true


  minio3:
    <<: *service-minio-proto
    hostname: minio3
    volumes:
      - /data/volumes/minio-data3/_data:/export
    deploy:
      << : *default-deploy
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.minio3 == true


  minio4:
    <<: *service-minio-proto
    hostname: minio4
    volumes:
      - /data/volumes/minio-data4/_data:/export
    deploy:
      << : *default-deploy
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.minio4 == true
```

When I published the port of the Minio items and connected the registry to some Minio address by the server’s IP address and the published port. And the registry works well. But if this server down the registry will not work too. So we need some reverse proxy that will combine all minio items. For this I using haproxy with config:
```haproxy
       listen minio
          bind *:9000
          log global
          mode http
          balance roundrobin
          option forwardfor
          option httplog
          option httpchk GET /minio/health/ready HTTP/1.0
          http-check expect rstatus 200
          server minio1 minio1:9000 resolvers docker check cookie minio1 inter 30000
          server minio2 minio2:9000 resolvers docker check cookie minio2 inter 30000
          server minio3 minio3:9000 resolvers docker check cookie minio3 inter 30000
          server minio4 minio4:9000 resolvers docker check cookie minio4 inter 30000
```

Also I tried use nginx. But **registry no works**. This is output:
```
The push refers to repository [localhost:20555/ubuntu]
8d267010480f: Retrying in 4 seconds 
270f934787ed: Retrying in 4 seconds 
02571d034293: Pushing [================================>                  ]  45.96MB/69.86MB
dial tcp 192.168.31.31:9380: connect: no route to host
```

Proxy from minio cookbook no works too. **How proxy must be configured for my task?**
Thanks
