### ISSUE TITLE
[gateway-gcs?] Minio ENV VARs from k8s secrets ref, 

### ISSUE THREAD

**Issue by verdverm** [minio/minio#7750]
## Expected Behavior

In Kubernetes, Minio keys should work when injected as ENV VARS via the secretKeyRef.

## Current Behavior

When specifying the Minio keys via secretKeyRef, attempting to use them via the browser or CLI returns "The access key ID you provided does not exist in our records"

When injected as regular env vars, everything works as expected.

Under both setups, the Minio ENV vars are the same:

```
$ kubectl exec -it minio-gcs-gateway-74bc9798b7-c85dv sh
/ # env | grep MINIO
MINIO_GCS_GATEWAY_SERVICE_HOST=10.60.8.22
MINIO_ACCESS_KEY_FILE=access_key
MINIO_GCS_GATEWAY_PORT_9000_TCP=tcp://10.60.8.22:9000
MINIO_GCS_GATEWAY_SERVICE_PORT=9000
MINIO_GCS_GATEWAY_PORT=tcp://10.60.8.22:9000
MINIO_ACCESS_KEY=minio
MINIO_UPDATE=off
MINIO_SECRET_KEY_FILE=secret_key
MINIO_SECRET_KEY=minio123
MINIO_GCS_GATEWAY_SERVICE_PORT_HTTP=9000
MINIO_GCS_GATEWAY_PORT_9000_TCP_ADDR=10.60.8.22
MINIO_GCS_GATEWAY_PORT_9000_TCP_PORT=9000
MINIO_GCS_GATEWAY_PORT_9000_TCP_PROTO=tcp
```

## Steps to Reproduce (for bugs)
1. Deploy to GKE, GCS, in gateway mode (minio files below)
2. kubectl port-forward <minio-gcs-pod-name> 9000
3. test that login works
4. swap the minio ENV VAR to use secretKeyRef
5. port-forward the new pod
6. See the login error

## Context

We would like to specify the Minio secrets via the Kubernetes Secrets system. This keeps the values out of deployment files and git.

## Regression

?

## Your Environment

deployment.yaml

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-gcs-gateway
  labels:
    app: minio-gcs-gateway
spec:
  selector:
    matchLabels:
      app: minio-gcs-gateway

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 5

  template:
    metadata:
      labels:
        app: minio-gcs-gateway
        foo: goo
    spec:
      containers:

      - name: minio
        image: minio/minio:RELEASE.2019-06-04T01-15-58Z
        args:
          - gateway
          - gcs
          - my-gcs-bucket
        env:
          - name: MINIO_ACCESS_KEY
            value: minio
          - name: MINIO_SECRET_KEY
            value: minio123
          # - name: MINIO_ACCESS_KEY
          #   valueFrom:
          #     secretKeyRef:
          #       name: minio-secrets
          #       key: MINIO_ACCESS_KEY
          # - name: MINIO_SECRET_KEY
          #   valueFrom:
          #     secretKeyRef:
          #       name: minio-secrets
          #       key: MINIO_SECRET_KEY
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: "/secrets/minio/credentials.json"
        ports:
        - containerPort: 9000

        volumeMounts:
          - name: minio-gcs-creds
            mountPath: /secrets/minio
            readOnly: true

      volumes:
      - name: minio-secrets
        secret:
          secretName: minio-secrets
      - name: minio-gcs-creds
        secret:
          secretName: minio-gcs-creds
```

minio-secrets.yaml

```
kind: Secret
apiVersion: v1
metadata:
  name: minio-secrets
type: Opaque
data:
  MINIO_ACCESS_KEY: bWluaW8K
  MINIO_SECRET_KEY: bWluaW8xMjMK
```
