### ISSUE TITLE
PutObjectRequest Unable to unmarshall response (Java 2 SDK)

### ISSUE THREAD

**Issue by kmualem** [minio/minio#7756]
## Expected Behavior

I would like to succesfully put an object in the bucket, while I'm using the AWS java2 SDK and minIO

## Current Behavior

I'm getting an exception while sending PutObjectRequest using the AWS Java2 SDK.
The exception is:
software.amazon.awssdk.core.exception.SdkClientException: Unable to unmarshall response (Invalid base 16 character: '-'). Response Code: 200, Response Text: OK

## Possible Solution

I noticed that the response that retured from the minIO contains ETag with '-' which then failed in the SDK code while decoding the ETag value to base16:
`byte[] ssHash = Base16Lower.decode(response.eTag().replace("\"", ""));`

In the response I see:
`"ETag: "767e97689fb29ddb7c6ac1229510c144-1"`

## Steps to Reproduce (for bugs)

s3Client.putObject(PutObjectRequest.builder().bucket(bucketName).key(fullFilePath).build(),
                RequestBody.fromBytes(bytes))

## Context

The probelm is super critical for us, because we're not able to use minIO currently in our environment due to the putObject failure.

## Regression

I don't know... I'm new to minIO.

## Your Environment

* Version used (`RELEASE.2019-06-04T01-15-58Z`):
* AWS JAVA SDK 2.5.51
* Operating System and version (`windows 10`):
* Link to your project:

**Comment by nitisht** [comment]
Thanks for reporting @kmualem we'll take a look

**Comment by harshavardhana** [comment]
If you want ETag to be md5sum then run MinIO in --compat mode, this is expected behavior by default.

**Comment by kmualem** [comment]
Thanks @nitisht @harshavardhana for your response!

@harshavardhana - I didn't want a special setting for the PutObjectRequest that I made, but just to upload a simple file to a bucket using the MinIO and updated java SDK of AWS

I'm running the MinIO in a docker container, image version RELEASE.2019-06-04T01-15-58Z
I don't have any special configuration in the docker-compose

Does the '-' character inside the Etag response was also in the previous MinIO versions ? or this is new? 
I don't know why the java SDK is checking the md5sum... but it seems that it expects to have base16 Etag and that's not the case with the MinIO response.

Can you please advise?

**Comment by harshavardhana** [comment]
> I don't know why the java SDK is checking the md5sum... but it seems that it expects to have base16 Etag and that's not the case with the MinIO response.

yes It is a new change where we don't compute md5sum for ETag if the client doesn't set Content-Md5   if you want md5sum ETag without Content-Md5 set by the client then start MinIO in `minio server --compat` mode.

**Comment by kmualem** [comment]
Can I configure it inside the docker-compose?

**Comment by harshavardhana** [comment]
Yes definitely paste your docker-compose example? @kmualem

**Comment by kmualem** [comment]
I can't paste it now because I'm not near my development environment...

**Comment by kmualem** [comment]
My current docker-compose is very basic... so, It will be great if you can just tell me where should I locate the compact settings.

Thanks for your help!

**Comment by harshavardhana** [comment]
All you need is this

```yml
version: '2'

# starts 4 docker containers running minio server instances. Each
# minio server's web interface will be accessible on the host at port
# 9001 through 9004.
services:
 minio1:
  image: minio/minio:RELEASE.2019-06-04T01-15-58Z
  volumes:
   - data1:/data
  ports:
   - "9001:9000"
  environment:
   MINIO_ACCESS_KEY: minio
   MINIO_SECRET_KEY: minio123
  command: server --compat http://minio1/data http://minio2/data http://minio3/data http://minio4/data 
 minio2:
  image: minio/minio:RELEASE.2019-06-04T01-15-58Z
  volumes:
   - data2:/data
  ports:
   - "9002:9000"
  environment:
   MINIO_ACCESS_KEY: minio
   MINIO_SECRET_KEY: minio123
  command: server --compat http://minio1/data http://minio2/data http://minio3/data http://minio4/data 
 minio3:
  image: minio/minio:RELEASE.2019-06-04T01-15-58Z
  volumes:
   - data3:/data
  ports:
   - "9003:9000"
  environment:
   MINIO_ACCESS_KEY: minio
   MINIO_SECRET_KEY: minio123
  command: server --compat http://minio1/data http://minio2/data http://minio3/data http://minio4/data 
 minio4:
  image: minio/minio:RELEASE.2019-06-04T01-15-58Z
  volumes:
   - data4:/data
  ports:
   - "9004:9000"
  environment:
   MINIO_ACCESS_KEY: minio
   MINIO_SECRET_KEY: minio123
  command: server --compat http://minio1/data http://minio2/data http://minio3/data http://minio4/data 

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  data1:
  data2:
  data3:
  data4:
```
