### ISSUE TITLE
Use of su-exec now requires container be started as root

### ISSUE THREAD

**Issue by jtackaberry** [minio/minio#7773]
As of RELEASE.2019-06-11T00-44-33Z, minio now fails to run in my environment.  Regression ostensibly introduced by #7569.

```
# docker-compose  up
Recreating minio ...
Recreating minio ... done
Attaching to minio
minio    | su-exec: setgroups(1001): Operation not permitted
minio exited with code 1
```

Given this `docker-compose.yaml`:

```yaml
minio:
 container_name: minio
 restart: always
 image: minio/minio:RELEASE.2019-06-11T00-44-33Z
 user: "1001:1001"
 command: minio server /data
 ports:
 - 9000:9000/tcp
 environment:
    HOME: /tmp
    MINIO_HTTP_TRACE: /data/minio.log
 volumes:
 - /home/minio/data:/data
 - /home/minio/config:/tmp/.minio
```
Here, Docker takes care of launching the container as uid 1001.  Minio's attempt to drop privileges ironically fails because it starts unprivileged.
