### ISSUE TITLE
Healthcheck fails when using a docker network.

### ISSUE THREAD

**Issue by nopjmp** [minio/minio#7780]
I'm running minio using a docker network with traefik in front of it.

## Expected Behavior
healthcheck returns 0

## Current Behavior
healthcheck returns 1
2019/06/12 23:27:48 Get http://127.0.0.11:38673/minio/health/live: EOF

## Possible Solution
root@tohru:/srv/traefik# docker exec services_minio_1 healthcheck
2019/06/12 23:27:48 Get http://127.0.0.11:38673/minio/health/live: EOF
root@tohru:/srv/traefik# docker exec services_minio_1 netstat -ntlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.11:38673        0.0.0.0:*               LISTEN      -
tcp        0      0 :::9000                 :::*                    LISTEN      -

I believe the healthcheck script should be looking by port what something is listening on from the environment variables passed in by the user or the default port.

https://github.com/minio/minio/blob/b4ab778cb2e6b5a2425f226e4ac1febde334ab51/dockerscripts/healthcheck.go#L79-L101 

## Steps to Reproduce (for bugs)
Create a docker network
Create a minio instance attached to that network
Eventually the healthcheck will start to fail after the grace period.

## Context
root@tohru:/srv# docker exec services_minio_1 healthcheck
2019/06/12 23:27:48 Get http://127.0.0.11:38673/minio/health/live: EOF
root@tohru:/srv# docker exec services_minio_1 netstat -ntlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.11:38673        0.0.0.0:*               LISTEN      -
tcp        0      0 :::9000                 :::*                    LISTEN      -

## Your Environment

* minio/minio:RELEASE.2019-06-11T00-44-33Z
* Docker 18.09.6
* Ubuntu 18.04
* Linux tohru 5.0.0-16-generic #17~18.04.1-Ubuntu SMP Mon May 20 14:00:27 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by blackandred** [comment]
Having the same issue with image `e31e8933bba3`. The health check gives a bad status code, so my monitoring is keeping alerting me.

**Comment by infomaniac50** [comment]
> I'm running minio using a docker network with traefik in front of it.

Docker Compose adds a network by default even if you don't specify one in the configuration file. The Minio server doesn't die or anything like that. It just sits there saying it's unhealthy.

This is the configuration for my home server.

```yaml
version: '2'
services:
  server:
    image: minio/minio
    restart: always
    command: server /export
    ports:
      - '9000:9000'
    volumes:
      - './data:/data'
      - './export:/export'
      - './config:/root/.minio'
```

**Comment by nopjmp** [comment]
I understand that. I'm using a docker network for specific reasons on my host, primarily for routing traffic inside of an isolated network.

**Comment by jbub** [comment]
Worked around it by temporarily disabling the healthcheck in docker compose:

```
healthcheck:
  disable: true
```

**Comment by nitisht** [comment]
please use the `minio/minio:edge` image if possible till we make a release with the fix

**Comment by jbub** [comment]
I can wait for the release, its not a mission critical setup :) Thanks for all of the hard work on the project by the way :)

**Comment by blackandred** [comment]
Thanks for your good work on the project :)
I can also wait for a release, because I know the cause.
What suprises me is that the monitoring says that one time a day the
service is ok for a few minutes :)

**Comment by n-pat** [comment]
> please use the `minio/minio:edge` image if possible till we make a release with the fix

Hi, minio/minio:edge still has this problem for me. Just as a feedback, but I will try again with newer version.

I have an internal network that connects to my reverse-proxy but everything else looks like in the szenario in this ticket.

To my setup: similar docker network, AMD64, docker 19.03.1, debian 10.0.

The error msg appers after 5-10 minutes. Workaround to disable healthcheck helps.

For completeness:
```
version: '2.1'

services:
  rinio:
    container_name: rinio
    image: minio/minio:edge
    networks:
      - lan-traefik-backbone
    environment:
      - MINIO_ACCESS_KEY=${RINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${RINIO_SECRET_KEY}
      - MINIO_DOMAIN=${RINIO_DOMAIN}
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=HostRegexp:${RINIO_DOMAIN},{subdomain:.*}.${RINIO_DOMAIN}"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.port=9000"
      #- "traefik.docker.network=lan-traefik-backbone"
    volumes:
      - '/rinio/data5:/data1'
      - '/rinio/data6:/data2'
      - '/rinio/data7:/data3'
      - '/rinio/data8:/data4'
    #healthcheck:
    #  disable: true
    restart: always
    command: ["server", "/data{1...4}"]

networks:
  lan-traefik-backbone:
    external: true
```
```
version: '2'

volumes:
  acme_data:
    external: true

services:
  proxy:
    container_name: reverse-proxy
    image: traefik:latest
    restart: always
    ports:
      - "8080:8080"
      - "443:443"
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik:/etc/traefik
      - acme_data:/etc/traefik/acme/
    environment:
      - "TZ=Europe/Berlin"
      - DNS_CUSTOMER_NUMBER
      - DNS_API_KEY
      - DNS_API_PASSWORD
    networks:
      - lan-traefik-backbone

networks:
  lan-traefik-backbone:
    external: true
```
