### ISSUE TITLE
change access key deletes files

### ISSUE THREAD

**Issue by HeberArratia** [minio/minio#7790]
## Expected Behavior

When changing MINIO_ACCESS_KEY and MINIO_SECRET_KEY, the files that min.io showed me with a previous access configuration disappear.

Is there any way to avoid this behavior? 
I think the archives should be maintained.

## Current Behavior

Files are lost when you modify the keys.

## Context

I'm using docker-compose

## Your Environment

My docker-compose file:

```
minio:
      image: minio/minio
      hostname: minio1
      container_name: minio
      ports:
      - "9000:9000"
      environment:
      - MINIO_ACCESS_KEY=ex123
      - MINIO_SECRET_KEY=example123
      volumes:
      - ~/mnt/data:/data
      - ~/mnt/config:/root/.minio
      networks:
      - backend
      command: server /export
```
