### ISSUE TITLE
minio/minio:RELEASE.2019-06-15T23-07-18Z claims atime is not set

### ISSUE THREAD

**Issue by k0da** [minio/minio#7829]
After updating to minio/minio:RELEASE.2019-06-15T23-07-18Z minio fails to start with:
Jun 25 11:34:50 172.19.0.1 s3cache[3432]: ERROR Unable to initialize disk caching: Atime support required for disk caching.

while:
  minio-cache:
    image: minio/minio:RELEASE.2019-06-15T23-07-18Z
    container_name: s3cache
    networks:
      - harbor
    volumes:
      - /mnt/s3cache:/cache:z

/dev/vdb on /mnt type ext4 (rw,relatime,seclabel,nobarrier,commit=30,data=ordered)

**Comment by nitisht** [comment]
Thanks for reporting @k0da we'll take a look

**Comment by poornas** [comment]
@koda, can you enable `strictatime` on the drive you are using for cache? [relatime](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/power_management_guide/relatime) does not necessarily update atime each time the file is accessed.

**Comment by k0da** [comment]
@poornas just tested this, minio still complains about no atime
/dev/vdb	/mnt	ext4	strictatime,barrier=0,commit=30,user_xattr,acl	0	0

mount | grep vdb
/dev/vdb on /mnt type ext4 (rw,seclabel,nobarrier,commit=30,data=ordered)

s3cache[3432]: ERROR Unable to initialize disk caching: Atime support required for disk caching.

**Comment by poornas** [comment]
Can you do a `stat filename` on a existing file in /mnt/ path, `cat filename` then try stat to see access time changed? We essentially do that to ensure atime is enabled - otherwise older cached entries cannot be evicted reliably. Perhaps you need to remount?

**Comment by k0da** [comment]
yes, access time changes
```  File: ‘/mnt/filename’
  Size: 0         	Blocks: 0          IO Block: 4096   regular empty file
Device: fd10h/64784d	Inode: 12          Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Context: unconfined_u:object_r:mnt_t:s0
Access: 2019-06-25 22:12:44.444604239 +0200
Modify: 2019-06-25 22:12:44.444604239 +0200
Change: 2019-06-25 22:12:44.444604239 +0200
 Birth: -
```
 vs 
```  File: ‘/mnt/filename’
  Size: 0         	Blocks: 0          IO Block: 4096   regular empty file
Device: fd10h/64784d	Inode: 12          Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Context: unconfined_u:object_r:mnt_t:s0
Access: 2019-06-25 22:13:01.707705485 +0200
Modify: 2019-06-25 22:12:44.444604239 +0200
Change: 2019-06-25 22:12:44.444604239 +0200
 Birth: -
```

**Comment by k0da** [comment]
@poornas I did remount and reboot node as well. + I do docker system prune before each attempt to start minio container

**Comment by poornas** [comment]
@koda, can you paste your docker-compose.yml here? In partcular would like to see  MINIO_CACHE_DRIVES env setting.

**Comment by k0da** [comment]
@poornas 
```
version: '2.3'
services:
  minio-cache:
    image: minio/minio:RELEASE.2019-06-15T23-07-18Z
    container_name: s3cache
    networks:
      - harbor
    volumes:
      - /mnt/s3cache:/cache:z
    ports:
      - "9000:9000"
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "s3cache"
    environment:
      - MINIO_ACCESS_KEY=<%=@harbor_s3_accesskey%>
      - MINIO_SECRET_KEY=<%=@harbor_s3_secretkey%>
      - MINIO_CACHE_DRIVES=/cache
      - MINIO_CACHE_EXPIRY=30
      - MINIO_CACHE_MAXUSE=80
    command: minio gateway s3
```
