### ISSUE TITLE
Infinite redirects when aliasing a path

### ISSUE THREAD

**Issue by ForsakenHarmony** [minio/minio#7851]
I use `i.hrmny.sh` as an alias to `s3.hrmny.sh/shr` (not dns level, reverse proxy adds the path to it)

## Expected Behavior
It should not endlessly redirect

## Current Behavior
The permission to list file in the folder is denied for everyone, so it denies access.
Then it tries to redirect to `i.hrmny.sh/minio/shr`, but that internally changes the path to `/shr/minio/shr` -> `/shr/minio/shr/minio/shr` -> `/shr/minio/shr/minio/shr/minio/shr` ......

## Possible Solution
Redirect to the domain given via `MINIO_DOMAIN`, maybe detect that the path already contains `/mino/...`

Also disable redirects by default, I'd rather have the access denied message (even if the browser is on)

## Steps to Reproduce (for bugs)
Alias in some way to prevent access to `/minio`

## Regression
It's a regression, probably from whenever redirects were introduced, don't know when that was

## Your Environment
* Version used (`minio version`): [`minio/minio:latest` from `June 27, 2019 11:43 PM`](https://i.hrmny.sh/iVgdjrAnVV.png) , probably `RELEASE.2019-06-27T21-13-50Z`
* Environment name and version: traefik with `"traefik.i.frontend.rule=Host:i.hrmny.sh;AddPrefix:/shr"`
* Server type and version: docker?

**Comment by harshavardhana** [comment]
Can you share your reverse proxy configuration?

**Comment by ForsakenHarmony** [comment]
It's that label for a docker container

Most important part being the `AddPrefix`

**Comment by harshavardhana** [comment]
Unfortunately I am not that savvy in docker terminologies, it would be beneficial if you can share your docker configs for MinIO container

**Comment by ForsakenHarmony** [comment]
you don't really need to know more than that the reverse proxy appends `/shr` to the path

but here you go
<details>
<summary>docker-compose.yml</summary>

```yml
version: '2'
services:
  block:
    image: minio/minio:latest
    command: minio server /data
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.s3.frontend.rule=Host:s3.hrmny.sh"
      - "traefik.i.frontend.rule=Host:i.hrmny.sh;AddPrefix:/shr"
    environment:
      MINIO_ACCESS_KEY: ""
      MINIO_SECRET_KEY: ""
      MINIO_REGION: hrmny
      MINIO_DOMAIN: s3.hrmny.sh
    volumes:
      - ./data:/data
      - ./config:/root/.minio

networks:
  web:
    external:
      name: traefik_webgateway
```

</details>
