### ISSUE TITLE
When Minio starts, it takes a lot of time to change the permissions of the file directory

### ISSUE THREAD

**Issue by shamartor** [minio/minio#7864]
Hi,I use docker to run Minio instances (in k8s) on shared NAS volumes as object gateways and share 13TB of data on NAS volumes, which are held by no-root users. At the same time, I set MINIO_USERNAME and MINIO_GROUPNAME as root (because volumes are held by root users in the production environment), and then we found that Minio instances have been changing directory permissions for shared volumes for a long time. I think the source file will decide whether to update directory permissions based on the existence of the “.minio.sys” folder. If I create this folder manually, can I guarantee Minio in the future? Or can you tell me how I should start in the most appropriate way? Thank you！
## Expected Behavior

Quick start when the amount of data is large

## Current Behavior

It takes a lot of time to change the permissions of the file directory

## Steps to Reproduce (for bugs)

This is my resource profile in k8s.
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: storage-minio
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: storage-minio
        component: minio
    spec:
      volumes:
      - name: local-ghome
        hostPath:
          path: "/ghome"
      containers:
      - name: storage-minio
        image: minio/minio:RELEASE.2019-06-19T18-24-42Z
        args:
        - gateway
        - nas
        - /ghome
        env:
        - name: MINIO_ACCESS_KEY
          value: "MINIO_ACCESS_KEY"
        - name: MINIO_SECRET_KEY
          value: "MINIO_SECRET_KEY"
        - name: MINIO_USERNAME
          value: "root"
        - name: MINIO_GROUPNAME
          value: "root"
        ports:
        - containerPort: 9000
          name: client
        volumeMounts:
        - name: local-ghome
          mountPath: "/ghome"
```

## Your Environment

* minio/minio:RELEASE.2019-06-19T18-24-42Z
* docker community 18.09.5
* kubernetes v1.13.5
* ubuntu 16.04
