### ISSUE TITLE
[not our bug] The request signature we calculated does not match the signature you provided. Check your key and signing method.

### ISSUE THREAD

**Issue by ricardolimaui** [minio/minio#7936]
Hello all. To be honest I don't know if the problem is from the Minio or the mc connecting to the api.
Initially I created a docker-compose with 

```
version: '3'
services:
  minio_s3:
    image: minio/minio
    container_name: minio_s3
    ports:
      - 9100:9000
    environment:
      - MINIO_ACCESS_KEY=accesskey
      - MINIO_SECRET_KEY=secretkey
    volumes:
      - DATA_MINIO:/data
      - ROOT_MINIO:/root/.minio
    command: [ "server", "/data"]
    expose:
      - "9100"


volumes:
  DATA_MINIO:
  ROOT_MINIO:
```

Now the problem is, if I use it without tls the mc is able to connect to Minio and do the job. But if I insert the crt and key files the Minio becomes secure and I can access it through the browser with ssl (I was also able to access without ssl) and the mc gives the error mentioned in the title .. 
To connect to the minio I use 
`./mc config host add minio https://domain.com Accesskeysecretkey --api s3v4`
I don't use the :port because the address are being redirect to the right port

Any ideia ? thank you
