### ISSUE TITLE
Kubernetes+Minikube with resource limits OOM(Out of Memory) when uploading 

### ISSUE THREAD

**Issue by ox-michaelradionov** [minio/minio#7962]
I have a local Kubernetes cluster inside Minikube on my Mac. I deploy a Minio standalone server as a single container with resource limits specified. When I upload a file which is larger than container memory limit, the container is terminated with reason `OOMKilled`.

I am not sure whether it is a Minio issue or environment I am running it in. Similar setup on Ubuntu seems to be working fine.

I've posted a [question on StackOverflow](https://stackoverflow.com/questions/57143001/minio-oomout-of-memory-when-uploading-a-file) with the same content, but maybe you could also point me in the right direction, because it seems to be Minio-specific.

## Expected Behavior

I expect Minio to function within provided limits and not consume memory equal to file size.

## Current Behavior

Container is limited to 256 MB of memory and 0.5 CPU using Kubernetes configuration. I am wondering if these resources are ok for Minio to perform correctly.

```
resources:
  requests:
    cpu: '500m'
    memory: '256Mi'
  limits:
    cpu: '500m'
    memory: '256Mi'
```

I open Minio dashboard, select a bucket and upload a 1 GB file. After about ~250 MB are uploaded, I get an error in Minio dashboard. Playing with limits and analyzing Heapster graphs I can see a correlation between file size and memory usage. Container uses exactly the same amount of memory equal to file size, which is weird to me. My impression is that file won't be stored directly in memory during file upload.

## Possible Solution

Not sure

## Steps to Reproduce (for bugs)

Minikube is running in VirtualBox and configured to use 4GB of memory. I also use Heapster and Metric Server to check memory usage over time.

```bash
$ minikube config set memory 4096
$ minikube addons enable heapster
$ minikube addons enable metrics-server
$ minikube start
```

![image](https://user-images.githubusercontent.com/19311309/61643714-1b119400-acac-11e9-8140-860ecd327ec8.png)

I use a slightly modified version of [Kubernetes confiuration for Minio standalone setup provided in Minio documentation](https://docs.min.io/docs/deploy-minio-on-kubernetes.html#minio-standalone-server-deployment). I create PV and PVC for storage, Deployment and Service for Minio server. Container configuration:

- Using official Minio Docker image
- Using initContainer to create a bucket

Full `videos-storage.yaml`

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: videos-storage-pv
  labels:
    software: minio
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/storage-videos/

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: videos-storage-pv-claim
spec:
  storageClassName: ''
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      software: minio

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: videos-storage-deployment
spec:
  selector:
    matchLabels:
      app: videos-storage
  template:
    metadata:
      labels:
        app: videos-storage
    spec:
      initContainers:
      - name: init-minio-buckets
        image: minio/minio
        volumeMounts:
        - name: data
          mountPath: /data/storage-videos
        command: ['mkdir', '-p', '/data/storage-videos/videos']
      containers:
      - name: minio
        image: minio/minio
        volumeMounts:
        - name: data
          mountPath: /data/storage-videos
        args:
        - server
        - /data/storage-videos
        env:
        - name: MINIO_ACCESS_KEY
          value: 'minio'
        - name: MINIO_SECRET_KEY
          value: 'minio123'
        ports:
        - containerPort: 9000
        resources:
          requests:
            cpu: '500m'
            memory: '256Mi'
          limits:
            cpu: '500m'
            memory: '256Mi'
        readinessProbe:
          httpGet:
            path: /minio/health/ready
            port: 9000
          initialDelaySeconds: 5
          periodSeconds: 20
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: 9000
          initialDelaySeconds: 5
          periodSeconds: 20
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: videos-storage-pv-claim

---

apiVersion: v1
kind: Service
metadata:
  name: videos-storage-service
spec:
  type: LoadBalancer
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: videos-storage
```

I deploy the config to the cluster:

```bash
$ kubectl apply -f videos-storage.yaml
```

and access Minio dashboard using Minikube, the following command opens it in browser:

```bash
$ minikube service videos-storage-service
```

Then I select a `videos` bucket and upload a 1 GB file. After about ~250 MB are uploaded, I get an error in Minio dashboard.

![image](https://user-images.githubusercontent.com/19311309/61643834-52804080-acac-11e9-80d2-e3650f3b04a5.png)

Minikube logs in `dmesg`:

```
[  +3.529889] minio invoked oom-killer: gfp_mask=0x14000c0(GFP_KERNEL), nodemask=(null), order=0, oom_score_adj=-998
[  +0.000006] CPU: 1 PID: 8026 Comm: minio Tainted: G           O     4.15.0 #1
[  +0.000001] Hardware name: innotek GmbH VirtualBox/VirtualBox, BIOS VirtualBox 12/01/2006
[  +0.000000] Call Trace:
[  +0.000055]  dump_stack+0x5c/0x82
[  +0.000010]  dump_header+0x66/0x281
[  +0.000006]  oom_kill_process+0x223/0x430
[  +0.000002]  out_of_memory+0x28d/0x490
[  +0.000003]  mem_cgroup_out_of_memory+0x36/0x50
[  +0.000004]  mem_cgroup_oom_synchronize+0x2d3/0x310
[  +0.000002]  ? get_mem_cgroup_from_mm+0x90/0x90
[  +0.000002]  pagefault_out_of_memory+0x1f/0x4f
[  +0.000002]  __do_page_fault+0x4a3/0x4b0
[  +0.000003]  ? page_fault+0x36/0x60
[  +0.000002]  page_fault+0x4c/0x60
[  +0.000002] RIP: 0033:0x427649
[  +0.000001] RSP: 002b:000000c0002eaae8 EFLAGS: 00010246
[  +0.000154] Memory cgroup out of memory: Kill process 7734 (pause) score 0 or sacrifice child
[  +0.000013] Killed process 7734 (pause) total-vm:1024kB, anon-rss:4kB, file-rss:0kB, shmem-rss:0kB
```

## Context

Developing microservice application. Want to use Minio as a storage. For development phase started with a standalone version running inside a container.

Initially the problem occurred when I did not have any resource limits. When I tried to upload a big file, container with Minio would use all of the memory available in the node, and because there is no memory left, Kubernetes services become unresponsive and it started killing other containers, like apiserver; and file won't upload either. After that I added resource limits to Minio container and cluster itself became stable, but Minio container still dies.

## Regression

Not sure

## Your Environment

- MacOS Mojave 10.14.5, 2.6 GHz Intel Core i5, 8 GB 1600 MHz DDR3
- Minikube v1.2.0
- VirtualBox 5.2.18 r124319
- kubectl v1.15.0
- Docker version 18.09.2, build 6247962
- Minio 2019-07-17T22:54:12Z (https://hub.docker.com/r/minio/minio)
