### ISSUE TITLE
Kubernetes: no persistent volumes available for this claim and no storage class is set

### ISSUE THREAD

**Issue by tobiasjpark** [minio/minio#7977]
I'm following the instructions from https://docs.min.io/docs/deploy-minio-on-kubernetes.html to install Minio on a single-node Kubernetes cluster. When I run the command 

`kubectl create -f https://github.com/minio/minio/blob/master/docs/orchestration/kubernetes/minio-standalone-pvc.yaml?raw=true`

the command executes successfully, but running `kubectl describe pvc minio-pv-claim` shows that the PVC is failing with the error `no persistent volumes available for this claim and no storage class is set`.

I'm not sure if I have to manually create a specific persistent volume and storage class in Kubernetes,  but I don't think that is the case as the documentation doesn't mention that as a prerequisite or state that I need to configure that myself. (In any case, my cluster does have a persistent volume and storage class set up separately).

## Expected Behavior

`minio-pv-claim` successfully binds to a persistent volume as intended.

## Current Behavior

`minio-pv-claim` stalls forever with the message `no persistent volumes available for this claim and no storage class is set`

## Steps to Reproduce (for bugs)

1. Set up a Kubernetes cluster and install kubectl
2. Run the command `kubectl create -f https://github.com/minio/minio/blob/master/docs/orchestration/kubernetes/minio-standalone-pvc.yaml?raw=true`

## Context

I am not able to proceed through the installation due to this issue.

## Regression
 No

## Your Environment

* Version used (`minio version`):  2.5.2
* Environment name and version (e.g. nginx 1.9.1): Kubernetes 1.15
* Server type and version: Ubuntu 18.04 
* Operating System and version (`uname -a`):
`Linux macallan 4.18.0-25-generic #26~18.04.1-Ubuntu SMP Thu Jun 27 07:28:31 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

* Link to your project:

**Comment by kannappanr** [comment]
@kd2eom Will take a look and get back to you.

**Comment by nitisht** [comment]
@kd2eom looks like there is no auto-provisioning the Kubernetes cluster you're running, so, this is a matter of mapping the existing storage class (PV) that you have to the MinIO PVC. You'd need to edit the file [here](https://github.com/minio/minio/blob/master/docs/orchestration/kubernetes/minio-standalone-pvc.yaml) to add the storage class that you have on your PV. 

We don't include PV in our documentation as per guidelines from [Kubernetes documentation here](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#writing-portable-configuration)

**Comment by tobiasjpark** [comment]
Thanks for your help. I created a StorageClass named "standard":

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
```

 and created a local PV that used that StorageClass.

```
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: tobias-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 11Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - <name of the node>
---
```

 I then modified the yaml you referenced so that it looks like this:

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pv-claim
  labels:
    app: minio-storage-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10
  storageClassName: standard
```

However, now `kubectl describe pods` is showing that deployment is pending with the error `0/1 nodes are available: 1 node(s) didn't find available persistent volumes to bind.` 

`kubectl describe pvc minio-pv-claim` says "waiting for first consumer to be created before binding".
