### ISSUE TITLE
Docker service healthcheck fails every 4 or 5 minutes

### ISSUE THREAD

**Issue by gregopenit** [minio/minio#7993]
I have a docker stack of 6 minio services distributed between 3 hosts. I followed the [documentation](https://docs.min.io/docs/deploy-minio-on-docker-swarm).

But my minio services keep restarting every 4 or 5 minutes. 'docker inspect' reveals a unhealthy status

## Expected Behavior
Service healthcheck should work.

## Current Behavior
Every 4 or 5 minutes, healthcheck fails for random services.

```
# date && docker stack ps minio
Tue Jul 30 09:32:06 CEST 2019
ID                  NAME                IMAGE                                      NODE                            DESIRED STATE       CURRENT STATE            ERROR               PORTS
3aibaudl4g9n        minio_minio3.1      minio/minio:RELEASE.2019-07-05T21-20-21Z   lnx-gva315.gva.dts.corp.local   Running             Running 5 minutes ago
diqd5s0q1glf        minio_minio2.1      minio/minio:RELEASE.2019-07-05T21-20-21Z   lnx-gva313.gva.dts.corp.local   Running             Running 5 minutes ago
bm7gt51plzwc        minio_minio1.1      minio/minio:RELEASE.2019-07-05T21-20-21Z   lnx-gva313.gva.dts.corp.local   Running             Running 5 minutes ago
g38fkhc0wcw6        minio_minio6.1      minio/minio:RELEASE.2019-07-05T21-20-21Z   lnx-gva321.gva.dts.corp.local   Running             Running 6 minutes ago
qlzc5mecgwfj        minio_minio5.1      minio/minio:RELEASE.2019-07-05T21-20-21Z   lnx-gva321.gva.dts.corp.local   Running             Running 6 minutes ago
mmv9kqv3vw84        minio_minio4.1      minio/minio:RELEASE.2019-07-05T21-20-21Z   lnx-gva315.gva.dts.corp.local   Running             Running 6 minutes ago

# date && docker stack ps minio
Tue Jul 30 09:32:30 CEST 2019
ID                  NAME                IMAGE                                      NODE                            DESIRED STATE       CURRENT STATE             ERROR               PORTS
01emgeljpxyt        minio_minio2.1      minio/minio:RELEASE.2019-07-05T21-20-21Z   lnx-gva313.gva.dts.corp.local   Running             Starting 3 seconds ago
r5kgoivji2cv        minio_minio1.1      minio/minio:RELEASE.2019-07-05T21-20-21Z   lnx-gva313.gva.dts.corp.local   Running             Starting 7 seconds ago
3aibaudl4g9n        minio_minio3.1      minio/minio:RELEASE.2019-07-05T21-20-21Z   lnx-gva315.gva.dts.corp.local   Running             Running 6 minutes ago
g38fkhc0wcw6        minio_minio6.1      minio/minio:RELEASE.2019-07-05T21-20-21Z   lnx-gva321.gva.dts.corp.local   Running             Running 6 minutes ago
qlzc5mecgwfj        minio_minio5.1      minio/minio:RELEASE.2019-07-05T21-20-21Z   lnx-gva321.gva.dts.corp.local   Running             Running 6 minutes ago
mmv9kqv3vw84        minio_minio4.1      minio/minio:RELEASE.2019-07-05T21-20-21Z   lnx-gva315.gva.dts.corp.local   Running             Running 6 minutes ago
```

Stopped service logs are:

```
# docker logs 8436b645411e
Waiting for a minimum of 3 disks to come online (elapsed 1s)
Waiting for a minimum of 3 disks to come online (elapsed 2s)
Waiting for a minimum of 3 disks to come online (elapsed 3s)
Waiting for a minimum of 3 disks to come online (elapsed 6s)
Waiting for a minimum of 3 disks to come online (elapsed 16s)

Unable to connect to http://minio1:9000/export: Post http://minio1:9000/minio/storage/v6/export/getinstanceid?: dial tcp: lookup minio1 on 127.0.0.11:53: no such host
Unable to connect to http://minio3:9000/export: Post http://minio3:9000/minio/storage/v6/export/getinstanceid?: dial tcp: lookup minio3 on 127.0.0.11:53: no such host
Unable to connect to http://minio5:9000/export: Post http://minio5:9000/minio/storage/v6/export/getinstanceid?: dial tcp: lookup minio5 on 127.0.0.11:53: no such host
Unable to connect to http://minio6:9000/export: Post http://minio6:9000/minio/storage/v6/export/getinstanceid?: dial tcp: lookup minio6 on 127.0.0.11:53: no such host

Waiting for a minimum of 3 disks to come online (elapsed 44s)

Status:         6 Online, 0 Offline.
Endpoint:  http://10.255.0.191:9000  http://10.0.4.42:9000  http://172.18.0.7:9000  http://127.0.0.1:9000

Browser Access:
   http://10.255.0.191:9000  http://10.0.4.42:9000  http://172.18.0.7:9000  http://127.0.0.1:9000

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide

Exiting on signal: TERMINATED
```

Sample of the inspect on a stopped service:

```
# docker inspect 8436b645411e
[
    {
        "Id": "8436b645411ece2b73fb5cf81af6b9472e1e273b8a595954ffeb4053f6b8f905",
        "Created": "2019-07-30T07:25:08.717049677Z",
        "Path": "/usr/bin/docker-entrypoint.sh",
(...)
        "State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2019-07-30T07:25:13.614747038Z",
            "FinishedAt": "2019-07-30T07:32:17.555973818Z",
            "Health": {
                "Status": "unhealthy",
                "FailingStreak": 3,
                "Log": [
                    {
                        "Start": "2019-07-30T09:28:13.945438907+02:00",
                        "End": "2019-07-30T09:28:14.166277934+02:00",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2019-07-30T09:29:14.187686747+02:00",
                        "End": "2019-07-30T09:29:14.346482798+02:00",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2019-07-30T09:30:14.356339818+02:00",
                        "End": "2019-07-30T09:30:14.642945929+02:00",
                        "ExitCode": 1,
                        "Output": "2019/07/30 07:30:14 no minio process found\n"
                    },
                    {
                        "Start": "2019-07-30T09:31:14.660750391+02:00",
                        "End": "2019-07-30T09:31:14.824644118+02:00",
                        "ExitCode": 1,
                        "Output": "2019/07/30 07:31:14 no minio process found\n"
                    },
                    {
                        "Start": "2019-07-30T09:32:14.838300576+02:00",
                        "End": "2019-07-30T09:32:14.982497632+02:00",
                        "ExitCode": 1,
                        "Output": "2019/07/30 07:32:14 no minio process found\n"
(...)
            "Healthcheck": {
                "Test": [
                    "CMD-SHELL",
                    "healthcheck"
                ],
                "Interval": 60000000000
            },
(...)
```

Full inspect log: [minio-inspect.log](https://github.com/minio/minio/files/3445816/minio-inspect.log)

## Possible Solution
No idea why the healthcheck fails.
But I launched a shell in a running service and manually execute the healthcheck command 'healthcheck'. Many times, the return code was 0 with no output. But then I caught this :

```
/ # healthcheck
2019/07/30 07:54:33 no minio process found
/ # ps aux
PID   USER     TIME  COMMAND
    1 root      0:00 minio server http://minio1/export http://minio2/export http://minio3/export http://minio4/export http://minio5/export http://minio6/export
   65 root      0:00 sh
  130 root      0:00 ps aux
```

I guess the healthcheck command should have found the minio process ?

Service state is fine if I disable the healthcheck with:
```
    healthcheck:
      disable: true
```
It can run several hours without any issue.

## Steps to Reproduce (for bugs)

Here is the compose file:

My compose file (without the healthcheck: disable: true)

```
version: "3.7"

services:
  minio1:
    image: minio/minio:RELEASE.2019-07-05T21-20-21Z
    hostname: minio1
    volumes:
      - /opt/minio1-data:/export
    ports:
      - "9001:9000"
    deploy:
      restart_policy:
        delay: 10s
        window: 60s
      placement:
        constraints:
          - node.labels.minioserver1==true
      labels:
        - "traefik.frontend.rule=Host: minio.dts.corp.local"
        - "traefik.enable=true"
        - "traefik.port=9000"
        - "traefik.docker.network=minio_default"
    command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export http://minio5/export http://minio6/export
    secrets:
      - secret_key
      - access_key

  minio2:
    image: minio/minio:RELEASE.2019-07-05T21-20-21Z
    hostname: minio2
    volumes:
      - /opt/minio2-data:/export
    ports:
      - "9002:9000"
    deploy:
      restart_policy:
        delay: 10s
        window: 60s
      placement:
        constraints:
          - node.labels.minioserver1==true
      labels:
        - "traefik.frontend.rule=Host: minio.dts.corp.local"
        - "traefik.enable=true"
        - "traefik.port=9000"
        - "traefik.docker.network=minio_default"
    command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export http://minio5/export http://minio6/export
    secrets:
      - secret_key
      - access_key

  minio3:
    image: minio/minio:RELEASE.2019-07-05T21-20-21Z
    hostname: minio3
    volumes:
      - /opt/minio3-data:/export
    ports:
      - "9003:9000"
    deploy:
      restart_policy:
        delay: 10s
        window: 60s
      placement:
        constraints:
          - node.labels.minioserver2==true
      labels:
        - "traefik.frontend.rule=Host: minio.dts.corp.local"
        - "traefik.enable=true"
        - "traefik.port=9000"
        - "traefik.docker.network=minio_default"
    command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export http://minio5/export http://minio6/export
    secrets:
      - secret_key
      - access_key

  minio4:
    image: minio/minio:RELEASE.2019-07-05T21-20-21Z
    hostname: minio4
    volumes:
      - /opt/minio4-data:/export
    ports:
      - "9004:9000"
    deploy:
      restart_policy:
        delay: 10s
        window: 60s
      placement:
        constraints:
          - node.labels.minioserver2==true
      labels:
        - "traefik.frontend.rule=Host: minio.dts.corp.local"
        - "traefik.enable=true"
        - "traefik.port=9000"
        - "traefik.docker.network=minio_default"
    command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export http://minio5/export http://minio6/export
    secrets:
      - secret_key
      - access_key

  minio5:
    image: minio/minio:RELEASE.2019-07-05T21-20-21Z
    hostname: minio5
    volumes:
      - /opt/minio5-data:/export
    ports:
      - "9005:9000"
    deploy:
      restart_policy:
        delay: 10s
        window: 60s
      placement:
        constraints:
          - node.labels.minioserver3==true
      labels:
        - "traefik.frontend.rule=Host: minio.dts.corp.local"
        - "traefik.enable=true"
        - "traefik.port=9000"
        - "traefik.docker.network=minio_default"
    command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export http://minio5/export http://minio6/export
    secrets:
      - secret_key
      - access_key

  minio6:
    image: minio/minio:RELEASE.2019-07-05T21-20-21Z
    hostname: minio6
    volumes:
      - /opt/minio6-data:/export
    ports:
      - "9006:9000"
    deploy:
      restart_policy:
        delay: 10s
        window: 60s
      placement:
        constraints:
          - node.labels.minioserver3==true
      labels:
        - "traefik.frontend.rule=Host: minio.dts.corp.local"
        - "traefik.enable=true"
        - "traefik.port=9000"
        - "traefik.docker.network=minio_default"
    command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export http://minio5/export http://minio6/export
    secrets:
      - secret_key
      - access_key

secrets:
  secret_key:
    external: true
  access_key:
    external: true
```

## Regression
Before switching on our production environment under CentOS and Docker 19.03, all my previous tests runned fine on VMWare PhotonOS 1.0 with Docker 18.03 and Minio RELEASE.2019-04-04T18-31-46Z.

## Your Environment
Minio version: RELEASE.2019-07-05T21-20-21Z and RELEASE.2019-07-24T02-02-23Z fails both.
Docker version: Docker CE 19.03.1
Docker Host OS : CentOS Linux release 7.6.1810 (Core)
