### ISSUE TITLE
"timeout awaiting response headers" on some PUT requests

### ISSUE THREAD

**Issue by Nepoxx** [minio/minio#8031]
## Expected behavior
PUT requests succeed
## Actual behavior
Gitlab is unable to upload some files to minio and fails with the following information:

```
handleFileUploads: extract files from multipart: persisting multipart file: upload part 1: PUT request \"https://minio.company.com/com.company.gitlab.artifacts/tmp/uploads/1565103111-4488-0055-6528-8b24198bb4aa3fb3cf76458aa5e34675?uploadId=f73e9843-af61-4e5c-848d-fc755bc2ea84&partNumber=1&X-Amz-Expires=15298&X-Amz-Date=20190806T145153Z&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=[FILTERED]%2F20190806%2Feu-east-1%2Fs3%2Faws4_request&X-Amz-SignedHeaders=host&X-Amz-Signature=[FILTERED]\": Put https://minio.company.com/com.company.gitlab.artifacts/tmp/uploads/1565103111-4488-0055-6528-8b24198bb4aa3fb3cf76458aa5e34675?uploadId=f73e9843-af61-4e5c-848d-fc755bc2ea84&partNumber=1&X-Amz-Expires=15298&X-Amz-Date=20190806T145153Z&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=[FILTERED]%2F20190806%2Feu-east-1%2Fs3%2Faws4_request&X-Amz-SignedHeaders=host&X-Amz-Signature=[FILTERED]: net/http: timeout awaiting response headers
```

## Steps to reproduce the behavior
Happens frequently when gitlab tries to upload artifacts

## mc version
- Version: 2019-06-12T20:35:20Z
Release-tag: RELEASE.2019-06-12T20-35-20Z
Commit-id: ca26dac8e2e7d2e9b2d888e82f9edbf0873b7d2e

## Server information
```
●  minio0:9000
   Status : online
   Uptime : 17 hours 
  Version : 2019-08-01T22:18:54Z
  Storage : Used 784 GiB
   Drives : 2/2 OK

●  minio1:9000
   Status : online
   Uptime : 17 hours 
  Version : 2019-08-01T22:18:54Z
  Storage : Used 784 GiB
   Drives : 2/2 OK

●  minio2:9000
   Status : online
   Uptime : 17 hours 
  Version : 2019-08-01T22:18:54Z
  Storage : Used 784 GiB
   Drives : 2/2 OK

●  minio3:9000
   Status : online
   Uptime : 17 hours 
  Version : 2019-08-01T22:18:54Z
  Storage : Used 784 GiB
   Drives : 2/2 OK

●  minio4:9000
   Status : online
   Uptime : 17 hours 
  Version : 2019-08-01T22:18:54Z
  Storage : Used 784 GiB
   Drives : 2/2 OK

●  minio5:9000
   Status : online
   Uptime : 17 hours 
  Version : 2019-08-01T22:18:54Z
  Storage : Used 784 GiB
   Drives : 2/2 OK
```

## System information
Minio is running in a docker swarm environment. Stack file:

```
version: '3.7'

x-default-deploy: &default-deploy
  replicas: 1
  restart_policy:
    condition: any
    delay: 10s
    window: 60s

x-venus-deploy: &venus-deploy
  <<: *default-deploy
  placement:
    constraints:
      - node.hostname == venus

x-mars-deploy: &mars-deploy
  <<: *default-deploy
  placement:
    constraints:
      - node.hostname == mars

x-saturn-deploy: &saturn-deploy
  <<: *default-deploy
  placement:
    constraints:
      - node.hostname == saturn

x-minio-service: &minio-common
  image: minio/minio:RELEASE.2019-08-01T22-18-54Z
  #image: minio/minio:RELEASE.2019-07-31T18-57-56Z
  networks:
    - minio_net
  logging:
    driver: json-file
    options:
      max-size: 50k
      max-file: 5
  environment:
    MINIO_ACCESS_KEY: [FILTERED]
    MINIO_SECRET_KEY: [FILTERED]
    MINIO_STORAGE_CLASS_STANDARD: EC:6 # Default is N/2
    MINIO_STORAGE_CLASS_RRS: EC:5
  command: >
    server --compat
    http://minio0/export0 http://minio0/export1
    http://minio1/export0 http://minio1/export1
    http://minio2/export0 http://minio2/export1
    http://minio3/export0 http://minio3/export1
    http://minio4/export0 http://minio4/export1
    http://minio5/export0 http://minio5/export1

services:
  minio0:
    <<: *minio-common
    deploy: *venus-deploy
    hostname: minio0
    ports:
      - target: 9000
        published: 9001
        mode: host
    volumes:
      - "/minio/disk0/export:/export0"
      - "/minio/disk1/export:/export1"

  minio1:
    <<: *minio-common
    deploy: *venus-deploy
    hostname: minio1
    ports:
      - target: 9000
        published: 9002
        mode: host
    volumes:
      - "/minio/disk2/export:/export0"
      - "/minio/disk3/export:/export1"

  minio2:
    <<: *minio-common
    deploy: *saturn-deploy
    hostname: minio2
    ports:
      - target: 9000
        published: 9003
        mode: host
    volumes:
      - "/minio/disk0/export:/export0"
      - "/minio/disk1/export:/export1"

  # Mars deployments
  minio3:
    <<: *minio-common
    deploy: *mars-deploy
    hostname: minio3
    ports:
      - target: 9000
        published: 9004
        mode: host
    volumes:
      - "/minio/disk0/export:/export0"
      - "/minio/disk1/export:/export1"

  minio4:
    <<: *minio-common
    deploy: *mars-deploy
    hostname: minio4
    ports:
      - target: 9000
        published: 9005
        mode: host
    volumes:
      - "/minio/disk2/export:/export0"
      - "/minio/disk3/export:/export1"

  minio5:
    <<: *minio-common
    deploy: *saturn-deploy
    hostname: minio5
    ports:
      - target: 9000
        published: 9006
        mode: host
    volumes:
      - "/minio/disk2/export:/export0"
      - "/minio/disk3/export:/export1"

  haproxy-saturn:
    image: haproxy:2.0.3-alpine
    volumes:
            - "/mnt/gfs/docker/haproxy-minio/config/saturn:/usr/local/etc/haproxy:ro"
            - "/mnt/gfs/docker/haproxy-minio/cert:/etc/ssl:ro"
    deploy: *saturn-deploy
    networks:
      hostnet: {}

networks:
  hostnet:
    external: true
    name: host
  minio_net:
```

Haproxy config:
```
global

    # Default SSL material locations
    ca-base /etc/ssl/certs
    crt-base /etc/ssl/private

    # Default ciphers to use on SSL-enabled listening sockets.
    # For more information, see ciphers(1SSL).
    ssl-default-bind-ciphers kEECDH+aRSA+AES:kRSA+AES:+AES256:RC4-SHA:!kEDH:!LOW:!EXP:!MD5:!aNULL:!eNULL

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend minio-http
    bind *:80
    mode http
    default_backend minio_nodes

frontend minio-https
    bind *:443 ssl crt /etc/ssl/company.com/wild.company.com.pem
    mode http
    default_backend minio_nodes

backend minio_nodes
    mode http
    balance leastconn
    option forwardfor
    option httpchk HEAD /minio/health/ready HTTP/1.1\r\nHost:localhost
    server minio1 127.0.0.1:9003 check
    server minio2 127.0.0.1:9006 check
```

I've changed from Apache to Haproxy after suspecting that the issue was cause by apache, but it was not.
