### ISSUE TITLE
minio.sha256sum must belong to minio file not minio.RELEASE...

### ISSUE THREAD

**Issue by ahmadalli** [minio/minio#8047]
I'm trying to download minio using ansible with this task:
```yaml
- name: download minio
  get_url:
    url: https://dl.min.io/server/minio/release/linux-amd64/minio
    dest: /usr/local/bin/minio
    mode: '0755'
    checksum: sha256:https://dl.min.io/server/minio/release/linux-amd64/minio.sha256sum
```

I'm getting error 

> Unable to find a checksum for file 'minio' in 'https://dl.min.io/server/minio/release/linux-amd64/minio.sha256sum'

because I'm downloading `minio` file but the sha belongs to `minio.RELEASE.2019-08-07T01-59-21Z` file

## Expected Behavior
`minio.sha256sum` must belong to `minio` file

## Current Behavior

`minio.sha256sum` belongs to `minio.RELEASE.2019-08-07T01-59-21Z`

## Possible Solution

use `minio` file for `minio.sha256sum` and `minio.RELEASE.2019-08-07T01-59-21Z` for `minio.RELEASE.2019-08-07T01-59-21Z` for `minio.RELEASE.2019-08-07T01-59-21Z.sha256sum`
