### ISSUE TITLE
Minio container is showing the status unhealthy after some minutes when start in docker-compose

### ISSUE THREAD

**Issue by appleboy** [minio/minio#8082]
minio container always change the status to unhealthy after some minutes in docker-compose

## Expected Behavior

always (healthy)

## Current Behavior

Minio container is showing the status unhealthy. When I am running `docker restart`, then it is again ok. But after sometimes it again becomes unhealthy.

## Steps to Reproduce (for bugs)

```yaml
  minio:
    image: minio/minio:edge
    command: server /data
    restart: always
    ports:
      - "127.0.0.1:9000:9000"
    volumes:
      - ${STORAGE_PATH}:/data
    logging:
      options:
        max-size: "100k"
        max-file: "3"
    environment:
      MINIO_ACCESS_KEY: 1234567890
      MINIO_SECRET_KEY: 1234567890
    labels:
      - "traefik.enable=true"
      - "traefik.s3.frontend.rule=Host:${S3_HOST}"
      - "traefik.s3.port=9000"
      - "traefik.s3.protocol=http"
```

steps:

```sh
docker-compose up -d
```

## Your Environment

* Version used (`minio version`): 

> Version: 2019-08-15T00:14:57Z
> Release-Tag: DEVELOPMENT.2019-08-15T00-14-57Z
> Commit-ID: 825e29f3015c96bb83b0de71352bc35d003e91f4

**Comment by nitisht** [comment]
Thanks for reporting @appleboy we'll take a look

**Comment by appleboy** [comment]
@nitisht I rollback the Minio version to `RELEASE.2019-04-23T23-50-36Z` tag. It is working for me. If anyone faces the issue, please try the `RELEASE.2019-04-23T23-50-36Z` tag

```yaml
  minio:
    image: minio/minio:RELEASE.2019-04-23T23-50-36Z
    command: server /data
    restart: always
```
