### ISSUE TITLE
During Minio deployment on AWS kubernetes node: "ERROR Unable to initialize disk caching: Atime support required for disk caching"

### ISSUE THREAD

**Issue by jkanturski** [minio/minio#8125]
Cannot start minio container in the pod to be deployed on AWS kubernetes cluster node because of atime support enabled requirement

## Expected Behavior
 Minio container should start, so the minio pod can be deployed on AWS kubernetes cluster

## Current Behavior
Minio pod logs: "ERROR Unable to initialize disk caching: Atime support required for disk caching" 
Minio pod status: "CrashLoopBackOff"
Container logs: "Back-off restarting failed container"

## Your Environment
* Version used: minio/minio:RELEASE.2019-08-21T19-40-07Z
* AWS ec2.internal node

**Comment by nitisht** [comment]
Thanks for reporting @jkanturski we'll take a look

**Comment by poornas** [comment]
Disk caching requires atime to be enabled on the cache drive(s) for cache eviction. Are the cache drive(s) specified in the MINIO_CACHE_DRIVES env variable actually backed by a cache drive with relatime/strictatime enabled? The cache drive(s) should be backed by a persistent volume with atime enabled on the mount point, @jkanturski

**Comment by bry00** [comment]
This error occurs when cache drive is backed by emptyDir volume, like with this configuration:
```
          - name: MINIO_CACHE_DRIVES
            value: "/valdi/s3/data"
          volumeMounts:
          - mountPath: /valdi/s3/data
            name: minio-cache-volume
      volumes:
      - name: minio-cache-volume
        emptyDir: {}
```
