### ISSUE TITLE
Signature error when uploading via cURL

### ISSUE THREAD

**Issue by bhrott** [minio/minio#8136]
When we try to upload a file to a bucket in localhost using cURL, we are getting this error:

```
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><Key>image.jpg</Key><BucketName>public</BucketName><Resource>/public/image.jpg</Resource><RequestId>15BECBCC7E9DEBA4</RequestId><HostId>f15f8798-8187-41f1-b130-975fae7043e0</HostId></Error>
```

## Expected Behavior
The file should be upload to the bucket.

## Current Behavior
We are getting the signature error.

## Steps to Reproduce (for bugs)

docker-compose:

```yml
local-minio:
    image: minio/minio
    container_name: local-minio
    ports:
      - '9000:9000'
    volumes:
      - /tmp/minio:/data
    environment:
      - MINIO_ACCESS_KEY=******
      - MINIO_SECRET_KEY=******
      - MINIO_BROWSER=on
    command: server /home/shared
```

```sh
#!/bin/bash

# usage: ./minio-upload my-bucket my-file.zip

bucket=$1
file=$2

host=localhost:9000
s3_key='******'
s3_secret='******'

resource="/${bucket}/${file}"
content_type="application/octet-stream"
date=`date -R`
_signature="PUT\n\n${content_type}\n${date}\n${resource}"
signature=`echo -en ${_signature} | openssl sha1 -hmac ${s3_secret} -binary | base64`

curl -v -X PUT -T "${file}" \
          -H "Host: $host" \
          -H "Date: ${date}" \
          -H "Content-Type: ${content_type}" \
          -H "Authorization: AWS ${s3_key}:${signature}" \
          http://$host${resource}
```

## Context
We need to dispatch a request from another application directly to the minio without using the minio client, only raw requests.

## Your Environment

* Version used (`minio version`):
    * Version: 2019-07-10T00:34:56Z
    * Release-Tag: RELEASE.2019-07-10T00-34-56Z
    * Commit-ID: 9d49688c87e9c7c3f769833c3a8697d16349f6c0
* Environment name and version (e.g. nginx 1.9.1): docker image `minio/minio`
* Operating System and version (`uname -a`): `Darwin MB-002993.local 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64`
