### ISSUE TITLE
Docker swarm healthcheck/startup issue

### ISSUE THREAD

**Issue by vsfalexanderpilch** [minio/minio#8140]
I'm running the (modified) docker swarm example from the documentation, but the nodes won't start if the healtchcheck is in there. **Docker swarm will only register the dns entry with the embedded dns after the container has been started successfully.** Here's the snippet I'm using in order to start a container:

```
  node1:
    image: minio/minio:latest
    hostname: node1
    volumes:
     - data1:/data
    networks:
      - backend
    command: server --compat http://node{1...4}/data/{1...8}
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:
        constraints:
          - node.labels.minio==node1
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
#      interval: 1m30s
#      timeout: 20s
#      retries: 3
#      start_period: 1m
    secrets:
      - secret_key
      - access_key
```
[docker-compose.txt](https://github.com/minio/minio/files/3551223/docker-compose.txt)

The healthcheck won't be able to acces node1, as minio will only start if multiple of those nodes are available. So it's kind of a deadlock: Minio will wait for other servers to be available, which will never happen as the dns entries aren't available. Docker Swarm healthcheck will wait for minio healthcheck to report success and that will never happen as minio won't start due to missing dns entries.

I've currently deactivated the healthcheck and it's working fine, although I'd prefer to be able to use the healthchecks.

Would it be possible to somehow report some success status before the container is fully initialized? The endpoint could report it at the beginning and later on switch to offline after some time. This would allow docker to register the dns entries and the other containers will be able to startup as well. If the status is changed, the container will be automatically restarted later on.
