### ISSUE TITLE
Cluster down as soon as one node is offline

### ISSUE THREAD

**Issue by philipkozeny** [minio/minio#8149]
I am running Minio on 4 different hosts with 2 disk each on Hetzners Cloud.

To run the nodes i am using docker-compose:

```
version: '3'

services:
 minio-1:
  image: minio/minio:latest
  volumes:
   - /mnt/volume-storage-1/:/data-1
   - /mnt/volume-storage-2/:/data-2
  ports:
   - "10.0.2.1:9000:9000"
  extra_hosts:
   - "minio-2:10.0.2.2"
   - "minio-3:10.0.2.3"
   - "minio-4:10.0.2.4"
  restart: always
  environment:
   MINIO_ACCESS_KEY: abc
   MINIO_SECRET_KEY: abc
  command: server http://minio-{1...4}/data-{1...2}
```

etc. I have a private network setup between the nodes. If all the nodes are online, everything is working great.

Output of 

`mc admin info server minio-1`

```
●  minio-1:9000
   Uptime: 2 minutes
  Version: 2019-08-29T00:25:01Z
  Storage: Used 338 GiB, Free 405 GiB
   Drives: 2/2 OK

   CPU        min        avg      max
   current    0.14%      0.16%    0.18%
   historic   0.08%      0.38%    4.98%

   MEM        usage
   current    68 MiB
   historic   68 MiB


●  minio-2:9000
   Uptime: 7 minutes
  Version: 2019-08-29T00:25:01Z
  Storage: Used 338 GiB, Free 405 GiB
   Drives: 2/2 OK

   CPU        min        avg      max
   current    0.23%      0.24%    0.25%
   historic   0.08%      1.37%    42.29%

   MEM        usage
   current    68 MiB
   historic   68 MiB


●  minio-3:9000
   Uptime: 7 minutes
  Version: 2019-08-29T00:25:01Z
  Storage: Used 338 GiB, Free 405 GiB
   Drives: 2/2 OK

   CPU        min        avg      max
   current    0.17%      0.25%    0.30%
   historic   0.11%      0.41%    10.78%

   MEM        usage
   current    68 MiB
   historic   68 MiB


●  minio-4:9000
   Uptime: 7 minutes
  Version: 2019-08-29T00:25:01Z
  Storage: Used 338 GiB, Free 405 GiB
   Drives: 2/2 OK

   CPU        min        avg      max
   current    0.16%      0.30%    0.52%
   historic   0.08%      0.26%    1.23%

   MEM        usage
   current    68 MiB
   historic   68 MiB
```

As soon as one node is offline (sudo docker-compose down), the complete cluster is not working anymore. I can login to the web-frontend, but no data is loaded. Every command with MC will take ages and time out after some time.

This is the log output of one of the online nodes:

```
→ sudo docker logs f58bb44e7f78
Status:         8 Online, 2 Offline.
Endpoint:  http://172.20.0.2:9000  http://127.0.0.1:9000

Browser Access:
   http://172.20.0.2:9000  http://127.0.0.1:9000

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide

API: SYSTEM()
Time: 10:38:25 UTC 08/29/2019
DeploymentID: 33a35db4-7ca0-4da6-8f69-c9a186889cfd
Error: Post http://minio-1:9000/minio/peer/v4/backgroundopsstatus?: dial tcp 10.0.2.1:9000: i/o timeout
       2: cmd/notification.go:290:cmd.(*NotificationSys).BackgroundOpsStatus()
       1: cmd/daily-lifecycle-ops.go:83:cmd.startDailyLifecycle()

API: SYSTEM()
Time: 10:38:44 UTC 08/29/2019
DeploymentID: 33a35db4-7ca0-4da6-8f69-c9a186889cfd
Error: disk not found
       endpoint=http://minio-1:9000/data-1
       3: cmd/prepare-storage.go:40:cmd.glob..func12.1()
       2: cmd/xl-sets.go:212:cmd.(*xlSets).connectDisks()
       1: cmd/xl-sets.go:243:cmd.(*xlSets).monitorAndConnectEndpoints()

API: SYSTEM()
Time: 10:39:44 UTC 08/29/2019
DeploymentID: 33a35db4-7ca0-4da6-8f69-c9a186889cfd
Error: disk not found
       endpoint=http://minio-1:9000/data-2
       3: cmd/prepare-storage.go:40:cmd.glob..func12.1()
       2: cmd/xl-sets.go:212:cmd.(*xlSets).connectDisks()
       1: cmd/xl-sets.go:243:cmd.(*xlSets).monitorAndConnectEndpoints()

API: SYSTEM()
Time: 10:40:26 UTC 08/29/2019
DeploymentID: 33a35db4-7ca0-4da6-8f69-c9a186889cfd
Error: Post http://minio-1:9000/minio/peer/v4/backgroundopsstatus?: dial tcp 10.0.2.1:9000: connect: connection refused
       2: cmd/notification.go:290:cmd.(*NotificationSys).BackgroundOpsStatus()
       1: cmd/daily-lifecycle-ops.go:83:cmd.startDailyLifecycle()
```

## Expected Behavior

Cluster should stay operable like designed.

## Steps to Reproduce (for bugs)

1. Create 4 hosts
2. Deploy minio with docker-compose on private network
3. Take on host down
4. Try to access data

## Your Environment
* Version used (`minio version`): Version: 2019-08-29T00:25:01Z
* Server type and version: Hetzner Cloud instance with private networks
* Operating System and version (`uname -a`): Linux utils 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5 (2019-06-19) x86_64 GNU/Linux

**Comment by kannappanr** [comment]
@philipkozeny  We will take a look into this issue and get back to you for more info if needed.

**Comment by harshavardhana** [comment]
This is fixed in latest release, are you sure you are using the latest release ?

**Comment by philipkozeny** [comment]
@harshavardhana pretty sure, yes. Just ran

`cd /opt/minio && sudo docker pull minio/minio && sudo docker-compose down && sudo docker-compose up -d`

on all hosts, rebooted the physical hosts again on all machines. When all 4 hosts are up everything is working, if i take one offline nothing works anymore. 

`mc admin info server minio-1`

reports Version: 2019-08-29T00:25:01Z for all 4 hosts.

**Comment by harshavardhana** [comment]
Okay will check @philipkozeny

**Comment by harshavardhana** [comment]
@philipkozeny I just checked 

```
docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                             PORTS                    NAMES
b26f441502d7        y4m4/minio:dev      "/usr/bin/docker-ent…"   40 seconds ago      Up 38 seconds (health: starting)   0.0.0.0:9003->9000/tcp   minio_minio3_1_7aa293196900
5f8c370fb2b9        y4m4/minio:dev      "/usr/bin/docker-ent…"   40 seconds ago      Up 39 seconds (health: starting)   0.0.0.0:9002->9000/tcp   minio_minio2_1_5f690c449f6b
45af6c63a9b7        y4m4/minio:dev      "/usr/bin/docker-ent…"   40 seconds ago      Up 39 seconds (health: starting)   0.0.0.0:9004->9000/tcp   minio_minio4_1_94694547f284
739f263aee6b        y4m4/minio:dev      "/usr/bin/docker-ent…"   40 seconds ago      Up 38 seconds (health: starting)   0.0.0.0:9001->9000/tcp   minio_minio1_1_2b7578d0ec11
```

```
~ mc ls myminio-local1
[2019-08-29 11:06:15 PDT]      0B testbucket/
```

```
~ docker stop 45af6c63a9b7
45af6c63a9b7
```

```
~ mc ls myminio-local1
[2019-08-29 11:06:15 PDT]      0B testbucket/
```

```
~ mc cp /etc/hosts myminio-local1/testbucket/
/etc/hosts:            417 B / 417 B ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00% 10.17 KiB/s 0s
```

Even the browser is loading fine

**Comment by harshavardhana** [comment]
Even with the same configuration that you have

```
~ mc mb myminio-local1/testbucket/
Bucket created successfully `myminio-local1/testbucket/`.
```
```
~ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
89ea50f38c39        y4m4/minio:dev      "/usr/bin/docker-ent…"   14 seconds ago      Up 12 seconds       0.0.0.0:9002->9000/tcp   minio_minio2_1_f059009bca5b
87e2f747ebff        y4m4/minio:dev      "/usr/bin/docker-ent…"   14 seconds ago      Up 12 seconds       0.0.0.0:9004->9000/tcp   minio_minio4_1_ef82b1004071
d05bc496fe32        y4m4/minio:dev      "/usr/bin/docker-ent…"   14 seconds ago      Up 12 seconds       0.0.0.0:9001->9000/tcp   minio_minio1_1_7980d6133110
aae8c43f40a5        y4m4/minio:dev      "/usr/bin/docker-ent…"   14 seconds ago      Up 11 seconds       0.0.0.0:9003->9000/tcp   minio_minio3_1_1b1ea2b5f50e
```

```yml
version: '3.7'

# starts 4 docker containers running minio server instances. Each
# minio server's web interface will be accessible on the host at port
# 9001 through 9004.
services:
  minio1:
    image: y4m4/minio:dev
    volumes:
      - data1-1:/data1
      - data1-2:/data2
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio{1...4}/data{1...2}

  minio2:
    image: y4m4/minio:dev
    volumes:
      - data2-1:/data1
      - data2-2:/data2
    ports:
      - "9002:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio{1...4}/data{1...2}

  minio3:
    image: y4m4/minio:dev
    volumes:
      - data3-1:/data1
      - data3-2:/data2
    ports:
      - "9003:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio{1...4}/data{1...2}            

  minio4:
    image: y4m4/minio:dev
    volumes:
      - data4-1:/data1
      - data4-2:/data2
    ports:
      - "9004:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio{1...4}/data{1...2}                  

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  data1-1:
  data1-2:
  data2-1:
  data2-2:
  data3-1:
  data3-2:
  data4-1:
  data4-2:
```

Kill one of the nodes at say port 9003

```
~ docker stop aae8c43f40a5
~ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
89ea50f38c39        y4m4/minio:dev      "/usr/bin/docker-ent…"   2 minutes ago       Up 2 minutes        0.0.0.0:9002->9000/tcp   minio_minio2_1_f059009bca5b
87e2f747ebff        y4m4/minio:dev      "/usr/bin/docker-ent…"   2 minutes ago       Up 2 minutes        0.0.0.0:9004->9000/tcp   minio_minio4_1_ef82b1004071
d05bc496fe32        y4m4/minio:dev      "/usr/bin/docker-ent…"   2 minutes ago       Up 2 minutes        0.0.0.0:9001->9000/tcp   minio_minio1_1_7980d6133110
```
~ mc cp /etc/hosts myminio-local1/testbucket/
/etc/hosts:            417 B / 417 B ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00% 3.56 KiB/s 0s
```
