### ISSUE TITLE
Docker image: bucket or object are not visible after refresh from Minio Browser

### ISSUE THREAD

**Issue by YoussefArfaoui** [minio/minio#8179]
I'm trying to test the docker compose file provided in the minio web site. I tried to create  bucket from the web interface. bucket is created and I can see it in the file system but if I refresh the page or I create the bucket using AWS S3 it's not visible in the browser. Please is there any missing configuration or recommendation to make it work as it should be?

```yaml
docker-compose.yml
version: '3.7'

# starts one docker container running minio server instances. Each
# minio server's web interface will be accessible on the host at port
# 9001 through 9004.
services:
  minio:
    image: dockerext.swift.com/minio/minio:RELEASE.2019-08-14T20-37-41Z
    volumes:
      - data1:/data
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: minio server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://minio:9000/minio/health/live"]
      interval: 1m30s
      timeout: 20s
      retries: 3
      start_period: 3m
## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  data1:
```
