### ISSUE TITLE
Service Unavailable, when running in docker on a build server

### ISSUE THREAD

**Issue by Ploppz** [minio/minio#8265]
I run minio in docker:
```
FROM archlinux/base

RUN pacman -Sy
RUN pacman -S tree --noconfirm
RUN pacman -Scc --noconfirm

RUN curl -o /usr/bin/minio https://dl.minio.io/server/minio/release/linux-amd64/minio
RUN chmod +x /usr/bin/minio

RUN useradd -ms /bin/bash user
# RUN passwd -d user
# RUN echo "user   ALL=(ALL) ALL" >> /etc/sudoers
USER user
WORKDIR /home/user

RUN mkdir -p /home/user/s3/test-bucket

ENV MINIO_ACCESS_KEY 123456789
ENV MINIO_SECRET_KEY 123456789

CMD minio server --address 0.0.0.0:9000 /home/user/s3
```

and with `docker-compose.yml`:
```
version: '3'
services:
  minio:
    image: minio
    ports:
      - 9000:9000
    tty: true
  rust:
    // omitted stuff for brevity
```
I use `docker-compose up` to run minio alongside my application
When I run it locally, it all works fine.
However, on the build server, I get: 
```
An error occurred (503) when calling the PutObject operation (reached max retries: 4): Service Unavailable
```
with this aws command
```
aws s3 --endpoint-url=http://minio:9000 --profile=testing cp /tmp/something s3://test-bucket/something --recursive
```
The `aws` cli is the same version on the build server and locally (it's in the docker image the application runs in)

Any idea what might be wrong that makes it fail on one machine and not the other?

## Your Environment
* Version used (`minio version`):
```
Version: 2019-09-11T19:53:16Z
Release-Tag: RELEASE.2019-09-11T19-53-16Z
Commit-ID: 53e4887e02b94ed37dea8c5173330f17548fe122
```
* Operating System and version (`uname -a`):

    - build server: `Linux ci 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
    - local pc:  `Linux erlend 5.1.16-arch1-1-ARCH #1 SMP PREEMPT Wed Jul 3 20:23:07 UTC 2019 x86_64 GNU/Linux`

**Comment by kannappanr** [comment]
@Ploppz It could be some firewall or some other setup issue. It is generally easier to debug these sorts of issues better if you are on our slack channel at https://slack.min.io . We can try to reproduce the issue here and get back to you with more questions.

**Comment by Ploppz** [comment]
The problem is resolved.
It had something to do with the build server indeed. Not the firewall, but for some strange reason it used a proxy to resolve the `minio` hostname.

**Comment by MartinP7r** [comment]
@Ploppz could you share how you fixed your issue exactly? I think I might experience something similar, but am not quite sure how to keep it from trying to resolve the hostname via our proxy...

**Comment by Ploppz** [comment]
Hey @MartinP7r , it's been a while so I'm not exactly sure what it was,
but candidates are:
These lines, in our Dockerfile which is based on ubuntu (from which we sent requests to minio running in dockercompose I think) But  maybe those lines were for something else like reaching the internet from within docker.

```
RUN echo 'Aquire::http::Proxy "http_proxy=http://our-web-proxy-url.com:8080";' > /etc/apt/apt.conf.d/proxy.conf
RUN echo 'Aquire::http::Proxy "https_proxy=http://our-web-proxy-url.com:8080";' >> /etc/apt/apt.conf.d/proxy.conf
```

Or in the docker-compose:
```yaml
version: '3.3'
services:
  minio:
    image: <our minio image>
    ports:
      - 9000:9000
    tty: true
  rust:
    .... some things left out
    security_opt:
        - seccomp:unconfined
    environment:
        - no_proxy=minio
networks:
    $BUILD_ID:
```
The `rust` image being the one from where requests are made. We are not using any of this anymore though.
