### ISSUE TITLE
Chrome fails to plays mp4 content with error net::ERR_CONTENT_DECODING_FAILED

### ISSUE THREAD

**Issue by grupoz** [minio/minio#8364]
Minio server sends in response Headers: "Content-Encoding: gzip''' for *.mp4 content, from documentation this content are excluded from compression, even if compression is enabled.

When chrome try to reproduce this content fails with msg:
net::ERR_CONTENT_DECODING_FAILED 
(in other browsers reproduction also fails)

Walkaround: Minio behind a proxy, which removes the Content-Encoding header for this type of content. 

mc version
Version: 2019-10-02T19:41:02Z
Release-tag: RELEASE.2019-10-02T19-41-02Z
Commit-id: 26b9044a8676a8c5ff79a6054343e5be74c35135

**Comment by kannappanr** [comment]
@grupoz Can you paste your `MinIO` version, plus if you can give more information about any environment variable that you have set, your config file, and the mode you started MinIO in and the command you entered to start MinIO.

I tried this on `FS` mode, with and without compression turned on and was unable to reproduce this issue.

**Comment by grupoz** [comment]
Hi @kannappanr:

Minio Version
```
mc version
Version: 2019-10-02T19:41:02Z
Release-tag: RELEASE.2019-10-02T19-41-02Z
Commit-id: 26b9044a8676a8c5ff79a6054343e5be74c35135
```
Minio Env Vars
```
MINIO_ACCESS_KEY=XXXXXXXXXXXXXXXX
MINIO_SECRET_KEY=XXXXXXXXXXXXXXXX
MINIO_REGION=lidice
MINIO_STORAGE_CLASS_STANDARD=EC:2
MINIO_SSE_AUTO_ENCRYPTION=on
MINIO_SSE_MASTER_KEY=my-minio-key:XXXXXXXXXXXXXXXX
MINIO_OPTS=--address *:9000
MINIO_DOMAIN=origin.domain.com
MINIO_COMPRESS=true
MINIO_VOLUMES='http://node-01.domain.com/s3_1 http://node-01.domain.com/s3_2  http://node-02.domain.com/s3_1 http://node-02.domain.com/s3_2'
```
Minio Startup script
```
/usr/sbin/minio server http://node-01.domain.com/s3_1 http://node-01.domain.com/s3_2  http://node-02.domain.com/s3_1 http://node-02.domain.com/s3_2
```
Minio Logs after start

```
Oct 04 17:49:31 ott-http-storage-01.grupoz.cl minio[2803]: Status:         4 Online, 0 Offline.
Oct 04 17:49:31 ott-http-storage-01.grupoz.cl minio[2803]: Endpoint:  http://10.0.0.103:9000  http://127.0.0.1:9000
Oct 04 17:49:31 ott-http-storage-01.grupoz.cl minio[2803]: Browser Access:
Oct 04 17:49:31 ott-http-storage-01.grupoz.cl minio[2803]: http://10.0.0.103:9000  http://127.0.0.1:9000
Oct 04 17:49:31 ott-http-storage-01.grupoz.cl minio[2803]: Object API (Amazon S3 compatible):
Oct 04 17:49:31 ott-http-storage-01.grupoz.cl minio[2803]: Go:         https://docs.min.io/docs/golang-client-quickstart-guide
Oct 04 17:49:31 ott-http-storage-01.grupoz.cl minio[2803]: Java:       https://docs.min.io/docs/java-client-quickstart-guide
Oct 04 17:49:31 ott-http-storage-01.grupoz.cl minio[2803]: Python:     https://docs.min.io/docs/python-client-quickstart-guide
Oct 04 17:49:31 ott-http-storage-01.grupoz.cl minio[2803]: JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
Oct 04 17:49:31 ott-http-storage-01.grupoz.cl minio[2803]: .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
```
when I upload an mp4 through the Minio browser, there are no problems.

However when I use the [ansible library](https://docs.ansible.com/ansible/latest/modules/aws_s3_module.html) to upload the content i run in this issue. (please note the metadata part):

```
    - name: PUT/upload with metadata
      aws_s3:
        bucket: '{{ test_bucket }}'
        object: '/incoming/{{ item }}'
        src: 'templates/videos/{{ item }}'
        mode: put
        encrypt: yes
        metadata: 'Content-Encoding=gzip,Cache-Control=no-cache'
        s3_url: http://{{ haproxy_public_ip }}:9000
        region: '{{ MINIO_REGION }}'
        aws_access_key: '{{ MINIO_ACCESS_KEY }}'
        aws_secret_key: '{{ MINIO_SECRET_KEY }}'
      with_items: ['SampleVideo_1280x720_20mb2.mp4']
```

Upload via Minio Browser
cat SampleVideo_1280x720_20mb.mp4/xl.json 
```
{"version":"1.0.1","format":"xl","stat":{"size":21079982,"modTime":"2019-10-07T17:37:42.288796253Z"},"erasure":{"algorithm":"klauspost/reedsolomon/vandermonde","data":2,"parity":2,"blockSize":10485760,"index":2,"distribution":[2,3,4,1],"checksum":[{"name":"part.1","algorithm":"highwayhash256S"}]},"minio":{"release":"RELEASE.2019-10-02T21-19-38Z"},"meta":{"X-Minio-Internal-Server-Side-Encryption-Iv":"CT8FKnAgidgwi1sZwxdHUPj2X7HnZ1YdV5R4KU5w8qA=","X-Minio-Internal-Server-Side-Encryption-S3-Kms-Key-Id":"my-minio-key","X-Minio-Internal-Server-Side-Encryption-S3-Kms-Sealed-Key":"IAEfAOqgpa2d8AUq6Fv3V2zMlt9Ch/hIXArmIsYhGqHZwfYPE896mHThQ7CpmOQLgY364IXX0Q2TWTanPyl/Rw==","X-Minio-Internal-Server-Side-Encryption-S3-Sealed-Key":"IAEfAKa1QPRVdlEjJpuDBOfVpnm8x1CngbOwzeuAcMDSr2kyqtFiziqmqiioIDD8rVFL5N7dHkzW0AHlcGQJ5w==","X-Minio-Internal-Server-Side-Encryption-Seal-Algorithm":"DAREv2-HMAC-SHA256","content-type":"video/mp4","etag":"20010f00fd2297fa9f85ba128d303ac6-1"},"parts":[{"number":1,"name":"part.1","etag":"","size":21079982,"actualSize":21069678}]}
```

Upload via ansible library
cat SampleVideo_1280x720_20mb2.mp4/xl.json 
```
{"version":"1.0.1","format":"xl","stat":{"size":21079982,"modTime":"2019-10-07T17:43:59.178971455Z"},"erasure":{"algorithm":"klauspost/reedsolomon/vandermonde","data":2,"parity":2,"blockSize":10485760,"index":1,"distribution":[1,2,3,4],"checksum":[{"name":"part.3","algorithm":"highwayhash256S"},{"name":"part.1","algorithm":"highwayhash256S"},{"name":"part.2","algorithm":"highwayhash256S"}]},"minio":{"release":"RELEASE.2019-10-02T21-19-38Z"},"meta":{"X-Minio-Internal-Encrypted-Multipart":"","X-Minio-Internal-Server-Side-Encryption-Iv":"7q2PdcP/vDrAlVz/Rm62d8YgAFkB3vkR1Ysgy9i6oJs=","X-Minio-Internal-Server-Side-Encryption-S3-Kms-Key-Id":"my-minio-key","X-Minio-Internal-Server-Side-Encryption-S3-Kms-Sealed-Key":"IAEfAI1GnfkJ1wFTUWYBUvdVTLT+2+yEt3atmdtJY+OIvYTknD92jaz1e2dU1JF8LFYzCxetkvqnSQfgYLrceg==","X-Minio-Internal-Server-Side-Encryption-S3-Sealed-Key":"IAEfAJdYGLCyaSYOMcPKynSlAEkLa1PHLFTB8ZWV+CauTrgEjfMTeA+gz3apdxGlS5nJtwvpg+0AoEHCo2PFqQ==","X-Minio-Internal-Server-Side-Encryption-Seal-Algorithm":"DAREv2-HMAC-SHA256","X-Minio-Internal-actual-size":"21069678","cache-control":"no-cache","content-encoding":"gzip","content-type":"video/mp4","etag":"c3fc514a8d6ee08990e7971d237e164b-3"},"parts":[{"number":1,"name":"part.1","etag":"20010f00863f4fd96db8e72a717910ae14e7b5a1c7c5c4af79457eaa5b1183fbc77f0d172f8925ed22666281de49e6ee","size":8392704,"actualSize":8388608},{"number":2,"name":"part.2","etag":"20010f00e8fed1fe8609d5270622ee14f80ef61a2c159a315e07a848eed0103f863c38c53b0917eddf610e72b1b36d16","size":8392704,"actualSize":8388608},{"number":3,"name":"part.3","etag":"20010f00aca3c92d3c7a83a555600e1886a4d25c97230cde4c12e942618341f97817cd5b6f3b68226d0e776ca27d8f61","size":4294574,"actualSize":4292462}]}
```

I don't know if it's the expected behavior, or Minio should ignore the metadata 'Content-Encoding = gzip', in the PUT operation for this type of content

Regards

**Comment by kannappanr** [comment]
@grupoz From the input that you have for the `ansible` part

```
    - name: PUT/upload with metadata
      aws_s3:
        bucket: '{{ test_bucket }}'
        object: '/incoming/{{ item }}'
        src: 'templates/videos/{{ item }}'
        mode: put
        encrypt: yes
        metadata: 'Content-Encoding=gzip,Cache-Control=no-cache'
        s3_url: http://{{ haproxy_public_ip }}:9000
        region: '{{ MINIO_REGION }}'
        aws_access_key: '{{ MINIO_ACCESS_KEY }}'
        aws_secret_key: '{{ MINIO_SECRET_KEY }}'
      with_items: ['SampleVideo_1280x720_20mb2.mp4']
```
You are setting `Content-Encoding` to `gzip`, so `MinIO` server will not override that just as AWS S3 will not. You will have to set the appropriate `Content-Encoding` in your `ansible` script
