### ISSUE TITLE
Error: Write failed. Insufficient number of disks online

### ISSUE THREAD

**Issue by yiranzai** [minio/minio#8383]
# Error

```
minio_server    | API: SYSTEM()
minio_server    | Time: 02:24:30 UTC 10/11/2019
minio_server    | DeploymentID: c0bdcc21-83cb-49f4-b8d7-30f59d3b3e29
minio_server    | Error: Write failed. Insufficient number of disks online
minio_server    |       11: cmd/erasure-encode.go:100:cmd.(*Erasure).Encode()
minio_server    |       10: cmd/xl-v1-object.go:630:cmd.xlObjects.putObject()
minio_server    |        9: cmd/xl-v1-object.go:514:cmd.xlObjects.PutObject()
minio_server    |        8: cmd/xl-sets.go:653:cmd.(*xlSets).PutObject()
minio_server    |        7: cmd/config-common.go:62:cmd.saveConfig()
minio_server    |        6: cmd/config.go:68:cmd.saveServerConfig()
minio_server    |        5: cmd/config-current.go:514:cmd.newSrvConfig()
minio_server    |        4: cmd/config-migrate.go:2474:cmd.migrateConfigToMinioSys()
minio_server    |        3: cmd/config.go:181:cmd.initConfig()
minio_server    |        2: cmd/config.go:144:cmd.(*ConfigSys).Init()
minio_server    |        1: cmd/server-main.go:342:cmd.serverMain()
minio_server    |
minio_server    | API: SYSTEM()
minio_server    | Time: 02:24:30 UTC 10/11/2019
minio_server    | DeploymentID: c0bdcc21-83cb-49f4-b8d7-30f59d3b3e29
minio_server    | Error: Write failed. Insufficient number of disks online
minio_server    |       11: cmd/erasure-encode.go:100:cmd.(*Erasure).Encode()
minio_server    |       10: cmd/xl-v1-object.go:630:cmd.xlObjects.putObject()
minio_server    |        9: cmd/xl-v1-object.go:514:cmd.xlObjects.PutObject()
minio_server    |        8: cmd/xl-sets.go:653:cmd.(*xlSets).PutObject()
minio_server    |        7: cmd/config-common.go:62:cmd.saveConfig()
minio_server    |        6: cmd/config.go:68:cmd.saveServerConfig()
minio_server    |        5: cmd/config-current.go:514:cmd.newSrvConfig()
minio_server    |        4: cmd/config-migrate.go:2474:cmd.migrateConfigToMinioSys()
minio_server    |        3: cmd/config.go:181:cmd.initConfig()
minio_server    |        2: cmd/config.go:144:cmd.(*ConfigSys).Init()
minio_server    |        1: cmd/server-main.go:342:cmd.serverMain()
minio_server    |
minio_server    | API: SYSTEM()
minio_server    | Time: 02:24:30 UTC 10/11/2019
minio_server    | DeploymentID: c0bdcc21-83cb-49f4-b8d7-30f59d3b3e29
minio_server    | Error: Write failed. Insufficient number of disks online
minio_server    |       11: cmd/erasure-encode.go:100:cmd.(*Erasure).Encode()
minio_server    |       10: cmd/xl-v1-object.go:630:cmd.xlObjects.putObject()
minio_server    |        9: cmd/xl-v1-object.go:514:cmd.xlObjects.PutObject()
minio_server    |        8: cmd/xl-sets.go:653:cmd.(*xlSets).PutObject()
minio_server    |        7: cmd/config-common.go:62:cmd.saveConfig()
minio_server    |        6: cmd/config.go:68:cmd.saveServerConfig()
minio_server    |        5: cmd/config-current.go:514:cmd.newSrvConfig()
minio_server    |        4: cmd/config-migrate.go:2474:cmd.migrateConfigToMinioSys()
minio_server    |        3: cmd/config.go:181:cmd.initConfig()
minio_server    |        2: cmd/config.go:144:cmd.(*ConfigSys).Init()
minio_server    |        1: cmd/server-main.go:342:cmd.serverMain()
minio_server    | Waiting for configuration to be initialized..
```

# Environment

> docker fo mac

## OS

```
macOS Mojave 10.14.6
```

## docker version

```
Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfc
 Built:             Thu Aug 29 05:26:49 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       6a30dfc
  Built:            Thu Aug 29 05:32:21 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

## docker-compose.yml

```yaml
---
version: "3.7"

services:
  minio_server:
    image: minio/minio:RELEASE.2019-10-11T00-38-09Z
    container_name: minio_server
    volumes:
      - ./minio/config:/root/.minio
      - ./minio/data1:/data1
      - ./minio/data2:/data2
      - ./minio/data3:/data3
      - ./minio/data4:/data4
      - ./minio/data5:/data5
      - ./minio/data6:/data6
      - ./minio/data7:/data7
      - ./minio/data8:/data8
      - ./minio/data9:/data9
      - ./minio/data10:/data10
      - ./minio/data11:/data11
      - ./minio/data12:/data12
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: yiranzai
      MINIO_SECRET_KEY: yiranzai123
    command: server /data1 /data2 /data3 /data4 /data5 /data6 /data7 /data8 /data9 /data10 /data11 /data12
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - minio_webnet
networks:
  minio_webnet:
```

## dir

```
❯ tree                                                                      
.
├── docker-compose.yml
└── minio
    ├── config
    │   └── certs
    │       └── CAs
    ├── data1
    ├── data10
    ├── data11
    ├── data12
    ├── data2
    ├── data3
    ├── data4
    ├── data5
    ├── data6
    ├── data7
    ├── data8
    └── data9
```

**Comment by lddsb** [comment]
I have the same issue
### OS
`macOS Catalina 10.15`

### Docker Version

```
Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfc
 Built:             Thu Aug 29 05:26:49 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       6a30dfc
  Built:            Thu Aug 29 05:32:21 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

### docker-compose.yml

```
version: '3'
services:
    minio:
        image: minio/minio
        container_name: minio
        volumes:
          - ./minio/data1:/data1
          - ./minio/data2:/data2
          - ./minio/data3:/data3
          - ./minio/data4:/data4
        ports:
          - "9000:9000"
        environment:
          MINIO_ACCESS_KEY: my_access_key
          MINIO_SECRET_KEY: my_secret
        command: server /data1 /data2 /data3 /data4
        healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
          interval: 30s
          timeout: 20s
          retries: 3
```
