### ISSUE TITLE
Created bucket other nodes are not synchronized.

### ISSUE THREAD

**Issue by Jacky2** [minio/minio#8451]
## Current Behavior
I have an Minio cluster:

``` bash
minio --config-dir /minio/config server --address :9002 http://harbor-minio{1...4}/data{1...2}
``` 

docker-compose.yml

```yaml

version: '3.7'

services:
  harbor-minio:
    image: minio/minio:RELEASE.2019-09-18T21-55-05Z
    network_mode: "host"
    volumes:
      - ./data1-1:/data1
      - ./data1-2:/data2
      - ./config:/minio/config
    ports:
      - "9002:9002"
    expose:
      - 9002
    environment:
      MINIO_ACCESS_KEY: kfpt
      MINIO_SECRET_KEY: 12345678
    command: --config-dir /minio/config server --address :9002 http://harbor-minio{1...4}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9002/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    extra_hosts:
      - "harbor-minio1:10.1.20.33"
      - "harbor-minio2:10.1.20.34"
      - "harbor-minio3:10.1.20.35"
      - "harbor-minio4:10.1.20.36"

```

Created bucket other nodes are not synchronized.

There is a problem creating the bucket, but I can't reproduce this problem, because when I create the bucket again, it's normal.

I use java code but only configure one IP: 10.1.20.35:9002 to create bucket. After creation, sometimes I can see the bucket, sometimes I can't see the data directory of the server. Only one server has this bucket.

![no-1](https://user-images.githubusercontent.com/23411395/67658066-7e8a1c80-f993-11e9-9d8e-9eb769e3fb8d.png)
![1](https://user-images.githubusercontent.com/23411395/67658073-834ed080-f993-11e9-8f5b-ef39fa4422b9.png)
![2](https://user-images.githubusercontent.com/23411395/67658077-8649c100-f993-11e9-992f-69b0fcbca04a.png)
![3](https://user-images.githubusercontent.com/23411395/67658082-8944b180-f993-11e9-8447-35f4e83b745a.png)

## Environment
* Version used (`minio/minio:RELEASE.2019-09-18T21-55-05Z`):
