### ISSUE TITLE
service not accessible and no logs after deployed with kubernetes

### ISSUE THREAD

**Issue by neo-feng** [minio/minio#8523]
I deployed distributed minio servers in kubernetes using yaml file option as stated here - https://github.com/minio/minio/blob/master/docs/orchestration/kubernetes/k8s-yaml.md 
I followed guide above strictly, except that I added secret-volume to make ssl work
## Expected Behavior

all pods lauched and service accessible from browser

## Current Behavior

all pods lauched with no issues, however, service is not accessible from browser
and no logs at all from any pod (kubectl logs -n xxx minio-0) -- this is the most strange part

And standalone deployment is working and verified, only distributed one failed.

## Steps to Reproduce (for bugs)

1. deploy local storage in kubernetes
2. create secret for secret-volume
3. deploy minio via yaml files
4. try to access https://nodeip:port/minio/login

## Your Environment

* Version used (`minio version`): image: minio/minio:RELEASE.2019-10-12T01-39-57Z
* Environment name and version (e.g. nginx 1.9.1): kubernetes 1.15.2
* Server type and version: kubernetes 1.15.2
* Operating System and version (`uname -a`): centos 7.3

my yaml file: 
```
apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    app: minio
spec:
  clusterIP: None
  ports:
    - port: 9000
      name: minio
  selector:
    app: minio
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: minio
spec:
  serviceName: minio
  replicas: {{replicas}}
  template:
    metadata:
      labels:
        app: minio
    spec:
      volumes:
      - name: timezone-config
        hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
      - name: secret-volume
        secret:
          secretName: tls-ssl-minio
          items:
          - key: public.crt
            path: public.crt
          - key: private.key
            path: private.key
          - key: public.crt
            path: CAs/public.crt       
      containers:
      - name: minio
        env:
        - name: MINIO_ACCESS_KEY
          value: "xxxxxx"
        - name: MINIO_SECRET_KEY
          value: "xxxxx"
        image: minio/minio:RELEASE.2019-10-12T01-39-57Z
        args:
        - server
        - http://minio-{0...3}.minio.default.svc.cluster.local/data
        ports:
        - containerPort: 9000
        # These volume mounts are persistent. Each pod in the PetSet
        # gets a volume mounted based on this field.
        volumeMounts:
        - name: data
          mountPath: /data
        - name: timezone-config
          mountPath: /etc/localtime  
        - name: secret-volume
          mountPath: /root/.minio/certs           
          
  # These are converted to volume claims by the controller
  # and mounted at the paths mentioned above.
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
      # Uncomment and add storageClass specific to your requirements below. Read more https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1
      storageClassName: {{storageClassName}}
---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 35009
      protocol: TCP
  selector:
    app: minio
```

any suggestion is appreciated.
