### ISSUE TITLE
Distributed Mode with K8S DaemonSet Deployment Error: no endpoint pointing to the local machine is found

### ISSUE THREAD

**Issue by KrasusC** [minio/minio#8598]
Distributed Mode with K8S DaemonSet Deployment Error: no endpoint pointing to the local machine is found
## Current Behavior
/ # minio server http://127.0.0.2/data/minio http://127.0.0.3/data/minio http://127.0.0.4/data/minio http://127.0.0.5/data/minio
ERROR Invalid command line arguments: no endpoint pointing to the local machine is found
      > Please provide correct combination of local/remote paths
      HINT:
        For more information, please refer to https://docs.min.io/docs/minio-erasure-code-quickstart-guide

## Steps to Reproduce (for bugs)
This problem can be reproduced both on a Kind (https://kind.sigs.k8s.io/) cluster and a bare metal k8s cluster.
1. Create a Kind k8s cluster with 4 nodes:
```
➜  minio git:(master) ✗ kubectl get nodes -owide
NAME                 STATUS   ROLES    AGE   VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE                                  KERNEL-VERSION     CONTAINER-RUNTIME
kind-control-plane   Ready    master   31m   v1.15.3   172.17.0.5    <none>        Ubuntu Disco Dingo (development branch)   4.9.184-linuxkit   containerd://1.2.6-0ubuntu1
kind-worker          Ready    <none>   31m   v1.15.3   172.17.0.2    <none>        Ubuntu Disco Dingo (development branch)   4.9.184-linuxkit   containerd://1.2.6-0ubuntu1
kind-worker2         Ready    <none>   31m   v1.15.3   172.17.0.3    <none>        Ubuntu Disco Dingo (development branch)   4.9.184-linuxkit   containerd://1.2.6-0ubuntu1
kind-worker3         Ready    <none>   31m   v1.15.3   172.17.0.4    <none>        Ubuntu Disco Dingo (development branch)   4.9.184-linuxkit   containerd://1.2.6-0ubuntu1
```
2. Apply following minio YAML:
```
---
apiVersion: v1
kind: Secret
metadata:
  name: minio
  labels:
    name: minio
    release: release-name
type: Opaque
data:
  access-key: aW1wbHk= #imply
  secret-key: aW1wbHlwYXNzd29yZA== #implypassword
---
# headless service
apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    app: minio
spec:
  clusterIP: None
  ports:
    - port: 9000
      name: minio
  selector:
    app: minio
---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  type: ClusterIP
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: minio
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: minio
  labels:
    app: minio
spec:
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      # We only deploy minio to the specified nodes. select your nodes by using `kubectl label node hostname1 -l minio-server=true`
      #nodeSelector:
      #  minio-server: "true"
      # This is to maximize network performance, the headless service can be used to connect to a random host.
      # We're just using a hostpath. This path must be the same on all servers, and should be the largest, fastest block device you can fit.
      #hostNetwork: true
      volumes:
      - name: storage
        hostPath:
          path: /data/minio/
      containers:
      - name: minio
        env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio
              key: access-key
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio
              key: secret-key
        - name: MINIO_BROWSER
          value: "on"
        image: minio/minio:RELEASE.2019-10-12T01-39-57Z
        # Unfortunately you must manually define each server. Perhaps autodiscovery via DNS can be implemented in the future.
        args:
        - server
        - http://172.17.0.5/data/minio
        - http://172.17.0.4/data/minio
        - http://172.17.0.3/data/minio
        - http://172.17.0.2/data/minio
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: storage
          mountPath: /data/minio/
```
3.  Check pod logs:
```
ERROR Invalid command line arguments: no endpoint pointing to the local machine is found
      > Please provide correct combination of local/remote paths
      HINT:
        For more information, please refer to https://docs.min.io/docs/minio-erasure-code-quickstart-guide
```

## Your Environment]
* Version used (`minio version`):RELEASE.2019-10-12T01-39-57Z
* Environment name and version (e.g. nginx 1.9.1): Kubernetes: v1.16.3, Docker 17.04.0-ce Kind 0.5.1
