### ISSUE TITLE
MINIO_SSE_MASTER_KEY_FILE environment variable has been removed from Dockerfile.

### ISSUE THREAD

**Issue by lucas-dehandschutter** [minio/minio#8757]
In June, I contributed to minio with the pull request [7825](https://github.com/minio/minio/pull/7825) to add the ability to setup SSE encryption with a key hosted in a Docker secret. This feature was in part implemented in the Dockerfile of minio in wich I added a MINIO_SSE_MASTER_KEY_FILE environment variable. The presence of this variable automatically checked the presence of the docker secret and applied SSE encryption.

As I'm trying to upgrade our minio clusters, I've discovered that this environment variable has disapeared and has been replace by MINIO_KMS_MASTER_KEY_FILE environment variable.

This change has produced a real regretion on our minio cluster!

Now, the minio docker image logs displays the following:

>  Server startup failed with 'Unable to initialize config system: madmin: invalid AEAD algorithm ID'

## Expected Behavior

An evironment variable MINIO_SSE_MASTER_KEY_FILE is set and then, minio read the encryption key from the docker secret located at /run/secret/sse_master_key

## Current Behavior

The environment variable has disappeared and the minio cluster is no longer starting due to an error.

## Possible Solution

Please let the configuration of the encryption free, don't force kms and allow the MINIO_SSE_MASTER_KEY_FILE environment variable.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by nitisht** [comment]
we'll take a look @lucas-dehandschutter // cc @aead

**Comment by aead** [comment]
This looks like a new config format regression. (/cc @harshavardhana) However, according to the docker script this env var should be honored (See: https://github.com/minio/minio/blob/master/dockerscripts/docker-entrypoint.sh#L85). What is the version you are trying to update to (See issue template)

**Comment by harshavardhana** [comment]
Master key and config init has nothing in common, what is happening here is config initialization failed, we need to know the server version under use. 

looks like you were using some development version and then upgraded. Because we migrated to a different sio package called secure-io which has a different AEAD id

**Comment by lucas-dehandschutter** [comment]
Hello,

The last version working on our side is the RELEASE.2019-10-12T01-39-57z
Then a change was done in commit 8392 to remove my environment variable.
You can see the change history [here](https://github.com/minio/minio/commit/ee4a6a823df5195dccec20e39d85a959368298e0#diff-3254677a7917c6c01f55212f86c57fbf
)

**Comment by harshavardhana** [comment]
@lucas-dehandschutter as I repeated your issue is not related to reading master key. It is related to backend config which is encrypted with your access credentials.

Please explain in detail what you did to get to this situation and what is the current release that is under use. From which version to which version did you upgrade and how you did it.

This will help us reproduce the issue. Issue description doesn't explain any of this, seems to directly go into assumptions.

**Comment by lucas-dehandschutter** [comment]
@harshavardhana I was initially running on a minio RELEASE.2019-09-18T21-55-05Z. My minio cluster is running in a docker swarm cluster. 

The minio instances are deployed with the following code in my docker-compose:

```
services:
  minio1:
    image: myrepo/s3/minio:RELEASE.2019-09-18T21-55-05Z
    hostname: minio1
    volumes:
      - minio1-data:/export
    deploy:
      placement:
        constraints:
          - node.labels.minio1==true
    command: "${MINIO_COMMAND}"
    environment:
      - MINIO_SSE_AUTO_ENCRYPTION=on
    secrets:
      - source: minio_secret_key
        target: secret_key
      - source: minio_access_key
        target: access_key
      - source: minio_encryption_key
        target: sse_master_key

  minio2:
   ...
```
As you can see, the access_key and secret_key are passed via docker secrets as for the sse_master_key.

The minio command passed to the deployment script is:

`server http://minio1/export http://minio2/export http://minio3/export http://minio4/export`

I first tried to update my docker compose with minio:RELEASE.2019-12-19T22-52-26Z but I did a mistake as I did not build minio using  my own Dockerfile (which is based on the official minio docker image and create a user which has access to my swarm binded volumes and then run minio with this user...). So the minio instances started but, logically, didnt has access to minio volumes.

I decided to quickly rollback to the previous minio version (RELEASE.2019-09-18T21-55-05Z) but the minio instances were crashing with the following message: 

> Error Unable to initialize config system: invalid character 'R' looking for beginning of value

I've fixed this issue by removing the minio config in each nodes located in .minio.sys/config.

After that last operation, my minio cluster was back.

Today,  I tried to migrate to a more recent version of minio (built with my dockerfile this time), and got the following error message at minio's boot:

> Server startup failed with 'Unable to initialize config system: madmin: invalid AEAD algorith ID' 
> Server switching to safe mode
> Please use 'mc admin config' to fix this issue

I can still authenticate to minio but there si no more bucket present.

**Comment by harshavardhana** [comment]
Thanks @lucas-dehandschutter let me reproduce this.

**Comment by harshavardhana** [comment]
>     image: myrepo/s3/minio:RELEASE.2019-09-18T21-55-05Z

Here is the thing @lucas-dehandschutter are you modifying the backend config after the fact the server is up, can you reproduce this without building custom container? because I can't seem to be able to reproduce it. 

```
~ docker-compose up -f old.yaml
```

Now stop and update
```
~ docker-compose up -f new.yaml
minio2_1_f22408ea487d | Attempting encryption of all config, IAM users and policies on MinIO backend
minio2_1_f22408ea487d | Configuration file config/config.json migrated from version '33' to new KV format successfully.
minio2_1_f22408ea487d | Status:         8 Online, 0 Offline. 
minio2_1_f22408ea487d | Endpoint:  http://172.25.0.5:9000  http://127.0.0.1:9000
```

```yaml
version: '3.7'

# starts 4 docker containers running minio server instances. Each
# minio server's web interface will be accessible on the host at port
# 9001 through 9004.
services:
  minio1:
    image: minio/minio:RELEASE.2020-01-03T19-12-21Z
    volumes:
      - data1-1:/data1
      - data1-2:/data2
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio{1...4}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio2:
    image: minio/minio:RELEASE.2020-01-03T19-12-21Z
    volumes:
      - data2-1:/data1
      - data2-2:/data2
    ports:
      - "9002:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio{1...4}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio3:
    image: minio/minio:RELEASE.2020-01-03T19-12-21Z
    volumes:
      - data3-1:/data1
      - data3-2:/data2
    ports:
      - "9003:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio{1...4}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio4:
    image: minio/minio:RELEASE.2020-01-03T19-12-21Z
    volumes:
      - data4-1:/data1
      - data4-2:/data2
    ports:
      - "9004:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio{1...4}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  data1-1:
  data1-2:
  data2-1:
  data2-2:
  data3-1:
  data3-2:
  data4-1:
  data4-2:
```

**Comment by harshavardhana** [comment]
@lucas-dehandschutter I am going to close this issue as not reproducible at the moment. Unless you can reply back to this issue on my questions.

**Comment by lucas-dehandschutter** [comment]
@harshavardhana here is a way to reproduce my initial issue from scratch.

1. Create directories for minio data

```
    mkdir /tmp/minio1
    mkdir /tmp/minio2
    mkdir /tmp/minio3
    mkdir /tmp/minio4
```

2. Create a Docker Swarm (important as we are using Swarm secrets to configure KMS)

`docker swarm init`

3. Create secrets for access key, secret key and encryptkey 
```
echo "admin" | docker secret create minio_access_key -
echo "password123" | docker secret create minio_secret_key -
echo "encryptkey:AC27C910D2EA05B3968EE039B7C2FB775D4C9DD2A1DA98DE7E45649C7D3ABB4D" | docker secret create minio_encryption_key -
```

4. Deploy the docker-compose-old.yaml which starts 4 minio RELEASE.2019-09-18T21-55-05Z (the last one which worked for me)
  
```
version: '3.3'

services:
  minio1:
    image: minio/minio:RELEASE.2019-09-18T21-55-05Z
    hostname: minio1
    volumes:
      - minio1-data:/export
    ports:
      - "9001:9000"
    environment:
      - MINIO_SSE_AUTO_ENCRYPTION=on
    networks:
      - minio_distributed    
    command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export
    secrets:
      - source: minio_secret_key
        target: secret_key
      - source: minio_access_key
        target: access_key
      - source: minio_encryption_key
        target: sse_master_key


  minio2:
    image: minio/minio:RELEASE.2019-09-18T21-55-05Z
    hostname: minio2
    volumes:
      - minio2-data:/export
    ports:
      - "9002:9000"
    networks:
      - minio_distributed  
    environment:
      - MINIO_SSE_AUTO_ENCRYPTION=on
    command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export
    secrets:
      - source: minio_secret_key
        target: secret_key
      - source: minio_access_key
        target: access_key
      - source: minio_encryption_key
        target: sse_master_key


  minio3:
    image: minio/minio:RELEASE.2019-09-18T21-55-05Z
    hostname: minio3
    volumes:
      - minio3-data:/export
    ports:
      - "9003:9000"
    networks:
      - minio_distributed    
    environment:
      - MINIO_SSE_AUTO_ENCRYPTION=on
    command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export
    secrets:
      - source: minio_secret_key
        target: secret_key
      - source: minio_access_key
        target: access_key
      - source: minio_encryption_key
        target: sse_master_key


  minio4:
    image: minio/minio:RELEASE.2019-09-18T21-55-05Z
    hostname: minio4
    volumes:
      - minio4-data:/export
    ports:
      - "9004:9000"
    networks:
      - minio_distributed        
    environment:
      - MINIO_SSE_AUTO_ENCRYPTION=on
    command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export
    secrets:
      - source: minio_secret_key
        target: secret_key
      - source: minio_access_key
        target: access_key
      - source: minio_encryption_key
        target: sse_master_key


volumes:
  minio1-data:
    driver: local
    driver_opts:
        type: none
        device: /tmp/minio1
        o: bind
  minio2-data:
    driver: local
    driver_opts:
        type: none
        device: /tmp/minio2
        o: bind  
  minio3-data:
    driver: local  
    driver_opts:
        type: none
        device: /tmp/minio3
        o: bind  
  minio4-data:
    driver: local
    driver_opts:
        type: none
        device: /tmp/minio4
        o: bind  

  
secrets:
  minio_access_key:
    external: true
  minio_secret_key:
    external: true
  minio_encryption_key:
    external: true

networks:
  minio_distributed:
    driver: overlay
    driver_opts:
      encrypted: "true"
    internal: true
```

Deploy it with the following command

`docker stack deploy --compose-file docker-compose-old.yml minio-stack`



5. We can verify that all minio instances are up:
```

$> docker service ls
   ID                  NAME                 MODE                REPLICAS            IMAGE                                      PORTS
   v9jgz3qu0mfz        minio-stack_minio1   replicated          1/1                 minio/minio:RELEASE.2019-09-18T21-55-05Z   *:9001->9000/tcp
   i9kra99orkca        minio-stack_minio2   replicated          1/1                 minio/minio:RELEASE.2019-09-18T21-55-05Z   *:9002->9000/tcp
   ttupuchd4ddv        minio-stack_minio3   replicated          1/1                 minio/minio:RELEASE.2019-09-18T21-55-05Z   *:9003->9000/tcp
   r5ydqlyfx1q5        minio-stack_minio4   replicated          1/1                 minio/minio:RELEASE.2019-09-18T21-55-05Z   *:9004->9000/tcp
```

6. Connect to one minio node, create a bucket and upload some files...

7. Update the docker compose with a more recent version of minio a deploy it (here i'm using RELEASE.2020-01-03T19-12-21Z). The version of minio is the only thing that has change in the following docker-compose file.

```
version: '3.3'

services:
  minio1:
    image: minio/minio:RELEASE.2020-01-03T19-12-21Z
    hostname: minio1
    volumes:
      - minio1-data:/export
    ports:
      - "9001:9000"
    environment:
      - MINIO_SSE_AUTO_ENCRYPTION=on
    networks:
      - minio_distributed    
    command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export
    secrets:
      - source: minio_secret_key
        target: secret_key
      - source: minio_access_key
        target: access_key
      - source: minio_encryption_key
        target: sse_master_key


  minio2:
    image: minio/minio:RELEASE.2020-01-03T19-12-21Z
    hostname: minio2
    volumes:
      - minio2-data:/export
    ports:
      - "9002:9000"
    networks:
      - minio_distributed  
    environment:
      - MINIO_SSE_AUTO_ENCRYPTION=on
    command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export
    secrets:
      - source: minio_secret_key
        target: secret_key
      - source: minio_access_key
        target: access_key
      - source: minio_encryption_key
        target: sse_master_key


  minio3:
    image: minio/minio:RELEASE.2020-01-03T19-12-21Z
    hostname: minio3
    volumes:
      - minio3-data:/export
    ports:
      - "9003:9000"
    networks:
      - minio_distributed    
    environment:
      - MINIO_SSE_AUTO_ENCRYPTION=on
    command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export
    secrets:
      - source: minio_secret_key
        target: secret_key
      - source: minio_access_key
        target: access_key
      - source: minio_encryption_key
        target: sse_master_key


  minio4:
    image: minio/minio:RELEASE.2020-01-03T19-12-21Z
    hostname: minio4
    volumes:
      - minio4-data:/export
    ports:
      - "9004:9000"
    networks:
      - minio_distributed        
    environment:
      - MINIO_SSE_AUTO_ENCRYPTION=on
    command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export
    secrets:
      - source: minio_secret_key
        target: secret_key
      - source: minio_access_key
        target: access_key
      - source: minio_encryption_key
        target: sse_master_key

volumes:
  minio1-data:
    driver: local
    driver_opts:
        type: none
        device: /tmp/minio1
        o: bind
  minio2-data:
    driver: local
    driver_opts:
        type: none
        device: /tmp/minio2
        o: bind  
  minio3-data:
    driver: local  
    driver_opts:
        type: none
        device: /tmp/minio3
        o: bind  
  minio4-data:
    driver: local
    driver_opts:
        type: none
        device: /tmp/minio4
        o: bind  
  
secrets:
  minio_access_key:
    external: true
  minio_secret_key:
    external: true
  minio_encryption_key:
    external: true

networks:
  minio_distributed:
    driver: overlay
    driver_opts:
      encrypted: "true"
    internal: true
```

Deploy it   

`   docker stack deploy --compose-file docker-compose-new.yml minio-stack`

8. Connect to minio again and try to download a file, you'll get a error: **"KMS not configured for a server side encrypted object"**



9. Rollback to the previous version: 
   
`   docker stack deploy --compose-file docker-compose-old.yml minio-stack`

10. Connect to minio again... **All buckets have disapeared!** Minio is not supporting rollback so I've discovered that we need to delete config to repair minio.

11. Stop all minio node:

`    docker stack rm minio-stack`

12. Remove the configs in all nodes:

```
    sudo rm -R /tmp/minio1/.minio.sys/config/*
    sudo rm -R /tmp/minio2/.minio.sys/config/*
    sudo rm -R /tmp/minio3/.minio.sys/config/*
    sudo rm -R /tmp/minio4/.minio.sys/config/*
```

13. Deploy the old version again:

`    docker stack deploy --compose-file docker-compose-old.yml minio-stack`

14. Connect to minio again, we're now able to download the files again
