### ISSUE TITLE
Binary not found: "server" when using vault-secrets-webhook on kubernetes

### ISSUE THREAD

**Issue by DrissiReda** [minio/minio#8791]
The [vault-secrets-webhook](https://github.com/innovia/kubernetes-mutation-webhook-vault-secrets/tree/master/helm-chart) works as expected with a barebone alpine pod. 
The same setup seems to work with minio until it has to run the minio provided commands

These are the minio logs
```bash
time="2020-01-10T16:38:09Z" level=info msg="Logging into Vault Kubernetes backend using the role: minio"
time="2020-01-10T16:38:09Z" level=info msg="Getting Service Account Token"
time="2020-01-10T16:38:09Z" level=info msg="Getting Vault secrets from path: secret/minio"
time="2020-01-10T16:38:09Z" level=info msg="Processing environment variables from Vault secret"
time="2020-01-10T16:38:09Z" level=info msg="Launching command"
time="2020-01-10T16:38:09Z" level=fatal msg="Binary not found: server"
```
I only added the annotations and a service account. As you can see, the vault part of my code works properly with no problems.

<details>
<summary>
minio-standalone-deployment.yaml
</summary>

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: minio
---
apiVersion: apps/v1
kind: Deployment
metadata:
  # This name uniquely identifies the Deployment
  name: minio
spec:
  selector:
    matchLabels:
      app: minio  # has to match .spec.template.metadata.labels
  strategy:
    # Specifies the strategy used to replace old Pods by new ones
    # Refer: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy
    type: Recreate
  template:
    metadata:
      annotations:
        vault.security/enabled: "true"
        vault.security/vault-addr: "http://192.168.1.22:8200"
        vault.security/vault-role: "minio"
        vault.security/vault-path: "secret/minio"
        vault.security/vault-tls-secret-name: "vault-minio-ca"
      labels:
        # This label is used as a selector in Service definition
        app: minio
    spec:
      serviceAccountName: minio
      # Volumes used by this deployment
      volumes:
      - name: data
        # This volume is based on PVC
        persistentVolumeClaim:
          # Name of the PVC created earlier
          claimName: minio-pv-claim
      containers:
      - name: minio
        # Volume mounts for this container
        volumeMounts:
        # Volume 'data' is mounted to path '/data'
        - name: data 
          mountPath: "/data"
        # Pulls the lastest Minio image from Docker Hub
        image: minio/minio:RELEASE.2020-01-03T19-12-21Z
        args:
        - server
        - /data
        env:
        # MinIO access key and secret key
        - name: MINIO_ACCESS_KEY
          value: "INIO_ACCESS_KEY"
        - name: MINIO_SECRET_KEY
          value: "minio123"
        - name: NOTH
          value: vault:MINIO_ACCESS_KEY
        ports:
        - containerPort: 9000
        # Readiness probe detects situations when MinIO server instance
        # is not ready to accept traffic. Kubernetes doesn't forward
        # traffic to the pod while readiness checks fail.
        readinessProbe:
          httpGet:
            path: /minio/health/ready
            port: 9000
          initialDelaySeconds: 120
          periodSeconds: 20
        # Liveness probe detects situations where MinIO server instance
        # is not working properly and needs restart. Kubernetes automatically
        # restarts the pods if liveness checks fail.
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: 9000
          initialDelaySeconds: 120
          periodSeconds: 20

```
</details>

For reference, it works perfectly for this alpine

<details>
<summary>
app.yaml
</summary>

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: vault-agent-demo
  replicas: 1
  template:
    metadata:
      annotations:
        vault.security/enabled: "true"
        vault.security/vault-addr: "http://192.168.1.22:8200"
        vault.security/vault-role: "app"
        vault.security/vault-path: "secret/app"
        vault.security/vault-tls-secret-name: "vault-app-ca"
      labels:
        app: vault-agent-demo
    spec:
      serviceAccountName: app
      containers:
      - name: app
        image: alpine
        command: ["/bin/sh", "-c"]
        args: ["echo $password"]
        env:
        - name: password
          value: vault:PASS
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app

```
</details>

<details>
<summary>
Alpine app logs
</summary>

```bash
time="2020-01-10T16:43:44Z" level=info msg="Logging into Vault Kubernetes backend using the role: app"
time="2020-01-10T16:43:44Z" level=info msg="Getting Service Account Token"
time="2020-01-10T16:43:44Z" level=info msg="Getting Vault secrets from path: secret/app"
time="2020-01-10T16:43:44Z" level=info msg="Processing environment variables from Vault secret"
time="2020-01-10T16:43:44Z" level=info msg="Launching command"
YOuShallNotPASS
```
</details>

For further information:

<details>
<summary>
minio pod
</summary>

```yaml
Name:         minio-56f59bc55-kjpd4
Namespace:    default
Priority:     0
Node:         red-hp-zbook-studio-g5/192.168.1.22
Start Time:   Fri, 10 Jan 2020 17:34:59 +0100
Labels:       app=minio
              pod-template-hash=56f59bc55
Annotations:  vault.security/enabled: true
              vault.security/vault-addr: http://192.168.1.22:8200
              vault.security/vault-path: secret/minio
              vault.security/vault-role: minio
              vault.security/vault-tls-secret-name: vault-minio-ca
Status:       Running
IP:           10.42.0.157
IPs:
  IP:           10.42.0.157
Controlled By:  ReplicaSet/minio-56f59bc55
Init Containers:
  init:
    Container ID:  containerd://1adbea5a382ed4cb944bca9c1574e8b52456f2fb72d11888e5ec1fccee65ddc5
    Image:         innovia/vault-env:1.1.0
    Image ID:      docker.io/innovia/vault-env@sha256:12d7b3340e3036ec755c578812cb2eb10d65b71739419c1147e883c325b91a75
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
      -c
      cp /usr/local/bin/vault-env /vault/
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Fri, 10 Jan 2020 17:34:59 +0100
      Finished:     Fri, 10 Jan 2020 17:34:59 +0100
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from minio-token-nrgtc (ro)
      /vault from vault-env (rw)
Containers:
  minio:
    Container ID:  containerd://d924a8d43db9a06c6cc76f4b51d100f434a9f104717394d38a904f1ea682a8c0
    Image:         minio/minio:RELEASE.2020-01-03T19-12-21Z
    Image ID:      docker.io/minio/minio@sha256:f00aa6ef2b7286dc620aca168bf1bc9280db8461a02d293d5ae491b3d6d3006b
    Port:          9000/TCP
    Host Port:     0/TCP
    Command:
      /vault/vault-env
    Args:
      server
      /data
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Fri, 10 Jan 2020 17:45:58 +0100
      Finished:     Fri, 10 Jan 2020 17:45:58 +0100
    Ready:          False
    Restart Count:  7
    Liveness:       http-get http://:9000/minio/health/live delay=120s timeout=1s period=20s #success=1 #failure=3
    Readiness:      http-get http://:9000/minio/health/ready delay=120s timeout=1s period=20s #success=1 #failure=3
    Environment:
      MINIO_ACCESS_KEY:  INIO_ACCESS_KEY
      MINIO_SECRET_KEY:  minio123
      NOTH:              vault:MINIO_ACCESS_KEY
      VAULT_ADDR:        http://192.168.1.22:8200
      VAULT_PATH:        secret/minio
      VAULT_ROLE:        minio
      VAULT_CAPATH:      /etc/tls/ca.pem
    Mounts:
      /data from data (rw)
      /etc/tls from tls (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from minio-token-nrgtc (ro)
      /vault from vault-env (rw)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  minio-pv-claim
    ReadOnly:   false
  minio-token-nrgtc:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  minio-token-nrgtc
    Optional:    false
  vault-env:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  tls:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  vault-minio-ca
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                 From                             Message
  ----     ------     ----                ----                             -------
  Normal   Scheduled  <unknown>           default-scheduler                Successfully assigned default/minio-56f59bc55-kjpd4 to red-hp-zbook-studio-g5
  Normal   Pulled     15m                 kubelet, red-hp-zbook-studio-g5  Container image "innovia/vault-env:1.1.0" already present on machine
  Normal   Created    15m                 kubelet, red-hp-zbook-studio-g5  Created container init
  Normal   Started    15m                 kubelet, red-hp-zbook-studio-g5  Started container init
  Normal   Created    14m (x4 over 15m)   kubelet, red-hp-zbook-studio-g5  Created container minio
  Normal   Started    14m (x4 over 15m)   kubelet, red-hp-zbook-studio-g5  Started container minio
  Normal   Pulled     14m (x5 over 15m)   kubelet, red-hp-zbook-studio-g5  Container image "minio/minio:RELEASE.2020-01-03T19-12-21Z" already present on machine
  Warning  BackOff    41s (x74 over 15m)  kubelet, red-hp-zbook-studio-g5  Back-off restarting failed container
```

</details>

<details>
<summary>
alpine app pod
</summary>

```yaml
Name:         app-7c5b8fc6d-flzpl
Namespace:    default
Priority:     0
Node:         red-hp-zbook-studio-g5/192.168.1.22
Start Time:   Fri, 10 Jan 2020 17:37:48 +0100
Labels:       app=vault-agent-demo
              pod-template-hash=7c5b8fc6d
Annotations:  vault.security/enabled: true
              vault.security/vault-addr: http://192.168.1.22:8200
              vault.security/vault-path: secret/app
              vault.security/vault-role: app
              vault.security/vault-tls-secret-name: vault-app-ca
Status:       Running
IP:           10.42.0.159
IPs:
  IP:           10.42.0.159
Controlled By:  ReplicaSet/app-7c5b8fc6d
Init Containers:
  init:
    Container ID:  containerd://da8e40b16a6ea7ce09753113aa91062a46cd7c628679f3db6c66656eec7b043f
    Image:         innovia/vault-env:1.1.0
    Image ID:      docker.io/innovia/vault-env@sha256:12d7b3340e3036ec755c578812cb2eb10d65b71739419c1147e883c325b91a75
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
      -c
      cp /usr/local/bin/vault-env /vault/
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Fri, 10 Jan 2020 17:37:49 +0100
      Finished:     Fri, 10 Jan 2020 17:37:49 +0100
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from app-token-cwnjj (ro)
      /vault from vault-env (rw)
Containers:
  app:
    Container ID:  containerd://e452955e8f50827f42232b8c3fa5e7443a4e3c737565c8c0861c8d27418fc635
    Image:         alpine
    Image ID:      docker.io/library/alpine@sha256:2171658620155679240babee0a7714f6509fae66898db422ad803b951257db78
    Port:          <none>
    Host Port:     <none>
    Command:
      /vault/vault-env
    Args:
      /bin/sh
      -c
      echo $password
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Fri, 10 Jan 2020 17:48:50 +0100
      Finished:     Fri, 10 Jan 2020 17:48:50 +0100
    Ready:          False
    Restart Count:  7
    Environment:
      password:      vault:PASS
      VAULT_ADDR:    http://192.168.1.22:8200
      VAULT_PATH:    secret/app
      VAULT_ROLE:    app
      VAULT_CAPATH:  /etc/tls/ca.pem
    Mounts:
      /etc/tls from tls (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from app-token-cwnjj (ro)
      /vault from vault-env (rw)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  app-token-cwnjj:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  app-token-cwnjj
    Optional:    false
  vault-env:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  tls:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  vault-app-ca
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                   From                             Message
  ----     ------     ----                  ----                             -------
  Normal   Scheduled  <unknown>             default-scheduler                Successfully assigned default/app-7c5b8fc6d-flzpl to red-hp-zbook-studio-g5
  Normal   Pulled     13m                   kubelet, red-hp-zbook-studio-g5  Container image "innovia/vault-env:1.1.0" already present on machine
  Normal   Created    13m                   kubelet, red-hp-zbook-studio-g5  Created container init
  Normal   Started    13m                   kubelet, red-hp-zbook-studio-g5  Started container init
  Normal   Pulling    13m                   kubelet, red-hp-zbook-studio-g5  Pulling image "alpine"
  Normal   Pulled     13m                   kubelet, red-hp-zbook-studio-g5  Successfully pulled image "alpine"
  Normal   Created    12m (x4 over 13m)     kubelet, red-hp-zbook-studio-g5  Created container app
  Normal   Started    12m (x4 over 13m)     kubelet, red-hp-zbook-studio-g5  Started container app
  Normal   Pulled     12m (x4 over 13m)     kubelet, red-hp-zbook-studio-g5  Container image "alpine" already present on machine
  Warning  BackOff    3m32s (x49 over 13m)  kubelet, red-hp-zbook-studio-g5  Back-off restarting failed container

```
</details>
