### ISSUE TITLE
kubernetes: uploading files works through a port-forward, but not through an ingress

### ISSUE THREAD

**Issue by yoe** [minio/minio#8810]
I'm trying to develop an app that needs to have an object store, and am using minio inside minikube to help me develop it. Uploading files to minio seems to work with port-forward, but the upload gets stuck after transferring 100% of the files when using an ingress

## Expected Behavior
After starting minikube, creating a pod for minio, and creating an ingress, logging in through a browser, creating a bucket, and adding a file to that bucket will work.

## Current Behavior
When adding a file, the transfer seems to succeed and reaches "100%". However, the blue "uploading" message remains; closing it will create a warning that this will abort the upload, and aborting it shows that no objects are created.

## Steps to Reproduce (for bugs)
1. Install minikube
2. Run `minikube start`
3. After that finished, create the following YAML file, and apply it with `kubectl apply -f`:

```yaml
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  serviceName: "minio"
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio
        ports:
        - containerPort: 9000
          name: minio
        args:
        - server
        - "/data"
        env:
        - name: MINIO_ACCESS_KEY
          value: minio
        - name: MINIO_SECRET_KEY
          value: foobar
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    app: minio
spec:
  ports:
  - port: 9000
    name: minio
  clusterIP: None
  selector:
    app: minio
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: minio
spec:
  rules:
  - host: minio.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: minio
          servicePort: 9000
```
4. Create a `/etc/hosts` entry for `minio.example.com` that points to whatever `minikube ip` points to
5. Open web browser, and enter `minio.example.com` as URL
6. Log in, add a bucket
7. Try to upload a file to that bucket (fails)
8. Run `kubectl port-forward svc/minio 9000`
9. Go back to browser, enter `localhost:9000` as URL
10. Log in, add a file to the bucket created in step 6 (succeeds)

(note: yaml file does not create any volumes for brevity, but it fails with a volume too)

## Your Environment
* Version used (`minio version`): `2020-01-03T19:12:21Z`; runtime `Version: go1.13.5 | CPUs: 4`
* Environment name and version (e.g. nginx 1.9.1): docker file, inside kubernetes
