### ISSUE TITLE
Node data is lost after mounting a new disk

### ISSUE THREAD

**Issue by jinnzy** [minio/minio#8829]
I replaced the original disk with 4 new disks on a minio node. When restarting, I used `mc admin heal -r --scan deep minio` to repair, but the node data was not recovered.
## Expected Behavior
![image](https://user-images.githubusercontent.com/33449123/72516786-380ad680-388d-11ea-81ab-17b3e27c3f87.png)

## Current Behavior
![image](https://user-images.githubusercontent.com/33449123/72516693-17428100-388d-11ea-9090-a7396ed00de3.png)

## Steps to Reproduce (for bugs)
```
version: '3.7'

services:
  minio:
    container_name: minio
    restart: always
    image: minio/minio:RELEASE.2019-09-05T23-24-38Z
    volumes:
      - /data/disk01:/data01
      - /data/disk02:/data02
      - /data/disk03:/data03
      - /data/disk04:/data04
    environment:
      MINIO_ACCESS_KEY: 0ALFWIBZPH9RC5MD
      MINIO_SECRET_KEY: b0mxwap42ygYtfBnDsQrzkdNov6j9SLFTMZeOPu1UlhqGW3KXE8H7AiVIcRC5JPu
    command: server  http://172.31.101.139/data{01...04}  http://172.31.101.140/data{01...04}  http://172.31.101.141/data{01...04}  http://172.31.101.142/data{01...04} 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    network_mode: host
```
172.31.101.139:
1. cd /opt/minio ; docker-compose down
2. rm -rf /data/disk01 /data/dis02 /data/disk03 /data/disk04 ; mkdir /data/disk{01..04}
3. mount /dev/sdd /data/disk03
4. mount /dev/sdb /data/disk01
5. mount /dev/sdc /data/disk02
6. mount /dev/sde /data/disk04
7. docker-compose up -d
8.  mc admin heal -r --scan deep  minio
 ◓  spinnaker-dedicated-cloud/front50/projects/last-modified.json
    0/2,615 objects; 65 MiB in 59s
    ┌────────┬───────┬─────────────────────┐
    │ Green  │ 2,622 │ 100.0% ████████████ │
    │ Yellow │     0 │   0.0%              │
    │ Red    │     0 │   0.0%              │
    │ Grey   │     0 │   0.0%              │
    └────────┴───────┴─────────────────────┘

## Your Environment
minio/minio:RELEASE.2019-09-05T23-24-38Z
centos7
3.10.0-514.26.1.el7.x86_64
```
/ # mc admin info server minio 
●  172.31.101.139:9000
   Uptime: 9 minutes 
  Version: 2019-09-05T23:24:38Z
  Storage: Used 31 GiB, Free 708 GiB
   Drives: 4/4 OK

   CPU        min        avg      max
   current    0.20%      0.23%    0.25%
   historic   0.04%      12.91%    119.53%

   MEM        usage
   current    69 MiB
   historic   69 MiB


●  172.31.101.140:9000
   Uptime: 2 hours 
  Version: 2019-09-05T23:24:38Z
  Storage: Used 31 GiB, Free 708 GiB
   Drives: 4/4 OK

   CPU        min        avg      max
   current    0.46%      0.47%    0.48%
   historic   0.03%      27.30%    315.73%

   MEM        usage
   current    202 MiB
   historic   176 MiB


●  172.31.101.141:9000
   Uptime: 2 hours 
  Version: 2019-09-05T23:24:38Z
  Storage: Used 31 GiB, Free 708 GiB
   Drives: 4/4 OK

   CPU        min        avg      max
   current    8.99%      9.00%    9.02%
   historic   0.04%      30.39%    321.32%

   MEM        usage
   current    202 MiB
   historic   197 MiB


●  172.31.101.142:9000
   Uptime: 2 hours 
  Version: 2019-09-05T23:24:38Z
  Storage: Used 31 GiB, Free 708 GiB
   Drives: 4/4 OK

   CPU        min        avg      max
   current    0.65%      0.66%    0.67%
   historic   0.03%      26.74%    299.88%

   MEM        usage
   current    202 MiB
   historic   154 MiB

```
