### ISSUE TITLE
Homepage does not load when being proxied with nginx-ingress

### ISSUE THREAD

**Issue by onedr0p** [minio/minio#8835]
## Expected Behavior
Minio homepage should load when I hit it thru `nginx-ingress`

## Current Behavior
When I use kubectl and proxy it to my local machine I can access it via `localhost:9000`. However when I try to access it via my web URL the background loads and the spinner is stuck spinning. After awhile the assets (js and pngs etc…) return a 504. Other services using this nginx-ingress are loading just fine. SSL is being offloaded outside my cluster…

## Steps to Reproduce (for bugs)
1. Deploy k3s
2. Deploy metallb
3. Deploy nginx-ingress
4. Deploy minio

## Your Environment
* Version used: RELEASE.2020-01-16T22-40-29Z
* Environment name and version: Kubernetes v1.16.3-k3s.2
* Server type and version: Ubuntu 18.04.3
* Operating System and version: Linux k3s-master 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

nginx-ingress Helm values
```yaml
---
controller:
  replicaCount: 2
  image:
    repository: quay.io/kubernetes-ingress-controller/nginx-ingress-controller
    tag: 0.27.0
  service:
    loadBalancerIP: 192.168.42.100
    externalTrafficPolicy: Local
  resources:
    requests:
      memory: 500Mi
      cpu: 25m
    limits:
      memory: 600Mi
defaultBackend:
  enabled: false
```

minio Helm values
```yaml
---
image:
  repository: minio/minio
  tag: RELEASE.2020-01-16T22-40-29Z
persistence:
  enabled: true
  existingClaim: "nfs-data-pvc"
  subPath: "minio"
accessKey: "mah8ein6tow6Ahhg3ahR"
secretKey: "ootoh0veik5teepheez7zei6Choa7ohH5jangeek"
ingress:
  enabled: true
  hosts:
    - minio.mysite.io
  annotations:
    kubernetes.io/ingress.class: nginx
resources:
  requests:
    memory: 350Mi
    cpu: 25m
  limits:
    memory: 1000Mi
```

metallb Helm values
```yaml
---
configInline:
  address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 192.168.42.100-192.168.42.105
```
