### ISSUE TITLE
Automatically provision user account keys on init

### ISSUE THREAD

**Issue by cbluth** [minio/minio#8885]
**Is your feature request related to a problem?**: Yes
Problem:
- i have a development environment with a running instance of minio-distributed in kubernetes, i deploy via docker image `minio/minio:latest`
- i have a nightly process that deletes all components of minio from kubernetes, even volumes, and then re-creates everything from scratch with a clean-slate, meaning everything is a fresh instantiation of all minio components, including freshly cleaned and empty volumes.
- this nightly process also provisions a static set of data from a different environment, and created the buckets and restores data into the buckets.
- this nightly process also provisions a static set of user credentials/keys and policies.
- the combination of all of this can take some time, and my nightly process script is a bit "hacky".

**Describe the solution you'd like**
i imagine a feature that would allow me to provision user accounts on instantiation of the minio cluster.
currently, my minio statefulset in kubernetes looks like this:
```yaml
      containers:
      - args:
        - server
        - http://minio-{0...2}.minio-headless.minio.svc/data{1...2}/minio
        env:
        - name: MINIO_ACCESS_KEY
          value: minio
        - name: MINIO_SECRET_KEY
          value: minioabc
        image: minio/minio:latest
```

perhaps the new "solution" could function like this:
```yaml
      containers:
      - args:
        - server
        - http://minio-{0...2}.minio-headless.minio.svc/data{1...2}/minio
        env:
        - name: MINIO_ACCESS_KEY
          value: minio
        - name: MINIO_SECRET_KEY
          value: minioabc
        - name: MINIO_USER_1_ACCESS_KEY
          value: some-user-1
        - name: MINIO_USER_1_SECRET_KEY
          value: some-user-1-key
        image: minio/minio:latest
```
^^ and then the minio process would read the environment variables and create the user accounts as indicated

a different project called vernemq handles a similar scenario in a similar fashion, search for `DOCKER_VERNEMQ_USER_<USERNAME>='password'` in this page: https://hub.docker.com/r/erlio/docker-vernemq/

**Describe alternatives you've considered**
im using a hacky bash script that accomplishes the same thing, but its not very stable, and is coming with its own issues. having minio handle user account creation seems like a useful feature.

**Additional context**
the end-goal with my scenario is to have a fresh minio cluster, that is ready-to-go, with user accounts created automatically, so that the minio cluster can be cleaned of all data on a schedule. this allows the development team in my department to have a "predictable" fresh/clean set of minio when they walk into the office in the morning.
