### ISSUE TITLE
GetObject returns invalid metadata from disk cache when using GCS with s3 gateway

### ISSUE THREAD

**Issue by retinio** [minio/minio#8942]
After updated the metadata "get_object" method returns old data if the object is already in disk cache.
I'm running minio as `s3` gateway for GCS with disk caching enabled. 
**docker-compose.yml**
```
version: '3.7'
minio:
    image: minio/minio
    container_name: minio
    volumes:
      - data-1:/data1
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: acces-key
      MINIO_SECRET_KEY: secret-key
      MINIO_CACHE: "on"
      MINIO_CACHE_DRIVES: "/data1/cache"
      MINIO_CACHE_EXPIRY: 14
      MINIO_CACHE_QUOTA: 80 
    restart: always      
    command: gateway s3 https://storage.googleapis.com

volumes:
  data-1:
```
I'm using AWS SDK for .NET with MinIO Server.
```
const string bucketName = "test-container-1";
const string objectName = "586191.webp";

var request = new CopyObjectRequest
                {
                    SourceBucket = bucketName,
                    SourceKey = objectName,
                    DestinationBucket = bucketName,
                    DestinationKey = objectName,
                    MetadataDirective = S3MetadataDirective.REPLACE
                };
request.Metadata.Add("watermark", "true");
var result = await s3Client.CopyObjectAsync(request );

var requestMeta = new GetObjectMetadataRequest { BucketName = bucketName, Key = objectName,  };
//The response contains correct metadata
var responseMetaBefore = await s3Client.GetObjectMetadataAsync(requestMeta);

var requestGetObject = new GetObjectRequest {BucketName = bucketName, Key = objectName};
//The response contains incorrect metadata 
var firstResponseGetObject = await s3Client.GetObjectAsync(requestGetObject);

//The response contains correct metadata 
var secondResponseGetObject = await s3Client.GetObjectAsync(requestGetObject);
```
## Current Behavior

Metadata in GCS is updated successfully. Metadata in disk cache is updated after the method get_object is run but old data is returned.

## Steps to Reproduce (for bugs)

With minio running as `s3` gateway for GCS with disk caching enabled, using the copy_object method with "x-amz-metadata-directive: REPLACE" to update metadata. Using the get_object method for get old metadata.

## Your Environment

* Version used (`minio version`): RELEASE.2020-01-25T02-50-51Z
* Server type and version: Docker version 19.03.5
