### ISSUE TITLE
Error: Storage resources are insufficient for the read operation.

### ISSUE THREAD

**Issue by rvadim** [minio/minio#9018]
Hi, thank your for great work.

We have Kubernetes minio setup: 4 servers with 8 disks.
```
        args:
        - minio
        - server
        - http://{{ app_name }}-0.{{ app_name }}.{{ domain_name }}:{{ app_port }}/data{1...8}
        - http://{{ app_name }}-1.{{ app_name }}.{{ domain_name }}:{{ app_port }}/data{1...8}
        - http://{{ app_name }}-2.{{ app_name }}.{{ domain_name }}:{{ app_port }}/data{1...8}
        - http://{{ app_name }}-3.{{ app_name }}.{{ domain_name }}:{{ app_port }}/data{1...8}
```
Other options is default.
During any operations, such as deploy new version or one of the node maintenance, minio is unable to read or write:
`Error: Storage resources are insufficient for the read operation.`
Maybe it's not very good configuration? Can you explain why this configuration not stable and what setup is more reliable?

Thank you.

## Your Environment
* Version used (`minio version`): RELEASE.2020-01-25T02-50-51Z
* Environment name and version (e.g. nginx 1.9.1): Kubernetes

**Comment by harshavardhana** [comment]
Can you explain what is the backend disk here? How are your PV's provisioned?

**Comment by rvadim** [comment]
We are using local PV from 4 HW servers. So we mount local disks to container with minio.
```
$ kubectl exec -it minio-0 -- df -h | grep /dev/sd
/dev/sdg1                 3.4T     88.0M      3.3T   0% /data7
/dev/sde1                 3.4T     88.0M      3.3T   0% /data3
/dev/sdj1                 3.4T     88.0M      3.3T   0% /data4
/dev/sdk1                 3.4T     88.0M      3.3T   0% /data5
/dev/sdi1                 3.4T     88.0M      3.3T   0% /data6
/dev/sdf1                 3.4T     88.0M      3.3T   0% /data1
/dev/sdh1                 3.4T     88.0M      3.3T   0% /data8
/dev/sdl1                 3.4T     88.0M      3.3T   0% /data2
```
PV type is filesystem(ext4).

**Comment by rvadim** [comment]
All PVs like:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
    pv.kubernetes.io/provisioned-by: local-volume-provisioner-node.name-429ad99f-a8a9-4c8a-ae66-20f8ef10d279
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    hardware: "true"
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: node.name
    kubernetes.io/os: linux
    ssd: "true"
  name: local-pv-1060b65f
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 3520Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: data-2-minio-1
    namespace: ns
  local:
    fsType: ext4
    path: /data/local-pv/0106c199-1f4f-4ad7-aaa4-a01b356ab1e7
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node.name
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-pv
  volumeMode: Filesystem
status:
  phase: Bound
```
