### ISSUE TITLE
Object lifecycle configuration not working

### ISSUE THREAD

**Issue by retinio** [minio/minio#9142]
After enabled object lifecycle configuration minio doesn't automatic delete objects after a specified number of days.
```
$ cat >one-days-bucket-lifecycle.json  << EOF
{ 
    "Rules": [
        {
            "Expiration": {
                "Days": 1                
            },
            "ID": "Delete very old pictures",
            "Filter": {
                "Prefix": "test/"
            },
            "Status": "Enabled"
        }
    ]
}
EOF
```
Verify that the configuration has been added
```
$ aws s3api get-bucket-lifecycle-configuration --bucket test --endpoint-url http://127.0.0.1:9000/
{
    "Rules": [
        {
            "Expiration": {
                "Days": 1
            },
            "ID": "Delete very old pictures",
            "Filter": {
                "Prefix": "test/",
                "Tag": {},
                "And": {}
            },
            "Status": "Enabled"
        }
    ]
}
```  
**Bucket contents:**

![image](https://user-images.githubusercontent.com/36562344/76740847-2fdcf380-6777-11ea-86ff-4d364664f294.png)

**docker-compose.yml**
``` 
services:
  minio:
    image: minio/minio:RELEASE.2020-03-14T02-21-58Z
    volumes:
      - data0-1:/data1
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
   
volumes:
  data0-1:
``` 

## Your Environment

* Version used (minio version): RELEASE.2020-03-14T02-21-58Z
* Server type and version: Docker version 19.03.5
