### ISSUE TITLE
[resolved] Intermittent mc failure "Specified user does not exist"

### ISSUE THREAD

**Issue by eco-minio** [minio/minio#9195]
Periodically `mc` shows the error in $TITLE

## Expected Behavior
If user exists, mc should not display error

## Current Behavior
Issue occurs infrequently in testing, took ~45 minutes to reproduce while running script below

## Possible Solution
?

## Steps to Reproduce (for bugs)

1. Run the following script
```
set -e
​
MINIO_ALIAS='myminio'
ACCESS_KEY='minio'
SECRET_KEY='minio123'
POLICY_NAME='test-policy'
POLICY_JSON='./test-policy.json'
​
while true
do
	
	mc admin user add $MINIO_ALIAS $ACCESS_KEY $SECRET_KEY
	mc admin policy add $MINIO_ALIAS $POLICY_NAME $POLICY_JSON
	mc admin policy set $MINIO_ALIAS $POLICY_NAME user=$ACCESS_KEY
	mc admin user remove $MINIO_ALIAS $ACCESS_KEY
done
```
Policy is any generic policy, sample used here:
`{"Version": "2012-10-17", "Statement": [{"Effect": "Allow", "Action": ["s3:*"], "Resource": ["arn:aws:s3:::test-bucket", "arn:aws:s3:::test-bucket/*"]}]}`

Run script, wait for some amount of time

## Regression
Unsure

## Your Environment
* Version used (`minio version`):
Initially seen with minio/minio:RELEASE.2020-02-07T23-28-16Z, running again with latest (Version: 2020-03-19T21:49:00Z)
* Operating System and version (`uname -a`):
Ubuntu 18.04

**Comment by harshavardhana** [comment]
Cannot reproduce this closing this as a non-issue for now.

**Comment by augnustin** [comment]
:+1: Same issue here, using docker image and 

```
# docker-compose.yml
  minio:
    image: minio/minio
    command: server /data
    env:
      - MINIO_ACCESS_KEY=XXXX
      - MINIO_SECRET_KEY=XXXX
```

**Comment by augnustin** [comment]
My bad, it was my health check that was not correctly plugged and `curl`ed `localhost:9000`. I changed it to:

```
  minio:
    image: minio/minio
    command: server /data
    env_file:
      - ./.env
    healthcheck:
      test: curl -fsS localhost:9000/minio/health/ready
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 1m
```
