### ISSUE TITLE
Intermittent slow list object

### ISSUE THREAD

**Issue by Nepoxx** [minio/minio#9261]
## Expected Behavior

ListObjects should be fast on small number of objects

## Current Behavior

ListObjects is slow (>1 second, I've even seen 20s) sometimes, but not always, even when my distributed minio cluster is under low load.

## Steps to Reproduce (for bugs)
This happens both when using s3 client, minio client or via curl requests. For instance:
```plaintext
nepoxx@nepoxx-arch ~> time mcli ls  --debug sbk/com.company.arcadia/project/builds.temp/
mcli: <DEBUG> GET /com.company.arcadia/?location= HTTP/1.1
Host: minio.company.com
User-Agent: MinIO (linux; amd64) minio-go/v6.0.45 mcli/2019-12-17T23:26:28Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20200403/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20200403T170025Z
Accept-Encoding: gzip

mcli: <DEBUG> HTTP/1.1 200 OK
Content-Length: 128
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Fri, 03 Apr 2020 17:00:26 GMT
Server: MinIO/RELEASE.2020-04-02T21-34-49Z
Vary: Origin
X-Amz-Request-Id: 16025DDDCE69F051
X-Xss-Protection: 1; mode=block

mcli: <DEBUG> Response Time:  45.381652ms

mcli: <DEBUG> GET /com.company.arcadia/?delimiter=%2F&encoding-type=url&fetch-owner=true&list-type=2&prefix=project%2Fbuilds.temp HTTP/1.1
Host: minio.company.com
User-Agent: MinIO (linux; amd64) minio-go/v6.0.45 mcli/2019-12-17T23:26:28Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20200403/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200403T170026Z
Accept-Encoding: gzip

mcli: <DEBUG> HTTP/1.1 200 OK
Content-Length: 431
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Fri, 03 Apr 2020 17:00:26 GMT
Server: MinIO/RELEASE.2020-04-02T21-34-49Z
Vary: Origin
X-Amz-Request-Id: 16025DDDCEB58161
X-Xss-Protection: 1; mode=block

mcli: <DEBUG> Response Time:  13.773497ms

mcli: <DEBUG> GET /com.company.arcadia/?delimiter=%2F&encoding-type=url&fetch-owner=true&list-type=2&prefix=project%2Fbuilds.temp%2F HTTP/1.1
Host: minio.company.com
User-Agent: MinIO (linux; amd64) minio-go/v6.0.45 mcli/2019-12-17T23:26:28Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20200403/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200403T170026Z
Accept-Encoding: gzip

mcli: <DEBUG> HTTP/1.1 200 OK
Content-Length: 42270
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Fri, 03 Apr 2020 17:00:27 GMT
Server: MinIO/RELEASE.2020-04-02T21-34-49Z
Vary: Origin
X-Amz-Request-Id: 16025DDDCF89F6BB
X-Xss-Protection: 1; mode=block

mcli: <DEBUG> Response Time: 10.811303031s

[2020-04-02 07:29:55 EDT]  1.6GiB 139131
[truncated (about 120 objects)]
[2020-04-03 12:36:09 EDT]  1.6GiB 139373

________________________________________________________
Executed in   10.93 secs   fish           external
   usr time   90.42 millis  597.00 micros   89.82 millis
   sys time   36.13 millis  242.00 micros   35.88 millis
```
(>10s for ~120 objects)

## Your Environment

* Version used (`minio version`):
```plaintext
●  minio1:9000
   Uptime: 57 minutes
   Version: 2020-04-02T21:34:49Z
   Network: 6/6 OK
   Drives: 2/2 OK

●  minio2:9000
   Uptime: 57 minutes
   Version: 2020-04-02T21:34:49Z
   Network: 6/6 OK
   Drives: 2/2 OK

●  minio3:9000
   Uptime: 57 minutes
   Version: 2020-04-02T21:34:49Z
   Network: 6/6 OK
   Drives: 2/2 OK

●  minio4:9000
   Uptime: 57 minutes
   Version: 2020-04-02T21:34:49Z
   Network: 6/6 OK
   Drives: 2/2 OK

●  minio5:9000
   Uptime: 57 minutes
   Version: 2020-04-02T21:34:49Z
   Network: 6/6 OK
   Drives: 2/2 OK

●  minio0:9000
   Uptime: 57 minutes
   Version: 2020-04-02T21:34:49Z
   Network: 6/6 OK
   Drives: 2/2 OK

1.2 TiB Used, 12 Buckets, 116,123 Objects
12 drives online, 0 drives offline
```
* Environment name and version (e.g. nginx 1.9.1):
Using docker swarm with Traefik. Swarm details:
```yaml
version: '3.7'

x-default-deploy: &default-deploy
  endpoint_mode: dnsrr
  replicas: 1
  restart_policy:
    condition: any
    delay: 10s
    window: 60s
  labels:
    - "traefik.enable=true"
    - "traefik.http.routers.minio.entrypoints=http"
    - "traefik.http.routers.minio.rule=Host(`minio.company.com`)"
    - "traefik.http.routers.minio.service=minio"
    - "traefik.http.routers.minio.tls=false"
    - "traefik.http.routers.minio_tls.entrypoints=https"
    - "traefik.http.routers.minio_tls.rule=Host(`minio.company.com`)"
    - "traefik.http.routers.minio_tls.service=minio"
    - "traefik.http.routers.minio_tls.tls=true"
    - "traefik.http.services.minio.loadbalancer.server.port=9000"
    - "traefik.http.services.minio.loadbalancer.healthcheck.port=9000"
    - "traefik.http.services.minio.loadbalancer.healthcheck.path=/minio/health/ready"
    - "traefik.http.services.minio.loadbalancer.healthcheck.interval=20s"
    - "traefik.http.services.minio.loadbalancer.passhostheader=true"

x-venus-deploy: &venus-deploy
  <<: *default-deploy
  placement:
    constraints:
      - node.hostname == venus

x-mars-deploy: &mars-deploy
  <<: *default-deploy
  placement:
    constraints:
      - node.hostname == mars

x-saturn-deploy: &saturn-deploy
  <<: *default-deploy
  placement:
    constraints:
      - node.hostname == saturn

x-minio-service: &minio-common
  image: minio/minio:RELEASE.2020-04-02T21-34-49Z
  networks:
    - traefik-net
  dns:
    - 1.1.1.1
    - 8.8.8.8
  logging:
    driver: json-file
    options:
      max-size: 50k
      max-file: 5
  environment:
    MINIO_ACCESS_KEY: [omitted]
    MINIO_SECRET_KEY: [omitted]
    MINIO_STORAGE_CLASS_STANDARD: EC:6 # Default is N/2
    MINIO_STORAGE_CLASS_RRS: EC:5
  command: >
    server --compat
    http://minio0/export0 http://minio0/export1
    http://minio1/export0 http://minio1/export1
    http://minio2/export0 http://minio2/export1
    http://minio3/export0 http://minio3/export1
    http://minio4/export0 http://minio4/export1
    http://minio5/export0 http://minio5/export1

services:
  minio0:
    <<: *minio-common
    deploy: *venus-deploy
    hostname: minio0
    ports:
      - target: 9000
        published: 9001
        mode: host
    volumes:
      - "/minio/disk0/export:/export0"
      - "/minio/disk1/export:/export1"

  minio1:
    <<: *minio-common
    deploy: *venus-deploy
    hostname: minio1
    ports:
      - target: 9000
        published: 9002
        mode: host
    volumes:
      - "/minio/disk2/export:/export0"
      - "/minio/disk3/export:/export1"

  minio2:
    <<: *minio-common
    deploy: *saturn-deploy
    hostname: minio2
    ports:
      - target: 9000
        published: 9003
        mode: host
    volumes:
      - "/minio/disk0/export:/export0"
      - "/minio/disk1/export:/export1"

  # Mars deployments
  minio3:
    <<: *minio-common
    deploy: *mars-deploy
    hostname: minio3
    ports:
      - target: 9000
        published: 9004
        mode: host
    volumes:
      - "/minio/disk0/export:/export0"
      - "/minio/disk1/export:/export1"

  minio4:
    <<: *minio-common
    deploy: *mars-deploy
    hostname: minio4
    ports:
      - target: 9000
        published: 9005
        mode: host
    volumes:
      - "/minio/disk2/export:/export0"
      - "/minio/disk3/export:/export1"

  minio5:
    <<: *minio-common
    deploy: *saturn-deploy
    hostname: minio5
    ports:
      - target: 9000
        published: 9006
        mode: host
    volumes:
      - "/minio/disk2/export:/export0"
      - "/minio/disk3/export:/export1"

networks:
  traefik-net:
    external: true
```
* Server type and version:
Using docker swarm: `Docker version 18.09.8, build 0dd43dd87f`
* Operating System and version (`uname -a`):
`Linux mars 4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
