### ISSUE TITLE
Occasional "Corrupted backend format" reported on fresh installs in distributed mode

### ISSUE THREAD

**Issue by jieyu** [minio/minio#9277]
<!--- Provide a general summary of the issue in the Title above -->
Starting a fresh minio cluster in distributed mode (4 replicas) occasionally report "corrupted backend format" on one of the replica like the following:
```
ERROR Unable to initialize backend: Disk http://minio-1.velero-kubeaddons-minio-svc.velero.svc.cluster.local:9000/data: corrupted backend format, please join https://slack.min.io for assistance
```
I traced to the error is coming from this line in the code:
https://github.com/minio/minio/blob/RELEASE.2020-03-06T22-23-56Z/cmd/format-xl.go#L395

I added some debug information like the following in the code, and was able to reproduce the issue in our CI:
```patch
diff --git a/cmd/format-xl.go b/cmd/format-xl.go
index 7fdb9332..568c34aa 100644
--- a/cmd/format-xl.go
+++ b/cmd/format-xl.go
@@ -390,6 +390,8 @@ func loadFormatXL(disk StorageAPI) (format *formatXLV3, err error) {
                                return nil, err
                        }
                        if len(vols) > 1 || (len(vols) == 1 && !isIgnoreHiddenDirectories(vols[0].Name)) {
+                               err := fmt.Errorf("loadFormatXL(): vols=%v", vols)
+                               logger.LogIf(context.Background(), err)
                                // 'format.json' not found, but we
                                // found user data.
                                return nil, errCorruptedFormat
```

The debug information shows:
```
API: SYSTEM()
Time: 06:36:21 UTC 04/04/2020
Error: loadFormatXL(): vols=[{.minio.sys 2020-04-04 06:24:43.711664084 +0000 UTC} {lost+found 2020-04-04 06:24:32 +0000 UTC}]
       3: /Users/jieyutemp/workspace/minio/cmd/format-xl.go:394:cmd.loadFormatXL()
       2: /Users/jieyutemp/workspace/minio/cmd/format-xl.go:329:cmd.loadFormatXLAll.func1()
       1: /Users/jieyutemp/workspace/minio/pkg/sync/errgroup/errgroup.go:55:errgroup.(*Group).Go.func1()
ERROR Unable to initialize backend: Disk http://minio-1.velero-kubeaddons-minio-svc.velero.svc.cluster.local:9000/data: corrupted backend format, please join https://slack.min.io for assistance
```

I think the offending dir is `.minio.sys`. There might be some race condition that creates this `.minio.sys` dir while the server is still initializing from an empty disk.

## Expected Behavior
<!--- If you're describing a bug, tell us what should happen -->
<!--- If you're suggesting a change/improvement, tell us how it should work -->
Starting a cluster from scratch should not report "Corrupted backend format" error.

## Current Behavior
<!--- If describing a bug, tell us what happens instead of the expected behavior -->
<!--- If suggesting a change/improvement, explain the difference from current behavior -->
Starting a cluster from scratch sometimes report "Corrupted backend format" error in one of the replica. It's not very frequent, but does occur sometimes.

## Possible Solution
<!--- Not obligatory, but suggest a fix/reason for the bug, -->
<!--- or ideas how to implement the addition or change -->

## Steps to Reproduce (for bugs)
<!--- Provide a link to a live example, or an unambiguous set of steps to -->
<!--- reproduce this bug. Include code to reproduce, if relevant -->
1. Install stable/minio chart (version 5.0.12) on a kubernetes cluster (1.16) on AWS with the following config (the default image tag of that version of chart is `RELEASE.2020-03-06T22-23-56Z`:
```yaml                                                                                                                                       
mode: distributed                                                                                                                                   
defaultBucket:                                                                                                                                      
  enabled: true                                                                                                                                     
  name: velero                                                                                                                                      
bucketRoot: "/data"                                                                                                                                 
mountPath: "/data"                                                                                                                                  
existingSecret: minio-creds-secret                                                                                                                                                                                                                                                 
resources:                                                                                                                                          
  requests:                                                                                                                                         
    memory: 256Mi                                                                                                                                   
    cpu: 250m                                                                                                                                       
  limits:                                                                                                                                           
    memory: 512Mi                                                                                                                                   
    cpu: 750m                                                                                                                                       
``` 
2. Occasionally, one of the minio server will report
```
ERROR Unable to initialize backend: Disk http://minio-1.velero-kubeaddons-minio-svc.velero.svc.cluster.local:9000/data: corrupted backend format, please join https://slack.min.io for assistance
```

## Context
<!--- How has this issue affected you? What are you trying to accomplish? -->
<!--- Providing context helps us come up with a solution that is most useful in the real world -->
Cause flaky CI in our environment.

## Regression
<!-- Is this issue a regression? (Yes / No) -->
<!-- If Yes, optionally please include minio version or commit id or PR# that caused this regression, if you have these details. -->

## Your Environment
<!--- Include as many relevant details about the environment you experienced the bug in -->
* Version used (`minio version`): RELEASE.2020-03-06T22-23-56Z
* Environment name and version (e.g. nginx 1.9.1): Kubernetes 1.16.8, AWS CSI driver, ext4 for the minio volume
* Server type and version: AWS t3.2xlarge (worker) * 4
* Operating System and version (`uname -a`): CentOS 7.6
* Link to your project:
