### ISSUE TITLE
[resolved] Minio OpenID in Docker Compose orchestration failure

### ISSUE THREAD

**Issue by dennishendriksen** [minio/minio#9282]
Minio starts successfully when OpenID initialization fails. It is unclear how to configure the Minio service to wait until a successful initialization is possible.

## Expected Behavior
One of the following:
- Minio fails to start when OpenID initialization fails.
- Minio retries initialization for a configurable number of attempts with a configurable interval

## Current Behavior
Minio logs an error that initialization fails but starts successfully.

## Possible Solution
One of the following:
- Change Minio such that it fails on OpenID initialization. This allows outside processes (e.g. Docker Compose to restart Minio until it starts successfully)
- Update Minio Dockerfile to allow for a ```wait_for``` wrapper solution to allow for starting Minio at the right time.
- Document a workaround

## Steps to Reproduce (for bugs)
```yml
version: "3.7"
services:
  keycloak:
    image: jboss/keycloak:9.0.2
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_USER: keycloak
      KEYCLOAK_PASSWORD: keycloak123
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth/realms/master"]
  minio:
    image: minio/minio:RELEASE.2020-04-04T05-39-31Z
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_IDENTITY_OPENID_CONFIG_URL: http://host.docker.internal:8080/auth/realms/variant/.well-known/openid-configuration
      MINIO_IDENTITY_OPENID_CLIENT_ID: account
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
volumes:
  minio-data:
```
1. docker-compose up

logs:
```
minio_1     |
minio_1     | API: SYSTEM()
minio_1     | Time: 08:34:17 UTC 04/07/2020
minio_1     | DeploymentID: 4dd1778a-729c-48c3-abf4-ef62169df723
minio_1     | Error: Unable to initialize OpenID: Get http://host.docker.internal:8080/auth/realms/variant/.well-known/openid-configuration: EOF
minio_1     |        7: github.com/minio/minio@/cmd/config-current.go:396:cmd.lookupConfigs()
minio_1     |        6: github.com/minio/minio@/cmd/config-current.go:572:cmd.loadConfig()
minio_1     |        5: github.com/minio/minio@/cmd/config.go:253:cmd.initConfig()
minio_1     |        4: github.com/minio/minio@/cmd/config.go:213:cmd.(*ConfigSys).Init()
minio_1     |        3: github.com/minio/minio@/cmd/server-main.go:246:cmd.initAllSubsystems()
minio_1     |        2: github.com/minio/minio@/cmd/server-main.go:220:cmd.initSafeMode()
minio_1     |        1: github.com/minio/minio@/cmd/server-main.go:447:cmd.serverMain()
```
2. navigate to http://localhost:9000

server started successfully without OpenID login

3. update docker-compose.yml to depend_on keycloak and add a 'wait_for' wrapper:

Download wait-for and put it in the same folder as docker-compose.yml
```yml
version: "3.7"
services:
  keycloak:
    image: jboss/keycloak:9.0.2
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_USER: keycloak
      KEYCLOAK_PASSWORD: keycloak123
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth/realms/master"]
  minio:
    image: minio/minio:RELEASE.2020-04-04T05-39-31Z
    depends_on:
      - keycloak
    volumes:
      - minio-data:/data
      - ./wait-for:/usr/local/bin/wait-for
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_IDENTITY_OPENID_CONFIG_URL: http://host.docker.internal:8080/auth/realms/variant/.well-known/openid-configuration
      MINIO_IDENTITY_OPENID_CLIENT_ID: account
        command:
          - wait-for
          - localhost:8081
          - --
          - server
          - /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
volumes:
  minio-data:
```

Results in the following error:
```
Attaching to minio-wait_keycloak_1, minio-wait_minio_1
minio_1     | ‘wait-for’ is not a minio sub-command. See ‘minio --help’.
minio-wait_minio_1 exited with code 1
```

## Context
I have build a system with a web application with single-sign using Keycloak and configured Minio to use Keycloak. Works like a charm. I want to use Docker Compose to simplify the installation and configuration of the system for developers.

## Regression
No

Thanks for the great work that you are doing on Minio!
