### ISSUE TITLE
[resolved] Cant run minio in docker by ansible in distributed mode

### ISSUE THREAD

**Issue by fufar** [minio/minio#9309]
I have 3 servers with 4 hdd for storage  /minio0 /minio1 /minio2 /minio3
I make a playbook and role that start docker container with this mounts, its work
role:
```
- hosts: minio
  gather_facts: yes
  vars:
    minio_port: 9000
  roles:
    - role: minio
```

playbook:

```
- name: run minio node
  docker_container:
    image: minio/minio:edge
    name: minio
    state: started
    restart_policy: always
    command: server /data0 /data1 /data2 /data3
    memory: 512M
    env:
      MINIO_ACCESS_KEY: "12345678"
      MINIO_SECRET_KEY: "12345678"
      MINIO_UPDATE: "on"
      MINIO_DOMAIN: "{{ ansible_hostname }}"
    volumes:
      - "/minio0:/data0"
      - "/minio1:/data1"
      - "/minio2:/data2"
      - "/minio3:/data3"
    ports:
      - "{{ ansible_eth0.ipv4.address }}:{{ minio_port }}:9000"
  tags:
    - container
```
then i tryed to start "master" containers which will connect in distributed mode this nodes

```
- hosts: minio
  tasks:
    - name: run master container
      docker_container:
        image: minio/minio:edge
        name: minio-master
        restart_policy: always
        state: started
        command: server http://server1:9000/data{0...3} http://server2:9000/data{0...3} http://server3:9000/data{0...3}
        memory: 1G
        env:
          MINIO_ACCESS_KEY: "12345678"
          MINIO_SECRET_KEY: "12345678"
          MINIO_UPDATE: "on"
        volumes:
          - "/root/.minio:/var/lib/minio-master"
        ports:
          - "{{ ansible_eth0.ipv4.address }}:9005:9000"
```

## Expected Behavior
That should make container that uses my storage location and be distributed

## Current Behavior
I get error in each "master" container

> Waiting for a minimum of 2 disks to come online (elapsed 8m37s)
> Unable to read 'format.json' from http://server1:9000/data0: 404 page not found
> Unable to read 'format.json' from http://server1:9000/data1: 404 page not found
> Unable to read 'format.json' from http://server1:9000/data2: 404 page not found
> Unable to read 'format.json' from http://server1:9000/data3: 404 page not found
> 

When i open any of this paths in browser - they open
## Your Environment

* Version used (`minio version`): minio/minio:edge also tryed minio/minio
* OS: Centos 7
* Ansible: 2.9.6
* Docker: 19.03.8

**Comment by harshavardhana** [comment]
>       - "{{ ansible_eth0.ipv4.address }}:{{ minio_port }}:9000"

You need to make sure to expose your host IP if you don't it won't work @fufar so as `net: host`

**Comment by fufar** [comment]
> You need to make sure to expose your host IP if you don't it won't work @fufar so as `net: host`

they are accessible on this port and ip, from host machines and containers also

**Comment by harshavardhana** [comment]
> they are accessible on this port and ip, from host machines and containers also

I don't think so @fufar the DNS is resolving to a different IP which is not accessible - this is why you see

> Unable to read 'format.json' from http://server1:9000/data0: 404 page not found
> Unable to read 'format.json' from http://server1:9000/data1: 404 page not found
> Unable to read 'format.json' from http://server1:9000/data2: 404 page not found
> Unable to read 'format.json' from http://server1:9000/data3: 404 page not found

**Comment by fufar** [comment]
> [root@server1 ~]# docker exec -it minio-master sh
> / # ping server1
> PING server1 (ip): 56 data bytes
> 64 bytes from ip: seq=0 ttl=64 time=0.113 ms
> ^C
> --- server1 ping statistics ---
> 1 packets transmitted, 1 packets received, 0% packet loss
> round-trip min/avg/max = 0.113/0.113/0.113 ms
> / # ping server2
> PING server2 (ip): 56 data bytes
> 64 bytes from ip: seq=0 ttl=63 time=0.317 ms
> ^C
> --- server2 ping statistics ---
> 1 packets transmitted, 1 packets received, 0% packet loss
> round-trip min/avg/max = 0.317/0.317/0.317 ms
> / # ping server3
> PING server3 (ip): 56 data bytes
> 64 bytes from ip: seq=0 ttl=63 time=0.433 ms
> ^C
> --- server3 ping statistics ---
> 1 packets transmitted, 1 packets received, 0% packet loss
> round-trip min/avg/max = 0.433/0.433/0.433 ms

And i tryed change in playbook command to 
`command: server http://ip1:9000/data{0...3} http://ip2:9000/data{0...3} http://ip3:9000/data{0...3}`

**Comment by harshavardhana** [comment]
Either use an overlay network or expose the host IP on the container - we need to know this information to make sure to export the disks which are local to the node for remote nodes to access.

**Comment by fufar** [comment]
If i understand question correctly - containers use bridge network, and forward port from it to local network

**Comment by harshavardhana** [comment]
> If i understand question correctly - containers use bridge network, and forward port from it to local network

Its called overlay network - it has nothing to do with what you export on your host system. What it means in MinIO context is that 

if server01 resolves to 10.1.10.x and this IP is not available on the container which is running server01 - MinIO will not know your /export01 belongs to server01 so it has no takers that are why you see `404 not found`

This is the crux of the issue here, you are overriding the server01 IP to be coming from a different network which is not exposed on the container, MinIO cannot auto assume things about disks which it needs to export, it needs to make sure that it exposes the correct disks from the right IP so that other remote servers can connect. 

Unlike nginx, traefik which you may be used to - MinIO is a distributed system and relies on IPs/DNS resolving correctly to the host which exposes the disk.

**Comment by fufar** [comment]
ok, i tryed to create without docker 
on server1, server2, server3 i start with
`MINIO_SECRET_KEY=12345678 MINIO_ACCESS_KEY=12345678 ./minio server /minio0 /minio1/ /minio2/ /minio3/`
then on another server i start with

`MINIO_SECRET_KEY=12345678 MINIO_ACCESS_KEY=12345678 ./minio server http://ip1/minio{0...3} http://ip2/minio{0...3} http://ip3/minio{0...3}`

And i have same error

> Unable to read 'format.json' from http://ip1:9000/minio2: 404 page not found

i of  couse have access to this ip, they are in local network, so i can ping/ssh/etc to them

**Comment by harshavardhana** [comment]
> ok, i tryed to create without docker
> on server1, server2, server3 i start with
> `MINIO_SECRET_KEY=12345678 MINIO_ACCESS_KEY=12345678 ./minio server /minio0 /minio1/ /minio2/ /minio3/`
> then on another server i start with
> 
> `MINIO_SECRET_KEY=12345678 MINIO_ACCESS_KEY=12345678 ./minio server http://ip1/minio{0...3} http://ip2/minio{0...3} http://ip3/minio{0...3}`
> 
> And i have same error

This is not how you start distributed setup @fufar  you only need to do one command line 

`MINIO_SECRET_KEY=12345678 MINIO_ACCESS_KEY=12345678 ./minio server http://ip1/minio{0...3} http://ip2/minio{0...3} http://ip3/minio{0...3}`

Also, this command line is incorrect you should use 

`MINIO_SECRET_KEY=12345678 MINIO_ACCESS_KEY=12345678 ./minio server http://ip{1...3|/minio{0...3}`

**Comment by harshavardhana** [comment]
I think you are doing things without reading out distributed setup docs @fufar its as simple as 

```
export MINIO_ACCESS_KEY=<ACCESS_KEY>
export MINIO_SECRET_KEY=<SECRET_KEY>
minio server http://host{1...32}/export{1...32}
```
https://github.com/minio/minio/tree/master/docs/distributed#2-run-distributed-minio

> All the nodes running distributed MinIO need to have same access key and secret key for the nodes to connect. To achieve this, it is recommended to export access key and secret key as environment variables, MINIO_ACCESS_KEY and MINIO_SECRET_KEY, on all the nodes before executing MinIO server command.

Will proceed to close this out as this is simply a setup issue for now.

**Comment by fufar** [comment]
ip1, ip2, ip3 is not a DNS names - its ip adresses
i tryed also

```
add to hosts
ip1 minio0 
ip2 minio1 
ip3 minio2 
```

```
export MINIO_ACCESS_KEY=12345678
export MINIO_SECRET_KEY=12345678
./minio server http://minio{0...2}/minio{0...3}
```

this not work also

**Comment by harshavardhana** [comment]
> add to hosts
> minio0 ip1
> minio1 ip2
> minio2 ip3

the hosts should be 

```
ip1 minio0
ip2 minio1
ip3 minio3
```

**Comment by fufar** [comment]
yep, it is, writed wrong here, in hosts  - right order

**Comment by harshavardhana** [comment]
lets talk on https://slack.min.io @fufar - this looks like a simple setup issue.

**Comment by fufar** [comment]
thx to @harshavardhana  - now it working
to fix i need
1) remove all old files from storage mounts
2) make a dns name - for me it was minio{0...2}
3) start like this `./minio server http://minio{0...2}/minio{0...3}`
4) to make working in docker i need to set   `network_mode: host`

for ansible and docker 
```
playbook
- hosts: minio
  gather_facts: yes
  vars:
    minio_port: 9000
  roles:
    - role: minio
```
role

```
- name: run minio node
  docker_container:
    image: minio/minio:edge
    name: minio
    state: started
    restart_policy: always
    command: server http://minio{0...2}/minio{0...3}
    memory: 512M
    env:
      MINIO_ACCESS_KEY: "12345678"
      MINIO_SECRET_KEY: "12345678"
      MINIO_BROWSER: "on"
    volumes:
      - "/minio0:/minio0"
      - "/minio1:/minio1"
      - "/minio2:/minio2"
      - "/minio3:/minio3"
    ports:
      - "{{ ansible_eth0.ipv4.address }}:{{ minio_port }}:9000"
    network_mode: host
```
