### ISSUE TITLE
Inplace copy with storage class set fails

### ISSUE THREAD

**Issue by cscetbon** [minio/minio#9357]
## Expected Behavior

Any inplace copy should succeed when storage class is set. That's how it works with aws s3.

## Current Behavior

It fails complaining that storage class is not set 
```
/ # aws --endpoint-url http://minio-domain:9000 s3 cp --storage-class REDUCED_REDUNDANCY \
s3://cassie/cyril/test/test.10 s3://cassie/cyril/test/test.10
copy failed: s3://cassie/cyril/test/test.10 to s3://cassie/cyril/test/test.10 
An error occurred (InvalidRequest) when calling the CopyObject operation: 
This copy request is illegal because it is trying to copy an object to itself without changing the object's metadata, storage class, website redirect location or encryption attributes.

/ # aws --endpoint-url http://minio-domain:9000 s3 cp --storage-class STANDARD \
s3://cassie/cyril/test/test.10 s3://cassie/cyril/test/test.10
copy failed: s3://cassie/cyril/test/test.10 to s3://cassie/cyril/test/test.10 
An error occurred (InvalidRequest) when calling the CopyObject operation: 
This copy request is illegal because it is trying to copy an object to itself without changing the object's metadata, storage class, website redirect location or encryption attributes.
```

On AWS s3 setting the storage class to the same value multiple times never fails:
```
aws s3 cp --storage-class STANDARD s3://etl-dp/toto s3://etl-dp/toto && echo OK
copy: s3://etl-dp/toto to s3://etl-dp/toto
OK
```
## Steps to Reproduce (for bugs)

1. create a sample file on s3
```
echo ola | aws --endpoint-url http://minio-domain:9000 s3 cp - \
s3://cassie/cyril/file1
```

2. try to do an inplace copy setting the storage class
```
/ # aws --endpoint-url http://minio-domain:9000 s3 cp \
--storage-class STANDARD s3://cassie/cyril/file1 s3://cassie/cyril/file1
copy failed: s3://cassie/cyril/file1 to s3://cassie/cyril/file1 An error occurred (InvalidRequest) when calling the CopyObject operation: This copy request is illegal because it is trying to copy an object to itself without changing the object's metadata, storage class, website redirect location or encryption attributes.
```

## Your Environment

* Version used (`minio version`): minio/minio:RELEASE.2020-03-25T07-03-04Z
* Environment name and version (e.g. nginx 1.9.1): kubernetes
* Server type and version:
```
$ k version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-13T18:08:14Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2020-01-14T00:09:19Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```

This issue is similar to https://github.com/minio/minio/issues/1071 but I can't see why it would not be relevant. If it doesn't I'll have to just stop using Minio as I need a local env identical to s3

**Comment by harshavardhana** [comment]
> Any inplace copy should succeed when storage class is set. That's how it works with aws s3.

Now quick question are you using MinIO in single drive more or multi-drive mode?

**Comment by cscetbon** [comment]
Single drive as far as I know. Here are my k8s objects 
```
apiVersion: v1
kind: Service
metadata:
  name: minio-domain
spec:
  selector:
    app: minio
  clusterIP: None
  ports:
  - name: http # Actually, no port is needed.
    port: 9000
    targetPort: 9000
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: minio
    release: minio
  name: cassie
spec:
  hostname: cassie
  subdomain: minio-domain
  containers:
  - command:
    - /bin/sh
    - -ce
    - /usr/bin/docker-entrypoint.sh minio -S /etc/minio/certs/ server /export
    env:
    - name: MINIO_ACCESS_KEY
      value: minio
    - name: MINIO_SECRET_KEY
      value: minio123
    - name: MINIO_BROWSER
      value: "on"
    - name: MINIO_DOMAIN
      value: minio-domain
    image: minio/minio:RELEASE.2020-03-25T07-03-04Z
    name: minio
    ports:
    - containerPort: 9000
      name: http
      protocol: TCP
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
    volumeMounts:
    - mountPath: /export
      name: export
  volumes:
  - name: export
    persistentVolumeClaim:
      claimName: minio
  - name: minio-user
    secret:
      defaultMode: 420
      secretName: minio
```
