### ISSUE TITLE
[not our bug] Problems with minIO using Docker Swarm

### ISSUE THREAD

**Issue by claytonnog** [minio/minio#9372]
Hey guys, how are you?

I am trying to use minIO using a docker swarm cluster, but I am having some problems doing it.

The 3 and 4 node always spam the message that 
"Waiting for a minimum of 2 disks to come online (elapsed 27s)"
and
"Waiting for the first server to format the disks."
and after that theres the error:
ERROR Unable to initialize server switching into safe-mode: Operation timed out

In the nodes 1 and 2 it´s appears to be ok.

It´s my .yaml file:
```yaml
`version: '3.7'

services:
  minio1:
    image: minio/minio:RELEASE.2020-04-15T19-42-18Z
    hostname: minio1
    volumes:
      - /export:/export
    ports:
      - "9001:9000"
    environment:
      - MINIO_BROWSER=on
    networks:
      - minio_distributed
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:
        constraints:
          - node.labels.minio1==true
    command: server http://minio{1...4}/export
    secrets:
      - secret_key
      - access_key
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio2:
    image: minio/minio:RELEASE.2020-04-15T19-42-18Z
    hostname: minio2
    volumes:
      - /export:/export
    ports:
      - "9002:9000"
    environment:
      - MINIO_BROWSER=on
    networks:
      - minio_distributed
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:
        constraints:
          - node.labels.minio2==true
    command: server http://minio{1...4}/export
    secrets:
      - secret_key
      - access_key
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio3:
    image: minio/minio:RELEASE.2020-04-15T19-42-18Z
    hostname: minio3
    volumes:
      - /export:/export
    ports:
      - "9003:9000"
    environment:
      - MINIO_BROWSER=on
    networks:
      - minio_distributed
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:
        constraints:
          - node.labels.minio3==true
    command: server http://minio{1...4}/export
    secrets:
      - secret_key
      - access_key
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio4:
    image: minio/minio:RELEASE.2020-04-15T19-42-18Z
    hostname: minio4
    volumes:
      - /export:/export
    ports:
      - "9004:9000"
    environment:
      - MINIO_BROWSER=on
    networks:
      - minio_distributed
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:
        constraints:
          - node.labels.minio4==true
    command: server http://minio{1...4}/export
    secrets:
      - secret_key
      - access_key
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

networks:
  minio_distributed:
    driver: overlay

secrets:
  secret_key:
    external: true
  access_key:
    external: true
`
```
I don't know how to do... I've already tried a lot of things to solve that problem.

Tried to use volumes like in the yaml file in the official page: https://docs.min.io/docs/deploy-minio-on-docker-swarm, but it's not working too.

When I enter the browser, in node 1 and 2, it's ok, but node 3 and 4 never goes into the cluster and never sync the files.

The mc admin info says that it's ok too:
[clayt.note-casa] ➤ ./mc admin info minio4

●  minio1:9000
   Uptime: 11 minutes
   Version: 2020-04-15T19:42:18Z
   Network: 4/4 OK
   Drives: 1/1 OK

●  minio2:9000
   Uptime: 11 minutes
   Version: 2020-04-15T19:42:18Z
   Network: 4/4 OK
   Drives: 1/1 OK

●  minio3:9000
   Uptime: 1 minute
   Version: 2020-04-15T19:42:18Z
   Network: 4/4 OK
   Drives: 1/1 OK

●  minio4:9000
   Uptime: 33 seconds
   Version: 2020-04-15T19:42:18Z
   Network: 4/4 OK
   Drives: 1/1 OK

0 B Used, 2 Buckets, 0 Objects
4 drives online, 0 drives offline

Thanks in advance
