### ISSUE TITLE
Copying files data after nodes failure in distributed mode

### ISSUE THREAD

**Issue by vclvm** [minio/minio#9404]
## Summary
I'm trying to simulate few minio nodes failure and minio acts not in the way I expected, what am I missing?
I have 6 minio instances running with one disk attached to each one of them as a docker volume.
I create a bucket and upload one 100 Mb file via web interface.
Then I stop and remove 2 minio containers and their volumes, that leaves me with 4 of them, n/2+1.
I can use minio - download my file and upload other files.
Then I recreate 2 previously deleted minio instances and their volumes.

## Expected Behavior
I expect newly created instances to join existing distributed mode cluster and copy its files to newly created volumes.
Volumes size must be at least 32 Mb like on other instances:

```
root@minio-test1:~# du -h /var/lib/docker/volumes/minio-int_data12/
12K	/var/lib/docker/volumes/minio-int_data12/_data/.minio.sys/backend-encrypted
4,0K	/var/lib/docker/volumes/minio-int_data12/_data/.minio.sys/multipart
12K	/var/lib/docker/volumes/minio-int_data12/_data/.minio.sys/config/iam/format.json
16K	/var/lib/docker/volumes/minio-int_data12/_data/.minio.sys/config/iam
12K	/var/lib/docker/volumes/minio-int_data12/_data/.minio.sys/config/config.json
32K	/var/lib/docker/volumes/minio-int_data12/_data/.minio.sys/config
4,0K	/var/lib/docker/volumes/minio-int_data12/_data/.minio.sys/tmp
12K	/var/lib/docker/volumes/minio-int_data12/_data/.minio.sys/buckets/bucket1/.usage-cache.bin
16K	/var/lib/docker/volumes/minio-int_data12/_data/.minio.sys/buckets/bucket1
12K	/var/lib/docker/volumes/minio-int_data12/_data/.minio.sys/buckets/.usage.json
12K	/var/lib/docker/volumes/minio-int_data12/_data/.minio.sys/buckets/.usage-cache.bin
44K	/var/lib/docker/volumes/minio-int_data12/_data/.minio.sys/buckets
104K	/var/lib/docker/volumes/minio-int_data12/_data/.minio.sys
32M	/var/lib/docker/volumes/minio-int_data12/_data/bucket1/electrcity_svoren.pdf
32M	/var/lib/docker/volumes/minio-int_data12/_data/bucket1
32M	/var/lib/docker/volumes/minio-int_data12/_data
32M	/var/lib/docker/volumes/minio-int_data12/
```

## Current Behavior
Error starting new instances:

```
minio4    | API: SYSTEM(bucket=.minio.sys, object=buckets/.usage.json)
minio4    | Time: 12:54:42 UTC 04/21/2020
minio4    | DeploymentID: e647fb25-5154-4206-9e48-b932b7d6f9e2
minio4    | Error: file access denied
minio4    |        5: github.com/minio/minio@/cmd/xl-v1-healing.go:467:cmd.xlObjects.healObject()
minio4    |        4: github.com/minio/minio@/cmd/xl-v1-healing.go:772:cmd.xlObjects.HealObject()
minio4    |        3: github.com/minio/minio@/cmd/xl-sets.go:1681:cmd.(*xlSets).HealObject()
minio4    |        2: github.com/minio/minio@/cmd/xl-zones.go:1501:cmd.(*xlZones).HealObject()
minio4    |        1: github.com/minio/minio@/cmd/background-heal-ops.go:89:cmd.(*healRoutine).run()
minio4    | Status:         6 Online, 0 Offline. 
minio4    | Endpoint:  http://minio-test22:9002
```
Files data is not copied to newly created instnaces (after couple of hours)
```
root@minio-test2:/home/me/minio-int# du -h /var/lib/docker/volumes/minio-int_data22/_data/
4,0K	/var/lib/docker/volumes/minio-int_data22/_data/.minio.sys/multipart
12K	/var/lib/docker/volumes/minio-int_data22/_data/.minio.sys/config/iam/format.json
16K	/var/lib/docker/volumes/minio-int_data22/_data/.minio.sys/config/iam
12K	/var/lib/docker/volumes/minio-int_data22/_data/.minio.sys/config/config.json
32K	/var/lib/docker/volumes/minio-int_data22/_data/.minio.sys/config
4,0K	/var/lib/docker/volumes/minio-int_data22/_data/.minio.sys/tmp
12K	/var/lib/docker/volumes/minio-int_data22/_data/.minio.sys/buckets/bucket1/.usage-cache.bin
16K	/var/lib/docker/volumes/minio-int_data22/_data/.minio.sys/buckets/bucket1
12K	/var/lib/docker/volumes/minio-int_data22/_data/.minio.sys/buckets/.usage.json
12K	/var/lib/docker/volumes/minio-int_data22/_data/.minio.sys/buckets/.usage-cache.bin
44K	/var/lib/docker/volumes/minio-int_data22/_data/.minio.sys/buckets
92K	/var/lib/docker/volumes/minio-int_data22/_data/.minio.sys
4,0K	/var/lib/docker/volumes/minio-int_data22/_data/bucket1
100K	/var/lib/docker/volumes/minio-int_data22/_data/
```

## Possible Solution
Running `mc admin heal` didn't help:
```
root@minio-test2:/home/me/minio-int# ./mc admin heal test2
Background healing status:
 ●  85 item(s) scanned in total
 ●  Completed 3 minutes ago
 ●  Next scheduled in 29 days
```
But folders are still 100K of size

## Steps to Reproduce (for bugs)
I have a bit non usual set up: three servers running two minio docker containers each with docker compose.
minio-test1 docker-compose:

```
version: '3.7'

services:
  minio1:
    container_name: minio1
    image: minio/minio:RELEASE.2020-04-15T19-42-18Z
    ports:
      - "9001:9001"
    volumes:
      - data11:/data11
    environment:
      MINIO_ACCESS_KEY: minio-key
      MINIO_SECRET_KEY: minio-secret
    command: server --address minio-test11:9001 http://minio-test11:9001/data11 http://minio-test12:9002/data12 http://minio-test21:9001/data21 http://minio-test22:9002/data22 http://minio-test31:9001/data31 http://minio-test32:9002/data32
    networks:
      minio:
        ipv4_address: 172.10.9.11
    extra_hosts:
      minio-test11: 172.10.9.11 
      minio-test12: 172.10.9.12
      minio-test21: 192.168.88.178
      minio-test22: 192.168.88.178
      minio-test31: 192.168.88.179
      minio-test32: 192.168.88.179

  minio2:
    container_name: minio2
    image: minio/minio:RELEASE.2020-04-15T19-42-18Z
    ports:
      - "9002:9002"
    volumes:
      - data12:/data12
    environment:
      MINIO_ACCESS_KEY: minio-key
      MINIO_SECRET_KEY: minio-secret
    command: server --address minio-test12:9002 http://minio-test11:9001/data11 http://minio-test12:9002/data12 http://minio-test21:9001/data21 http://minio-test22:9002/data22 http://minio-test31:9001/data31 http://minio-test32:9002/data32
    networks:
      minio:
        ipv4_address: 172.10.9.12
    extra_hosts:
      minio-test11: 172.10.9.11
      minio-test12: 172.10.9.12
      minio-test21: 192.168.88.178
      minio-test22: 192.168.88.178
      minio-test31: 192.168.88.179
      minio-test32: 192.168.88.179

volumes:
  data11:
  data12:

networks:
  minio:
    driver: bridge
    ipam:
      config:
        - subnet: 172.10.9.0/24
```
minio-test2 docker-compose:

```
version: '3.7'

services:
  minio3:
    container_name: minio3
    image: minio/minio:RELEASE.2020-04-15T19-42-18Z
    ports:
      - "9001:9001"
    volumes:
      - data21:/data21
    environment:
      MINIO_ACCESS_KEY: minio-key
      MINIO_SECRET_KEY: minio-secret
    command: server --address minio-test21:9001 http://minio-test11:9001/data11 http://minio-test12:9002/data12 http://minio-test21:9001/data21 http://minio-test22:9002/data22 http://minio-test31:9001/data31 http://minio-test32:9002/data32
    networks:
      minio:
        ipv4_address: 172.10.9.13
    extra_hosts:
      minio-test11: 192.168.88.177
      minio-test12: 192.168.88.177
      minio-test21: 172.10.9.13
      minio-test22: 172.10.9.14
      minio-test31: 192.168.88.179
      minio-test32: 192.168.88.179

  minio4:
    container_name: minio4
    image: minio/minio:RELEASE.2020-04-15T19-42-18Z
    ports:
      - "9002:9002"
    volumes:
      - data22:/data22
    environment:
      MINIO_ACCESS_KEY: minio-key
      MINIO_SECRET_KEY: minio-secret
    command: server --address minio-test22:9002 http://minio-test11:9001/data11 http://minio-test12:9002/data12 http://minio-test21:9001/data21 http://minio-test22:9002/data22 http://minio-test31:9001/data31 http://minio-test32:9002/data32
    networks:
      minio:
        ipv4_address: 172.10.9.14
    extra_hosts:
      minio-test11: 192.168.88.177
      minio-test12: 192.168.88.177
      minio-test21: 172.10.9.13
      minio-test22: 172.10.9.14
      minio-test31: 192.168.88.179
      minio-test32: 192.168.88.179

volumes:
  data21:
  data22:

networks:
  minio:
    driver: bridge
    ipam:
      config:
        - subnet: 172.10.9.0/24

```

minio-test2 docker-compose:

```
version: '3.7'

services:
  minio5:
    container_name: minio5
    image: minio/minio:RELEASE.2020-04-15T19-42-18Z
    ports:
      - "9001:9001"
    volumes:
      - data31:/data31
    environment:
      MINIO_ACCESS_KEY: minio-key
      MINIO_SECRET_KEY: minio-secret
    command: server --address minio-test31:9001 http://minio-test11:9001/data11 http://minio-test12:9002/data12 http://minio-test21:9001/data21 http://minio-test22:9002/data22 http://minio-test31:9001/data31 http://minio-test32:9002/data32
    networks:
      minio:
        ipv4_address: 172.10.9.15
    extra_hosts:
      minio-test11: 192.168.88.177
      minio-test12: 192.168.88.177
      minio-test21: 192.168.88.178
      minio-test22: 192.168.88.178
      minio-test31: 172.10.9.15
      minio-test32: 172.10.9.16

  minio6:
    container_name: minio6
    image: minio/minio:RELEASE.2020-04-15T19-42-18Z
    ports:
      - "9002:9002"
    volumes:
      - data32:/data32
    environment:
      MINIO_ACCESS_KEY: minio-key
      MINIO_SECRET_KEY: minio-secret
    command: server --address minio-test32:9002 http://minio-test11:9001/data11 http://minio-test12:9002/data12 http://minio-test21:9001/data21 http://minio-test22:9002/data22 http://minio-test31:9001/data31 http://minio-test32:9002/data32
    networks:
      minio:
        ipv4_address: 172.10.9.16
    extra_hosts:
      minio-test11: 192.168.88.177
      minio-test12: 192.168.88.177
      minio-test21: 192.168.88.178
      minio-test22: 192.168.88.178
      minio-test31: 172.10.9.15
      minio-test32: 172.10.9.16

volumes:
  data31:
  data32:

networks:
  minio:
    driver: bridge
    ipam:
      config:
        - subnet: 172.10.9.0/24

```

Steps to reproduce are:
1. Start all 6 minio nodes in distributed mode
2. Copy files to them
3. Remove 2 minio nodes and their storages
4. Create 2 new minio nodes with empty storages

## Your Environment

image: minio/minio:RELEASE.2020-04-15T19-42-18Z
Linux minio-test2 5.3.0-46-generic #38~18.04.1-Ubuntu SMP Tue Mar 31 04:17:56 UTC 2020 Ubuntu 18.04.4 LTS"
Docker version 19.03.8, build afacb8b7f0
docker-compose version 1.25.5, build 8a1c60f6
