### ISSUE TITLE
kubernetes distributed minio setup with volume mount not working

### ISSUE THREAD

**Issue by Arun-KumarH** [minio/minio#9464]
We are using a distributed minio setup with volume mount, but the instances are not running.
(Without volume mount, the system runs gracefully).

We have created a PVC named `webapp-os-pvc` and used it as below, but we get error `Error: Storage resources are insufficient for the read operation` in one of the minio instance.
Each of the 4 instance is reachable to other instance.
 
```
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: webapp-os
  namespace: appns
spec:
  serviceName: webapp-os
  replicas: 4
  template:
    metadata:
      labels:
        app: webapp-os
        version: production
        tier: backend
    spec:
      containers:
      - name: minio
        env:
        - name: MINIO_ACCESS_KEY
          value: "xxxxxxx"
        - name: MINIO_SECRET_KEY
          value: "yyyyyyy"
        image: minio/minio:RELEASE.2020-04-23T00-58-49Z
        args:
        - server
        - http://webapp-os-{0...3}.webapp-os.appns.svc.cluster.local/data
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: webapp-os-data
          mountPath: "/data"
      volumes:
      - name: webapp-os-data
        persistentVolumeClaim:
          claimName: webapp-os-pvc
```
Error:
```
Error: Storage resources are insufficient for the read operation.
       5: github.com/minio/minio@/cmd/config-common.go:40:cmd.readConfig()
       4: github.com/minio/minio@/cmd/config-encrypted.go:141:cmd.checkBackendEncrypted()
       3: github.com/minio/minio@/cmd/config-encrypted.go:57:cmd.handleEncryptedConfigBackend()
       2: github.com/minio/minio@/cmd/server-main.go:197:cmd.initSafeMode()
       1: github.com/minio/minio@/cmd/server-main.go:450:cmd.serverMain()
Waiting for config backend to be encrypted..
```

Also we tried to use `volumeClaimTemplates` configuration as below but the pods are always in `containerCreating` state:

```
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: webapp-os
  namespace: appns
spec:
  serviceName: webapp-os
  replicas: 4
  template:
    metadata:
      labels:
        app: webapp-os
        version: production
        tier: backend
    spec:
      containers:
      - name: minio
        env:
        - name: MINIO_ACCESS_KEY
          value: "xxxxx"
        - name: MINIO_SECRET_KEY
          value: "yyyy"
        image: minio/minio:RELEASE.2020-04-23T00-58-49Z
        args:
        - server
        - http://webapp-os-{0...3}.webapp-os.appns.svc.cluster.local/data
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: webapp-os-data
          mountPath: "/data"
  volumeClaimTemplates:
  - metadata:
      name: webapp-os-data
      namespace: appns
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 50Gi
```

## Your Environment
* Version used : minio/minio:RELEASE.2020-04-23T00-58-49Z
* Operating System and version:
NAME="Flatcar Container Linux by Kinvolk"
ID=flatcar
ID_LIKE=coreos
VERSION=2345.3.1
VERSION_ID=2345.3.1
BUILD_ID=2020-03-26-2026
PRETTY_NAME="Flatcar Container Linux by Kinvolk 2345.3.1 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://flatcar-linux.org/"
BUG_REPORT_URL="https://issues.flatcar-linux.org"
FLATCAR_BOARD="amd64-usr"
kernel:
Linux core4 4.19.107-flatcar #1 SMP Thu Mar 26 19:48:36 -00 2020 x86_64 Intel(R) Xeon(R) CPU E5-2430 v2 @ 2.50GHz GenuineIntel GNU/Linux
