### ISSUE TITLE
[faq] Error as server/data is not a valid command when deployed over AWS FARGATE ECS

### ISSUE THREAD

**Issue by vishallanke** [minio/minio#9494]
I am deploying report portal on AWS FARGATE ECS containers. I want to use below settings.
```
  minio:
    image: minio/minio:latest
    #ports:
    #  - '9000:9000'
    volumes:
      - ./data/storage:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: always
```

Login to AWS. Select ECS. Create Cluster. Create Task Definition. Add container inside Task Definition. Provide Image Name, Health Check, Commands as specified above inside ECS Task Definition. SAve Task Definition. Start the Task. 

Getting error as 'server /data' is a not valid command, existing container.
