### ISSUE TITLE
Write permission error using docker image

### ISSUE THREAD

**Issue by LukasFritzeDev** [minio/minio#9537]
The latest image produces a file permission error if used in a docker-compose file.

## Expected Behavior

Should have write permission to the data directory like the images before.

## Current Behavior

Given this `docker-compose.yaml`:
```yaml
services:
  minio:
    image: minio/minio
    volumes:
      - /tmp/minioData-1:/data1
    ports:
      - 9002:9000
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
```

produces the following error:

```yaml
 | ERROR Unable to initialize backend: Unable to write to the backend
 |       > Please ensure MinIO binary has write permissions for the backend
 |       HINT:
 |         Use 'sudo chown root /data1 && sudo chmod u+rxw /data1' to provide sufficient permissions.
```

Using
```yaml
    image: minio/minio:RELEASE.2020-05-01T22-19-14Z
```
works fine. The issue was introduced with `RELEASE.2020-05-06T23-23-25Z`.

Is there any update of the configuration required?

**Comment by gpulido** [comment]
I'm also having this problem.
I even tried with a new empty folder on the host and providing a 777 permissions without luck

**Comment by screencomuser** [comment]
Appears to have been caused by https://github.com/minio/minio/blob/fea4a1e68e9bf81b2997ca40b2c785d15b4a0748/cmd/posix.go#L181

Noticing this behavior on Docker for MacOS (docker-19.03.8)

Running the same on a Linux VM (LXC) does work with docker 19.03.6

**Comment by kobaltz** [comment]
Thank you for finding the last working version @LukasFritzeDev. That was going to be on my todo list today for one of my projects. 💌

**Comment by LukasFritzeDev** [comment]
I can confirm the behavior with macOS. A colleague just tried the docker-compose file with `latest` on his Linux machine and it works. For me on macOS it fails.

@kobaltz You’re welcome. It wasn’t that complicated since it was the second last version 😉

**Comment by gpulido** [comment]
I've just tried with latest on a Ubuntu server, running one node swarm and it doesn't work.

**Comment by harshavardhana** [comment]
We need direct IO supported backend.

**Comment by EricGregMiller** [comment]
This failed for us on our build slave. It fails when we use a shared memory ramdisk. It's OK when we use a regular disk.

**Comment by harshavardhana** [comment]
We will be reporting 

```
~ minio server /dev/shm/test
ERROR Unable to initialize backend: Unable to write to the backend
      > Please ensure your disk supports O_DIRECT
      HINT:
        '/dev/shm/test' does not support O_DIRECT flags, refusing to use
```

v/s

```
~ minio server /tmp/test
Endpoint:  http://10.0.0.67:9000  http://10.213.130.42:9000  http://172.17.0.1:9000  http://172.18.0.1:9000  http://127.0.0.1:9000            
AccessKey: minio 
SecretKey: minio123 
Region:    us-east-1

Browser Access:
   http://10.0.0.67:9000  http://10.213.130.42:9000  http://172.17.0.1:9000  http://172.18.0.1:9000  http://127.0.0.1:9000            

Command-line Access: https://docs.min.io/docs/minio-client-quickstart-guide
   $ mc config host add myminio http://10.0.0.67:9000 minio minio123
```

**Comment by jhendershott** [comment]
I'm seeing this exact issue still. Currently using centos as my linux distro

ERROR Unable to initialize backend: Unable to write to the backend
      > Please ensure MinIO binary has write permissions for the backend
      HINT:
        Use 'sudo chown -R root /data && sudo chmod u+rxw /data' to provide sufficient permissions.

As mentioned above. I have also created a /data folder with chmod 777 permission and root ownership but still seeing the same issue
```

  minio:
    image: minio/minio:latest
    #ports:
    #  - '9000:9000'
    volumes:
     # For unix host
      - ./data/storage:/data
     # For windows host
     # - minio:/data
    environment:
      MINIO_ACCESS_KEY: [accesskey]
      MINIO_SECRET_KEY: [secret]
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: always
```
as you can see runnong current latest. 

Does anyone have any other ideas?
