### ISSUE TITLE
Unable to mount a volume with docker from ver `RELEASE.2020-05-06T23-23-25Z`

### ISSUE THREAD

**Issue by mamoroom** [minio/minio#9549]
I got a volume mouting error from ver `RELEASE.2020-05-06T23-23-25Z` on docker hub.
the ver of `RELEASE.2020-05-01T22-19-14Z` worked.

- docker-compose.yml
```yaml
version: "3.7"
services:
  minio:
      image: minio/minio:RELEASE.2020-05-06T23-23-25Z
    ports:
      - "9000:9000"
    volumes:
      - './data:/export'
    environment:
      MINIO_ACCESS_KEY: brabra
      MINIO_SECRET_KEY: brabrabra
    command: server /export
```
- error
```shell
minio_1       | ERROR Unable to initialize backend: Unable to write to the backend
minio_1       |       > Please ensure MinIO binary has write permissions for the backend
minio_1       |       HINT:
minio_1       |         Use 'sudo chown root /export && sudo chmod u+rxw /export' to provide sufficient permissions.
```
