### ISSUE TITLE
Rolling Update in Kubernetes occur in errors while deployment

### ISSUE THREAD

**Issue by rdxmb** [minio/minio#9557]
##  Expected Behavior
When updating my distributed minIO-Cluster in kubernetes, I was expecting that this will run in zero-Downtime.

## Current Behavior
While updating in RollingUpdate, errors occur. This means, clients are not able to connect the minIO-instance while one after the other pod is updating. Also, the minIO-instances log something about unsufficient space (see below)
However, when all pods were upgraded, the minIO-cluster is available again and the disk space on each pod is like
`/dev/sdm                  4.9G      2.5G      2.1G  55% /data`

## Possible Solution
Maybe there is a kind of migration between the two versions. Do they need more than double the space? Maybe 60s waiting between upgrading the pods is not enough?

## Steps to Reproduce (for bugs)
Deploy the following setup with kubectl apply:

```
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: minio
  labels:
    app.kubernetes.io/name: minio-ha
    app.kubernetes.io/instance: "myproject"
spec:
  serviceName: minio-headless
  replicas: 4
  updateStrategy: 
    type: RollingUpdate
  selector:
    matchLabels:
        app.kubernetes.io/name: minio-ha
        app.kubernetes.io/instance: "myproject"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minio-ha
        app.kubernetes.io/instance: "myproject"
    spec:
      affinity:        
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 50
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: minio-ha
                    app.kubernetes.io/instance: "myproject"
                topologyKey: kubernetes.io/hostname
        
      containers:
        - name: minio
          image: "minio/minio:RELEASE.2019-03-27T22-35-21Z"
          imagePullPolicy: "IfNotPresent"
          args: 
            - server
            - "http://minio-0.minio-headless.myproject.svc.cluster.local/data"
            - "http://minio-1.minio-headless.myproject.svc.cluster.local/data"
            - "http://minio-2.minio-headless.myproject.svc.cluster.local/data"
            - "http://minio-3.minio-headless.myproject.svc.cluster.local/data"
          resources:
            limits:
              memory: 900Mi
          
          env:
            - name: TZ
              value: Etc/UTC
         
            - name: MINIO_ACCESS_KEY
              value: myaccesskey
            - name: MINIO_SECRET_KEY
              value: mysecretkey
            
          volumeMounts: 
            - name: minio
              mountPath: /data
              subPath: mount
            - name: minio
              mountPath: /root/.minio
              subPath: config
          readinessProbe:
            exec: 
              command: 
                - /bin/true
            initialDelaySeconds: 60
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: 9000
            initialDelaySeconds: 600
            periodSeconds: 60
  volumeClaimTemplates:
    - metadata:
        name: minio
        labels:
          app.kubernetes.io/name: minio-ha
          app.kubernetes.io/instance: "myproject"
          
      spec:
        storageClassName: "iscsi-pv-provisioner-delete"
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
---
# Source: minio-ha/templates/service.yaml

---
kind: Service
apiVersion: v1
metadata:
  name: minio-headless
  labels:
    app.kubernetes.io/name: minio-ha
    app.kubernetes.io/instance: "myproject"
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  selector:
    app.kubernetes.io/name: minio-ha
    app.kubernetes.io/instance: "myproject"
  ports:
  - protocol: TCP 
    port: 9000
  clusterIP: None
  publishNotReadyAddresses: true
---
kind: Service
apiVersion: v1
metadata:
  name: minio
  labels:
    app.kubernetes.io/name: minio-ha
    app.kubernetes.io/instance: "myproject"
spec:
  selector:
    app.kubernetes.io/name: minio-ha
    app.kubernetes.io/instance: "myproject"
  ports:
  - protocol: TCP 
    port: 9000
  type: LoadBalancer
  loadBalancerIP: 10.XX.XX.XX
```

Then change the image tag up to `RELEASE.2020-05-06T18-00-07Z` and deploy again.

## Context
I am trying to run a zero-downtime RollingUpdate in my production environment. Actually, in staging and qa this fails.

## Your Environment
* Version used (`minio version`): see above
* Environment name and version (e.g. nginx 1.9.1): kubernetes 1.17 with 1 master and 3 nodes
* Operating System and version (`uname -a`): ubuntu 16.04 LTS
* please also note that there are 60s "sleep" between updating the pods, which should be enough (?)
```
minio-0                          2/2     Running   0          7d17h
minio-1                          1/2     Running   0          16s
minio-2                          2/2     Running   0          100s
minio-3                          2/2     Running   0          3m20s
```

## log snippets
### minio-0
```
 You are running an older version of Minio released 1 year ago                                         
 Update: https://docs.minio.io/docs/deploy-minio-on-kubernetes                                         
                                                                                                       
                                                                                                       
Status:         3 Online, 1 Offline.                                                                   
Endpoint:  http://10.244.1.192:9000  http://127.0.0.1:9000                                             
                                                                                                       
Browser Access:                                                                                        
   http://10.244.1.192:9000  http://127.0.0.1:9000                                                     
                                                                                                       
Object API (Amazon S3 compatible):                                                                     
   Go:         https://docs.minio.io/docs/golang-client-quickstart-guide
   Java:       https://docs.minio.io/docs/java-client-quickstart-guide
   Python:     https://docs.minio.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.minio.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.minio.io/docs/dotnet-client-quickstart-guide

API: SYSTEM()
Time: 14:47:35 UTC 05/08/2020
Error: disk not found
       endpoint=http://minio-3.minio-headless.myproject.svc.cluster.local:9000/data
       1: cmd/prepare-storage.go:40:cmd.glob..func16.1()
       2: cmd/xl-sets.go:211:cmd.(*xlSets).connectDisks()
       3: cmd/xl-sets.go:242:cmd.(*xlSets).monitorAndConnectEndpoints()

API: SYSTEM()
Time: 14:49:21 UTC 05/08/2020
Error: 404 page not found

       1: cmd/xl-v1.go:83:cmd.getDisksInfo()
       2: cmd/xl-v1.go:114:cmd.getStorageInfo()
       3: cmd/xl-v1.go:147:cmd.xlObjects.StorageInfo()
       4: cmd/xl-sets.go:308:cmd.(*xlSets).StorageInfo()
       5: cmd/metrics.go:118:cmd.(*minioCollector).Collect()
       6: /q/.q/sources/gopath/pkg/mod/github.com/prometheus/client_golang@v0.9.2/prometheus/registry.go:434:prometheus.(*Registry).Gather.func1()

API: PutObject(bucket=mybucket, object=http-api-66f46976b7-rd8wn.livecheck)
Time: 14:49:21 UTC 05/08/2020
RequestID: 160D150251837348
RemoteHost: 10.244.1.103
Error: 404 page not found

       1: cmd/api-errors.go:1660:cmd.toAPIErrorCode()
       2: cmd/api-errors.go:1685:cmd.toAPIError()
       3: cmd/object-handlers.go:1250:cmd.objectAPIHandlers.PutObjectHandler()
       4: net/http/server.go:1995:http.HandlerFunc.ServeHTTP()

API: PutObject(bucket=mybucket, object=smtp-inbound-bddc9bdcf-6sbz7.livecheck)
Time: 14:49:21 UTC 05/08/2020
RequestID: 160D150510D39D39
RemoteHost: 10.244.1.146
Error: 404 page not found

       1: cmd/api-errors.go:1660:cmd.toAPIErrorCode()
       2: cmd/api-errors.go:1685:cmd.toAPIError()
       3: cmd/object-handlers.go:1250:cmd.objectAPIHandlers.PutObjectHandler()
       4: net/http/server.go:1995:http.HandlerFunc.ServeHTTP()

API: SYSTEM()
Time: 14:49:21 UTC 05/08/2020
Error: 404 page not found

       1: cmd/xl-v1.go:83:cmd.getDisksInfo()
       2: cmd/xl-v1.go:114:cmd.getStorageInfo()
       3: cmd/xl-v1.go:147:cmd.xlObjects.StorageInfo()
       4: cmd/xl-sets.go:308:cmd.(*xlSets).StorageInfo()
       5: cmd/metrics.go:118:cmd.(*minioCollector).Collect()
       6: /q/.q/sources/gopath/pkg/mod/github.com/prometheus/client_golang@v0.9.2/prometheus/registry.go:434:prometheus.(*Registry).Gather.func1()

API: PutObject(bucket=mybucket, object=smtp-outbound-78dbd68f6d-8lwc4.livecheck)
Time: 14:49:29 UTC 05/08/2020
RequestID: 160D150870AF57F1
RemoteHost: 10.244.1.111
Error: 404 page not found

       1: cmd/api-errors.go:1660:cmd.toAPIErrorCode()
       2: cmd/api-errors.go:1685:cmd.toAPIError()
       3: cmd/object-handlers.go:1250:cmd.objectAPIHandlers.PutObjectHandler()
       4: net/http/server.go:1995:http.HandlerFunc.ServeHTTP()

API: SYSTEM()
Time: 14:50:00 UTC 05/08/2020
Error: 404 page not found

       1: cmd/xl-v1.go:83:cmd.getDisksInfo()
       2: cmd/xl-v1.go:114:cmd.getStorageInfo()
       3: cmd/xl-v1.go:147:cmd.xlObjects.StorageInfo()
       4: cmd/xl-sets.go:308:cmd.(*xlSets).StorageInfo()
       5: cmd/metrics.go:118:cmd.(*minioCollector).Collect()
       6: /q/.q/sources/gopath/pkg/mod/github.com/prometheus/client_golang@v0.9.2/prometheus/registry.go:434:prometheus.(*Registry).Gather.func1()

API: SYSTEM()
Time: 14:50:00 UTC 05/08/2020
Error: 404 page not found

       1: cmd/xl-v1.go:83:cmd.getDisksInfo()
       2: cmd/xl-v1.go:114:cmd.getStorageInfo()
       3: cmd/xl-v1.go:147:cmd.xlObjects.StorageInfo()
       4: cmd/xl-sets.go:308:cmd.(*xlSets).StorageInfo()
       5: cmd/metrics.go:118:cmd.(*minioCollector).Collect()
       6: /q/.q/sources/gopath/pkg/mod/github.com/prometheus/client_golang@v0.9.2/prometheus/registry.go:434:prometheus.(*Registry).Gather.func1()

API: PutObject(bucket=mybucket, object=http-api-66f46976b7-rzxkm.livecheck)
Time: 14:50:01 UTC 05/08/2020
RequestID: 160D150FCAAF0FC1
RemoteHost: 10.244.1.97
Error: 404 page not found

       1: cmd/api-errors.go:1660:cmd.toAPIErrorCode()
       2: cmd/api-errors.go:1685:cmd.toAPIError()
       3: cmd/object-handlers.go:1250:cmd.objectAPIHandlers.PutObjectHandler()
       4: net/http/server.go:1995:http.HandlerFunc.ServeHTTP()

API: PutObject(bucket=mybucket, object=http-api-66f46976b7-rzxkm.livecheck)
Time: 14:50:11 UTC 05/08/2020
RequestID: 160D151218D4244B
RemoteHost: 10.244.1.97
Error: 404 page not found

       1: cmd/api-errors.go:1660:cmd.toAPIErrorCode()
       2: cmd/api-errors.go:1685:cmd.toAPIError()
       3: cmd/object-handlers.go:1250:cmd.objectAPIHandlers.PutObjectHandler()
       4: net/http/server.go:1995:http.HandlerFunc.ServeHTTP()

API: SYSTEM()
Time: 14:51:00 UTC 05/08/2020
Error: 404 page not found

       1: cmd/xl-v1.go:83:cmd.getDisksInfo()
       2: cmd/xl-v1.go:114:cmd.getStorageInfo()
       3: cmd/xl-v1.go:147:cmd.xlObjects.StorageInfo()
       4: cmd/xl-sets.go:308:cmd.(*xlSets).StorageInfo()
       5: cmd/metrics.go:118:cmd.(*minioCollector).Collect()
       6: /q/.q/sources/gopath/pkg/mod/github.com/prometheus/client_golang@v0.9.2/prometheus/registry.go:434:prometheus.(*Registry).Gather.func1()

API: SYSTEM()
Time: 14:51:00 UTC 05/08/2020
Error: 404 page not found

       1: cmd/xl-v1.go:83:cmd.getDisksInfo()
       2: cmd/xl-v1.go:114:cmd.getStorageInfo()
       3: cmd/xl-v1.go:147:cmd.xlObjects.StorageInfo()
       4: cmd/xl-sets.go:308:cmd.(*xlSets).StorageInfo()
       5: cmd/metrics.go:118:cmd.(*minioCollector).Collect()
       6: /q/.q/sources/gopath/pkg/mod/github.com/prometheus/client_golang@v0.9.2/prometheus/registry.go:434:prometheus.(*Registry).Gather.func1()

API: SYSTEM()
Time: 14:51:00 UTC 05/08/2020
Error: 404 page not found

       1: cmd/xl-v1.go:83:cmd.getDisksInfo()
       2: cmd/xl-v1.go:114:cmd.getStorageInfo()
       3: cmd/xl-v1.go:147:cmd.xlObjects.StorageInfo()
       4: cmd/xl-sets.go:308:cmd.(*xlSets).StorageInfo()
       5: cmd/metrics.go:118:cmd.(*minioCollector).Collect()
       6: /q/.q/sources/gopath/pkg/mod/github.com/prometheus/client_golang@v0.9.2/prometheus/registry.go:434:prometheus.(*Registry).Gather.func1()

API: SYSTEM()
Time: 14:51:00 UTC 05/08/2020
Error: 404 page not found

       1: cmd/xl-v1.go:83:cmd.getDisksInfo()
       2: cmd/xl-v1.go:114:cmd.getStorageInfo()
       3: cmd/xl-v1.go:147:cmd.xlObjects.StorageInfo()
       4: cmd/xl-sets.go:308:cmd.(*xlSets).StorageInfo()
       5: cmd/metrics.go:118:cmd.(*minioCollector).Collect()
       6: /q/.q/sources/gopath/pkg/mod/github.com/prometheus/client_golang@v0.9.2/prometheus/registry.go:434:prometheus.(*Registry).Gather.func1()
```

### minio-3
```
[snip]

Unable to read 'format.json' from http://minio-0.minio-headless.myproject.svc.cluster.local:9000/data: invalid character '<' looking for beginning of value

Unable to read 'format.json' from http://minio-1.minio-headless.myproject.svc.cluster.local:9000/data: invalid character '<' looking for beginning of value

Unable to read 'format.json' from http://minio-2.minio-headless.myproject.svc.cluster.local:9000/data: invalid character '<' looking for beginning of value

Waiting for a minimum of 2 disks to come online (elapsed 1m8s)

Unable to read 'format.json' from http://minio-0.minio-headless.myproject.svc.cluster.local:9000/data: invalid character '<' looking for beginning of value

Unable to read 'format.json' from http://minio-1.minio-headless.myproject.svc.cluster.local:9000/data: invalid character '<' looking for beginning of value

Waiting for a minimum of 2 disks to come online (elapsed 1m8s)

Unable to read 'format.json' from http://minio-0.minio-headless.myproject.svc.cluster.local:9000/data: invalid character '<' looking for beginning of value

Unable to read 'format.json' from http://minio-1.minio-headless.myproject.svc.cluster.local:9000/data: invalid character '<' looking for beginning of value

Waiting for a minimum of 2 disks to come online (elapsed 1m9s)

Unable to read 'format.json' from http://minio-0.minio-headless.myproject.svc.cluster.local:9000/data: invalid character '<' looking for beginning of value

Unable to read 'format.json' from http://minio-1.minio-headless.myproject.svc.cluster.local:9000/data: invalid character '<' looking for beginning of value

Waiting for a minimum of 2 disks to come online (elapsed 2m9s)

Unable to read 'format.json' from http://minio-0.minio-headless.myproject.svc.cluster.local:9000/data: invalid character '<' looking for beginning of value

Unable to read 'format.json' from http://minio-1.minio-headless.myproject.svc.cluster.local:9000/data: invalid character '<' looking for beginning of value

Waiting for all MinIO sub-systems to be initialized.. lock acquired
Attempting encryption of all config, IAM users and policies on MinIO backend

API: SYSTEM()
Time: 14:49:55 UTC 05/08/2020
DeploymentID: 43ae9190-04f5-4ae6-818f-97a41c021092
Error: Write failed. Insufficient number of disks online
      10: github.com/minio/minio@/cmd/erasure-encode.go:100:cmd.(*Erasure).Encode()
       9: github.com/minio/minio@/cmd/xl-v1-object.go:597:cmd.xlObjects.putObject()
       8: github.com/minio/minio@/cmd/xl-v1-object.go:481:cmd.xlObjects.PutObject()
       7: github.com/minio/minio@/cmd/xl-sets.go:751:cmd.(*xlSets).PutObject()
       6: github.com/minio/minio@/cmd/xl-zones.go:463:cmd.(*xlZones).PutObject()
       5: github.com/minio/minio@/cmd/config-common.go:66:cmd.saveConfig()
       4: github.com/minio/minio@/cmd/config-encrypted.go:237:cmd.migrateConfigPrefixToEncrypted()
       3: github.com/minio/minio@/cmd/config-encrypted.go:63:cmd.handleEncryptedConfigBackend()
       2: github.com/minio/minio@/cmd/server-main.go:227:cmd.initSafeMode()
       1: github.com/minio/minio@/cmd/server-main.go:521:cmd.serverMain()
Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to migrate all config at .minio.sys/config/: Storage resources are insufficient for the write operation.)

API: BackgroundHeal()
Time: 14:49:55 UTC 05/08/2020
DeploymentID: 43ae9190-04f5-4ae6-818f-97a41c021092
Error: Write failed. Insufficient number of disks online
       2: github.com/minio/minio@/cmd/admin-heal-ops.go:683:cmd.(*healSequence).healItemsFromSourceCh()
       1: github.com/minio/minio@/cmd/admin-heal-ops.go:717:cmd.(*healSequence).healFromSourceCh()
Waiting for all MinIO sub-systems to be initialized.. lock acquired
Attempting encryption of all config, IAM users and policies on MinIO backend

API: SYSTEM()
Time: 14:49:55 UTC 05/08/2020
DeploymentID: 43ae9190-04f5-4ae6-818f-97a41c021092
Error: Write failed. Insufficient number of disks online
      10: github.com/minio/minio@/cmd/erasure-encode.go:100:cmd.(*Erasure).Encode()
       9: github.com/minio/minio@/cmd/xl-v1-object.go:597:cmd.xlObjects.putObject()
       8: github.com/minio/minio@/cmd/xl-v1-object.go:481:cmd.xlObjects.PutObject()
       7: github.com/minio/minio@/cmd/xl-sets.go:751:cmd.(*xlSets).PutObject()
       6: github.com/minio/minio@/cmd/xl-zones.go:463:cmd.(*xlZones).PutObject()
       5: github.com/minio/minio@/cmd/config-common.go:66:cmd.saveConfig()
       4: github.com/minio/minio@/cmd/config-encrypted.go:237:cmd.migrateConfigPrefixToEncrypted()
       3: github.com/minio/minio@/cmd/config-encrypted.go:63:cmd.handleEncryptedConfigBackend()
       2: github.com/minio/minio@/cmd/server-main.go:227:cmd.initSafeMode()
       1: github.com/minio/minio@/cmd/server-main.go:521:cmd.serverMain()
Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to migrate all config at .minio.sys/config/: Storage resources are insufficient for the write operation.)
Waiting for all MinIO sub-systems to be initialized.. lock acquired
Attempting encryption of all config, IAM users and policies on MinIO backend

API: SYSTEM()
Time: 14:49:56 UTC 05/08/2020
DeploymentID: 43ae9190-04f5-4ae6-818f-97a41c021092
Error: Write failed. Insufficient number of disks online
      10: github.com/minio/minio@/cmd/erasure-encode.go:100:cmd.(*Erasure).Encode()
       9: github.com/minio/minio@/cmd/xl-v1-object.go:597:cmd.xlObjects.putObject()
       8: github.com/minio/minio@/cmd/xl-v1-object.go:481:cmd.xlObjects.PutObject()
       7: github.com/minio/minio@/cmd/xl-sets.go:751:cmd.(*xlSets).PutObject()
       6: github.com/minio/minio@/cmd/xl-zones.go:463:cmd.(*xlZones).PutObject()
       5: github.com/minio/minio@/cmd/config-common.go:66:cmd.saveConfig()
       4: github.com/minio/minio@/cmd/config-encrypted.go:237:cmd.migrateConfigPrefixToEncrypted()
       3: github.com/minio/minio@/cmd/config-encrypted.go:63:cmd.handleEncryptedConfigBackend()
       2: github.com/minio/minio@/cmd/server-main.go:227:cmd.initSafeMode()
       1: github.com/minio/minio@/cmd/server-main.go:521:cmd.serverMain()
Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to migrate all config at .minio.sys/config/: Storage resources are insufficient for the write operation.)
Waiting for all MinIO sub-systems to be initialized.. lock acquired
Attempting encryption of all config, IAM users and policies on MinIO backend

API: SYSTEM()
Time: 14:50:02 UTC 05/08/2020
DeploymentID: 43ae9190-04f5-4ae6-818f-97a41c021092
Error: Write failed. Insufficient number of disks online
      10: github.com/minio/minio@/cmd/erasure-encode.go:100:cmd.(*Erasure).Encode()
       9: github.com/minio/minio@/cmd/xl-v1-object.go:597:cmd.xlObjects.putObject()
       8: github.com/minio/minio@/cmd/xl-v1-object.go:481:cmd.xlObjects.PutObject()
       7: github.com/minio/minio@/cmd/xl-sets.go:751:cmd.(*xlSets).PutObject()
       6: github.com/minio/minio@/cmd/xl-zones.go:463:cmd.(*xlZones).PutObject()
       5: github.com/minio/minio@/cmd/config-common.go:66:cmd.saveConfig()
       4: github.com/minio/minio@/cmd/config-encrypted.go:237:cmd.migrateConfigPrefixToEncrypted()
       3: github.com/minio/minio@/cmd/config-encrypted.go:63:cmd.handleEncryptedConfigBackend()
       2: github.com/minio/minio@/cmd/server-main.go:227:cmd.initSafeMode()
       1: github.com/minio/minio@/cmd/server-main.go:521:cmd.serverMain()
Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to migrate all config at .minio.sys/config/: Storage resources are insufficient for the write operation.)

API: SYSTEM()
Time: 14:50:05 UTC 05/08/2020
DeploymentID: 43ae9190-04f5-4ae6-818f-97a41c021092
Error: invalid character '<' looking for beginning of value
       endpoint=http://minio-1.minio-headless.myproject.svc.cluster.local:9000/data
       2: github.com/minio/minio@/cmd/prepare-storage.go:49:cmd.glob..func4.1()
       1: github.com/minio/minio@/cmd/xl-sets.go:230:cmd.(*xlSets).connectDisks.func1()

API: SYSTEM()
Time: 14:50:05 UTC 05/08/2020
DeploymentID: 43ae9190-04f5-4ae6-818f-97a41c021092
Error: invalid character '<' looking for beginning of value
       endpoint=http://minio-0.minio-headless.myproject.svc.cluster.local:9000/data
       2: github.com/minio/minio@/cmd/prepare-storage.go:49:cmd.glob..func4.1()
       1: github.com/minio/minio@/cmd/xl-sets.go:230:cmd.(*xlSets).connectDisks.func1()
Waiting for all MinIO sub-systems to be initialized.. lock acquired
Attempting encryption of all config, IAM users and policies on MinIO backend

API: SYSTEM()
Time: 14:50:09 UTC 05/08/2020
DeploymentID: 43ae9190-04f5-4ae6-818f-97a41c021092
Error: Write failed. Insufficient number of disks online
      10: github.com/minio/minio@/cmd/erasure-encode.go:100:cmd.(*Erasure).Encode()
       9: github.com/minio/minio@/cmd/xl-v1-object.go:597:cmd.xlObjects.putObject()
       8: github.com/minio/minio@/cmd/xl-v1-object.go:481:cmd.xlObjects.PutObject()
       7: github.com/minio/minio@/cmd/xl-sets.go:751:cmd.(*xlSets).PutObject()
       6: github.com/minio/minio@/cmd/xl-zones.go:463:cmd.(*xlZones).PutObject()
       5: github.com/minio/minio@/cmd/config-common.go:66:cmd.saveConfig()
       4: github.com/minio/minio@/cmd/config-encrypted.go:237:cmd.migrateConfigPrefixToEncrypted()
       3: github.com/minio/minio@/cmd/config-encrypted.go:63:cmd.handleEncryptedConfigBackend()
       2: github.com/minio/minio@/cmd/server-main.go:227:cmd.initSafeMode()
       1: github.com/minio/minio@/cmd/server-main.go:521:cmd.serverMain()
Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to migrate all config at .minio.sys/config/: Storage resources are insufficient for the write operation.)

API: SYSTEM()
Time: 14:50:25 UTC 05/08/2020
DeploymentID: 43ae9190-04f5-4ae6-818f-97a41c021092
Error: disk not found
       endpoint=http://minio-1.minio-headless.myproject.svc.cluster.local:9000/data
       2: github.com/minio/minio@/cmd/prepare-storage.go:56:cmd.glob..func4.1()
       1: github.com/minio/minio@/cmd/xl-sets.go:230:cmd.(*xlSets).connectDisks.func1()
Waiting for all MinIO sub-systems to be initialized.. lock acquired
Attempting encryption of all config, IAM users and policies on MinIO backend

API: SYSTEM()
Time: 14:50:25 UTC 05/08/2020
DeploymentID: 43ae9190-04f5-4ae6-818f-97a41c021092
Error: Write failed. Insufficient number of disks online
      10: github.com/minio/minio@/cmd/erasure-encode.go:100:cmd.(*Erasure).Encode()
       9: github.com/minio/minio@/cmd/xl-v1-object.go:597:cmd.xlObjects.putObject()
       8: github.com/minio/minio@/cmd/xl-v1-object.go:481:cmd.xlObjects.PutObject()
       7: github.com/minio/minio@/cmd/xl-sets.go:751:cmd.(*xlSets).PutObject()
       6: github.com/minio/minio@/cmd/xl-zones.go:463:cmd.(*xlZones).PutObject()
       5: github.com/minio/minio@/cmd/config-common.go:66:cmd.saveConfig()
       4: github.com/minio/minio@/cmd/config-encrypted.go:237:cmd.migrateConfigPrefixToEncrypted()
       3: github.com/minio/minio@/cmd/config-encrypted.go:63:cmd.handleEncryptedConfigBackend()
       2: github.com/minio/minio@/cmd/server-main.go:227:cmd.initSafeMode()
       1: github.com/minio/minio@/cmd/server-main.go:521:cmd.serverMain()
Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to migrate all config at .minio.sys/config/: Storage resources are insufficient for the write operation.)
Waiting for all MinIO sub-systems to be initialized.. lock acquired
All MinIO sub-systems initialized successfully
Use `mc admin info` to look for latest server/disk info
 Status:         3 Online, 1 Offline. 
Endpoint:  http://10.244.2.219:9000  http://127.0.0.1:9000

Browser Access:
   http://10.244.2.219:9000  http://127.0.0.1:9000

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide

API: SYSTEM()
Time: 14:52:23 UTC 05/08/2020
DeploymentID: 43ae9190-04f5-4ae6-818f-97a41c021092
Error: disk not found
       endpoint=http://minio-0.minio-headless.myproject.svc.cluster.local:9000/data
       2: github.com/minio/minio@/cmd/prepare-storage.go:56:cmd.glob..func4.1()
       1: github.com/minio/minio@/cmd/xl-sets.go:230:cmd.(*xlSets).connectDisks.func1()

[snip]
```
