### ISSUE TITLE
MinIO Scaling

### ISSUE THREAD

**Issue by dev5790** [minio/minio#9576]
I am working on a project which uses MinIO as a file server. The project is running on a VSphere Kubernetes cluster with three nodes.

The initial deployment is using MinIO in a distributed mode having 3 Minio instances with 2 disks each. The below docker-compose was used to bring up the initial deployment.

```
version: '3.3'

services:
  minio1:
    image: minio/minio:RELEASE.2020-05-06T23-23-25Z
    volumes:
      - /home/user1/minio_data/data1-1:/data1
      - /home/user1/minio_data/data2-2:/data2
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio{1...3}/data{1...2}
    networks:
      - minio_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  minio2:
    image: minio/minio:RELEASE.2020-05-06T23-23-25Z
    volumes:
      - /home/user1/minio_data/data3-1:/data1
      - /home/user1/minio_data/data4-2:/data2
    ports:
      - "9002:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio{1...3}/data{1...2}
    networks:
      - minio_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  minio3:
    image: minio/minio:RELEASE.2020-05-06T23-23-25Z
    volumes:
      - /home/user1/minio_data/data5-1:/data1
      - /home/user1/minio_data/data6-2:/data2
    ports:
      - "9003:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio{1...3}/data{1...2}
    networks:
      - minio_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

networks:
  minio_network:
    external: true
```
This question is regarding the scaling of these instances. We ran the below file to add further instances and disks.

```
version: '3.3'
services:
  minio4:
    image: minio/minio:RELEASE.2020-05-06T23-23-25Z
    volumes:
      - /home/user1/minio_data/data7-1:/data1
      - /home/user1/minio_data/data8-2:/data2
    ports:
      - "9004:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio{1...3}/data{1...2} http://minio{4...6}/data{1...2}
    networks:
      - minio_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  minio5:
    image: minio/minio:RELEASE.2020-05-06T23-23-25Z
    volumes:
      - /home/user1/minio_data/data9-1:/data1
      - /home/user1/minio_data/data10-2:/data2
    ports:
      - "9005:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio{1...3}/data{1...2} http//minio{4...6}/data{1...2}
    networks:
      - minio_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
   minio6:
    image: minio/minio:RELEASE.2020-05-06T23-23-25Z
    volumes:
      - /home/user1/minio_data/data11-1:/data1
      - /home/user1/minio_data/data12-2:/data2
    ports:
      - "9006:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio{1...3}/data{1...2} http://minio{4...6}/data{1...2}
    networks:
      - minio_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
networks:
  minio_network:
    external: true
```
But this action failed and I got the error "waiting for disk".

```
minio6_1  | Waiting for the first server to format the disks.
minio5_1  | Waiting for the first server to format the disks.
minio4_1  | Waiting for the first server to format the disks.
minio6_1  | Waiting for the first server to format the disks.
```
Is this the correct way to scale the setup? Are there any steps missing?

## Your Environment

* Version used (`minio version`): latest
* Operating System and version (`uname -a`): Linux accslgalvmipo 3.10.0-693.el7.x86_64
