### ISSUE TITLE
notify_mysql doesn't reconnect on timeouts (tested with mariadb)

### ISSUE THREAD

**Issue by buhl** [minio/minio#9679]
## Expected Behavior
When the mysql server drops the client connection minio should reestablish a new one.

## Current Behavior
When using notify_mysql an not notifications has been send for a while. The mysql server will drop the connection and next time minio wants to send a notification an error is raised.
I have tried different dsn settings timeout settings without luck.
Also the setting [checkConnLiveness](https://github.com/go-sql-driver/mysql#checkconnliveness) is unrecognized.
```
$ mc admin config set minio notify_mysql:1 enable=on format=access dsn_string="minio:minio123@tcp(mariadb:
3306)/minio?charset=utf8mb4,utf8&timeout=300s&checkConnLiveness=true" table=mini_access
mc: <ERROR> Cannot set 'notify_mysql:1 enable=on format=access dsn_string=minio:minio123@tcp(mariadb:3306)/minio?charset=utf8mb4,utf8&timeout=300s&checkConnLiveness=true table=mini_access' to server. Error 1193: Unknown system variable 'checkConnLiveness'.
```

From the log:
```
minio4_1              | API: SYSTEM()
minio4_1              | Time: 21:44:42 UTC 05/21/2020
minio4_1              | DeploymentID: 5d677f54-8865-4ab5-851c-005bd9ab41af
minio4_1              | Error: bad connection
minio4_1              |        targetID=mysql
minio4_1              |        3: github.com/minio/minio@/cmd/logger/logonce.go:52:logger.(*logOnceType).logOnceIf()
minio4_1              |        2: github.com/minio/minio@/cmd/logger/logonce.go:80:logger.LogOnceIf()
minio4_1              |        1: github.com/minio/minio@/cmd/notification.go:796:cmd.(*NotificationSys).Init.func1()
```

## Possible Solution
I don't know if it is just a setting I missed.
But I think if we could get minio to send keep alive packages to the server this would not happen and maybe as a fallback use `checkconnliveness`

## Steps to Reproduce (for bugs)
Use this docker-compose.yml
```
version: "3.7"
services:

  minio1:
    image: minio/minio:latest
    volumes:
      - data1-1:/data1
      - data1-2:/data2
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio{1...4}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio2:
    image: minio/minio:latest
    volumes:
      - data2-1:/data1
      - data2-2:/data2
    ports:
      - "9002:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio{1...4}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio3:
    image: minio/minio:latest
    volumes:
      - data3-1:/data1
      - data3-2:/data2
    ports:
      - "9003:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio{1...4}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio4:
    image: minio/minio:latest
    volumes:
      - data4-1:/data1
      - data4-2:/data2
    ports:
      - "9004:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio{1...4}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  mariadb:
      image: mariadb:latest
      environment:
          MYSQL_USER: nifi
          MYSQL_PASSWORD: nifi123
          MYSQL_DATABASE: nifi
          MYSQL_ROOT_PASSWORD: root123

volumes:
  data1-1:
  data1-2:
  data2-1:
  data2-2:
  data3-1:
  data3-2:
  data4-1:
  data4-2:
```
Then do
```
$ docker-compose up -d
$ mc admin config set minio notify_mysql:test enable=on format=access dsn_string="minio:minio123@tcp(mariadb:
3306)/minio?charset=utf8mb4,utf8&timeout=300s" table=mini_access queue_dir=
Setting new key has been successful.
Please restart your server with `mc admin service restart minio`.
$ mc admin service restart minio
$ mc mb myminio/test
$ mc event add myminio/test arn:minio:sqs::test:mysql --event put,delete,get
```
wait 5 minutes or so and upload a file to minio to see the previously mentioned error in minios log

## Regression
I don't know

## Your Environment
LSB Version:	core-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal
