### ISSUE TITLE
Server startup failed with 'Unable to initialize sub-systems: Unable to migrate all config at .minio.sys/config/

### ISSUE THREAD

**Issue by partizza** [minio/minio#9726]
Can't start minio container with volumes 

## Expected Behavior
Run minio container with mounted directory

docker-compose.yml consist with:

```
version: "3"
services:

  minio:
    image: minio/minio
    container_name: minio
    hostname: minio
    volumes:
      - ./minio/s3:/data
    ports:
      - 9000:9000
    command: 'server /data'
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
```
 

## Current Behavior
```
Creating minio ... done
Attaching to minio
minio    | Attempting encryption of all config, IAM users and policies on MinIO backend
minio    | 
minio    | API: SYSTEM()
minio    | Time: 16:41:52 UTC 05/28/2020
minio    | DeploymentID: fe4965f4-6869-4143-93a3-8a6212da10b1
minio    | Error: Unexpected error, please report this issue at https://github.com/minio/minio/issues
minio    |        8: github.com/minio/minio@/cmd/fs-v1-helpers.go:337:cmd.fsCreateFile()
minio    |        7: github.com/minio/minio@/cmd/fs-v1.go:996:cmd.(*FSObjects).putObject()
minio    |        6: github.com/minio/minio@/cmd/fs-v1.go:910:cmd.(*FSObjects).PutObject()
minio    |        5: github.com/minio/minio@/cmd/config-common.go:66:cmd.saveConfig()
minio    |        4: github.com/minio/minio@/cmd/config-encrypted.go:237:cmd.migrateConfigPrefixToEncrypted()
minio    |        3: github.com/minio/minio@/cmd/config-encrypted.go:63:cmd.handleEncryptedConfigBackend()
minio    |        2: github.com/minio/minio@/cmd/server-main.go:230:cmd.initSafeMode()
minio    |        1: github.com/minio/minio@/cmd/server-main.go:524:cmd.serverMain()
minio    | Server startup failed with 'Unable to initialize sub-systems: Unable to migrate all config at .minio.sys/config/: Unexpected error, please report this issue at https://githu
b.com/minio/minio/issues'
minio    | Server switching to safe mode
minio    | Please use 'mc admin config' commands fix this issue
minio    | Endpoint:  http://172.21.0.2:9000  http://127.0.0.1:9000

```

## Steps to Reproduce (for bugs)
1. docker-compose up --build
