### ISSUE TITLE
NAS Gateway can't start over NFS

### ISSUE THREAD

**Issue by HelderFSFerreira** [minio/minio#9779]
I'm trying to mount an NFSv3 share as data volume using MinIO NAS Gateway

## Expected Behavior

Start without any issues

## Current Behavior
When I started the container it stops with this issue:
`minio    | ERROR Unable to initialize gateway backend: Unable to write to the backend
minio    |       > Please ensure MinIO binary has write permissions for the backend
minio    |       HINT:
minio    |         Use 'sudo chown root /data && sudo chmod u+rxw /data' to provide sufficient permissions.
minio exited with code 1`

Permitions on the ./nfs:
`ls -ali
total 5
      4 drwxrwxr-x 2 root root    2 Jun  6 11:39 .
`

## Possible Solution
As I'm using and NFSv3 share the command chown is not posible to use, having the proper user permissions configured correctly  the error on chown command shouldn't stop the container.

## Steps to Reproduce (for bugs)
1. Create an NFSv3 Share and mount it
2. Use this compose:
```
version: "3.3"

services:

  minio:
    image: minio/minio
    container_name: minio
    environment: 
      - "MINIO_ACCESS_KEY=minio"
      - "MINIO_SECRET_KEY=minio123"
    ports:
      - 9000:9000
    volumes:
      - ./nfs:/data
    command: gateway nas /data
```

## Context
I'm unable to start using MinIO my S3 object storage using my file server over NFS

## Your Environment

* Version used (`minio docker img`): 5f9dddcc548c 
* Environment name and version (e.g. nginx 1.9.1): Using ubuntu 20:04 as client and Freenas 11.2 as NFS mount host
* Server type and version:
* Operating System and version (`uname -a`): Ubuntu 18:04 as an alternative server that I already tested
* Link to your project:
