### ISSUE TITLE
[resolved] Minio access key and secret key passing through vault and setting them as environment variable is not working. 

### ISSUE THREAD

**Issue by Srikanthshetty** [minio/minio#9814]
## Expected Behavior
I am implementing minio distributed statefulset installation using vault secrets. As per vault documentation to use vault secrets as application environment variable,  secrets file should be sourced during container startup. Sourcing secrets using in statefulset commands not working along with minio startup commands.

my statefulset.yaml
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  entrypoint.sh: |-
    #!/bin/sh
    source /vault/secrets/minio
---
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: StatefulSet
metadata:
  name: minio
  namespace: minio
  labels:
     app: minio
spec:
  selector:
    matchLabels:
      app: minio
  serviceName: minio
  replicas: 4
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-status: "update"
        vault.hashicorp.com/role: "minio-role"
        vault.hashicorp.com/agent-inject-secret-minio: "secret/minio/credentials"
        vault.hashicorp.com/agent-inject-template-minio: |
          {{- with secret "secret/minio/credentials" -}}
             export MINIO_ACCESS_KEY="{{ .Data.MINIO_ACCESS_KEY }}"
             export MINIO_SECRET_KEY= "{{ .Data.MINIO_SECRET_KEY }}"
          {{- end -}}
      labels:
        app: minio
    spec:
      serviceAccountName: minio-sa
      containers:
      - name: minio
        image: minio/minio:latest
        command:
        - /bin/entrypoint.sh
        args:
        - server
        - http://minio-0.minio.minio.svc.cluster.local/data
        - http://minio-1.minio.minio.svc.cluster.local/data
        - http://minio-2.minio.minio.svc.cluster.local/data
        - http://minio-3.minio.minio.svc.cluster.local/data
        ports:
        - containerPort: 9000
          hostPort: 9000
        # These volume mounts are persistent. Each pod in the StatefulSet
        # gets a volume mounted based on this field.
        volumeMounts:
        - name: data
          mountPath: /data
        - name: configmap-volume
          mountPath: /bin/entrypoint.sh
          readOnly: true
          subPath: entrypoint.sh
      volumes:
      - name: configmap-volume
        configMap:
          defaultMode: 0700
          name: my-configmap
  # These are converted to volume claims by the controller
  # and mounted at the paths mentioned above.
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: minio-sc
      resources:
        requests:
          storage: 10Gi

```

using above configmap option to execute sourcing of secret file or passing directly in  command and args  ["/bin/sh","-c", "source /vault/secrets/minio"] along with minio commands goes crashloopback and no logs for this specific error.

![image](https://user-images.githubusercontent.com/19268128/84467618-b015d680-ac4a-11ea-89f8-b53797e98445.png)

Looks like i cant run "sh" commands along with minio startup command "-server" and " - http://minio-0.minio.minio.svc.cluster.local/data" together

## Possible Solution
Is there any minio commands to source the file ? 

## Steps to Reproduce (for bugs)
I am following with environment variable. 
https://www.vaultproject.io/docs/platform/k8s/injector/examples#environment-variable-example

Vault secret file in stored in /vault/secret/minio and i am able to see the accesskey and secretkey passed through vault.

1. Using Vault in kubernetes using vault injector
2. Minio distributed with statefulset
3. Sourcing vault secrets as minio environment variable is not working.
4. Using K8s secrets i am able to successfully install but not with Hashicorp Vault.

## Your Environment

* Version used (`minio version`): minio version RELEASE.2020-06-12T00-06-19Z 
* Environment name and version (e.g. nginx 1.9.1): In k8s cluster 
* Server type and version: K8s version : 1.16.7 in PKS
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by harshavardhana** [comment]
>              export MINIO_ACCESS_KEY1= "{{ .Data.MINIO_ACCESS_KEY }}"

There is no such thing as MINIO_ACCES_KEY1 its just MINIO_ACCESS_KEY @Srikanthshetty

**Comment by Srikanthshetty** [comment]
Sorry i didnt updated original post. Since it is not loading i just used kubernetes secret with vault secrets to see if vault secrets moved to minio container. I used MINIO_ACCESS_KEY and MINO_SECRET_KEY only and it still not working. I updated the original comment.

**Comment by harshavardhana** [comment]
@Srikanthshetty here is how to run this successfully 

```yaml
## Create headless service to StatefulSet to work.
apiVersion: v1
kind: Service
metadata:
  name: minio-headless
  labels:
    app: minio-headless
spec:
  ports:
  - port: 9000
  clusterIP: None
  selector:
    app: minio
---
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: StatefulSet
metadata:
  name: minio
  labels:
     app: minio
spec:
  selector:
    matchLabels:
      app: minio
  serviceName: "minio-headless"
  replicas: 4
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-minio-secrets: "internal/data/minio/config"
        vault.hashicorp.com/role: "minio-app"
        vault.hashicorp.com/agent-inject-template-minio-secrets: |
          {{- with secret "internal/data/minio/config" -}}
             export MINIO_ACCESS_KEY="{{ .Data.data.access_key }}"
             export MINIO_SECRET_KEY="{{ .Data.data.secret_key }}"
          {{- end -}}
      labels:
        app: minio
    spec:
      serviceAccountName: minio-app
      containers:
      - name: minio
        image: minio/minio:RELEASE.2020-06-14T18-32-17Z
        command: [
        "/bin/sh",
        "-ce",
        "source /vault/secrets/minio-secrets && /usr/bin/docker-entrypoint.sh server http://minio-{0...3}.minio-headless.default.svc.cluster.local/data" ]
        ports:
        - containerPort: 9000
          hostPort: 9000
```

Followed this article for vault setup https://learn.hashicorp.com/vault/kubernetes/sidecar

and here is a successful setup

```
~ kubectl get pods -l app=minio
NAME      READY   STATUS    RESTARTS   AGE
minio-0   2/2     Running   0          79s
minio-1   2/2     Running   0          94s
minio-2   2/2     Running   0          108s
minio-3   2/2     Running   0          2m4s
```

```
~ kubectl get deployments
NAME                   READY   UP-TO-DATE   AVAILABLE   AGE
vault-agent-injector   1/1     1            1           34m
```

```
~ kubectl get statefulsets
NAME    READY   AGE
minio   4/4     4m15s
vault   1/1     34m
```

**Comment by Srikanthshetty** [comment]
Thanks for the solution it worked for me with above entry point commands.

**Comment by akshayuppal3** [comment]
Thanks for explaining the steps in detail. I had a minor doubt. I was installing minio via helm chart and there are other charts in addition to minio and I create it as a 
dependency in chart.yaml
```
dependencies:
  - name: minio
    version: 8.0.9
    repository: https://helm.min.io
```
I was trying to update value via values.yaml, based on the discussion above I was able to piece together this. 
```
minio:
  serviceAccount:
    create: true
    # Creating service account to allow it to authenticate with vault. This will be the 
    # service account for binding it with a policy within vault
    name: minio-app
.....
  # Adding the prometheus annotations will trigger autodiscovery of the Prometheus scraper
  podAnnotations:
    ....
    # annotations for vault side car injection
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/agent-inject-secret-minio-secrets: "kv/data/azure-blob"
    vault.hashicorp.com/role: "minio-app"
    vault.hashicorp.com/agent-inject-template-minio-secrets: |
      {{- with secret "internal/data/minio/config" -}}
          export MINIO_ACCESS_KEY="{{ .Data.data.USERNAME }}"
          export MINIO_SECRET_KEY="{{ .Data.data.PASSWORD }}"
      {{- end -}}

  extraArgs: [
      "/bin/sh",
      "-ce",
      "source /vault/secrets/minio-secrets" ]
```

Now my question was if we don't set the values of access and the secret key would they be generated and overwriting the defaults?? As mentioned here: https://github.com/minio/charts/blob/master/minio/values.yaml#L67
